### ISSUE TITLE
Document FluentMigrator's Dependencies

### ISSUE THREAD

**Issue by mFingers** [fsharp/FAKE#1002]
I can submit a PR for a change in the documentation, but before I do, I wanted to make sure that it's warranted (read: make sure I'm not crazy).

In order for me to get FluentMigrator to work in my FAKE script, I had to reference [FluentMigrator.Runner](https://www.nuget.org/packages/FluentMigrator.Runner), **and also** have [FluentMigrator.Tools](https://www.nuget.org/packages/FluentMigrator.Tools) downloaded to my machine.

In the [FluentMigrator sample](https://github.com/fsharp/FAKE/blob/master/src/app/Fake.FluentMigrator/Sample/Sample.fsx), it shows the reference to the "Runner".  I only knew that I needed "Tools" when I tried to narrow down why the migration wasn't working, and tried without it being installed.

Furthermore, each library needs to reference the _exact same version_ of FluentMigrator.  The symptom I had was that the migration step worked without error, but only the VersionInfo table was created in the database.  I found [this](http://stackoverflow.com/a/29832877) on StackOverflow, and started looking at the dependencies.

Let me know if documenting this is a good idea - at least in the interim?  Preferably, FAKE.FluentMigrator should probably take a dependency on the other two libraries.

**Comment by dsyme** [comment]
@mFingers yes, please submit a doc update for this
