### ISSUE TITLE
NUnit 3 console support

### ISSUE THREAD

**Issue by dlsteuer** [fsharp/FAKE#1010]
NUnit 3 has just been released and the options to the console runner (now called nunit3-console.exe) have been changed.

Some examples of changed options are:
* -nologo has changed to -noheader
* -noshadow has changed to -shadowcopy and the semantics of it are inverted
* -labels has changed to require a value -labels=VALUE (Off, On, All)

Also it appears the output xml format has changed, but can be forced into nunit2 format with an option.

**Comment by 7sharp9** [comment]
This breaks existing build scripts as nunit-console.exe no longer exists, so when NUnit tasks are executed you get a file not found  :-(

**Comment by forki** [comment]
yes you need to do "nuget NUnit ~> 2" in your dependencies file.
The FAKE support is only for NUnit 2.x - until someone writes a new helper or somehow detects the version and does some magic.

**Comment by 7sharp9** [comment]
Yeah a lot of scripts just take the latest, like projectscaffold etc

**Comment by forki** [comment]
yeah bad timing ;-)

**Comment by neoeinstein** [comment]
This seams like a prime opportunity for me to give the NUnit runner the same treatment I gave XUnit. I'll take a swing through this over the weekend.

**Comment by fstaffa** [comment]
Created NUnit 3 support, PR is here: #1064

**Comment by aprooks** [comment]
@forki should this issue be closed due to #1064 merge?
