### ISSUE TITLE
Allow working dir in ZipHelper ZipOfIncludes

### ISSUE THREAD

**Issue by Steinblock** [fsharp/FAKE#1014]
http://fsharp.github.io/FAKE/apidocs/fake-ziphelper.html

After I build my project I have the following directory structure

> ci\build\project1 (contains all files for project 1)
> ci\build\project2 (contains all files for project 2)
> ci\build\project3\sub\dir (contains all files for project 3)

Now I want to create a zip file named project-version.zip with directories projec1 and project2

```
Target "Zip" (fun _ ->
    [   "project1", !! "ci/build/project1/**/*"
        "project2", !! "ci/build/project2/**/*"
        "project3", !! "ci/build/project3/sub/dir/**/*"
    ]
    |> ZipOfIncludes (sprintf @"ci/deploy/project.%s.zip" buildVersion)
)
```

However, this would place all files from project 1 in the zip folder `ci\build\project1` instead of `project1`

The `CreateZip` function contains a parameter working dir `///  - `workingDir` - The relative dir of the zip files. Use this parameter to influence directory structure within zip file.` which I would need to change this behaviour but `ZipOfIncludes` doesn't . It would be great to allow to define this per include (since project 3 in this example is even in a deeper structure.

So I want to write this:

```
Target "Zip" (fun _ ->
    [   "project1", "ci/build/project1",  !! "ci/build/project1/**/*"
        "project2",  !! "ci/build/project2/**/*" // allow ommiting working directory to maintain backward compability
        "project3", "ci/build/project3/sub/dir", !! "ci/build/project3/sub/dir/**/*"
    ]
    |> ZipOfIncludes (sprintf @"ci/deploy/project.%s.zip" buildVersion)
)
```

**Comment by matthid** [comment]
Fake 5 will have some helpers to be able to write:

```fsharp
Target "Zip" (fun _ ->
    [   !! "ci/build/project1/**/*"
            |> Zip.FilesAsSpecs "ci/build/project1"
            |> Zip.MoveToFolder "project1"
        !! "ci/build/project2/**/*"
            |> Zip.FilesAsSpecs "ci/build/project2"
            |> Zip.MoveToFolder "project2"
        !! "ci/build/project3/sub/dir/**/*"
            |> Zip.FilesAsSpecs "ci/build/project3"
            |> Zip.MoveToFolder "project3"
    ]
    |> Seq.concat
    |> Zip.ZipSpec (sprintf @"ci/deploy/project.%s.zip" buildVersion)
)
```

https://github.com/fsharp/FAKE/pull/1781
