### ISSUE TITLE
MSTest helper /detail support

### ISSUE THREAD

**Issue by Steinblock** [fsharp/FAKE#1016]
I am using fake to build my project from gitlab-ci
I would like to run my tests with `mstest /testcontainer:MyProject.Tests.dll /detail:errormessage` to see not only that a test has failed but also the message in the build logs.

Currently the [/detail switch](https://msdn.microsoft.com/library/ms182489.aspx#detail) is not supported by fake, it would be great to defile:

```
Target "Test" (fun _ ->
    !! (testDir + "**/*.Tests.dll") 
      |> MSTest (fun p -> 
        { p with 
            Details = ["errormessage", "duration"] })
)
```

Please not that `/details` can be used multiple times, so the above should translate to `mstest.exe /testcontainer:MyProject.Tests.dll /detail:errormessage /detail:duration`

**Comment by forki** [comment]
Please submit a pull request
