### ISSUE TITLE
isMacOS misbehaves

### ISSUE THREAD

**Issue by albertjan** [fsharp/FAKE#1019]
```
trace (sprintf "Mac: %b" isMacOS)
trace (sprintf "Plat: %O" Environment.OSVersion.Platform)
trace (sprintf "ID: %O" PlatformID.MacOSX)
```

returns:

```
Mac: false
Plat: Unix
ID: MacOSX
```

mono version:

```
Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Tue Oct  6 11:27:49 PDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

on Yosemite

tried FAKE 4.9.2 and 4.9.3

**Comment by albertjan** [comment]
This is probably a mono issue, but they don't appear to want to fix it. I'm surprised no one else ran into this.

**Comment by inosik** [comment]
Looking at the [source of System.Environment](https://github.com/mono/mono/blob/4504107/mcs/class/corlib/System/Environment.cs#L233) and commit history, it seems it never actually worked. Maybe we should copy the [code](https://github.com/Microsoft/vscode-mono-debug/blob/8a53868/src/common/Utilities.cs#L35) from the Mono debugger for VS Code.

**Comment by forki** [comment]
PR welcome ;-)

2015-12-17 17:54 GMT+01:00 Ilja Nosik <notifications@github.com>:
