### ISSUE TITLE
FAKE Invoking Powershell does not execute anything

### ISSUE THREAD

**Issue by devfunkd** [fsharp/FAKE#1023]
Trying to run a powershell script using F# FAKE but nothing happens... there are no errors, the target loads but nothing actually is run.

```
// include Fake lib
#r "packages/FAKE/tools/FakeLib.dll"
#r "System.Management.Automation"

open System
open System.IO
open System.Diagnostics
open System.Management.Automation

    Target "Powershell" <| fun _ ->
    PowerShell.Create()
      .AddScript("& 'test.ps1'")
      .Invoke()
      |> Seq.iter (printfn "%O")

// Dependencies
"Clean"
  ==> "Powershell"

// start build
RunTargetOrDefault "Powershell"
```

Am I missing something? Without any error I am not sure what the issue is.

This is the powershell script I am testing with, FAKE does nothing.

```
New-Item c:\AnEmptyFile.txt -ItemType file
```

Source: http://stackoverflow.com/questions/34006281/f-run-powershell-script-as-target

**Comment by inosik** [comment]
I tried this in FSI 8cpuld not find the assembly in a C# project) and it worked for me, after I changed the path to the script to an absolute one. It seems that the `AddScript` method uses some weird path to look for the script, it's not the current working directory.

**Comment by matthid** [comment]
It looks like this is something external
