### ISSUE TITLE
FileIncludes.IsMatch only works on absolute paths

### ISSUE THREAD

**Issue by fsoikin** [fsharp/FAKE#1029]
Consider this perfectly reasonable script:

```
Target "CopyAllImages" <| fun _ ->
   let images = 
      !! "**/*.jpg"
      ++ "**/*.png"
      ++ "**/*.gif"

   CopyDir "imagesDir" "sourceDir" images.IsMatch
```

This script will copy no files, because `images.IsMatch "sourceDir/whatever/flower.jpg"` will return `false`, because `"sourceDir/whatever/flower.jpg"` is not an absolute path.

The following will work, of course:

```
   CopyDir "imagesDir" "sourceDir" (FullName >> images.IsMatch)
```

But this seems like an inconsistency: either `CopyDir` should pass full paths to the predicate, or `IsMatch` should work for relative ones. And since the former may be a breaking change, I think the latter should happen.

**Comment by matthid** [comment]
Yes I agree, next release will match relative paths here as well
