### ISSUE TITLE
WiX Helper: Minimal working example + some refactorings

### ISSUE THREAD

**Issue by DigitalFlow** [fsharp/FAKE#1030]
Hey all,

I recently saw in an issue, that someone had problems using the WiX helper.
Thus I would like to contribute a minimal working example that folks can adjust to their needs.
Where would be the right place for submitting this? Maybe on some of the help pages?
In addition to that, I looked over the code again and found that some methods were not as good as they could be, but for changing those I would have to adjust some types.

@forki: Do you think I can just adjust these types, or how do we handle such cases?

Kind Regards

**Comment by forki** [comment]
yes please create copies of the types and mark the old ones obsolete.

**Comment by DigitalFlow** [comment]
Hey @forki,

Do I have to change something so that the minimal working example for WiX shows up on the API page?

Kind Regards

**Comment by forki** [comment]
Can you reference the lines that you mean?

**Comment by DigitalFlow** [comment]
I created a /help/wix.md file with a minimal working example for explaining how to use the WiXhelper.
Unfortunately it does not show up on fsharp.github.io/fake.

**Comment by forki** [comment]
did you link it from

https://github.com/fsharp/FAKE/blob/master/help/templates/template.cshtml
https://github.com/fsharp/FAKE/blob/master/help/literate/templates/template-file.html

**Comment by DigitalFlow** [comment]
Ok so that was missing, will edit, thanks a lot.
