### ISSUE TITLE
SquirrelHelper.fs example does not work properly

### ISSUE THREAD

**Issue by thebrianlopez** [fsharp/FAKE#1031]
[SquirrelHelper.fs#L122](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/SquirrelHelper.fs#L122) contains sample usage of *SquirrelPack* however the example in the docs is not working for me.

build.fsx
```
--line 84--
Target "CreateSquirrelPackage" (fun _ ->
    SquirrelPack (fun p -> {p with WorkingDir = "./tmp"}) "./my.nuget"
)
--line 88--
```
cli output
```
C:\code\user\.net45code>"packages\FAKE\tools\Fake.exe" build.fsx

F# Interactive for F# 4.0 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\code\user\.net45code\build.fsx]



build.fsx(86,49): error FS0001: This expression was expected to have type
    string option
but here has type
    string


```
Running the executable directly allow the command to complete successfully. 

Is the example in SquirrelHelper.fs incorrect?

**Comment by forki** [comment]
maybe it changed. PR to docs would be appreciated

**Comment by thebrianlopez** [comment]
ok , thanks for the quick response
