### ISSUE TITLE
MSBuildHelper BuildWebsite fails with invalid OutDir path

### ISSUE THREAD

**Issue by reidev275** [fsharp/FAKE#1032]
This happens because of the `prefix` code in BuildWebsite https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L435.

My `outputPath`s are local file paths like `c:\deploys\artifacts` so the existing ../ prefix turns my output paths into `../../c:\deploys\artifacts`

If I switch the `prefix` code to check if the path is rooted the build works.  

```
let prefix = if Path.IsPathRooted outputPath
             then ""
             else (String.replicate diff "../")
```

I may be missing something with the initial intent of the prefix code that would break with this suggested change though.  

@forki since you had the initial commit on this line can you help determine whether my suggestion helps or hurts?

**Comment by matthid** [comment]
Seems to be fixed.
