### ISSUE TITLE
issue following compiling fsharp in fake instructions

### ISSUE THREAD

**Issue by mooreniemi** [fsharp/FAKE#1037]
Using http://fsharp.github.io/FAKE/fsc.html

```fsharp
Target "Something.dll" (fun _ ->
  !! "src/**/*.fs"
  |> Fsc (fun p ->
           { p with Output = "Something.dll"
                    FscTarget = Library })
)
```

The `!! "src/**/*.fs"` returns a type error for me:

> Type mismatch. Expecting a `FileIncludes -> unit`     but given a `string list -> unit`     The type 'FileI    ncludes' does not match the type 'string list'.

How can I translate the `!!` command into the expected type?

**Comment by inosik** [comment]
`FileIncludes` implements `string seq` (`IEnumerable<string>` in C# world), and you can convert it using `List.ofSeq`.

Probably this won't work right, because in F# the order of the files matters. I think we should update the docs.

**Comment by mooreniemi** [comment]
Looks like I'm not the only one?

http://stackoverflow.com/questions/34067617/how-do-i-create-a-joined-string-from-fileincludes

**Comment by DavidTheBugWriter** [comment]
You can do this:
    !! "src/**/*.fs"
    |> Seq.toList
    |> Fsc (fun p ->
