### ISSUE TITLE
Not throwing invalidArg from various helpers when arguments are invalid

### ISSUE THREAD

**Issue by BlueHatbRit** [fsharp/FAKE#1041]
My team and I just spent the past few weeks struggling with some iOS Build issues through the XamarinHelper, after a long time of assuming we had certificate or environment issues it turned out that our configurations in our FAKE scripts were in correct. We tried to pass in something that was obviously not valid into the Configuration parameter and it seemed to thus be defaulting to "Debug" or for some reason passing through the invalid parameters which were being switched to "Debug" by XBuild.

I was looking through the code and can't find anywhere that we validate the parameters passed into iOSBuild. I had a look through some more issues and found #862 which is from someone having the same issue as us and still had no resolved answer.

Before I go ahead and make a pull request, I was wondering if there is a reason that the parameters aren't being validated when passed in and throwing some sort of invalidArg exception. Alternatively is there a more preferred method of validating parameters that may be being used elsewhere in the code? I've had a look and can't really seem to find any examples.

**Comment by bentayloruk** [comment]
@BlueHatbRit what value did you put in the `Configuration` parameter?  I'm not familiar with the `XamarinHelper`, but it looks like `Configuration` is a string, that is defaulted to `Debug`.  Without writing code to look for valid configurations in the proj files, you could probably check for "" and maybe alphanumerics (assuming configuration names are limited in that way).  Would be simple to [add here](https://github.com/fsharp/FAKE/blob/6a15fe01034c8bcfdc4d9b519dfc0cdbf1c0d9cd/src/app/FakeLib/XamarinHelper.fs#L99).

**Comment by BlueHatbRit** [comment]
We had a project configuration called `Ad-Hoc` but were passing in `AdHoc` which was causing it to default to `Debug`. I've just run one manually from the command line and found it's actually MSBuild that defaults over to a valid configuration. I'm assuming it's using the first configuration it can find in the csproj so you're right there would have to be a check to look at the proj file to search for a valid configuration.

Would this be something we'd want added to the project? I'm still somewhat new to F# but I'd be up for giving it a crack if it's something people thought would be beneficial.

**Comment by bentayloruk** [comment]
IMO it would be nice to have a function that could provide a list of valid Configuration and Platform combinations for a given project file.  You could then choose to use this if you want, early in your build script, to validate your values.  This would make it isolated and optional.  I'd be hesitant to suggest we add such a check to all functions similar to that in the `XamarinHelper`, because of the potential to break people.

Having said that, I know MSBuild is a complicated beast, so I don't know if this feasible.  I'll leave that to you :smile:.  Also, you should check and see if such a thing exists in FAKE already.

I'd say go for it.  Worst case, you get better at the wonderful F#!

**Comment by BlueHatbRit** [comment]
That sounds like a sensible approach, I'll give that a crack and see how it goes over the next few days. It would be good to have some sort of validation in there to prevent this issue for future users.

I've spent some time browsing through the code and docs and haven't found anything that does this so far but I will take another look just to make sure.

F# really is a great language even with only a few brief encounters with it so far.

**Comment by bentayloruk** [comment]
👍🏻

On Friday, 22 January 2016, Elliot Blackburn <notifications@github.com>
wrote:

> That sounds like a sensible approach, I'll give that a crack and see how
> it goes over the next few days. It would be good to have some sort of
> validation in there to prevent this issue for future users.
>
> I've spent some time browsing through the code and docs and haven't found
> anything that does this so far but I will take another look just to make
> sure.
>
> F# really is a great language even with only a few brief encounters with
> it so far.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fsharp/FAKE/issues/1041#issuecomment-173873707>.
>


-- 
Ben
