### ISSUE TITLE
SignToolHelper not available in Fake script

### ISSUE THREAD

**Issue by pdfforge** [fsharp/FAKE#1045]
Disclaimer: I am completely new to FAKE and just performing my first steps, so I might be missing something important or obvious

I am trying to access the SignToolHelper from the build script. For some reason, SignTool is available, but SignToolHelper is not.

From what I understand, it should be included though, as the SignToolHelper.fs lies just next to the SignTool.fs in the repo.

This is my attempt of a minimal (non-) working sample:
(The parameters for the SignToolHelper are wrong, of course)

     #r "packages/FAKE/tools/FakeLib.dll"
     
     open Fake
     
     // works
     Target "SignWorking" (fun _ ->
         !! "bin/myapp.exe"
           |> SignTool "packages/signtool" "Dev.pfx" "pass.txt"
     )
     
     // says "The value or constructor SignToolHelper is not defined"
     Target "SignWorking" (fun _ ->
         !! "bin/myapp.exe"
           |> SignToolHelper "packages/signtool" "Dev.pfx" "pass.txt"
     )

Any idea why this is not working is greatly appreciated

**Comment by forki** [comment]
SignToolHelper is a module, not a function. The closest thing in C# is a namespace. So you can open that thing and use methods in it.

**Comment by pdfforge** [comment]
oh, yes, that's true, but SignToolHelper.Sign gives me "namespace SignToolHelper does not exist" as well. I now copied the contents of the SignToolHelper.fs locally an performaned a #load on that file an then I can access the module. Could it be that there is a problem with that in FAKE 4.10.5?

With the local copy, I can call

     Sign "packages/signtool" signParams

Which, in return, makes it harder to pipe files into that, as they are wrapped inside the params

**Comment by inosik** [comment]
Just checked it, `FakeLib.fsproj` does not have a `<Compile ... />` node for the `SignToolHelper.fs` file. Seems that #535 added only the source file.

If we bring it in, is it a good idea to `[<AutoOpen>]` it? And should we remove the old `SignHelper` then?

**Comment by pdfforge** [comment]
Thanks for pointing this out!

As for the [<AutoOpen>], I have no idea, but it seems to be used quite often among the project.

For the rest: I have created a pull request to fix this. I have removed the SignHelper there, as the SignToolHelper contains a function that provides the same syntax as the SignHelper did.
