### ISSUE TITLE
Target Alias

### ISSUE THREAD

**Issue by pms1969** [fsharp/FAKE#1052]
Is there a way to alias a target in Fake?

For instance, 
    - I have a target called "UpdateNugetPackages", and I'd like to call it as "up"
    - I have a set of targets that I'd like to alias as 1 call. "ENV"==> "SOMETHINGELSE" ==> "LAST_THING" aliased as "doit"

for both these scenarios at present I use another target, set the build chain in there and pipe thru run. i.e.
Target "up" (fun _ -> "up" ==> "UpdateNugetPackages" |> Run)

It's not really an issue, but this method means I get 2 build summaries, 1 for the inside build chain, and then 1 for the alias.  It just looks a bit weird, and the alias thing kind of makes sense.

Thoughts?

**Comment by forki** [comment]
Target "up" (fun _ -> "up" ==> "UpdateNugetPackages" |> Run)

I don't think that's a good idea since it will mess with FAKE's internal target managment stuff.

Better:

    Target "up" DoNothing
    "UpdateNugetPackages" ==> "up"

for the second case:

    Target "doit" DoNothing
    "ENV" ==> "SOMETHINGELSE" ==> "LAST_THING" ==> "doit"

**Comment by pms1969** [comment]
Thanks.  

The problem for me is that I don't want LAST_THING to always be dependent on SOMETHINGELSE or ENV.  Is there a way of dealing with that?

I use the wrapper to prevent the chains from firing every time, and set up dynamic build chains for various calls.  It has worked well so far, but I appreciate that it's unsupported.  In my case, there are no target chains except those set up in the aliases.

I've had a rumage around the code, and have an idea for the alias.  If there's no current way to support  the requirement for the dependency chain to be transient in the way I describe above, I'll see if I can implement something and supply a pull request.

**Comment by forki** [comment]
Maybe you can use =?> which allows you to have conditional dependencies.

**Comment by pms1969** [comment]
possible, I hadn't thought of that, because I already have conditional dependencies depending on my context (alias).  That could get quite complicated quite quickly.  I've managed to make some changes.  I'll commit and give you a pull request.  look it over and if it's suitable, then good.  If not, no problem, I'm sure I can just keep my fork in sync with master and use the changes as they stand for my work.
