### ISSUE TITLE
Run multiple targets from the command line

### ISSUE THREAD

**Issue by arialdomartini** [fsharp/FAKE#1054]
It would be very nice to run multiple targets from the command line, like in

```
fake clean test
```

As far as I understood, this is not currently possible: the second argument, `test`, would be just ignored.

[Gradle supports it](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html), and so [does Ant](https://ant.apache.org/manual/running.html).

**Comment by Stift** [comment]
duplicate to #960

**Comment by piers7** [comment]
psake has this also. I miss it. When you have two tasks that can run independently, but sometimes you want to run them together (maybe they have an optional dependency relationship) this is much more convenient than having to explicitly define additional parent tasks (RunTaskAAndRunTaskB).

I grant you this is mostly used in build script testing. When you really want to do a 'build' or a 'build and test' you setup a dependency. But when if you are testing the build script, or using it as a simple command line front-end into a bunch of build-related functions, being able to cherry-pick more easily is quite useful I've found.

(I totally get that the bottom line here is that if I care enough, I should just implement it myself and raise a PR :-)
