### ISSUE TITLE
DotCover report and sendTeamCityDotNetCoverageImport

### ISSUE THREAD

**Issue by kerams** [fsharp/FAKE#1059]
According to the docs, this function sends dotcover, partcover, ncover and ncover3 reports to TC using `sendToTeamCity "##teamcity[importData type='dotNetCoverage' path='%s']"`. However, when I pass in my `DotCover.dcvr`, the coverage does not show up in TC. If I specify the exact tool using `sendToTeamCity "##teamcity[importData type='dotNetCoverage' tool='dotcover' path='%s']"`, it all works fine.
Do you think this is an issue with TeamCity or FAKE?

**Comment by bjartwolf** [comment]
I believe the dotcover mentioned in the first command is the one you get if you run the .dcvr through DotCoverReport to create an ndepend report file 
'''
Target "CreateDotCoverXmlReport" (fun _ ->
   DotCoverReport (fun p -> { p with 
                                Source = artifactsDir @@ "MSTest.dcvr"
                                Output = artifactsDir @@ "dotCoverReport.xml"
                                ReportType = DotCoverReportType.NDependXml} ) false)
'''

I think we should clarify this in the docs and make a special .dcvr helper to do the dcvr import. I struggled with this as well.

**Comment by kerams** [comment]
Thanks for clearing this up. Is it only the importing of the entire snapshot (as produced by `DotCoverNUnit`) that requires `tool='dotcover'`?

**Comment by bjartwolf** [comment]
That is my understanding, at least. And I think that is easier to do, then the CreateDotCoverXmlReport should be unnescessary.

**Comment by baronfel** [comment]
I just got bit by this today as well.  I'd be up for writing a PR that obsoletes this function, and creates a new function that provides a DU for the type of coverage tool, if people would use that.
