### ISSUE TITLE
Print a warning if FAKE is unable to parse the new style command line args

### ISSUE THREAD

**Issue by bentayloruk** [fsharp/FAKE#1082]
I just noticed a couple of issues related to people using a mix of old and new style command line arguments (e.g. https://github.com/fsharp/FAKE/issues/1072 and https://github.com/fsharp/FAKE/issues/594).  This is understandable, so perhaps it would make sense for us to print a warning when the [Argu parse fails and we fall back on the old style](https://github.com/fsharp/FAKE/blob/master/src/app/FAKE/Program.fs#L128).  Currently we do this silently, which is not very helpful.  I wrote this originally, and this was intentional in order not to disturb existing scripts.  However, perhaps it now makes sense to at least show a warning.

I'm happy to do this work, but thought I would raise it here first to see if anyone objects to it.

**Comment by bentayloruk** [comment]
I just noticed that the [Running Targets](http://fsharp.github.io/FAKE/specifictargets.html) documentation lists the `target=Build` syntax.  I think this might be causing some of the confusion, as `target=` is not really needed any more AFAIK, because you can just say `fake MyTargetName`.  However, when `target=MyTargetName` is mixed with new style command line options, we'll get failures.

**Comment by bentayloruk** [comment]
@forki I will put a warning in, but I think we should remove the old style, the next time FAKE has breaking changes.  It's better that everyone moves over, as the warning will easily be missed in a script of any size.  What do you think?

**Comment by forki** [comment]
Yeah probably
