### ISSUE TITLE
No argument escaping in DotCover

### ISSUE THREAD

**Issue by vbfox** [fsharp/FAKE#1091]
The arguments passed to `dotcover.exe` in `DotCover.DotCoverNUnit3` function aren't escaped at all, just placed between quotes (I saw the problem in `DotCover.DotCoverNUnit3` but I suspect that it's a lot more general in the codebase)

The problem in this specific case is the `/TargetArguments=` one as it contain arguments that should be passed to NUnit itself and contain `"` characters. The argument string generated currently look like that :

> "cover" "/TargetExecutable=c:\Code\rfq-hub\packages\NUnit.Console\tools\nunit3-console.exe" "/TargetArguments="--noheader" "--where=cat != 'SmokeTests' and cat != 'ExternalSystems' and cat != 'UI'" "--framework=v4.5" "--timeout=3600000" "--result=c:\Code\rfq-hub\nunit-report.xml" "c:\Code\rfq-hub\bin\UnitTests\Debug\UnitTests.dll" "c:\Code\rfq-hub\bin\FSharpUnitTests\Debug\FSharpUnitTests.dll"" "/Filters=+:*;-:Infragistics*;-:TestStack*;-:Nest*;-:Gallio*;-:Dapper*;-:CsvHelper*;-:IntegrationTests*;-:UnitTests*;-:TestUtils*;-:Ids.RfqHub.SmokeTests*" "/Output=c:\Code\rfq-hub\NUnitDotCover.snapshot"

But standard windows argument parsing make `--noheader"` ends the argument that began with  `"/TargetArguments=` so an argument starting with `"--where=cat` is seen by dotCover.exe that complains with : 

> JetBrains dotCover Console Runner 10.0.2. Build 104.0.20151218.125453
> Copyright (c) 2009-2016 JetBrains s.r.o. All rights reserved.
> Failed to parse xml parameters
> Type 'dotCover help' for usage.

(I decompiled dotCover parser and the "xml" part is due that all non "key=value" arguments after the first one -- "cover" in this case -- are considered as some kind of xml formatted arguments)

Ugly hack
------------

To fix in in our build scripts I followed http://www.daviddeley.com/autohotkey/parameters/parameters.htm#WINARGV and implemented windows command line escape, then passed the whole command line as a "custom" parameter.

It's ugly but it works : https://gist.github.com/vbfox/ba82be78a16b45ed27ad

PR ?
------

Now come the question of the PR, what should it do as there are a few quirks to argument escaping :

On windows argument parsing is done by the target program. The code in my gist is valid for executables using msvcr command line parsing, and most windows program use it or have it re-implemented their way but it isn't the only one.

On mono + unix it's implementing a slightly different parsing (in [split_cmdline](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/eglib/src/gshell.c#L32)) that is easier to escape but slightly different (my code will work most of the time as-is except if the input contains \\` or \$). The parsing is implemented by mono because on unix programs are started with an array of arguments and don't do the parsing themselves.

A PR would need to take at least mono into account in addition to msvcrt.

Also what should be the scope of the change ? Should the PR only include an escaping helper and be applied just to `TargetArguments` for `DotCoverNunit` or should I propose the `CmdLine` module and use it for the whole command line ?

**Comment by bjartwolf** [comment]
I struggled with something similar, but not sure if it is entirely related, in doing the same for MSTest. I found it works for us by just not quoting everything. Not claiming that this is the right way to do it... 
https://github.com/fsharp/FAKE/pull/972/files

**Comment by vbfox** [comment]
@bjartwolf Yes it might be possible to side-step it in my very specific case.
But in your example if `parameters.ResultsDir` contains space the arguments build will be wrong no ?

**Comment by bjartwolf** [comment]
@vbfox Yes. I am pretty sure there are bugs related to this. The implementations all work a little bit different for different dotcover. Just looked at it again, and I think the MSTest one iterates over the .dll's causing all but the latest snapshot to be overwritten. The Xunit2 implementation is also a bit different. Definitely worth having a proper look at. My feeling was that it was written to work for one test assembly, and it failed when I tried to use it in our project, but I don't claim to have fixed this properly, I honestly found it hard to reason about these nested arguments being passed around and quoted... I have spaces in the path for targetexecutable, but you are probably right about what goes into the TargetArguments.

```
C:\Users\n24733\Source\Repos\PS.Frontend\Worker\Nrk.Programspiller.ScoresUpdater\tools\dotCoverConsoleRunner.2.5.574.60\
dotCover.exe "cover" "/TargetExecutable=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\mstest.exe" "/Ta
rgetArguments=/testcontainer:C:\Users\n24733\Source\Repos\PS.Frontend\Worker\Nrk.Programspiller.ScoresUpdater\test\Nrk.P
rogramspiller.ScoresApi.UnitTests.dll /testcontainer:C:\Users\n24733\Source\Repos\PS.Frontend\Worker\Nrk.Programspiller.
ScoresUpdater\test\Nrk.Programspiller.ScoresUpdaterTests.dll /resultsfile:./artifacts/\20160125-103428.24.trx" "/Filters
=+:Nrk.Programspiller.Scores*;-:Nrk.Programspiller.Common*;-:*Test*" "/AttributeFilters=-:Generated*-:System.Diagnostics
.CodeAnalysis.ExcludeFromCodeCoverageAttribute" "/Output=./artifacts/MSTest.dcvr"
```
