### ISSUE TITLE
Restoring paket.dependencies using FAKE

### ISSUE THREAD

**Issue by mvkra** [fsharp/FAKE#1095]
Might be just me who can't find how to do it but I'm after the ability to do a "paket restore" from FAKE. There's lots of helpers on how to do so in Nuget but in the Paket module there only seems to be the ability to create and push packages.

There's an assumption that I'm getting FAKE via Paket and that paket.dependencies file is the same as required for the solution I'm building. In my case FAKE is already retrieved from elsewhere and I want to restore the paket.dependencies for a solution before building it.

Any help would be appreciated - thanks.

**Comment by forki** [comment]
I'm not against such an helper. Should be straight forward to build that. Give it a try.

**Comment by mvkra** [comment]
There you go. Let me know if there is any concerns.
