### ISSUE TITLE
TeamCity should build with nodereuse-false as default?

### ISSUE THREAD

**Issue by bjartwolf** [fsharp/FAKE#1109]
As commented on http://theimowski.com/blog/2016/01-18-continuous-delivery-with-fake-paket-and-teamcity/index.html I think running with 
```
MSBuildDefaults <- { MSBuildDefaults with NodeReuse = false}
```
is the way to go on TeamCity, as for example the stylecop.dll's will be locked for, I think, 60 seconds if nodereuse is on. This causing clean to fail if the next build comes within 60 seconds of the previous completing. This caused issues for us and we have been running with node-reuse off in all our build scripts for months now.

**Comment by theimowski** [comment]
maybe another option could be if you checked the "clean checkout directory" before building on TeamCity?

**Comment by bjartwolf** [comment]
Yes. But I'm not sure how to detect that. Have to look into it and check if this is an environment variable we can read in Fake.

**Comment by forki** [comment]
MSBuildDefaults <- { MSBuildDefaults with NodeReuse = false}

we could set this automatically when we detect TC as host

**Comment by bjartwolf** [comment]
That is what I was thinking, I'll send a PR in the not to distant future.
