### ISSUE TITLE
Paket.Pack does not include project dependencies (dll) to the result nupkg

### ISSUE THREAD

**Issue by ar3cka** [fsharp/FAKE#1111]
Paket version: 2.47.1.0

**Comment by forki** [comment]
did you set the param? see http://fsprojects.github.io/Paket/paket-pack.html#Including-Reference-Projects

**Comment by ar3cka** [comment]
I can't find it in corresponsing fake target.

**Comment by forki** [comment]
Yes but that's easy to solve ;-)

Please send a pull request and I will merge asap
