### ISSUE TITLE
Feature request: Please create the script cache in the .fake folder below the script

### ISSUE THREAD

**Issue by pms1969** [fsharp/FAKE#1114]
If you call your script from various different places, you end up with .fake folders all over your hard drive.  So I'd like to propose that the .fake cache folder is created under the directory where the script resides, not the directory from where it is called.

**Comment by forki** [comment]
Mhm I thought we already do that.

**Comment by pms1969** [comment]
nope, just rechecked.  certainly the case for 4.17.0

**Comment by ChrSteinert** [comment]
The relevant line seems to be located here: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L504

**Comment by forki** [comment]
fixed in #1250
