### ISSUE TITLE
Feature Request: Attribute type in AssemblyInfoFile to have optional value parameter

### ISSUE THREAD

**Issue by kellerd** [fsharp/FAKE#1115]
Some attributes don't have any parameters, but can be quite useful.

```[<assembly: ExtensionAttribute()>]```, enables VB 14 (from VS2015) to use CSharp style extensions.

Currently https://github.com/fsharp/FAKE/src/app/FakeLib/AssemblyInfoFile.fs only allows empty strings

Repro: https://github.com/kellerd/Chessie, https://github.com/kellerd/Chessie/blob/master/build.fsx
Generates: https://github.com/kellerd/Chessie/blob/master/src/Chessie/AssemblyInfo.fs

Removing this attribute, and the VB tests won't compile. Adding ```[<assembly: ExtensionAttribute()>]``` will allow VB to use the CSharp style extensions.

**Comment by inosik** [comment]
You can use the constructor of the `AssemblyInfoFile.Attribute` type directly.

```fs
Target "Info" (fun _ ->
    [Attribute("Extension", "", "System.Runtime.CompilerServices")]
    |> CreateFSharpAssemblyInfo "AssemblyInfo.fs"
)
```
The above script generates this:
```fs
namespace System
open System.Runtime.CompilerServices

[<assembly: ExtensionAttribute()>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "LocalBuild"
```

**Comment by kellerd** [comment]
Knew it was something I was missing.
