### ISSUE TITLE
Cannot pass build param

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1121]
I feel I must be making an embarrassingly obvious mistake, but I can't figure out how to pass build params any more. I swear I used to just do this:

```
FAKE script.fsx whatever=value
```

But now when I try this I get:

```
Error parsing command line arguments.  You have a mistake in your args, or are using the pre-2.1.8 argument style:
Exception Message:unrecognized argument: '--whatever'.
```

Has the syntax changed? All I can find on the Interwebs seems to confirm that I'm doing it the right way. What's going on here?

Using 4.17.1.

**Comment by kentcb** [comment]
Hmm, I _think_ I've stumbled on the solution via [this](https://github.com/fsharp/FAKE/issues/594).

Is this right?

```
FAKE script.fsx -ev whatever value
```

Why is it so hard to find an example of this? Shouldn't the docs for `getBuildParamOrDefault` make this really clear? Even the [command line reference](http://fsharp.github.io/FAKE/commandline.html) doesn't help to relate this back to `getBuildParamOrDefault`...

**Comment by bentayloruk** [comment]
@kentcb your previous usage was probably working.  However, FAKE supports an "old" and "new" style CLI and I recently added a warning, which you are seeing here, that the syntax you are using is the old style and fails new style parsing.

Sorry for your frustration.  I know this is confusing and I'm working to clear things up.  See https://github.com/fsharp/FAKE/pull/1090 for details.

The documentation is a really good idea.  Could you make the edits you think would clear this up?

**Comment by dsyme** [comment]
Closing old inactive issue. Please send a PR to address this if it continues to be a problem
