### ISSUE TITLE
FSI arg --debug+ does not appear to work with caching on

### ISSUE THREAD

**Issue by bentayloruk** [fsharp/FAKE#1134]
I was just trying to debug a build script, with a good old `Debugger.Break()`, but was unable to see any useful information in the debugger.

My command line looks like this:

`--fsiargs --debug+ --optimize- BuildCs.fsx --platform "AnyCpu" --configuration "Release"`

You can see the debug and optimize flags.

I got latest on FAKE and stepped through this.  I can see that the FSI args are being correctly parsed, and they are used in the [`FsiEvaluationSession.Create` call](https://github.com/matthid/Yaaf.FSharp.Scripting/blob/develop/src/source/Yaaf.FSharp.Scripting/YaafFSharpScripting.fs#L1058).  However, they do not seem to work, when the script is cached.

If I run the command line with `--nocache` prepended, it all works as expected in the debugger. i.e.
 
`--nocache --fsiargs --debug+ --optimize- BuildCs.fsx --platform "AnyCpu" --configuration "Release"`

Therefore, I'm guessing the caching approach is breaking the `--debug+` option (and possibly others?).  Unfortunately, I'm not super familiar with the FSI session/caching code, so was hoping @matthid might have an idea?  For now, I'll workaround with `--nocache`.

**Comment by bentayloruk** [comment]
OK, what I described is not happening across the board.  The `--nocache` is fixing the debugging *when I am debugging my script with the FAKE solution*, but when I switch back to running my script with the release FAKE binaries, the `--nocache` arg does not fix the issue.  Will look again.

**Comment by matthid** [comment]
You are correct, debugging with the release binaries is no fun (at least I could never make it work when I needed it). In regards to the cache, we currently throw away the [pdb file](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FSIHelper.fs#L371)... and should probably save it when the `--debug` flag is given?

**Comment by bentayloruk** [comment]
Thanks for the info @matthid.  Not really sure what we should do here.  Guess we have a couple of issues:

1.  Is debugging a FAKE build script in VS, supposed to work?  If yes, what can we do about that.  *Probably for another issue*.
2.  Which FSI options are not respected when caching is used, and what do we do about it?

With regards to the `pdb`.  Why is it thrown away currently?  Could you just leave it if it's generated?  Why they need to explicitly check for the `--debug+` arg?

**Comment by dsyme** [comment]
Closing old inactive issue. Please send a PR to address this if it continues to be a problem
