### ISSUE TITLE
FAKE for .NET 4.5

### ISSUE THREAD

**Issue by sergey-tihon** [fsharp/FAKE#1152]
There is an interesting case [batch-toolkit](https://github.com/johnazariah/batch-toolkit)
The project is compiler for .NET 4.5 and depend of `Microsoft.Bcl` that does not have dlls for `net45` (they are part of framework already) but have dlls for `net40`.

When we execute FAKE (.NET 4.0) and ask to generate reference docs it fails because cannot load dlls.
![image](https://cloud.githubusercontent.com/assets/1197905/13347854/2ea3016a-dc81-11e5-8bd0-c5ef569ee307.png)
If we artificially add all `net40` dirs to `libDirs`
![image](https://cloud.githubusercontent.com/assets/1197905/13347894/5bf3b75e-dc81-11e5-875e-7f02c64a7b58.png)
it also will not generate docs =(
![image](https://cloud.githubusercontent.com/assets/1197905/13347912/6be92694-dc81-11e5-9be6-95e042fcf9e8.png)

**Comment by sergey-tihon** [comment]
@johnazariah do we still need this?

**Comment by johnazariah** [comment]
No we do not. I was unable to close the issue though!

Thanks for everything, mate! :)
