### ISSUE TITLE
SemVerInfo.ToString doesn't match input

### ISSUE THREAD

**Issue by amazingant** [fsharp/FAKE#1154]
Given a release notes with version `2.9.75-beta2`, calling `notes.SemVer.ToString()` returns `2.9.75-beta` instead of `2.9.75-beta2`. Appears to be from [here](https://github.com/fsharp/FAKE/blob/43c4800c5f132d2c2d6832a3a59232a64d83d4c0/src/app/FakeLib/SemVerHelper.fs#L47). Not sure if it makes a difference, but Paket's `SemVerInfo` typedef contains an `Original` field that contains the original text that was parsed; FAKE's `SemVerInfo` could do the same maybe?

**Comment by dsyme** [comment]
fixed
