### ISSUE TITLE
FscHelper.FscParam.Target constructor conflicts with TargetHelper.Target when both modules are open

### ISSUE THREAD

**Issue by fsoikin** [fsharp/FAKE#1155]
[This constructor](https://github.com/fsharp/FAKE/commit/c544eb7a4a567a91ff0c9f05dab1b2d00458b54e#diff-87a104fe2888ff19de45871a96b8750eR244)

**Reproducing script:**

```
#r @"packages/build/FAKE/tools/FakeLib.dll"
open Fake
open Fake.FscHelper

Target "a" (fun _ -> 
  ["a.fs"] |> Compile [])
```

This yields an error "_This value is not a function and cannot be applied_" referring to the expression `Target "a"`, which is caused by the identifier `Target` being resolved to mean `FscHelper.FscParam.Target` instead of `TargetHelper.Target`.

**Comment by fsoikin** [comment]
And here is the first victim: http://stackoverflow.com/questions/35737192/fake-error-when-trying-to-use-fake-fschelper/35737303#35737303

**Comment by cloudRoutine** [comment]
this is easily resolved by changing the order of the open statements
```fsharp
#r @"packages/FAKE/tools/FakeLib.dll"
open Fake.FscHelper
open Fake

Target "a" (fun _ -> 
  ["a.fs"] |> Compile [])
```

**Comment by fsoikin** [comment]
1. Doesn't make it any less of an issue

2. [The docs](https://github.com/fsharp/FAKE/blob/master/help/fsc.md) show this order, so people would copy&paste it and get an error.

**Comment by cloudRoutine** [comment]
Good point about the docs, I submitted a PR to change it. 

Perhaps I was too optimistic to think that people would be able to easily handle this kind of name resolution issue :laughing:   

So what do you think should be done instead, change the name and if so to what?

I think it'd be overkill to add `[<RequireQualifiedAccess>]` to the DU

**Comment by fsoikin** [comment]
Why not just rename the constructor? Say, the way it was - `FscTarget`. Or maybe `FSharpTarget`. Or `CompileTarget`.

**Comment by cloudRoutine** [comment]
Calling it `FscTarget` would introduce a different name resolution issue that would break any code using the existing `FscTarget` 

The reason I chose those particular names for the `FscParams` cases was so that they would match the  compilation flags that fsc uses

```
                - OUTPUT FILES -
--out:<file>                   Name of the output file (Short form: -o)
--target:exe                   Build a console executable
--target:winexe                Build a Windows executable
--target:library               Build a library (Short form: -a)
--target:module                Build a module that can be added to another assembly
--delaysign[+|-]               Delay-sign the assembly using only the public portion of the strong name key
--doc:<file>                   Write the xmldoc of the assembly to the given file
--keyfile:<file>               Specify a strong name key file
--keycontainer:<string>        Specify a strong name key container
--platform:<string>            Limit which platforms this code can run on: x86, Itanium, x64, anycpu32bitpreferred, or anycpu.
                               The default is anycpu.
--nooptimizationdata           Only include optimization information essential for implementing inlined constructs. Inhibits
                               cross-module inlining but improves binary compatibility.
--nointerfacedata              Don't add a resource to the generated assembly containing F#-specific metadata
--sig:<file>                   Print the inferred interface of the assembly to a file


                - INPUT FILES -
--reference:<file>             Reference an assembly (Short form: -r)


                - RESOURCES -
--win32res:<file>              Specify a Win32 resource file (.res)
--win32manifest:<file>         Specify a Win32 manifest file
--nowin32manifest              Do not include the default Win32 manifest
--resource:<resinfo>           Embed the specified managed resource
--linkresource:<resinfo>       Link the specified resource to this assembly where the resinfo format is <file>[,<string
                               name>[,public|private]]


                - CODE GENERATION -
--debug[+|-]                   Emit debug information (Short form: -g)
--debug:{full|pdbonly}         Specify debugging type: full, pdbonly. ('full' is the default and enables attaching a debugger
                               to a running program).
--optimize[+|-]                Enable optimizations (Short form: -O)
--tailcalls[+|-]               Enable or disable tailcalls
--crossoptimize[+|-]           Enable or disable cross-module optimizations


                - ERRORS AND WARNINGS -
--warnaserror[+|-]             Report all warnings as errors
--warnaserror[+|-]:<warn;...>  Report specific warnings as errors
--warn:<n>                     Set a warning level (0-5)
--nowarn:<warn;...>            Disable specific warning messages
--warnon:<warn;...>            Enable specific warnings that may be off by default
--consolecolors[+|-]           Output warning and error messages in color


                - LANGUAGE -
--checked[+|-]                 Generate overflow checks
--define:<string>              Define conditional compilation symbols (Short form: -d)
--mlcompatibility              Ignore ML compatibility warnings


                - MISCELLANEOUS -
--nologo                       Suppress compiler copyright message
--help                         Display this usage message (Short form: -?)


                - ADVANCED -
--codepage:<n>                 Specify the codepage used to read source files
--utf8output                   Output messages in UTF-8 encoding
--fullpaths                    Output messages with fully qualified paths
--lib:<dir;...>                Specify a directory for the include path which is used to resolve source files and assemblies
                               (Short form: -I)
--baseaddress:<address>        Base address for the library to be built
--noframework                  Do not reference the default CLI assemblies by default
--standalone                   Statically link the F# library and all referenced DLLs that depend on it into the assembly
                               being generated
--staticlink:<file>            Statically link the given assembly and all referenced DLLs that depend on this assembly. Use an
                               assembly name e.g. mylib, not a DLL name.
--pdb:<string>                 Name the output debug file
--simpleresolution             Resolve assembly references using directory-based rules rather than MSBuild resolution
--highentropyva[+|-]           Enable high-entropy ASLR
--subsystemversion:<string>    Specify subsystem version of this assembly
--targetprofile:<string>       Specify target framework profile of this assembly. Valid values are mscorlib or netcore.
                               Default - mscorlib
--quotations-debug[+|-]        Emit debug information in quotations

```
granted not *every* single one matches, there are a few that are overloaded (e.g `debug`) and I added some new ones that work better with collections, but I think it's best to keep it as similar to what FSC uses as possible

**Comment by fsoikin** [comment]
Sure, as similar as possible, absolutely. But this is precisely the case where it's impossible.

**Comment by jchidley** [comment]
I came across this problem too.  I had followed the documentation and I wasn't using a code editor (just copy con for speed) so I was stumped for a time.  It was only when I opened build.fsx in Visual Studio that I spotted the name conflict.  As you wrote, it was simple enough to reorder the references and then fully qualify the names but it took a while.  Short term fix, adjust the documentation.

However, I have now run into a different problem: the compiler service just isn't working properly anyway.  

I get this error 
<code>
FSC with args:[|"-o"; "GettingStarted.dll"; "--target:library"; "--platform:anycpu"; "-g-";
  "GettingStarted.fs"|]
commandLineArgs (0,1)-(0,81) parameter error Unrecognized option: '-g-'
Running build failed.
Error:
Fsc: compile failed with exit code
</code>

with this input
<code>
Target "BuildLibrary" (fun _ ->
    trace "Building the library"
    ["GettingStarted.fs"]
    |> FscHelper.Compile [  FscParam.Target TargetType.Library
                            Platform AnyCpu
                            Debug false ]
)
</code>

I understand that I could use MSBuild but I am trying to keep everything very, very simple at the moment.  Just a library file, a script file and FAKE for building.

**Comment by fsoikin** [comment]
@jchidley: filed #1218.

**Comment by matthid** [comment]
We have this now over a year, so I'm closing this for now. But I agree that this is a sad collision, we should have removed it.
