### ISSUE TITLE
FscHelper documentation seems to be outdated

### ISSUE THREAD

**Issue by fsoikin** [fsharp/FAKE#1156]
[The documentation](https://github.com/fsharp/FAKE/blob/master/help/fsc.md) still refers to the `Fsc` function, which [seems to be obsolete](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FscHelper.fs#L154) according to the source code.

**Comment by cloudRoutine** [comment]
These kinds of issues could be caught easier if the docs were `.fsx` files instead of `.md` files, it might be worthwhile to change some of them.

**Comment by dsyme** [comment]
This appears to have been fixed at some point
