### ISSUE TITLE
SemVerHelper.ToString is missing prerelease number

### ISSUE THREAD

**Issue by davezych** [fsharp/FAKE#1157]
I'm using the `SemVer` prop of the `ReleaseNotesHelper`, and when I `ToString` it the output is missing the `Number` of the prerelease.

For instance, if I have a version of 

    1.0.0-alpha

it outputs 

    1.0.0-alpha 

which is correct. However if I have 

    1.0.0-alpha2

it only outputs

    1.0.0-alpha

Unless I'm misunderstanding something, I think it should have the prerelease number in the output.

**Comment by Stift** [comment]
seems to be duplicate of #1154

**Comment by davezych** [comment]
Yep. Closing in favor of #1154.
