### ISSUE TITLE
Should ILMergeHelper be `[<AutoOpen>]`? And a general question about Fake namespace pollution

### ISSUE THREAD

**Issue by cloudRoutine** [fsharp/FAKE#1158]
While working on fixing some name resolution issues involved with FscHelper and updating the docs I noticed another one with `Library` where it resolved to 
[`Fake.ILMergeHelper.TargetKind.Library`](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/ILMergeHelper.fs#L23-L26) instead of `FscParam.Library` 

Looking through the library it seems like `[<AutoOpen>]` has been used very liberally without even a namespace to constrain some of these modules.

Some other modules that could be stripped of `[<AutoOpen>]`

* [WiXHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/WiXHelper.fs)
* [FxCopHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/FXCopHelper.fs)
* [NCoverHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/NCoverHelper.fs)
* [MSIHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/MSIHelper.fs)
* [SpecFlowHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/SpecFlowHelper.fs)
* [RegAsmHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/RegAsmHelper.fs)
* [TeamCityRESTHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/TeamCityRESTHelper.fs)
* [SQLServerHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/Fake.SQL/SQLServerHelper.fs)
* [MSpecHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/UnitTest/MSpecHelper.fs)
* [IISHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/Fake.IIS/IISHelper.fs)
* [MageHelper](https://github.com/fsharp/FAKE/blob/448a0e59aa1381714d045bf81c3ab5692aad6259/src/app/FakeLib/MageHelper.fs)
* [TeamCityHelper](https://github.com/fsharp/FAKE/blob/7d609c841fbc01a66b95c605a89b0b8e4f1616dd/src/app/FakeLib/TeamCityHelper.fs)

Or better namespacing could be introduced to stop everything from polluting as soon as FAKE is opened.  (like how the modules in the `Git` namespace are setup)

**Comment by forki** [comment]
Using auto open everywhere is an old decision and we font do that anymore.

**Comment by cloudRoutine** [comment]
I noticed some of these files haven't been changed for anywhere from 1-5 years. Does this mean you're amenable to removing the `[<AutoOpen>]` attributes from them?

**Comment by forki** [comment]
actually I don't want to break stuff ;-)

2016-03-02 8:40 GMT+01:00 Jared Hester <notifications@github.com>:

**Comment by cloudRoutine** [comment]
maybe stow it for next major version?

**Comment by dsyme** [comment]
Closing as @forki said no
