### ISSUE TITLE
Support for Attributes with parameter-less constructors to AssemblyInfoFile

### ISSUE THREAD

**Issue by trondd** [fsharp/FAKE#1163]
We have a few internal attributes that are used in AssemblyInfo-files that don't take any constructor parameters, and as far as I can tell this does not work with `AssemblyInfoFile`. I looked into changing the `Value` member of `Attribute` type to an option type, but this would probably break tons of code out there. Any other ideas?

**Comment by inosik** [comment]
[This](https://github.com/fsharp/FAKE/issues/1115#issuecomment-175462855) should do. But I agree that from API-design point of view, it's a bit odd.
