### ISSUE TITLE
Consider adding support for DocFx

### ISSUE THREAD

**Issue by Martin-Bohring** [fsharp/FAKE#1177]
[DocFx](https://github.com/dotnet/docfx) is the new documentation builder from the .Net Foundation.

It follows a similar approach as [F# Formatting](https://github.com/tpetricek/FSharp.Formatting) (e.g. mixing reference documentation with conceptional pages and the output is markdown as well), but with support for c# (unfortunately there is no F# support, yet).

Of course it is possible to just shell out a process to use it during build time, but an it just works experience is still the better option.

**Comment by forki** [comment]
Yes I would probably accept a PR for such a helper.

**Comment by forki** [comment]
implemented in #1251
