### ISSUE TITLE
Can't find dSYM file with FileSystemHelper

### ISSUE THREAD

**Issue by thomasvdb** [fsharp/FAKE#1178]
I don't know if this is an issue of FAKE but it seems I can't search for dSYM files.
`FileSystemHelper.TryFindFirstMatchingFile "*.dSYM" outputFolder |> fun file -> trace file.Value`

If I search for 
`FileSystemHelper.TryFindFirstMatchingFile "*.exe" outputFolder |> fun file -> trace file.Value`
a value is returned. 

The dYSM file, however, is in the same folder as the exe.
Any ideas?

**Comment by Vidarls** [comment]
Could it be that you have misspelled `dSYM` in your code snippet it says `*.dYSM` ?

**Comment by thomasvdb** [comment]
@Vidarls I've updated the code :) I made a typo here but in the build script it's set correctly.

**Comment by Vidarls** [comment]
Was worth a shot ;-)

**Comment by alexsorokoletov** [comment]
dSYM is a folder, might that be a problem?

**Comment by thomasvdb** [comment]
@alexsorokoletov That would explain a lot! I'll try it as soon as possible and let you know. Thanks!

**Comment by thomasvdb** [comment]
Issue closed; dSYM is a folder!
