### ISSUE TITLE
MSBuild for Xamarin.iOS: Compiled app ends up in the wrong folder

### ISSUE THREAD

**Issue by aspnetde** [fsharp/FAKE#1182]
When using the MSBuildHelper with Xamarin.iOS, the output, a folder called YourAppName.app, will eventually be put in the folder one level above the defined outputPath.

I guess that's caused by that "correction" here: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L449

Unfortunately I don't have a clue whether it is a bug in Mono (a bug in the implementation of System.IO.Path.IsPathRooted()) or in the helper itself. I tried to pass both a relative path and an absolute one, yet with the same result.

My workaround is to give in an additional level within my outputPath, so instead of "./build-ios/" I am now using "./build-ios/tmp/", so all the assemblies are going to tmp, but the ipa is finally being placed within build-ios (when using the Xamarin.iOSBuild helper, which internally used the MSBuild helper).

**Comment by forki** [comment]
Why are you using the BuildWebsite helper and not MSBuild helper directly?

**Comment by aspnetde** [comment]
Okay, that trace was misleading – I'm not. It's MSBuild which I used directly before and which is also used by the iOSBuild helper.

**Comment by forki** [comment]
Mhm very very strange. I don't remember anything like that in MSBuild
helper. The idea was always to just wrap the command line

**Comment by aspnetde** [comment]
My bad. OutputPath actually expects the full path to the *.ipa file for iOSBuild. Anyway, when using AndroidPackage the described behaviour applies, too. Some of the assemblies, seems to be the ones references by the build projects, are located one folder up to the OutputPath. 

Would you like to have me open another issue for that one?

**Comment by forki** [comment]
> Would you like to have me open another issue for that one?

Sure, but PR with fix would be even better ;-)
