### ISSUE TITLE
MSBuildHelper isDirectoryCheck

### ISSUE THREAD

**Issue by BlythMeister** [fsharp/FAKE#1184]
Hi,

I get an illigal characters in the file path when running FAKE when it is checking if the environment variable "MSBuild" is a directory.

The value i have in there is "c:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe" (including the quotes)
I noticed this error when upgrading from an older version of FAKE and noticed that this check was added between the versions i have.

I've worked around the issue by adding 
`let msbuildvar = environVar "MSBuild"`
`if (msbuildvar.StartsWith("\"") && msbuildvar.EndsWith("\"")) then`
`       setEnvironVar "MSBuild" (msbuildvar.Substring(1,msbuildvar.Length - 2))`
(sorry for the bad formatting!)

This removes the leading and trailing " and then works OK.

Should this be added to the MSBuild helper? - or have i got something wrong.

**Comment by Stift** [comment]
Do I understand it right that you environment variable contains these quotes? Why don't you just remove it?
I understand that you may use that variable also in other places, but this should contain only the path to the location and not anything else

BTW: `let ev = environVar "MSBuild" |> trimChars [| '"' |]` would also do your job.

**Comment by BlythMeister** [comment]
I can't see that I'm ever setting the environment variable. 
I am happy to leave my removal code in, but wanted to see if it's just my issue. 

Thanks for the code improvement though!

**Comment by Stift** [comment]
Can you maybe check your machine setting? Open Command Prompt and call `set` and you should see all variables. If you want to reconfigure them take a look at system settings in the control panel.

**Comment by BlythMeister** [comment]
strangly i don't see MSBuild listed, so i have no idea where the environment variable is coming from!

**Comment by Stift** [comment]
Ah. I see now what the problem is. When fake is starting your script it tries to start the fsi and this sets some default environment vars. I will take a look into that.

**Comment by BlythMeister** [comment]
Excellent! Thanks. 
For now, I can work around it by just fixing the env variable in my script, so not a huge issue for me.

**Comment by Stift** [comment]
I had some tests running and don't see that issue. My first assumption was not 100% correct.
Would you run this script fake script (*.fsx) and show us the output?
````
#r "../FAKE/build/FakeLib.dll"

open Fake

tracefn "MsBuild location (before): %s" <| environVar "MsBuild"

let ex = msBuildExe
tracefn "MsBuildExe location: %s " ex

tracefn "MsBuild location (after): %s" <| environVar "MsBuild"
````
I have on my machine:
````
MsBuild location (before):
MsBuildExe location: C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe
MsBuild location (after):
````

and also which fake version are you running (`fake --version`)?

**Comment by BlythMeister** [comment]
I'll give this a go tomorrow and feed back. 
I noticed you had a lower case S on MSBuild not sure if it's case sensitive, but the MSBuild helper uses upper case s.

**Comment by Stift** [comment]
We are on windows. It doesn't care about this.

**Comment by BlythMeister** [comment]
I have found the issue. 
I was using a bat file someone else write and didn't think to check until now.
Inside that file, the environment variable was incorrectly set! 

I'm sorry for wasting your time!
Its my code wrong, not fake.

**Comment by Stift** [comment]
That would be my last guess, but wanted to first see whether it's not an issue. Don't worry about my time. Just enjoy using FAKE!
