### ISSUE TITLE
Question: TeamCityHelper Get Changed Files

### ISSUE THREAD

**Issue by BlythMeister** [fsharp/FAKE#1186]
Hi,

I'm interested in using the get changed files function on the team city helper
(https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/TeamCityHelper.fs#L195)

I can see that it is needing an app setting pointing to a file which seems to contain all the changes.
But i am unsure how team city makes such a file.

I've had a look on the docs, and can't see any mention of it, can anyone advise?

**Comment by Stift** [comment]
I don't see how getRecentlyFailedTests and getChangedFilesInCurrentBuild should work. Are these legacy functions? /cc @forki

**Comment by forki** [comment]
I don't think I use that stuff.

**Comment by Stift** [comment]
For me it looks like the implementation is very special and needs some explanation. It queries some appSettings which do not make sense to me.
