### ISSUE TITLE
When calling FAKE from powershell, it runs successfully then exits with an error

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1187]
FAKE Version:

```
Installing 'FAKE 4.22.8'.
Successfully installed 'FAKE 4.22.8'.
```

This powershell script 

```
    $ErrorActionPreference = "Stop"
	# restore fake from nuget
	&".\.nuget\nuget.exe" "Install" "FAKE" "-OutputDirectory" "packages" "-ExcludeVersion"
	# and build using fake
	&".\packages\FAKE\tools\Fake.exe" "build.fsx"
```

Runs successfully and then exits with an error:

```
...
Hello World from FAKE
Finished Target: Default

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                       Duration
------                       --------
First                        00:00:00.0002082
RestoreNugget                00:00:03.1739934
DownloadBinaryDependencies   00:00:00.1209889
Clean                        00:00:00.0040734
BuildApp                     00:00:15.0406521
BuildUnitTests               00:00:04.5540232
ExtractTools                 00:00:13.9669876
RunUnitTests                 00:01:12.0171539
CoverageReport               00:00:01.5417982
BuildDocumentation           00:00:17.6886626
HarvestHeat                  00:00:00.2742397
ZipUpOutput                  00:00:02.3542330
BuildSetup                   00:00:29.4801323
Default                      00:00:00.0004666
Total:                       00:02:40.2605144
Status:                      Ok
---------------------------------------------------------------------
FAKE.exe : 
In Zeile:5 Zeichen:2
+     &".\packages\FAKE\tools\Fake.exe" "build.fsx"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

![image](https://cloud.githubusercontent.com/assets/4236651/14045490/049c991e-f29b-11e5-9f53-9ba379c52b17.png)

  
This behaviour does not occur with 

'FAKE 4.7.2'.

![image](https://cloud.githubusercontent.com/assets/4236651/14045682/792a2db8-f29c-11e5-898f-eccc60cd85b9.png)

**Comment by forki** [comment]
It doesn't show an error. What's fake's exit code?

**Comment by 0x53A** [comment]
Sorry, I'm on vacation for the next two weeks, but my guess is that it is related to stderr.
(Will see if I can connect remotely to my work pc and test it...)

I think when in prowershell     `$ErrorActionPreference = "Stop"` is set, it converts any EXE writing to stderr into an exception.

Since the exception message is empty, my blind guess is that on exit, FAKE flushes some kind of buffer and writes an empty message to stderr, causing powershell to throw.

**Comment by PhilipDaniels** [comment]
Err, is there a way of knowing whether this fix has made it to the package available on nuget.org? I am just checking out FAKE, running through the starter example, and the build.ps1/bat script fails with exactly this error if run from the PowerShell console in Visual Studio. That is as of today, 1 Aug 2016, fake reports version 4.36.0.

**Comment by 0x53A** [comment]
I think the pr https://github.com/fsharp/FAKE/pull/1210 was included in 4.23.6
This fixed the issue for me, but we use a frozen version at work, so it might be that the same issue was reintroduced later. I wanted to create a test for this, but never got to this ...

Also if you look at the pr comments, @matthid mentions that the same issue might happen in other code-paths, maybe you just hit a different one than me.

**Comment by esterad** [comment]
I think the issue is reintroduced in version 4.48.0. It works fine in 4.47.4 but when upgraded powershell throws exception despite successfully executing FAKE script

**Comment by matthid** [comment]
Another way would be to check for an empty string here: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/TraceListener.fs#L59 instead of the call-site as in #1210
I think that should at least remove those empty string errors. (On any other case we have at least a string to search for). I also think that is the only case we write to the std-err (might be wrong though)
