### ISSUE TITLE
Question: Condition for (not) executing a Task

### ISSUE THREAD

**Issue by WebDucer** [fsharp/FAKE#1190]
Helo.

I'm absolute newbe in F# and use FAKE to build C# project.

I want the following behaviour:

- Build on CI-Server
    - Execute SonarQube start and stop targets
- Build on local machine (isLocalBuild)
    - DON'T execute SonarQube start and stop targets

Is it possible with FAKE?

I have the following dependency declaration of my tasks:
```
// Target dependencies
"Cleanup"
   ==> "UpdateAssemblyInfos"
   ==> "StartSonar"
   ==> "BuildLibrary40"
   ==> "EndSonar"
   ==> "BuildLibrary45"

"BuildLibrary40" ==> "CreatePackage"
"BuildLibrary45" ==> "CreatePackage"
```

**Comment by forki** [comment]
sure. change both deps to somthing like:

    =?> ("StartSonar",hasBuildParam "runSonar")

and run the CI build with additional command line arg "runSoanr"

**Comment by WebDucer** [comment]
Thanks.

Works like a charm.
