### ISSUE TITLE
bulkComponentCreationAsSubDir   -> error CNDL0014 : The Directory/@Id attribute's value, 

### ISSUE THREAD

**Issue by PvlD** [fsharp/FAKE#1193]
error CNDL0014 : The Directory/@Id attribute's value, '20433
14266', is not a legal identifier.  Identifiers may contain ASCII characters A-Z, a-z, digits, underscores (_),
or periods (.).

Should be like this :
 Id = **"d"** +  directoryInfo.FullName.GetHashCode().ToString().**Replace("-", "")**

the same as in  "bulkComponentCreation"

Id = "f" + file.Name.GetHashCode().ToString().Replace("-", "")

**Comment by matthid** [comment]
I don't really understand this. Could you please send a PR or repro steps? Closing for now as its quite old.

**Comment by PvlD** [comment]
Yes.
It is old.
As for now – works fine.


Sent from Mail for Windows 10
