### ISSUE TITLE
Object Disposed Exception

### ISSUE THREAD

**Issue by Nickolas-** [fsharp/FAKE#1194]
After some time my CI start to raise unhandled Object Disposed exception. IOS works fine, problem in android.

```
Target "android-package" (fun () ->
    AndroidPackage (fun defaults ->
        {defaults with
            ProjectPath = "project path"
            Configuration = "Release"
            OutputPath = "out path"
        })
    |> AndroidSignAndAlign (fun defaults ->
        {defaults with
            KeystorePath = "Tollminder.keystore"
            KeystorePassword = getBuildParamOrDefault "pass" ""
            KeystoreAlias = "tollminder"
            ZipalignPath = "path/build-tools/23.0.2/zipalign"
        })
    |> ignore
)

```

After in build it try to create "Signed" apk.

```
Verifying alignment of ...*Aligned.apk (4)...Finished Target: android-package

Starting Target: android-hockey (==> android-package)
      50 META-INF/MANIFEST.MF (OK - compressed)
   17780 META-INF/TOLLMIND.SF (OK - compressed)
   35700 META-INF/TOLLMIND.RSA (OK - compressed)
   36850 AndroidManifest.xml (OK - compressed)
   38699 res/anim/abc_fade_in.xml (OK - compressed)
   38989 res/anim/abc_fade_out.xml (OK - compressed)
   39296 res/anim/abc_grow_fade_in_from_bottom.xml (OK - compressed)
   39755 res/anim/abc_popup_enter.xml (OK - compressed)
   40091 res/anim/abc_popup_exit.xml (OK - compressed)
   40446 res/anim/abc_shrink_fade_out_from_bottom.xml (OK - compressed)
   40908 res/anim/abc_slide_in_bottom.xml (OK - compressed)
   41209 res/anim/abc_slide_in_top.xml (OK - compressed)
   41514 res/anim/abc_slide_out_bottom.xml (OK - compressed)
   41815 res/anim/abc_slide_out_top.xml (OK - compressed)

Unhandled Exception:
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Stream has been closed'.
  at System.IO.FileStream.BeginRead (System.Byte[] array, Int32 offset, Int32 numBytes, System.AsyncCallback userCallback, System.Object stateObject) <0x1a2aca0 + 0x00256> in <filename unknown>:0
  at System.Diagnostics.AsyncStreamReader.ReadBuffer (IAsyncResult ar) <0x8565930 + 0x0033b> in <filename unknown>:0
  at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback (System.Object completedTask) <0x186a2b0 + 0x0004c> in <filename unknown>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x196a230 + 0x001bb> in <filename unknown>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x196a1f0 + 0x00033> in <filename unknown>:0
  at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke (System.Threading.Tasks.Task completingTask) <0x186a320 + 0x000ef> in <filename unknown>:0
  at System.Threading.Tasks.Task.FinishContinuations () <0x19579f0 + 0x0020c> in <filename unknown>:0
  at System.Threading.Tasks.Task.FinishStageThree () <0x1955cc0 + 0x0006b> in <filename unknown>:0
  at System.Threading.Tasks.Task.FinishStageTwo () <0x1955b90 + 0x00115> in <filename unknown>:0
  at System.Threading.Tasks.Task.Finish (Boolean bUserDelegateExecuted) <0x19559e0 + 0x0008a> in <filename unknown>:0
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task& currentTaskSlot) <0x19567a0 + 0x00135> in <filename unknown>:0
  at System.Threading.Tasks.Task.ExecuteEntry (Boolean bPreventDoubleExecution) <0x1956650 + 0x000df> in <filename unknown>:0
  at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () <0x19565b0 + 0x00025> in <filename unknown>:0
  at System.Threading.ThreadPoolWorkQueue.Dispatch () <0x196f180 + 0x001d8> in <filename unknown>:0
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () <0x19709c0 + 0x00017> in <filename unknown>:0
```

And after FAKE do some target I get some chinese symbols

```
Starting Target: core-build (==> clean)
卍畂汩⁤畡潴搭瑥捥楴湯›獵湩⁧獭畢汩⁤敶獲潩⁮㐧〮‧牦浯✠䰯扩慲祲䘯慲敭潷歲⽳潍潮昮慲敭潷歲嘯牥楳湯⽳⸴⸴⼰楬⽢潭潮㐯㔮⸧䄊汬瀠捡慫敧⁳楬瑳摥椠⁮慰正条獥挮湯楦⁧牡⁥污敲摡⁹湩瑳污敬⹤
义但⠠敲瑳牯⥥›潃灭瑵摥挠潯楫⁥慪⁲慰桴›唯敳獲港捩潫慬獳灨瑯湥潫ⸯ慸慭楲⵮牣摥湥楴污ੳ
```

FAKE version 4.22.9 
Mac OS X El Capitan v. 10.11.3
Zipalign r. 23.0.2

Update 1 april 2016:
Now ios stop building too.

```
  1) System.Exception: Error while posting to HockeyApp.
Messages: ≻楴汴≥∺潔汬業摮牥椠协Ⱒ戢湵汤彥摩湥楴楦牥㨢挢浯琮汯浬湩敤≲∬異汢捩楟敤瑮晩敩≲∺㝥㐷㌹㙡㜴㥥㠴㐹㙡㥡㔹戲攱㘳捡ぢⰢ瀢慬晴牯≭∺佩≓∬敲敬獡彥祴数㨢ⰰ挢獵潴彭敲敬獡彥祴数㨢畮汬∬牣慥整彤瑡㨢㈢㄰ⴵ㈱㌭吰㤰㔺㨷㌰≚∬灵慤整彤瑡㨢㈢㄰ⴶ㐰〭吱㐱〺㨴㤲≚∬敦瑡牵摥㨢慦獬ⱥ椢≤㈺㜶㌲ⰰ挢湯楦彧牵≬∺瑨灴㩳⼯楲歮栮捯敫慹灰渮瑥洯湡条⽥灡獰㈯㜶㌲⼰灡彰敶獲潩獮㘯Ⱒ瀢扵楬彣牵≬∺瑨灴㩳⼯楲歮栮捯敫慹灰渮瑥愯灰⽳㝥㐷㌹㙡㜴㥥㠴㐹㙡㥡㔹戲攱㘳捡ぢⰢ洢湩浩浵潟彳敶獲潩≮∺⸸∰∬敤楶散晟浡汩≹∺偩潨敮椯潐≤∬瑳瑡獵㨢ⰲ瘢獩扩汩瑩≹∺牰癩瑡≥∬睯敮≲∺汇牯畩⁭敔档潮潬楧獥Ⱒ漢湷牥瑟歯湥㨢戢㙤ㄶ㝤㝡昹慤㘸㐶扣晤㐱挷挰昵㜳㙣戲㘸散≥∬潣灭湡≹∺汇牯畩⁭敔档潮潬楧獥索㈊㄰ 
```

What it can be ?

**Comment by kentcb** [comment]
I'm seeing similar strangeness in #1196. I just found this because I also get `ObjectDisposedException`, though mine was during an attempt to restore packages. In addition, I get the asian characters in the output.

**Comment by kentcb** [comment]
In this particular case, it was not repeatable. I just ran my exact same script again and this time it worked. However, there are still a heap of asian characters in the output.

Also, #1196 seems to "fail" every time.

**Comment by Nickolas-** [comment]
When I start IOS hockey my script failed with this exception, but when I open a new tab in ITerm2 , everything start to build properly, but than appear again.

**Comment by Nickolas-** [comment]
Hello guys , still got this error. Any ideas ?

**Comment by kentcb** [comment]
Still getting this with 4.28.0 :(

**Comment by molinch** [comment]
Same here :(

**Comment by Nickolas-** [comment]
It's very important bug , that stopped our CI for a while.

**Comment by forki** [comment]
any ideas what to do?

**Comment by kentcb** [comment]
I do have Xamarin support looking into this and other issues. Basically I gave them my whole project and said _here, this should build on both mono and Windows but doesn't on either_. They have confirmed issues and said they'd get back to me. Will update this thread when they do.

**Comment by bartdkmediahuis** [comment]
Thanks for the update kentcb !
Also facing a similar issue after upgrading from mono 4.2.1 to 4.4.0 

You have a temporary workaround available ? Since this is breaking our CI environment as well.

**Comment by ewan-fraedom** [comment]
Same problem. seems intermittent

**Comment by amcculloch-fd** [comment]
Same issue - causing us serious issues :-(

**Comment by forki** [comment]
// cc @nosami

**Comment by bartdkmediahuis** [comment]
Any idea on where to look for a certain solution ?
Can we fork with a given fix or something ?

Did you guys do a rollback of mono ? Since rollback of FAKE does not fix this issue.

**Comment by bgidwani** [comment]
As a workaround till the issue is fixed, updated TeamCity to invoke the following

```
#ignore "cannot access a disposed object" exception
[[ $(mono --runtime=v4.0 ../tools/FAKE.exe build.fsx $@>&1) =~ "System.ObjectDisposedException: Cannot access a disposed object." ]]
```

This is used only for Android Package target from CI tool, so the exception is ignored and the build does not fail.

**Comment by ewan-fraedom** [comment]
whereabouts do you put that line? in the fake script? we have already set TC to ignore all errors for the moment. Seem to get the Chinese characters intermittently on a number of different build steps atm. seems to be when a shell command is run?

**Comment by ewan-fraedom** [comment]
we also get the hockey app problem, although it seems to succeed despite the odd characters

**Comment by bgidwani** [comment]
@ewan-fraedom the code is not part of the fake script. This is a regular shell script that invokes the Fake script (build.fsx file) and ignores the object disposed exception.

You can save the script in a android-package.sh file and invoke the script as follows -
./android-package.sh android-package buildmode=QA ..... (any additional parameters for FAKE script)

**Comment by ewan-fraedom** [comment]
gotcha

**Comment by bartdkmediahuis** [comment]
Thanks @bgidwani , This seems to "fix" the issue !
Not familiar with that syntax at all (any documentation we can read in order to find some more info ? ;) )

Seems like our logging is no longer printed, does this have any thing to do with the new command structure hiding it ?

**Comment by varon** [comment]
Also experiencing this on a similar setup - TeamCity, Xamarin, OS X for an Android build.
After signing an APK using `XamarinHelper.AndroidSignAndAlign`, I'm met with the same Chinese characters and the `ObjectDisposedException`.

I've tried a few alternative approaches to the trapping suggested by @bgidwani, but nothing seems to reliably prevent the error.

For now I'm just going to build on Windows (which so far seems to not fail, or at least fail a lot less). I'd greatly appreciate a workaround that preserves logs, and will be happy to provide more information or help with testing any possible fixes.

**Comment by alexsorokoletov** [comment]
Got these crashes after upgrading to the cycle 7 Xamarin. Sometimes build works fine, sometimes I see object disposed. After compiling Android.

**Comment by bartdkmediahuis** [comment]
Which version of the zipAlign tool are you using when executing the AndroidSignAndAlign ?
The object dispose catch did not solve the issue.

**Comment by alexsorokoletov** [comment]
/Library/Developer/Xamarin/android-sdk-macosx/build-tools/23.0.1/zipalign

**Comment by alexsorokoletov** [comment]
Hey guys, just catched something very unusual in the build log

```
Time Elapsed 00:01:32.7578650
jar signed.

Warning: 
No -tsa or -tsacert is provided and this jar is not timestamped. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2046-04-08) or after any future revocation date.
Verifying alignment of /Users/jen....Android/bin/Ad-Hoc/com....android-SignedAndAligned.apk (4)...
      50 META-INF/MANIFEST.MF (OK - compressed)
   15160 META-INF/COM_EAST.SF (OK - compressed)
   30430 META-INF/COM_EAST.RSA (OK - compressed)
   31579 AndroidManifest.xml (OK - compressed)
   32954 res/anim-v21/design_bottom_sheet_slide_in.xml (OK - compressed)
   33351 res/anim-v21/design_bottom_sheet_slide_out.xml (OK - compressed)
   33724 res/anim/abc_fade_in.xml (OK - compressed)
   34014 res/anim/abc_fade_out.xml (OK - compressed)
   34321 res/anim/abc_grow_fade_in_from_bottom.xml (OK - compressed)
   34780 res/anim/abc_popup_enter.xml (OK - compressed)
   35116 res/anim/abc_popup_exit.xml (OK - compressed)
   35471 res/anim/abc_shrink_fade_out_from_bottom.xml (OK - compressed)
   35933 res/anim/abc_slide_in_bottom.xml (OK - compressed)
   36234 res/anim/abc_slide_in_top.xml (OK - compressed)
[ARTEFACT] APK at: ....Android/bin/Ad-Hoc/com.....android_Ad-Hoc_1.0.374_Signed.apk
Finished Target: Android
   36539 res/anim/abc_slide_o
```

Here you can see that aligner is still verifying the apk while the code after validation is already executing in F#!

This is the code
```
      AndroidPackage (fun defaults ->
        {defaults with
            ProjectPath = csprojName
            Configuration = configuration
            OutputPath = outputDir
            Properties = androidParameters
        }) 
      |> AndroidSignAndAlign (fun defaults ->
        {defaults with
            KeystorePath = keystorePath
            KeystorePassword = keystorePassword
            KeystoreAlias = keystoreAlias
            ZipalignPath = zipalignPath
            JarsignerPath = jarsignPath
        })
      |> ignore

      traceStartTask "android-package-name" "renaming APK to reflect versioning and configuration"
      let apkName = Path.Combine(outputDir, String.Format("{0}-Signed.apk", AndroidPackageName))
      let apkFinalName = Path.Combine(outputDir, String.Format("{0}_{1}_{2}.{3}_Signed.apk", AndroidPackageName, configuration, version, buildNumber))
      File.Move(apkName, apkFinalName)
      traceEndTask "android-package-name" ""

      trace ("[ARTEFACT] APK at: " + apkFinalName)
      if not <| String.IsNullOrEmpty shouldPublish then
        UploadAndroidToHockey apkFinalName
```

What am I doing wrong?

**Comment by alexsorokoletov** [comment]
Here is what I did to get rid of the problem.
Due to the fact I got chinese characters also #1213 I was looking into fixing the part with encoding and found out that XamarinHelper is using very specific way to start process and this way doesn't specify UTF-8 encoding.

To test my strategy I basically made a copy of `AndroidSignAndAlign` and called `ExecProcessAndReturnMessages` which adds UTF-8 settings. Chinese disappeared at once and as a bonus zipalign and jarsign tasks are now awaited as they should be.

If you see the output from previous message, the log had like 20 messages from zipalign but in reality there are almost 500 lines in the output from zipalign that were never displayed (even in the old builds which did not fail and run on the mono 4.2 before Xamarin cycle 7 update).
I believe we have a problem in XamarinHelper with not waiting for the process to finish and only with mono 4.4 the problem started to cause crashes during build.

My guess is that it's related to the garbage collection changes but who knows. I'll test the changes for a few days and will make a PR.

Appreciate any feedback or comments

**Comment by forki** [comment]
Awesome. Please send pr

**Comment by bartdkmediahuis** [comment]
@alexsorokoletov thanks for the update !
Any chance a similar issue occurs when running the hockeyapp helper ?

With version .29 we are getting this exception : 

`17:54:53]System.Exception: Error while posting to HockeyApp.
[17:54:53]Messages: ≻楴汴≥∺效⁴楎略獷汢摡Ⱒ戢湵汤彥摩湥楴楦牥㨢挢浯洮摥慩畨獩洮扯汩慥灰⹳敮獷灡⹰扮⹯污桰≡∬異汢捩楟敤瑮晩敩≲∺㝡㈹㐱㑤㌲㘹ㄹ㕥晡㠸挶㐹ㅥ戵晣㈸Ⱒ瀢慬晴牯≭∺湁牤楯≤∬敲敬獡彥祴数㨢ⰲ挢獵潴彭敲敬獡彥祴数㨢∢∬牣慥整彤瑡㨢㈢㄰ⴵ㠰㈭吸㤰㐺㨳㤱≚∬灵慤整彤瑡㨢㈢㄰ⴶ㘰ㄭ吹㔱㔺㨴㌵≚∬敦瑡牵摥㨢慦獬ⱥ爢汯≥〺∬摩㨢㈲㌲㌷∬潣普杩畟汲㨢栢瑴獰⼺爯湩⹫潨正祥灡⹰敮⽴慭慮敧愯灰⽳㈲㌲㌷愯灰癟牥楳湯⽳㘴∱∬異汢捩畟汲㨢栢瑴獰⼺爯湩⹫潨正祥灡⹰敮⽴灡獰愯㤷ㄲ搴㈴㤳㤶攱愵㡦㘸㥣攴㔱换㡦∲∬業楮畭彭獯癟牥楳湯㨢㐢ㄮⰢ搢癥捩彥慦業祬㨢畮汬∬瑳瑡獵㨢ⰲ瘢獩扩汩瑩≹∺牰癩瑡≥∬睯敮≲∺敍楤桡極≳∬睯敮彲潴敫≮∺愸散㈴攰㘰挴昸扡㘴戸㝥愲敤晦〵㔰㈰㘵㕤㐴Ⱒ挢浯慰祮㨢䴢摥慩畨獩索㈊㄰
[17:54:53]Errors: 
[17:54:53]
[17:54:53]  at Fake.HockeyAppHelper.HockeyApp (Microsoft.FSharp.Core.FSharpFunc`2 setParams) <0x9197e70 + 0x003df> in <filename unknown>:0 `

**Comment by ewan-fraedom** [comment]
also in AndroidPackage

[android-package] /Library/Frameworks/Mono.framework/Commands/mono  "tools/xpkg/xamarin-component.exe" restore ../TravelApp.sln
[14:33:01][android-package] Process output: 
[14:33:01][android-package] "义但⠠敲瑳牯⥥›潃灭瑵摥挠潯楫⁥慪⁲慰桴›唯敳獲猯浡牵楡挭⽩砮浡牡湩挭敲敤瑮慩獬䤊䙎⁏爨獥潴敲㨩嬠崪删獥潴楲杮砠浡牡湩愮瑵⁨ㅶ㈮㌮ㄮ䤊䙎⁏爨獥潴敲㨩嬠崪匠捵散獳畦汬⁹敲瑳牯摥砠浡牡湩愮瑵⁨ㅶ㈮㌮ㄮ"

**Comment by alexsorokoletov** [comment]
Is it happening only with 4.29?

**Comment by alexsorokoletov** [comment]
Can reproduce, will be fixing the problem

Alex

**Comment by ewan-fraedom** [comment]
hmm ok so 4.28

[10:31:10][android-package] Starting Target: android-package 
[10:31:13][android-package] 卍畂汩⁤畡..... **LOTS of incorrectly encoded stuff**
[10:31:14][android-package] Task: MSBuild ../source/TravelApp.Droid/TravelApp.Droid.csproj

4.29

[android-package] Starting Target: android-package 
... **lots of properly encoded stuff**
[15:02:21][android-package] /Library/Frameworks/Mono.framework/Commands/mono  "tools/xpkg/xamarin-component.exe" restore ../TravelApp.sln
[15:02:22][android-package] Process output: 
[15:02:22][android-package] "义但⠠敲瑳牯⥥›.... **etc *SOME* incorrectly encoded stuff**
[15:02:22][android-package] Task: MSBuild ../source/TravelApp.Droid/TravelApp.Droid.csproj
[15:02:22][android-package] Building project: ../source/TravelApp.Droid/TravelApp.Droid.cspr
....
....
[15:03:46][android-package] jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore '../source/TravelApp.keystore' -storepass kiHyhswyqJ74 -signedjar '/Library/TeamCity/buildAgent/work/af9cce5fd849001a/source/TravelApp.Droid/bin/Release/com.fraedom.travelapp-Signed.apk' '/Library/TeamCity/buildAgent/work/af9cce5fd849001a/source/TravelApp.Droid/bin/Release/com.fraedom.travelapp.apk' TravelApp
[15:03:47][android-package] Process output: 
**[15:03:47][android-package] "慪⁲楳湧摥ਮ圊牡......................... etc etc**
[15:03:47][android-package] zipalign -f -v 4 /Library/TeamCity/buildAgent/work/af9cce5fd849001a/source/TravelApp.Droid/bin/Release/com.fraedom.travelapp-Signed.apk /Library/TeamCity/buildAgent/work/af9cce5fd849001a/source/TravelApp.Droid/bin/Release/com.fraedom.travelapp-SignedAndAligned.apk
[15:03:47][android-package] Process output: 
**[15:03:47][android-package] "敖楲祦湩⁧污杩..................... etc etc**
[15:03:47][android-package] Publishing artifacts (2s)
[15:03:47][android-package] ##teamcity[publishArtifacts 
[15:03:47][android-package] Finished Target: android-package

**Comment by alexsorokoletov** [comment]
Problem identified, checking the fix and will provide a fresh pull request soon

**Comment by ewan-fraedom** [comment]
still getting some enconding issues with 4.29.2

[12:03:31][core-build] Build property string 
[12:03:35][core-build] 卍畂汩⁤畡潴搭瑥捥楴湯›獵湩⁧獭畢汩⁤敶獲潩⁮㐧〮.....

**Comment by alexsorokoletov** [comment]
@ewan-fraedom I had to rollback encoding fixes in all processes cause this turned out to be much more complex issue that should be addressed.
4.29.2 should have encoding fixed with XamarinHelper

**Comment by aspnetde** [comment]
An update to 4.29.2 did the trick for me. I also noticed that the output directory of the .ipa changed, so I had to make some adjustments in my configuration here as well. But at least it works now with the latest Mono bits again.

**Comment by ewan-fraedom** [comment]
yeah the output directory change is v annoying. is it fake related though? we tried to fix by specifiing outputdir and/or outputpath but found that it incorrectly appends the filename to the last directory.

ie

outputdir = ./bin/iPhone -> ./bin/IphoneMyApp.ipa

when really you want

./bin/iPhone/MyApp.ipa

**Comment by aspnetde** [comment]
That's a mess I gave up on ;-).

What happens with the iOS helper:

    iOSBuild (fun defaults ->
        { defaults with
            BuildIpa = true
            ProjectPath = "src/Xyz.csproj"
            Configuration = "AdHoc"
            Platform = "iPhone"
            Target = "Build"
            OutputPath ="ios-build/bin/"
        })

Given that configuration I would expect to find everything within `ios-build/bin/`. Instead some stuff including the *.dSYM goes one level up, and for the actual IPA an sub directory is being created, but not within `ios-build/bin/`, but one level up, too. So the ipa ends in `ios-build/bin{name-of-the-ios-csproj} {timestamp}/`.

**Comment by ewan-fraedom** [comment]
yeah best i can tell is that its not using the default output path of the bin dir and then MSBuild or whatever is doing its default 'no output path' behaviour

then if you specify the output path there is a bug where it treats the last dir as something to prepend to the filename. tried all variations of ./directory/./ etc

**Comment by aspnetde** [comment]
Yep, and so did I. I am suffering a little OCD here knowing files are thrown in directories where they do not belong, but as I don't have to watch it while it's running on the build agent, I can live with that. It's just a bit annoying to figure out how things (not) work.

(But my F# knowledge is to limited at this point to dig deeper and provide a fix.)

**Comment by alexsorokoletov** [comment]
> So the ipa ends in ios-build/bin{name-of-the-ios-csproj} {timestamp}/
There is a bug for that in Xamarin http://stackoverflow.com/questions/37726925/xamarin-cycle-7-ios-ipa-output-now-in-a-datetime-folder/

**Comment by aspnetde** [comment]
I think those are two different things. The one thing is that folder with the timestamp, the other, storing everything outside the configured target directory, is more likely to be FAKE/XamarinHelper related.

**Comment by kentcb** [comment]
The IPA output path change is a separate issue that I have also been hounding Xam support about. It's apparently been fixed, but not released yet. See https://bugzilla.xamarin.com/show_bug.cgi?id=41963 for discussion and possible interim workarounds.

smh at how this got through to stable.
