### ISSUE TITLE
Release notes trims markdown lists (stars)

### ISSUE THREAD

**Issue by ianbattersby** [fsharp/FAKE#1206]
### Description

When you parse release notes that use the markdown list syntax it trims the prefixed stars.
### Repro steps

Please provide the steps required to reproduce the problem

1) Write a release note, e.g.

```
#### 1.2.3 - 06.04.2015
* Implement something amazing.
* Fix something else.
```

2) Run
(`List.head` of)

```
let releaseNotesData =
    File.ReadAllLines "RELEASE_NOTES.md"
    |> parseAllReleaseNotes
```
### Expected behavior

Expect release notes to retrain the star (*) prefix, certainly for when pushing to GitHub API.

```
* Implement something amazing.
* Fix something else.
```
### Actual behavior

```
Implement something amazing.
Fix something else.
```
### Known workarounds

None, I was looking in the direction of this but my F# is poor and didn't know if this was actually intended behaviour (in which case any PR a waste of time):
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/ReleaseNotesHelper.fs#L139
### Related information
- Version: 4.22.6
- Operating system: Windows Ent 10

**Comment by forki** [comment]
I think removing the * is fine.
But it should add it before the push to github again.

**Comment by matthid** [comment]
A PR would probably be accepted if there is a clever way to do it.
