### ISSUE TITLE
FscHelper translates "Debug true" to "-g+", which is incorrect

### ISSUE THREAD

**Issue by fsoikin** [fsharp/FAKE#1218]
### Description

When FscHelper is given a `Debug true` or `Debug false` in the list of arguments, it emits FSC args "-g+" and "-g-" respectively, which is incorrect and causes FSC to fail with error message "unrecognized option -g+".

This apparently happens because of this rather misleading line from the FSC help:

```
   --debug[+|-]                   Emit debug information (Short form: -g)
```

From which one would (and apparently did) conclude that the long form of this switch would be `--debug-` and `--debug+`, while short forms - `-g-` and `-g+` respectively. But this intuition is incorrect: short forms work differently than the long ones. Long form for enabling debug build is `--debug+`, and short form is just `-g`, whereas for disabling debug build one would specify `--debug-` for long form or omit the switch entirely for short form. In other words, the switch `-g-` does not exist.

### Repro steps

```
Target "Build" <| fun _ ->
  [ "src/src.fs" ]
  |> Compile [ Target Library; Debug false; Out "out.dll" ] 
```

### Expected behavior

Compile the source without debug info.

### Actual behavior

Error: "unrecognized option -g-"

### Known workarounds

If possible, omit the `Debug` argument entirely.

Alternatively, use `compileFiles` instead of `Compile` and specify arguments manually:

```
Target "ReleaseBuild" <| fun _ ->
  [ "src/src.fs" ]
  |> compileFiles [| "--out out.dll"; "-g"; "--target:library" ] 
```

**Comment by baronfel** [comment]
There is also a bug with how the optimize flag is handled, according to the CLI documentation for fsc.exe.  The long form of optimize, `--optimize`, also doesn't take a + or - after it to signal enablement, and yet we issue this string right now if optimization options are bassed.

**Comment by cloudRoutine** [comment]
@fsoikin  thanks for the explanation, that's exactly what I thought when I wrote it

**Comment by ErikSchierboom** [comment]
I have encountered the same problem.
