### ISSUE TITLE
NuGet restore of project.json

### ISSUE THREAD

**Issue by andersosthus** [fsharp/FAKE#1225]
Hi,

The current ```RestorePackageHelper``` can only restore packages from ```packages.config```, not project.json files. I have a need for doing ```project.json``` restore as well, and thought I should fix it, but I'd like to clear up a few points first.

 - The current ```RestorePackage``` (https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/RestorePackageHelper.fs#L151) helper doesn't actually restore packages, but installs them.
 - The ```nuget install``` currently used by the ```RestorePackage``` command does not support project.json (https://docs.nuget.org/consume/command-line-reference#install-command)
 - To restore packages from ```project.json```, ```nuget restore``` needs to be used (https://docs.nuget.org/consume/command-line-reference#restore-command)
 - Even though the current ```RestorePackage``` name is misleading in regards to what it actually does, I guess keeping it as is for compatibility with existing stuff is the best way to go.

So, I have a couple of solutions, but I'm not sure what'll be best.

 - Update ```RestorePackage``` with a match or something that detects ```project.json``` files and does a ```restore``` in stead of ```install``` when those are detected.
 - Add a new helper for dealing with ```project.json```, but I'm not sure what that should be called.

Any suggestions?

**Comment by isaacabraham** [comment]
Can this issue be closed? Might need to be a new issue once a new nuget package format is decided upon.
