### ISSUE TITLE
Improvement: extend token replacement in chocolateyinstall.ps1

### ISSUE THREAD

**Issue by xlegalles** [fsharp/FAKE#1238]
Hi, would it be possible to extend the list of tokens that are replaced in chocolateyinstall.ps1 and chocolateyuninstall.ps1? I'm talking about the id and the version number for instance.

Let me explain quickly my use case:
- I deploy a zip which is part of the nupkg (btw the documentation is a bit short on the subject): the zip is named exactly as the nupkg itself and its the only way I have to find it. I don't have the id, nor the version variable available.
- After the extraction of the archive, I want to install and start a TopShelf service: again, how can I know the name of the executable?

I use a choco template, I would like to be able to do things in a generic way and I don't want to hardcode anything.
Thank you.

**Comment by laedit** [comment]
To clarify, you want to be able to add custom replacement tokens to Choco.PackFromTemplate, which will be used in the nuspec, chocolateyInstal or chocolateyUninstall creation, is that right?
