### ISSUE TITLE
Consider VS 2015 Task Runner extension

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#1242]
### Description

It would be excellent to be able to provide support in VS 2015 for running Fake targets as the 'official' VS build.  Microsoft have provided a mechanism for doing this via [Task Runners](https://blogs.msdn.microsoft.com/webdev/2016/01/06/task-runners-in-visual-studio-2015/), examples can be seen [here](https://github.com/madskristensen/ProjectTaskRunner) and [here](https://github.com/madskristensen/NpmTaskRunner)
### Expected behavior

I should be able to easily CTRL + Shift + B to run my default FAKE target, or choose a target and run it from within VS with error reporting.
### Actual behavior

This is possible, but it involves setting up msbuild targets to override the default MSBuild build/compile targets, as seen [here](http://stackoverflow.com/questions/30218608/how-can-i-get-visual-studio-to-use-fake-for-building-my-solution)
### Known workarounds

See above

I'd be interested in taking this on if there is interest.  Initial concerns I have include
- should we embed FAKE into the extension, like with we do with Paket.VisualStudio? if we do this we get good structured errors, but then we may/would want to be able to continuously deliver the VS extension, suggesting that it should live in the overall FAKE project.
- if we don't embed FAKE into the VS extension, then we have to parse command-line output to get errors/warnings/info.

**Comment by matthid** [comment]
This is definitely interesting...

**Comment by matthid** [comment]
Any way forward here would probably be accepted :)
