### ISSUE TITLE
Make WiXHelper support 64Bit Setups

### ISSUE THREAD

**Issue by DigitalFlow** [fsharp/FAKE#1243]
### Description

If you set the ProgramFilesFolder param in "FillInWiXScript" to ProgramFiles64, WiX will fail with the message 

`error LGHT0204 : ICE80: This 32BitComponent cXXXXXXXXX uses 64BitDirectory INSTALLDIR`

As I found out, for WiX being able to create a setup that installs to ProgramFiles64, there need to be certain values set in the package node and in all component and file nodes.

These values are:
- Package: Platform="x64"
- Component: Win64="yes"
- File: ProcessorArchitecture="x64"

I already added those values to the type definitions, but I'm still figuring out, where it would be best to set them.
I will create an initial PR.

Kind Regards,
Florian

**Comment by matthid** [comment]
Seems like this is resolved :)
