### ISSUE TITLE
Support msbuild in unix environments

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/FAKE#1246]
As of mono 4.4, a preview build of msbuild [is being bundled](http://www.mono-project.com/docs/about-mono/releases/4.4.0/#msbuild-preview-for-os-x) with the OSX release. I've been looking at ways in which I could use this with FAKE, however [xbuild is pretty much hardwired](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L23) in the MSBuild helper method implementations.

Creating this issue as a discussion. Should we make it possible to opt for msbuild instead of xbuild? Or simply wait until the former replaces the latter completely?

**Comment by baronfel** [comment]
Going to tackle this later tonight by probing for msbuild first and then xbuild, since the world is moving towards msbuild.  If a user wants to specify one or the other they can do PATH manipulation to alter which is found.

**Comment by dsyme** [comment]
I think this has been implemented because I now see FAKE calling msbuild in Unix environments
