### ISSUE TITLE
Error from git describe helper function

### ISSUE THREAD

**Issue by rojepp** [fsharp/FAKE#1256]
### Description

Git `describe` fails with 

> git describe failed: fatal: No annotated tags can describe '66ea20b4776d0bef89b85fa1daf40f985109a220'.
### Repro steps

I'm trying to find out if current commit was tagged and in that case publish.
If I'm on an untagged commit, I get the error message above
### Expected behavior

I'd get the output from `git describe --tags`.
### Actual behavior

I get the output from `git describe`, which errors if I'm not 'on' a tagged commit.
### Related information
- Windows 10
- Git v2.7.0
- Fake 4.21.2

**Comment by forki** [comment]
does it work from command line?
What's the difference in FAKE's command?

**Comment by matthid** [comment]
I'm also not sure what the error is, can you clarify? Maybe we need a new feature in FAKE to enable to set the `--tags` parameter? Closing for now.
