### ISSUE TITLE
Bower Helper

### ISSUE THREAD

**Issue by wooderz** [fsharp/FAKE#1257]
Are there any plans to add a Bower helper? As far as I can see it would be a clone of the current Npm Helper, but using the bower command rather than npm? I'd be more than happy to fork and create this, then open a PR, but wanted to make sure I'm not stepping on anyone's toes first.

**Comment by wooderz** [comment]
Noticed AppVeyor didn't kick off a build in time and thus timed out - have made it run now and all checks have passed

**Comment by smoothdeveloper** [comment]
this can be closed now.
