### ISSUE TITLE
Hierarchy of Scripts causing Namepsace Issues

### ISSUE THREAD

**Issue by EolAncalimon** [fsharp/FAKE#1259]
Repro steps

Set up project with a similar structure to:

https://github.com/EolAncalimon/SampleFakeBuildScripts

Expected behavior

Fake script should run targets without error, the same scripts work when called with fsi rather than FAKE

Actual behavior

FS00039 error about a namespace not being defined, even though it is.

Related information

Visual Studio 2015
Windows 7

Anyone have any workarounds (bar putting everything in one file)

**Comment by dsyme** [comment]
This is an F# bug, fixed in F# 4.1
