### ISSUE TITLE
Fake ignores source errors in #load'ed sub-scripts

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1262]
### Description
In some cases, when I ``#load`` 2.fsx from 1.fsx, FAKE seems to ignore source errors like a misplaced brace in 2.fsx.

(In my actual script, this manifested as either a ExecutionEngineException or a nullref inside fake)

### Repro steps

1.fsx

```F#
#r @"packages\fake\tools\fakelib.dll"
open Fake

#load "2.fsx"


Target "T1" DoNothing

"T1" ==> "T2"

RunTargetOrDefault "T2"
```

=============

2.fsx

```F#
#r @"packages\fake\tools\fakelib.dll"
open Fake

Target "T2" (fun _ ->
    trace "This shouldn't work"
) )

```

Run.bat

```
packages\fake\tools\fake.exe 1.fsx
pause
```

### Expected behavior

It should fail with an error

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/4236651/15807278/1ce6099a-2b5a-11e6-85e5-ff74ab4432ca.png)

### Related information 

* Operating system: Win10
* Version: 4.28.0
* .NET Runtime: latest Full .Net Framework, I think 4.6.1

[FakeIssue.zip](https://github.com/fsharp/FAKE/files/299462/FakeIssue.zip)

**Comment by dsyme** [comment]
external
