### ISSUE TITLE
Fix test for script caching

### ISSUE THREAD

**Issue by forki** [fsharp/FAKE#1267]
after merging https://github.com/fsharp/FAKE/pull/1250 I have trouble to fix the tests.

@matthid could you please take a look?

/cc @ChrSteinert

**Comment by ChrSteinert** [comment]
Hmm, not nice. Will try to look at it in the (german time zone) evening.

**Comment by matthid** [comment]
Fixed via https://github.com/fsharp/FAKE/pull/1274.

**Comment by baronfel** [comment]
@forki can we close now that PR is merged?
