### ISSUE TITLE
ZipHelper silently mangles filenames.

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/FAKE#1269]
### Description

I'm not sure if this is expected behaviour or not. If you use any of the `ZipOfIncludes` functions in the ZipHelper module, if the base directory is not a direct child of the folder that you want to zip, the filespecs of all the files will be wrong. I've identified where the problem occurs, but I'm not sure if there should be a fix for this or not - happy to submit a PR if the desired behaviour of the code can be identified.
### Repro steps

Call `ZipOfIncludes` something like below: -

``` fsharp
Fake.ZipHelper.ZipOfIncludes "Foo.zip" [ ".", !!"Folder/To/Zip/**" ] 
```

where `Folder/To/Zip` is **not** in your current working directory. The code (https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/ZipHelper.fs#L141-L154) goes through and does a substring based on the _working directory_ instead of the folder that the zip lives in. The files then get concatenated if the current working directory name length and folder to zip name length don't match.
### Expected behavior

Zip file should contain original file names.
### Actual behavior

Zip file names are mangled.
### Known workarounds

Using the `Zip` function and explicitly passing in the working directory fixes the problem.

**Comment by matthid** [comment]
> goes through and does a substring based on the working directory instead of the folder that the zip lives in.

It does the substring based on the `BaseDirectory` (which you can set). Maybe this has been fixed since you reported the bug? I'm not sure what you are suggesting. Maybe send a PR and we can discuss :).
Closing for now, just in case this has been fixed.

**Comment by isaacabraham** [comment]
Almost a year old, I think this can't be that bad. I can't even remember it :-)
