### ISSUE TITLE
MSBuildRelease helper does not kill MSBuild processes

### ISSUE THREAD

**Issue by panesofglass** [fsharp/FAKE#1280]
### Description

`MSBuildRelease` helper does not kill `MSBuild.exe` processes once complete.
### Repro steps
1. Close all instances of Visual Studio and ensure no `MSBuild.exe` processes are currently running by running `get-process "*msbuild*"` from a powershell prompt.
2. Create a FAKE target that calls `MSBuildRelease` named `Build`.
3. Run `packages\FAKE\tools\FAKE.exe build.fsx build; get-process "*msbuild*"` from a powershell prompt.
### Expected behavior

Once FAKE completes running the target, all `MSBuild.exe` processes should be killed.
### Actual behavior

`MSBuild.exe` processes remain running.
### Known workarounds

Use `Shell.Exec` to run a powershell or batch script that executes `MSBuild.exe`.
### Related information
- Operating system: Windows Server 2012 R2
- Branch: 4.4.1
- .NET Runtime, CoreCLR or Mono Version: .NET 4.6.1
- Performance information, links to performance testing scripts

**Comment by inosik** [comment]
I also noticed that at the end of the day, there are lots of `MSBuild.exe` processes hanging around.

However, [this answer](http://stackoverflow.com/a/13510466) on SO seems to solve it for me. I set `MSBUILDDISABLENODEREUSE` environment variable to `1`, and there are no `MSBuild.exe`s after running FAKE anymore.

MSBuild creates a pool of `MSBuild.exe`s, which (should) get reused whenever you need to build multiple projects in parallel. This behavior is the default and can be disabled with the environment variable mentioned above or with `/nodereuse:false` command line parameter. This parameter is also [set to `true`](https://github.com/fsharp/FAKE/blob/c063bf415dac7f7d4df4c37fe76badce76cae3c3/src/app/FakeLib/MSBuildHelper.fs#L152) in FAKE by default, unless we are on TeamCity or Team Foundation Server.

**Comment by matthid** [comment]
Yeah please verify that the remaining processes are actually spawned by FAKE... Feel free to re-open if they are or when you think we should change the default.
