### ISSUE TITLE
TypeScriptCompiler doesn't work with TypeScript 1.5 compiler.

### ISSUE THREAD

**Issue by MarcinJuraszek** [fsharp/FAKE#1284]
### Description

I'm trying to use `TypeScriptCompiler` but it's failing, because it's looking for TypeScript 1.0, which is an old version. I have TypeScript 1.5 installed on my machine, and I'd expect FAKE to be smart enough to pick it up and use to compile my .ts files.

I can see 

```
let private TypeScriptCompilerPath = 
    @"[ProgramFilesX86]\Microsoft SDKs\TypeScript\1.0\;[ProgramFiles]\Microsoft SDKs\TypeScript\1.0\;[ProgramFilesX86]\Microsoft SDKs\TypeScript\0.9\;[ProgramFiles]\Microsoft SDKs\TypeScript\0.9\"
```

in https://github.com/fsharp/FAKE/blob/b7630d6e9bdb7caf7640ac38ca4166d9d7717d59/src/app/FakeLib/TypeScript.fs#L43. I think it should be able to use my TypeScript binaries from *C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5* (and probably in a way that will make it work with any new version of TypeScript, and not just 1.5).

**Comment by forki** [comment]
Please send a pull request

**Comment by alexfoxgill** [comment]
You can specify the path using the `ToolPath` parameter. For example

    !! ("**/*.ts")
    |> TypeScriptCompiler (fun p -> { p with ToolPath = @"C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe" })

However, perhaps it would be nice for FAKE to look for the most recent version of TypeScript in the standard directory
