### ISSUE TITLE
Using old-style argument parsing should print a warning

### ISSUE THREAD

**Issue by mkoerner** [fsharp/FAKE#1285]
### Description

Passing multiple boolean flags with `-ef A B` instead of `-ef A -ef B` disables other options (i.e. `-pd` and `-nc`).
### Repro steps

Running the script `test.fsx`

```
#I "packages/FAKE.x64.4.29.2/tools"
#r "FakeLib"
open Fake 
Target "Test" (fun _ ->
  if hasBuildParam "A" then trace "Got A ..."
  if hasBuildParam "B" then trace "Got B ..."
  trace "Testing stuff ..."
)
Run "Test"
```

with `packages\FAKE.x64.4.29.2\tools\FAKE.exe test.fsx Deploy -pd -ef A -ef B` has details in output

```
FakePath: C:\Users\mkoerner\packages\FAKE.x64.4.29.2\tools\FakeLib.dll
FAKE - F# Make "4.29.2"
Running Buildscript: test.fsx
Using cache
Building project with version: LocalBuild
Shortened DependencyGraph for Target Test:
<== Test

The resulting target order is:
 - Test
Starting Target: Test
Got A ...
Got B ...
Testing stuff ...
Finished Target: Test

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Test       00:00:00.0011667
Total:     00:00:00.0318487
Status:    Ok
---------------------------------------------------------------------

Ready.
```

while running it with `packages\FAKE.x64.4.29.2\tools\FAKE.exe test.fsx Deploy -pd -ef A B` has not

```
Building project with version: LocalBuild
Shortened DependencyGraph for Target Test:
<== Test

The resulting target order is:
 - Test
Starting Target: Test
Got A ...
Got B ...
Testing stuff ...
Finished Target: Test

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Test       00:00:00.0012198
Total:     00:00:00.0346119
Status:    Ok
---------------------------------------------------------------------
```

**Comment by Stift** [comment]
IMO the alternative call uses the secon paramter 'B' as build parameter which is the old argument style.

**Comment by mkoerner** [comment]
@Stift: maybe I misread the documentation. I understood
`--envflag [-ef] <name:string>`
Set environment variable flag name to 'true'. Supports multiple.
as being able to pass mutiple names to `-ef` instead of being able to use `-ef` mutiple times.

Even if the alternative call is the old argument style, I'm still surprised that `-pd` is disabled by that.

**Comment by matthid** [comment]
Yeah I think @Stift is correct. "Supports multiple" means you can use '-ef' more often. And in fact this probably is one weird side effects of basically using two argument parsers (for historical reasons). If the new parser fails we fallback to the second...

BTW: This is one point I will get rid of in the new dotnetcore implementation.

**Comment by matthid** [comment]
The old parser doesn't recognize '-pd': https://github.com/fsharp/FAKE/blob/master/src/app/FAKE/Program.fs#L140

In fact we had a PR previously adding a warning when falling back to the old parameters (which IMHO is the correct thing to do):
https://github.com/fsharp/FAKE/blob/master/src/app/FAKE/Program.fs#L126
But I guess it was too verbose and lead to a lot of headache for too many users :)

**Comment by mkoerner** [comment]
Thanks @matthid and @Stift for the feedback.
I had a look at the code. The old and new argument parsers really behave very differently. I agree that some feedback when the old parser is taken would be nice.

**Comment by matthid** [comment]
Tracked at https://github.com/fsharp/FAKE/pull/1128
