### ISSUE TITLE
Environment variables are not different between x86 and x64 

### ISSUE THREAD

**Issue by Stift** [fsharp/FAKE#1286]
### Description

The variables EnvironmentHelper.ProgramFiles and EnvironmentHelper.ProgramFilesX86 are the same. That means especially replacements of folders in e.g. ProcessHelper.tryFindFile will not work as expected. The reason is that the fsi which executes the Fake-script is running in 32-bit mode and therefore the EnvironmentVariable %ProgramFiles% is set to the 32-bit folder.
### Repro steps

Put the following in your Fake-script and let it run:
tracefn "%s" ProgramFiles
tracefn "%s" ProgramFilesX86
### Expected behavior

output:
C:\Program Files
C:\Program Files (x86)
### Actual behavior

output:
C:\Program Files (x86)
C:\Program Files (x86)
### Known workarounds

The only thing that I can imagine which could work, is to open the 64-bit hive of the registry and look for HKLM\Software\Microsoft\Windows\CurrentVersion and read the values from there.
### Related information
- Windows

**Comment by Stift** [comment]
I would also implement it, but first want to hear any possible issues or different ideas to solve this issue.

**Comment by baronfel** [comment]
An alternative would be to fetch these folders using `System.Environment.GetFolderPath(System.Environment.SpecialFolder)`, using `System.Environment.SpecialFolder.ProgramFiles` and `System.Environment.SpecialFolder.ProgramFilesX86`.  These return the correct values for the machine, not based on environment variables of the process.

**Comment by matthid** [comment]
I think that makes sense. If we can do it without registry even better :)
