### ISSUE TITLE
Exit code from fake.exe

### ISSUE THREAD

**Issue by dassie** [fsharp/FAKE#1296]
### Description

Fake.exe seems to always return exit code 0. Regardless of if the build failed or succeeded.

### Repro steps

Run the following:
```
#r "tools/FakeLib.dll"
open Fake

Target "Default" (fun _ ->
    raise (System.Exception("Error"))
)

RunTargetOrDefault "Default"
```

### Expected behavior

If a build fails like in the sample above, the executable should reflect that in its error code. This makes for easier integration in various build systems. TeamCity for example will look for a non-zero exit code to detect a failure. 

### Actual behavior

Exits with 0

**Comment by forki** [comment]
are you sure? FAKE catches all exceptions and sets the exit code to 1
