### ISSUE TITLE
XamarinHelper: Implement AndroidAbiTargetConfig.SuffixAndExtension

### ISSUE THREAD

**Issue by WebDucer** [fsharp/FAKE#1298]
### Description

In XamarinHelper is the type `AndroidAbiTargetConfig` with property `SuffixAndExtension` definied. This property is never used in code.

If I understand the intension behind this property, this should be used to generate specific names for the APKs generated for different ABIs. Is this correct? Was this planed but not implemented?

Type definition:
[XamarinHelper:L73](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/XamarinHelper.fs#L73)

Default values:
[XamarinHelper:L89](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/XamarinHelper.fs#L89-L96)

Static file name generation:
[XamarinHelper:L208](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/XamarinHelper.fs#L208-L214)
### Repro steps

Define own configuration for `AndroidPackageAbiParam.SpecificAbis` with other extensions than default. Aufter build this definition have no leverage on file names.
### Expected behavior

I think, the SuffixAndExtension should influence the final file name of the generated APK.
### Actual behavior

File name generation is static and can not be set up with the build script.
### Known workarounds

Rename final APK files after generation
### Related information
- Win10 / OS X 10.11
- Xamarin.Android

**Comment by matthid** [comment]
I'll try to consider this when someone ports the XamarinHelper to fake 5, for now I'm closing this as it is in the legacy codebase
