### ISSUE TITLE
.NET Core SDK helpers

### ISSUE THREAD

**Issue by enricosada** [fsharp/FAKE#1314]
Helpers for .NET Core SDK commands
- `dotnet pack`
- `dotnet build`
- `dotnet test`
- `dotnet publish`

initial work from @forki #1309 #1310 #1311 #1313

Most command have two important options

`--framework`: the fw (like `netstandard1.6` or `netcoreapp1.0` or `net45`)
`--runtime`: the target os ( `win`, `osx` ) if there are multiple

`dotnet restore` useful
- the fallback: `-f|--fallbacksource <FEED>      A list of packages sources to use as a fallback.` really nice to restore a built locally package from directory, without a need for a feed.
- verbosity: `-v|--verbosity <verbosity>      The verbosity of logging to use. Allowed values: Debug, Verbose, Information, Minimal, Warning, Error.`

`dotnet pack` usefull
- the version suffix: `--version-suffix <VERSION_SUFFIX>   Defines what`*`should be replaced with in version field in project.json`. it cannot replace complety the version, but nice for prerelease number

And the **most important of all**, `-v`.
- `dotnet cmd` run the cmd
- `dotnet --verbose cmd` (the `--verbose` or `-v` is BEFORE command), show all command line execution for all commands, it's really really useful in log

Another useful command (for log in ci server) is `dotnet info` who show all dotnet core sdk info, instead `dotnet --version` show only version.

**Comment by alexvaluyskiy** [comment]
I've just updated our build script to the newest FAKE. Looks good, but I really need two additional features
1) Export tests results to xml file (I can use -xml paremeter in xunit test runner, and Idk how to do it in nunit test runner)
2) Set output dir for nuget packages (-output parameter in dotnet pack)
3) Set version-suffix parameter in dotnet pack

**Comment by forki** [comment]
see https://github.com/fsharp/FAKE/pull/1321

**Comment by enricosada** [comment]
1. `dotnet test -xml testsresult.xml`
2. :+1: 
3. :+1:

**Comment by forki** [comment]
dotnet test -xml testsresult.xml doesn't work. dnc doesn't like that param

**Comment by enricosada** [comment]
nunit or xunit? works with xunit
can you try with nunitlite param `--result`? probably other params are passed to test excutor

**Comment by forki** [comment]
I'm not sure I undestand how that works. @enricosada can you send a PR when you find time? for now we have https://github.com/fsharp/FAKE/pull/1322

**Comment by enricosada** [comment]
`dotnet test --result:prova.xml` for nunit, see https://github.com/nunit/docs/wiki/NUnitLite-Options

argument of `dotnet test` are passed to specific implementation. a common out format or parameter doesnt exists atm i think

**Comment by forki** [comment]
so how would we model that? allow test helper to take in additional args?

**Comment by enricosada** [comment]
Yes, that's good. reading the project.jspn testrunner property is too much 

All command can add additional arguments right? That's not a base behavior for command task?

**Comment by forki** [comment]
https://github.com/fsharp/FAKE/pull/1323

**Comment by alexvaluyskiy** [comment]
NunitLite is the same as https://www.nuget.org/packages/dotnet-test-nunit/3.4.0-beta-1 ?

**Comment by enricosada** [comment]
Practically for command line. 
But dotnet test give remote execution, for example for test runners.

**Comment by alexvaluyskiy** [comment]
Why your implementation of DotnetCli helpers looks like completely different from the same helpers from CoreClr branch?
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotNetCLIHelper.fs#L103
vs
https://github.com/matthid/FAKE/blob/coreclr/src/app/Fake.DotNet.Cli/Dotnet.fs#L286

**Comment by forki** [comment]
it was developed independently ;-)
cc @matthid

**Comment by matthid** [comment]
Mine is just a copy of https://raw.githubusercontent.com/dolly22/FAKE.Dotnet/master/src/Fake.Dotnet/Dotnet.fs
...

**Comment by dsyme** [comment]
Fixed by https://github.com/fsharp/FAKE/pull/1387
