### ISSUE TITLE
SemVerHelper.parse doesn't handle prerelease segments that begin with a digit.

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#1324]
### Description

The SemVerHelper.parse method returns a None prerelease when given a SemVer string like "0.0.12-012345678".  This fails according to the spec, quoted here:

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

### Repro steps

Please provide the steps required to reproduce the problem

1. `Fake.SemVerHelper.parse "0.0.12-01234578" |> fun i -> i.Prerelease.IsNone <> true`

### Expected behavior

The prerelease segment is parsed as Some { Origin = "012345678"; Name = ""; Number = Some "012345678" }.

### Actual behavior

The prerelease segment is parsed as None

### Known workarounds

None

**Comment by mynkow** [comment]
Can this be fixed asap please.
