### ISSUE TITLE
error FS0193: internal error: Value cannot be null. Parameter name: con

### ISSUE THREAD

**Issue by halcwb** [fsharp/FAKE#1329]
### Description

Cannot load build script in fsi. The weird thing is that I am quite sure that this worked before. If I send the build script to Fake.exe then it runs without problems.
### Repro steps

Please provide the steps required to reproduce the problem

```
#I "../../packages/FAKE/tools/"

#r @"FakeLib.dll"
#load "../../packages/SourceLink.Fake/tools/Fake.fsx"

```
### Expected behavior

Script loaded in fsi.
### Actual behavior

Error message: 

> error FS0193: internal error: Value cannot be null. Parameter name: con
### Known workarounds

??
### Related information
- Windows 7 Ultimate 64 bit
- Fake 4.29.4 (also with latest release)
- .NET Runtime: 4.5

**Comment by matthid** [comment]
@halcwb Is this working with latest version?
