### ISSUE TITLE
How to create 2 different dependency graphs

### ISSUE THREAD

**Issue by CraftyFella** [fsharp/FAKE#1330]
### Description

I want to create 2 different dependency graphs for 2 different targets. Both share some common targets.. however the second build has an `ExtraThing` which needs to happen before `RunTests`. Is it possible to do this with FAKE? 

I'm pretty sure I'm just missing something.
### Repro steps

Create a fake script with the following dependencies:

`"Cleanup" ==> "Build" ==> "RunTests" ==> "Build1"`
`"Cleanup" ==> "Build" ==> "ExtraThing" ==>  "RunTests" ==> "Build2"`
### Expected behavior

When I run `Build1` _I don't want_ `ExtraThing` to be included in the dependency graph
When I run `Build2` I want `ExtraThing` to be included and it is :)
### Actual behavior

When I run `Build1` `ExtraThing`  _is_ included in the dependency graph but I don't want it to be
When I run `Build2` `ExtraThing` is included correctly
### Known workarounds

I have created duplicate target names with the build name prefixed to them.. E.g. `RunTestsBuild1` and `RunTestsBuild2`

`"Cleanup" ==> "Build" ==> "RunTestsBuild1" ==> "Build1"`
`"Cleanup" ==> "Build" ==> "ExtraThing" ==>  "RunTestsBuild2" ==> "Build2"`

**Comment by 0x53A** [comment]
AFAIK this is by design, 

`"Cleanup" ==> "Build" ==> "RunTestsBuild1" ==> "Build1"`

is the same as 

```
"Cleanup" ==> "Build"
"Build" ==> "RunTestsBuild1"
"RunTestsBuild1" ==> "Build1"
```

What I have used in the past to create similar graphs is using the operator `?=>` (soft-dependency).
It only tells fake the order, but does not add a dependency.


`"a" ?=> "b"` means:

> If both targets a and b are scheduled, then execute a before b, but if only b is scheduled, don't execute a.

**Comment by matthid** [comment]
Yes @0x53A already gave a complete explanation :)
Related https://github.com/fsharp/FAKE/pull/920 and http://stackoverflow.com/a/25400039 which was a clever way of doing it before we had soft dependencies.
