### ISSUE TITLE
How to create AssemblyInfo for every project in solution?

### ISSUE THREAD

**Issue by devployment** [fsharp/FAKE#1333]
I found a fairly old issue (https://github.com/fsharp/FAKE/issues/160). There is a custom target discussed to create an AssemblyInfo file for every project. Here's the target:

```
Target "WriteVersions" <| fun _ ->
    let flip f x y = f y x
    let attrs = 
        [ Attribute.Product "Test product"
          Attribute.Version version
          Attribute.FileVersion version ]

    !! @".\**\*\*.fsproj" 
    |> Seq.map (fun x -> (Path.GetDirectoryName x) + "AssemblyInfo.fs")
    |> Seq.iter ((flip CreateFSharpAssemblyInfo) attrs)

    !! @".\**\*\*.csproj" 
    |> Seq.map (fun x -> (Path.GetDirectoryName x) + @"\Properties\AssemblyInfo.cs")
    |> Seq.iter ((flip CreateCSharpAssemblyInfo) attrs)
```

@forki mentioned that he would avoid flip. As I'm totally new to F# and functional programming in general I don't really get why this flip is needed or how it could be avoided.

What would be the "right" way of creating the files for every project in a solution?

**Comment by inosik** [comment]
The `flip` function is just a helper to change the order of the parameters of the `f` function. Without `flip`, you could write this instead:

``` fsharp
!! @".\**\*\*.fsproj" 
|> Seq.map (fun x -> (Path.GetDirectoryName x) + "AssemblyInfo.fs")
|> Seq.iter (fun file -> CreateFSharpAssemblyInfo file attrs)
```

The actual code looks OK to me, I would do it in a similar way.

**Comment by matthid** [comment]
@inosik already answered it. Thanks!
