### ISSUE TITLE
Octokit missing type annotation breaks build.* clean

### ISSUE THREAD

**Issue by cjstephen** [fsharp/FAKE#1336]
### Description

After an update build.sh no longer works. Can be remedied by adding a type annotation of string to:
paket-files/build/fsharp/FAKE/modules/Octokit/Octokit.fsx:178
### Repro steps

paket update to current version
build clean fails (and default target) with the attached output
### Expected behavior

Builds at least clean without errors
### Actual behavior

Fails every time
### Known workarounds

This patch is sufficient
178c178
## <         let! drafts = Async.AwaitTask <| client'.Repository.Release.GetAll(owner, project)

> ```
>     let! drafts = Async.AwaitTask <| client'.Repository.Release.GetAll((owner:string), project)
> ```
### Related information
- Operating system: Windows 10
- .NET Runtime, CoreCLR or Mono Version
  .NET 4.5

paket.dependencies:
source https://nuget.org/api/v2

nuget FSharp.Core redirects: force

nuget Endorphin.Core
nuget System.Reactive.Interfaces
nuget FSharp.Control.Reactive
nuget log4net

github WarwickEPR/Endorphin.Core src/Endorphin.Core.Reactive.fs

group Build
    source https://nuget.org/api/v2

```
nuget SourceLink.Fake
nuget FAKE
nuget FSharp.Formatting

github fsharp/FAKE modules/Octokit/Octokit.fsx
```

[build-clean-error.txt](https://github.com/fsharp/FAKE/files/388236/build-clean-error.txt)
[paket.lock.txt](https://github.com/fsharp/FAKE/files/388237/paket.lock.txt)

**Comment by cloudRoutine** [comment]
fixed by #1338
