### ISSUE TITLE
NugetHelper.fs: GetPackageVersion - returns incorrect package version

### ISSUE THREAD

**Issue by bobahml** [fsharp/FAKE#1342]
### Description

I have 2 package in the deployments folder:
- Castle.Core.3.3.3
- Castle.Core-NLog.3.3.3

`"Castle.Core", GetPackageVersion "./packages/" "Castle.Core"`
-> returns NLog.3.3.3

NLog.3.3.3' is not a valid version string.
### Expected behavior

GetPackageVersion in this case must return 3.3.3.

**Comment by forki** [comment]
Marked as u

**Comment by revuniversal** [comment]
It looks like this was fixed in 7344d28e6b2afe821434a41388da3d664aa68221.

**Comment by TeaDrivenDev** [comment]
Yep, just tested this again with 4.60.0, and it works as expected.

**Comment by TeaDrivenDev** [comment]
@forki Is anything missing for closing this? (My goal is getting it out of the up-for-grabs list,)
