### ISSUE TITLE
AssemblyInfo.GetAttribute and AssemblyInfo.GetAttributeValue double quote response

### ISSUE THREAD

**Issue by mglodack** [fsharp/FAKE#1344]
### Description

I'm sort of confused by the current response of `AssemblyInfoFile.GetAttribute`, but maybe I'm missing something.

I currently have to `Trim` the response because the expected behavior appears to be a doubly quoted strings (see below).

Would it be possible to remove the extra quotes or is this the expected behavior?

### Repro steps

Here is link to the spec that validates the current response.
https://github.com/fsharp/FAKE/blob/master/src/test/Test.FAKECore/AssemblyInfoSpecs.cs#L74

### Expected behavior

I would expect the response be something like this:

```
"1.0.0"
```

### Actual behavior

Currently, the response is of this form:

```
"\"1.0.0\""
```

### Known workarounds

My current workaround for this response is to just `Trim` the extra quotes.
```
let GetVersion () =
    match (AssemblyInfoFile.GetAttributeValue "AssemblyInformationalVersion" "AssemblyInfo.cs") with
    | Some versionString -> versionString.Trim[| '"' |]
    | None ->
      let errorMessage =
          sprintf "Error: missing attributes `%s` in %s" "AssemblyInformationalVersion" "AssemblyInfo.cs"
      traceError errorMessage
      exit 1
```

**Comment by forki** [comment]
I think a pr which trims it would be OK

**Comment by mglodack** [comment]
@forki Awesome! I will have that soon :+1:
