### ISSUE TITLE
FakeLib - ZipHelper tries to add it's own zip file to the zip

### ISSUE THREAD

**Issue by zyborgLP** [fsharp/FAKE#1346]
### Description

When calling the Zip function and the workingDir matches with the target zip file directory, the ZipHelper tries to add the zip it is creating, to the zip.

This throws in a System.IO.IOException:
`System.IO.IOException: The process cannot access the file '...' because it is being used by another process.`
### Repro steps
1. Call the zip function with the zip file specified in the same directory as the working dir

```
Target "ZipOutputDir" (fun _ ->
    !! "./**/*"
      |> SetBaseDir build.OutputDir
      |> Zip build.OutputDir (build.OutputDir @@ solutionName + "." + build.Environment.``build.number`` + ".zip")
  )
```
### Expected behavior

The Zip function should not try to add the zip file to the zip file and exclude it from the file sequence.
### Actual behavior

The Zip function tries to add the zip file into the zip file, which throws the specified exception.
### Known workarounds

A know workaround is to exclude the zip file from the files externally:

```
Target "ZipOutputDir" (fun _ ->
    !! "./**/*"
    -- "./*.zip"
      |> SetBaseDir build.OutputDir
      |> Zip build.OutputDir (build.OutputDir @@ solutionName + "." + build.Environment.``build.number`` + ".zip")
  )
```
### Related information
- Operating system: Windows 10
- Branch: master 4.27.0

**Comment by matthid** [comment]
Honestly I'm not sure about this. What we can do is to use a temporary file, but that way the new zip-file will contain the old zip-file and it will just work. But that is not what you want, right?
I'll close this as "wont-fix" for now (as it is old) but feel free to discuss this further.
