### ISSUE TITLE
Naming/Documentation of ToolPath for NUnit3 is wrong + Mark ToolName obsolete

### ISSUE THREAD

**Issue by robkuz** [fsharp/FAKE#1348]
### Description

The documentation for ToolPath for the NUnit3 implies that it really only wants the the path to the "nunit3-console.exe". for example `./packages/NUnit.Consolerunner/tools`. However it needs the `ToolName` to.
### Repro steps

```
Target "Test" (fun _ ->
    !! (testDir + "/MyApp.exe")
    |> NUnit3 (fun p -> {p with ToolPath = "./packages/NUnit.Consolerunner/tools")
)
```

The above will fail. If one however includes the ToolName as well it will work

```
Target "Test" (fun _ ->
    !! (testDir + "/MyApp.exe")
    |> NUnit3 (fun p -> 
        {p with 
            ToolPath = "./packages/NUnit.Consolerunner/tools/nunit3-console.exe")
)
```
### Expected behavior

For some reason on the switch to NUnit 3 the record field `ToolName` got dropped but is somehow needed nevertheless.

I would suggest to reinstate the given field.
### Known workarounds

Add the ToolName also to the ToolPath or return `NUnit3Defaults` from the lambda.

```
Target "Test" (fun _ ->
    !! (testDir + "/MyApp.exe")
    |> NUnit3 (fun p -> NUnit3Defaults)
)
```
### Related information
- MacOSX 10.11
- Mono 4.4.2

**Comment by inosik** [comment]
Every FAKE helper, which uses an external tool, has a `ToolPath` parameter. This parameter always needs to point to the executable file of the tool.

The initial PR for NUnit 3 support actually had a `ToolName` parameter, but I suggested to drop it for consistency. I never used NUnit 2 with FAKE, so I didn't know that it has both, `ToolPath` and `ToolName`.

Reintroducing `ToolName` would break existing scripts, so I suggest to adjust the documentation.

**Comment by matthid** [comment]
Yes I agree with @inosik

**Comment by alex-bogomaz** [comment]
Current documentation for NUnit3 ToolPath says the following:
```fsharp
/// The path to the NUnit3 console runner: `nunit3-console.exe`
    ToolPath : string
```
and for default value description:
```fsharp
/// - `ToolPath` - The `nunit-console.exe` path if it exists in a subdirectory of the current directory.
```
do you think is OK or it still needs some improvements?

**Comment by inosik** [comment]
How about this:

``` diff
-/// - `ToolPath` - The `nunit-console.exe` path if it exists in a subdirectory of the current directory.
+/// - `ToolPath` - The `nunit-console.exe` path if it exists in `tools/Nunit/`.
```

**Comment by alex-bogomaz** [comment]
ok, thank you, but what about documentation of ```ToolPath``` itself:
```
/// The path to the NUnit3 console runner: `nunit3-console.exe`
```
do you think this is fine?
CC: @robkuz

**Comment by matthid** [comment]
I think it is fine as-is. It is consistent with other helpers.
