### ISSUE TITLE
Sample app FAKE-CALCULATOR does not run on Windows

### ISSUE THREAD

**Issue by 100s** [fsharp/FAKE#1353]
### Description

Fake calculator does not run on Windows
### Repro steps
1. Extract zipped sample project FAKE-CALCULATOR
2. Type in cmd: build.bat
### Expected behavior

Fake should run
### Actual behavior

"Unable to find package "FAKE".
### Known workarounds

Specify correct path to nuget.exe
### Related information

Windows 10
Master

**Comment by OnTheFenceDevelopment** [comment]
Same issue here - I downloaded the latest version of nuget from https://dist.nuget.org/index.html, overwrote the one that came with the Calculator sample and it works fine for me.

HTH

**Comment by awright18** [comment]
This seems to have been corrected by closing issue #1416 which switched the sample to using paket instead of nuget.

**Comment by matthid** [comment]
Ah cool, thanks @awright18
