### ISSUE TITLE
ResGenHelper would be nice to have

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#1360]
It would be nice to have a ResGenHelper module. Right now if you want to compile resource files with `resgen.exe` as part of your build process, you have to use ProcessHelper -- which works, but isn't as convenient as it could be because you have to deal with paths yourself (where is resgen.exe on Mono? Where is it on Windows?), and so on.

If I get around to writing a ResGenHelper, I'll submit a PR, but it might take me a while. So I'm putting the idea out there for anyone else to pick up if they get to it first.

**Comment by matthid** [comment]
This would be a nice feature to add and a PR is very welcome. Closing this for now.
