### ISSUE TITLE
Add Checksum infos in Choco.Pack

### ISSUE THREAD

**Issue by laedit** [fsharp/FAKE#1364]
### Description

Checksum will soon be mandatory in chocolatey and should be handled in ChocoHelper.

### Expected behavior

Add Checksum[64] and ChecksumType[64] parameters to ChocoPack.

### Known workarounds

For now, it is possible to use a template for chocolateyInstall.PS1 which add these parameters.

I will propose a PR soon.

**Comment by forki** [comment]
thanks. waiting for PR then ;-)
