### ISSUE TITLE
FAKE.Lib nuget package can't be installed in mono project

### ISSUE THREAD

**Issue by hravnx** [fsharp/FAKE#1370]
### Description

The NuGet package for FAKE.Lib (and FAKE.Lib.x64) can't be installed in a Xamarin  Mono project on macOS
### Repro steps
1.  Open Xamarin Studio in macOS
2.  Create a new Library project, selecting F# as the language
3.  From the menu select `Project->Add NuGet Packages...`
4. Type in FAKE.Lib in the search box, check FAKE.Lib from the search results and click the `Add Package` button
### Expected behavior

The package should install
### Actual behavior

The package fails to install with the error message `Could not install package 'FAKE.Lib 4.39.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Note that the full FAKE package installs just fine.
### Known workarounds

None
### Related information
- macOS 10.11.6
- Xamarin 6.0.2
- Mono 4.4.2

**Comment by inosik** [comment]
If you want to use FAKE.Lib, you have to choose .NET 4.5.1 or higher as the target framework.

The full FAKE package can be installed, because it doesn't have a `lib/` directory in it.

**Comment by matthid** [comment]
Correct
