### ISSUE TITLE
Use of multiple items in DefineConstants failing on mono

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1385]
### Description

When specifying multiple symbols in `DefineConstants` (separated by `;`), the tooling fails on mono with:

```
Building project: Src/Redacted.Android.sln
  xbuild  Src/Redacted.Android.sln /t:Build  /v:d  /p:RestorePackages="False" /p:Optimize="True" /p:DebugSymbols="True" /p:DefineConstants="RAYGUN;LOGGING;" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"/Users/vagrant/git/Src/packages/FAKE/tools/FakeLib.dll"
xbuild  Src/Redacted.Android.sln /t:Build  /v:d  /p:RestorePackages="False" /p:Optimize="True" /p:DebugSymbols="True" /p:DefineConstants="RAYGUN;LOGGING;" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"/Users/vagrant/git/Src/packages/FAKE/tools/FakeLib.dll"
MSBUILD: error MSBUILD0005: Invalid syntax. Property name and value expected as <prop name>=[<prop value>]
Running build failed.
Error:
Building Src/Redacted.Android.sln failed with exitcode 1.
```
### Repro steps

Please provide the steps required to reproduce the problem
1. Specify multiple symbols in `DefineConstants`:

```
                Properties =
                    [
                        "DefineConstants", "RAYGUN;LOGGING;"
                    ]
```
1. Build on mono
### Expected behavior

Both symbols should be defined during compilation.
### Actual behavior

Compilation fails with the above error.
### Known workarounds
- build on Windows (although this is not a viable workaround for me)
### Related information
- Mac (running in Bitrise)
- mono 4.6.0
- Running FAKE 4.40.0

**Comment by jerone** [comment]
Running into the same issue. Anyone found a solution for multiple symbols?

**Comment by nesshoever** [comment]
Same here when using nuget.
```
user@host:~/path$ nuget
NuGet Version: 3.5.0.1996
user@host:~/path$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

user@host:~/path$ nuget restore ./path-to-solution/solution-file.sln
MSBuild auto-detection: using msbuild version '14.0' from '/usr/lib/mono/xbuild/14.0/bin'.
MSBUILD: error MSBUILD0005: Invalid syntax. Property name and value expected as <prop name>=[<prop value>]

```

**Comment by jerone** [comment]
Using a space instead of `;` solved it for me.

**Comment by matthid** [comment]
Yes I have run into this as well from time to time. This is basically a `xbuild` bug. I think this solves itself as mono is shifting towards using msbuild (now that it has been open sourced).

**Comment by mt-yu** [comment]
@jerone  space  !!!
