### ISSUE TITLE
Master branch failing to build

### ISSUE THREAD

**Issue by simax** [fsharp/FAKE#1391]
I cloned the latest ```Master``` branch onto my windows PC and opened solution in ```VS 2013```. Tried to rebuild all which failed on the following line in ```Sql.DacPac.fs```

```
    let getVsVersion path = (Path.GetDirectoryName path |> DirectoryInfo).Name |> int
```

with ```invalid use of type name with and/or object constructor...```

It also fails to build when I run ```build.cmd``` from the command line.

If I change the offending line to the following
```
    let getVsVersion path = Path.GetDirectoryName path |> (fun p -> DirectoryInfo(p).Name) |> int
```

The solution then builds in ```VS```. and with ```build.cmd```

I'm a total ```F#``` noob so I could be totally off the mark here, but is this a bug?.

**Comment by forki** [comment]
It's using newer F# version. Try vs 2015 instead.
