### ISSUE TITLE
Run db script doesn't work with GO statements

### ISSUE THREAD

**Issue by andyking32** [fsharp/FAKE#1393]
If I use the Fake.SQL.SqlServer runScript method, it won't work if you have Go statements. I get an error message stating Microsoft.SqlServer.BatchParserClient.dll can't be found.

I can resolve this by dropping v12 of Microsoft.SqlServer.BatchParserClient.dll and microsoft.sqlserver.batchparser.dll into the tools folder.

I'm currently using 4.40.0 and see the following SqlServer dlls in the tools folder:
Microsoft.SqlServer.ConnectionInfo.dll
Microsoft.SqlServer.ConnectionInfoExtended.dll
Microsoft.SqlServer.Management.Sdk.Sfc.dll
Microsoft.SqlServer.Smo.dll
Microsoft.SqlServer.SmoExtended.dll
Microsoft.SqlServer.SqlClrProvider.dll
Microsoft.SqlServer.SqlEnum.dll

However, I see in 4.41 that some dlls are now no longer there and you have just three:
Microsoft.SqlServer.ConnectionInfo.dll
Microsoft.SqlServer.Management.Sdk.Sfc.dll
Microsoft.SqlServer.Smo.dll 

Not sure what the reason is for the difference between 4.40.0 and 4.40.1. I was going to submit a PR added the two new dlls above. 

Please advise how to proceed on this.

**Comment by matthid** [comment]
Are we missing an dependency? was this resolved in the mean time?

**Comment by andyking32** [comment]
Noone ever responded so i didn't submit the PR. You need the two dlls mentioned above in order to be able to run go commands.

**Comment by matthid** [comment]
See https://github.com/fsharp/FAKE/pull/1377. No idea if we can revisit the decision to support SQL Server 2008 R2...
