### ISSUE TITLE
ToolPath for XSL in FxCopHelper is wrong when using ApplyOutXsl and not setting OutputXslFileName explicitly

### ISSUE THREAD

**Issue by pr-yemibedu** [fsharp/FAKE#1394]
### Description

The ToolPath parameter is used wrong with the Fxcop Helper to generate a report when you set ApplyOutXsl to true but leave OutputXslFileName at either its default or set it to an empty string explicitly.
### Repro steps
1. Use whatever method you like to get FxCop installed and note the path to FxCopCmd.exe
2. set up a project and build.fsx to use the FxCop Helper called "FxCop" where you specify parameters. For example:
```fsharp
Target "FxCop" (fun () -> 
  !! (DebugDir + @"*_\_.dll")
  |> FxCop(fun p ->
        let fxcopPath = "C:/Program Files (x86)/Microsoft Visual Studio 14.0/Team Tools/Static Analysis Tools/FxCop"
        {p with 
                ApplyOutXsl = true
                OutputXslFileName = ""
                ReportFileName = "FXCopResults.html" 
                Verbose = false
                ToolPath =  fxcopPath @@ "FxCopCmd.exe" } ) )
```

3. run your build including this target.
### Expected behavior

We would expect FXCopResults.xml to contain content that is styled from FxCopReport.xsl
### Actual behavior

We receive an error:
```
Error writing output file to 'FXCopResults.xml': Could not find a part of the path 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Static Analysis Tools\FxCop\FxCopCmd.exe\Xml\FxCopReport.xsl'.. If there is an XML report output file, make sure that the location of the report style sheet is correct.
```
We can see the reference "FxCop\FxCopCmd.exe\Xml\FxCopReport.xsl" that should be "FxCop\Xml\FxCopReport.xsl"
### Known workarounds

If you explicitly set the OutputXslFileName path and name, then everything generates as expected.
### Related information
- Windows 10
- FAKE (4.40.1)
- .NET Runtime = 4.0
- Microsoft (R) FxCop Command-Line Tool, Version 14.0 (14.0.25420.1) X86
### Source code reference

[line 92 let param = ](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FXCopHelper.fs#L93)
[line 93 if param.ApplyOutXsl && param.OutputXslFileName = String.Empty then](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FXCopHelper.fs#L93)
[line 94 { param with OutputXslFileName = param.ToolPath @@ "Xml" @@ "FxCopReport.xsl" }](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FXCopHelper.fs#L94)
[line 95 else param](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FXCopHelper.fs#L95)

[line 131  tracefn "FxCop command\n%s %s" param.ToolPath commandLineCommands](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FXCopHelper.fs#L131)

**Comment by matthid** [comment]
Closing issues in the legacy code base, feel free to re-open if this still exists in fake 5
