### ISSUE TITLE
The '--break' command line switch doesn't do anything

### ISSUE THREAD

**Issue by dassie** [fsharp/FAKE#1402]
### Description

Usage of the '--break' command line switch has no effect. 
### Repro steps

Run a trivial Fake target using fake.exe and supply the '--break' switch.
### Expected behavior

Fake.exe should pause with a Debugger.Break() "somewhere near the start". 
### Actual behavior

The switch has no effect.
### Related information

Version: 4.92.2

**Comment by Stift** [comment]
Can you try `-br` instead, please?

**Comment by Stift** [comment]
in my latest it works. Can you provide the complete command that is executed?

**Comment by yemibedu** [comment]
Hello,
 You can see in the source code here: [| [\<AltCommandLine("-br")\>] Break](https://github.com/fsharp/FAKE/blob/73589a85a5e30a2c78d61efccdd3446a99483142/src/app/FAKE/Cli.fs#L16)

It is in fact the smaller two letter version.

**Comment by dassie** [comment]
Changed to version 4.41.5 (which was the latest on nuget.org) and it works. I was trying both '-br' and '--break'. 

Feel free to close this.

**Comment by Stift** [comment]
yeah. already saw that strange version you specified. You can close yourself.
