### ISSUE TITLE
Fake.Git.Information.getBranchName is hardcoded localized to english

### ISSUE THREAD

**Issue by embix** [fsharp/FAKE#1403]
### Description

`getBranchName` I get "Auf Branch master" instead of "master".

### Repro steps

1. build.fsx:

        #r "packages/FAKE/tools/FakeLib.dll"
        open Fake
        open Fake.Git
        
        Target "Default" (fun _ ->
            let branch = getBranchName ""
            trace branch
        )
        
        RunTargetOrDefault "Default"

2. build.bat:

        @echo off
        cls
        ".nuget\NuGet.exe" "Install" "FAKE" "-OutputDirectory" "packages" "-ExcludeVersion"
        "packages\FAKE\tools\Fake.exe" build.fsx
        pause

3. start powershell
4. execute: `PS C:\temp> .\build.bat`

### Expected behavior

I'd expect to only get the branch name: `master`.

### Actual behavior

I get the branch name prefixed by `Auf Branch master`.

### Known workarounds

Detect language and strip prefix yourself.

### Related information 

* German Windows10x64 1607, ran fake via build.bat in powershell (cmd.exe works too)
* Branch: every branch ;-) or Fake 4.41.5 a7c04ed4 if that is what you want to know
* .NET 4.6.2

**Comment by forki** [comment]
Urgs. Why do you use localized git? That's big pain - not only with fake

Am 12.10.2016 11:29 vorm. schrieb "Michel Bretschneider" <
notifications@github.com>:

**Comment by embix** [comment]
It's not that I want a localized git, in fact I'd prefer my dev tools in English. I guess git for Windows looks at my locale "English UI, German Keyboard" and figures "let's annoy that guy". While this is a separate issue, the original issue remains for all those poor developers having to work with localized tools.

**Comment by cdrnet** [comment]
Some git commands have a `--porcelain` option, which tells it that we want to parse the output. Its format is then supposedly stable between versions and independent of user settings (which hopefully includes the language).

**Comment by Stift** [comment]
I didn't even know that there is a localized version!
I think porcelain won't help as FAKE parses it already wrong. Just see the command above. Fake call `git status` to extract the branch. Better would be to call `git branch` and filter for '*'. Then this can't happen.

 @embix Do you know which git you are using and what installed it?

**Comment by forki** [comment]
PRs for using porcelain welcome!

**Comment by embix** [comment]
@Stift  [Git For Windows 2.10][gfw] installed to `C:\Program Files\Git\` and added to PATH

    $ git --version
    git version 2.10.0.windows.1

 [gfw]: https://github.com/git-for-windows/git/releases/download/v2.10.1.windows.1/Git-2.10.1-64-bit.exe

Lazy me would probably just use LibGit2Sharp for that.
