### ISSUE TITLE
Enable configuration of service failure actions in WixHelper (ServiceConfig)

### ISSUE THREAD

**Issue by alexey-tschudnowsky** [fsharp/FAKE#1411]
### Description

WixHelper does not enable configuration of failure actions for services to be installed. According to WixToolset documentation this should be possible using ServiceConfig child element of ServiceInstall element (http://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceinstall.html ,  http://wixtoolset.org/documentation/manual/v3/xsd/util/serviceconfig.html). Current version of WixHelper, however, doesn't implement a possibility to set ServiceConfig field for a ServiceInstall record (http://fsharp.github.io/FAKE/apidocs/fake-wixhelper-wixserviceinstall.html).

### Repro steps

1. Check documentation at http://wixtoolset.org/documentation/manual/v3/xsd/util/serviceconfig.html
1. Check https://github.com/alexey-tschudnowsky/FAKE/blob/master/src/app/FakeLib/WiXHelper.fs

### Expected behavior

WiXServiceInstall record contains a field for specifying a sequence of ServiceConfig objects. The objects are then serialized into corresponding XML Children Elements within the ServiceInstall-Element

### Actual behavior

There is no possibility to specify ServiceConfig configuration using records and fields from WixHelper

### Known workarounds

1. Create a new record type representing the ServiceConfig element structure
2. Implement the ToString XML serialization method on the ServiceConfig record type
3. Create a function for instantiating ServiceConfig objects
4. Extend the WiXServiceInstall record type with a field to hold a sequence of ServiceConfig objects

**Comment by dsyme** [comment]
Fixed by merged PR https://github.com/fsharp/FAKE/pull/1412
