### ISSUE TITLE
SGEN: MSBuildRelease

### ISSUE THREAD

**Issue by wahmedswl** [fsharp/FAKE#1413]
### Description

Running build in Visual Studio with Release config builds successfully but MSBuildRelease fail with SGEN error. I do have mixed assemblies but i have updated sgen.exe.config, changed Generate Serialization Assemblies to False and also, VS2015 is building fine. Is there anything i am missing?

### Repro steps

Project which have .Net 2 assemblies referred in .Net 4 project

### Expected behavior

It should build successfully as it is building in VS.

### Actual behavior

Its not building and giving up error
```
SGEN : error : Mixed mode assembly is built against version 'v2.0.50727' of the runtime and cannot be loaded in the 4.0 runtime without additional configuration
        information.
```

### Related information 

* Microsoft Server 2016 TP5
* Stable
* .NET Framework

Thanks

**Comment by matthid** [comment]
FAKE is probably picking up a different `sgen.exe` as the one you put the config in. Can you try running msbuild with detailed log (to see which `sgen.exe` it is running) and then check if there is a `sgen.exe.config` nearby. Closing this for now.
