### ISSUE TITLE
Nuget (3.5.0) push with PublishUrl errors out with ambiguous argument

### ISSUE THREAD

**Issue by seanamosw** [fsharp/FAKE#1415]
### Description

When publishing a package with the Nuget helper and using Nuget 3.5.0, the publish fails with a ```Ambiguous option 's'. Possible values: Source SymbolSource SymbolApiKey.``` error.

### Repro steps

1. Ensure you are using Nuget 3.5.0.
2. 
    ```fsharp
    NuGet (fun p ->
        { p with
            ....
            Publish = true
            PublishUrl = url
        })
        ...
    ```

### Expected behavior

The Nuget CLI should not throw a parameter error.

### Actual behavior

A parameter error is thrown by the Nuget CLI:
```Ambiguous option 's'. Possible values: Source SymbolSource SymbolApiKey.```

### Known workarounds

Manually push the package using the ```-Source``` parameter instead of ```-s```.

**Comment by forki** [comment]
could you please try to come up with a fix?
@emgarten @yishaigalatzer did nuget 3.5 have breaking changes?

**Comment by yishaigalatzer** [comment]
Cool catch. Just use the full name of the switch. The commandline can use a partial if there are no collisions. I believe we added a new switch which will break this shorthand.

Thinking out loud: we should keep it as is and perhaps call it out?

Thoughts?

**Comment by forki** [comment]
tbh we are probably much faster to fix it in FAKE. but will -Source break older nuget.exes?

**Comment by yishaigalatzer** [comment]
It shouldn't because they always had it.

For example:
-s
-so
-so

Should all still work

**Comment by forki** [comment]
thanks. 

just saw we already use -source in different command. so I think aad67ca is fine.

**Comment by yishaigalatzer** [comment]
That was fast!
