### ISSUE TITLE
In getting started tutorial, build.bat cant find "FAKE" package

### ISSUE THREAD

**Issue by aloisdg** [fsharp/FAKE#1416]
### Description

To learn FAKE, I started the [getting started tutorial](https://fsharp.github.io/FAKE/gettingstarted.html). When I run `build.bat`, the "FAKE" package is not found.

### Repro steps

Please provide the steps required to reproduce the problem

1. Download and unzip FAKE-Calculator

2. Run build.bat

### Expected behavior

![screenshot](https://fsharp.github.io/FAKE/pics/gettingstarted/afterdownload.png)

### Actual behavior

    Unable to find package 'Fake'.
    The system cannot find the path specified.
    Press any key to continue . . .

### Known workarounds

...

### Related information 

* Operating system: Windows 10

**Comment by aloisdg** [comment]
The Nuget.config file contains:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <solution>
    <add key="disableSourceControlIntegration" value="true" />
  </solution>
</configuration>
```

**Comment by forki** [comment]
Yes but there must another nuget.config in your machine that defines the
sources?

Am 04.11.2016 10:43 schrieb "Alois" <notifications@github.com>:

**Comment by aloisdg** [comment]
As far as I know, I dont have one. How can I verify it?

**Comment by forki** [comment]
Please replace contents of the file with:

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <solution>
        <add key="disableSourceControlIntegration" value="true" />
      </solution>
      <config>
        <add key="repositoryPath" value=".\packages" />
      </config>
      <packageSources>
        <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
      </packageSources>
    </configuration>

**Comment by aloisdg** [comment]
Still not working.

**Comment by forki** [comment]
I think it should. But what do I know about nuget.... 
We should update the sample to use paket. At least it would restore then

**Comment by forki** [comment]
new uploaded zip is using Paket instead of nuget. can you please give it a try?

**Comment by aloisdg** [comment]
@forki sure!

**Comment by forki** [comment]
I can now change the beginning of the tutorial since paket is already in place

**Comment by aloisdg** [comment]
I downloaded the [zip file](http://fsharp.github.io/FAKE/FAKE-Calculator.zip], ran "build.bat" and it worked as expected!

```
Paket version 4.0.0-alpha021
Downloading FAKE 4.44.2
59 seconds - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target Default:
<== Default

The resulting target order is:
 - Default
Starting Target: Default
Hello World from FAKE
Finished Target: Default

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Default    00:00:00.0008527
Total:     00:00:00.0480827
Status:    Ok
---------------------------------------------------------------------
```

**Comment by forki** [comment]
ok. cool.

updated docs a bit
