### ISSUE TITLE
FAKE process is killed, leaving long running Nunit processes running

### ISSUE THREAD

**Issue by xavierzwirtz** [fsharp/FAKE#1421]
### Description

FAKE process is killed, leaving long running Nunit processes running. This causes subsequent builds to fail due to the assemblies being locked

### Repro steps

1. Create a FAKE script that builds a .net project then executes Nunit tests.

2. Start the build

3. Kill the FAKE process while it is waiting for Nunit to finish

### Expected behavior

Nunit process would be killed when FAKE process is killed.

### Actual behavior

Nunit process is not killed. Persits and screws up subsequent builds.

### Related information 

Windows supports job objects, where we can register to have our child process killed when the we are killed or exit. [Here is a stackoverflow answer that implements it for C#.](http://stackoverflow.com/a/37034966/4358412)

Would a PR that implements this be acceptable?

**Comment by forki** [comment]
I thought we track child processes. So not sure what's wrong. But yes a fix would be appriciated

**Comment by xavierzwirtz** [comment]
Wouldn't surprise me if child processes are being tracked, but I don't think that helps in the case where FAKE is forcibly killed by another process.

**Comment by xavierzwirtz** [comment]
I am closing this, FAKE adequately handles this currently. Nunit is the one behaving badly. It leaves its child processes hanging around.
