### ISSUE TITLE
Fake overrides the version of newtonsoft.json.dll that a script references

### ISSUE THREAD

**Issue by kflu** [fsharp/FAKE#1423]
Details of the repro is in fslaborg/FsLab/issues/120. Basically, if a script loads a specific version of newtonsoft.json.dll that's **different** than the one Fake uses, no matter how the script references it using a combination of `#I` and `#r`, when the script is run by Fake, the referenced DLL is always wrong. Note that when the script is loaded by `fsi`, the referenced DLL is addressed correctly. I suspect this is because Fake is taking a dependency on newtonsoft.json.dll, but it should allow the script to use a different version of the DLL at its own choice.

**Comment by matthid** [comment]
I think this is related to our problem with fsharp.compiler.service (that's the reason we bundle it).

**Comment by kflu** [comment]
@matthid what would be the fix/next step?

**Comment by matthid** [comment]
@kflu not sure if there is a simple answer. In FAKE-vnext we will/should use .netcore `AssemblyContext`, so this might 'just work'. Even if we don't use `AssemblyContext` the situation will improve as we don't bundle dependencies anymore but resolve them via "Paket".

**Comment by kflu** [comment]
@matthid thanks for clarifying!

**Comment by matthid** [comment]
I think we need to close this by-design. We could do the same we do for FSharp,Compiler.Service (ie renaming via Mono.Cecil), but this is much more complicated as other references probably use `Newtonsoft.Json` indirectly as well (and we would need to rewrite them as well oO). 

I don't think we should go down that path and just wait for FAKE 5.
