### ISSUE TITLE
Kill Processes Recursively (Child Processes)

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1427]
### Description

I use Fake / Opencover / XUnit to run my unit tests under code coverage.
Normally this works perfectly.
Lately I've been having issues with timeouts.

You can set a timeout in `OpenCoverParams`, but this timeout only applies to the OC process itself.
So when the timeout elapses, the Opencover process is terminated, but any subprocesses are still running.
This caused issues where one build timed out, failed, and then subsequent builds failed to start because the xunit process was still running and locking files.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a unit test with Thread.Sleep(10 minutes)

2. Run this unit test under opencover, and set a timeout of 1 minute

3. Start the first build, it will fail with a timeout

4. Start a second build, it won't even be able to build because xunit is running and locking files

### Expected behavior

First I was thinking about creating a bugreport in opencover itself, but this issue is not limited to opencover and one child, because the testrunner itself could spawn new processes and so on.

What I would prefer is for Fake to walk the whole process chain and kill opencover and ALL sub processes when the timeout elapses.

Maybe this should be behind a configuration switch? Are there cases where childprocesses should not be killed?

I can't implement this in user code, because when I handle the exception in my Task, I can't get the process id of the OpenCover process to enumerate the children.

**Comment by matthid** [comment]
Related: https://github.com/fsharp/FAKE/issues/1280
I generalize this to kill the process tree of spawned processes.

**Comment by dedale** [comment]
Why is code duplicated between src\app\Fake.Core.Process\Process.fs and src\app\FakeLib\ProcessHelper.fs ? (e.g. ExecProcessWithLambdas)

**Comment by dedale** [comment]
What's the difference between Fake.Core.Process and Fake.ProcessHelper ? Can the latter use the former ?

**Comment by matthid** [comment]
@dedale One (Fake.Core.Process) is the FAKE 5 port where we make breaking API changes. I started the porting by trying to reuse code and do conditional compilation, but that wasn't successful at all.
So this is currently the way forward. Once the new API has stabilized we could review this, but honestly it's probably not worth it.

**Comment by matthid** [comment]
To clarify, you would implement such a bug feature in `Fake.Core.Process` only.

**Comment by dedale** [comment]
Cf. https://github.com/aspnet/Common/blob/dev/shared/Microsoft.Extensions.Process.Sources/ProcessHelper.cs for a sample implementation

**Comment by matthid** [comment]
This would be a nice feature to add and a PR is very welcome. Closing this for now.
