### ISSUE TITLE
The project name ist fake

### ISSUE THREAD

**Issue by henning-flmnn** [fsharp/FAKE#1430]
### Description

Fake seems to be a great tool.

Yet, using fake as a name is really confusing.
And it will hinder adoption of the project because of this.

Would you applaud if someone will come into your project, and say, hey, "let's build everything with delete makefiles"??? (to use an example with a name that members of the fake project do not yet know about)

Everybody not already knowing the project will go "what? why you wanna delete our build instead of actually doing it?"

So did I, so does everyone, and we always have to explain it, and it's tiring...

You may have thought it's funny when you created the project, and the project is really cool, but after the 10th time to explain it, 

### Repro steps

Please provide the steps required to reproduce the problem

1.Tell Members of your team who do not know about fake or even organisation with multiple teams you're now going to use fake makefiles for your project.

2. Watch the reactions, listen the questions.

### Expected behavior

People ask how the tool works.

### Actual behavior

People complain and wonder why the build is now faked and not actually done anymore, and how that's supposed to help development.

### Known workarounds

Have a project name with a non negative / faky conotation.

### Related information 

* Operating system - any
* Branch - any
* .NET Runtime, CoreCLR or Mono Version - any
* Performance information, links to performance testing scripts - any

**Comment by forki** [comment]
Yeah naming is hard. 
But this project is really well known in the ecosystem and its been around for 7 years or so. So we don't consider to change the name anymore. Sorry

**Comment by henning-flmnn** [comment]
Well, in a company with ~30 C# developers only 3 knew it here, and you list 10 companies using it on the webiste - so maybe for a project that exists 7 years it's now very well known and widely used. And maybe that's because of the name, because nobody wants to fake their build. 

Anyway, I'm just trying to help to spread your project - if theres no way to change, it be so  ;)

**Comment by nosami** [comment]
make, fake, cake, rake, psake

**Comment by alexeyzimarev** [comment]
@henning-flmnn your last comment is rather offensive. If you try to convince people that the project is being used by ten companies only and this is a big failure, mostly caused by the project name - you are just plain wrong.

**Comment by theimowski** [comment]
we're still missing bake, lake, take and wake

**Comment by alexeyzimarev** [comment]
and "brake"

**Comment by 7sharp9** [comment]
Just look at all the fake books:
https://www.halleonard.com/search/search.action?_c&seriesfeature=FKBK

**Comment by forki** [comment]
This concern comes up every now and then. And I heard all the puns. Really all of them. Multiple times. 

If I'd start the project again I would probably used a different name for a couple of reasons. But tbh the name never really hurt adoption. Even in large corporations FAKE is used. Some people introduced it as "F# Make" and avoid the naming problem in intro talks. 

I think if you ask around in your company then the problem that people didn't know it didn't come from naming. In my experience it's much more likely that it's a F# thing and therefore it's ignored by C# shops. Often people just use whatever Microsoft is providing. So many C# shops go with TFS, vanilla MSBuild or just no build script at all.

**Comment by henning-flmnn** [comment]
Thanks forki for the reply (and understanding that I do not try to tell you your problem is a failure!) and the wording idea in introductions ;)
Let's go on...

**Comment by forki** [comment]
It's also a good way to Google related topics.

Am 08.12.2016 1:05 nachm. schrieb "henning-flmnn" <notifications@github.com

**Comment by jayhill** [comment]
Use it as a noun instead of an adjective: "let's use Fake" instead of "use fake makefiles."
Do you have the same problem when discussing virtual machines?

**Comment by nosami** [comment]
I've been hearing loads about FAKE news in the press recently

**Comment by forki** [comment]
https://twitter.com/fsharpMake/status/799333928020705280

Am 08.12.2016 8:57 nachm. schrieb "Jason Imison" <notifications@github.com>:
