### ISSUE TITLE
Unable to define symbols for F# Interactive

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FAKE#1431]
### Description

I'm not able to figure out how to use `--fsiargs` and `-d:SYMBOL` to define symbols - I suppose I'm just doing something wrong here...

### Repro steps

```
$ packages/FAKE/tools/FAKE.exe --version
FakePath: C:\Tomas\Public\fsprojects\FSharp.Data.Toolbox\packages\FAKE\tools\FakeLib.dll
FAKE - F# Make "4.46.1"

$ cat build.fsx
#if AAA
printfn "AAA"
#else
printfn "Not AAA"
#endif

$ packages/FAKE/tools/FAKE.exe --fsiargs build.fsx --define:AAA
Not AAA
```

### Expected behavior

The `AAA` symbol should be defined and it should print `AAA`

### Actual behavior

It seems that the symbol is _not_ defined..

### Related information 

* Operating system: Windows
* Version: 4.46.1

**Comment by matthid** [comment]
It works like this

```
./packages/build/FAKE/tools/FAKE.exe -nc --fsiargs --define:AAA test.fsx
```

everything after the script is parsed as arguments for the script. Though it is not obvious and I had to look that up in the code as well ;)

**Comment by matthid** [comment]
We know that the command line parsing is basically broken. This is just another quirk :/
