### ISSUE TITLE
FAKE doesn't find MSBuild 15.0 (shipped with Visual Studio 2017)

### ISSUE THREAD

**Issue by opcon** [fsharp/FAKE#1442]
### Description

The MSBuildHelper module of FAKE does not find the correct executable for the MSBuild.exe shipped with Visual Studio 2017 RC (Community edition).

This is because MSBuild 15.0 (shipped with VS 2017 RC) is installed to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin`, rather then a separate MSBuild folder in Program Files as with earlier versions.

### Repro steps

1. Have Visual Studio 2017 RC installed (I have the Community edition, but I imagine it affects others as well).

2. Use the MSBuildHelper in a FAKE script to build a project, such as e.g.:

```
        !! (substructioDir + "src/**/*.csproj")
            |>
            match mode.ToLower() with
                | "release" -> MSBuildRelease "" "Build"
                | _ -> MSBuildDebug "" "Build"
            |> Log "AppBuild-Output:"
````

### Expected behavior

FAKE script builds the project successfully.

### Actual behavior

FAKE attempts to use the MSBuild.exe located in `C:\Windows\Microsoft.NET\Framework\v4.0.30128\`, due to the search paths listed here: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L25
which then fails because it uses an old version of MSBuild with C# 5 rather than C# 6

### Known workarounds

My current workaround is to see if the Visual Studio 2017 MSBuild directory exists, and if so set the build parameter MSBuild to use that:

```
    if (directoryExists msbuild2017Location) then
        setBuildParam "MSBuild" msbuild2017Location
```

The fix would be to add the VS 2017 MSBuild folder to the search paths listed here: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L25

A separate entry may be needed for every edition of VS 2017 (Community, Professional, Enterprise)

### Related information 

* Operating system: Windows 10
* Branch: Master, FAKE 4.47.1
* .NET 4.5

**Comment by matthid** [comment]
This was added.

**Comment by gonzogonzales** [comment]
Just as Information the Github-Links does not work.
