### ISSUE TITLE
Fake.YarnHelper

### ISSUE THREAD

**Issue by Yoshi325** [fsharp/FAKE#1449]
### Description

Any interest in a Yarn Helper being added to FAKE?

### Related information 

* https://yarnpkg.com/

I'm thinking about doing this, and wanted to gauge interest or allow for dissent about such a pull request.

**Comment by forki** [comment]
Yes that would be great

Am 13.01.2017 19:29 schrieb "Charles Y." <notifications@github.com>:

**Comment by vivainio** [comment]
What would it do?

I'd recommend downloading a single bundled yarn.js file (that the guys ship) and run that with "node ./yarn-bundled.js".

Any other way of installing yarn easily ends up in tears.

**Comment by Yoshi325** [comment]
@vivainio It would mirror Fake.NpmHelper which allows for install of dependencies for a package. As well as other sub-commands of yarn. NpmHelper requires that node and npm already be installed. My intention would be to follow the same pattern, rather than create a new one.

**Comment by docrinehart** [comment]
I'd use it... if I can find the time, I'd even be willing to help develop it.

**Comment by vivainio** [comment]
We have a separate script to do what YarnHelper would do (not directly triggered from Fake), but there are essentially 2 things a build script could need to do (as yarn doesn't require separate shrinkwrap phase):

- Install packages (i.e. run the command "yarn")
- Run a script in package.json ("yarn run"). This can be done with NpmHelper, as npm is installed by default in all node installations.

New helper task could seem like overkill for a naive observer here.

**Comment by M0ns1gn0r** [comment]
> as npm is installed by default in all node installations.
I personally uncheck the npm checkbox during node installation. Because there is no point in installing npm if I intend to use yarn.

**Comment by wooderz** [comment]
Just a heads up, I dealt with this last week:

http://fsharp.github.io/FAKE/apidocs/fake-yarnhelper.html
