### ISSUE TITLE
Running unit test cases gives an error , " access to c:/Users/Local/ApplicationData " is denid.

### ISSUE THREAD

**Issue by Kshitij-agrawal** [fsharp/FAKE#1456]
### Description

When I run unit test cases from FAKE , it gives an error Access to c:/Users/Local/ApplicationData is denied . 

And the Code is -

Target "Test" (fun _ ->
!! (testDir + "/NUnit.Test.*.dll")
  |> NUnit (fun p ->
      {p with
         DisableShadowCopy = true;
         OutputFile = testDir + "TestResults.xml" }))

Please explain the code and why this error is coming .

**Comment by matthid** [comment]
The code is trying to run some `NUnit` tests. Can you provide a minimal sample which yields the problem? Closing until we can reproduce.
