### ISSUE TITLE
[CscHelper] Build fails with VS 2017 without C# payload installed

### ISSUE THREAD

**Issue by CaringDev** [fsharp/FAKE#1457]
### Description

With VS 2017 RC (15.0.26020.0) installed *without C# payload* running `build.*` fails due to `CscHelper` failing to find `csc.exe`.

### Repro steps

1. Install VS 2017 without C# payload
2. Clone FAKE repo
3. Run `build.sh` or `build.cmd`

### Expected behavior

FAKE is built and tested. `CscHelper` uses latest available `csc.exe` available subject to `MsBuildEntry.msBuildExe` search order.

### Actual behavior

The build fails with
<pre>
Failures:  

compile csfiles to dll
¯ should compile to dll (FAIL)
System.Exception: Start of process C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\csc.exe failed. The system cannot find the file specified
  at Fake.ProcessHelper.ExecProcessWithLambdas@91-16.Invoke(String message) in .\FAKE\src\app\FakeLib\ProcessHelper.fs:line 91
</pre>

### Known workarounds

- Install C# payload
- Specify `VisualStudioVersion` for VS with C#

### Related information

This is
- independent of exact VS version.
- also affecting FAKE users.

I'd implement if @forki agrees with below proposed solution. Would you  rather want additional cleanup of touched files in the same or a separate commit?

### Proposed solution

CscHelper to scan folders following logic in `MsBuildEntry`. This should be backwards compatible modulo projects depending on *not* finding `csc.exe`.

Implementation should probably
- factor out MsBuild path search in `MsBuildEntry`
- use factored out bits to look out for
  - MsBuild
  - CSC

**Comment by hmemcpy** [comment]
Gah. It is now possible we'll have to match 'capabilities' of msbuild before building... I'll poke around, see if there's anything doable...

**Comment by hmemcpy** [comment]
But yeah, the proposal sounds reasonable... if csc.exe isn't found, there's not much FAKE (or msbuild, for that matter) can do. At least it could fail with a proper message...

**Comment by CaringDev** [comment]
Status update: leaving as is for now. F# in VS 2017 with F# only payload is broken too, payload dependencies are still changing and chances are this will be fixed. [see](https://developercommunity.visualstudio.com/content/problem/16112/minimal-fsharp-payload-not-working.html)

**Comment by matthid** [comment]
This should be fixed in the latest release (with https://github.com/fsharp/FAKE/commit/d4e132b3e1e7353312593339046ad69ea3e1fa85).

**Comment by CaringDev** [comment]
👍  seems latest VS also includes `csc` as a mandatory payload when installing F#
