### ISSUE TITLE
Revert System.Console.OutputEncoding to not break the shell

### ISSUE THREAD

**Issue by inosik** [fsharp/FAKE#1461]
### Description

When using any external tool from a FAKE script (MSBuild, test runners, Paket, …), after FAKE exits, the terminal is broken. I tried different console emulators (Windows console, PowerShell, ConsoleZ) and different shells (`cmd.exe`, PowerShell, bash), and all show the same behavior.

### Repro steps

1. Open a `cmd.exe` window.

1. Run FAKE with a target which invokes an external tool.

As I found out, [the assignment][assignment] of the output encoding before starting the process is the problem. The assigned value remains set after FAKE exits, which apparently breaks the input handling of the shell.

  [assignment]: https://github.com/fsharp/FAKE/blob/805ca9420e0234fe2ac8fe2033f28faeec2ebb40/src/app/FakeLib/ProcessHelper.fs#L27

### Actual behavior

After FAKE exits, I can't use the German Umlaut-characters. When I try to type an "Ä" for example, it doesn't appear on the screen, but now I'm able to delete already printed output from the console.

I reproduced this with `fsi`:

![Screencast](https://cloud.githubusercontent.com/assets/11393003/22290445/112e2be6-e301-11e6-942c-a77ca407b78d.gif)

### Known workarounds

Use FAKE in its own terminal window.

### Related information 

* Operating system: Windows 7
* .NET Runtime, CoreCLR or Mono Version: .NET 4.6.2

**Comment by inosik** [comment]
Changing back to `ibm850` encoding with `chcp 850` after running FAKE seems to fix this. But maybe FAKE should restore the old encoding?

**Comment by matthid** [comment]
Thanks for this! I noticed this several times in the past as well. In fact this is probably why I use git bash mostly (which doesn't seem to have this problem). I never managed to reproduce this or find the reason :)

**Comment by inosik** [comment]
> In fact this is probably why I use git bash mostly (which doesn't seem to have this problem).

I use the Git Bash most of the time, too, but that doesn't make any difference to me. The only terminal I tried, which doesn't seem to have this problem, is [Hyper](https://hyper.is).
