### ISSUE TITLE
Issue with iOSBuild target, not all items end up in the correct folder path

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/FAKE#1466]
### Description

There seems to be a path issue with iOSBuild target where not all items end up in the correct path

### Repro steps

Build an iOS project using the iOSBuild target:
```fsharp
let iosProject   = baseFolder </> iosFolder   </> "MyApp.fsproj"
let iosFolder   = "MyApp"

Target "Build-iOS" (fun () ->
    UpdatePlist Dev buildNumber version (baseFolder </> iosFolder)
    !! iosProject
    |> Seq.iter (fun project ->
        iOSBuild (fun defaults ->
            {defaults with
                ProjectPath = project
                Configuration = "Release"
                Platform = "iPhoneSimulator"
                Properties = ["Environment", "Dev"]
                Target = "Build"
                OutputPath = buildDir </>  "MyApp/Release/"
            }
        )
    )
)
```
### Expected behavior

All items output end up in the correct path 

### Actual behavior

Most items end up in the correct path but ipa files and iTunes artwork end up having the folder prefixed to the file names rather than placed in the folder:

![screen shot 2017-02-02 at 1 46 54 pm](https://cloud.githubusercontent.com/assets/588746/22552009/08f4f988-e94f-11e6-88b6-ef9715d97273.png)

### Known workarounds

None

### Related information 

* osx 10.11.6
* Fake (4.48)
* Mono 4.6.2

**Comment by inosik** [comment]
The path separator gets trimmed in the underlying [`MSBuild` task](https://github.com/fsharp/FAKE/blob/e842705560e95dd75dd2c6a78fb1ae62db545297/src/app/FakeLib/MSBuildHelper.fs#L408). Maybe we should even ensure that the separator exists at the end, in case of some string concatenation in a `.targets` or `.props` file.

**Comment by matthid** [comment]
Closing issues in the legacy code base, feel free to re-open if this still exists in fake 5
