### ISSUE TITLE
SignToolHelper is incomplete

### ISSUE THREAD

**Issue by jimfoye** [fsharp/FAKE#1471]
I am signing using an Extended Validation (EV) Certificate, which is stored on a USB stick. So there is no file, and thus no "/f" option used on the command line. I found that I could not use SignToolHelper but instead had to build my command line and call it using ExecProcess().

Also, I notice that there are command-line options for "signtool.exe /sign" that are not covered by SignToolHelper.

I am up for revamping this module if nobody else is working on it.

**Comment by matthid** [comment]
Yes that would be very welcome :)

**Comment by jimfoye** [comment]
OK, thanks. At this point, I might be better off waiting for this next major version of FAKE to come out?

**Comment by matthid** [comment]
Well there probably is always a reason to wait, but then it's never done :)
Basically we cannot migrate everything to netcore (its just to much work) from day one. As this is marked as "extension" it can be migrated afterwards. So there is no reason to not do it right now ;)

**Comment by jimfoye** [comment]
OK, I'll get started.

**Comment by jimfoye** [comment]
This is close to being finished.

**Comment by jimfoye** [comment]
@matthid Since this is my first contribution to FAKE, I wonder if you might take a quick look at

https://github.com/jimfoye/FAKE/blob/signtool/src/app/FakeLib/SignTool.fs

and let me know if I'm on the right track. I believe this is "FAKE 5 ready".

Thanks.

**Comment by matthid** [comment]
Yes the code looks fine. We have some docs on how to create a module which might help: https://fake.build/contributing.html#Porting-a-module-to-FAKE-5

Let me know if they don't or if we should clarify some points.

The only thing I saw:
 - We usually use the tool-exe path instead of the parent directory
 - We usually make the exe-path optional (but overridable) and try to find the exe in PATH or some default directories (compare with existing wrappers, the most advanced is probably MSBuild)

**Comment by jimfoye** [comment]
> We usually use the tool-exe path instead of the parent directory

Yeah I had that backwards, thanks. Fixed.

> We usually make the exe-path optional (but overridable) and try to find the exe in PATH or some default directories (compare with existing wrappers, the most advanced is probably MSBuild)

That's a lot of code! If this is the approach all FAKE tasks should be using, probably that code should be refactored and made generic for use by any task. (Though I'm not sure if that's really possible).

SignToolHelper took the exe path as a parameter, so as it is, we are not losing any functionality in this new module. Perhaps this is something that can be done later, as a separate step?

**Comment by matthid** [comment]
Yes sure I was just pointing out that this way you don't need to hardcode some magic string path in your build script...

**Comment by matthid** [comment]
Pr is https://github.com/fsharp/FAKE/pull/1690
