### ISSUE TITLE
fsi.CommandLineArgs results in error due to cached compiled script

### ISSUE THREAD

**Issue by bogdangaliceanu** [fsharp/FAKE#1477]
### Description

Trying to use fsi.CommandLineArgs in the build script results in a NullReferenceException, likely due to the compiled build script from the .fake folder being used. Deleting the .fake folder gets rid of the error, which then resurfaces as soon as the .fake folder is regenerated.

### Repro steps

1. Run any build script that accesses fsi.CommandLineArgs (I run it as **.\FAKE.exe build.fsx**). It will work.

2. Run the same script again. It will cause a NullReferenceException.

3. Delete the .fake folder and run the script again. It will work.

### Expected behavior

It should work all the time.

### Actual behavior

See description above. 

### Known workarounds

Delete .fake folder.

### Related information 

* Windows 8.1
* .NET 4.6.1
* FAKE 4.51.1

**Comment by matthid** [comment]
uah yeah probably...

**Comment by matthid** [comment]
@bogdangaliceanu Can you use the info from (System) Environment as a workaround?
This might not be fixed anytime soon - well except someone else wants to do it ;)

**Comment by bogdangaliceanu** [comment]
@matthid Yes, I can use an environment variable to get what I need.

Thank you :)

**Comment by matthid** [comment]
What I meant was https://msdn.microsoft.com/en-us/library/system.environment.getcommandlineargs(v=vs.110).aspx

**Comment by bogdangaliceanu** [comment]
I used FAKE's fsiargs-buildscriptargs

**Comment by matthid** [comment]
I don't think we have such differences in FAKE 5. However I think you probably cannot use `fsi.CommandLineArgs` anymore.
