### ISSUE TITLE
Wishlist: AndroidPublisher.PublishApk - add release notes to an apk submission

### ISSUE THREAD

**Issue by mcleodia** [fsharp/FAKE#1480]
Feature request - AndroidPublisher - the ability to create release notes on an apk submission.

Would be great if we could use this to automate pushing the release notes for a new version as well as the apk. (What's new in this version...)

Think it might be do-able via the api call:
https://developers.google.com/android-publisher/api-ref/edits/apklistings/update

Best wishes
Iain

**Comment by matthid** [comment]
This would be a nice feature to add and a PR is very welcome. Closing this for now.
