### ISSUE TITLE
FAKE FAKE.Core FAKE.Lib

### ISSUE THREAD

**Issue by wallymathieu** [fsharp/FAKE#1486]
### Description

What is FAKE.Core? Usually you reference FAKE, but there is also a FAKE.Core that looks like a tools project. FAKE.Lib looks like the one to use to write code against FAKE?

### Repro steps

1. Install FAKE.Core and reference it using paket. 
2. No Fake namespace is included
To alleviate the issue
1. Install FAKE.Lib

### Expected behaviour

I expected that there would be one tool package and one library package.

### Actual behaviour

Two different tool packages

**Comment by inosik** [comment]
FAKE.Core does only contain `FAKE.exe`. FAKE is the full package with extensions like [FAKE.IIS][fake.iis] and [FAKE.SQL][fake.sql] included, as the package description points out:

> FAKE - F# Make - is a build automation tool for .NET. Tasks and dependencies are specified in a DSL which is integrated in F#. **This package bundles all extensions.**

  [fake.iis]: https://www.nuget.org/packages/FAKE.IIS/
  [fake.sql]: https://www.nuget.org/packages/FAKE.SQL/

FAKE.Lib contains the actual code for all the tasks and can be used in other build tools. I use it in some custom FAKE extension libraries, to compile an assembly against `FakeLib.dll`.

**Comment by wallymathieu** [comment]
So it was only due to a misunderstanding on my part, since FAKE.Core and FAKE on NuGet looks to similar.
