### ISSUE TITLE
Xamarin iOS wrong AppExtensionReferences path when buidling with iOS Extension

### ISSUE THREAD

**Issue by Nickolas-** [fsharp/FAKE#1496]
Hi all,

When I building with FAKE iOS csproj, it give me exception 

`MTOUCH: error MT0063: Cannot find the executable in the extension WRONG_PATH (no CFBundleExecutable entry in its Info.plist)`

I found that `Target _CompileToNative` give me very strange path for field `AppExtensionReferences` like ProjectDir+OutputPath+EXECUTABLE_FILENAME .

So I'm guessing something wrong with `AppExtensionReferences="@(_ResolvedAppExtensionReferences)"` on FAKE , because when I building with Xamarin everything works correctly.

### Repro steps

Create iOS project with app Extension and try to iOSBuild.

### Expected behavior

It will builded

### Actual behavior

Give exception that it couldn't find an executable file.

### Related information 

FAKE 4.50.0

**Comment by Nickolas-** [comment]
Try to on FAKE 4.56.0 get the same results ?

**Comment by matthid** [comment]
FAKE just calls an external process. Can you look at the output what FAKE calls and try that by hand? Posting the call and if it fails without FAKE as well would help.
If you could figure out how the call should look to make it work that would be perfect.

Closing as its unclear what we can do....
