### ISSUE TITLE
Missing '--skipnontestassemblies' parameter for nunit3-console runner

### ISSUE THREAD

**Issue by amacal** [fsharp/FAKE#1498]
### Description

The '--skipnontestassemblies' nunit3 console parameter is not supported by any of the nunit3 helper functions or in the NUnit3Params class

### Repro steps

N/A

### Expected behavior

A parameter exposing the '--skipnontestassemblies' argument

### Actual behavior

'--skipnontestassemblies' argument is not available

### Known workarounds

N/A

### Related information 

N/A

**Comment by matthid** [comment]
Will be part of FAKE 5 https://github.com/fsharp/FAKE/pull/1608
