### ISSUE TITLE
Update Docs regarding FAKE.Deploy status page

### ISSUE THREAD

**Issue by duncanmak** [fsharp/FAKE#1511]
Hello, I followed the instructions on http://fsharp.github.io/FAKE/deploy.html and when I try to load localhost:8080/fake, I get a 405 page.

```
c:\FAKE\tools>fake.deploy
2017-03-29 19:05:38 [Information] Starting...
2017-03-29 19:05:38 [Information] Listening on http://localhost:8080/
2017-03-29 19:05:38 [Information] WorkDirectory is c:\FAKE\tools
2017-03-29 19:05:38 [Information] LogDirectory is c:\FAKE\tools\log
2017-03-29 19:05:38 [Information] Authorization is Off
```
I seem to be hitting the same error as reported here - http://stackoverflow.com/questions/41476140/fake-deploy-service-returns-405-error-when-200-is-expected

This is what I'm running:

```
c:\FAKE\tools>fake -v
FakePath: c:\FAKE\tools\FakeLib.dll
FAKE - F# Make "4.57.4"
```

**Comment by Stift** [comment]
I just investigated this a little bit, but it seems that the documentation is a little bit outdated, when it says that a call on GET /fake/ should report a status page. I assume that GET /fake/statistics/ should be sth like the status page. If so, then the documentation should be updated.

**Comment by duncanmak** [comment]
I looked at `/fake/statistics` and it returns a JSON with some information about the machine.

I'm still not sure if it's running or not, and how to proceed.

**Comment by Stift** [comment]
You have now a deploy agent running on that machine. Next step would be to call sth like `Fake.Deploy /deployRemote http://integration-1:8080/fake C:/Appdev/MyDeployment.nupkg` to deploy a package to that machine.

**Comment by matthid** [comment]
See this [Announcement](https://github.com/fsharp/FAKE/issues/1820). I'm closing this for now. We would still accept and release PRs at this point.
