### ISSUE TITLE
Wrong dependency order after updating to the latest Fake causes tests to be run before built

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FAKE#1515]
### Description

Before:

![image](https://cloud.githubusercontent.com/assets/738761/24885799/652c09f2-1e48-11e7-8387-74d0170694db.png)

After
![image](https://cloud.githubusercontent.com/assets/738761/24885748/215d77ec-1e48-11e7-8826-3dee43e3ab04.png)

### Repro steps

* Run `build All` on the current master of FSharp.Data - https://github.com/fsharp/FSharp.Data/commit/4012bd983932540bf08d98dd075169581f0c0053 - everything works as expected (first screenshot)

* Run `paket update` - https://github.com/ovatsus/FSharp.Data/commit/2571a154aef88202b6855f88f44f297131a9ac91 - wrong dependency order (second screenshot)

**Comment by forki** [comment]
@BlythMeister can you please take a quick look at this? I assume it's related to your recent changes.

**Comment by BlythMeister** [comment]
Yeah sure, can you please provide your dependency trees from the fsx file.

**Comment by forki** [comment]
Should be at the bottom of https://github.com/fsharp/FSharp.Data/blob/master/build.fsx

**Comment by BlythMeister** [comment]
Yeah just realised that.
From what i can see, there is no dependency between build tests, build and run tests.
Therefore that dependency structure states these things can run in any order.

If you have a dependency between targets you should state that in the dependencies for the build.

**Comment by forki** [comment]
I think the problem is at https://github.com/fsharp/FSharp.Data/blob/master/build.fsx#L126

@ovatsus you define that the targets should run before the runtest target. That condition is fulfilled. I think want you want is to reverse the arrow.

**Comment by forki** [comment]
@BlythMeister yes it seems to be unspecified in the script. I will send a pull request to fsharp.data. But it's still a bit unfortunate that we changed behavior here.

**Comment by BlythMeister** [comment]
Agreed, it's a shame the behaviour changed.  But arguably it's now correct in that it obeys the dependencies you set in your script rather than being down to chance/ordering.

If you don't state that b is dependent on a, then that states they can run in any order.

**Comment by forki** [comment]
It obeyed it before as well.

**Comment by BlythMeister** [comment]
True, but a lot of it came down to the order dependency was specified rather than making targets actually dependant.

I can try and make those orders be the same without having to make the change?
Would be an easy test case to add.

**Comment by forki** [comment]
I just looked at @ovatsus's project
It really relies on dependency specification order. Everywhere. We broke such assumptions.

**Comment by forki** [comment]
@BlythMeister I think we should restore that behaviour

**Comment by BlythMeister** [comment]
Ok, I'll have a look into why that situation does not work.
I can knock a test up and repo it.

**Comment by forki** [comment]
thanks!

**Comment by BlythMeister** [comment]
This is the commit that broke it i think... e87f690b9c4fe5189a1277ef5ea515f64d66b4a5

I didn't know that target specification ordering impacted target ordering.

**Comment by forki** [comment]
@BlythMeister it was never intended to do so, but since important project rely on it...

**Comment by BlythMeister** [comment]
Ahh as i expected...it worked by chance 😋

I will try and restore it.

**Comment by BlythMeister** [comment]
@forki  I've had a look at this, and it's because it's running the targets as early as possible now.

Since those "RunTests_" are not dependant on anything, they can run really early.

Previously targets ran in the order they were visited, hence why they would run later in the build.

The way the current solution works does take into account the ordering in the file to state the order of execution, but "RunTests_" is defined ahead of all the other targets.

The way i see it we have 2 choices.

1) accept the behaviour & users add missing dependencies
2) Revert the change to we go back to pure visit order and running targets as late as possible.

**Comment by forki** [comment]
I'm tending towards 2

**Comment by ovatsus** [comment]
The reason I did not specify test to depend on build, was that I wanted to be able to do 'build RunTests' without forcing to build again, that's very useful when manually editing some tests and just reruning. There are probably a lot of projects with similar issues as the FSharp.Data build script was then used as an example for Deedle and the for project scaffolding, so it would be great if we could get the old behaviour. Or if it's still possible to achieve what I had in a different way, I'm happy to change the scrip as well

**Comment by BlythMeister** [comment]
I feared you would say that...it feels wrong to me.

Things should run as early as they can.

Maybe we could have a flag set to retain old run function?

A "RunInVisitOrder" environment variable?

**Comment by forki** [comment]
> Things should run as early as they can.

why? that's not really needed

2017-04-11 10:06 GMT+02:00 Chris Blyth <notifications@github.com>:

**Comment by forki** [comment]
@ovatsus  there is a run-single-target command line parameter for FAKE. But you are probably not the only one

**Comment by BlythMeister** [comment]
@forki running dependencies early means it fails faster.

I am happy to revert the logic if you think that is best.

**Comment by forki** [comment]
yes we see that here. it fails pretty fast ;-)

**Comment by BlythMeister** [comment]
haha :)

@ovatsus i don't understand the scenario where you would want to run something you have yet to build

**Comment by forki** [comment]
@BlythMeister it's already built. he just wants to rerun tests

**Comment by BlythMeister** [comment]
@forki would you accept a configuration switch to use old logic?

that way, if someone has issues, they can revert to the old logic?

**Comment by forki** [comment]
tbh. I don't see why that's needed. We usually strive to be backwards compatible and don't want to break existing build scripts. usualy these scripts are not touched for very long time.
When we break such things we usally revert.

**Comment by BlythMeister** [comment]
ok, i'll get a revert in so single thread just runs in the order they are visited rather than as early as possible.

**Comment by forki** [comment]
yes that sounds good.

**Comment by BlythMeister** [comment]
revert raised, should probably be tested on your PR to f# data?

**Comment by BlythMeister** [comment]
i guess on a parallel build, it makes sense to run things as early as possible, but on a non parallel, it does not.

I think this code could be simplified to reflect that...

**Comment by BlythMeister** [comment]
@forki suggest this should be closed now?
