### ISSUE TITLE
Debugger.Launch not working on mono

### ISSUE THREAD

**Issue by raould** [fsharp/FAKE#1521]
### Description
Have not been able to get a way to debug my FAKE script. (1) can't get "--break" to work. (2) wouldn't know how to attach a debugger anyway probably. Ideally this should all be automagic, not an uphill battle.

### Expected behavior
There is some way I can pass "--break" to build.sh and have the FAKE script be something I can attach to with a debugger.

### Actual behavior
I can't find a way to pass "--break" either to build.sh or to the "raw" invocation of mono running FAKE.

### Related information 

build.sh runs
```
mono packages/FAKE/tools/FAKE.exe $@ --fsiargs -d:MONO build.fsx
```

so I have tried various things like
```
$ ./build.sh --break
Checking Paket version (downloading latest stable)...
Paket.exe 4.4.0 is up to date.
Paket version 4.4.0
0 seconds - ready.
Build failed.
Error:
The method or operation is not implemented.
-------------------
 FAKE usage
-------------------
...
```

```
$ mono packages/FAKE/tools/FAKE.exe --break
Build failed.
Error:
The method or operation is not implemented.
-------------------
 FAKE usage
-------------------
...
```

```
$@ --fsiargs -d:MONO build.fsx --break
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== Clean
... runs ok without ever stopping at a breakpoint!
```

etc. other variations on the theme, none of which have apparently worked.

Linux Ubuntu 16.04 64 bit
mono 4.8.1
FAKE 4.58.6

**Comment by matthid** [comment]
related https://github.com/fsharp/FAKE/issues/1402
Is there even a debugging story on mono/linux? If I need to guess the problem is probably that https://github.com/fsharp/FAKE/blob/master/src/app/FAKE/Program.fs#L55 (`Debugger.Launch()`) is not supported on mono.

**Comment by matthid** [comment]
merging with (almost) duplicate https://github.com/fsharp/FAKE/issues/1714
Hopefully there will be a better debugging story on netcore on linux ...
