### ISSUE TITLE
FAKE is kind of too slow for me, at least partially due to paket overhead

### ISSUE THREAD

**Issue by raould** [fsharp/FAKE#1522]
### Description

It is frustrating to have to wait for paket.bootstrapper.exe and paket.exe to run every time I want to do a build. It prevents a nice edit-build-run cycle.

It would be nice if the paket stuff were somehow optional?

### Repro steps

Just run FAKE, either via command line, or via VSCode Ionide plugin.

### Expected behavior

Fast builds.

### Actual behavior

Slow builds.

### Known workarounds

Since I am on Linux, I could hack the build.sh to not do any of the paket stuff.

### Related information 

Linux Ubuntu 16.04 64 bit
mono 4.8.1
FAKE 4.58.6

**Comment by forki** [comment]
So then just run fake. It's in no way attached to paket.exe. You can change that in your build script.
