### ISSUE TITLE
Helper request: FileHelper.AppendBinaryFiles

### ISSUE THREAD

**Issue by vivainio** [fsharp/FAKE#1524]
### Description

FileHelper has AppendTextFiles. There could also be FileHelper.AppendBinaryFiles (which could be more efficient).

AppendTextFiles is currently this:

```fsharp
let AppendTextFiles newFileName files = 
    let fi = fileInfo newFileName
    if fi.Exists then failwithf "File %s already exists." (fi.FullName)
    use writer = new StreamWriter(fi.FullName, false, encoding)
    files |> Seq.iter (fun file -> 
                 logVerbosefn "Appending %s to %s" file fi.FullName
                 ReadFile file |> Seq.iter writer.WriteLine)
```

The AppendBinaryFiles variant could just concatenate the bytes directly, without dealing with encodings and writing lines one by one.

Use case: I'm doing web asset concatenation with Fake (a'la gulp-concat), and it deeply pains me to see that it does lots of unnecessary work ;).

**Comment by vivainio** [comment]
Note: I can do a PR if you agree with the requirement in principle.

**Comment by matthid** [comment]
Yeah why not :)

**Comment by matthid** [comment]
Closing this out to clean the house, PR is welcome :)
