### ISSUE TITLE
How can I make build.cmd execute failed if “Running build failed” in jenkins.

### ISSUE THREAD

**Issue by MrSunSea** [fsharp/FAKE#1537]
### Description
I use jenkins to call build.bat to build my projects by using FAKE,but the jenkins marks the build.bat execute result as SUCCESS even though FAKE “Running build failed”.

### Repro steps

Please provide the steps required to reproduce the problem

1. In build.bat : 

@echo off
"tools\Fake.exe" "%1"
exit /b %errorlevel%

2. Call build.bat using a target will fail as  “Running build failed” in jenkins.

3.Check jenkins build result,it was SUCCESS .

### Expected behavior

I just want find a way that makes jenkins build result as failed while FAKE  “Running build failed”.

### Actual behavior

Jenkins build result,it was SUCCESS

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Operating system
* Branch:
* .NET Runtime,
* Performance information, links to performance testing scripts

**Comment by matthid** [comment]
@MrSunSea have you set an option in Jenkins to ignore the exit code? Usually when FAKE said that the build failed it returns an non-zero exit code. Jenkins should pickup the exit code and mark the build as failed.
Which version of FAKE are you using?

**Comment by MrSunSea** [comment]
@matthid  Thanks, I found the problem, It's because I did sth else after "tools\Fake.exe" "%1" ,So the jenkins can't get the exitcode  of FAKE.
