### ISSUE TITLE
RestorePackageHelper.RestorePackages doesn't work if project has .Net Standard / .Net Core sub projects

### ISSUE THREAD

**Issue by bradphelan** [fsharp/FAKE#1550]
### Description

I migrated two of my subproject to .Net Standard projects. The fake script failed to build to restore packages in a way that those two subprojects could handle. As .net standard projects don't use 'packages.config' files the implementation of RestorePackages is broken.

### Known workarounds

Instead of using

    RestorePackageHelper.RestorePackages

use

    RestoreMSSolutionPackages (fun p->p) "Foo.sln"

and ensuring a copying of __nuget.exe__ **version 4.*** is on the path.

**Comment by matthid** [comment]
I guess that is to be expected when switching to another system. Or I don't get what you are suggesting :)

**Comment by bradphelan** [comment]
What "other system"?  If I do 'nuget restore' from cli everything works
correctly. Why would a user not expect the Fake helper 'RestorePackages' to
work correctly also? I understand that nuget has changed a bit in its
behaviour from 3.* to 4.*. The current Fake helper makes the assumption
that you can just iterate through the packages files to do the job. This
will no longer work. Especially in a hybrid solution with a mix of .net
framework and .net standard/core projects it is not obvious why it doesn't
work.

**Comment by matthid** [comment]
Oh I thought we do 'dotnet restore' now...

**Comment by bradphelan** [comment]
At least not on the master branch.

https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/RestorePackageHelper.fs#L156

```
/// Restores all packages from NuGet to the default directories by scanning for packages.config files in any subdirectory.
let RestorePackages() = 
    !! "./**/packages.config"
    |> Seq.iter (RestorePackage id)
```

**Comment by matthid** [comment]
> The eco system is very confusing at the moment.

Oh yeah.

For now I'll close this as the solution is to either add another function to call `dotnet restore` on your sub-projects or use `RestoreMSSolutionPackages` if that works for you.
The `RestorePackages` helper is doing exactly what the docs say it does.

We might be able to re-visit this once the eco system has stabelized...
