### ISSUE TITLE
FakeLib.xml for FAKE.Lib nuget package

### ISSUE THREAD

**Issue by hafuu** [fsharp/FAKE#1555]
### Description
Please add `FakeLib.xml` to Fake.Lib nuget package.

[FSDN](http://fsdn.azurewebsites.net/) extracts API and API's document from nuget package.
Since Fake.Lib does not contain an XML document file, it can not display the document in FSDN.

### Repro steps

1. download `Fake.Lib` from https://www.nuget.org/

2. open `FAKE.Lib\lib\net451\` in `Fake.Lib`

### Expected behavior

`FakeLib.xml` exists.

### Actual behavior

`FakeLib.xml` dose not exist.

### Related information 

https://github.com/fsharp/FAKE/issues/1485
http://stackoverflow.com/questions/43860728/does-f-have-pursuit-or-hoogle

**Comment by matthid** [comment]
I guess this is a simple up-for-grabs. And I might just do it next time I stumble over this code path.
