### ISSUE TITLE
Defining constants using MsBuildReleaseExt will clobber all constants defined in FsProj files.

### ISSUE THREAD

**Issue by TOTBWF** [fsharp/FAKE#1557]
### Description

Pretty self explanitory, when you use the properties field of MsBuildReleaseExt to define constants, all other constants defined inside project files will be ignored. For an example project, see [here](https://github.com/TOTBWF/FakeBugDemo)

### Repro steps

Please provide the steps required to reproduce the problem

1. Inside of a fsproj file, use the <DefineConstants> property to define a constant.

2. Use conditional compilation directives using that constant

3. In fake, use `MSBuildReleaseExt "" [ ("DefineConstants", "TEST") ] "Rebuild"` to build

### Expected behaviour

The code compiles and runs with the behaviour specified by the constant.

### Actual behaviour

The constant is ignored, and the code will always compile as if the constant was not defined.

### Known workarounds

Don't use DefineConstants with MsBuildReleaseExt

### Related information 

* Operating system: Mac OS X 10.11.6
* Version Fake 4.61.2
* Mono 5.0.0.100, dotnet 1.0.4

**Comment by 0x53A** [comment]
afaik this is a "feature" of msbuild:

> MSBuild lets you set properties on the command line by using the /property (or /p) switch. These global property values override property values that are set in the project file.

https://stackoverflow.com/a/33719037/1872399

So, working as intended? ...
I don't know if there is a way in msbuild to provide defaults which can be overridden?

**Comment by matthid** [comment]
Yes I think this works as designed. I think the proper way is to use 
`<DefineConstants>$(DefineConstants);RELEASE</DefineConstants>` in the project file?

**Comment by 0x53A** [comment]
> I think the proper way is to use
<DefineConstants>$(DefineConstants);RELEASE</DefineConstants> in the project file?

No, the issue is that if you set ``/p:DefineConstants=xxx``, then you __can't__ override it later, the line ``<DefineConstants>$(DefineConstants);RELEASE</DefineConstants>`` will be ignored.

**Comment by matthid** [comment]
Thanks for clarifying for future readers :)

**Comment by 0x53A** [comment]
I'll remove this comment in a few minutes ... but I hate MSBuild so much ....
