### ISSUE TITLE
Glob Regex escapes ^ inside [^]

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fsharp/FAKE#1561]
### Description

I'm trying to glob all typescript files under a dir while excluding `*.d.ts` files with the regex
`src/**/*[^d].ts` which doesn't work because the magic for recursive directories makes the `[^d]` into `[\^d]` (whole regex produced: `^src\\(.*(/|\\))?([^\\/]*)\[\^d]\.ts$`)

### Repro steps

Please provide the steps required to reproduce the problem

1. Cut a hole in a box (or use a regex containing a negated character class such as `src/**/*[^d].ts`)

2. Put your regex in the box (or glob)

3. Profit

### Expected behavior

Expected it will match any file under the src directory that ends in `.ts` but doesn't end in `d.ts`

### Actual behavior

It matches nothing at all

### Known workarounds

No known workarounds although I'm sure there exist alternative regexes that may make it past the engine. I don't think the engine is doing something helpful here.

### Related information 

Link to the method in question https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/Globbing/Globbing.fs#L115

**Comment by matthid** [comment]
Usually people use
'''
 !! "*.ts"
 -- "*.d.ts"
'''

to achieve this

**Comment by matthid** [comment]
Closing this as I don't think we support regex at globbing at all. We only really support `*` and use "EnumerateFileSystem" APIs (which don't really support regex). So while this might be accepted with a thought through and tested PR, we probably won't do it (considering there is an easy workaround for your case)
