### ISSUE TITLE
[Website] Menu on mobile

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1568]
### Description

It seems like some items are overlapping on the mobile menu (shrink site width until you get a menu button left top and scroll to the bottom).

Do we have any css experts?

**Comment by matthid** [comment]
Slack: It's probably a problem with line breaks and too long menu entries.

**Comment by vlukash** [comment]
I believe the right way to fix this is just to hide text that doesn't fit into the mobile menu item width.

Also the common approach is to add `...` at the end of the string (text-overflow: ellipsis). So it looks like this:
![fake web](https://user-images.githubusercontent.com/8005242/30562649-13f13490-9c74-11e7-83f1-6d82e5aef7e3.jpg)

CSS changes:
```
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
```

**Comment by vlukash** [comment]
#1668
