### ISSUE TITLE
"fake build" alias for "fake run"

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1569]
### Description

We have now the [fake.build](https://fake.build) website. So we should make `fake build` a thing.

**Comment by rmunn** [comment]
Another thought: if multiple verbs are added to FAKE in the future, it's possible that one or more of them may end up conflicting with someone's target name in their pre-existing `build.fsx`. E.g., they may have a target named `test`, lowercase, which would conflict with a hypothetical future `fake test` verb.

If more verbs are added to FAKE, it would probably be good to document how to run them, e.g. "If you already have a task named `build`, you can run it with `fake run build`."

**Comment by matthid** [comment]
In fake 5 we currently have no shortcut syntax, so we currently don't have this problem. You always have to write `fake run` at the moment...
But yeah if we decide to add shortcuts we inherit this problem.

**Comment by matthid** [comment]
I think `fake build` should be an alias for `fake run build.fsx` (including the default name `build.fsx`) this way the most common use-case is more natural. The positional (optional) argument can be the "target".

**Comment by matthid** [comment]
Implemented in https://github.com/fsharp/FAKE/pull/1770
