### ISSUE TITLE
xbuild is used instead of msbuild on Mono >= 5.0

### ISSUE THREAD

**Issue by Nihlus** [fsharp/FAKE#1570]
### Description

When using MSBuildRelease on Linux, running under Mono >= 5.0, xbuild is used instead of msbuild. Mono 5.0 deprecated the xbuild tool in favor of the now open msbuild tool.

At present, this is not a blocking issue, but xbuild is deprecated and produces warnings about this when it is being built.

### Related information 

* Linux Mint 18.1
* FAKE 4.61.3
* Mono 5.0.1.1 (2017-02/5077205

**Comment by baronfel** [comment]
Thanks for this report! In the meantime, until we fix it, you can workaround this by specifying an `MSBuild` environment variable that points to msbuild directly when you invoke your FAKE script, like so:

```
MSBuild=`which msbuild` mono packages/FAKE/tools/.......
```

**Comment by Nihlus** [comment]
Thanks! I've implemented the workaround and it functions fine.

**Comment by varon** [comment]
This unfortunately now causes the build script to fail to execute now if mono is not installed, which is entirely possible on windows, or in the future, on platforms running dotnet instead of mono.

`./build.sh: line 35: mono: command not found`

Can we address that?

**Comment by matthid** [comment]
actually we do use msbuild for mono 5 upwards (https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L49)

I think our mono version detector fails on your system. Can you print the variable "monoversion" (https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/EnvironmentHelper.fs#L151) and tell us the result?

**Comment by Nihlus** [comment]
Ah, my bad. FAKE updated without me noticing, and it is now detecting msbuild correctly. Sorry for taking your time!
