### ISSUE TITLE
Problem finding a quoted path

### ISSUE THREAD

**Issue by psiLearn** [fsharp/FAKE#1572]
in build.fsx `ProcessHelper.tryFindFileOnPath` an not handle a path if it is surrounded by quotes (")

steps to reproduce:
Add quotes at the beginning and end of a path entry C:\Program Files (x86)\Yarn\bin => "C:\Program Files (x86)\Yarn\bin"
than the executable can not be found

Workaround:
remove the quotes, they are not needed anymore

System: Windows 7, Windows 10

**Comment by matthid** [comment]
Is this a regression. I

**Comment by psiLearn** [comment]
I run into problems building https://github.com/fable-compiler/fable-suave-scaffold when i looked into, I found that PATH entries containingillegal char are filtered out. In old Windows versions path entries with spaces needed quotationmarks in the beginnig and ending. So some of my path entries habe them still. But they are filtered out ans so some tools will not statt. The path to yarn.cmd was on my machine for some reasons withquotationmarks and build.fsx run exited with an error.

**Comment by matthid** [comment]
Ok according to:
 - https://serverfault.com/questions/349179/path-variable-and-quotation-marks-windows
 - https://superuser.com/a/452357
 - https://blogs.msdn.microsoft.com/oldnewthing/20060929-06/?p=29533

Therefore the correct way to set PATH on the command line is:

`set PATH="c:\programs (86)\somedir;c:\anotherpath;c:\and so on"`

If there is no compelling reason (like some popular program setting PATH incorrectly) I'd not consider this worth supporting.

**Comment by matthid** [comment]
@psiLearn Just to make it clear: It was you setting the PATH variable manually and not some external tool/installer, correct?

**Comment by psiLearn** [comment]
Yes used to do it this way, since I learned it 20 years ago.
