### ISSUE TITLE
Re-think warnings in FAKE -> Writing to stderr (might fail the build), but always have a "proper" way to fix them

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1574]
### Description

Currently we just never write on stderr on some systems. But it's just the proper thing to write there when we have warnings/errors. Most systems can be configured to ignore writes into the stderr, therefore we just need to go though and provide proper fixes -> then we can re-enable writing to stderr in those cases.

See https://github.com/fsharp/FAKE/issues/1573 for example

**Comment by Slesa** [comment]
Why exactly is the warning error for the missing dotnet SDK written at all? It seems that the only reason is that MSBuild.exe was found in a directory with "BuildSystem" in its name. Which is also the case when using VStudio 2017.

**Comment by matthid** [comment]
We now have a more customizable `Target` module which adds the flexibility to add customized listeners not writing to stderr (beta023).
