### ISSUE TITLE
FAKE duplicates all the NuGet packages when using paket.dependencies

### ISSUE THREAD

**Issue by inosik** [fsharp/FAKE#1589]
### Description

FAKE uses too much disk space, when its modules are defined in a `paket.dependencies` file.

### Repro steps

- Create a `build.fsx` file:

  ```fsharp
  (* -- Fake Dependencies paket.dependencies
  file ./paket.dependencies
  group netcorebuild
  -- Fake Dependencies -- *)

  #load ".fake/Fakefile.fsx/loadDependencies.fsx"

  open Fake.Core
  open Fake.Core.TargetOperators

  Target.Create "Clean" (fun _ -> printfn "Cleaning ...")
  Target.Create "Build" (fun _ -> printfn "Building ...")
  Target.Create "Deploy" (fun _ -> printfn "Deploying ...")

  "Clean" ==> "Build" ==> "Deploy"

  Target.RunOrDefault "Deploy"
  ```

- Create a `paket.dependencies` file:

  ```
  group netcorebuild
  source https://nuget.org/api/v2

  nuget Fake.Core.Targets prerelease
  ```

- Run `paket install`

- Run `fake run build.fsx`

### Expected behavior

FAKE uses the `packages/netcorebuild/` directory.

### Actual behavior

FAKE copies all the packages from `packages/netcorebuild/`, installed by Paket, to `.fake/build.fsx/packages/`.

The simple `paket.dependencies` from above already downloads ~350 MB of who knows what, and now I have all this stuff duplicated, for every project.

### Known workarounds

- Define FAKEs modules in the script

- Create a symlink from `packages/netcorebuild/` to `.fake/build.fsx/packages/` to avoid the duplication.

### Related information 

* FAKE 5.0.0-alpha-10

**Comment by matthid** [comment]
interesting, thanks for reporting. I thought this would already work :/

**Comment by matthid** [comment]
While that issue might still be there I now recommend to use a separate group with `storage: none` with fake 5.

**Comment by matthid** [comment]
I don't think this is the case anymore. In any case `storage:none` is the default and recommended everywhere.
