### ISSUE TITLE
Build failing with segfault on macOS during pack step

### ISSUE THREAD

**Issue by joefiorini** [fsharp/FAKE#1593]
### Description

When building (via `./build.sh`) on macOS 10.12.5 the build fails with a segfault while trying to use `dotnet pack`. The output is vague, so I can't figure out what the actual problem is. Check the [output of the entire DotnetPackage target](https://gist.github.com/joefiorini/8fd965441640a916c7501aecc813b6be). Can anyone see what the root cause is here?

### Repro steps

`./build.sh` on macOS 10.12.5 (might not repro for you, no idea)
### Expected behavior

A successful build

### Actual behavior

Build fails with segfault

### Related information 

* Operating system
macOS 10.12.5
* Branch
master
* .NET Runtime, CoreCLR or Mono Version
mono 5.0.1.1
```
⊕ ~/.dotnet/dotnet --version                                                                                                                                                                 
1.0.4
```

* Performance information, links to performance testing scripts

**Comment by matthid** [comment]
Looks like a mono-crash. Is this happening every time or one on occasion?

**Comment by matthid** [comment]
See https://github.com/fsprojects/Paket/issues/2393. 
@joefiorini  Can you report this to mono?
