### ISSUE TITLE
FSI Evaluation error in FSAC travis builds

### ISSUE THREAD

**Issue by rneatherway** [fsharp/FAKE#1595]
### Description

Travis builds are failing for FsAutoComplete: https://travis-ci.org/fsharp/FsAutoComplete/builds/242994717?utm_source=github_status&utm_medium=notification

The error says to open an issue here and cc @matthid 

```
error FS0193: Specified method is not supported.
CACHING ERROR - please open a issue on FAKE and /cc @matthid
```

### Repro steps

Run Travis tests on FSAC

### Expected behavior

Tests run

### Actual behavior

FSI Evaluation error

### Known workarounds
None
### Related information 

* Operating system: Linux
* fake: 4.55
* Mono Version: 5.0.1.1

**Comment by baronfel** [comment]
I believe that Fake 4.59 fixed this issue: https://github.com/fsharp/FAKE/blob/master/RELEASE_NOTES.md#4590---27042017

So it should just be a package update required here.

**Comment by rneatherway** [comment]
Thanks, testing now at https://github.com/fsharp/FsAutoComplete/pull/169

**Comment by matthid** [comment]
So I guess it worked :)

**Comment by rneatherway** [comment]
:-) Yes!
