### ISSUE TITLE
BuildWebsitesConfig not including content files.

### ISSUE THREAD

**Issue by wooderz** [fsharp/FAKE#1597]
### Description

BuildWebsitesConfig doesn't copy output files. I believe it needs to use _WPPCopyWebApplication rather than _CopyWebApplication

**Comment by wooderz** [comment]
Ok turns out I was wrong, and it's the copy line underneath only looks at files, not folders recursively.

PR incoming with a fix to this.

**Comment by wooderz** [comment]
Here we go: https://github.com/fsharp/FAKE/pull/1598

**Comment by matthid** [comment]
closing this as PR is open.
