### ISSUE TITLE
MSTest /test support

### ISSUE THREAD

**Issue by walliski** [fsharp/FAKE#1601]
### Description
Add support for using the /test parameter to specify which tests are to be run.

### Repro steps
Add a "Test" parameter for MSTest configuration which is a list of tests to run. 
`["namespace.test"; "namespace.test2"]`

### Expected behavior
Only the specified tests are run

### Actual behavior
The parameter is not recognised.

### Known workarounds
No?

### Related information 
--

**Comment by matthid** [comment]
This has been implemented.
