### ISSUE TITLE
Add support for /consoleloggerparameters

### ISSUE THREAD

**Issue by seanamosw** [fsharp/FAKE#1607]
### Description

The current `Fake.MSBuildHelper` module does not have support for the various `/consoleloggerparameters` options msbuild exposes.

A very useful one is `/consoleloggerparameters:ForceConsoleColor` which will output colors using ANSI color codes, so you can get colors in build agent console logs.

**Comment by matthid** [comment]
Yes we would accept a PR adding this feature. Also we currently think about redesigning the msbuild API and it might contain a "custom arguments" API in the future.
