### ISSUE TITLE
Fake Deploy unzips nuget package, leads to problems with filenames with spaces.

### ISSUE THREAD

**Issue by enriquein** [fsharp/FAKE#1609]
### Description

It seems that internally when Nuget packages files, it converts filenames that contain spaces (and potentially other special characters) to their "URL encoded" equivalent. However, if you manually unzip the Nuget package, the files are extracted with URL encoded names instead of the original filenames. Fake.Deploy seems to be unzipping the package, hence leading to this behavior. In our specific case, we can probably get by for now renaming the files that have spaces on them, but I would argue that this would be a bit unwieldy if there were many such files in a deployment.

I found [this thread](http://help.octopusdeploy.com/discussions/problems/30733-octoexe-url-encode-filenames) in the OctopusDeploy support forum where a customer was having a similar issue, and the suggestion was to run `nuget install Foo.Package -Source C:\Wherever -OutputDirectory C:\Foo` instead of unzipping.

### Repro steps

1) Create a deployment package that has files with spaces in their filenames.
2) Deploy the package.
3) Check resulting filenames.

### Expected behavior

I would expect filenames to look exactly the way that they were prior to packaging.

### Actual behavior

Files with spaces in their filenames are written to disk with their url encoded filenames instead.

### Known workarounds

Renaming files after deployment.

### Related information 

* Windows Server 2016
* Fake/Fake.Deploy 4.61.3
* .NET 4.6

**Comment by seburgi** [comment]
Hi,

we also ran into this issue for some generated files that contained spaces in their file names. A bit of digging around in the nuget code uncovered the culprit:
1) Uri escaping during packaging: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageCreation/Authoring/PackageBuilder.cs#L730
2) Uri unescaping during extraction: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/PackageArchiveReader.cs#L157

This suggests that nuget would also encode other special-chars in file names (not only spaces) but I haven't tried that out yet:
"a\\b\\test älter" => "a/b/test%20%C3%A4lter"

**Comment by matthid** [comment]
See this [Announcement](https://github.com/fsharp/FAKE/issues/1820). I'm closing this for now. We would still accept and release PRs at this point.

if this is not related to Fake.Deploy let me know.
