### ISSUE TITLE
Build fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by greenaj** [fsharp/FAKE#1616]
### Description

The build fails for master or 5.0.0-alpha010. I have mono 5.0.1.1 and dotnetcore 1.0.4.

### Repro steps

1. Clone repo

2. Run build.sh

### Actual behavior

Please provide a description of the actual behavior you observe. 

Some of the error output is shown below:

```
BuildSolution                 Failure
Total:                        00:02:05.1571983
---------------------------------------------------------------------
Status:                       Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building ./FAKE.sln failed with exitcode 1.
  2) MSB4086: /home/greenaj/build/FAKE/src/app/FakeLib/FakeLib.fsproj(450,11): A numeric comparison was attempted on "$(TargetFSharpCoreVersion)" that evaluates to "" instead of a number, in condition "$(TargetFSharpCoreVersion) >= 4.3.0.0 AND $(TargetFSharpCoreVersion) < 4.3.1.0 ".
  3) MSB4086: /home/greenaj/build/FAKE/src/app/FAKE/FAKE.fsproj(56,11): A numeric comparison was attempted on "$(TargetFSharpCoreVersion)" that evaluates to "" instead of a number, in condition "$(TargetFSharpCoreVersion) >= 4.3.0.0 AND $(TargetFSharpCoreVersion) < 4.3.1.0 ".
```

**Comment by vlukash** [comment]
I see the same behavior on my Ubuntu 16.04 (with Mono 5.0.1.1 and .NET Core 1.0.4 only)
But I can build the project successfully if I install 'fsharp' package:
```
sudo apt-get install fsharp
```

I believe 'fsharp' package uses Mono but not .NET Core .
Should the 'fsharp' dependency be removed or it's OK to use Mono in this case?

**Comment by fsoikin** [comment]
Same here. Windows 10, dotnet 2.0.0, but no Visual Studio.

**Comment by matthid** [comment]
Currently Mono is required to build the "full-framework" part of this repository as well as to execute test runners and other stuff. So yes mono is still required. Maybe this needs to be documented a bit better?

**Comment by matthid** [comment]
> Same here. Windows 10, dotnet 2.0.0, but no Visual Studio.

I'm not sure about this scenario I thought this should work since we added reference assemblies very recently.

**Comment by fsoikin** [comment]
It fails not due to lack of references, but due to undefined `$(TargetFSharpCoreVersion)` and `$(FSharpTargets)`. These seem to be dependent on Visual Studio being installed, and perhaps they're somehow emulated by Mono as well.

**Comment by matthid** [comment]
@fsoikin I think it might work after removing the following lines:
https://github.com/fsharp/FAKE/blob/41eb15bf9ed52a1cb336c61ec449096be8830c70/src/app/FakeLib/FakeLib.fsproj#L456-L482

They shouldn't be required as we use the `FSharp.Compiler.Tools` package.

**Comment by matthid** [comment]
Thanks for reporting, it someone can verify this I can fix it (a PR is welcome as well).

**Comment by fsoikin** [comment]
Yes, I was wondering about significance of those lines. I actually fixed it on my local by adding  `<TargetFSharpCoreVersion Condition="'$(TargetFSharpCoreVersion)' == ''">4.4.1.0</TargetFSharpCoreVersion>` above.

And what about this line: https://github.com/fsharp/FAKE/blob/master/src/test/Fake.Core.IntegrationTests/Fake.Core.IntegrationTests.fsproj#L73 ? Is it necessary?

**Comment by matthid** [comment]
@fsoikin AFAIK yes, and additionally that project is missing FSharp.Compiler.Tools reference atm.

**Comment by fsoikin** [comment]
Well, in that case, just removing the `$(TargetFSharpCoreVersion)` lines won't fix the issue. I've already verified that.

**Comment by matthid** [comment]
Well at least the error message should change. Sorry, I don't have a system ready to verify/test/fix this...

**Comment by fsoikin** [comment]
Yes, the error message certainly does change:

```
src\test\Fake.Core.IntegrationTests\Fake.Core.IntegrationTests.fsproj(73,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
```

**Comment by matthid** [comment]
Yes this is what I said above: It needs to have FSharp.Compiler.Tools reference. You can add that via `paket.references` of this project and then running `paket install`
(Sorry I cannot fix that today only write not helpful comments)

**Comment by fsoikin** [comment]
Oh, I didn't realize that merely adding the reference would (hopefully) fix it. Let me try that...

**Comment by fsoikin** [comment]
Replacing targets imports with `FSharp.Compiler.Tools` reference did not help. I am now (quite expectedly) getting this:

```
src\app\FakeLib\FakeLib.fsproj : error MSB4057: The target "Build" does not exist in the project.
```

In hindsight, I don't see how `FSharp.Compiler.Tools` was ever supposed to replace MSBuild targets.

**Comment by matthid** [comment]
If everything worked. `paket install` will add this line: 
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/FakeLib.fsproj#L3

And you can see in https://github.com/fsharp/fsharp/blob/master/FSharp.Compiler.Tools.Nuget/build/FSharp.Compiler.Tools.props that this defines everything to the bundled packages

with the additional line `<Import Project="$(FSharpTargetsPath)" />` everything should work.
