### ISSUE TITLE
Obsolete warning references none existing module in Fake5

### ISSUE THREAD

**Issue by WalternativE** [fsharp/FAKE#1622]
### Description

When using the newest version of Fake (as of writing this alpha013) using the Target construct of the 'legacy' Fake module the warning emitted references the Fake.Core.Targets module and suggests to use the new Target construct. Currently there is no such construct that fits this description (as far as I can see). I assume the Fake.Core.Target module in the Fake.Core.Targets package (also alpah013) would be the right place to look for the new functionality right now but I was not able to use it correctly I assume.

### Repro steps

- Create new project with paket and fake (reference fake prerelease from nuget)
- Use the Target construct from the Fake module

```fsharp
Open Fake

Target "Something" (fun () -> trace "Hello world!")
...
```
- Try to open the module linked in the deprecation warning

### Known workarounds

Just use the old Target construct - works fine.

### Related information 

* Windows 10 1703
* Package from Nuget (alpha013)
* net462

**Comment by matthid** [comment]
Recently I did an experiment with the targets module and updated it according to the design guidelines https://fake.build/contributing.html#API-Design.

So the API changed a bit: https://fake.build/core-targets.html

So your code now reads:

```
open Fake.Core

Target.Create "Something" (fun _ -> trace "Hello world!")
```

As this is an experiment feel free to give feedback about this change. Idea is that the IDE can help you more after `Target.` and give you available members for Target stuff.

Note that now all operators like `==>` need to be imported manually via `open Fake.Core.TargetOperators`. So Fake will no longer "pollute" the global namespace by default.

**Comment by WalternativE** [comment]
Thanks for the fast response - I'll adapt my scripts accordingly.

Regarding Feedback:
I really like the modularization because for small projects I don't need all the things but while playing around with a small setup (fake, paket, F# with simplified fsproj file, NUnit3, dotnet cli tooling and full .net framework on a Windows box) it was quite exhausting to get all moving parts to work. The import section of my build.fsx file currently looks like this:

```fsharp
#r "./packages/FAKE.Core/tools/FakeLib.dll"
#r "./packages/System.Console/lib/net46/System.Console.dll"
#r "./packages/System.IO.FileSystem/lib/net46/System.IO.FileSystem.dll"
#r "./packages/System.Diagnostics.Process/lib/net46/System.Diagnostics.Process.dll"
#r "./packages/Fake.Core.Globbing/lib/netstandard1.6/Fake.Core.Globbing.dll"
#r "./packages/Fake.Core.Context/lib/netstandard1.6/Fake.Core.Context.dll"
#r "./packages/Fake.Core.Environment/lib/netstandard1.6/Fake.Core.Environment.dll"
#r "./packages/Fake.Core.BuildServer/lib/netstandard1.6/Fake.Core.BuildServer.dll"
#r "./packages/Fake.Core.Tracing/lib/netstandard1.6/Fake.Core.Tracing.dll"
#r "./packages/Fake.Core.Process/lib/netstandard1.6/Fake.Core.Process.dll"
#r "./packages/Fake.Testing.Common/lib/netstandard1.6/Fake.Testing.Common.dll"
#r "./packages/Fake.DotNet.Testing.NUnit/lib/netstandard1.6/Fake.DotNet.Testing.NUnit.dll"
```
Is there a more concise way to get this working or am I doing it wrong to begin with?

**Comment by matthid** [comment]
> Is there a more concise way to get this working or am I doing it wrong to begin with?

Indeed. When using FAKE 5 (the not netcore version = the nuget package) you only need `FakeLib`, it contains all the new APIs as a convenience.

When using the netcore version (for example via `choco install fake -pre`) or as outlined in the docs (or `.travis.yml`), then you only need to specify the modules you want via `paket.dependencies` or a FAKE header (again it's in the docs). Manually adding `#r` lines is not required.

**Comment by WalternativE** [comment]
Ah I see. I think I have been looking at the wrong places when I was searching for answers. Just found the appropriate pages in the documentation. I am very sorry for wasting your time ^^;

**Comment by matthid** [comment]
Thanks for testing out the alphas! It's not like all the docs are up-2-date so....
Let me know if you run into problems or the docs can be improved in some way.

Also as outlined somewhere the API is still subject to change... So we might break your scripts using the new API. For that reason I suggest using the new netcore runner. It will "lock" versions and your scripts will still work until you are ready to update (obviously everything is still alpha :P)

**Comment by WalternativE** [comment]
I just use them for my exercism.io projects right now anyway (as an exercise! :D) so breaking changes are totally welcome (more challenges!). If I find anything of substance I'll let you know. Thank you again for your great work!
