### ISSUE TITLE
Fake 5 using local netcore

### ISSUE THREAD

**Issue by halcwb** [fsharp/FAKE#1633]
### Description

I am interested to know if it is a feasible option to start, and develop a local F# project without any system wide installation of a .net framework like mono, .net, netcore. It seems that Fake 5 is aiming to do this? I tried to set this up. But I am not sure this will be supported in the future and whether my setup and assumptions are right. 

My questions:

1. Is it possible, or will it be possible to setup, build and run an F# project on Windows, Linux, or macOS using a local netcore SDK, without any machine dependencies?
2. Is it possible to have intellisense in a code editor like Atom or Visual Code using this approach?
3. When running `./fake.sh` with this setup I get an error message when installing, but the installation seems fine and when I run a script, `./fake.sh run --script script.fsx`, then I get warnings about local caching, but the script runs fine as well. Are these relevant problems for my setup? 

I have gotten thus far:

### Repro steps

Please provide the steps required to reproduce the problem

1. Start with a fresh Ubuntu install. Add `curl` and `libunwind8` and `git` to the installed Ubuntu. 

2. Clone the Fake repository. 

3. Copy the `.fake.sh` and `script/obtain_fake.sh` files to a local directory.

4. Run `./fake.sh`. This will install a local netcore Fake installation. The script will report an error code but everything seems fine.

5. Create an fsx file and run the file with: `./fake.sh run --script file.fsx`. This will generate warnings about local caching, but again, it seems to work.

### Expected behavior

Being able to use the local downloaded netcore framework for developing and building.

### Actual behavior

It is possible with this minimal installation to setup a local fsharp project without any machine wide dependencies other than git, curl and libunwind8 on Ubuntu 14.04. You seem to be able to run an F# script file, however, I don't know how to actually build or have intellisense for an F# project.

### Known workarounds

Not applicable.

### Related information 

* Ubuntu, macOS, Windows
* CoreCLR or Mono

**Comment by matthid** [comment]
What you are seeing is what FAKE provides, which means a way to run F#/FAKE script files.
You are basically free to do whatever you want in your script (IE install other dependencies like a dotnet sdk).
So yeah you can certainly use this entry point. Some people seem to prefer to use "dotnet sdk" as entry point, but we will probably provide both entry points going forward.

Does this somehow answer this? Sorry for the late response.

**Comment by halcwb** [comment]
Thank you, indeed that was what I am trying to achieve. However, unfortunately dotnet core had the ability to start up a repl, like `dotnet repl` or `dotnet fsi`, but they removed this functionality. What I aim at is to provide a complete localized development environment without the need for any system wide installations of dotnet core. As far as I can tell is that when you use Fake to run a script, the script gets compiled?

**Comment by matthid** [comment]
Yes FAKE (5) compiles your script and will downloads all dependencies of your script via paket

**Comment by matthid** [comment]
I think this has been answered.
