### ISSUE TITLE
VSTest paths missing for VS 2017

### ISSUE THREAD

**Issue by walliski** [fsharp/FAKE#1635]
### Description

When only having VS 2017 installed you cant use `VSTest` due to it not finding the correct paths. 

### Repro steps

1. Install VS 2017

2. Run a FAKE target with `VSTest` in it

### Expected behavior

FAKE finds the correct files and runs tests.

### Actual behavior

FAKE throws an error.

```
Error:
System.Exception: VSTest: No tool path specified, or it could not be found automatically.
```

### Known workarounds

Specifying the paths manually using the parameters.

### Related information 

`FAKE - F# Make "4.62.5"`

### Other Comments

The question is, should FAKE have all these default installation paths in it, or is it up to everyone to supply different paths? We have added a couple of paths for MSTest also manually.

**Comment by Steinblock** [comment]
> ### Known workarounds
> 
> Specifying the paths manually using the parameters.

This is how you do it:

```
let vstestPaths = 
    [| @"[ProgramFilesX86]\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow";
       @"[ProgramFilesX86]\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow";
       @"[ProgramFilesX86]\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow";
       @"[ProgramFilesX86]\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow"|]

let vsTestExe = 
    if isMono then failwith "VSTest is not supported on the mono platform"
    else "vstest.console.exe"

let vstestToolPath =
       match tryFindFile vstestPaths vsTestExe with
       | Some path -> path
       | None -> ""

Target "Test" (fun _ ->

    !! (buildDir + "/*.Tests.dll")
    |> VSTest (fun p ->
        { p with
            ToolPath = vstestToolPath
        })

)

```

This is still an issue in master branch on different locations.

https://github.com/fsharp/FAKE/blob/2b028cb33738ed3d35a79730bd792c24d48a0f31/src/app/FakeLib/UnitTest/VSTest.fs#L8
https://github.com/fsharp/FAKE/blob/2b028cb33738ed3d35a79730bd792c24d48a0f31/src/app/FakeLib/UnitTest/MSTest.fs#L9
https://github.com/fsharp/FAKE/blob/2b028cb33738ed3d35a79730bd792c24d48a0f31/src/app/Fake.DotNet.Testing.MSTest/MSTest.fs#L13

while MSBuild and MSBuild Helper are already aware of the new locations 

https://github.com/fsharp/FAKE/blob/2b028cb33738ed3d35a79730bd792c24d48a0f31/src/app/Fake.DotNet.MsBuild/MsBuild.fs#L25
https://github.com/fsharp/FAKE/blob/2b028cb33738ed3d35a79730bd792c24d48a0f31/src/app/FakeLib/MSBuildHelper.fs#L24

> The question is, should FAKE have all these default installation paths in it, or is it up to everyone to supply different paths? We have added a couple of paths for MSTest also manually.

There is nothing wrong in supplying good default values. However defining constant values in different locations that are outdated with every visual studio version does not seem to be the best solution.

I would propose the following approach:

1. Get `nuget.exe` location from [here](https://github.com/fsharp/FAKE/blob/2b028cb33738ed3d35a79730bd792c24d48a0f31/src/app/FakeLib/RestorePackageHelper.fs#L12-12)
2. Load `nuget.exe` as an assembly
3. Get the msbuild directory which is a piece of cake with `nuget.exe`

```
     var console = new Console();
     var msbuildDirectory = MsBuildUtility.GetMsBuildDirectory(null, console);
    // msbuildDirectory = C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin on my dev machine
```
4. Based on this you could determine the path for mstest `..\Common7\IDE` and vstest `..\Common7\IDE\CommonExtensions\Microsoft\TestWindow`

With this approach you can rely on microsoft updating the nuget.exe with every visual studio version and being aware of the different locations.
