### ISSUE TITLE
I need a strategy to install multiple dotnet versions in parallel

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1640]
For https://github.com/fsprojects/Paket/pull/2664 I need the 2.x Sdk and the 1.x Runtime.

The issue is that ``DotNetCli.InstallDotNetSDK`` cleans up before it installs anything - so if I first install 1.x then 2.x, 1.x will be deleted.

Instead it should (maybe only if configured, so it doesn't waste too much space) merge the two installations.

For comparison, you can take a look at the folder structure created by the MS installers:

C:\Program Files\dotnet

![image](https://user-images.githubusercontent.com/4236651/29737320-d233c66e-8a0b-11e7-8281-adf87ecc4ca8.png)

![image](https://user-images.githubusercontent.com/4236651/29737329-e21210a4-8a0b-11e7-96c8-7e321e72f0d7.png)

and so on.

There is one dotnet.exe in the root (probably the latest?), but many dirs in parallel.

**Comment by matthid** [comment]
In FAKE 5 that thing is replaced with https://github.com/fsharp/FAKE/tree/master/src/app/Fake.DotNet.Cli which runs the "official" install script. Maybe that could be tweaked to have the same structure or works better ootb?

**Comment by 0x53A** [comment]
The use-case in Paket was "fixed" by just recompiling the affected binary against netcoreapp2.0.

But I would guess that this requirement (2.x Sdk + 1.x Runtime) will be common.

Are there any reasons against either moving Paket to Fake.5, or backporting this stuff to Fake.legacy? If backported, probably with a different method name...

**Comment by matthid** [comment]
@0x53A no real reason, just something historical I added this in the FAKE 5 branch before someone wrote this again in the master branch :/. You can use it directly via paket-files or the nuget package

**Comment by matthid** [comment]
So I guess this is solved.
