### ISSUE TITLE
Improve error message "Error during parsing of `paket.lock`"

### ISSUE THREAD

**Issue by purkhusid** [fsharp/FAKE#1642]
### Description

I'm getting an error when trying to run my FAKE script

```
Build failed.
Error:
Error during parsing of 'C:\SamskipDev\samskip-service-web-new\paket.lock'.
InnerException:
Could not parse 'framework: restriction: || (&& (< net45) (>= netstandard1.3) (< netstandard1.4) (< monoandroid) (< wpa81)) (&& (< net45) (>= netstandard1.4
) (< netstandard1.5) (< monoandroid) (< wpa81)) (&& (< net45) (>= netstandard1.5) (< netstandard1.6) (< monoandroid)) (&& (>= net46) (< netstandard1.4)) (&&
 (>= uap10.0) (< uap10.1)) (&& (>= netstandard1.6) (< netstandard2.0) (< monotouch) (< xamarintvos) (< xamarinwatchos) (< xamarinios) (< xamarinmac))' as ke
y/value pairs.
```

### Repro steps

Minimum repro:
[FakePaketRepro.zip](https://github.com/fsharp/FAKE/files/1259897/FakePaketRepro.zip)

1. Extract the repro and go to the root folder
2. Run `fake run ./Project/build.fsx`

### Expected behavior

Fake should run the build script

### Actual behavior

Produces and error

### Known workarounds

None

### Related information 

* Windows 10
* FAKE version 5.0.0-alpha014
* Paket Version 5.91.0

**Comment by sjuberman** [comment]
Does not fail with alpha015. Closing the issue

**Comment by matthid** [comment]
oO didn't expect that at all. Maybe we fixed something in paket and alpha015 got that fix. Thanks for testing!

**Comment by matthid** [comment]
We should improve this error message
