### ISSUE TITLE
TypeScript tsconfig.json or project support

### ISSUE THREAD

**Issue by kylesonaty** [fsharp/FAKE#1646]
### Description

I have a TypeScript project with an already established tsconfig.json. I want to be able to use target that project parameter for TypeScript projects. 

https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

### Proposed Task

```
TypeScriptCompilerTsConfig(fun p -> { p with Project = ".\somedirwithtsconfig"} )
```

### Expected behavior

Execute tsc.exe --project ".\somedirwithtsconfig"

**Comment by matthid** [comment]
Yes a PR with this would be accepted.

**Comment by matthid** [comment]
Closing this until PR is created :)
