### ISSUE TITLE
Running FAKE behind a proxy with custom credentials

### ISSUE THREAD

**Issue by ruhullahshah** [fsharp/FAKE#1660]
### Description

Fake fails behind a proxy with custom credentials (different than the default windows credentials)
Is there a way to set custom proxy credentials in FAKE?

### Details of the exception
Running build failed.
Error:
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at Fake.DotNetCli.downloadSDK@496(String tempDir, String downloadPath, String archiveFileName) in D:\code\FAKE\src\app\FakeLib\DotNetCLIHelper.fs:line 503
   at Fake.DotNetCli.InstallDotNetSDK(String sdkVersion) in D:\code\FAKE\src\app\FakeLib\DotNetCLIHelper.fs:line 533
   at FSI_0005.Build.clo@131-3.Invoke(Unit _arg2)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in D:\code\FAKE\src\app\FakeLib\TargetHelper.fs:line 626

---------------------------------------------------------------------

### Code Analysis

I went to the <a href="https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/DotNetCLIHelper.fs">source</a> of the exception and found that default credentials are always passed to the proxy which might not be true all the time

            let proxy = Net.WebRequest.DefaultWebProxy
            proxy.Credentials <- Net.CredentialCache.DefaultCredentials
            use webclient = new Net.WebClient(Proxy = proxy)
            webclient.DownloadFile(downloadPath, localPath)

**Comment by matthid** [comment]
Interesting, can you suggest a code-change via PR? To be honest, I have no idea what we need to do to help you.

**Comment by stmax82** [comment]
Could this be broken again in fake 5.0.0-beta29? I cannot get through the company proxy with the following error:

```
PS C:\svn\FooProj-trunk\Sources> fake build
Updating group Main in C:\svn\FooProj-trunk\Sources\.fake\build.fsx\paket.dependencies
Resolving packages for group Main:
Script failed with
-> Unable to retrieve package versions for 'Fake.IO.FileSystem'
   -- CLOSED --

   -- OPEN ----
      Fake.IO.FileSystem  (from C:\svn\FooProj-trunk\Sources\.fake\build.fsx\paket.dependencies)
      Fake.DotNet.MsBuild  (from C:\svn\FooProj-trunk\Sources\.fake\build.fsx\paket.dependencies)
      Fake.Core.Target  (from C:\svn\FooProj-trunk\Sources\.fake\build.fsx\paket.dependencies)
-> HttpRequestException: An error occurred while sending the request.
-> WinHttpException: Die Serververbindung konnte nicht hergestellt werden
PS C:\svn\FooProj-trunk\Sources>
```

The following piece of code to download something through the proxy works:

```
open System.Net
let proxy = WebRequest.DefaultWebProxy
proxy.Credentials <- CredentialCache.DefaultCredentials
let webclient = WebClient(Proxy = proxy)
webclient.DownloadString("http://www.google.com")
```
