### ISSUE TITLE
Error running Fake

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FAKE#1666]
### Description

    System.Exception: Start of process MSBuild.exe failed. The system cannot find the file specified
       at Fake.ProcessHelper.ExecProcessWithLambdas@103-16.Invoke(String message) in 
    D:\code\FAKE\src\app\FakeLib\ProcessHelper.fs:line 103

### Repro steps

Run `build All` on the current FSharp.Data master

### Related information 

* Only have Visual Studio 2017 15.3.4 is installed
* Building the solution in VS works correctly

**Comment by matthid** [comment]
You can try to specify msbuild path by setting the MSBuild Environment variable if FAKE is not able to find it.

Did you install Visual Studio in a non-standard path?

**Comment by ovatsus** [comment]
No, I installed on the standard path

**Comment by baronfel** [comment]
here are the lookup paths for the version of FAKE we're using in FSharp.Data at the moment:
```
let knownMsBuildEntries =
    [
        { Version = "15.0"; Paths = [@"\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin"
                                     @"\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin"
                                     @"\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin"
                                     @"\MSBuild\15.0\Bin"
                                     @"\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"] }
        { Version = "14.0"; Paths = [@"\MSBuild\14.0\Bin"] }
        { Version = "12.0"; Paths = [@"\MSBuild\12.0\Bin"; @"\MSBuild\12.0\Bin\amd64"] }
    ]

let oldMsBuildLocations =
    [ @"c:\Windows\Microsoft.NET\Framework\v4.0.30319\";
      @"c:\Windows\Microsoft.NET\Framework\v4.0.30128\";
      @"c:\Windows\Microsoft.NET\Framework\v3.5\"
    ]

```

Do any of these contain MSBuild on your machine, @ovatsus?

**Comment by ovatsus** [comment]
I have `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin`

**Comment by matthid** [comment]
Can you try setting the path manually? For example via `MSBuild` environment variable or check if some environment variable is accidentally set on your system?

**Comment by matthid** [comment]
One quirk that comes to mind are recent changes in the paket shell scripts (see https://github.com/fsprojects/Paket/pull/2754/files)

**Comment by ovatsus** [comment]
Found the issue, I had added `set VisualStudioVersion=14.0` the last time I published FSharp.Data -
 https://github.com/fsharp/FSharp.Data/pull/1045

I only have VS2017 now, and if I remove that fake runs, but I get a bunch of errors like `The module/namespace 'System.Collections.Generic' from compilation unit 'mscorlib'`, so I'll go back to VS2015
