### ISSUE TITLE
ApplicationVersion & MinimumRequiredVersion Update

### ISSUE THREAD

**Issue by BlythMeister** [fsharp/FAKE#1669]
### Description

Add ability to update ApplicationVersion & MinimumRequiredVersion in the same way assembly info can be updated

**Comment by matthid** [comment]
Can you please give a bit more context?

**Comment by BlythMeister** [comment]
These fields exist in the project files and are used as part of building a click once application.
Fake currently has that ability to update assembly info.
But these values do not get updated.

I would like the ability to have them updated, rather than craft my own way of doing it.

**Comment by matthid** [comment]
But these files are not part of assemblyInfo?
The "good" thing about AssemblyInfo files is that you can split the generated from the not generated attributes and let FAKE generate one part.

> the same way assembly info can be updated

I don't think this is viable here?

**Comment by BlythMeister** [comment]
I meant the same mechism, as in something standard I call with version number.
Not the same function call.

Instead of having to put logic such as I have in my build script here: https://github.com/BlythMeister/Gallifrey/blob/master/build.fsx

**Comment by matthid** [comment]
Closing old issue. I think we would accept a PR for this.
