### ISSUE TITLE
Bunch of new log files created when running FAKE

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FAKE#1676]
These started being generated when i run FAKE on FSharp.Data

InternalTrace.1424.FSharp.Data.Tests.dll.log
InternalTrace.14760.log
InternalTrace.5004.log
InternalTrace.7528.FSharp.Data.DesignTime.Tests.dll.log
nunit-agent_1424.log
nunit-agent_7528.log

Is there a way to make them not be created?

**Comment by matthid** [comment]
Which version?

**Comment by ovatsus** [comment]
4.63.2

**Comment by ovatsus** [comment]
Repro steps: `build All` in current FSharp.Data master

**Comment by matthid** [comment]
Could it be a nunit update? Can you compare the invoked command lines with the last working verson?

**Comment by ovatsus** [comment]
I tried going back to NUnit and NUnit.Runners 3.4.1, which was in FSharp.Data about a year ago, and at the time these log files were not generated, but the issue remains, so I think it was some fake change. Maybe before those files went to the temp folder and now they go to the local directory due to the way Fake invokes the nunit test runner?

**Comment by matthid** [comment]
Is this still a problem with fake 5?
