### ISSUE TITLE
ReadFile deprecated but no replacement?

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1679]
### Description

[ReadFile](https://github.com/fsharp/FAKE/blob/6ff09fbf5468f5718ea20c4cb9c3bd31c29a2e12/src/app/FakeLib/StringHelper.fs#L238) has been deprecated, and it suggests to use `Fake.Core.String` instead. But unless I'm missing something, there is no ability to read a file via `Fake.Core.String`.

### Repro steps

Please provide the steps required to reproduce the problem

1. Use `ReadFile`.
2. Run and view deprecation warnings.

### Expected behavior

An actual viable replacement should be available (and suggested).

### Actual behavior

Non-viable replacement is suggested.

### Known workarounds

* Continue to use deprecated API.
* Write your own API.

### Related information 

* Windows
* 5.0.0-alpha018

**Comment by matthid** [comment]
I think APIs like this moved to File

**Comment by kentcb** [comment]
You mean `System.IO.File.ReadAllLines` instead, right? Maybe I missed it, but I don't feel like the deprecation warnings pointed me in this direction.

**Comment by matthid** [comment]
No I meant Fake.IO.FileSystem.File.Read (or ReadFile)

Yes I think the warning needs to be improved... Thanks for reporting.
