### ISSUE TITLE
Removing "open Fake" results in "Shell is not defined"

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1680]
### Description

Trying to remove `open Fake` from my scripts as suggested by migration guide. However, I then can't run my script:
```
build-helpers.fsx(15,18): error FS0039: The value, namespace, type or module 'Shell' is not defined.
```

### Repro steps

Use `Shell` in a script and remove `open Fake`

### Expected behavior

Clear migration path provided.

### Actual behavior

No clear migration path provided.

**Comment by matthid** [comment]
Thanks for reporting these kind of issues.

**Comment by devcrafting** [comment]
Yep that's because some obsolete attributes are missing. Working on it : #1670

**Comment by matthid** [comment]
@devcrafting I was already on it, see the linked commit (https://github.com/fsharp/FAKE/commit/08dac27599f62e61f3d3f2d9535c6f25f67ffcf0) above

**Comment by devcrafting** [comment]
YEs I saw, but since I was working on PR #1670 to rework Obsolete messages for Fake.IO.FileSystem. But merge went well :).
