### ISSUE TITLE
Migrating CreateCSharpAssemblyInfoWithConfig

### ISSUE THREAD

**Issue by kentcb** [fsharp/FAKE#1681]
### Description

I'm quite sure this is my lack of F# skill tripping me up, but I can't see how to migrate a previous use of `CreateCSharpAssemblyInfoWithConfig` to FAKE 5. From what I can tell, I should just need:
```
open Fake.DotNet.AssemblyInfoFile

...

AssemblyInfo.CreateCSharpAssemblyInfoWithConfig ...
```
But that doesn't work:
```
build.fsx(179,18): error FS0039: The value, constructor, namespace or type 'CreateCSharpAssemblyInfoWithConfig' is not defined.
```

### Repro steps

Use `CreateCSharpAssemblyInfoWithConfig` without `open Fake.AssemblyInfoFile`.

### Expected behavior

Should migrate successfully.

### Actual behavior

Does not migrate successfully (my fault?).

**Comment by kentcb** [comment]
OK, by changing to `CreateCSharpWithConfig` I get past that problem, but now my `Attribute.Xxx` invocations are failing:
```
build.fsx(182,23): error FS0039: The field, constructor or member 'Version' is not defined.
```
Again, guessing my fault here, but not clear to me how to fix yet.

**Comment by matthid** [comment]
Yes the API changed, see https://fake.build/dotnet-assemblyinfo.html

I guess the migration warnings are outdated?

**Comment by kentcb** [comment]
Guess I just need a working example...
```
build.fsx(180,5): error FS0039: The value, namespace, type or module 'AssemblyInfoFile' is not defined. Maybe you want one of the following:
           AssemblyInfo
           AssemblyRef
           Assemblies
           AssemblyLoadEventArgs
```
This is despite having `open open Fake.DotNet.AssemblyInfoFile`. I've tried the suggestion to use `AssemblyInfo` instead, but that doesn't seem to help. 😕

**Comment by matthid** [comment]
Working sample: https://github.com/fsharp/FAKE/blob/2b280a638fd60d9f1221d2eb37cd902a5475daa1/build.fsx#L176-L256

Especially: Open `Fake.DotNet` instead of `Fake.DotNet.AssemblyInfoFile` 
and use `AssemblyInfoFile.CreateCSharpWithConfig` in the code

**Comment by kentcb** [comment]
Thanks!

**Comment by matthid** [comment]
Question is still what the underlying issue is. do we have outdated docs/ warnings. how could we make that easier to figure out?

**Comment by kentcb** [comment]
Yeah, good point. I think it's at least partly my fault as I'm not very proficient in F#.

But yeah, docs are absent and the deprecation warning didn't exactly point me in the right direction.

**Comment by matthid** [comment]
Making Fake easy to get started with is definitely a goal. but as long as we don't have real intellisense and stuff it will be quite hard...

Yes i'll keep this as reminder to fix that warning
