### ISSUE TITLE
[FAKE5] Module/Api to download Files.

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1684]
There should be a easy way to download a file :/

**Comment by vlukash** [comment]
@matthid 
What about a namespace and module name for this functionality?

Probably it could be under ```Fake.IO```. 
Or we can create a new namespace for HTTP/FTP modules.

Options for a module name:
- HTTP
- ?

Options for the namespace:
- Fake.Net
- Fake.IO
- ?

Please share your thoughts on this

**Comment by vlukash** [comment]
#1746

**Comment by matthid** [comment]
We have this now, thanks again!
