### ISSUE TITLE
FTP for FAKE 5

### ISSUE THREAD

**Issue by jimfoye** [fsharp/FAKE#1700]
The current FTPHelper module does not support secure FTP. I wrote my own FTP module which supports this, you can see it here:

https://github.com/jimfoye/FAKE/blob/ftp/src/app/FakeLib/Ftp.fs

This delegates the creation of the FtpWebRequest object to a function passed in by the caller. Although this slightly complicates the API, I've provided a default factory function to create this for the simple scenarios only supported by FtpHelper, so I don't think this should be a problem for anyone. The advantage is that now a caller can take over creating this and turn on SSL (or whatever else he needs to do). I've put an example of this in the comments.

There are some other things about FtpHelper that are not (IMHO) ideal, and I've addressed in this code:

The public API is quite busy. What does a build script need to do other than upload files (possibly deleting them first) to an FTP server? So I've narrowed the public API, and I think it's easier to use now. But you can't list remote folder contents - maybe somebody would disagree with that decision.

Why do validation on directory names? I think this module should not try to be a full-on FTP client, but merely make it easy to pass on FTP commands from a build script. If a folder name is unacceptable to a server, an FTP error will occur and the user will certainly learn of the problem. (Also note that while directory names are validated, file names are not). So I've just removed this.

Sometimes it's not real obvious when a path refers to a local path or a remote one on the FTP server. I've used a couple of type aliases that I think make things more readable. For example the signature for upload is

`FtpRequestFunc -> RemotePath -> LocalPath -> unit`

I don't claim this is all perfect as is, but it has worked well for me. I just don't know if everyone would agree on using it as a replacement for the existing FTPHelper module.

**Comment by matthid** [comment]
Please send a PR and introduce it as new FAKE 5 module (or make that your own project if you want, we can advertise in docs). Personally I don't have the requirement to use FTP but your statements sound reasonable.

**Comment by jimfoye** [comment]
I'm happy to submit a PR, of course. Regarding the FAKE 5 module, can I leave that you, as I did with the SignTool module? Also, note that I used `printfn` because tracing has changed in FAKE 5 and it's not clear to me what the replacement is.

If you're wondering why I seem to be struggling with these issues - I can no longer build FAKE (!) in Visual Studio 2015. It has something to do with paket (maybe) and/or .NET core (maybe) or perhaps it's because I'm still in 2015 (which I have to be in, because of problems with 2017). Of course I would love to get this sorted out, but I'm short of time, and I don't want to waste your time on this, you seem plenty busy enough!

**Comment by matthid** [comment]
> I'm happy to submit a PR, of course. Regarding the FAKE 5 module, can I leave that you, as I did with the SignTool module?

Yes, in fact I think I will handle the `SignTool` shortly.

> If you're wondering why I seem to be struggling with these issues - I can no longer build FAKE (!) in Visual Studio 2015. It has something to do with paket (maybe) and/or .NET core (maybe) or perhaps it's because I'm still in 2015 (which I have to be in, because of problems with 2017). Of course I would love to get this sorted out, but I'm short of time, and I don't want to waste your time on this, you seem plenty busy enough!

No worries, we would like to hear where people are struggling with. There is a ton of stuff to improve.

Will close this and wait for the PR :)

**Comment by jimfoye** [comment]
#1782
