### ISSUE TITLE
[FAKE5] Removing strings in Target

### ISSUE THREAD

**Issue by vbfox** [fsharp/FAKE#1705]
This is a proposition of a new API to replace / supplement `Target`

I wanted to do a PR but I don't really know what direction would be desirable so I opened this issue for discussion (I evoked it a month ago on twitter where @matthid responded https://twitter.com/matthi__d/status/905175619515936768 )

The syntax I propose would look like that : 

```fsharp
// Normal version taking a function in parameter
// The return value is of type TaskInfo & describe a task for the purpose of creating dependencies to it
let clean = Task "Clean" [] <| fun _ -> 
    CleanDir "out"

// Using the computation expression (prefered)
// IfNeeded make the dependency "soft" (can be renamed)
let assemblyInfo = task "AssemblyInfo" [ clean.IfNeeded ] {
    // ...
}

// Same with a normal dependency
let build = task "Build" [ assemblyInfo ] {
    !! "**/*.fsproj" |> MSBuildRelease "" "Rebuild" |> ignore
}

let runTests = task "RunTests" [ build ] {
    !! "**/*Test.exe" |> Expecto id
}

// The dependency here is conditional on an user defined parameter
let default = Task "Default" [ build; test.If(buildServer = AppVeyor) ] DoNothing

RunTaskOrDefault default
```

And here is a working FAKE 4 implementation : https://gist.github.com/vbfox/2eee346524d688af55ccc467e154e1b4 (That I already use in a few of my projects)

* So, does it look good ?
* Should it be included with a separate name (Like Task here) ?
* should it be named Target but in another namespace ?
* should it replace Target and I create a `Target.Legacy` module that mimik the current API ?

**Comment by devcrafting** [comment]
Like it a lot :+1

**Comment by sergey-tihon** [comment]
Will not this be very difficult to understand dependencies in the really large build script?

**Comment by matthid** [comment]
I agree with @sergey-tihon but I don't see why we shouldn't have both. In principle I like the idea a lot. We just need to see how it feels with real code ;). Especially if there are any side effects by using computation expressions (or some weirdness users need to know to write targets).

On the other hand we can introduce nice syntax for settings a target description and stuff (which currently nobody is really doing)

**Comment by matthid** [comment]
One early implementation was https://github.com/fsharp/FAKE/pull/1548/files

**Comment by matthid** [comment]
Closing old discussion. I think we now have the opportunity to experiment with new NuGet packages...
