### ISSUE TITLE
MSBuildHelper: trailing backslash does not get correctly escaped

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1709]
```
    |> MSBuildHelper.build (fun p -> { p with MaxCpuCount = Some (Some Environment.ProcessorCount)
                                              
                                              Properties =
                                              [
                                                "VCInstallDir", timRoot @@ @"packages\build\VisualCppTools.Community.D14Layout\lib\native\"
                                                "Include", timRoot @@ @"packages\build\Precast.WindowsSdk\tools\windows-kits\8.1\Include\um"

                                              ]})
```

```"VCInstallDir", timRoot @@ @"packages\build\VisualCppTools.Community.D14Layout\lib\native\"```

results in the following cmd line:

```/p:VCInstallDir="C:\Source\Tim\TimPrecast\packages\build\VisualCppTools.Community.D14Layout\lib\native\" /p:Include="C:\Source\Tim\TimPrecast\packages\build\Precast.WindowsSdk\tools\windows-kits\8.1\Include\um" ```

the ``\"`` escapes the quote marks and so does __not__ split the cmd line.

I tried to fix a similar issue in Argu (pr still pending), I can try to port it to the Fake helper: https://github.com/fsprojects/Argu/pull/88/files

**Comment by matthid** [comment]
Ah yeah those trailing slashes on windows :/. Yes a PR is very welcome.

**Comment by alexsorokoletov** [comment]
With latest mono/fake we get similar issue when there is a comma (`,`) in parameter value. MSBuild thinks it should be a separate parameter

**Comment by ChrSteinert** [comment]
I tried it on my machine and was not able to reproduce it. It set up a repro here https://github.com/ChrSteinert/FAKE1709Repro. Can someone tell me what I did wrong?

**Comment by 0x53A** [comment]
@ChrSteinert https://github.com/ChrSteinert/FAKE1709Repro/pull/1

**Comment by matthid** [comment]
Yes we probably need some real CLI Arg escaping API used throughout the FAKE code ...

**Comment by matthid** [comment]
I think this works now
