### ISSUE TITLE
Error using netcore app and vsts

### ISSUE THREAD

**Issue by nicolocodev** [fsharp/FAKE#1710]
### Description

I'm using FAKE with netcore app and I'm getting this error message from VSTS:

```
Build FAILED. 
        "d:\a\1\s\src\FooBar.Agent\FooBar.Agent.fsproj" (Build target) (1) ->
        "d:\a\1\s\src\FooBar.Shared\FooBar.Shared.fsproj" (default target) (2:2) ->
        (ReportAssetsLogMessages target) -> 
          C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(323,5): error : Assets file 'd:\a\1\s\src\FooBar.Shared\obj\project.assets.json' not found. Run a ] 
        "d:\a\1\s\src\FooBar.Agent\FooBar.Agent.fsproj" (Build target) (1) ->
        "d:\a\1\s\src\FooBar.Shared\FooBar.Shared.fsproj" (default target) (2:2) ->
        (RunResolvePackageDependencies target) -> 
          C:\Program Files\dotnet\sdk\2.0.0\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets(165,5): error : Assets file 'd:\a\1\s\src\FooBar.Shared\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [d:\a\1\s\src\FooBar.Shared\FooBar.Shared.fsproj]
```
### Expected behavior

Works on my machine, lol. I've been reading about FAKE and netcore, [found this](https://github.com/dolly22/FAKE.Dotnet) and [FAKE 5](https://fake.build/fake-gettingstarted.html) but I can't figure out how to get this working on VSTS 😞

**Comment by matthid** [comment]
I guess you run `dotnet pack` or something like that with FAKE? You could try to explicitly run `dotnet restore` before that. It feels like this is a dotnet problem and it feels like it should be reproducible with a clean local state (ie `git clean -xdf`)

**Comment by nicolocodev** [comment]
thank you! I finally got this working based on [fake build file](https://github.com/fsharp/FAKE/blob/master/build.fsx)

🍻
