### ISSUE TITLE
MSBuildHelper: can't add a logger (/logger)

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1712]
I need to add the [StructuredLogger](https://github.com/KirillOsenkov/MSBuildStructuredLog) to my build.

From the readme, I need to emit a cmdline like this:

```
msbuild solution.sln /t:Rebuild /v:diag /noconlog /logger:BinaryLogger,%localappdata%\MSBuildStructuredLogViewer\app-1.1.168\BinaryLogger.dll;1.binlog
```

Currently I hacked it like this:

```F#
    MSBuildHelper.MSBuildLoggers <- (sprintf "StructuredLogger,\"%s\";%s" ((getExtractedToolsDir()) @@ @"Microsoft.Build.Logging.StructuredLogger\lib\net46\StructuredLogger.dll") (logDir @@ "TimPrecast.buildlog") ) :: MSBuildHelper.MSBuildLoggers
    MSBuildHelper.MSBuildLoggers <- (sprintf "BinaryLogger,\"%s\";%s" ((getExtractedToolsDir()) @@ @"Microsoft.Build.Logging.StructuredLogger\lib\net46\StructuredLogger.dll") (logDir @@ "TimPrecast.binlog") ) :: MSBuildHelper.MSBuildLoggers
```

But it would obviously be preferrable if I didn't have to hack the global state.

There is ``FileLoggers`` with emits ``/fl`` and ``DistributedLoggers``, which emits ``/dl``, but there seems to be nothing that emits ``/logger``.

This could be solved either by adding an explicit property ``Loggers``, or by just adding a string list ``AdditionalArguments``.

Thoughts?

**Comment by matthid** [comment]
As we have already discussed I'd like the msbuild module to be reworked :P.

A nice side effect would be that this particular feature would be easy to add. And we could have convenience high order functions to add a particular logger to the arguments...

**Comment by 0x53A** [comment]
If I were to consider PRing this...

I'd add two properties, ``Loggers`` which maps to ``/logger`` and ``AdditionalArguments``, which is a string list and just gets appended to the end.

Would you agree?

**Comment by matthid** [comment]
@0x53A Maybe/probably, I'd have to see in the PR the exact changes :)

**Comment by matthid** [comment]
Relevant for https://github.com/fsharp/FAKE/issues/2096#issuecomment-423328448
