### ISSUE TITLE
MSBuild fails when VS2017(+) isn't installed in default directory

### ISSUE THREAD

**Issue by Luaancz** [fsharp/FAKE#1718]
### Description

For a Visual Studio 2017+ instance that isn't installed in the default directory, FAKE fails to find the latest MSBuild and setup proper MSBuild environment.

### Repro steps

1. Install Visual Studio 2017 on a clean Windows installation, make sure to change the target directory

2. Create a new Console Application in F# in Visual Studio

3. Use FAKE to invoke MSBuild on the project/solution

### Expected behavior

FAKE should invoke the correct MSBuild version and compile the solution just like Visual Studio or running MSBuild from a VS Developer Command Prompt.

### Actual behavior

Build uses the first version of MSBuild it finds (in my case, the one included in .NET 4.0) and fails:

> error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.

This is caused by two problems - using an old version of MSBuild, and missing environmental variables (in this case VisualStudioVersion, which is required for FSharpTargetsPath post-VS11).

### Known workarounds

Everything works correctly if you start the FAKE script in a developer's command prompt (sets the proper environmental variables as in previous versions of VisualStudio). It seems that setting the correct VisualStudioVersion and path to MSBuild is enough.

The ideal solution on Windows would be using _vswhere_ (either as a Nuget package or as a redistributable packed with Visual Studio Installer) for Visual Studio 2017+ support. This allows enumerating all instances installed by the Visual Studio installer, and choosing the latest correctly installed version with the required capabilities (e.g. MSBuild, F#...). This could be used to both find the correct MSBuild version, as well as set all the required environmental variables (maybe launch MSBuild in an environment setup by VsDevCmd?). For extra points, you could search for the VS version specified in the solution/project file rather than always picking the latest.

### Related information 

* Operating system - Windows 10
* .NET 4.6.2
* FAKE 4.61.3.0
* Visual Studio 2017

**Comment by matthid** [comment]
A PR for this would be highly welcome (to get a feeling on how this would look like).
I feel like it is OK for the MSBuild package to have an additional dependency on `vswhere` as long as we can make sure linux/macos still works.

**Comment by wallymathieu** [comment]
This also relates to finding `csc.exe` in FAKE 5

In another project we have done:
`build.cmd`:
```cmd
...
for /f "usebackq tokens=*" %%i in (`%~dp0\packages\vswhere\tools\vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
  set VSInstallDir=%%i
)

IF NOT EXIST "%VSInstallDir%\MSBuild\15.0\Bin\MSBuild.exe" (
  exit /b -1
)

packages\build\FAKE\tools\FAKE.exe build.fsx %* "VSInstallDir=%VSInstallDir%"
```

and then in `build.fsx`:
```fsharp
let visualStudioInstallDir = getBuildParamOrDefault "VSInstallDir" @"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\"
...
#if MONO
let extraCscParams = id
#else
let extraCscParams (parameters:CscHelper.CscParams) = 
  { parameters with ToolPath = visualStudioInstallDir </> @"MSBuild\15.0\Bin\Roslyn\csc.exe" }
#endif
```
in order to find `csc.exe` (from https://github.com/fsprojects/SyntacticVersioning/pull/24)

**Comment by matthid** [comment]
Closing in favor of https://github.com/fsharp/FAKE/pull/1752 which should solve this problem
