### ISSUE TITLE
Update getting started docs

### ISSUE THREAD

**Issue by wooderz** [fsharp/FAKE#1722]
Been using Fake 4 for a long time now, and tried to migrate. Got to say, to me it's nigh on impossible.. can we at least have a working Fake 5 example that isn't a "this is a bad example actually..." 

Sorry if I'm missing something, but I've been on this all day and getting no where. I could just go back to Fake 4... but I'm worried that that doesn't solve my issues, just postpones them?

**Comment by matthid** [comment]
It might help to describe at which point you were running into issues and what the issues actually are so that we can improve?

We definitely have issues in docs (and probably even some bugs as this is still beta), but we need to pinpoint them to fix.
At release date I hope that we have a getting started page to get started from scratch (in addition to the migration guide), but we currently still have a lot of moving parts...

Help and feedback/critics is welcome, but please give us a chance to improve (or even help with PRs).

**Comment by wooderz** [comment]
I'm struggling with just getting started with FAKE 5. There is no help at all in setting up a new script. I found the script on the https://fake.build/fake-commandline.html page - but this doesn't build. Could someone just put up a very simple script, such as on that page, that builds as a starting point? Once I've got that, I can see what's going on and would be more than happy to contribute to docs - until then, I think I'll have to stick to version 4.

**Comment by matthid** [comment]
> I found the script on the https://fake.build/fake-commandline.html page - but this doesn't build

Yes thank you very much, I'll fix that one.  It is very important that people report these kind of issues are it is quite hard to keep everything updated.

> Could someone just put up a very simple script

We have some very simple ones in the integration test suite: https://github.com/fsharp/FAKE/blob/master/integrationtests/core-reference-fake-core-targets/before/reference_fake-targets.fsx
In theory they all work with latest version as they are checked before we release.

The most simple script is just
```fsharp
printfn "Hello world"
```

With a `paket.dependencies` file:
```
// [ FAKE GROUP ]
group netcore
storage: none
source https://nuget.org/api/v2

nuget Fake.Runtime prerelease
nuget FSharp.Core prerelease
```

We have that [here](https://github.com/fsharp/FAKE/tree/master/integrationtests/core-implicit-dependencies-hello-world) as integration test.

**Comment by wooderz** [comment]
Awesome thanks @matthid that's exactly what I was looking for. I'll use these as a base and see how I get on. If I feel I can add any content to the docs I'll send through a PR.

Thanks again!

**Comment by wooderz** [comment]
OK, I got the integration test version to work, so we're moving forward. So now I'm just trying to get a clean to work.. so far I have:

`(* -- Fake Dependencies paket-inline
storage: none
source https://nuget.org/api/v2

nuget Fake.Runtime prerelease
nuget Fake.Core.Target prerelease
nuget FSharp.Core prerelease
-- Fake Dependencies -- *)

open Fake.Core
open Fake.Core.TargetOperators

// Directories
let buildDir = "./build/"

// ---------------------------------------------------------------------------------------------
// Clean build results
// ---------------------------------------------------------------------------------------------
Target.Create "Clean" (fun _ ->
    CleanDirs [buildDir;]
)

Target.RunOrDefault "Clean"`

But this results in the failure:

`Script failed with
-> Compilation failed:
   C:\Development\N17 Solutions\Infrastructure\build.fsx (20,4)-(20,13): Error FS0039: The value or constructor 'CleanDirs' is not defined.`

I know it's something i've done, but any help would be appreciated.. just help me find the stuff that used to work in v4 and I can start translating and writing docs.

Cheers!

**Comment by wooderz** [comment]
Just wondered if anyone had any ideas? @matthid

**Comment by seanamosw** [comment]
CleanDirs is in the Fake.IO.Shell module now.

For example:
```fsharp
open Fake.IO

Shell.CleanDirs ["test"]
```

**Comment by matthid** [comment]
Yes we no longer embrace using loose functions. We try to put everything in modules which makes stuff more organized (considering the size of FAKE).

**Comment by matthid** [comment]
The docs on fake.build have been reviewed (though some things might still change or slipped through).

But we can handle them one by one.
