### ISSUE TITLE
Please, use File.Open(fileName, FileMode.Truncate, FileAccess.Write)

### ISSUE THREAD

**Issue by vik-borisov** [fsharp/FAKE#1724]
https://github.com/fsharp/FAKE/blob/838f43e1e6ac18014b2515799fe7fa0e23186fbc/src/app/Fake.Core.Xml/Xml.fs#L148

Please, use 
`
File.Open(fileName, FileMode.Truncate, FileAccess.Write)
`

**Comment by matthid** [comment]
Makes a lot of sense, can you come up with a PR?
