### ISSUE TITLE
Create a nuget package for fake5

### ISSUE THREAD

**Issue by Slesa** [fsharp/FAKE#1731]
### Description

Fake can be installed via Choco. But that is not always a good option. On Build servers, choco may is not allowed. 

### Expected behavior

The old behavior with **nuget install Fake-runtime** would be great. Instead of packing all OS versions in one package, it is probably better to use different packages (if needed add all). 
So the resulting command would be **nuget install Fake-win-runner**

**Comment by matthid** [comment]
We publish all FAKE-modules on NuGet already. The new FAKE 5 runner will have a sdk-ready nuger package as well (such that `dotnet fake <>` works). It will most likely be called `dotnet-fake` but I couldn't get it running yet.

**Comment by matthid** [comment]
We have `dotnet-fake` now: https://fake.build/fake-gettingstarted.html#Install-FAKE
