### ISSUE TITLE
Using Windows.Choco.Pack with default OutputDir throws exception

### ISSUE THREAD

**Issue by ElijahReva** [fsharp/FAKE#1734]
## Fake.Windows.Choco defects. 
While using Fake I've discovered several minor issues with that module. I will put all of them here.

### Choco Pack

Using `Choco.Pack` throws `System.Exception: OutputDir ./Chocolatey does not exist.` if default OutputFolder used.

### Repro steps
```
#r @"..\packages\FAKE.5.0.0-beta010\tools\FakeLib.dll"

open Fake.Core
open Fake.Windows

Target.Create "Test" (fun _ ->
    Choco.Pack (fun p -> 
            { p with  
                PackageId = "Test"
                Version = "0.0.1"
                Authors = ["0.0.1"]
                Description = "Test"
                Title = "Test"
                PackageDownloadUrl = "//uri/d$/file.exe" })    
)

Target.RunOrDefault "Test"
```
### Expected behavior

Output appears in current folder.

### Actual behavior

    System.Exception: OutputDir ./Chocolatey does not exist.

### Known workarounds

Use ` Directory.create "Chocolatey"` before `Choco.Pack` call.

**Comment by ElijahReva** [comment]
I can't find the way to produce nupkg in current directory at all. I've tried to use "." of  `Fake.FileSystemHelper.currentDirectory` as OutputDir but getting the same exception in both tries.
```
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.FileInfo.MoveTo(String destFileName)
   at Fake.IO.Shell.MoveFile(String target, String fileName) in C:\proj\FAKE\src\app\Fake.IO.FileSystem\Shell.fs:line
 316
   at Fake.Windows.Choco.Pack(FSharpFunc`2 setParams) in C:\proj\FAKE\src\app\Fake.Windows.Chocolatey\Chocolatey.fs:l
ine 762

```

**Comment by ElijahReva** [comment]
Also, It could be much more useful if Fake will validate all required parameters before calling `choco pack` directly. 
It already does for _Title_ and _PackageDownloadUrl_ 
When
```
Directory.create "Chocolatey"
Choco.Pack (fun p -> p )  
```
Then
```
(Inner Exception #0) System.Exception: chocolateyInstall.ps1 need at least Title and PackageDownloadUrl to be cr
eated.
   at Fake.Windows.Choco.createChocolateyInstallPs1(ChocoPackParams parameters, String outputDir) in C:\proj\FAKE\src
\app\Fake.Windows.Chocolatey\Chocolatey.fs:line 601
```

But if I even if set them - I get next output after choco pack got called.
```
Chocolatey v0.10.7
Id is required.
Version is required.
Authors is required.
Description is required.
```

**Comment by matthid** [comment]
yes I think the module is quite new. please feel free to send a pr to improve the situation.
In any case thanks for the detailed report

**Comment by ElijahReva** [comment]
@matthid Thank you for the response! I'm planning to address those issue this weekend. 
There are several more bugs that have workarounds
- `Choco.Pack` parameter `AdditionalArgs` appended twice. 
```
Target.Create "Test" (fun _ ->
    "Test.0.0.1.nupkg"
    |>Choco.Push (fun p -> 
        { p with 
            AdditionalArgs = "--forse" 
            } )    
)
```
      C:\ProgramData\chocolatey\bin\choco.exe push "Test.0.0.1.nupkg" --source https://push.chocolatey.org/ -y --forse--forse 

Workaround to put space in the end.

- `Choco.Pack` ApiKey got traced. Workaround to use `Process.setEnableProcessTracing  false` before call.

Issues with visibility of  functions to applying templaates and raw choco callers:
- `createNuSpecFromTemplate ` 
- `createChocolateyInstallPs1FromTemplate ` 
- `createChocolateyUninstallPs1FromTemplate ` 
- `callChocoPack` 
- `callChoco` Note: should use `FindFile` if no exePath param specified.
- `getTempFolder ` should have ability to specify explicitly

**Comment by matthid** [comment]
Is this now solved?

**Comment by matthid** [comment]
I'm closing this for now but by any means PR is welcome :)
