### ISSUE TITLE
Paket.Pack uses outdated syntax

### ISSUE THREAD

**Issue by Szer** [fsharp/FAKE#1736]
Usage of this command:
`Paket.Pack(fun p -> { p with OutputPath = "bin" })`
invokes this:
`paket pack output "bin"`

which produces this error:
> Please use the new syntax: 'output' is the default argument and should be omitted.

Currently Paket `pack` command should be invoked like this:
`paket pack "bin"`

I think this is very trivial change in this line:
https://github.com/fsharp/FAKE/blob/0341a2e614eb2a7f34607cec914eb0ed83ce9add/src/app/Fake.DotNet.Paket/Paket.fs#L135

**Comment by artarf** [comment]
It would be nice to include this to version 4 also.
