### ISSUE TITLE
Fake.Dotnet.Cli.DotNetInstallerOptions Default branch

### ISSUE THREAD

**Issue by auxym** [fsharp/FAKE#1739]
### Description

Hello, I would like to suggest that the default branch to download the installer be updated. I'm not submitting a PR because I don't think it's worth it for a one-string-fix, but see [here](https://github.com/fsharp/FAKE/blob/0341a2e614eb2a7f34607cec914eb0ed83ce9add/src/app/Fake.DotNet.Cli/Dotnet.fs#L94)

I'd suggest either `master` or, if we fear that the script might be unstable (which I doubt), then maybe `release/2.0.0`?

### Repro steps

The old script from the currentdefault `1.0.0` branch was giving me all sorts of weird powershell errors when I was trying to specify the `Current` or `2.0` channel. For example, try this:

```F#
Target.Create "InstallDotNetCLI" (fun _ ->
    DotnetCliInstall (fun opts ->
        {opts with 
            Channel = Some "2.0"
            }
        )
)
```

### Expected behavior

Error free install of dotnet 2.0 using default options :)

### Actual behavior

Various errors from the old ps1 script, for example:

`Failed to download https://dotnetcli.blob.core.windows.net/dotnet/Sdk/current/latest.version.  StatusCode: 404, ReasonPhrase: 'The specifblob does not exist.', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:`

`dotnet_install.ps1 : Cannot convert argument "bytes", with value:"9e724ed14e4213b7300af702c16244a242acc56b`

### Known workarounds

Manually specifying the installer options:

```F#
Target.Create "InstallDotNetCLI" (fun _ ->
    DotnetCliInstall (fun opts ->
        {opts with 
            Channel = Some "2.0"
            InstallerOptions = (fun opts -> {opts with Branch="master"})
            }
        )
)
```

### Related information 

* Win10
* Fake 5.0.0 beta 10 from Nuget
* .NET 4.6.2

**Comment by matthid** [comment]
> I'm not submitting a PR because I don't think it's worth it

It is always worth it :). For example, we can see in the builds that everything is still green and I can simply click merge ;).

Please send a PR. I guess we should change the default branch to rel/2.0.0 now? I also guess that the branch should always matches/works with our suggested default version. Can we add a test for that?

**Comment by auxym** [comment]
Noted! I'll look into putting together a PR with a test.

**Comment by auxym** [comment]
@matthid BTW, I was also thinking it would be useful to check the user's path for `dotnet`, additionally to [`DefaultDotnetCliDir`](DefaultDotnetCliDir) before installing a new copy. Something like try running `cmd /c dotnet --version` / `sh -c dotnet --version` and if the returned version satisfies a given constraint, skip the install and use whatever is on the path. What do you think? I could look into a separate PR for this.

**Comment by matthid** [comment]
Yes a PR would be nice to discuss the changes. In principle I agree that we can reuse an existing installation if either the installed version matches or the user has not specified a version explicitly in the fake script.

**Comment by matthid** [comment]
The issue itself will be fixed with beta012
