### ISSUE TITLE
Example script to multi-target library

### ISSUE THREAD

**Issue by phatcher** [fsharp/FAKE#1740]
I'm trying to convert a library that targets .NET 4.5 so that I can have a NETSTANDARD version as well.

If I build it in VS 2017 I get all the versions output, but I can't get the correct syntax when invoking from Fake - does any one have a working example?

**Comment by KongWooDongBang** [comment]
Hello,

have you tried something like this:

```
#r "../packages/FAKE/tools/FakeLib.dll"
open System
open Fake.Core
open Fake.Core.TargetOperators
open Fake.Core.Globbing.Operators
open Fake.IO

let execContext = Fake.Core.Context.FakeExecutionContext.Create false "build.fsx" []
Fake.Core.Context.setExecutionContext (Fake.Core.Context.RuntimeContext.Fake execContext)

let buildDir = "./bin2"
let projFile = !! ("./*.fsproj") |> Seq.head

Target.Create "Clean" ( fun _ ->
    Shell.CleanDir buildDir
)

Target.Create "BuildNet45" ( fun _ -> 
 Fake.DotNetCli.Build
  (fun p -> 
   { p with Framework = "net45"; Output = buildDir + "/net45";  Project=projFile}))

Target.Create "BuildNetStandard" ( fun _ -> 
 Fake.DotNetCli.Build
  (fun p -> 
   { p with Framework = "netstandard1.6"; Output = buildDir + "/netstandard1.6";   Project= projFile }))

"Clean"
==> "BuildNetStandard" 
==> "BuildNet45" 
  
Target.RunOrDefault "BuildNet45"
```

**Comment by phatcher** [comment]
Ah, I'll give that a try - I thought I could do it with one invoke of msbuild and it would take care of the multi-platforming on its own

**Comment by matthid** [comment]
I guess it did work?

**Comment by phatcher** [comment]
@matthid What I did in the end was change my project files to VS2017 format, introduce the multi-targeting and then set it to build the NuGet packages on compile

Still have to flip over to using "dotnet test" rather than the NUnit console to run the tests; will probably write it all up once it's working
