### ISSUE TITLE
A few typos on the fake.build website

### ISSUE THREAD

**Issue by mshulman** [fsharp/FAKE#1747]
### Description

There are a few typos on the fake.build website. I'd like to make a PR to fix, but I don't see where the site is in the git repo.

Is the fake.build website source in git somewhere?

**Comment by matthid** [comment]
Yes please send a PR, the documentation is [here](https://github.com/fsharp/FAKE/blob/master/help/markdown/contributing.md#documentation) Basically the stuff is part of the `help` folder or generated by code-comments.

Let me know if we can improve that section.

**Comment by matthid** [comment]
As there is not anything from my side I can do (as I don't know which typos). I'll close this issue and hope to see a PR or the list of typos ;)
