### ISSUE TITLE
( !! ) x   does not work with remote folders

### ISSUE THREAD

**Issue by ushenkodmitry** [fsharp/FAKE#1750]
### Description

By using something like `!! ("\\server\folder" @@ "*.config")`, i want to enumerate all config files placed in a remote folder. The files are there, but nothing is returned.

### Repro steps

1.  Just try to enumerate files in any remote folder.

### Expected behavior

I expect that files will be returned. 

### Actual behavior

Nothing returned.

### Known workarounds

Directory.EnumerateFiles is working fine with remote folders.

### Related information 

* Windows 10, Windows Server 2016 Standard
* Fake 4.63.2 from nuget
* Net Framework 4.5

**Comment by matthid** [comment]
We use `Directory.EnumerateFiles` as well:

https://github.com/fsharp/FAKE/blob/8e68acc830309d5d2587f6c6880de6cc43747499/src/app/Fake.Core.Globbing/Globbing.fs#L62

I'm not sure what is going on.

**Comment by matthid** [comment]
Ok I stumbled over a similar issue and decided to fix this as well. This should be fixed with RC014
