### ISSUE TITLE
Paket gives me a "Platform not specified" warning, but the project in question claims everything is as it should

### ISSUE THREAD

**Issue by tlycken** [fsharp/FAKE#1753]
I'm getting a `Platform not specified for library or executable ..., please tell the authors of that project` error when building my project, specifically for a couple of dll's in the xUnit suite, but Brad Wilson maintains that this is not a problem with xUnit. Thus, I assume it's something with my setup - but what?

Steps to reproduce, log output etc are detailed in that issue: https://github.com/xunit/xunit/issues/1603

If something is wrong with my setup and/or configuration, what? If not, is this a problem with Paket or with xUnit?

**Comment by matthid** [comment]
Yes this is a Paket issue. Please move it there (and close this). I responded to the xunit issue as well.

**Comment by tlycken** [comment]
@matthid Hum, I intended to file this on Paket, not on Fake. Must have had too many tabs open... sorry for the noise!

**Comment by tlycken** [comment]
Filed new issue there: https://github.com/fsprojects/Paket/issues/2958
