### ISSUE TITLE
Migration guide change for paket update

### ISSUE THREAD

**Issue by phatcher** [fsharp/FAKE#1756]
The Migration Guide says to issue

.paket/paket.exe update FAKE

it's more likely that you will have to issue

.paket/paket.exe update FAKE --group Build

**Comment by matthid** [comment]
Yes is there any particular reason to change that (as the former includes the later)? I have no objections just trying to figure out if anything special happened here.

**Comment by phatcher** [comment]
@matthid It might have been me changing my project to having Fake in the build group rather than the default area, i.e. I was trying to update and move groups at the same time.

How about

.paket/paket.exe update

which seemed to work for me

**Comment by matthid** [comment]
Ah I see, the problem is

> With Paket: add prerelease after nuget FAKE in paket.dependencies file then .paket/paket.exe update FAKE, check that paket.lock references FAKE version 5

Should probably we written as

> With Paket: add prerelease after nuget FAKE in `paket.dependencies` file then `.paket/paket.exe update` FAKE, check that paket.lock references FAKE version 5

**Comment by phatcher** [comment]
That looks good
