### ISSUE TITLE
Deleting .Net Core every build?

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1761]
### Description
```
 Target "InstallDotNetCore" <| fun _ ->
   dotnetExePath <- DotNetCli.InstallDotNetSDK "2.0.3"
```

```
Finished Target: Clean
Starting Target: InstallDotNetCore (==> Clean)
dotnet --info
/Users/h/.local/share/dotnetcore/dotnet --info
Deleting contents of /Users/h/.local/share/dotnetcore
```

How come?

### Expected behavior

Not deleting already downloaded .net core.

### Actual behavior

Deleting it.

**Comment by voronoipotato** [comment]
I presume that's to ensure that the correct version is installed?

**Comment by matthid** [comment]
I think this is now solved in fake 5. With the recommended approach it will only download if we cannot detect an installation with the correct version
