### ISSUE TITLE
.Net Core download termination error

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1762]
### Description

When downloading .Net core and cancelling the download, FAKE doesn't properly remove/dispose of its WIP, such that next time around, the zip/tar file is corrupt and the build fails.

Instead paket should download to a temporary file, move the finished file in place and then unzip it. Once it's been unzipped, mark completion with a marker file and then remove the downloaded file.

Next time around, if there's no marker file, delete any unzipped WIP. If there's only a temporary file (not moved yet), delete it and start over.

<img width="724" alt="screen shot 2018-01-21 at 15 36 42" src="https://user-images.githubusercontent.com/193115/35195240-e69acc2c-fec0-11e7-86cc-cafeb360bb34.png">

### Repro steps

Run the Expecto build, cancelling it while downloading .net core. Then run `build.sh` again.

### Workaround

      rm /var/folders/c1/wxqsbv6n7ygdp32gwgb0y85w0000gn/T/dotnet-sdk-2.0.*

**Comment by matthid** [comment]
Adding the obsolete flag as `DotNetCli` is the obsolete API (FAKE5 uses the `Fake.DotNet.Cli` Module). For historic reasons we have multiple versions of that API :/

**Comment by matthid** [comment]
PR is welcome. I'm closing this to clean the house a bit - But I assume nobody will fix the legacy API anyway ;)
