### ISSUE TITLE
Wrong errors gets cached in .fake directory along the dll

### ISSUE THREAD

**Issue by pkese** [fsharp/FAKE#1765]
### Description

If there's a target error at first build (when DLL gets cached), then the accompanying error message gets stored into `.fake` directory and is then reproduced at each consecutive invocation of Fake.

### Repro steps

*Note: I install fake using paket and keep my build.fsx in `src` directory rather than project root, thus calling paket from `..\packages\FAKE\tools`*

    cd src
    del .fake\*.*
    ..\packages\FAKE\tools\FAKE.exe build.fsx inexistent.target

fails with error that target doesn't exist as expected.
However, when cosecutively calling a target that works

    ..\packages\FAKE\tools\FAKE.exe build.fsx existing.target

ends with an Ok report following with cached error that's not relevant to current taget

    ---------------------------------------------------------------------
    Build Time Report
    ---------------------------------------------------------------------
    Target                 Duration
    ------                 --------
    existing.target        00:00:02.5970559
    Total:                 00:00:02.6221405
    Status:                Ok
    ---------------------------------------------------------------------
    System.Exception: Target "inexistent.target" is not defined.
       at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1379.Invoke(String message)
       at Fake.Core.Target.visitDependenciesAux@322[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, HashSet`1 visited, List`1 ordered, Int32 level, Tuple`2 tupledArg)
       at Fake.Core.Target.visit@319[a](FSharpFunc`2 fGetDependencies, FSharpFunc`2 fVisit, String targetName)
       at Fake.Core.Target.visitDependencies(FSharpFunc`2 fVisit, String targetName)
       at Fake.Core.Target.run$cont@484(String targetName, Unit unitVar)
       at Fake.Core.Target.run(String targetName)
       at Fake.Core.Target.RunOrList()
       at <StartupCode$FSI_0005>.$FSI_0005_Build$fsx.main@() in d:\work\4o_backend\test\src\build.fsx:line 294
    Stopped due to error

### Known workarounds

    echo "" > .fake\build.fsx_36415925_warnings.txt

### Related information 

* Operating system: Windows 10
* Branch: fake 5.0.0.beta-10
* .NET Runtime, CoreCLR or Mono Version: .Net 2.0.3
* Performance information, links to performance testing scripts: N/A

**Comment by matthid** [comment]
Ah thanks for the report! I think something similar was reported on latest stable but we never figured out the repro steps.

**Comment by matthid** [comment]
I added the obsolete flag as I think this doesn't happen in the new netcore-runner. Also I think this is only an annoyance as exit code and everything else works as it should.

**Comment by pkese** [comment]
Ok. It seems fair enough. Lets just move on to netcore-runner if that will solve the issue.
I suppose it is then acceptable to close the ticket.
