### ISSUE TITLE
Fake glob operator (!!) should ignore casing on windows

### ISSUE THREAD

**Issue by ralphwillgoss** [fsharp/FAKE#1772]
### Description

I'm using the glob operator (!!) in my build script and its not searching the directory as I would expect.
```
let path = "" // function to generate path
trace path // would look something like "c:\git\project\**\*UnitTest*"
!! path.ToLower()
|> Seq.iter (fun file -> trace file ) // this would not output anything
```

### Expected behavior
When running the script specifying the **fsi.exe** path, the expected behavior of the glob happens:
`C:\Program Files (x86)\Microsoft SDKs\F#\4.1\fsi --load:build.fsx`

As expected the directory path is searched and the unit test dlls are found.

When using the **fsi** directly the following works, which includes using `ToLower()` on the path:
```
Microsoft (R) F# Interactive version 4.1
<snip>
#r @"packages/FAKE/tools/FakeLib.dll";;
open Fake;;
!! "**\*UnitTests.dll" |> Seq.iter (fun x -> trace x);;
C:\git\project1\bin\Debug\project1.UnitTests.dll
C:\git\project2\bin\Debug\project2.UnitTests.dll

!! "**\*UnitTests.dll".ToLower() |> Seq.iter (fun x -> trace x);;
C:\git\project1\bin\Debug\project1.UnitTests.dll
C:\git\project2\bin\Debug\project2.UnitTests.dll
```

### Actual behavior
When I run the script above by itself, the glob operator does not work and no dlls are found:

### Known workarounds

If I remove the `ToLower()` from the path, then the unit test dlls are found.

### Related information 

Fake v4.63.2
Windows 10
F# 4.1

I originally posed this on StackOverflow:
https://stackoverflow.com/questions/48527620/fake-glob-operator-not-expanding-directory-paths

**Comment by matthid** [comment]
Like stackoverflow suggests you should chrleck your usage of the backslash, maybe you actually use different patterns in your manual tests. 
Generally I would consider patterns case sensitive (because fake works cross platform) therefore I wouldn’t recommend ToLower.

To better understand the issue I feel like we need step by step examples with your results and what you would expect (for every step), because i’m not sure what the issue is.

For example:
 - create the following folder structure...
 - fake build.fsx with following content: ...
    expected:...
    actual: ...
 - ...

**Comment by ralphwillgoss** [comment]
Thanks @matthid, i will look over it again.
What is not explained, is why the script works even with the ToLower() left in, when I run the script referencing the path to **fsi.exe** directly:
`C:\Program Files (x86)\Microsoft SDKs\F#\4.1\fsi --load:build.fsx`

**Comment by matthid** [comment]
Basically what I'm asking for are exact repro steps because I want to reproduce on my machine. Ideally self contained.

**Comment by matthid** [comment]
On windows tolower should not have any effect as the filesystem ignores casing...

**Comment by ralphwillgoss** [comment]
No worries, I'll create a test script

**Comment by matthid** [comment]
Oh I didn't see the response yesterday so it seems I failed there. 

So you basically say that windows is case-sensitive for your example? I know that windows is actually storing the casing information in the File-System but all APIs should ignore the casing therefore - in theory - it shouldn't matter...

**Comment by ralphwillgoss** [comment]
Yes, but somewhere, something is storing the casing information. The fact that I remember I actually changed the casing helps. Checking the src out to a new directory resolves the issue too.

**Comment by pkanavos** [comment]
NTFS is a case-preserving but not case-sensitive file system. That means that if a folder named `Company` is created, the casing is preserved but file functions can still access the folder as `company`. If !! returns different results according due to the case it means its code uses case-sensitive comparisons or pattern matching

**Comment by matthid** [comment]
There are reasons for doing it either way. On one hand users expect it to be case insensitive on windows.
On the other hand the current code embraces cross platform compat ...

**Comment by ralphwillgoss** [comment]
Windows users would expect case insensitivity (look at the issue I had), any reason we could not use  `Fake.EnvironmentHelper.isWindows` to add the change mentioned by @pkanavos ?

**Comment by pkese** [comment]
Using `Fake.EnvironmentHelper.isWindows` is more of an approximate solution - e.g. it doesn't solve the case like accessing windows partitions from Linux-on-windows bash shell.

It's probably better than nothing though (a good default), but ideally one should be able to configure it somewhere in glob (like one can set BaseDirectory).

**Comment by ralphwillgoss** [comment]
@pkanavos - are there any methods for detecting if the file system is NTFS?
@pkese - sounds good, I'll look at a solution that takes that into account

**Comment by ralphwillgoss** [comment]
I assume I should make the changes in Fake.Core.Globbing.Glob? since Fake.Globbing is deprecated?

**Comment by matthid** [comment]
exactly, note that I did some changes in the beta 015 brach, make sure to work on top of that for now
