### ISSUE TITLE
Impossible to specify <custombuild>.fsx for `dotnet fake.dll`

### ISSUE THREAD

**Issue by pkese** [fsharp/FAKE#1774]
### Description

When running `dotnet fake.dll` it is not possible to specify which `.fsx` file Fake should use.

### Repro steps

    >dotnet .\some-path\fake.dll build2.fsx mytarget
    ERROR: unrecognized argument: 'build2.fsx'.
    USAGE: fake [--help] [--version] [--verbose] [<subcommand> [<options>]]

### Expected behavior

Fake would source and run `build2.fsx` as specified on command line.

### Actual behavior

See above

### Known workarounds

Have single build.fsx file

### Related information 

* Operating system: Windows 10
* Branch: 5.0.beta-12
* .NET Runtime, CoreCLR or Mono Version: netcore 2.0.x

**Comment by matthid** [comment]
Note that the command line has been changed in the new runner: https://fake.build/fake-commandline.html

**Comment by pkese** [comment]
Oh. I see. Thanks.
Apparently I've missed this document altogether.

I think the previous approach was more elegant (and `run` seems not to serve much purpose), but I really like the fact that one can pass along normal '--' args.

**Comment by matthid** [comment]
Not sure I get the feedback. imho the old syntax has lots of ambiguities while the new one is straight forward unix default. So any suggestions are welcome but I don't know what you like to see improved. related: https://github.com/fsharp/FAKE/issues/1569
