### ISSUE TITLE
Fake no longer available on Chocolatey

### ISSUE THREAD

**Issue by JohnStov** [fsharp/FAKE#1784]
### Description

Fake seems to have disappeared from chocolatey

### Repro steps

'clist fake -pre' finds no packages

### Expected behavior

'choco install fake -pre' should install the latest fake pre-release

### Actual behavior

No package found

**Comment by JohnStov** [comment]
Weird - it's back now. Must have been a choco issue.

**Comment by matthid** [comment]
Yes I can't remember doing anything special. Today I tried to release beta-014 again (because I failed to increase the version number) but it that has the above effect....
