### ISSUE TITLE
FAKE 5 improper warning message

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FAKE#1787]
### Description

Improper warning message of deprecated Fake.TraceHelper.Log in FAKE 5.0.0-beta015

### Repro steps

using Fake.TraceHelper.Log in FAKE 5.0 fsx

### Expected behavior

should generate message:

warning FS0044: This construct is deprecated. use Fake.Core.Trace instead (open Fake.Core and use 'Trace.')

### Actual behavior

generates warning message:

warning FS0044: This construct is deprecated. use Fake.Core.Tracing instead (open Fake.Core and use 'Tracing.')

### Known workarounds

n/a

### Related information 

5.0.0-beta015

**Comment by matthid** [comment]
Nice catch, however the correct warning message would be

```
warning FS0044: This construct is deprecated. use Fake.Core.Tracing instead (open Fake.Core and use 'Trace.')
```

Because right now the package is called https://www.nuget.org/packages/Fake.Core.Tracing

Maybe I should rename that to `Fake.Core.Trace` as well to make life easier?

**Comment by jackfoxy** [comment]
@matthid  I don't understand.
Fake.Core.Trace.Log autocompletes and works exactly as its predecessor in 4.x
Fake.Core.Tracing.Trace does not autocomplete

**Comment by jackfoxy** [comment]
BTW, the warning message on TraceHelper.traceImportant is not helpful. There does not seem to be a 1-for-1 replacement.

**Comment by matthid** [comment]
> Fake.Core.Trace.Log autocompletes and works exactly as its predecessor in 4.x
> Fake.Core.Tracing.Trace does not autocomplete

Yes, the F# module is called `Fake.Core.Trace` and therefore the warning is confusing. But if you use the new FAKE 5 Modules you need to write 
```fsharp
#r "paket:
nuget Fake.Core.Tracing
//"

open Fake.Core
Trace.Log "text"
```

Which might be a bit confusing. The first part of the message "This construct is deprecated. use Fake.Core.Tracing instead" is kind of correct. The second part "(open Fake.Core and use 'Tracing.')" is wrong.

Maybe we could make the messages a bit more clearer in that regard. In any case renaming the nuget package might be a good idea given the confusion.

**Comment by matthid** [comment]
> BTW, the warning message on TraceHelper.traceImportant is not helpful. There does not seem to be a 1-for-1 replacement.

Ok will take a look, thanks

**Comment by jackfoxy** [comment]
Wow, there must be over 12 Fake nuget packages. It seems some functionality comes with nuget FAKE 5.0 and some does not. How do I tell when I need and additional package and when I do no?

**Comment by matthid** [comment]
> How do I tell when I need an additional package and when I do not?

Basically all functionality will go into NuGet packages / Fake Modules. However we might still reduce the number of packages before we go with the final fake 5 release.

**Comment by matthid** [comment]
I think I improved the obsolete messages, the package has been renamed already. Let me know if there are other things to improve :)
