### ISSUE TITLE
[Fake5]: I need GetErrors() (or something equivalent)

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1791]
![grafik](https://user-images.githubusercontent.com/4236651/36382372-f25bced8-1588-11e8-8846-b6686f0e62b9.png)

At the end of the build, I create a summary file. For this I need to be able to access all errors.

**Comment by matthid** [comment]
I don't like how the `GetErrors` API (or most of the Target Module in fact) use a lot of side-effects to work.
Maybe we can give the current state (and the errors you need) via the argument of the Target function somehow?

**Comment by 0x53A** [comment]
Since this kind of information gathering only really makes sense at the end of a build, my second suggestion would be to re-type the final targets as ``ExecutionHistory->unit``. My first suggestion is to keep it as-is and not over-engineer it. ;-)

**Comment by matthid** [comment]
It's less about over-engineering and more about refactoring. There are already some issues in the Targets-API and some common pitfalls.

**Comment by matthid** [comment]
In beta022 we will have

```fsharp
type TargetDescription = string

type TargetResult =
    { Error : exn option; Time : TimeSpan; Target : Target; WasSkipped : bool }

and TargetContext =
    { PreviousTargets : TargetResult list }
    static member Empty = { PreviousTargets = [] }
    member x.HasError =
        x.PreviousTargets
        |> List.exists (fun t -> t.Error.IsSome)
    member x.TryFindPrevious name =
        x.PreviousTargets |> List.tryFind (fun t -> t.Target.Name = name)        

and TargetParameter =
    { TargetInfo : Target
      Context : TargetContext }

/// [omit]
and Target =
    { Name: string;
      Dependencies: string list;
      SoftDependencies: string list;
      Description: TargetDescription option;
      Function : TargetParameter -> unit}
```

So you can use the `HasError` member for your use-case.

**Comment by 0x53A** [comment]
Is there also something to get the errors themselves?

**Comment by matthid** [comment]
Yes thanks for bringing that up, that was a trigger to fix some long outstanding points I wanted to improve (in particular that errors are no longer shown twice and that we show all targets on failure and the timing information of failed tasks). And I even found some other issues ;)

![image](https://user-images.githubusercontent.com/1866463/36945915-17791c6c-1fb5-11e8-8599-c0f095460524.png)

**Comment by matthid** [comment]
![image](https://user-images.githubusercontent.com/1866463/36945984-203f7f70-1fb6-11e8-92b6-490fdf7d3bb3.png)
