### ISSUE TITLE
Fake.Dotnet.Cli.DotNetCompile is not user friendly

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1792]
### Description

In the latest version of Fake.Dontet.Cli (5.0.0-beta-18), if I want to use the API I need to do:

```fsharp
DotNetCompile (fun c -> c()) proj
```

Here is the signature of DotNetCompile:

```fsharp
val DotNetCompile: 
   setParams: (unit -> DotNetBuildOptions) -> DotNetBuildOptions ->
   project  : string 
           -> unit
```

### Expected behavior

I think the signature should be:

```fsharp
val DotNetCompile: 
   setParams: DotNetBuildOptions -> DotNetBuildOptions ->
   project  : string 
           -> unit
```

I think this is the how the API was previously.

**Comment by matthid** [comment]
Yes good catch thanks

**Comment by matthid** [comment]
This has been released.
