### ISSUE TITLE
Ensure user experience for Fake.IO.FileSystem API

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1795]
### Description

The Fake.IO.FileSystem API has been designed with a certain user experience in mind.

User experience expected:

```fs
open Fake.IO
open Fake.Core

Target.Create "Docs.Setup" (fun _ ->
    // Make sure directories exist
    Directory.ensure "./docs/scss/extra/highlight.js/"

    // Copy files from node_modules allow us to manage them via yarn
    Shell.CopyDir "./docs/public/fonts" "./node_modules/font-awesome/fonts" (fun _ -> true)
    Shell.CopyFile "./docs/scss/extra/highlight.js/atom-one-light.css" "./node_modules/highlight.js/styles/atom-one-light.css"
)
```

If the user do:

```fs
open Fake.IO.Directory
open Fake.IO.Shell
open Fake.Core

Target.Create "Docs.Setup" (fun _ ->
    // Make sure directories exist
    ensure "./docs/scss/extra/highlight.js/"

    // Copy files from node_modules allow us to manage them via yarn
    CopyDir "./docs/public/fonts" "./node_modules/font-awesome/fonts" (fun _ -> true)
    CopyFile "./docs/scss/extra/highlight.js/atom-one-light.css" "./node_modules/highlight.js/styles/atom-one-light.css"
)
```

Then the user experience is really bad IMO.

I propose to use `[<RequiredQualifiedAccess>]` attributes to make sure the user will have the expected experience. My motivation being the FAKE5 API, is already hard enough in current form. You need to know which nuget to include and which modules to open.

By controlling the API usage, we can probably improve the user experience.

**Comment by matthid** [comment]
Yes adding `RequireQualifiedAccess` is in fact a very good idea, that is how the API is supposed to be used anyway. Feel free to send PRs, otherwise I'll probably add them one by one as soon as I stumble over stuff.
