### ISSUE TITLE
FAKE 5 output color feels strange

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1796]
### Description

Running a command from the CLI or via Fake give different ouput color.

CLI command:
<img width="873" alt="capture d ecran 2018-02-22 a 16 48 16" src="https://user-images.githubusercontent.com/4760796/36548362-667d0ea8-17f0-11e8-9e30-b746f8826fca.png">

Fake command:
<img width="867" alt="capture d ecran 2018-02-22 a 16 48 27" src="https://user-images.githubusercontent.com/4760796/36548355-632b83ba-17f0-11e8-8f8e-97bcafead771.png">

I think, we should have the same ouput color. Because, it's feel strange to have a successful command displayed in yellow. 

I think FAKE 4, is keeping the ouput color. Is this change wanted (a feature) ?

**Comment by matthid** [comment]
> Is this change wanted

No, colors are something we need to take a deep look at. Thanks for this reminder.

**Comment by matthid** [comment]
This should be fixed since beta022

**Comment by MangelMaxime** [comment]
I tested it with beta023 and I see no change in color used.

I am using zsh under OS X.
If you want to test my `build.fsx`: https://github.com/MangelMaxime/Thot

**Comment by matthid** [comment]
Yes you need to update your packages:

https://github.com/MangelMaxime/Thot/blob/6c165d3232d74c49153a804e8f444165c2fa19a1/paket.lock#L837-L843

The fake runner is split from the actual packages like `Fake.Core.Target`

**Comment by MangelMaxime** [comment]
Ah yes, I only updated `dotnet-fake` version.

I totally forget about the `paket.dependencies`.

I run `mono .paket/paket.exe update --group netcorebuild`
And now, I get: 

```shell
  Restore completed in 6,93 ms for /Users/mangelmaxime/Workspace/Github/MangelMaxime/Thot/dotnet-fake.csproj.
  Restore completed in 44,62 ms for /Users/mangelmaxime/Workspace/Github/MangelMaxime/Thot/dotnet-fake.csproj.
Could not load types of compiled script:
 - Could not load type 'ProcStartInfo' from assembly 'Fake.Core.Process, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'ProcStartInfo' from assembly 'Fake.Core.Process, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'ProcStartInfo' from assembly 'Fake.Core.Process, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'ProcStartInfo' from assembly 'Fake.Core.Process, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'ProcStartInfo' from assembly 'Fake.Core.Process, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
 - Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
-> TypeLoadException: Could not load type 'TargetParameter' from assembly 'Fake.Core.Target, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

I post it here because perhaps you know the reason. I will try to debug on my side too.

**Comment by matthid** [comment]
@MangelMaxime Did paket install a mix of different versions (like some beta022 and some beta023)?
Note that `Fake.Core.BuildServer` and `Fake.Core.Globbing` do no longer exists and you might need to remove them from the `paket.dependencies` file.

**Comment by matthid** [comment]
@MangelMaxime And beta is the best time to look at these kind of update-pitfalls and see how we want to takle that after the final release, so please report these kind of issues (as I have for example not seen that yet)

**Comment by MangelMaxime** [comment]
Awesome this is working now.

<img width="1103" alt="capture d ecran 2018-03-05 a 16 44 19" src="https://user-images.githubusercontent.com/4760796/36984153-7ce03420-2094-11e8-8eee-4ecfdfd4ea3b.png">

----

I needed to clean the `.fake` folder and then fix the build.fsx to use the latest API https://github.com/MangelMaxime/Thot/commit/5d9f86a7320194208f29debce5515eda388f9d09#diff-6074983490330a0aac1bd23c958232d7

**Comment by matthid** [comment]
Question is can we reproduce this. In an ideal world you never need to delete `.fake` folder (as the cache should be invalidated as needed)...
