### ISSUE TITLE
Tab-completion of FAKE build targets for Bash

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#1798]
Opening an issue rather than a PR because this probably doesn't belong in the FAKE source code itself, but I wanted to make people aware of it. Perhaps this could be added to the documentation somewhere, or to a wiki.

I've written a short-and-simple [Bash tab-completion file for FAKE build scripts](https://gist.github.com/rmunn/49871011ac2eab6c3f10e5fa5abc52d9). It makes a few assumptions that are broadly, but not universally, true of most F# projects I've seen:

1. Your Bash script to run FAKE is called `build.sh`
1. Your FAKE build script is called `build.fsx`
1. Your build target names don't have any spaces in them

BTW, if your build target names *do* have spaces in them, you'll have to tweak the `grep -o 'Target ".*?"' "${BUILD_FSX}" | cut -d'"' -f2` line in the script.

Hopefully this Bash completion script will be helpful to others who develop F# on Linux or OS X.

**Comment by matthid** [comment]
Yes this is in-fact a good idea. We probably need a way to get the list of targets from a file to provide intellisense for targets. Yes adding documentation would be very welcome :).

Note that your assumptions have to be re-checked for FAKE 5 and .net core projects.

**Comment by baronfel** [comment]
Suggestion: because we have to parse/run the file to correctly derive all the targets, would it be possible to instead create a cached file containing the target names that is blown away whenever the compiled script is run?

so for a given script version, write a file `targets` to the `.fake` directory, and any completion scripts can just read that. Then, next time FAKE is run and recompiles the script that file can be overwritten as well.

That should help ensure that the effort to port any scripts to new shells is very lightweight. Alternatively, a new command for FAKE could be written that would just echo/generate-then-echo this file as appropriate, to prevent shells from having to know about FAKE internals. Something like `fake completions` with additional calls to `fake completions --prefix=PREFIX` to filter that list and `fake completions purge` to clear them out, etc

**Comment by matthid** [comment]
@baronfel You might be able to use `fake -s build --list` or `fake -s run build.fsx --list` It works as long as people don't have side-effect-code while generating the targets.

It should be quite fast (~500ms on a "warm"/cached start)

**Comment by baronfel** [comment]
That's much faster that I was thinking it would be. Does that work only with the new runner, or with the fake 5 legacy runner as well? (I'm thinking only the new runner because it doesn't have the new syntax from what I can tell)

**Comment by matthid** [comment]
@baronfel Yes it will be new runner only (actually the old runner should be fast as well because it also does caching but I don't think we should support the old runner for this at this time)

Old runner supports `Fake.exe --list-target` (or something like it) as well, but it probably doesn't work as well as we'd like.

**Comment by baronfel** [comment]
The new runner works decently-well, but there is still a bit of noise that the `-s` flag didn't remove:
```
bash-3.2$ fake -s build -f build.fsx --list
building applications in the `Release` configuration
The following targets are available:
   AssemblyInfo
   KillStarted
   Clean
   YarnInstall
   DotnetRestore
   DotnetBuild
   DotnetTest
   WatchUnitTests
   BrunchProduction
   DotnetPublish
   BuildWebsiteDebug
   BuildCollectorDebug
   BuildBrunch
   WatchWebsite
   RunWebsite
   CheckGitlab
   ReleaseGitlab
   DebianPackage
   CopyDeployScripts
   CopyDeployScriptsDebug
   CreateUpdatePackage
   CreateUpdatePackageDebug
   UploadToUpdateServer
   Debug
   Release
   JavascriptBuild
   Build
   RunTests
   Version
   Xml
   BuildProduction
/Users/chethusk/work/server/build.fsx (301,18)-(301,57): Warning FS0052: The value has been copied to ensure the original is not mutated by this operation or because the copy is implicit when returning a struct from a member and another member is then accessed
/Users/chethusk/work/server/build.fsx (947,50)-(947,89): Warning FS0052: The value has been copied to ensure the original is not mutated by this operation or because the copy is implicit when returning a struct from a member and another member is then accessed
```

In addition, a few enhancements that would be nice here:
* target names could be sorted in order to save the caller piping into `| sort`
* `--list` isn't in the fake help:
```
Error while parsing command line, usage is:

Usage:
  fake.exe [fake_opts] run [run_opts] [<script.fsx>] [--] [<scriptargs>...]
  fake.exe [fake_opts] build [build_opts] [--] [<scriptargs>...]
  fake.exe --version
  fake.exe --help | -h

Fake Options [fake_opts]:
  -v, --verbose [*]     Verbose (can be used multiple times)
                        Is ignored if -s is used.
                        * -v: Log verbose but only for FAKE
                        * -vv: Log verbose for Paket as well
  -s, --silent          Be silent, use this option if you need to pipe your output into another tool or need some additional processing.                  

Fake Run Options [run_opts]:
  -d, --debug           Debug the script.
  -n, --nocache         Disable fake cache for this run.
  -p, --partial-restore
                        Only restore the required group instead of a full restore, 
                        can be set globally by setting the environment variable FAKE_PARTIAL_RESTORE to true.
  --fsiargs <fsiargs> [*]  Arguments passed to the f# interactive.

Fake Build Options [build_opts]:
  -d, --debug           Debug the script.
  -n, --nocache         Disable fake cache for this run.
  -p, --partial-restore
                        Only restore the required group instead of a full restore, 
                        can be set globally by setting the environment variable FAKE_PARTIAL_RESTORE to true.
  --fsiargs <fsiargs> [*]  Arguments passed to the f# interactive.
  -f, --script <script.fsx>
                        The script to execute (defaults to `build.fsx`).
  ```

**Comment by matthid** [comment]
@baronfel 

- Ok I think the warnings are introduced recently because I refactored some stuff there :/

- The sort suggestion makes sense

- `building applications in the "Release" configuration`
  Not sure where this is emitted but it can probably just be removed generally (at least for `--list`)

- > `--list` isn't in the fake help:

This is currently "by-design" as the this only the cli of the runner/runtime. The rest is part of the `Fake.Core.Target` package:

```
$ fake --help

Usage:
  fake.exe [fake_opts] run [run_opts] [<script.fsx>] [--] [<scriptargs>...]
  fake.exe [fake_opts] build [build_opts] [--] [<scriptargs>...]
  fake.exe --version
  fake.exe --help | -h

Fake Options [fake_opts]:
  -v, --verbose [*]     Verbose (can be used multiple times)
                        Is ignored if -s is used.
                        * -v: Log verbose but only for FAKE
                        * -vv: Log verbose for Paket as well
  -s, --silent          Be silent, use this option if you need to pipe your output into another tool or need some additional processing.


Fake Run Options [run_opts]:
  -d, --debug           Debug the script.
  -n, --nocache         Disable fake cache for this run.
  -p, --partial-restore
                        Only restore the required group instead of a full restore,
                        can be set globally by setting the environment variable FAKE_PARTIAL_RESTORE to true.
  --fsiargs <fsiargs> [*]  Arguments passed to the f# interactive.

Fake Build Options [build_opts]:
  -d, --debug           Debug the script.
  -n, --nocache         Disable fake cache for this run.
  -p, --partial-restore
                        Only restore the required group instead of a full restore,
                        can be set globally by setting the environment variable FAKE_PARTIAL_RESTORE to true.
  --fsiargs <fsiargs> [*]  Arguments passed to the f# interactive.
  -f, --script <script.fsx>
                        The script to execute (defaults to `build.fsx`).
  Hint: Run 'fake run <script.fsx> --help' to get help from your script.
```

And if we follow the hint:

```
$ fake run build.fsx --help
Build Number: 5.0.0-rc016

Usage:
  fake-run --list
  fake-run --version
  fake-run --help | -h
  fake-run [target_opts] [target <target>] [--] [<targetargs>...]

Target Module Options [target_opts]:
    -t, --target <target>
                          Run the given target (ignored if positional argument 'target' is given)
    -e, --environment-variable <keyval> [*]
                          Set an environment variable. Use 'key=val'. Consider using regular arguments, see https://fake.build/core-targets.html
    -s, --single-target    Run only the specified target.
    -p, --parallel <num>  Run parallel with the given number of tasks.

Hint: Run 'fake run <build.fsx> target <target> --help' to get help from your target.
```

**Comment by baronfel** [comment]
Oh that makes a lot of sense! I'm interesting in looking at how you register those options on a per-module basis now.

I'm currently trying to build FAKE locally so I can try to do part of your list above.

**Comment by baronfel** [comment]
Oh, the 'building applications....' line was some tracing from my own script, because I am a bad, stateful person.

**Comment by matthid** [comment]
> Oh, the 'building applications....' line was some tracing from my own script, because I am a bad, stateful person.

Haha I was searching for that in your PR and didn't find it ;)

**Comment by baronfel** [comment]
for posterity, here's my completion script for the new FAKE 5 runner:
```
_fake() {
  local cur
  cur="${COMP_WORDS[COMP_CWORD]}"
  RESULTS=$(fake -s build --list 2>/dev/null | tail -n +2 | awk '{$1=$1};1')
  COMPREPLY=($(compgen -W "$RESULTS" -- "$cur"))
}

complete -F _fake fake

compdef fake
```

**Comment by matthid** [comment]
@baronfel Should we somehow install that with our debian package?

**Comment by matthid** [comment]
I'm closing this, but to answer the initial post: I'd love to see a pr to somehow add this here (like I said for example the debian package or to the docs on how to get this running on my shell)
