### ISSUE TITLE
ChangeWatcher is not ported to FAKE 5

### ISSUE THREAD

**Issue by wallymathieu** [fsharp/FAKE#1799]
### Description

The documentation for [documentation](https://fake.build/apidocs/fake-changewatcher.html) does not work in FAKE 5 due to change watcher having a dependency on legacy type.

### Repro steps

Please provide the steps required to reproduce the problem

1. Use latest beta of FAKE

2. Copy paste code [from documentation](https://fake.build/apidocs/fake-changewatcher.html) : 
and update to match FAKE 5
```
Target.Create "Watch" (fun _ ->
    use watcher = !! "c:/projects/watchDir/*.txt" |> WatchChanges (fun changes ->
        // do something
    )

    System.Console.ReadLine() |> ignore

    watcher.Dispose() // if you need to cleanup the watches.
)
```

### Expected behavior

The above code to compile

### Actual behavior

Due to `!!` operator returning `IGlobbingPattern` the code does not compile

### Known workarounds

A simple workaround would be to use an adapter of FileIncludes to IGlobbingPattern.

### Related information 

* Operating system : All
* Branch : FAKE 5

**Comment by wallymathieu** [comment]
See #1788 for further information

**Comment by matthid** [comment]
Yes, mixing old and new style has problems on other places as well. One other workaround is to use the old globbing operator

**Comment by wallymathieu** [comment]
Indeed. I will see how far I get on making complete PR for this.

**Comment by matthid** [comment]
This is now released as part of the `Fake.IO.FileSystem` package.

**Comment by matthid** [comment]
Thanks a lot!

**Comment by wallymathieu** [comment]
No problem!
