### ISSUE TITLE
Warning when using DateTime.Now

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1803]
### Description

With the following code:

```fs
let test = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")
```

I am getting this warning at the end of the build

```
Warning FS0052: The value has been copied to ensure the original is not mutated by this operation or because the copy is implicit when returning a struct from a member and another member is then accessed
```

I can't find a way to use `DateTime.Now`without having this warning ? 
Is it possible to use `DateTime.Now` with FAKE without the warning ?

**Comment by MangelMaxime** [comment]
I forgot to specify I am having this warning with FAKE5.

**Comment by pmbanka** [comment]
The workaround is to use

`let test = let now = DateTime.Now in now.ToString()`

ugly, but maybe unblocks you. See also https://stackoverflow.com/a/33325042/1108916

**Comment by MangelMaxime** [comment]
Thank you, indeed not pretty code :)

**Comment by JarnoNijboer** [comment]
It is also possible to ignore the warning for the entire file by putting the following at the top of you `.fsx`:

```
#nowarn "52"
```
