### ISSUE TITLE
Cannot execute nuget install from FAKE script 

### ISSUE THREAD

**Issue by Reptarsrage** [fsharp/FAKE#1806]
### Description

I would like to utilize nuget.exe to install some packages that are needed to run code coverage, and other build tasks. These packages are not specified in the project's package.config and shouldn't be.

I would like to be able to run the command:  
`nuget install <package-name> -ExcludeVersion -OutputDirectory packages`  
 
This command would need to be run in a FAKE Target, as we would only install these packages if we were running the "code coverage" Target. Otherwise I could download these packages before executing my FAKE script.

So that I can use tools like  
Fake.OpenCoverHelper  
Fake.ReportGeneratorHelper

### Expected behavior

This should probably be documented somewhere.

### Actual behavior

I couldn't find any documentation on this.

**Comment by matthid** [comment]
Are you running FAKE 5? Usually we would just use a `Paket` group for this and add the nuget packages there. This way stuff will be downloaded automatically and there is no need to call nuget (probably the easiest way). Do you have large nuget packages or why do you want to download lazily (which is a bit unusual).

Maybe we can figure out what you are looking for and then improve the documentation?

**Comment by alexeyzimarev** [comment]
@matthid My issue is that I have no way to get the path where those packages are downloaded.

**Comment by matthid** [comment]
Usually that path can be configured via NuGet.Config when in fact using `nuget.exe`. Honestly I'm not sure what you are after. Maybe you can create a sample script and tell what you expect and what you are seeing instead?

**Comment by alexeyzimarev** [comment]
Well, I am on Linux and I have no nuget.exe. Cake has this ability to restore tool packages to a tools folder in the repo root so I can run things like SonarQube, dotCover and stuff like this. In our company this is a major critique point of people who used Cake, against FAKE. I thought the new paket reference wold help but it doesn't seem like it.

**Comment by matthid** [comment]
> I thought the new paket reference wold help but it doesn't seem like it.

Yes they do, but what you need to do depends a bit on what kind of references you are using. For example the following two should work:

### First approach

`test.fsx`
```
#r "paket:
source https://api.nuget.org/v3/index.json
storage: none
nuget Fake.Core.Target

group MyOtherDeps
source https://api.nuget.org/v3/index.json
nuget JetBrains.dotCover.CommandLineTools

//"
#load ".fake/test.fsx/intellisense.fsx"

open Fake.Core

Target.Create "Target" (fun _ ->
    ())

Target.RunOrDefault "Target"
```

Here fake will automatically restore your dependencies to `.fake/test.fsx/packages/myotherdeps`

### Second approach

An alternative (and probably my suggestion) is to reference a `paket.dependencies`:

`paket.dependencies`
```
// [ FAKE GROUP ]
group Build
source https://api.nuget.org/v3/index.json
storage: none
nuget Fake.Core.Target


group MyOtherDeps
source https://api.nuget.org/v3/index.json
nuget JetBrains.dotCover.CommandLineTools
```

`test.fsx`
```
#load ".fake/test.fsx/intellisense.fsx"

open Fake.Core

Target.Create "Target" (fun _ ->
    ())

Target.RunOrDefault "Target"
```

This time fake will restore your dependencies into `packages/myotherdeps` which is a bit more visible

**Comment by matthid** [comment]
@Reptarsrage Does this answer your original question as well?

**Comment by Reptarsrage** [comment]
I'm curious if there's a way to configure FAKE to only restore a package if a certain target is run. Can paket groups be tied to a specific target, or do they always all run before the FAKE script runs?

**Comment by Reptarsrage** [comment]
Oh cool, I see that Paket takes a group as a param [here](https://fake.build/apidocs/fake-dotnet-paket-paketrestoreparams.html). This is really neat I'm glad you showed me this. Thank you

**Comment by matthid** [comment]
@Reptarsrage No this is not supported and yes fake will always restore all "relevant" groups. And I don't think there is a reasonable way to support this for Fake 5 (maybe something for the future)
