### ISSUE TITLE
Convert DotNet API to "module based"

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1808]
### Description

Would it make sense to convert DotNet API to "module based" DSL ?

Most of the API in FAKE5 are "module based" DSL.

Example:

```fs
Process.Exec // Before, beta23 it was ExecProcess
Shell.CleanDirs
String.toLines
...
```

I find it strange to use: 

- `DotNetBuild` and not `DotNet.Build` 
- `DotNetRestore` and not `DotNet.Resotre`
- etc.

The only non direct conversion would be for the generic [`DotNet`](https://github.com/fsharp/FAKE/blob/master/src/app/Fake.DotNet.Cli/DotNet.fs#L432) function. We could write `DotNet.Custom` or `DotNet.Raw`.

If you agree to this proposition, I can send a PR to the repo.

**Comment by matthid** [comment]
I agree and would like that to happen. However I *think* you cannot have a module named like the parent namespace. Therefore it looks a bit ugly at the moment :/

**Comment by MangelMaxime** [comment]
I made a quick test in one of my project about having a module named like the parent namespace and my tests was green.

I will try to apply the changes to FAKE 5 and see if this is working or no.

**Comment by matthid** [comment]
Ok then maybe this was a huge brainfail on my part :)
