### ISSUE TITLE
DotNetCli doesn't look for dotnet on path (Windows)

### ISSUE THREAD

**Issue by severisv** [fsharp/FAKE#1810]
### Description

Fake.DotNet.Cli seems to look for `dotnet` in the default install directory, but if `dotnet` is installed somewhere else it should be able to retrieve it from path.

### Repro steps
Run any Fake.DotNet.Cli-command without specifying `dotnet` location

### Expected behavior

The command runs fine.

### Actual behavior

```System.Exception: Start of process C:\Users\buildguest\AppData\Local\Microsoft\dotnet\dotnet.exe failed. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified```

### Known workarounds

Find `dotnet` on path manually and pass it into DotNetCli as an option.

### Related information 

I'm not using DotNet.Cli to install `dotnet`, I prefer to have it installed already.

I'd be happy to make an attempt at fixing this, if my reasoning is correct that DotNet.Cli should in fact use the path variable.

**Comment by matthid** [comment]
Yes we appreciate a PR, in fact we have a bug for this somewhere already...
