### ISSUE TITLE
Add Verbosity setting for NuGet restore

### ISSUE THREAD

**Issue by walliski** [fsharp/FAKE#1824]
### Description

Add the possibility of setting the `Verbosity` flag for NuGet restore command.

```
nuget help restore
...
 -Verbosity            Display this amount of details in the output: normal, quiet, detailed.
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Restore NuGet packages using `RestoreMSSolutionPackages` command.

### Expected behavior

I can choose the verbosity level with a `Verbosity` parameter in the FAKE command.

### Actual behavior

NuGet always returns a lot of spam into console.

### Known workarounds

Anyone?

**Comment by vanceism7** [comment]
Hey @matthid, I can try my hand at this one if no one's taken it yet

**Comment by matthid** [comment]
Will be fixed with RC011
