### ISSUE TITLE
[Help Wanted] FAKE 5 packages for various package managers.

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1828]
### Description

To have convenient installation options for most distributions we should provide packages for debian, ubuntu and probably some others.

For example via https://github.com/jordansissel/fpm

### Known workarounds

Download the packages from github.

**Comment by matthid** [comment]
@baronfel Yes I somehow started with it, but I couldn't really finish it :(

https://github.com/fsharp/FAKE/blob/6b6a78f06c1ac9a433a1ba0e73f66028ef625ace/build.fsx#L821-L838

**Comment by baronfel** [comment]
Hah! I see you've been talking with @theangrybyrd already.

**Comment by baronfel** [comment]
For fake 5, are we only netcorapp2.0? so any package that we make would need to be able to express that as a dependency?

**Comment by baronfel** [comment]
Also, there's a larger question of storage/repository serving. Suppose we made Debian/Ubuntu/RedHat packages. We'd need to store them in various feeds that we would serve to users.  Who would host that?

**Comment by matthid** [comment]
the package doesn’t have dotnetcore as dependency (but we could ship the portable and wrapper scripts - it would make the package smaller but a but more work to package properly).
The backage would have the same dependencies as the official netcore package.

Assume for this particular issue that either hosting is not a problem / that we try to integrate in the official feeds (preferred) / self host something.

**Comment by TheAngryByrd** [comment]
Also might want to checkout https://github.com/qmfrederik/dotnet-packaging/blob/master/README.md

**Comment by matthid** [comment]
@TheAngryByrd Oh wow

**Comment by matthid** [comment]
Because you can use fake for other automation tasks or without dotnet-core?
For example as lightweight fsi.

**Comment by TheAngryByrd** [comment]
Ok thats good to know. 

So the checklist is?

- [ ] Create a place to host packages.  https://packagecloud.io has some OSS plans.  There's probably other options.
- [ ] publish this as a self contained app as `linux-x64` 
- [ ] wrap up the dependencies into respective package (deb/rpm) with dependencies 
- [ ] push these to the package host(s)

**Comment by matthid** [comment]
While help here is still appreciated, unix/linux is not my primary use-case and people just seem to be happy enough with dotnet global tools. Therefore I'm closing this (like I said people helping with re-packaging are still welcome & needed)

**Comment by TheAngryByrd** [comment]
Yeah I'm fine with just `curl`ing the deb package from releases for machines that I want to put FAKE on without dotnet.
