### ISSUE TITLE
The nuget 4.64.11 is corrupted

### ISSUE THREAD

**Issue by cboudereau** [fsharp/FAKE#1836]
### Description

The nupkg is corrupted

### Repro steps

1. download from https://api.nuget.org/v3-flatcontainer/fake/4.64.11/fake.4.64.11.nupkg 

2. Try to extract 

### Expected behavior

The zip is extracted

### Actual behavior

The zip is corrupted : unexpected end of data.

### Known workarounds

use an older version of fake or replace the source by the v2 : https://www.nuget.org/api/v2/

**Comment by matthid** [comment]
Works for me. Can you try cleaning your caches or report to NuGet? /cc @forki

**Comment by cboudereau** [comment]
I manually download the package and try to extract it with 7z. So the cache
is not the problem.

**Comment by cboudereau** [comment]
The problem occur when I use the nuget.org v3 source : https://api.nuget.org/v3/index.json

**Comment by matthid** [comment]
I can download and open with 7zip with the link from your post ...

**Comment by matthid** [comment]
If this still happens for you I'd recommend to report this as an issue to nuget gallery and link back.
