### ISSUE TITLE
What is 5.0 replacement for legacy Fake.FSIHelper.fsiPath?

### ISSUE THREAD

**Issue by jackfoxy** [fsharp/FAKE#1841]
### Description

What is 5.0 replacement for legacy Fake.FSIHelper.fsiPath?

### Actual behavior

No migration help message available.

### Related information 

5.0.0-beta025 +

**Comment by matthid** [comment]
I don't think we have one, as we don't have a FSI module on FAKE 5 yet.

**Comment by jackfoxy** [comment]
Would that be related to the item 

Use F# Type Providers and F# Interactive in .NET Core 2.1. (specifically FSI)

on the MSFT VS roadmap https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2018-roadmap ?

I imagine this is also the major impediment to moving forward with FSharp.Formatting 3.0?

**Comment by matthid** [comment]
Maybe a bit, but yeah we probably should upgrade netcore to 2.1

**Comment by vanceism7** [comment]
Hey @matthid, is this issue do-able? If so, I can port over the fsihelper module. What would the module be called? Fake.FSI.Helper? Or just Fake.FSIHelper?

**Comment by matthid** [comment]
@vanceism7 yes I think it can be added. I guess we would name it Fake.DotNet.Fsi or Fake.Tools.Fsi

**Comment by matthid** [comment]
PR is welcome. I'm closing this to clean the house a bug ;)

**Comment by vanceism7** [comment]
Just a bump for whoever is wondering, I should have a PR coming in for this pretty soon

**Comment by halcwb** [comment]
This has been a year, will there be a FAKE 5 FSIhelper module, or is this still open?

**Comment by vanceism7** [comment]
@halcwb: looks like a PR for this was merged about a year ago. 

https://github.com/fsharp/FAKE/pull/1970

It wasn't merged into a main branch but I assume all the changes have been integrated into the main release by now

**Comment by matthid** [comment]
Yes it is [here since 5.1.0](https://fake.build/apidocs/v5/fake-dotnet-fsi.html), should have liked those issues up :)
