### ISSUE TITLE
Support fake as a global .NET Core Global Tool

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/FAKE#1864]
### Description

(This section is intentionally left blank)

### Repro steps

1. `dotnet tool install dotnet-fake -g --version 5.0.0-rc004`

### Expected behavior

Please provide a description of the behavior you expect.

### Actual behavior

```
error NU1212: Invalid project-package combination for dotnet-fake 5.0.0-rc004. DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'dotnet-fake' failed to install. You may need to specify the version using

   dotnet tool install -g dotnet-fake --version <version>
```

### Related information 

* Operating system: Windows 10 Professional
* ~~.NET Runtime,~~ CoreCLR ~~or Mono~~ Version: `2.1.300-preview2-008530`

**Comment by matthid** [comment]
Maybe we can wait until this feature is actually released? Though a PR would be welcome.

Question is if dotnet-fake is the correct place for this of if we need a new package...

**Comment by matthid** [comment]
I'm pretty sure we will have this eventually. PR is appreciated in the meantime. Anyway I'm closing this for now.

**Comment by OlegZee** [comment]
Any update on this? :)

**Comment by teo-tsirpanis** [comment]
It broke? How so? I saw the CI log and did not see any failures with `fake-cli`.

**Comment by matthid** [comment]
I did not receive a full bug report sadly :/
But I'm happy to hear that it works.
Global tools still depend on installed .net sdk, so it is quite possible that it fails if rc is not installed (you might all still have rc installed in addition to the release)
