### ISSUE TITLE
BootstrapTestDotNetCore should probably delete old testbuild.fsx.lock

### ISSUE THREAD

**Issue by kblohm** [fsharp/FAKE#1889]
Hi,
I just tried to build fake and the BootstrapTestDotNetCore failed. The reason was an old testbuild.fsx.lock file that caused fake to download old packages. 
After i deleted the file everything worked fine again.
BootstrapTestDotNetCore already deletes ".fake/testbuild.fsx/paket.lock". So testbuild.fsx.lock could probably just be added. Or am i doing something wrong here?

**Comment by matthid** [comment]
Yes you are correct :)
