### ISSUE TITLE
New ReportGenerator.generateReports fails with return code 8 on non-Windows platforms

### ISSUE THREAD

**Issue by SteveGilham** [fsharp/FAKE#1892]
### Description

Running the report generator task in rc-008 fails with "ReportGenerator reported errors: 8" on a Linux platform where the same script works on Windows.  Return code 8 usually means that an attempt was made to directly execute a .net executable.

### Repro steps

Please provide the steps required to reproduce the problem

1. Get a script working on Windows/.net framework
2. Now run it on Linux/Mono

### Expected behavior
There should be no difference

### Actual behavior

Build failure with "ReportGenerator reported errors: 8" ; looking at the code in https://github.com/fsharp/FAKE/blob/master/src/app/Fake.Testing.ReportGenerator/ReportGenerator.fs#L110 it looks like there should be a `|> Fake.Core.Process.withFramework` at the end of the expression to fix this up.

### Known workarounds

Haven't found one that works yet.  The obvious sort of fix-up like

```
      let hack = if Environment.isWindows then String.Empty else "/usr/bin/mono --debug "
      ReportGenerator.generateReports
                     (fun p -> { p with ExePath = hack + (findToolInSubPath "ReportGenerator.exe" ".")
```
**doesn't** work, looking like the ExePath gets parsed all-in-one

**Comment by matthid** [comment]
>  it looks like there should be a `|> Fake.Core.Process.withFramework` at the end of the expression to fix this up.

Yes I think that analysis is correct. Care to send a PR? 
Also @magicmonty did we miss this on the other ones as well?

**Comment by SteveGilham** [comment]
PR sent as requested.

**Comment by magicmonty** [comment]
@matthid I have a look

**Comment by SteveGilham** [comment]
My issue is definitely fixed now with RC 10.

**Comment by matthid** [comment]
Thanks
