### ISSUE TITLE
FAKE .net dll release example

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1895]
### Description

Docs.

### Repro steps

How do I write https://github.com/haf/expecto/blob/master/build.fsx#L129 as FAKE5?

Or in short, can you help me complete https://github.com/SuaveIO/suave/blob/master/build.fsx#L90?

**Comment by matthid** [comment]
You mean releasing to github release page? look at the fake buildscript we add several files to the github. We have a Fake.Api.Github module but it is missing in the modules menu: https://fake.build/apidocs/fake-api-github.html

It needs to be added into the Api submenu
