### ISSUE TITLE
FAKE should fail on invalid input 

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1896]
E.g. ` ./build.sh --single-target --target Pack` doesn't warn or anything; just proceeds with the default build.

**Comment by matthid** [comment]
Accoding to the cli it is not really invalid input.

`fake build --single-target --target Pack`
Can be parsed as 
`fake.exe [fake_opts] build [build_opts] [--] [<scriptargs>...]`
`fake.exe` ~~`[fake_opts]`~~ `build` ~~`[build_opts]` `[--]`~~ `[<scriptargs>...]`
So `<scriptargs>` is `--single-target --target Pack` 

This in return will be parsed by the target module according to:
`fake-run [target_opts] [target <target>] [--] [<targetargs>...]`
`fake-run` ~~`[target_opts] [target <target>] [--]`~~ `[<targetargs>...]`

So `<targetargs>` is `--single-target --target Pack` and fake will run the default target with the two given arguments, according to https://fake.build/core-targets.html#Targets-with-arguments

Therefore this cannot be detected. We might trigger a warning if we can detect unparsed valid parameters. But the whole point of this is to allow conflicting parameters in a consistent way.

**Comment by haf** [comment]
Why not require `--` to pass arguments to the target?

Can you make it `--single-target` to be consistent with the rest of the world?

**Comment by matthid** [comment]
> Why not require -- to pass arguments to the target?

Because with the current system it will not work the way people would expect it to. In particular the first parser (from the runtime) the `--` will be matched and then it will no longer be there for the second parser.

> Can you make it --single-target to be consistent with the rest of the world?

Yes we could add / change that. Would we change `--environmentvariable` to `--environment-variable` as well?

**Comment by haf** [comment]
Yes those would be changed too.
