### ISSUE TITLE
FAKE paket pack only packages net461

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1897]
Example:

```

Target.create "Pack" <| fun _ ->
  let pkg = Path.GetFullPath "./pkg"
  let props (project: string) (p: Paket.PaketPackParams) =
    { p with OutputPath = pkg
             IncludeReferencedProjects = true
             Symbols = true
             ProjectUrl = "https://suave.io"
             Version = release.SemVer.ToString()
             WorkingDir = Path.GetDirectoryName project
             ReleaseNotes = String.Join("\n", release.Notes)
             //LicenseUrl = "https://opensource.org/licenses/Apache-2.0"
             TemplateFile = "paket.template" }

  projects
  |> Seq.iter (fun project -> DotNet.Paket.pack (props project))
```

**Comment by matthid** [comment]
Did you compare with running paket on the command line? Is this really a fake issue?

**Comment by haf** [comment]
Yes it's a FAKE issue.

**Comment by matthid** [comment]
I thought the solution is to use `dotnet pack`?

**Comment by matthid** [comment]
Honestly I'm not sure what to do. Fake doesn't tell paket which framework to pack? If at all Paket itself needs to be fixed imho.

**Comment by matthid** [comment]
Closing as I think we never implemented `paket pack` support for new sdk project files. In fact afaik you need to use `dotnet pack`. But feel free to open an issue at paket.

**Comment by haf** [comment]
Dotnet pack provides the wrong dependency constraints; overly specific .

**Comment by matthid** [comment]
Yes thrn we need to improve dotnet pack. paket already rewrites the nuspec in that scenario so your use case needs to be part of that. In any case paket is the correct place to discuss and fix (feel free to open an issue there and link to this)
