### ISSUE TITLE
FAKE paket pack doesn't group by framework target by default

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1898]
This https://github.com/Albacore/albacore/blob/master/lib/albacore/nuget_model.rb#L164

**Comment by matthid** [comment]
Did you compare with running paket on the command line? Is this really a fake issue?

**Comment by haf** [comment]
A build system should not just invoke commands, it should be smarter than that because it has more knowledge about the problem it's solving. Otherwise, how could albacore solve this?

**Comment by matthid** [comment]
I probably just don't understand the problem and how it can/should be solved

**Comment by haf** [comment]
Basically, if `dotnet pack` does the right thing, then FAKE+Paket should do the right thing.

A solution is linked in the issue. Another one is in dotnet.

In short; check `TargetFrameworks`, for each, add the dependencies indicated by `paket.lock` with a framework constraint that matches.

**Comment by matthid** [comment]
I thought in new style projects we use `dotnet pack` which internally calls paket?
/cc @forki

**Comment by matthid** [comment]
Closing as I think we never implemented `paket pack` support for new sdk project files. In fact afaik you need to use `dotnet pack`. But feel free to open an issue at paket.
