### ISSUE TITLE
Maybe add ".CMD" to this list? And make the documentation more explicit that the file extensions are appended to the input?

### ISSUE THREAD

**Issue by josiahdj** [fsharp/FAKE#1899]
https://github.com/fsharp/FAKE/blob/7f99a9c4350b6b15a044254977c882574cd72b61/src/app/Fake.Core.Process/Process.fs#L622

In my case, it took me a while to track down why this wasn't finding "grunt.cmd" the way it used to in FAKE 4 (for Windows). Simple fix in my build script was to remove the ".cmd", so I "fixed it" for myself, but this could confuse other people?

**Comment by matthid** [comment]
Is the `PATHEXT` variable not defined on your system?

**Comment by josiahdj** [comment]
It is, and I got it to work once I removed the `.cmd` at the end of the command (`grunt.cmd`) I wanted. Maybe a good way of handling this is:
if `Environment.isWindows` and the end of the `file` given already contains one of the extensions listed in PATHEXT, then don't re-append the `postFix` values from the PATHEXT in the call to `Seq.tryPick`?

**Comment by matthid** [comment]
Ah now I get it. You basically suggest doing a search with empty "suffix" first. Yes that sounds reasonable.

I guess for cross platform compatibility we assume users don't specify the file-extension there

**Comment by josiahdj** [comment]
LGTM
