### ISSUE TITLE
Process no longer returns path with .cmd extension on windows - causing Yarn and npm modules to fail on Windows

### ISSUE THREAD

**Issue by severisv** [fsharp/FAKE#1911]
### Description

The Yarn and npm modules rely on `Process.tryFindFileOnPath` returning the install location with the `.cmd` extension. This works in RC8, but not in RC10 - I'm assuming because of [this commit](https://github.com/fsharp/FAKE/commit/2fb49e312a3fc1381b78feccc71ddb55c2ee7857#diff-774ae7c2a450242e2db4ea0ec27c1a58).

### Repro steps

Perform any npm or Yarn command using the respective module.

### Related information 

Windows
.NET Core 2.1.300-preview2-008533

### Suggested solution

I don't understand the change in the Process module, so I don't know if the new behaviour is expected, but if not it must be repaired to work like it did in RC8.

If the new behaviour is as intended, then the Yarn and npm modules must be changed to add .cmd to the location found on path (Windows). Not sure if/how this affects Mac users.

**Comment by matthid** [comment]
So if there exists a file without extension the `tryFindFileOnPath` function should prefer the file with an actual extension. I think that the function is a lot more useful if it does this (considering cross-plat setups).

The commit was to fix https://github.com/fsharp/FAKE/issues/1899. I guess changing the priorities would still be acceptable to fix both issues.
