### ISSUE TITLE
Msbuild error in rc011:  Illegal characters in path

### ISSUE THREAD

**Issue by gkonterman** [fsharp/FAKE#1915]
Sorry for the short description with no repro, I just ran into this problem at work. I hope I can add more info tonight

I just upgraded to `rc011` and I'm getting the following error:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(283,5): error MSB4184: The expression "[System.IO.Path]::Combine(D:\Git\Path1, D:\Git\Path2" /p:Configuration=Release /p:TargetFrameworkVersion=v4.6.1 /p:Platform=AnyCPU\)" cannot be evaluated. Illegal characters in path. [D:\Git\Project.csproj]`

The msbuild call is:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe  D:\Git\Project.csproj  /m    /v:q    /p:RestorePackages="False" /p:PreBuildEvent="" /p:PostBuildEvent="" /p:TreatWarningsAsErrors="true" /p:LangVersion="7" /p:OutputPath="D:\Git\Output\\\" /p:Configuration="Release" /p:TargetFrameworkVersion="v4.6.1" /p:Platform="AnyCPU"`

Rollback to `rc008` solves it

My guess it has something to do with the tripple slash in `/p:OutputPath`

**Comment by matthid** [comment]
Yes please. more information is definitely required ;)

**Comment by HeinzmeierDornbuschFeldhausen** [comment]
I have the same problem with rc011. Msbuild does not like triple slashes in OutputPath. An error MSB4184 (Path.Combine related) is thrown.

```
Target.create "BuildNetTest" ( fun _ ->
    let projFile = @"D:\fake\SomeProject.csproj"
    let publishLocalDir = @"D:\fake\bin"

    let buildMode = Environment.environVarOrDefault "buildMode" "Release"
    let setParams (defaults: MSBuildParams) =
        { defaults with
            Verbosity = Some(Quiet)
            Targets = ["Build"]
            Properties =
                [
                    "Optimize", "True"
                    "DebugSymbols", "False"
                    "Configuration", buildMode
                    "DebugType", "none"
                ]
         }
    [projFile] |> Fake.DotNet.MSBuild.runRelease setParams publishLocalDir "Build" |> ignore
)
```

**Comment by gkonterman** [comment]
I'm think https://github.com/fsharp/FAKE/pull/1905 is the problem

**Comment by JarnoNijboer** [comment]
Running msbuild with same parameters on cmd line, triggers same error. Removing a slash fixes it.
Should be fixed in #1918

**Comment by Cawifre** [comment]
This may cause a regression of #869. Why wouldn't `TrimSeperator` have actually trimmed the separator? If we're ending up with `\\\` after appending `\\` to the output of `TrimSeperator`, doesn't that indicate a problem?

**Comment by matthid** [comment]
@Cawifre Are you saying that you have a problem with latest? Can you open a new issue?
