### ISSUE TITLE
Using FAKE 5 from a standard netcore project

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fsharp/FAKE#1922]
FAKE 5 scripts involve quite some magic (inserting Paket syntax in the script, adding a reference to a file for intellisense, a custom lock file). We're using VS Team Services for CI and it doesn't seem to like this magic very much (the script runs fine locally but not on the server).

I'm trying now to use just a normal netcore project. This way I can also manage the dependencies directly from the common `paket.dependencies` file in the repo root and run the build simply with `dotnet run`.

Apparently one of the purposes of modularization is the ability to use FAKE from a normal project. But I didn't find any guide to do that. I had some problems with the runtime context. I managed to get this working:

```fsharp
[<EntryPoint>]
let main _args =
  Context.FakeExecutionContext.Create false __SOURCE_FILE__ []
  |> Context.Fake
  |> Context.setExecutionContext

  Target.create "Benchmark" <| fun _ ->
    runDotnet "../src/Benchmark" "run" "-c Release"

  Target.create "Test" <| fun _ ->
    runDotnet "../src/Coxos.Properties" "test" ""

  Target.runOrDefault "Test"

  0
```

Does it look right? Would it be possible to add a section in the starting guide to mention how to use a standard project instead of a script?

**Comment by matthid** [comment]
> Regarding ExecutionContext

Yes I think we need some rudimentary documentation around that. Basically it is there to trigger all the things FAKE does "behind the scenes" in a user-controllable way. In our test-framework we use

```fsharp
      use execContext = Fake.Core.Context.FakeExecutionContext.Create false "text.fsx" []
      Fake.Core.Context.setExecutionContext (Fake.Core.Context.RuntimeContext.Fake execContext)
```

This is in order to do some cleanup after the `use` ends (like fake is automatically killing started processes and stuff like that if configured). It also allows to setup a "new" context (because setting up targets and things like that are saved in the context)

> Regarding VSTS

Can you clarify what the problem is? We actually have a VSTS build here on the fake repository and it worked fine (besides the 30 minute public timeout and other limitations which makes it unusable for us). Additionally, we use fake on TFS-On-premise in work :)

**Comment by matthid** [comment]
> Regarding VSTS

Basically what's missing is a nice to use "Fake-5-Task", but you can workaround that for now by having a dummy `build.proj` file.

**Comment by alfonsogarciacaro** [comment]
Apparently the server couldn't find the intellisense file. Maybe I forgot to add a task to restore it. This was in the logs:

```
2018-05-03T09:29:27.4286075Z Script failed
2018-05-03T09:29:27.4357201Z -> FAKE-CACHING: Could not find file './.fake/build.fsx/intellisense.fsx' in any paths searched. Searched paths:
2018-05-03T09:29:27.4357681Z    [""]
```

Anyways, I like it with the project. Thanks a lot for the pointer about `use`! I'll try to send a PR to the docs to explain briefly how to set up FAKE with a project. Thanks again for your work!

**Comment by matthid** [comment]
The project approach is interesting indeed, though I really hope soon the fake runner is the more straight-forward (and easiest) approach. So feel free to leave feedback on that.
Also I'm currently experimenting with VSTS releases and how to propagate the fake-cache through the pipeline (for speed).

**Comment by matthid** [comment]
@alfonsogarciacaro Can you give feedback on what the final solution was. Did the runner work in the end or did you use a netcore project as indicated above?

**Comment by alfonsogarciacaro** [comment]
I used the netcore project :) It runs fine and looks cleaner to me.

**Comment by matthid** [comment]
I would love to hear about the setup or see some small sample of what exactly you are doing. If you ever document this approach feel free to point me to it :)

Do you use multiple release-stages and build the netcore app via `dotnet run` or deploy the results as artifact?

I guess your CI just contains a single `dotnet run`?

**Comment by alfonsogarciacaro** [comment]
Sorry for the late answer. Please [find here](https://gist.github.com/alfonsogarciacaro/338284f6db05dcf30d2465a85ddf970d) the main file of the netcore project we're using to run FAKE (very simple at the moment, there's no deployment). The .fsproj is just a standard netcore console project with dependencies managed by Paket. And yes, we run CI just with a single `dotnet run` task in the proper directory :)
