### ISSUE TITLE
Make Fake-Cache a bit portable

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1924]
### Description

Currently you cannot move your fake-cache alongside the script without any bad sideeffects.
This issue should be used to investigate where we can automatically invalidate/detect such scenarios and also investigate where we can for example save relative paths to allow copying.

**Comment by OlegZee** [comment]
@matthid, is it the same case as if I put the build sctipt to folder:
![image](https://user-images.githubusercontent.com/513301/39965394-0fb20996-56c2-11e8-85a7-e78b4d2b4948.png)

**Comment by matthid** [comment]
@OlegZee I guess you mean "Moving" the script to a different folder or moving the project?

**Comment by OlegZee** [comment]
@matthid I just moved the script to a samples folder and now I cannot run it without changing current folder.

**Comment by matthid** [comment]
Yes we need to allow that. Current workaround is to `rm -rf .fake`...
Basically I always thought the `.fake` is not in the working directory but alongside the script (or maybe it is always alongside `paket.dependencies`, not sure which one is better actually).

**Comment by OlegZee** [comment]
Btw, do you know FAKE is also affected by an https://github.com/dotnet/cli/issues/4808? Offtopic here but hardly deserve its own issue.

**Comment by matthid** [comment]
Basically yes, however nobody seems to notice because fake is in the root folder and not a lot of stuff is living there I guess. Or people use chocolatey ;)

**Comment by matthid** [comment]
I think this is solved by storing relative paths (relative to the script) into the fake cache in addition to detecting the nuget-packages directory. This should cover most cases besides the one you posted @OlegZee . To handle that scenario I think it makes the most sense to detect that error and hint the user into deleting the `.fake` directory.

**Comment by matthid** [comment]
or save the `.fake` directory always alongside the script path (not the working directory)
