### ISSUE TITLE
FAKE5 Targets always complete as "Failed"

### ISSUE THREAD

**Issue by BlythMeister** [fsharp/FAKE#1929]
### Description

The logging of a target always finished with "Finished (Failed) 'TargetName' in <time>

It would appear the the default state on tracing is Failed, and this is never set to success in the target helper if it runs to completion.

**Comment by BlythMeister** [comment]
Sure, our scripts are open source, so if you look at this repo https://github.com/15below/Build.Tools/tree/NewTools
Main.fsx is the entry point, and at the moment the targets are all empty.
When these run you always get the following logs.

Started
No description
Finished

**Comment by BlythMeister** [comment]
Looking at the logs for https://ci.appveyor.com/project/matthid/fake-6w516/build/1.0.1571 it would seem that you get (Success).

I wonder if there is something in the code for the target which sets the status...
However, I think If you do the simple hello world from https://fake.build/fake-gettingstarted.html you will get that symptom

**Comment by JarnoNijboer** [comment]
I've seen the same after upgrading to rc012, while running the following snippet:
```fsharp
Target.create "Bootstrap" (fun _ ->
    Trace.setBuildNumber (sprintf "%s-%s" buildNumber branchName)
)
```
Output:
![image](https://user-images.githubusercontent.com/2635154/40023177-7e9c6f82-57ca-11e8-9e7d-e289ca233a84.png)

**Comment by matthid** [comment]
So it seems to be a minor annoyance - fake printing the wrong stuff, correct?

**Comment by matthid** [comment]
I think this is related to https://github.com/fsharp/FAKE/commit/9d29f00797165f747b2adffc3e8f2be728542ecb. Idea is to report "tasks" as failed when `_.MarkSuccess()` is not called (which indicates an exception). Seems like I have missed some places there.

**Comment by kblohm** [comment]
Instead of using a disposable, cant u just wrap everything in a function that forces u to return succes/failure and handle the try catch finally inside whatever calls the function. That way iyou cant forget to call MarkSucces(). I am pretty sure most people will just forget to call it.

**Comment by matthid** [comment]
> That would of course be a breaking change though.

Yes we could add that as additional API, because we no longer do breaking changes at this point.

**Comment by matthid** [comment]
Actually I failed two times because the default should be `Warning` instead of `Error`. Now `Warning` isn't used at all :)

**Comment by BlythMeister** [comment]
Can someone please explain how I should be writing the target then to use mark success. As I'm a bit confused and can't see in docs

**Comment by matthid** [comment]
Sorry I didn’t make that clear. I think it is an internal bug. Just tried to clarify the issue and reasoning if someone wants to step in

**Comment by BlythMeister** [comment]
But if I have a target which I only do private stuff in, I don't want it to report warning if it was ok.

Imo, if it has an error thrown, it's error.
If it doesn't, its success...

**Comment by matthid** [comment]
Ok but it’s not so easy to detect. But yeah I guess we just need to fix this bug and it will be fine again

**Comment by BlythMeister** [comment]
Psudo code:

Try 
execute target
Mark success
With
Mark failure
Throw

Might not even need the with as default is failure

**Comment by matthid** [comment]
I found the problem and it is fixed with rc13
