### ISSUE TITLE
Fake is printing the target description twice

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1931]
### Description

Fake is printing the target description twice.

### Repro steps

```fs
Target.Description "Build server for PRODUCTION environment"
Target.create "Build.Server.Production" ignore
```

Preview:
<img width="625" alt="capture d ecran 2018-05-16 a 15 03 34" src="https://user-images.githubusercontent.com/4760796/40118486-61c1f2e6-591a-11e8-9f05-08b61137c19a.png">

I think we should remove the white text and show only the green text ?

**Comment by matthid** [comment]
Yes I agree, fixed with https://github.com/fsharp/FAKE/commit/364ee368c6fa788fcb06f5119d0d37a525d64320
