### ISSUE TITLE
NuGet.Restore.RestoreMSSolutionPackages quoting seems broken

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#1933]
```F#
    for s in solutions do
        NuGet.Restore.RestoreMSSolutionPackages (fun x -> { x with
                                                                OutputPath = (Path.GetDirectoryName s) @@ "packages"
                                                                Verbosity = NuGet.Restore.NugetRestoreVerbosity.Quiet
                                                                Sources = [ @"C:\Projekte_BUILD\a_CommonBinaries\nuget" ] }) s
```

![grafik](https://user-images.githubusercontent.com/4236651/40166621-42052c02-59bf-11e8-98cd-eeb5892f9b13.png)

```
PS C:\_build\fake-bootstrap> dotnet fake --version
FAKE 5 - F# Make (5.0.0-rc012.95+vsts.617e5c3e3ac66e15fd822f03d531fe4dce04dd85)
FakePath: C:\Users\rieluk\.nuget\packages\fake.runtime\5.0.0-rc012.95\lib\netstandard2.0\Fake.Runtime.dll
```

The whole quoting code looks suspicious, CLI passing on windows is a bleeping mess.

**Comment by matthid** [comment]
I think we now have a working quoting implementation in place. Problem is I might have mixed that with existing code trying to do manual quoting. Once that is figured out it should work correctly.

In particular I'm pretty sure that https://github.com/fsharp/FAKE/blob/master/src/app/Fake.Core.Process/CmdLineParsing.fs is working (I use it on various projects with weird command line arguments). Point is that we now need to ensure that whatever we give into:

https://github.com/fsharp/FAKE/blob/d099facbe19ed1676e66c74fef295baa43a73c66/src/app/Fake.DotNet.MSBuild/MSBuild.fs#L309

is the correct list of arguments.
Can you take a look and come up with a PR?

**Comment by matthid** [comment]
Ah wait you are talking about nuget task. We probably need to do the same as we did for the msbuild task and use `Args.toWindowsCommandLine` with the correct raw argument list (no quoting required)

**Comment by matthid** [comment]
I'm not even sure what I just saw... https://github.com/fsharp/FAKE/commit/92cd82bb7faf7b9c3635cae3b2e61d4b449ba217

**Comment by 0x53A** [comment]
lol. That is def bonkers.

Ich hab gerade ein schlechtes Gewissen bekommen und wollte auch noch schnell einen PR senden (was ich ja schon am Freitag wollte :D), aber ich glaube mein Computer sagt mir ich soll schlafen gehen ...¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/4236651/40333478-eb65d494-5d58-11e8-841c-0f91718c62c2.png)

![image](https://user-images.githubusercontent.com/4236651/40333557-648ee3f6-5d59-11e8-9e2c-1ef800bd8a8c.png)

**Comment by matthid** [comment]
Don't worry about it. I was bored while waiting for a build ;)
that lock thing might indicate that you should get latest and do a global restore and/or update dotnet sdk to the latest preview (works pretty good on my machine with the global fake-cli tool)

**Comment by matthid** [comment]
However it will not be part of rc16 (because that was the build I was waiting on)
