### ISSUE TITLE
Any interest for an Rsync module ?

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#1935]
### Description

For my work, I am creating an Rsync module for FAKE5. Any interest in adding it here ?

**Comment by matthid** [comment]
For new stuff the current way is to add it to the docs (PR is very welcome) but ideally have separate repositories. Maybe we soon need another github organisation account for fake and add all the repositories there.
Currently everything is in the global fake repository for historical reasons until we have hit the final 5.0 release (then stuff will be reorganized a bit).

So there definitely is interest, but if we add it now it will probably be moved again soon :)
Let me know if this clarifies the situation.

**Comment by MangelMaxime** [comment]
Totally make and this was more or less the idea behind my question :)

I think I will wait for the final 5.0 release and follow the decision taken at that moment.

Quick reflexion:

If the module is hosted directly by the author:

Pros:
- Easier to work on because author control everything
- Smaller repo = easier to read IMO

Cons:
- Can be harder to maintain consistency between all the FAKE modules

If the module is hosted in a global FAKE repo:

Pro:
- Having a consistency between all FAKE modules should be "easier" because the FAKE maintainer need to validate the module
- Easier to find/document the FAKE modules because we know where they are

Cons:
- Harder to contribute
- Building the repo can take a long time like for FAKE and be scary

**Comment by matthid** [comment]
> Can be harder to maintain consistency between all the FAKE modules

Question is what that means. We probably can not do breaking changes anymore. What we can do instead is add new modules (and let old ones die)...

> Building the repo can take a long time like for FAKE and be scary

Yes it is :), But it might become a lot better once we release fake 5 and start to remove the legacy stuff from the build (at least by default or a separate build script)

**Comment by matthid** [comment]
Actually, just to be clear: It could very well be that we decide the other way around as well. We probably try with some modules and if it doesn't work or increases the overhead (as we have so much automation on this repository at the moment) we might just as well add everything here ;)

So if you would like to try it out with your module and report back if you or others have issues with it please report back. Also /cc @OlegZee

**Comment by MangelMaxime** [comment]
@matthid Just to be sure, you want me to try adding the Rsync module into this repo ?

**Comment by matthid** [comment]
I'm just trying to say that I might change my mind on this as I have no idea what the best way forward is, but I'd be happy to see you try the extra repository approach and report back. Also if you feel like this should be in some kind of "fake"-github-organisation I can create one.

**Comment by matthid** [comment]
Ok I created an organization and added both of you, feel free to create repositories there. I'm probably waiting for the 5.0 release before doing anything there ;)

**Comment by matthid** [comment]
Closing this for now, basically feel free to do anything you think is reasonable. Send PRs ;) I don;t have a strong opinion either way as you might have seen in this discussion. Now that we upgraded to latest sdk all the paket perf fixes and enabled `--parallel 3` on all CIs we are basically below 30 minutes again so the pain to add new modules went away for now ;)

**Comment by cloudRoutine** [comment]
@matthid did you forget that we have https://github.com/fsharp-infrastructure ?

**Comment by matthid** [comment]
Oh 0 repositories :)
