### ISSUE TITLE
Add reference to netstandard to prevent issues "You must add a reference to assembly netstandard"?

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1938]
### Description

![image](https://user-images.githubusercontent.com/1866463/40239112-67b72044-5ab5-11e8-8132-856f7a2f9b47.png)

### Expected behavior

Intellisense works.

### Actual behavior

See screenshot

### Known workarounds

Potentially adding `#r "netstandard"`

Most portable workaround:

```fsharp
#if !FAKE
  #r "netstandard" // windows
  #r "Facades/netstandard" // mono
#endif
```

**Comment by kblohm** [comment]
Just an FYI as i have the same problem right now, the workaround for me is 
```
#if !FAKE
  #r "netstandard"
#endif
```
otherwise i get intellisense but FAKE complains about `Multiple references to 'netstandard.dll' are not permitted`

**Comment by matthid** [comment]
Yes that is the correct workaround I have used as well for the same reason. I guess now that we all have this in place we might as well add it to the `intellisense_lazy.fsx file :)

I was a bis hesitant because older editors might choke at that line.

**Comment by kblohm** [comment]
Not sure if this is related, but i tried to use Newtonsoft.Json.Linq and i get:
> A reference to the type 'System.Dynamic.IDynamicMetaObjectProvider' in assembly 'System.Core' was found, but the type could not be found in that assembly

Compiles just fine, but intellisense is broken.

**Comment by matthid** [comment]
Interesting because I thought we emit framework assemblies into the intellisense file as well. But maybe we just miss them for some reason

**Comment by kblohm** [comment]
Intellisense_lazy.fsx does contain System.Core. A minimal example is working here at home, so it might not be a FAKE problem at all. My computer at work might have some super old .net version installed and `#r` might just load an old version then.

**Comment by matthid** [comment]
Yes only `netstandard` is missing, correct? Thinking about this maybe this is a paket issue. Question is how do we know that we have to reference netstandard. Probably once we use a `netstandard` dll paket should have that logic

**Comment by kblohm** [comment]
Yes thats the only one missing. Do you know of a way to deal with `#r` to load a specific version? You can probably always reference the dll directly. But maybe that problem is so uncommon its not worth doing something about it. Who still has .net 3.5 sdk installed.. :)

**Comment by matthid** [comment]
I don't think you can get it running smoothly with .net3.5 :P
But afaik it will always prefer the first referenced version.

**Comment by HoraceGonzalez** [comment]
Just for the record, referencing the `netstandard` reference library this way didn't fix the issue for me: 
```
#if !FAKE
  #r "netstandard"
#endif
```

I had to provide the explicit path to a newer, 4.7.1 facade assembly to get it to work. Eg.

```
#if !FAKE
#r "/usr/lib/mono/4.7.1-api/Facades/netstandard.dll"
#endif
```

**Comment by csmager** [comment]
As I mentioned in https://github.com/ionide/ionide-vscode-fsharp/issues/839#issuecomment-396296095, I think you'll find that this works for mono:
```fsharp
#if !FAKE
  #r "Facades/netstandard"
#endif
```

**Comment by matthid** [comment]
I'm addressing this here for Visual Studio Code: https://github.com/fsharp/FsAutoComplete/pull/402
I do not plan to address this for Visual Studio, but there is already an [issue open](https://github.com/dotnet/fsharp/issues/5216)

Therefore I'm closing this now. I thought about this several times and there is just no good way to address this in FAKE itself.
