### ISSUE TITLE
Mark Process.quote functionality as Obsolete and point to Args.toWindowsCommandLine

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#1940]
### Description

All existing implementations are basically broken for some input (ie inputs containing quotes, ending with backslashes or similar).

We only have one properly working implementation and people should use it.

Accoding to comment in https://github.com/fsharp/FAKE/pull/1932#issuecomment-390391921

**Comment by kblohm** [comment]
Args.toWindowsCommandLine is missing all the functionality that the Process.xxxParam methods have though. Also most of the API (String Module and Process Module at least) are not very clear in what functions quote and or dont quote. I have to look at the implementation every time.
Cake does this pretty clearly as far as i can tell with their [ProcessArgumentBuilder](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Extensions/ProcessArgumentListExtensions.cs).
There is always a quoted and an normal method.

**Comment by matthid** [comment]
Question is do I really care about quotation at all? I just want to start a process with a list of (unquoted) arguments and want the process to receive exactly what I specified.

**Comment by matthid** [comment]
I'm not sure what the best way is. On the other side: The current "way" mostly works

**Comment by matthid** [comment]
This was changed recently
