### ISSUE TITLE
Issues with relative paths when using fake-cli or chocolatey

### ISSUE THREAD

**Issue by kblohm** [fsharp/FAKE#1956]
I am not sure if this is something that FAKE can/should handle, but it is pretty inconvenient.
For example 
```fsharp
let configPath = "relative/path/to/config.json"
let configuration = 
        ConfigurationBuilder()
            .AddJsonFile(configPath)
            .Build()
```
does not find the configuration, because it searches inside the fake-cli folder / the chocolatey folder.
Globbing on the other hand works just fine and searches relative to the build.fsx (probably because of [this](https://github.com/fsharp/FAKE/blob/master/src/app/Fake.IO.FileSystem/GlobbingFileSystem.fs#L122)).

**Comment by matthid** [comment]
I don't think we can - they probably use `AppBase`-Directory or something like that and it cannot be changed later (at least not without dirty reflection hacks which might break other stuff or just break next release).

**Comment by kblohm** [comment]
As far is i know, the (old) dotnet-fake cli tool is always in the root directory together with the build script so that just works.
I had a similair problem with loading configurations in dotnet-xunit. They solved that somehow in one of the latest beta releases.

Yes `Path.GetFullPath` works.

**Comment by matthid** [comment]
I’m closing this for now but if someone comes around with a pr or a link to the docs or a hack of how this can be fixed I’m happy to merge or implement (or re-open).

I definitely would like this to be fixed but I’m not sure if it is possible.

**Comment by tebeco** [comment]
@kblohm 

There's a working code here :
https://github.com/mono/mono/issues/9315#issuecomment-400727297

i will soon update this sample (probably this week end) :
https://github.com/FakeBuild/fake-netcore-sample/blob/master/Nuget/build.fsx

i will re-use the code i linked in the ISSUE

**Comment by tebeco** [comment]
As a work around, user-secrets could be used
Works fine using something like this :
https://github.com/mono/mono/issues/9315#issuecomment-400727297
