### ISSUE TITLE
Separate FAKE Boot into a separate package

### ISSUE THREAD

**Issue by t0yv0** [fsharp/FAKE#196]
Steffen, is there a strong motivation to make it into a package? The only one I can think of is dropping NuGet.Core dependency from FakeLib, is that the reason? Otherwise, given the slightly "kitchen-sink" nature of FAKE, one more module does not hurt it, no?

**Comment by forki** [comment]
ary you still using FAKE.Boot?

**Comment by dsyme** [comment]
Closing old issue
