### ISSUE TITLE
getBuildParam now is Docopt?

### ISSUE THREAD

**Issue by wooderz** [fsharp/FAKE#1964]
Can anyone help me with the Docopt implementation please? Basically because there is no getBuildParam I'm trying to parse command line args.. I have

```
let cli = """
Build
Usage: 
  prog [options]

Options:
  --octopus-api-key=KEY         Octopus Api Key
  --octopus-api-url=URL         Octopus Api Url
  --octopus-project-name=NAME   Octopus Project Name
"""
```

and when I parse --octopus-project-name "Octopus Project Name"

It treats the value as 3 more keys and breaks.. how do you pass command line args with spaces?

**Comment by matthid** [comment]
It basically works on argument arrays so it doesn't even have to take care spaces at all. I'm not sure what the problem is but can you provide a self contained sample with the problem?

Note that spacing is important when writing the usage string.

**Comment by matthid** [comment]
note that `getBuildParam` is just `Environment.environVar` it never was something special

**Comment by wooderz** [comment]
`Environment.environVar` doesn't seem to pick up the values like it used to now though?

```
// Octopus Deploy Info
let cli = """
Build
Usage: 
  prog [options]

Options:
  --octopus-api-key=KEY         Octopus Api Key
  --octopus-api-url=URL         Octopus Api Url
  --octopus-project-name=NAME   Octopus Project Name
"""

let ctx = Context.forceFakeContext()
let args = ctx.Arguments
let parser = Docopt(cli)
let parsedArguments = parser.Parse(args |> List.toArray)

let octopusApiKey = 
  match DocoptResult.tryGetArgument "--octopus-api-key" parsedArguments with
  | None -> ""
  | Some arg -> arg
  
let octopusApiUrl = 
  match DocoptResult.tryGetArgument "--octopus-api-url" parsedArguments with
  | None -> ""
  | Some arg -> arg

let octopusProjectName =
  match DocoptResult.tryGetArgument "--octopus-project-name" parsedArguments with
  | None -> ""
  | Some arg -> arg
```

Is in the fsx and I'm calling it like
`./fake.sh build --octopus-api-key APIKEY --octopus-api-url http://www.octopusapi.url --octopus-project-name "My Project Name"`

Error I get is:
```
Script reported an error:
-> DocoptException: DocoptException: '[|Project;Name|]' could not be parsed
```

**Comment by wooderz** [comment]
I've just tried 

```
let octopusApiKey = Environment.environVar "OctopusApiKey"
let octopusApiUrl = Environment.environVar "OctopusApiUrl"
let octopusProjectName = Environment.environVar "OctopusProjectName"
```

calling it like
`./fake.sh build OctopusApiKey=APIKEY OctopusApiUrl=http://www.octopusapi.url OctopusProjectName="My Project Name"`

And all three vars are empty - I'm obviously missing something here

**Comment by kblohm** [comment]
What is in your fake.sh ? Because your first example is working just fine for me with the global fake-cli.

**Comment by wooderz** [comment]
@kblohm my fake.sh has:

```
#!/bin/bash

set -e -o pipefail

PATH="~/.dotnet:$PATH"
dotnet restore dotnet-fake.csproj
dotnet fake $@
```

**Comment by matthid** [comment]
I think we might need `dotnet fake "$@"` here but I'm not a bash expert.

**Comment by kblohm** [comment]
Sorry, but i do not have a linux installation here. It is working fine on windows. Maybe the arguments are not passed through properly. But your Docopt code is working fine, so you can atleast rule that out.

**Comment by matthid** [comment]
Also depending on your shell you can either set environment variables for a single call:

```
OctopusApiKey=APIKEY OctopusApiUrl=http://www.octopusapi.url OctopusProjectName="My Project Name" ./fake.sh build 
```

Or use the `-e` parameter

```
./fake.sh build -e OctopusApiKey=APIKEY -e OctopusApiUrl=http://www.octopusapi.url -e OctopusProjectName="My Project Name"
```

This is because the cli has changed.

Also note that this ONLY works if you use the `Fake.Core.Target` module in your script (ie if you run targets)

**Comment by wooderz** [comment]
@matthid LEGEND!!

`I think we might need dotnet fake "$@" here but I'm not a bash expert.`

This did the trick! Thanks so much, been doing my head in for hours that one!

**Comment by kblohm** [comment]
`set -e -o pipefail

dotnet restore dotnet-fake.csproj
dotnet fake "$@"`
Is working for me with git-bash.

**Comment by matthid** [comment]
@wooderz Did you get that from the sample? Do we need to fix this somewhere?

**Comment by wooderz** [comment]
Yeah, got it from: 
https://github.com/FakeBuild/fake-bootstrap/blob/master/fake.sh

Happy to do a PR for it if you would like

**Comment by matthid** [comment]
Yes please, I always like PRs :)
