### ISSUE TITLE
global tool doesn't work with dotnet 2.1.3

### ISSUE THREAD

**Issue by jrr** [fsharp/FAKE#1974]
### Description

fake-cli seems to rely specifically on an earlier .net core RC.

### Repro steps

Install the latest stable .net core (2.1.3 as of this writing)

`$ dotnet tool install fake-cli -g --version=5.0.0-*`

(`Tool 'fake-cli' (version '5.0.0-rc015.196') was successfully installed.`)

Attempt to run fake:

`fake`

### Expected behavior

Fake runs

### Actual behavior

Error:
```
$ fake
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-rc1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
(...)
```

**Comment by kblohm** [comment]
Should work after #1972 gets merged.

**Comment by matthid** [comment]
Yes should work since https://www.nuget.org/packages/fake-cli/5.0.0-rc018.244
Feel free to report back.
