### ISSUE TITLE
dotnet publish problems

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#1975]
### Description

* It has a `NoBuild: bool` flag, that is currently removed, but has been re-added https://github.com/dotnet/cli/issues/5331#issuecomment-378432458
* It has no way to pass `/p:BuildProjectReferences=false` to msbuild

Version: FAKE 5

**Comment by matthid** [comment]
Yes PR is welcome.

### Workaround:

Use `CustomParams`:

https://github.com/fsharp/FAKE/blob/master/src/app/Fake.DotNet.Cli/DotNet.fs#L343

Which is part of every record, including the publish one:

https://github.com/fsharp/FAKE/blob/master/src/app/Fake.DotNet.Cli/DotNet.fs#L798

**Comment by matthid** [comment]
This has been added. Now there is a `MSBuildParams` property on most commands.
