### ISSUE TITLE
fake-cli doesn't run on 2.1

### ISSUE THREAD

**Issue by severisv** [fsharp/FAKE#1976]
### Description

Using FAKE5 like this:
```
dotnet tool install fake-cli --tool-path .fake  --version 5.0.0-*
.\.fake\fake run build.fsx --parallel 3 %*
```

This works when 2.1.300-preview2 is installed (even if 2.1-300 is specified in `global.json`), but when it is not (on build servers typically), fake fails like this:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-rc1' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
  - The following versions are installed:
      1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      2.1.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

[Example AppVeyor build](https://ci.appveyor.com/project/SeverinSverdvik/myteam/build/1.0.515)

This happens for me on VSTS aswell.

### Related information 

Operating system: Windows 10

Am I doing it wrong, or does the CLI not work on 2.1-300 yet? If so, how can it be fixed?

**Comment by kblohm** [comment]
`dotnet tool install fake-cli --tool-path .fake  --version 5.0.0-*`
probably installs `5.0.0-rc015.196` (as that is the lowest version matching `5.0.0-*` . You need `5.0.0-rc018.244` for dotnet 2.1.300. So change that to `dotnet tool install fake-cli --tool-path .fake  --version 5.0.0-rc018.244` and it should be fine. 
We might need to update the docs/bootstrap-repo for this.

**Comment by matthid** [comment]
Wow that is unfortunate. Question is: Should we unlist the other rc packages or would this break others?

**Comment by kblohm** [comment]
Unlist should not really break anyone, unless someone forgot to upgrade to 2.1 RTM. In that case its a friendly reminder ;).

**Comment by matthid** [comment]
Ok unlisted, does it help?

**Comment by severisv** [comment]
Running the same build on AppVeyor still fails, but I guess `5.0.0-rc015.196` is cached somewhere? Not sure how to do `dotnet tool install` without looking in caches.

Installing `5.0.0-rc018.244` specifically works (thanks!)

**Comment by matthid** [comment]
Yeah I guess nuget might still install unlisted versions in order to have "Stable" builds. Unfortunately stable means broken for us until we finally release fake 5 :/

**Comment by matthid** [comment]
I don't even know why they allow wildcards there to be honest :/

**Comment by matthid** [comment]
I’m closing this as we will release 5.0 shortly. The only thing we should do is update the docs afterwards...
