### ISSUE TITLE
Discussion: Update templates before release?

### ISSUE THREAD

**Issue by kblohm** [fsharp/FAKE#1981]
I saw you just created #1979 (again ;))
Have you thought about updating "tooling support" before releasing Fake 5?
For example Forge (and therefore Ionide) as well as ProjectScaffold create new projects with Fake 4. I feel like it is somewhat important to update these with/before the release of Fake 5. Otherwise a lot of people will probably default to v4 and updating afterwards is just extra work. 

Stuff that should be done for this:
* create a list of project templates that should be updated.
* decide on the "best" bootstrapping approach to use.
* update :)!

**Comment by matthid** [comment]
I thought we first need to release and then people will update ;)

**Comment by kblohm** [comment]
Fair enough.
I am probably just too impatient because i have to change stuff manually after creating a project :p.
