### ISSUE TITLE
DotNet.clean

### ISSUE THREAD

**Issue by jrr** [fsharp/FAKE#1982]
### Description

There's a DotNet.build and a DotNet.publish; it stands to reason that there should be a DotNet.clean too.

Using Fake 5, installed via fake-cli.

https://fake.build/apidocs/v5/fake-dotnet-dotnet.html

(I'll try to find time to contribute this in the coming weeks)

**Comment by matthid** [comment]
Yes PR is welcome :)

**Comment by matthid** [comment]
Again, PR is welcome but I don't think we need a tracking issue (I'd like to keep the issue list small)
