### ISSUE TITLE
Unable to use Microsoft.AspNetCore.App/All metapackage with FAKE

### ISSUE THREAD

**Issue by kblohm** [fsharp/FAKE#1991]
### Description

I can not reference the `Microsoft.AspNetCore.App` metapackage and use it in my `build.fsx` when running it with FAKE. I can however run the script in FSI.

### Repro steps

1. Use the following `paket.dependencies`
```
// [ FAKE GROUP ]
group Build
    source https://api.nuget.org/v3/index.json
    nuget Fake.Core.Target
    nuget Microsoft.AspNetCore.App
```
2. Use the following `build.fsx`
```fsharp
#load ".fake/build.fsx/intellisense.fsx"

// let execContext = Fake.Core.Context.FakeExecutionContext.Create false "build.fsx" []
// Fake.Core.Context.setExecutionContext (Fake.Core.Context.RuntimeContext.Fake execContext)
open Fake.Core
open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.Hosting

Target.create "Dummy" (fun _ ->
    ()
)
Target.runOrDefault "Dummy"
```
run `fake build`. This does not seem to work. If you uncomment the fakeContext-stuff and run it in FSI, everything is fine. Is this just me or is this a bug?

### Workaround
Reference packages directly
```
// [ FAKE GROUP ]
group Build
    source https://api.nuget.org/v3/index.json
    nuget Fake.Core.Target
    nuget Microsoft.AspNetCore
    nuget Microsoft.AspNetCore.Hosting
```

**Comment by matthid** [comment]
Another instance of:
- https://github.com/fsprojects/Paket/issues/3082#issuecomment-368957508
- https://github.com/fsprojects/Paket/issues/3232

Basically fake uses `netstandard2.0` as framework moniker and not `netcoreapp` - maybe we can indeed change that but I have no idea what other side-effects that has.

**Comment by kblohm** [comment]
Ahh, that is inconvenient. So the workaround is pretty much what i am doing now, at least until we can maybe think of something more clever?

**Comment by matthid** [comment]
No it seems to be by design that you can explicitly not use that package in a library setting (which even makes sense) and currently we consider the script to be a "library" loaded by the fake library (which is technically what happens)

**Comment by matthid** [comment]
Or in other words I'm not quite ready to do hacks in paket or fake just for that package ;)

**Comment by kblohm** [comment]
I read the other issues, that makes sense. Thanks!
