### ISSUE TITLE
Target without description prints "NoDescription"

### ISSUE THREAD

**Issue by zakaluka** [fsharp/FAKE#1993]
### Description

If a Target does not have an explicit description, it is shown in the Console as `NoDescription`.  This is quite unhelpful as it is hard to tell which step the script failed at.

### Repro steps

Create any script without `Core.Target.description`.  Run the script.

### Expected behavior

If there is no description, the system should print the `Target.name`.

### Actual behavior

System prints out `NoDescription`.

### Known workarounds

None.

### Related information 

Windows
Published version of FAKE 5
.NET Core

**Comment by matthid** [comment]
Closing as the PR is probably merged soon.
