### ISSUE TITLE
How to pass target to fake via `dotnet build` ?

### ISSUE THREAD

**Issue by theimowski** [fsharp/FAKE#1998]
I'd like to adapt same build strategy for SAFE template as is currently in FAKE repo.
Can't figure out however how do I pass a non-default target to the cli invocation?

`dotnet build build.proj` <- how do i inject `--target MyTarget` there?

I assume it's possible thanks to [FakeTarget variable](https://github.com/fsharp/FAKE/blob/release/next/build.proj#L19)

**Comment by matthid** [comment]
Yes just use regular msbuild properties

**Comment by theimowski** [comment]
Thanks, `dotnet build build.proj /p:FakeTarget=run` works for me
