### ISSUE TITLE
New dependencies are not detected

### ISSUE THREAD

**Issue by SCullman** [fsharp/FAKE#1999]
### Description

A new dependency is not recognized on a new run.
The last restore is still up to date. Nothing left to do.

### Repro steps

following the steps of https://fake.build/fake-gettingstarted.html
In section "Compiling the application", the MsBuild package is added as dependency
```
#r "paket:
nuget Fake.IO.FileSystem
nuget Fake.DotNet.MSBuild
nuget Fake.Core.Target //"
```

### Expected behavior

When the build script runs after the change, _Fake.DotNet.MSBuild_ is downloaded.

### Actual behavior

_The last restore is still up to date. Nothing left to do._

### Known workarounds

delete lock file

### Related information 

* Operating system Windows 10

**Comment by SCullman** [comment]
Ok, the problem is in front of the computer and did not read the instructions carefully:  

_Just like before add the required module on top via nuget Fake.DotNet.MSBuild, **delete** the build.fsx.lock file and run the script. _

**Comment by 0x53A** [comment]
Can you reopen this as a feature request? I think it should either silently re-install, or at least do a check and print an error.

**Comment by matthid** [comment]
@0x53A I think we already have a feature request for this open. Yes a warning might make sense. But only if it doesn't kill performance (ie we would need to calculate that in the background while running the script and print at the end if finished / force wait in error condition)

**Comment by SCullman** [comment]
Well, the message "The last restore is still up to date." is just wrong or unneeded.
I expected that adding a new dependency to the build script is similar to adding it to paket.dependencies, and fake akts the same as a ``paket install``.

**Comment by matthid** [comment]
@SCullman no it cannot be equivalent to `paket install` because that means your script can break when a new package is released. Fake is equivalent to `paket restore` which does print the same message.

**Comment by matthid** [comment]
Or maybe it could be `paket install`, but I don't trust it will always work we would expect. It would also hurt startup performance, because paket calls are very slow.

**Comment by 0x53A** [comment]
Fake could just string-compare the paket.dependencies.

Then it would also complain about whitespace changes, but it would be fast.

**Comment by matthid** [comment]
@0x53A Yes that would be one option. In fact it does something similar for other files already.
