### ISSUE TITLE
Documentation for Process.execSimple is using deprecated constructs

### ISSUE THREAD

**Issue by frabert** [fsharp/FAKE#2003]
I'm in the middle of migrating some FAKE 4 scripts to FAKE 5 and I ran into some code that uses `ExecProcess` which is marked as deprecated. I went to look on the docs the modern usage, and it still references the deprecated version: https://github.com/fsharp/FAKE/blob/master/src/app/Fake.Core.Process/Process.fs#L488-L491

**Comment by matthid** [comment]
Thanks for reporting
