### ISSUE TITLE
Should FAKE have a Parallel target?

### ISSUE THREAD

**Issue by MorganPersson** [fsharp/FAKE#201]
After a discussion on twitter with @forki about parallel targets it may be worth discussing it a bit more.

* Where would it help / make sense to use parallel targets?
* Logging
  * If each task just logs stuff it will probably be (very) confusing reading the log
  * Buffer all logs until all parallel targets finished
  * other options?
* What happens when one target fails?

**Comment by blacktaxi** [comment]
Any updates on this? +1 to parallel targets.

**Comment by krauthaufen** [comment]
i implemented a global option to specify the number of threads used for building (when possible according to the dependencies)
https://github.com/fsharp/FAKE/pull/676

In general this option may cause problems and obviously obfuscates the log somehow but we were able to reduce build times for an internal project (about 150 MSBuild calls) by a factor of about 4

**Comment by dsyme** [comment]
Address sufficiently by #676
