### ISSUE TITLE
fake-cli 'tool path' install doesn’t seem to work on OS X/linux

### ISSUE THREAD

**Issue by samritchie** [fsharp/FAKE#2013]
### Description

If I install fake via `dotnet tool install fake-cli --tool-path .fake` and then attempt to run `.fake/fake run build.fsx` I get an error like `The application to execute does not exist: '/opt/src/.fake/..//opt/src/.fake/.store/fake-cli/5.1.0/fake-cli/5.1.0/tools/netcoreapp2.1/any/fake-cli.dll'.`

### Repro steps

As above.

### Expected behavior

Should run my fake build.

### Actual behavior

Returns the error `The application to execute does not exist: '/opt/src/.fake/..//opt/src/.fake/.store/fake-cli/5.1.0/fake-cli/5.1.0/tools/netcoreapp2.1/any/fake-cli.dll'.` - it appears to be some sort of path issue (on unix at least). I have not tested on Windows.

### Known workarounds

Installing the tool globally (`dotnet tool install -g fake-cli`) works.

### Related information 

* MacOS 10.13.5, debian:stretch-slim
* 2.1.301 SDK, mono 5.8

**Comment by baronfel** [comment]
See a related comment I made [here](https://github.com/fsharp/FAKE/pull/1989#issuecomment-396057330), but there seems to be a bug in the dotnet sdk around installing tools to a non-default path.

**Comment by baronfel** [comment]
Possibly related: https://github.com/dotnet/cli/issues/8829

**Comment by samritchie** [comment]
The tool definitely installs (i get the directory structure with `.store` etc), it just fails when you run it. I don’t know much about dotnet tools, but the path it’s complaining about is clearly wrong.

**Comment by baronfel** [comment]
One of the bugs I linked mentions using a relative `tool-path` causes the failure, which we use unedited in the `.cmd` and `.sh` files. Perhaps those files should expand the path to be absolute?

More info: https://stackoverflow.com/questions/7126580/expand-a-possible-relative-path-in-bash

**Comment by baronfel** [comment]
Yes, that worked for me: `dotnet new fake -b tool -tp $(pwd)/.faketool` resulted in `.faketool/fake`, which runs correctly.

**Comment by baronfel** [comment]
So the fix here should be to resolve the passed-in toolpath in the cmd and sh files (which naturally will need to be platform-specific) to make sure we use an absolute path for the toolpath

**Comment by baronfel** [comment]
Slack is reporting that relative paths work fine on windows, so this fix can just go in the `fake.tool.sh` file.
