### ISSUE TITLE
Documentation of FAKE 5 API (cosmetic).

### ISSUE THREAD

**Issue by Rodhern** [fsharp/FAKE#2017]
I see this text in [The FAKE 5 Migration Guide](https://fake.build/fake-migrate-to-fake-5.html): 

> ... if you use Target.Create, but ...

So I look up [Fake.Core.Target](https://fake.build/apidocs/v5/fake-core-targetmodule.html) . There is a function there called `create` listed as `create(name body)`.

I don't think it is completely consistent in the guide and documentation when a method is spelled with an initial lower case letter and when an upper case letter is used.

Anyway the thing that caught my eye is the parenthesis. If you are used to F#, when you see, `create(name body)`, you may wonder if `name` is a function, when in this case it is a `string`. Maybe it is a standard way to describe APIs that I don't know. Is it done like this on purpose?

**Comment by matthid** [comment]
Yes both are wrong unfortunately.
Obviously it needs to be `Target.create` as that is what we use now.

An yes the parenthesis are wrong it should probably read `create name body`...

**Comment by matthid** [comment]
I think the problem is FSharp.Formatting and I reported the bug here: https://github.com/fsprojects/FSharp.Formatting/issues/472
