### ISSUE TITLE
Want to keep packages folder in root path or How to used  paket.references in Group reference 

### ISSUE THREAD

**Issue by aarunraja** [fsharp/FAKE#2025]
### Description

Want to keep all my dependence (package folder) in root folder only.  used paket.references to achieve, but getting **FileNotFoundException: Could not find file '..\script\paket.dependencies** error.

### Repro steps
I have folder structure as specified below.
src
--> script
--> build.fsx
--> fake.cmd
--> paket.references
--> svc
--> packages
--> paket.dependencies

the script folder will have F# Make script. in that i have refer my group packet. the code snap given below
#r "paket: groupref build //"

My paket.references will look like this

// [ FAKE GROUP ] group Build source https://api.nuget.org/v3/index.json nuget Fake.Core.Target

when i try to run my script getting below error
There was a problem while setting up the environment:
-> FileNotFoundException: Could not find file '..\script\paket.dependencies'.

### Expected behavior
All my dependence should be in root folder only (package folder). the script should run with all it dependence .

### Actual behavior
Getting FileNotFoundException: Could not find file '..\script\paket.dependencies error.

### Known workarounds
we can reference the components by Absolute Path. 

need a document or reference how i can use  Absolute Path.

Sample code available [here ](https://github.com/aarunraja/Fake5/tree/master/folderStrct)

**Comment by matthid** [comment]
Yes this scenario should work... PR is welcome but will take a look eventually.

**Comment by matthid** [comment]
Ah it took me a while to realize what the actual failure was because it was working on my end:

1. `git clone ...`
2. `cd folderStrct`
3. `fake run script/build.fsx` <- works as expected
4. `cd script`
5. `fake run build.fsx` <- fails as discussed above

So there is your first workaround: Change your working directory (honestly that is probably what you want anyway)... Investigating further

**Comment by matthid** [comment]
(Btw: Your script misses a call to `Target.runOrDefault "All"` at the end to actually do something)

**Comment by matthid** [comment]
Ok this should work properly with the next release. You might need to delete the `.fake` directory. Thanks for the report.
