### ISSUE TITLE
FAKE.Lib package not listing dependencies, also should ideally depend on lower FSharp.Core 

### ISSUE THREAD

**Issue by dsyme** [fsharp/FAKE#2026]
### Description

A few issues based on updating to FAKE 5.2

* The FakeLib.dll in FAKE package `tools` references FSharp.Core 4.5.0.0, a very recent release of FSHarp.Core. This means it is not usable with the fsi.exe available in Visual Studio 15.7 for example. Guidance on http://fsharp.github.io is that libraries should depend on the lowest version of FSHarp.Core that is "reasonable" to allow more clients to use the library.

* The FAKE.Lib package on nuget doesn't list its dependencies properly https://www.nuget.org/packages/FAKE.Lib/

I recommend that at least the `FAKE.Lib` package list its dependencies correctly so we can accurately acquire a dependency on this library

**Comment by matthid** [comment]
Fakelib is obsolete at this point but yeah this might be an issue worth fixing. Historically this always was a problem with new FSharp.Core releases. You can however load the new individual fake packages as they reference a lower FSharp.Core version (using paket and load scripts should work in theory)

Or you can use an older fakelib.dll...

**Comment by dsyme** [comment]
> Fakelib is obsolete at this point but yeah this might be an issue worth fixing. Historically this always was a problem with new FSharp.Core releases. You can however load the new individual fake packages as they reference a lower FSharp.Core version (using paket and load scripts should work in theory)

Roughly which package should I reference instead of FakeLib? thx

**Comment by matthid** [comment]
All the new ones depending on the API you use:

- https://www.nuget.org/packages/Fake.Core.Target/
- https://www.nuget.org/packages/Fake.IO.FileSystem/

Should be mentioned in every API on it's documentation page.

For example if you navigate to `Environment` on the API reference:

![image](https://user-images.githubusercontent.com/1866463/43038205-7b034dde-8d15-11e8-9d30-d68e39fd2144.png)


Just make sure you are on the `v5`-Api Reference or use the "modules" menu to find the correct API.

**Comment by matthid** [comment]
I thought about this some more. I'm not so sure anymore if we would fix this. Considering this problem has existed ever since we would recommend staying on an older version of fakelib overall. Is there a specific need for you to upgrade the package? I'm asking because all the "old" APIs are basically frozen and all the "new" APIs are available via new packages.

**Comment by matthid** [comment]
I'm closing this as historically we always updated to latest `FSharp.Core` in legacy "FakeLib" for other reasons. For the "new" fake modules we indeed use a lower `FSharp.Core` version (`4.3.4`) which is accoding to guidelines (IE the fake runner uses latest `FSharp.Core` while the modules use a lower one)
