### ISSUE TITLE
replaceInFiles changes the Encoding UFT8 without BOM to UTF8 with BOM

### ISSUE THREAD

**Issue by bsteinemann** [fsharp/FAKE#2032]
### Description

I am using the method ['replaceInFiles' (Template.fs)](https://github.com/fsharp/FAKE/blob/575330d8eab58177152bc79963b3b21599aef76e/src/app/Fake.IO.FileSystem/Templates.fs#L23) to patch my configurations files. The files need to be encoded in UTF8 without BOM. When using replaceInFiles the encoding of the File is changed from UTF8 without BOM to UTF8 with BOM.

This happens because of the default encoding in the [File-Module](https://github.com/fsharp/FAKE/blob/575330d8eab58177152bc79963b3b21599aef76e/src/app/Fake.IO.FileSystem/File.fs#L107) is UTF8.

### Repro steps

- create a file encoded with UTF8 without BOM
- use the replaceInFiles to replace anything in the file

The encoding of the file is now UTF8 with BOM.

### Expected behavior

Using replaceInFiles should not change the encoding of the file.

### Suggested Solution

Since the methods in the File-Module use the method ['getEncoding'](https://github.com/fsharp/FAKE/blob/575330d8eab58177152bc79963b3b21599aef76e/src/app/Fake.IO.FileSystem/File.fs#L17) to detect the encoding of existing files and the encoding UTF8 with a BOM can be detected. The default encoding should be UTF8 without BOM. This would prevent a change of the file encoding of files encoded in UTF8 without BOM.

I am aware of the fact that this change could cause problems for other people if they are writing new files because the encoding of new Files would change to UTF8 without BOM.

### Workaround

Rewriting the file with the encoding UTF8 without BOM after using 'replaceInFiles' solves the problem for me.

**Comment by matthid** [comment]
Yes I agree that `replaceInFiles` shouldn't change the existing encoding (just like other helpers don't by default). This is definitely a bugfix and a PR would be welcome and merged.
