### ISSUE TITLE
Allow exclusion of the OutputDirectory on a nuget restore

### ISSUE THREAD

**Issue by bronumski** [fsharp/FAKE#2033]
### Description

I have a mixed solution with legacy cs projects and dotnet standard projects. When running the restore on the solutions nuget packages I end up with .net standard packages being restored to the  packages folder which is not only unnecessary but also causes issues with my nuget pack step later on in the build process.
If the nuget restore allows for the exclusion of the output directory parameter it would work correctly with the legacy projects having their packages restored to the default ./packages folder and the .net standard projects having there dependencies in the centralised cache.

### Repro steps

```
RestoreMSSolutionPackages (fun p ->
      { p with
          ToolPath = findNuget
          OutputPath = null
          //OutputPath = no output directory set, tried using null but that doesn't work either
          Verbosity = Restore.NugetRestoreVerbosity.Detailed
          Retries = 4 }))
```

### Expected behavior

No OutputDirectory in the generated workaround

### Actual behavior

OutputDirectory is always included regardless which prevents nuget from deciding where to restore packages.

### Known workarounds

Rewriting a local version of the restore packages function:

```
let private verbosityToString (v:Fake.DotNet.NuGet.Restore.NugetRestoreVerbosity) = (match v with | Fake.DotNet.NuGet.Restore.Quiet -> "quiet" | Fake.DotNet.NuGet.Restore.Detailed -> "detailed" | Fake.DotNet.NuGet.Restore.Normal -> "normal")
let RestoreMSSolutionPackages setParams solutionFile =
    use __ = Trace.traceTask "RestoreSolutionPackages" solutionFile
    let (parameters:Fake.DotNet.NuGet.Restore.RestorePackageParams) = Fake.DotNet.NuGet.Restore.RestorePackageDefaults |> setParams

    let sources = parameters.Sources |> Fake.DotNet.NuGet.Restore.buildSources

    let args =
        [
            yield! ["restore"; (solutionFile |> Path.getFullName)]
            //yield! ["-OutputDirectory"; parameters.OutputPath |> Path.getFullName]
            yield! sources
            yield! ["-verbosity"; (verbosityToString parameters.Verbosity)]
        ] |> Args.toWindowsCommandLine

    Fake.DotNet.NuGet.Restore.runNuGetTrial parameters.Retries parameters.ToolPath parameters.TimeOut args (fun () -> failwithf "Package restore of %s failed" solutionFile)
    __.MarkSuccess()
```

**Comment by matthid** [comment]
I don't think I understand, can you please provide steps to reproduce and/or the output you see (when it is failing

**Comment by matthid** [comment]
not quite. A small sample would help because:
- paket uses the “packages” directory as well so you might have different tooling accessing the same directory in different ways
- I don’t recall that OutputDirectory has anything to do with “restore”. dotnet core projects should always restore to global cache and old style projects restore always to “./packages”. The output directory doesn’t really change that.

A small sample would let me reproduce it locally. But I assume setting output directory to “./packages” might interfere with nuget in a unintended way. Can you choose a different directory?

**Comment by matthid** [comment]
If your suggestion is to remove `-OutputDirectory` from the commandline if `null` is given? Feel free to send a PR for that.
