### ISSUE TITLE
gitlab ist nicht bunt

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#2037]
would be awesome if this were green:

![grafik](https://user-images.githubusercontent.com/4236651/43211636-4ac02c9e-9032-11e8-9f8c-97196e9b17a4.png)

**Comment by 0x53A** [comment]
Adding

```f#


nuget Fake.BuildServer.GitLab

...

// Init buildserver
Fake.Core.BuildServer.install [ Fake.BuildServer.GitLab.Installer ]

```

helped :)

**Comment by 0x53A** [comment]
Hm, it helped only partially:

Now the output from fake itself is colored, but output from msbuild (which is colored when I execute it from cmd) is grey.

Is there a way to pass-through msbuild colors to gitlab?

**Comment by matthid** [comment]
Yeah Farben :)

**Comment by matthid** [comment]
I have no idea what's going on with msbuild. If we redirect the output than there is obviously no color. If we don't redirect the output I feel like it is a msbuild problem.

I'd love if you could check the root cause :)

**Comment by 0x53A** [comment]
> I'd love if you could check the root cause :)

Don't count on it, my imaginary to-do list is really big.

I'm just happy that fake itself is colored now ;)
