### ISSUE TITLE
[Opinion] Expecto Runner should not pass any parameters by default

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#2039]
Unittest DLL:

```c#
Runner.RunTestsWithArgs(Impl.ExpectoConfig.defaultConfig.WithParallel(false), args, ...)
```

Fake script:

```f#
Fake.DotNet.Testing.Expecto.run id [ testExe ]
```

__Expected:__

Just logically speaking, I have set parallel to false in the exe, have not specified anything in my script, so I expect it to run serially.

__Actual:__

command-line:

```
Tests.exe --parallel --parallel-workers 0 --fail-on-focused-tests --version
```

Instead fake passes ``--parallel`` and so the tests run in parallel.

__Workaround 1:__

```f#
Fake.DotNet.Testing.Expecto.run (fun o -> {o with Parallel = false }) [ testExe ]
```

__Workaround 2:__

in the c# test-exe:

```c#
args = args.Except(new[] { "--parallel" }).ToArray();
```

__Fix:__

This would be a breaking change, but the proper fix would be to make the properties Options. If they are not set, they stay at None and are not passed to the exe.

**Comment by matthid** [comment]
Yes PR would be welcome :)

**Comment by matthid** [comment]
If you don't specify anything in the command line it will run parallel as well, correct (afaik that is just the default in expecto)?

**Comment by 0x53A** [comment]
Yeah, I think so

**Comment by matthid** [comment]
We could just set the default to `false` which would change the behavior in fake to not pass the argument at all
