### ISSUE TITLE
[Question]  Deutsche Umlaute / parallel restore

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#2049]
We use gitlab (hosted)

![grafik](https://user-images.githubusercontent.com/4236651/43630963-144d27da-9702-11e8-945a-950353333e8d.png)

1) ``Pakete f�r`` The buildserver is a German windows, do you have any idea if/how I can change the encoding so it prints special characters correctly?  
This seems to be an issue between the gitlab-runner and fake, if I just open a cmd prompt and execute the script, it prints it correctly.

2) One time in ~400 builds I got this:

```
Starting full restore process.
Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist.
Script reported an error:
-> Junction failed with code = 1
```

We have one build agent with two parallel builds, so I assume that two builds were started at exactly the same time, getting a conflict during restore.

**Comment by matthid** [comment]
>Pakete f�r 

Do I understand this correct that you run a batch script in your fake build and then the encoding is incorrect?
If you run the batch script in a shell it works properly?

> One time in ~400 builds I got this:

Can you run in verbose and try to get a full stack of this (or at least set [`FAKE_DETAILED_ERRORS`](https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.netcore/Program.fs#L89) if running in verbose prevents the race condition). We probably should document this feature.

**Comment by 0x53A** [comment]
> Do I understand this correct that you run a batch script in your fake build and then the encoding is incorrect?
If you run the batch script in a shell it works properly?

gitlab-runner.exe -> build.bat-> dotnet fake: ``�``
(open cmd by hand) ->build.bat-> dotnet fake: ``ü``

I've managed to fix other similar issues by setting the console encoding to UTF-8 in Main.

Do you know if there are any downsides to just setting the encoding generally? Or should it be a new cmd parameter?


> Can you run in verbose and try to get a full stack of this (or at least set FAKE_DETAILED_ERRORS if running in verbose prevents the race condition). We probably should document this feature.

Looking at the error again, I think that it is actually an exception from my own script (``Script reported an error:``)
I got confused by the preceding ``Starting full restore process.``

**Comment by matthid** [comment]
So the problem is the gitlab-runner?

**Comment by 0x53A** [comment]
The problem is between keyboard and chair.

build.bat:

```
dotnet restore build.csproj
dotnet fake ...
```

The ``�`` is printed by the ``dotnet restore``, NOT by Fake.

Sorry ...
