### ISSUE TITLE
Issues with documentation on fake.build website

### ISSUE THREAD

**Issue by gkalnytskyi** [fsharp/FAKE#2061]
Hello F# Make Team,
I have started learning Fake to someday migrate my company's current mix MSBuild and batch files to Fake. But going through the Getting Started Guide is rather hard for novice because there are typos in it, for example in _Create and Edit scripts with Intellisense_ section the code that should be typed in is not obvious and the same code in the next section contains type of `//"` where just closing quote was intended. I would like to ask how should I report these issue or maybe even submit pull requests with fixes.

Kind Regards,
Georgii

**Comment by matthid** [comment]
Hey Georgii,

> But going through the Getting Started Guide is rather hard for novice because there are typos in it
> I would like to ask how should I report these issue or maybe even submit pull requests with fixes.

Yes, please either report them (ie where exactly?) or just fix them in the markdown files as part of this repository and send a pull request:

- Indexpage: https://github.com/fsharp/FAKE/blob/release/next/help/templates/indexpage.cshtml
- Template: https://github.com/fsharp/FAKE/blob/release/next/help/templates/template.cshtml
- Content: https://github.com/fsharp/FAKE/tree/release/next/help/markdown

If not can you please send a link to the page you mean with a list of errors we made?

> same code in the next section contains type of //" where just closing quote was intended

Note that using `//"` is sometimes required for technical reasons, therefore we tried to add it to all samples (just to be safe).

**Comment by gkalnytskyi** [comment]
Thanks a lot! I'll try to help.
