### ISSUE TITLE
Vault does not prevent printing secrets to output

### ISSUE THREAD

**Issue by BlythMeister** [fsharp/FAKE#2071]
### Description

If I store secrets in the vault and someone sends a pr (or runs locally) to print my secrets to console they will print.

### Repro steps

Create a vault variable.
Print the contents to trace
Contents show fine

### Expected behavior

Contents are redacted

### Actual behavior

Secrets can be leaked out of a vault

### Known workarounds

Manually register secrets with TraceSecrets.Register

Still not perfect as a simple console.writeline or file.write and attach artifact will leak the secret.

Inject your key or IV at build time using your build server, but that kinda defeats the point of the vault.

**Comment by matthid** [comment]
I'm not sure this is something we can solve easily, because the idea of the vault is to not keep stuff in memory, as soon as we keep them in tracesecrets they are in memory ...

**Comment by BlythMeister** [comment]
I agree completely, but maybe the docs should be updated to reflect this.

At the moment the docs say this helps not to leak secrets, but I don't see how that is the case.
It's no different to me putting an environment variable into my build tools.

If anything it's less secure that using a secure variable (in teamcity and appveyour at least) as tools often automatically redact values you mark as secure.

I'm struggling to come up with a use case where this is considered "secure".
This is just obfuscation since all the keys are in a file, in the repo.

**Comment by matthid** [comment]
Also I'm not sure if this is a problem because the vault is intended to be used with compatible build servers (like vsts) which will hide the output again. And it is probably good practice to not have the secrets lokally.

If however for some reason you want to hide your output by fake then your workaround is the way to go.

Does that make any sense whatsoever?

**Comment by BlythMeister** [comment]
No I'm well and truly lost 😂

**Comment by matthid** [comment]
> If anything it's less secure that using a secure variable

It should be combined with those features if possible, not replace them.

**Comment by matthid** [comment]
all the vault does is remove those variables from environment variables and makes it explicit instead of implicitly forwarding the secrets to all your processes :/

**Comment by matthid** [comment]
basically what this does if processes crash and make a memory dump or if processes print all environment variables then your vault variables will not be there.

Honestly the feature was developed very close to vsts secret variables and complements them. I haven't looked at how this would integrate into other systems, but I believe it is open and documented quite good so others can step in now ;)

**Comment by BlythMeister** [comment]
I think if they key and iv also came from variables in would feel more comfortable with it.
The way I read  the docs was that it was a replacement for ci tools secret stores, whereas it not.

I'm also not sure how the vault having encryption means that the build servers won't know to redact the content, because the build server itself doesn't know the decrypted value.

**Comment by BlythMeister** [comment]
Maybe I'm over thinking it, but in my professional role, security on build and deploy is a key part 😂

**Comment by matthid** [comment]
the build servers know the secrets because they are providing them? This feature in no waz means you should add stuff to the repository, maybe I should point that out in the docs

**Comment by BlythMeister** [comment]
A 1 liner in the docs as a warning that a secret could still be written to screen or disk by a malicious actor would make me much more comfortable...whilst not solving the problems with security in the build chain, it's making users aware of the pitfalls 😀

**Comment by BlythMeister** [comment]
Right, I think I understand better now...so the build script creates the key and iv on the fly to take the secret and encrypt whilst in use?

**Comment by matthid** [comment]
What about https://github.com/fsharp/FAKE/pull/2070/commits/9cba25b97a3bdd3afc11165272fcfebce73bbe1e ?

**Comment by matthid** [comment]
And https://github.com/fsharp/FAKE/pull/2070/commits/828dc7d5a86476514bf58d9f9e7b8a35469348f0

**Comment by BlythMeister** [comment]
Yeah, that sounds good.  Makes it clear that this isn't a replacement for build server secrets 😀

**Comment by matthid** [comment]
It doesn't feel like people want to join the discussion. I guess it will be a expert feature for writing adapters for CI systems anyway.
