### ISSUE TITLE
Unknown globbing input

### ISSUE THREAD

**Issue by giacomociti** [fsharp/FAKE#2073]
while migrating to FAKE 5 I got this error message:

     (Unknown globbing input '\**\bin\Debug\*.Tests.dll', try to use a relative path and report an issue!)

Following the message I solved the issue (using the relative path `.\**\bin\Debug\*.Tests.dll`) and now I'm reporting it:)

Thanks

**Comment by matthid** [comment]
So this was working before and behaving like your relative path, correct?

**Comment by giacomociti** [comment]
yes, with FAKE 4.64.13 it was behaving like a relative path even if the starting dot was missing.
Also notice that the original expression was

     !! "/**/bin/Debug/*.Tests.dll"

so in the error message the slashes are reversed (of course I'm running on Windows 10)

**Comment by matthid** [comment]
Ok I guess the error message and behavior is reasonable. We should change the message in that particular situation (where we detect starting `/` or `\`) and remove the "report an issue".

Just to explain starting with `/` is considered an absolute path on unix system, therefore I feel like we shouldn't "just" make that a relative path on windows.

I added the message while rewriting some parts of the globbing implementation where I wasn't sure how and when a particular code path can be reached
