### ISSUE TITLE
install via global dotnet tools fails on arch linux

### ISSUE THREAD

**Issue by draptik** [fsharp/FAKE#2075]
### Description

Following installation instructions: results in error message.

```
dotnet tool install fake-cli -g
$ dotnet new | grep FAKE
FAKE - Template                                   fake                                 build/FAKE
```

### Repro steps

```
dotnet new fake -o foo
cd foo
./fake.sh
```

### Expected behavior

Expected no error when running `fake.sh`.

### Actual behavior

```
./fake.sh 
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/patrick/projects/fake-dotnetcore-fake5-demos/foo/.fake/.store/fake-cli/5.5.0/fake-cli/5.5.0/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

### Related information 

I also asked in the "F# Software Foundation Slack General Forum", providing the same infos as here. Although a few people tried to help me, we could not find a solution.

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.3 [/opt/dotnet/sdk]
  2.1.401 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.1.3 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I installed dotnetcore using the official arch repository: https://www.archlinux.org/packages/community/x86_64/dotnet-sdk/

I tried modifying the `DOTNET_ROOT` environment variable, without success.

```
$ la /opt/dotnet/host/fxr/2.1.3/
-rwxr-xr-x 1 root    root    327K 22. Aug 15:49 libhostfxr.so

patrick@raven:~/projects/fake-dotnetcore-fake5-demos/demo3$ echo $DOTNET_ROOT                                                                                                                                     
/opt/dotnet/host/fxr/
patrick@raven:~/projects/fake-dotnetcore-fake5-demos/demo3$ ./fake.sh                                                                                                                                             
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/patrick/projects/fake-dotnetcore-fake5-demos/demo3/.fake/.store/fake-cli/5.5.0/fake-cli/5.5.0/tools/netcoreapp2.1/any/].             
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.                        
patrick@raven:~/projects/fake-dotnetcore-fake5-demos/demo3$ . ~/.bashrc
patrick@raven:~/projects/fake-dotnetcore-fake5-demos/demo3$ echo $DOTNET_ROOT
/opt/dotnet/host/fxr/2.1.3/
patrick@raven:~/projects/fake-dotnetcore-fake5-demos/demo3$ ./fake.sh 
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/patrick/projects/fake-dotnetcore-fake5-demos/demo3/.fake/.store/fake-cli/5.5.0/fake-cli/5.5.0/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

Any other things I can try?

**Comment by matthid** [comment]
I'm quite positive this is an instance of https://github.com/dotnet/cli/issues/9114. Is there a way for me to reproduce this on a docker container for example?

**Comment by draptik** [comment]
I will try to create a docker image. Since Arch Linux is a bleeding edge distro, the result will have a short half live...

**Comment by draptik** [comment]
OK, here is some code. I haven't tested if this reproduces the error.

Dockerfile
```
FROM base/archlinux

RUN pacman-db-upgrade
RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm dotnet-sdk

RUN dotnet tool install fake-cli -g
```

Build image with

```
docker build -t foo/arch-dotnetcore:0.1 .
```

Run image with

```
#!/bin/bash
docker run \
    --rm \
    -it \
    -v ${PWD}/host-folder:/docker-folder/ \
    foo/arch-dotnetcore:0.1 \
    /bin/bash
```
Does this help?

**Comment by draptik** [comment]
I am no "docker-native", but I think it would be good to setup a non-root user in the docker container to reproduce the error.

**Comment by draptik** [comment]
Drop me a line if the above docker infos are enough or if you need a more detailed setup.

**Comment by matthid** [comment]
Yes it does  reproduce and the following works:

`DOTNET_ROOT=/opt/dotnet ./fake.sh`

**Comment by draptik** [comment]
can you explain the steps in the docker container before executing:

`DOTNET_ROOT=/opt/dotnet ./fake.sh`
?

**Comment by matthid** [comment]
No as you write in the initial post I can see the the error and reproduce it.

Once I set `DOTNET_ROOT=/opt/dotnet` it starts to work. Which is what you would expect from https://github.com/dotnet/cli/issues/9114 (which pretty much explains what is going on).

All I did was:

```
$ docker run --rm -it -v E:\:/docker-folder base/archlinux /bin/bash
$ pacman-db-upgrade
$ pacman -Syyu --noconfirm
$ pacman -S --noconfirm dotnet-sdk
$ dotnet tool install fake-cli -g
$ dotnet new -i "fake-template::*"
$ dotnet new fake -o foo
$ Y
$ cd foo
$ ./fake.sh # fails
$ DOTNET_ROOT=/opt/dotnet ./fake.sh # works
```

**Comment by draptik** [comment]
So: what is the proposed solution?

Prepending `fake` with `DOTNET_ROOT=/opt/dotnet`?

**Comment by matthid** [comment]
I'd suggest setting that globally on your system for now. It hopefully will be overwritten locally on demand anyway. (But keep this change in mind in case something goes sideways)

**Comment by matthid** [comment]
The "correct" solution is that the .net guys fix their issue ;)

**Comment by draptik** [comment]
:-) Thanks for the easy workaround! 
And yes, I will have to remember to remove this workaround if things go sideways...

**Comment by draptik** [comment]
Which entry to `.bashrc` would you recommend?

**Comment by matthid** [comment]
Not sure, on gentoo we had some files to setup global variables (and be sure they are set in all of the possible environments)

**Comment by draptik** [comment]
Maybe contact the maintainer of https://www.archlinux.org/packages/community/x86_64/dotnet-sdk/

**Comment by draptik** [comment]
Or should he/she contact you?

**Comment by matthid** [comment]
Yeah contact him but ideally the .NET guys fix it in their source code instead of the maintainer via patch files.

**Comment by matthid** [comment]
I'm closing this as it is tracked elsewhere and there is a workaround.
