### ISSUE TITLE
How should AssemblyInfo files interact with the dotnet SDK?

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#2078]
### Description

While working on https://github.com/fsharp/FSharp.Data/pull/1202, I found that the dotnet sdk writes an assembly info file for you and that files' values override any present by the `AssemblyInfo.fs` file that can be generated though FAKE.  I opened this issue to discuss this situation and see how we could work towards a better user experience here.

### Repro steps

1. Create a dotnet-sdk project
2. Add FAKE
3. Add a script that creates/updates an AssemblyInfo.fs file
4. Perform a build
5. See that the attributes you defined that are any of `System.Reflection.AssemblyCompanyAttribute, System.Reflection.AssemblyConfigurationAttribute, 
System.Reflection.AssemblyFileVersionAttribute, System.Reflection.AssemblyInformationalVersionAttribute, System.Reflection.AssemblyProductAttribute, System.Reflection.AssemblyTitleAttribute, System.Reflection.AssemblyVersionAttribute` are overwritten due to the `WriteCodeFragment` task.

### Expected behavior

Any assemblyinfo attributes I set in AssemblyInfo.fs are set

### Actual behavior

The values of the above attributes are overwritten.

### Known workarounds

1. Disable Assembly File generation via msbuild flag (`<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`)
2. Provide the desired assembly info values through some other mechanism, whether that's `Directory.Build.props`, writing the values into separate project files, or passing the values via MSBuild property parameters.

### Related information 

* OSX
* 5.x
* dotnet sdk 2.1.400
* Effects everyone, but can be worked around easily

**Comment by baronfel** [comment]
Here's the latest version of the MSBuild tasks that derive the assembly information. https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets

There's some useful stuff in there, like source control revision information, so I don't necessarily advocate recommending to disable Assembly Info generation.

**Comment by matthid** [comment]
In fake we use the following approach:

https://github.com/fsharp/FAKE/blob/0b02fc41323338570f06154a99a0753935b1bfe4/build.fsx#L695-L714

I'd suggest to just use the msbuild generation feature instead of fake to rewrite assembly infos? Or disable it completely as you already list as known workaround.

**Comment by baronfel** [comment]
I'm leaning towards that myself, but what I would miss is the convenience of having those module members generated by fake, instead of having to write the reflection lookups myself
