### ISSUE TITLE
Can't resolve Fake.Azure.Kudu.ZipDeployParams for Url field

### ISSUE THREAD

**Issue by chinwobble** [fsharp/FAKE#2080]
### Description

Can't resolve Fake.Azure.Kudu.ZipDeployParams for Url field

### Repro steps

On W10 run the following commands
1. `dotnet new fake --name repro`
2. add `nuget Fake.Azure.Kudu` to fake build group in paket.dependencies
3. run the following script by running the following cmd `fake.cmd build`
```
#load ".fake/build.fsx/intellisense.fsx"

open Fake.Core
open Fake.Core.TargetOperators
open Fake.Azure

Target.create "Deploy" (fun _ -> 
    {
        Kudu.ZipDeployParams.PackageLocation = ""
        Password = ""
        UserName = ""
        Url = new System.Uri("")        
    }
    ()
)

Target.create "All" ignore

"Deploy"
  ==> "All"

Target.runOrDefault "All"
```

### Expected behavior

Script should compile and run correctly

### Actual behavior
when trying to run the build script I get the following error
```
Script is not valid:
        C:\dev\repro\build.fsx (16,8)-(16,11): Error FS0039: The record label 'Url' is not defined.
```
### Known workarounds

none

### Related information 

* Operating system: windows 10 
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: .net core sdk 2.1.401
* Indications of severity: medium
* Version of FAKE (4.X, 5.X): fake 5.5
* (if performance issue) Performance information, links to performance testing scripts

**Comment by matthid** [comment]
I'd assume you somehow are using the api incorrectly but I'm on phone right now. or the field is missing, can you check in the source code?

/cc @isaacabraham

**Comment by matthid** [comment]
Can you try:

```fsharp
open Fake.Azure
Target.create "Deploy" (fun _ -> 
    Kudu.zipDeploy
          { Url = uri
            UserName = username
            Password = password
            PackageLocation = zipFile } 
)
```

**Comment by chinwobble** [comment]
@matthid 
thanks looks like that worked. 

Could you explain why that works and my code doesn't? I thought I was just trying to create record type by specifying all record fields.

**Comment by matthid** [comment]
If you mean "why is it not calling kudo" then that's because the call to 'Kudu.zipDeploy' is missing.

But yes if you ask why you get that specific error I'm not exactly sure. I'd say it could be everything from a specific behavior of type inference (ie it might have worked by prefixing all record field like you did with the first). 

Maybe we should report that instance to visualfsharp and ask for a better error message (tbh I'd have expect that code to compile with the warning: 'expected void but given Kudu.ZipDeployParams, use ignore if you want to ignore the value')

**Comment by matthid** [comment]
Ok I took a look: and apparently it is not enough to only annotate the first field:

```fsharp
namespace Test1

type MyRecord =
    { Label1 : string
      Label2 : string }

namespace Test2

open Fake.Azure

module Program =
    [<EntryPoint>]
    let main argv =
        ignore (fun _ -> 
            {
                Test1.Label1 = ""
                Label2 = ""
            }
            ()
        )
        0
```

![image](https://user-images.githubusercontent.com/1866463/45262706-759b5c00-b41c-11e8-83a3-6730e0dbc347.png)

![image](https://user-images.githubusercontent.com/1866463/45262711-8ba91c80-b41c-11e8-886d-0b70779292c7.png)
