### ISSUE TITLE
DotNet.Cli can not restore projects with ConfigFile option

### ISSUE THREAD

**Issue by ZeekoZhu** [fsharp/FAKE#2082]
### Description

DotNet.Cli can not restore projects with ConfigFile option.

### Repro steps

1. Create a target that restore projects with `ConfigFile` option set:

```fsharp
Target.create "restore:dotnet" (fun _ ->
    !! "**/*.*proj"
    |> Seq.iter (DotNet.restore (fun o -> { o with ConfigFile = Some "./Nuget.Config" }))
)
```

2. Run this target

### Expected behavior

It should execute dotnet restore "/path/to/xxxx.csproj" --configfile "./Nuget.Config"

### Actual behavior

```
Starting task 'DotNet:restore': /path/to/xxxx.csproj
/usr/bin/dotnet  restore  "/path/to/xxxx.csproj" --configFile "./Nuget.Config"
MSBUILD : error MSB1001: Unknown switch.
Switch: --configFile
```

### Known workarounds

I think it is this [line](https://github.com/fsharp/FAKE/blob/d91092c51bb3c6955fc08f51e23ad944fc6762d8/src/app/Fake.DotNet.Cli/DotNet.fs#L841) set a wrong argument name for `ConfigFile` option, so the workaround is using ``DotNet.exec` instead of `DotNet.restore``

### Related information 

* Windows 10 Build 17744 AND docker: microsoft/dotnet:2.1-sdk
* dotnet sdk 2.1.401
* Version of FAKE 5.5.0

**Comment by matthid** [comment]
So the issue is that fake emits `--configFile` instead of `--configfile`, correct?

**Comment by ZeekoZhu** [comment]
Yes, It works, thank you.
