### ISSUE TITLE
Fake is unable to install dependencies

### ISSUE THREAD

**Issue by jcdekoning** [fsharp/FAKE#2088]
### Description

When running a fake script, dependencies don't get installed and the script ends with an error

I tried this on multiple machines (with and without fake being installed up front). We even tried this on a hosted build agent of Visual Studio Team Services (which does not have any state). But in all cases it is not working

### Repro steps

Please provide the steps required to reproduce the problem

1. Have a empty fake script with one dependency
``` 
#r "paket:
nuget Fake.Core.Target//"

open Fake.Core
```

2. Run the script (fake run build.fsx)

### Expected behavior

The script will run without errors and dependencies get installed

### Actual behavior

```
Updating group Main in .\.fake\build.fsx\paket.dependencies
Resolving packages for group Main:
Trial1 (NuGet.GetVersions) did not yield any results, trying again.
   https://api.nuget.org/v3-flatcontainer/fake.core.target///index.json?semVerLevel=2.0.0
Performance:
 - Cli parsing: 234 milliseconds
 - Packages: 3 seconds
   - Resolver: 2 seconds (1 runs)
      - Runtime: 112 milliseconds
      - Blocked (retrieving package versions): 2 seconds (1 times)
   - Average Request Time: 624 milliseconds
   - Number of Requests: 3
 - Script analyzing: 165 milliseconds
 - Runtime: 3 seconds
There was a problem while setting up the environment:
-> Unable to retrieve package versions for 'Fake.Core.Target//'
   -- CLOSED --

   -- OPEN ----
      Fake.Core.Target//  (from .\.fake\build.fsx\paket.dependencies)
-> Request 'https://api.nuget.org/v3-flatcontainer/fake.core.target///index.json?semVerLevel=2.0.0' finished with: []
Hint: If you just upgraded the fake-runner you can try to remove the .fake directory and try again.
```

### Known workarounds

None for clean environments
For environments which already have the packages cached we can copy over the lock file to get the script working.

### Related information 

* Operating system: Windows 10 but also a hosted build agent on VSTS
* .NET Runtime: 2.1.4
* Indications of severity: High (because this is blocking)
* Version of FAKE: 5.6.1

**Comment by matthid** [comment]
This could be considered a paket bug.
You need a space between your package name and `//`

**Comment by jcdekoning** [comment]
Wow....

That solves indeed the problem. Thanks for your answer!
