### ISSUE TITLE
XUnit2 ToolPath not working with tilde (~) parameter inside the path on Mac OS

### ISSUE THREAD

**Issue by tjaskula** [fsharp/FAKE#2094]
### Description

When defining a Xunit2 `ToolPath` parameter the path cannot contain the tilde (~) because it won't be expanded inside quotes.

### Repro steps

Define the following step:

```
Target.create "RunTests" (fun _ ->
    !! testAssemblies
    |> XUnit2.run (fun p ->
        { p with
            TimeOut = System.TimeSpan.FromMinutes 20.
            XmlOutputPath = Some "TestResults.xml"
            ToolPath = "~/.nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe"})
)
```

1. run build script with something like `fake run build.fsx`

### Expected behavior

The test should run

### Actual behavior

The tool is called with the following command:

```
Starting task 'xUnit2'
/usr/local/bin/mono --debug "~/.nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe" -parallel none -xml "TestResults.xml"
```

this won't work because the tilde won't be expanded inside the quotes and we have the following error:

```
Cannot open assembly '~/.nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe': No such file or directory.
```

This works (without quotes)

```
Starting task 'xUnit2'
/usr/local/bin/mono --debug ~/.nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe -parallel none -xml "TestResults.xml"
```

this works too (tile outside the quotes)

```
Starting task 'xUnit2'
/usr/local/bin/mono --debug ~/".nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe" -parallel none -xml "TestResults.xml"
```

### Known workarounds

No workaround found

### Related information 

* Operating system
macOs High Sierra 10.13.6

* .NET Runtime, CoreCLR or Mono Version

mono 5.14.0.177

* Indications of severity

Blocking

* Version of FAKE (4.X, 5.X)

5

**Comment by matthid** [comment]
Who is expanding the tilde if we don't use quotes? I'm a bit sceptical if that would fix the issue

**Comment by tjaskula** [comment]
The command line in terminal of macOs (and linux) is not expanding the tilde if inside the quotes. So if the nugget packages are installes in the user home folder it's better to reference the home folder with the tilde so in my case `~/.nuget/packages/...` expands to `/users/tjaskula/.nuget/packages...` etc.
When the path is passed as argument inside quotes, tilde won't expand.

**Comment by matthid** [comment]
Yes but we don’t execute the command line to start the process, we use process.start. 
The quotes should not be received by the started process.

Can you test with a standalone process.start example if quotes make a difference?

**Comment by tjaskula** [comment]
> Yes but we don’t execute the command line to start the process, we use process.start.
> The quotes should not be received by the started process.

They are according to the output

```
Starting task 'xUnit2'
/usr/local/bin/mono --debug "~/.nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe" -parallel none -xml "TestResults.xml"
```

> Can you test with a standalone process.start example if quotes make a difference?

Yes, I'll do it, however I don't know well what the `process.start` is? I assume it's in the fake API.

**Comment by matthid** [comment]
What I meant was the `System.Diagnostics.Process` API with using `ShellExecute = false` (which I believe is what fake is using always). But yeah you can experiment with the fake api as well.

**Comment by tjaskula** [comment]
I've solved it using the following `System.Environment.ExpandEnvironmentVariables("%HOME%/.nuget/packages/xunit.runner.console/2.4.0/tools/net452/xunit.console.exe")`. It expands to the correct home directory. However I'm not sure it works on Windows.
