### ISSUE TITLE
GitlabCI detection returning false

### ISSUE THREAD

**Issue by TheAngryByrd** [fsharp/FAKE#2095]
### Description

I'm having an issue with using FAKE's built in BuildServer detections for Gitlab.  When looking for the environment variable, `GITLAB_CI` is present with the value `true`.  When using FAKE's `isGitlabCI` is returns `false`.  When I copy the same code and add it to my build script it returns `true`.  Additionally since the built in is returning false, it reports the builder server as `LocalBuild`.  I'm not entirely sure why this is happening.  

Additionally I am hosting our own build agents in docker so I'm not sure if that helps.

```
Starting target 'PrintInfo'
"envVar -> GITLAB_CI=true"
BuildServer.isGitlabCI -> false
Copied.isGitlabCI -> true
BuildServer.buildServer -> LocalBuild
BuildServer.buildVersion -> "LocalBuild"
BuildServer.isLocalBuild -> true
```

### Repro steps

Please provide the steps required to reproduce the problem

1. Setup gitlab runner

2. 
```fsharp

let isGitlabCI = Environment.environVar "CI_SERVER_NAME" = "GitLab CI" || Environment.environVar "GITLAB_CI" = "true"

Target.create "PrintInfo" <| fun _ ->
  // Environment.environVars()
  // |> Seq.iter(fun (key,value) -> Trace.tracefn "%s=%s" key value )
  Trace.tracefn "envVar -> GITLAB_CI=%s" (Environment.environVar "GITLAB_CI")
  Trace.tracefn "BuildServer.isGitlabCI -> %A" BuildServer.isGitlabCI
  Trace.tracefn "Copied.isGitlabCI -> %A" isGitlabCI
  Trace.tracefn "BuildServer.buildServer -> %A" BuildServer.buildServer
  Trace.tracefn "BuildServer.buildVersion -> %A" BuildServer.buildVersion
  Trace.tracefn "BuildServer.isLocalBuild -> %A" BuildServer.isLocalBuild
```

### Expected behavior

isGitlabCI returns true in the build runner.

### Actual behavior

isGitlabCI returns true in the built runner.

### Known workarounds

Look for environment variables myself.

### Related information 

* Operating system
`Linux/docker container`
* Branch 
`5.5`
* .NET Runtime, CoreCLR or Mono Version
```
dotnet --version
2.1.402
```
* Indications of severity
minor
* Version of FAKE (4.X, 5.X) 
`5.5`
* (if performance issue) Performance information, links to performance testing scripts

**Comment by matthid** [comment]
I just checked and it is working for the fake build (see legacy-build.fsx in fake repository). we generate special versions in gitlab and it works. any idea what's going on?

**Comment by TheAngryByrd** [comment]
I really don't understand why it wouldn't work.  What other info can I grab?

**Comment by matthid** [comment]
Some things to analyze this further:
- Can you somehow reproduce this with the docker container locally (by setting the environment variable beforehand for example)?
- Can you try creating your own NuGet package with the `isGitlabCi` statically initialized module variable and use that? Is the problem happening there as well?
- Can you check the exact versions of the `Fake.Core.Environment` (lockfile) and fake runtime (`fake --version`) you are using?
- Can you output the list of environment variables at the start of your script?
- Can you hook into the process start of `fake.exe` and retrieve it's environment variables? (Similar to the Process Monitor of Sysinternals where you can look at the "process start" event and check all environment variables)
- Can you report your findings of the above and the exact steps you tried?

**Comment by matthid** [comment]
Any progress / interest in debugging this? Otherwise I'd assume we can close? Like I said everything is working on the gitlab runner we use for this repository...

**Comment by TheAngryByrd** [comment]
Sorry been on vacation this week. Close it for now. I'll investigate later.
