### ISSUE TITLE
Install Paket as dotnet tool

### ISSUE THREAD

**Issue by nojaf** [fsharp/FAKE#2101]
Since the new [alfa of Paket](https://github.com/fsprojects/Paket/pull/3183), we can install it as dotnet global tool.

I've made a little [sample script](https://github.com/nojaf/fable-docker/blob/remove-mono/sample/build.fsx) where I first install Paket and later use the existing module.

```fsharp
Target.create "InstallPaket" (fun _ ->
    if not (File.exists paketExe) then
        DotNet.exec id "tool" "install --tool-path \".paket\" Paket --version 5.182.0-alpha001 --add-source https://api.nuget.org/v3/index.json"
        |> ignore
    else
        printfn "paket already installed"
)
```

When running `fake.ps1 Build` (or `fake.sh Build`) it adds paket, downloads dependencies and builds the code. This seems like a nice setup for a CI build.

Could we benefit from something similar in the `Fake.DotNet.DotNet` or `Fake.Dotnet.Paket` module?

**Comment by matthid** [comment]
I'd love to see a PR for this, but I have not planned to do it myself.
