### ISSUE TITLE
Improve overall (especially TeamCity) parallel build output support

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#2105]
### Description

Once you enable `--parallel` the output on TeamCity becomes basically useless.
One of the few ways to "fix" this would be to redirect all output from all started processes and properly mark the output with a flowid (and internally manage contexts IDs)

**Comment by BlythMeister** [comment]
I stopped using parallel for this exact reason!

**Comment by matthid** [comment]
@BlythMeister you should have reported it ;) I'm seeing that the first time. Granted all other CIs have  mixed output as well but wow TeamCity with it's grouping is really hard to decrypt

**Comment by BlythMeister** [comment]
I thought it was just TeamCity being bad 😂

**Comment by matthid** [comment]
I think this should be better now, feel free to test and report back

**Comment by matthid** [comment]
Ah wrong issue sorry

**Comment by matthid** [comment]
I think to address this (or rather parallel outpu in general on all systems) we should redirect the output of all started processes and print them only if needed (or together after a particular target has been finished)

This is probably not too hard but some bookkeeping would be required, also we need to indicate/report and detect if there is still progress (as otherwise people might cancel the build)
