### ISSUE TITLE
Error 'Target ""Default"" is not defined.' - but the target is there

### ISSUE THREAD

**Issue by mapfel** [fsharp/FAKE#2107]
### Description

followed tutorial "GETTING STARTED WITH FAKE - F# MAKE" 
https://fake.build/fake-gettingstarted.html

after pasting the 2nd code block of "CLEANING THE LAST BUILD OUTPUT"
https://fake.build/fake-gettingstarted.html#Cleaning-the-last-build-output

I get the error

The last restore is still up to date. Nothing left to do.
run "Default"
Building project with version: LocalBuild
The following targets are available:
   Clean
   Default
Target ""Default"" is not defined. Existing targets:
  - Clean
  - Default
Script reported an error:
-> Target ""Default"" is not defined.

### Related information 

* Operating system: Win 10 Pro DE
* Version of FAKE (4.X, 5.X): 5.7.0 and 5.7.2 tested

**Comment by BlythMeister** [comment]
Can you please provide the command you use to call fake?

**Comment by mapfel** [comment]
fake run build.fsx
fake build

both end up with the same messages

**Comment by matthid** [comment]
@mapfel Can you please upload your script file you wrote?

**Comment by mapfel** [comment]
it is exactly that one from the tutorial
https://fake.build/fake-gettingstarted.html

**Comment by matthid** [comment]
No I think something is different (maybe whitespace?). Can you please zip and upload the folder because something is different. Also the full fake output might be helpful. For me it looks like this:
![image](https://user-images.githubusercontent.com/1866463/46073747-0ea0d580-c186-11e8-8afe-26247f62bf5a.png)

**Comment by matthid** [comment]
@mapfel From your output it looks like some quotes got added in your setup/environment . Did you add some environment variables?

**Comment by mapfel** [comment]
attached a zip, including the fake scripts, my environment and the output
[fake.2107.zip](https://github.com/fsharp/FAKE/files/2420064/fake.2107.zip)

**Comment by mapfel** [comment]
your are right: it was the TARGET variable in my environment!
deleting it, and now I have a "green" output
wtf! strange
thanks guys for your efforts!!

**Comment by matthid** [comment]
@mapfel Yes sadly that is an historic artifact and still there because of backwards compat... Maybe we should warn if it is used.

**Comment by mapfel** [comment]
Yes, in case somebody tries to upgrade like me, he will run into the same situation. It was a very frustrating experience not to be able to run the Getting Started sample.
So FAKE should check the existence of that variable and display a meaningful warning. Would be nice.

**Comment by matthid** [comment]
@mapfel Thanks for reporting, next version fake will tell when it uses the `target` environment variable.
Note that when looking thought the code I noticed that cli arguments are preferred so `fake build --target Default` should have worked as well.
