### ISSUE TITLE
traceImportant produces a normal message in TeamCity

### ISSUE THREAD

**Issue by otto-gebb** [fsharp/FAKE#2108]
`traceImportant` produces a normal message in TeamCity, although it should produce a warning.

### Repro steps

1. Set `TEAMCITY_VERSION` environment variable to 1.
1. Run a FAKE script with a `traceImportant` call in it.

### Expected behavior

The message is logged as

```
##teamcity[message text='your_message_here' status='WARNING']
```

### Actual behavior

The message is logged as

```
your_message_here
``` 

### Known workarounds

Use this function instead of `traceImportant`:

```fsharp
let logWarning str =
  let inline escape text =
    text
    |> String.replace "|" "||"
    |> String.replace "'" "|'"
    |> String.replace "\n" "|n"
    |> String.replace "\r" "|r"
    |> String.replace "[" "|["
    |> String.replace "]" "|]"
  if isLocalBuild
  then Trace.traceImportant str
  else Trace.logfn "##teamcity[message text='%s' status='WARNING']" <| escape str
```

### Related information 

* TeamCity docs: [Reporting Messages For Build Log](https://confluence.jetbrains.com/display/TCD18/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingMessagesForBuildLog)

**Comment by BlythMeister** [comment]
To extend this, error also doesn't work as status should be error.

**Comment by matthid** [comment]
@BlythMeister So when you (or any api you use) uses `traceError` you expect the build to fail?

**Comment by BlythMeister** [comment]
No, but reporting a message as an error message doesn't make build fail (I don't think)

There is another issue that when a target ends with a failure result, the TeamCity listener should post an build failure with the close block error message. (I think)

**Comment by BlythMeister** [comment]
As far as I know, in TeamCity 'ERROR' != 'FAILURE'

**Comment by matthid** [comment]
@BlythMeister Can you verified that?

**Comment by otto-gebb** [comment]
@BlythMeister A build definition has a setting in the "Failure conditions" that is looks like "Fail build when errors are logged".

**Comment by BlythMeister** [comment]
Ahh yeah, I never have that enabled 😂

**Comment by matthid** [comment]
The reason why I asked is because we tried to change stuff there in there past and usually people start to complain that there builds are failing (even when they should fix their builds)

**Comment by matthid** [comment]
Or put differently, when we decide to do it I'll probably close those issues with "by-design" or have a workaround ready ;)
We are not reverting afterwards like we did in the past (people can lock the old versions of the module), but we  should be sure we are doing the right thing.

**Comment by matthid** [comment]
We could for example add documentation for the TeamCity option if that already exists.

**Comment by otto-gebb** [comment]
We can start by changing just the behavior of `traceImportant`, that would generate a warning. Warnings do not fail the build. Can we?

**Comment by matthid** [comment]
@otto-gebb I just want to discuss and decide this once and for all, we changed to policy countless times in the past, reverted releases/prs and I want this to end :)

**Comment by matthid** [comment]
@BlythMeister Yes that would be very welcome, feel free to update the docs (=api docs for the [teamcity module](https://fake.build/apidocs/v5/fake-buildserver-teamcity.html) similar to the [TeamFoundation](https://fake.build/apidocs/v5/fake-buildserver-teamfoundation.html) one) as well (just link to official docs)

**Comment by BlythMeister** [comment]
@matthid this would extend on @otto-gebb pr to include trace error and a "block" ending with a failure.
@otto-gebb, I'll base my branch off of yours and raise it tomorrow. 👍

**Comment by otto-gebb** [comment]
Currently this functionality is broken again, except it's even worse: `traceImportant` produces no message at all. @matthid should I create a separate bug?

**Comment by matthid** [comment]
Yes please, you can link back here. Also I'd love to get help on this....
