### ISSUE TITLE
Accessing script arguments

### ISSUE THREAD

**Issue by mac10688** [fsharp/FAKE#2125]
### Description

I would like to access arguments passed in via command line with my build script.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create test.fsx

2. Insert the following code
```
#load ".fake/build.fsx/intellisense.fsx"
open Fake.Core

Trace.log(Environment.environVarOrFail "config")
```

3. Call script with

`./.fake/fake run test.fsx config=test`

### Expected behavior

The variable config will be found and trace.log will print test

### Actual behavior

The call fails to find config.

### Known workarounds

I will need to set the config as an environment variable.

export config=test

### Related information 

* Operating system: macOS High Sierra
* Branch: master?
* .NET Runtime, CoreCLR or Mono Version: Mono
* Indications of severity: Annoying
* Version of FAKE (4.X, 5.X): 5
* (if performance issue) Performance information, links to performance testing scripts

**Comment by matthid** [comment]
There are several ways to do this:

- Environment variables: 
  * Either set them before executing fake, for example via your shell `MYVAR=myval ./fake run test.fsx` (syntax depends on your shell)
  * Set them via the command line arguments [`-e MYVAR=myval`](https://fake.build/core-targets.html#Command-line-interface-for-the-target-module). Note: This only works when using the `Fake.Core.Target` module, which extends the [`fake run test.fsx ...` syntax](https://fake.build/fake-commandline.html#FAKE-Command-Line)
- Custom CLI:
  * If you use the Fake.Core.Target module: Then you can use [this](https://fake.build/core-targets.html#Targets-with-arguments)
  * If you use your own, see [this example on how to retrieve the remaining fake arguments](https://fake.build/core-commandlineparsing.html#Fake-Core-CommandLineParsing)

Hope this clarifies the situation. Feel free to leave suggestions on how to improve the documentation or implementation.

**Comment by mac10688** [comment]
Oh ok. I can do that. I'm not sure what Fake.Core.Target is. I was hesitant to do this because I didn't want to set global state in my shell. I don't know what the scope of setting an environment variable is so I was afraid of what happened if two builds kicked off at one time. One for production and one for qa. I'm using teamcity to build it and you don't seem to have an issue with it so I will do this. Thank you for your help.

**Comment by matthid** [comment]
@mac10688 Yes try to get some docs for the shell you are using most have a syntax to set environment variables for the current session only or even for a single command (for bash it's just setting the variables before the command on the same line see my example)

**Comment by matthid** [comment]
@mac10688 yes that SO answer is outdated as both the cli as well as the APIs changed. Please feel free to add another answer...
