### ISSUE TITLE
DotNet helper breaks PATH

### ISSUE THREAD

**Issue by adusak** [fsharp/FAKE#2142]
### Description
When building using the DotNet helper the $PATH variable is overwritten rendering some builds broken.
### Repro steps

Have a csproj that executes external tools such as node.

### Expected behavior

DotNet helper preserves the original PATH.

### Actual behavior

DotNet helper sets PATH only to found dotnet cli tool.

### Known workarounds

Do not use DotNet helper

### Related information 

* Operating system 
Windows, this is not reproducible on macOS

**Comment by matthid** [comment]
Is this with `5.8.4` because we just fixed this bug and released `5.8.5`?

**Comment by matthid** [comment]
@adusak Can you take a look at the lockfile and upload it?
Also a minimal sample would probably help

**Comment by adusak** [comment]
Sorry, it was caused only by my stupidity. I had the latest CLI but the lock file contained an old version of the DotNet package. Sorry!

**Comment by matthid** [comment]
@adusak happy to know that it works, thanks for reporting back
