### ISSUE TITLE
Fake.DotNet.NuGet needs to support ContentFiles section in nuspec

### ISSUE THREAD

**Issue by chappoo** [fsharp/FAKE#2144]
### Description

Currently the Fake.DotNet.NuGet module does not support interpolation of the ContentFiles section, which means delivery of content files will not work correctly for .NET Core.  This is documented here:

https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

### Expected behavior

Definition of the ContentFiles element should be possible via `NuGet.NuGetParams` to inject the desired `files` elements.

### Actual behavior

Not possible to define.

### Known workarounds

Currently I'm hardcoding the element in `nuspecs` which are duplicated for the different use-cases, which isn't going to work long-term.

### Related information 

* Windows / MacOS / Linux
* master
* .NET Runtime, CoreCLR or Mono Version
* Fake.DotNet.NuGet 5.8.5

### Comments

I'm just reporting this error with the intention of providing a pull request, but I have to prioritise the work against other things, which will likely mean a week or two before that's possible.  If anyone else picks this up, great, but I'm intending on contributing 👍

**Comment by chappoo** [comment]
Using `dotnet pack` is desirable, but there's no real support for content only packages at the moment.  `dotnet pack` requires an MSBuild project (csproj etc), which then leads to clunky `NoBuild=true`-type settings and an requirement to do a `dotnet restore` (ref: https://github.com/NuGet/Home/issues/4254).

At least, that's what I believe to be the case having looked into it.  Very plausible I could be mistaken...

**Comment by matthid** [comment]
> Using dotnet pack is desirable, but there's no real support for content only packages at the moment. 

I think there is (maybe /cc @enricosada)
But indeed it's probably a bit of playing around with msbuild to get it to do what you want.
