### ISSUE TITLE
ansiColorSupport outputs junk to build log in teamcity and breaks wix build

### ISSUE THREAD

**Issue by MarioVolarevic** [fsharp/FAKE#2146]
### Description

Setup for our tool is built on teamcity using wix toolset with FAKE scripts for preparing the environment.
After updating FAKE in context of teamcity, Msbuild now gets this flag by default which didn't exist before: 
clp:ForceConsoleColor
And it seems that this freezes the wix build at one point.
When this flag is removed, setup is built successfully.

It seems that this was added in this FAKE commit: 
https://github.com/fsharp/FAKE/commit/3e79fd1f0d955c1887811c9e789ef707d816abb3
with this condition:
      `   if BuildServer.ansiColorSupport then [ForceConsoleColor]`
And for Teamcity, this flag is set to true.

Additionally, when the flag is used, gibberish is shown both in the console output and teamcity build log.
It can be also reproduced if called from Command Prompt, teamcity doesn't have to be used.

This is an example of corrupted output.
```C
Build started 12.10.2018. 14:00:46.
[36;1mProject "D:\\<somefolder>\\MyBundle.sln" on node 1 (Rebuild target(s)).
[m[30;1m[36;1mValidateSolutionConfiguration:
[30;1m  Building solution configuration "Release|x64".
```

### Expected behavior
New flags shouldn't break the build.

### Actual behavior
clp:ForceConsoleColor freezes the build and outputs broken text (check example above).
As soon as the flag is removed, build works again.

### Known workarounds
Remove the flag as default.

### Related information 

* Operating system
Windows 10 x64 b1709 16299.665
`msbuild /version` output:
Microsoft (R) Build Engine version 15.8.169+g1ccb72aefa for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
15.8.169.51996

* Branch
https://github.com/fsharp/FAKE/commit/3e79fd1f0d955c1887811c9e789ef707d816abb3
* .NET Runtime, CoreCLR or Mono Version
.NET 4.6.2
* Indications of severity
Breaks the build
* Version of FAKE (4.X, 5.X)
latest fake 5.x: -> fake.5.8.4

**Comment by matthid** [comment]
Are you by any chance using an old version of TeamCity? If yes does the following workaround make it work for you:
```fsharp
BuildServer.Install [...]
BuildServer.ansiColorSupport <- false
```

**Comment by matthid** [comment]
I thought TeamCity supported Ansi-Colors maybe @BlythMeister knows?

**Comment by MarioVolarevic** [comment]
We are using Teamcity 10.0.5 (build 42677)
And we bypassed the issue by setting ConsoleLogParameters  to [ ]
I think if using your proposed method as a workaround or ours, the result it the same and command line parameters don't include: clp:ForceConsoleColor

Also, Teamcity build log output actually becomes colored, but the problem is that weird symbols are output with the colors.

**Comment by BlythMeister** [comment]
I wasn't getting any junk, I was getting colours...

**Comment by matthid** [comment]
@MarioVolarevic while that is a completely sensible standpoint from msbuild develooers the conclusion:

>  so I guess this part is expected and OK.

Is problematic, because what should happen is that TeamCity detects those special characters, and only displays their meaning (ie hides them but colorizes the output). This means they should only be visible to you when you retrieve the 'raw' outpu (is something like that exists)

But yeah in any case it is a bit strange that this would affect the wix build. Are you usung parallel build by any chance?

**Comment by BlythMeister** [comment]
Though, disclaimer, I don't use fake to call msbuild.
For all cli tools I just hand roll the calls to the exe using Fake.Core.Process to give greater control over the arguememts and responses.
Since I have a level of abstraction over fake to hide targets etc.

**Comment by matthid** [comment]
I'm not sure what to do with issue? What should we change?
The only issue I'm seeing here is that the fake output is not colorized while teamcity seems to support some kind of coloring...

As I'm probably not fixing that myself I'm closing this issue for now, but feel free to send a PR.

**Comment by Enigmaderockz** [comment]
How jenkins is using ANSI color output in their logs. came can't be used in Teamcity?
