### ISSUE TITLE
No "dotnet nuget [push|delete]" command

### ISSUE THREAD

**Issue by bratfizyk** [fsharp/FAKE#2148]
I'm using FAKE5, created a project using the dotnet template.

I've managed to add a target that packs my library into a NuGet package (to do so I used DotNet.pack). However, I'd like to automate pushing my package, but I can't see anything that correlates with:

> dotnet nuget push myNuGet.nupkg -k myfancyapikey0123456789 -s https://www.nuget.org/

If it's not available, that's fine - I'm happy to go ahead and try to implement it on my own. Just want to make sure I'm not going to reimplement the wheel.

**Comment by BlythMeister** [comment]
@matthid but it's msbuild "for .netcore"   so don't know if that is the same...

**Comment by matthid** [comment]
@blythmeister yes indeed it is different but it has the same cli and we use the same code to generate it, so from a 'fake' perspective the only difference is that one is 'msbuild.exe' and one is 'dotnet msbuild' otherwise they are treated equally

**Comment by matthid** [comment]
>  As I'm quite new to FAKE, can you tell me if there's another (preferred) way of uploading NuGet packages to the official feed ?

Fake itself uses `nuget.exe push` and `paket.exe push`

> I'd like to set up travis to build my project and automatically upload a new NuGet to the repo. Is there anything wrong with this idea and maybe I should e.g. push my NuGets myself instead ?

I think your suggestions is reasonably, it just isn't implemented yet. But you can always just use `DotNet.exec` and add the `nuget push` argument manually.
