### ISSUE TITLE
Method not found: Void BuildOptions

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#2168]
### Description

Method not found: 'Void BuildOptions

When changing from `storage: none` to removing that line and doing a `paket install` thereafter.

### Repro steps

Please provide the steps required to reproduce the problem

1. `./build.fsx` with code

```
// Define general properties across various commands (with arguments)
let inline withWorkDir wd =
  DotNet.Options.lift install.Value
  >> DotNet.Options.withWorkingDirectory wd
  >> DotNet.Options.withCustomParams (Some (sprintf "/p:Configuration=%s" buildMode))

// Set general properties without arguments
let inline dotnetSimple arg = DotNet.Options.lift install.Value arg

```

2. Step B

Build it

### Expected behavior

No crash

### Actual behavior

```
Script reported an error:
-> BuildFailedException: Target 'BuildAPI' failed.
-> One or more errors occurred. (Method not found: 'Void BuildOptions..ctor(Options, BuildConfiguration, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Boolean)'.)
-> MissingMethodException: Method not found: 'Void BuildOptions..ctor(Options, BuildConfiguration, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Boolean)'.
```

Part of diff from `paket install`:

```diff
-    dotnet-fake (5.6.1) - clitool: true
-    Fake.Api.Github (5.6.1)
+    BlackFox.VsWhere (0.3.2)
+      FSharp.Core (>= 4.2.3)
+    dotnet-fake (5.9.3) - clitool: true
+    Fake.Api.Github (5.9.3)
       FSharp.Core (>= 4.3.4)
       Octokit (>= 0.32)
-    Fake.Core.CommandLineParsing (5.6.1)
+    Fake.Core.CommandLineParsing (5.9.3)
       FParsec (>= 1.0.3)
       FSharp.Core (>= 4.3.4)
-    Fake.Core.Context (5.6.1)
+    Fake.Core.Context (5.9.3)
       FSharp.Core (>= 4.3.4)
-    Fake.Core.Environment (5.6.1)
+    Fake.Core.Environment (5.9.3)
       FSharp.Core (>= 4.3.4)
-    Fake.Core.FakeVar (5.6.1)
-      Fake.Core.Context (>= 5.6.1)
+    Fake.Core.FakeVar (5.9.3)
+      Fake.Core.Context (>= 5.9.3)
```

### Invariants broken

 - I haven't upgraded a major version, there should be no breaking changes
 - I haven't done `paket update`, there are should be no updated packages, going from `storage: none` to nothing about storage.

### Workaround

Downgrade all of FAKE manually, despite it being the same MAJOR version.

### Related information 

* Operating system: macOS
* Branch
* .NET Runtime, CoreCLR or Mono Version: 4.2.204, mono 5.14
* Indications of severity: major
* Version of FAKE (4.X, 5.X)
* (if performance issue) Performance information, links to performance testing scripts

**Comment by matthid** [comment]
@haf can you check if this is a duplicate of https://github.com/fsharp/FAKE/issues/2099?

**Comment by matthid** [comment]
@haf have you checked? It could also be another dependency depending on one of the fake modules depending on a API which we do (historically) not consider to be binary compatible.
Or we simply introduced a breaking change somewhere

**Comment by haf** [comment]
@matthid I have not and I'm afraid I don't have it readily available to check any more. I'm closing this due to the lack to repro.
