### ISSUE TITLE
Support Additional GitVersion options

### ISSUE THREAD

**Issue by StanleyGoldman** [fsharp/FAKE#2171]
`GitVersion.exe` has a few command line options that can inject version information into `AssemblyInfo` files.

https://gitversion.readthedocs.io/en/latest/usage/command-line/#inject-version-metadata-into-the-assembly

I see how this functionality can be supported and I wouldn't mind sending in the pull request for it in the next few days. In the mean time I believe I can make do with `CreateProcess`.

**Comment by matthid** [comment]
Yes a PR is welcome.

**Comment by kmadof** [comment]
@StanleyGoldman how the work is going? Can I take this one, if you don't have time to work on this?

**Comment by StanleyGoldman** [comment]
Hi @kmadof 
I never got around to this. Please feel free.
