### ISSUE TITLE
Fake coloured text output leaves console colours changed on exit in some circumstances

### ISSUE THREAD

**Issue by SteveGilham** [fsharp/FAKE#2173]
### Description

In a Windows PowerShell console with screen text set to White, running a fake script through `dotnet fake` can exit with a display colour sticking like
![2018-10-28](https://user-images.githubusercontent.com/7460854/47619914-b4c06200-dadb-11e8-9e9d-a1036a71ddab.png)
![2018-10-28 1](https://user-images.githubusercontent.com/7460854/47619918-bb4ed980-dadb-11e8-8405-07912f2a702a.png)

Here the yellow from the warnings has persisted, but depending on the script and the state of the system being built, red, green or light grey can stick instead

### Repro steps

Please provide the steps required to reproduce the problem

1. In a Windows PowerShell console, with default colurs (white on dark blue) navigate to a local FAKE repo

2. execute `dotnet fake run .\build.fsx --target DotNetCoreUnitTests` a number of times

### Expected behavior

System colours are preserved always.

### Actual behavior

See picture above for an example. 

### Known workarounds

Save `Console.ForegroundColor` ,and, to be paranoid, `Console.BackgroundColor`, on entry to the script, and then execute a final target to set the colours to the saved values.

### Related information 

* Operating system -- WinX home
* Branch -- released versions, also current release/next
* .NET Runtime, CoreCLR or Mono Version -- .net 4.7 and various .net core
* Indications of severity  -- cosmetic
* Version of FAKE (4.X, 5.X) 5.x pre-release certainly, can't remember if seen in 4.x

**Comment by BlythMeister** [comment]
The issue here is the way fake sets and resets console colour in the listener.

It should use 
```
Console.ResetColor()
```
Rather than saving the colour and then resetting it manually

**Comment by matthid** [comment]
@BlythMeister While `ResetColor` might fix this it would be interesting to know why the current code wouldn't work. AFAIK we serialize everything to a single mailbox processor which should take care of everything?

**Comment by matthid** [comment]
Or hm, maybe we have indeed two places where we write, one in the fake-runtime and one in `Fake.Core.Trace`

**Comment by matthid** [comment]
Related: https://github.com/fsharp/FAKE/issues/1858 https://github.com/haf/expecto/issues/249
Please re-open (or open a new issue) if you encounter this with a runner > 5.14 (which will be released soon)
