### ISSUE TITLE
FAKE CLIs restore step fails on some machines, but .paket/paket.exe restore works

### ISSUE THREAD

**Issue by atlemann** [fsharp/FAKE#2182]
### Description

I have some Windows Server 2008 TeamCity build agents which fail when building using FAKE CLI. The NuGet restore process fails with a bunch of exceptions, however doing a `.paket/paket.exe restore` works fine.

### Repro steps

I'm not sure, it works on my workstation and linux build agents, but none of my Windows build agents.

### Expected behavior

Build to pass

### Actual behavior

Build fails. See attached build log:
[build.log](https://github.com/fsharp/FAKE/files/2538681/build.log)

### Known workarounds

1. First run `.paket/paket.exe restore`
2. then run `build.cmd`

### Related information 

* Operating system
Windows Server 2008
* .NET Runtime, CoreCLR or Mono Version
CoreCLR
* Indications of severity
Blocking
* Version of FAKE (4.X, 5.X)
FAKE 5

**Comment by matthid** [comment]
Have you checked if this is a duplicate of #2097?
In particular [this comment](https://github.com/fsharp/FAKE/issues/2097#issuecomment-423653243)

**Comment by atlemann** [comment]
Adding `<DotnetCliToolTargetFramework>netcoreapp2.0</DotnetCliToolTargetFramework>` fixes this issue. Now my `build.proj` file looks like this:

```xml
<Project>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DotnetCliToolTargetFramework>netcoreapp2.0</DotnetCliToolTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-fake" Version="5.*" />
  </ItemGroup>

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <RepoRootDir>$([System.IO.Path]::GetFullPath("$(MSBuildThisFileDirectory)"))</RepoRootDir>
    <BuildDependsOn></BuildDependsOn>
    <CoreBuildDependsOn></CoreBuildDependsOn>
    <FakeParallel Condition="'$(Parallel)' == 'true'">--parallel 3</FakeParallel>
    <FakeTargetArg Condition="'$(FakeTarget)' != ''">target $(FakeTarget)</FakeTargetArg>
  </PropertyGroup>

  <Target Name="Build">
    <Exec IgnoreStandardErrorWarningFormat="true" Command='dotnet fake build $(FakeParallel) $(FakeTargetArg)' WorkingDirectory="$(RepoRootDir)" />
  </Target>

  <Target Name="Pack">
  </Target>

  <Target Name="Test">
  </Target>

  <Target Name="VSTest" DependsOnTargets="Test" />
</Project>
```
