### ISSUE TITLE
Paket.push looks for "paket.exe" even on linux

### ISSUE THREAD

**Issue by atlemann** [fsharp/FAKE#2186]
### Description

Using the `Paket.push` target invokes `paket.exe` using mono even if the solution is bootstrapped with netcore Paket. It looks for `paket.exe` in `.paket` folder, but that binary on linux is called `paket`.

See: https://github.com/fsharp/FAKE/blob/3827f95ad533978ec14c29db92658f48b0609e05/src/app/Fake.DotNet.Paket/Paket.fs#L67

### Repro steps

Bootstrap netcore Paket and run the Paket.push target. It finds the `paket.exe` inside `.paket/.store` folder.

### Expected behavior

netcore `.paket/paket` binary to be invoked

### Actual behavior

Paket.exe invoked using mono:

`/usr/bin/mono" --debug /opt/teamcity-agent/work/d21010bbf5ce97d0/.paket/.store/paket/5.184.0/paket/5.184.0/tools/paket.exe push`

### Known workarounds

None

### Related information 

* Operating system
Ubuntu

* Version of FAKE (4.X, 5.X)
FAKE 5

**Comment by forki** [comment]
would love to get PR

Am Mo., 5. Nov. 2018 um 09:35 Uhr schrieb Atle Rudshaug <
notifications@github.com>:

**Comment by atlemann** [comment]
I could give it a try

**Comment by atlemann** [comment]
Does FAKE5 have a wrapper for [dotnet nuget pack](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push?tabs=netcore20)? I can't seem to find it, so I'm just wondering if I suck at searching source code. It seems like `Fake.DotNet.Nuget` is using `nuget.exe`.

**Comment by matthid** [comment]
@atlemann No it does not. I guess a bit of refactoring is needed as I'd assume it has the same arguments as `nuget.exe pack`...

**Comment by atlemann** [comment]
Ops, I meant `dotnet nuget push` above which it links to. You already have `dotnet pack`.

**Comment by matthid** [comment]
yes my answer still holds ;)
