### ISSUE TITLE
Issue during FAKE build

### ISSUE THREAD

**Issue by DigitalFlow** [fsharp/FAKE#2190]
### Description
As discussed, this is an issue for errors during FAKE build. To me it sounds however, as if msbuild might be the root cause in here.
When building the FAKE project using `fake build`, some errors occur in the output:

```
C:\Program Files\dotnet\sdk\2.1.402\Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: Die Verweisassemblys für Framework ".NETFramework,Version=v4.6" wurden nicht gefunden. Installieren Sie zum Beheben dieses Problems das SDK oder das Paket zur Festlegung von Zielversionen für die vorliegende Frameworkversion, oder legen Sie als neues Ziel für die Anwendung eine Version des Frameworks fest, für die Sie das SDK oder Paket zur Festlegung der Zielversionen installiert haben. Assemblys werden im globalen Assemblycache (GAC) aufgelöst und anstelle von Verweisassemblys verwendet. Daher wird die Assembly für das gewünschte Framework unter Umständen nicht ordnungsgemäß als Ziel festgelegt. [C:\Users\kroflo\Entwicklung\FAKE\src\app\Fake.DotNet.Testing.XUnit2\Fake.DotNet.Testing.XUnit2.fsproj]
```

The full output can be found [here](https://pastebin.com/8i6QGAVf).

I have all targeting Frameworks for .NET installed using Visual Studio Installer:
![image](https://user-images.githubusercontent.com/4287938/48068244-9bea3780-e1d2-11e8-855c-62aad7ce9818.png)

### Repro steps
Seems system specific. DotNet is installed, as well as fake using chocolatey. When running fake build, issues occur. All .NET target packs are installed.

### Expected behavior
Build should succeed

### Actual behavior
Build fails

### Related information 

* Operating system: Windows 10
* Branch Master
* .NET Runtime, CoreCLR or Mono Version
* Version of FAKE (4.X, 5.X) v5.9.3

**Comment by matthid** [comment]
> error MSB3644: Die Verweisassemblys für Framework ".NETFramework,Version=v4.6" wurden nicht gefunden

Afaik this shouldn't happen as we use 

https://github.com/fsharp/FAKE/blob/4eadc22f7ff7e46a31f7a03ad4da7c0ca0a6348f/paket.dependencies#L103

**Comment by matthid** [comment]
Combined with https://github.com/fsharp/FAKE/blob/release/next/src/Directory.Build.props

**Comment by matthid** [comment]
Can you make sure the `packages/build/RoslynTools.ReferenceAssemblies` folder exists?

**Comment by DigitalFlow** [comment]
@matthid: I checked the folder, it existed but was empty.
I never touched the packages folder, so it seems some restore must have gone wrong.

I ran `paket.exe restore` again and the Roslyn package was initiated correctly.
Thanks a lot!
