### ISSUE TITLE
[Website] anchor link titles are hidden under stick top nav

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#2201]
### Description

When you navigate to a link with an anchor (for example https://fake.build/fake-gettingstarted.html#One-note-on-Intellisense), the section header is (partially) hidden under the sticky top nav bar.

### Repro steps

Please provide the steps required to reproduce the problem

1. Navigate to the URL above

2. Observe the section header isn't visible once the page loads.

### Expected behavior

![image](https://user-images.githubusercontent.com/573979/48575748-6206e880-e8d8-11e8-9c3a-644a3ad300cc.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/573979/48575738-574c5380-e8d8-11e8-9d91-13b01e239431.png)

### Known workarounds

a) scroll a bit down
b) apply a top-padding of ~50px (or the exact height of the nav bar) to all anchors? This seems to work for me in simple testing.

**Comment by baronfel** [comment]
I added a page-level style of `.anchor { padding-top: 50px; }` and all links in the side table of contents started working correctly.

**Comment by matthid** [comment]
@baronfel Can you please send a PR for this?
