### ISSUE TITLE
Visual Studio 2017 v 15.9.1 breaks the tool path auto-detection in the FxCop task

### ISSUE THREAD

**Issue by SteveGilham** [fsharp/FAKE#2204]
### Description

Having installed the update from 15.8.x last thing yesterday, I try a build of one of my projects this morning and get an empty string for the installation path from the detection code
```
            let instance =
                BlackFox.VsWhere.VsInstances.getWithPackage
                    "Microsoft.VisualStudio.Component.Static.Analysis.Tools" false
                |> List.tryHead
            match instance with
            | Some vs -> vs.InstallationPath
            | None -> String.Empty
```
even though the FxCop tool is still present

### Repro steps

See above

### Expected behavior

The build works like it did yesterday with v15.8

### Actual behavior

Build failure with
```
 (Start of process 'Team Tools/Static Analysis Tools/FxCop/FxCopCmd.exe' failed.)
```

### Known workarounds

Use another and less-specific means of deriving the Visual Studio install location to override the default from the script.  Possibly another VsWhere invocation will do -- I'm not sure at which point in the chain the VS upgrade has affected things -- but the one I'd previously rolled for myself does work in this circumstance --
```
  let installPath () =
            use hklmKey =
                Microsoft.Win32.RegistryKey.OpenBaseKey
                    (Microsoft.Win32.RegistryHive.LocalMachine, Microsoft.Win32.RegistryView.Registry32)
            use key = hklmKey.OpenSubKey(@"SOFTWARE\Microsoft\VisualStudio\SxS\VS7")
            key.GetValue("15.0", String.Empty) :?> string
 
  let toolPath = installPath() @@ "Team Tools/Static Analysis Tools/FxCop/FxCopCmd.exe"
```
and override the default ToolPath

### Related information 

* Operating system -- WinX home
* Branch -- released 5.10.1
* .NET Runtime, CoreCLR or Mono Version -- net core 2.1.402
* Indications of severity -- moderate

**Comment by SteveGilham** [comment]
Having done yet another reboot, the problem is cleared. _Mea culpa_.

**Comment by vbfox** [comment]
I took the more "safe" way of considering only full installs without error, but we could change that so that they are taken into account last instead, In some cases it will break but most of the time the error will be in a component we don't actually use.

**Comment by vbfox** [comment]
Especially in cases where we target a package we could check that the package isn't in error (Even if it's not 100% guaranteed as some have hidden dependencies, we can call a fully installed MSBuild and depend on some targets file provided by a not fully installed other package)
