### ISSUE TITLE
Fake.Azure.WebJobs.deployWebJobs not working when remote folders not exist

### ISSUE THREAD

**Issue by brase** [fsharp/FAKE#2216]
### Description

I tried to use `Fake.Azure.WebJobs.deployWebJobs` to a new deployment slot for my azure website. In this new slot the directoy structure for the webjobs does not exist, yet. This seems to be the reason why the deployment does not work. Fake says "success" but when I look into the logs of Kudu I see 404s for the jobs.

### Repro steps

Create a new Deployment Slot in an azure website and try to deploy a webjob.

### Expected behavior

After upload the job should be listed in the portal. (The needed directory structure should be created)

### Actual behavior

The job is missing and there are 404s for the paths where it did a PUT to upload the zips.

### Known workarounds

My workaround is to manually create the directory structure. Then the jobs are deployed correctly.

**Comment by isaacabraham** [comment]
Urgh. I need to refresh my memory on what this does - to be honest there are probably better ways now with zipdeploy and stuff anwyay.

**Comment by matthid** [comment]
@isaacabraham So we remove the module? Mark it obsolete? Change docs?

**Comment by isaacabraham** [comment]
Let me check through the code - I can't remember what it does. There are a few ways to deploy to webjobs in Fake.

**Comment by isaacabraham** [comment]
Haven't looked at the code yet - I thought this was the older version that used the github-based deployment and copied stuff around with kudu directly, but now that I've actually read the original description properly, you've made it clear it's using zip deploy.

So this sounds like an issue around behaviour with deployment slots - all the Fake zipdeploy code does IIRC is do a PUT into the rest API that kudu exposes. Evidently there's something different with secondary deployment slots and zipdeploy, but I don't know what that is.

**Comment by isaacabraham** [comment]
@brase hmmm, that's possible! If I'm honest it's been a while since i deployed a webjob into app service - normally I host them in the app itself using attributes (you have the `[<Timer>]` attribute as well as the normal triggers).

**Comment by TWith2Sugars** [comment]
I hit this issue all the time (I was the one that originally made the fake module). I just upload an empty webjob via the portal to make sure the directory structure is all in place and then all other deployments via fake.

**Comment by matthid** [comment]
Can someone send a PR for this? Otherwise, I feel like we should see this thing as unmaintained and maybe move out of the core?

**Comment by brase** [comment]
I will try to fix it with including the folder structure into the zip file. PR will follow.

**Comment by matthid** [comment]
So should we close this and/or move this module into a separate repository?

**Comment by brase** [comment]
Okay, plz close it.

What are people using to deploy to azure app services with fake today? Maybe this method is outdated and not needed anymore?

**Comment by isaacabraham** [comment]
I think it's outdated. The easiest way is either [zip deploy](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip) or the (even newer) [deploy as package](https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package).

It should be possible to write a nice Fake module around both of them easily enough but ultimately they are usually just HTTP PUTs.
