### ISSUE TITLE
Does the template bootstrapping method create a reproducible build?

### ISSUE THREAD

**Issue by theprash** [fsharp/FAKE#2223]
The `fake.cmd` file created by the template runs `dotnet tool install fake-cli --tool-path ./.fake`. This installs the latest FAKE locally into the `.fake` which is git ignored. The `paket.references` file contains `nuget Fake.DotNet.Cli`, `nuget Fake.IO.FileSystem` etc. which will get locked to specific versions as soon as someone starts working on the project.

Consider this scenario:

- I create an instance of the template, do `paket install` and commit `paket.lock` with FAKE 5.x.
- A couple of years later, on a new machine, I clone my project, run `paket restore` and then run `fake.cmd`.

Won't `fake.cmd` install the latest FAKE at this time as a local tool, which could be 6.x or 7.x? But the paket dependencies are locked at 5.x so the script will references 5.x FAKE DLLs. Will the build work at this point?

**Comment by matthid** [comment]
No probably not, but there is not much we can do about it. If you use wildcards like `5.*` nuget will choose lowers (5.0.0-rc something) which is not really what we want.

So feel free to suggest something but I'm not sure what we can do here.

**Comment by kblohm** [comment]
The default template does not lock the version. If you want to, you can always just specify the version by passing `--version 5.x.x` to `dotnet new fake`, or if you already ran the command, add the `--version 5.x.x` into your `fake.cmd`.

This might get easier with .NET Core 3 and local tools.

**Comment by matthid** [comment]
As long as there is no concrete way or suggestion on how we can close this issue/suggestion I'm closing it ;)
Please feel free to open suggestions or concrete changes we could make to discuss them, then I can re-open this. Also @kblohm described a workflow without the issue.
