### ISSUE TITLE
Feature request: describing the targets

### ISSUE THREAD

**Issue by et1975** [fsharp/FAKE#2225]
### Description

Most other build tools (make, rake, gradle, etc) have a way to describe targets available in the script. Would be nice to have it here too.

### Expected behavior

If the script has any targets defined one could list them with something like:

`fake -d`

and it would list them all and (maybe, not sure if it's a good idea) show the dependencies graph.

**Comment by matthid** [comment]
something like 'fake build --list'?

**Comment by et1975** [comment]
Is that a thing already? Sorry, didn't see it in the `-h`, feel free to close if it already works.

**Comment by matthid** [comment]
Yes it should
