### ISSUE TITLE
ChangeWatcher doesn't trigger onchange when one directory name include the other

### ISSUE THREAD

**Issue by humhei** [fsharp/FAKE#2230]
### Description

ChangeWatch doesn't trigger onchange when one directroy name include the other
### Repro steps

Please run `fake build` to see repro steps https://gist.github.com/humhei/1c8a8489de9e0ade52f6509e0d898f66
```fsharp
open Fake.Core
open Fake.IO
open Fake.IO.Globbing

let file1 = Path.getFullName "TestLib/Test.fs"
let file2 = Path.getFullName "TestLib2/Test.fs"
let pattern =
    let files = [file1;file2]
    { BaseDirectory = Path.getFullName "./"
      Includes = files
      Excludes = [] }

ChangeWatcher.run (fun changes ->
    changes |> Seq.iter (fun change -> printfn "file %s changed" change.FullPath)
) pattern


```

### Expected behavior
```fsharp
File.append file1 ["\n"] //this will trigger onchange
File.append file2 ["\n"] //this will trigger onchange
```
### Actual behavior
```fsharp
File.append file1 ["\n"] //this will trigger onchange
File.append file2 ["\n"] //this will not trigger onchange
```

### Known workarounds
Carfully naming directorys 
Or
change https://github.com/fsharp/FAKE/blob/master/src/app/Fake.IO.FileSystem/GlobbingFileSystem.fs#L147
 ```fsharp
|> Seq.exists (fun p -> d.StartsWith p && p <> d)
 ```
    to 
```fsharp
|> Seq.exists (fun p -> d.StartsWith (p + "\\") && p <> d)
```

### Related information 

* win10
* FAKE 5.11.1

**Comment by matthid** [comment]
Thanks for the detailed report! Since you have already suggested a fix, are you interested in sending a PR and include a testcase for this? Let me know if you need help.
