### ISSUE TITLE
Can't #r a .net standard 2 dll

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#2231]
I have a .NET Standard 2.0 Assembly.

When I reference it with 

```f#
#r "./CreateProcessAsUser.dll"
```

then it works in VS and seems to also compile, but execution fails with 

![grafik](https://user-images.githubusercontent.com/4236651/50694336-e6086180-1039-11e9-86b4-85e352e85ea5.png)

Repro: https://github.com/0x53A/fake-2231

just run ``run.bat``

__Version:__ ``<DotNetCliToolReference Include="dotnet-fake" Version="5.11.1" />``

**Comment by matthid** [comment]
Indeed, sadly that is currently not a supported scenario, see https://github.com/fsharp/FAKE/issues/1888

**Comment by 0x53A** [comment]
So that means it is impossible to reference any local dll, I can only use nuget packages?
