### ISSUE TITLE
Why does FAKE depend on the Roslyn reference assemblies?

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/FAKE#2238]
The package [RoslynTools.ReferenceAssemblies](https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.ReferenceAssemblies) is so big (117 MB) that made me questioning its purpose.

Why depend on a package which is not even in the nuget.org gallery in the first place?

**Comment by matthid** [comment]
It allows building for full-framework as it includes the reference assemblies. This removes the need for what microsoft calls the "targeting packs" (which imho are a huge mess as users need to install them and it's not clear what to install on mono)

**Comment by matthid** [comment]
I should add: If you have another idea or this works now without this package feel free to send a PR :)

**Comment by teo-tsirpanis** [comment]
My problem was that this package could not be downloaded; even on an Ethernet connection. I guess I have to increase the Paket's timeout value.

**Comment by katatunix** [comment]
I have the same issue with @teo-tsirpanis 
Has this issue been fixed?

**Comment by matthid** [comment]
I'm not sure there is an issue here? Either you have problems/limitations in your infrastructure or it is an issue with myget which you should report to them and link back here. Or it is an issue with paket then you should report there.
As clarified above we currently have a need for this package and afaik it is not available on NuGet Gallery.

@katatunix can you clarify what your exact issue is? Can you try to download it manually and putting it into the NuGet cache? Can you report it to the correct so it can be solved? :)

**Comment by katatunix** [comment]
The approach of manually downloading works. Thanks!

**Comment by matthid** [comment]
@katatunix Please report anyway with the exact error you got to https://github.com/fsprojects/Paket
It would be nice if this could 'just work' for anyone.
