### ISSUE TITLE
Paket.Push does not work with dotnet tool.

### ISSUE THREAD

**Issue by nojaf** [fsharp/FAKE#2242]
### Description

Paket.Push does not working when Paket is installed as dotnet tool.

### Repro steps

Please provide the steps required to reproduce the problem

1. Install paket
> dotnet tool install --tool-path ".paket" Paket --add-source https://api.nuget.org/v3/index.json

2. Push nupkg

`Paket.push (fun p -> { p with WorkingDir = "bin" }))`

### Expected behavior

Same as if paket.exe full framework

### Actual behavior

```
"C:\projects\fantomas\.paket\.store\paket" push  --url  https://www.myget.org/F/fantomas/api/v2/package --api-key  6f14488e-843b-4454-8b7d-e832e471c1be "C:\projects\fantomas\bin\fantomas-tool.2.9.1-latest.nupkg" (In: false, Out: false, Err: false)
```

```
 Start of process 'C:\projects\fantomas\.paket\.store\paket' failed.
-> Win32Exception: Access is denie
```

### Known workarounds

```
let pushPackage additionalArguments =
    let paketFile = Path.Combine(".", ".paket", (if Environment.isWindows then "paket.exe" else "paket"))
    IO.Directory.EnumerateFiles("bin", "*.nupkg", SearchOption.TopDirectoryOnly)
    |> Seq.iter (fun nupkg ->
        let args =
            [ yield "push";
              yield! additionalArguments
              yield nupkg ]
        
        CreateProcess.fromRawCommand paketFile args
        |> Proc.run
        |> ignore
    )
```

### Related information 

* Operating system Widows
* .NET CoreCLR 2.1.503
* Version of FAKE:
- Fake.DotNet.Paket (5.12)

**Comment by inosik** [comment]
It works if you set the `ToolPath` property on the parameters:

``` fsharp
Paket.push (fun p ->
    { p with
        ToolPath = ".paket/paket.exe"
        WorkingDir = "bin" })
```

The `findPaketExecutable` function in the `Paket` module should be fixed:

https://github.com/fsharp/FAKE/blob/e1ce84d0e8e6710475989b830e88ce1ffcf7059a/src/app/Fake.DotNet.Paket/Paket.fs#L35-L40

FAKE tries to "start" the directory.

**Comment by matthid** [comment]
Yes, a PR would be appreciated.

**Comment by matthid** [comment]
@inosik Can you please open a new issue for this? Seems to be similar but not the same issue, or is it?

**Comment by inosik** [comment]
It's the same issue as reported by @nojaf: FAKE looks for a file **or a directory** named `paket` and tries to start the first one it finds as a process.

``` fsharp
match Fake.IO.Globbing.Tools.tryFindToolFolderInSubPath "paket" with
| Some dir -> printfn "%A" dir
| _ -> printfn "No paket directory.")
```

The script above gives this output:

``` text
"C:\my-project\paket-files\github.com\upstream-org\upstream-repo\.git\refs\tags"
```

The `Paket` module [turns that into `[...]\refs\tags\paket`](https://github.com/fsharp/FAKE/blob/e1ce84d0e8e6710475989b830e88ce1ffcf7059a/src/app/Fake.DotNet.Paket/Paket.fs#L38), _which is still a directory_. It's created by Paket when it tags the checked out commit of a Git dependency with the tag `paket/lock`.

I think we shouldn't try to be overly clever here and just look for `.paket/paket.exe` on Windows and for `.paket/paket` or `.paket/paket.exe` on Unix. What do you think?

**Comment by matthid** [comment]
@inosik Interesting case: FAKE searches for files and git saves those tag-refs as files as well :)
Not sure how to filter those out.

**Comment by atlemann** [comment]
Guess #2186 is related. I started using `dotnet nuget push` instead, so I didn't catch this on a windows machine.

**Comment by atlemann** [comment]
I started out with checking the platform first, but changed it later...

https://github.com/fsharp/FAKE/pull/2191/commits/30cc73e3b1d4f8855655adf191f6cee1f3326025

Could maybe change `tryFindToolFolderInSubPath` to get the first file that matches instead.

```fsharp
let tryFindToolFolderInSubPath toolname =
    !! ("./**/" @@ toolname)
    |> Seq.tryFind File.Exists
    |> Option.map Path.GetDirectoryName
```

**Comment by inosik** [comment]
@atlemann Yes, changing `tryFindToolFolderInSubPath` to actually look for _files_ seems like a good idea.

But I'd still simplify `findPaketExecutable` to only look in `.paket/`.

**Comment by atlemann** [comment]
We also need to support Paket installed as a global tool. Not sure exactly how to do that.

**Comment by inosik** [comment]
Simply fall back to `paket.exe`/`paket` if `.paket/paket` doesn't exist? The Paket binary has to be in `PATH` in this case. That's how `Paket.Restore.targets` works.

**Comment by matthid** [comment]
Should be fixed with the next release
