### ISSUE TITLE
FileStatus.getAllFiles incorrect documentation or implementation.

### ISSUE THREAD

**Issue by serjebulavsky** [fsharp/FAKE#2244]
### Description

https://github.com/fsharp/FAKE/blob/5e58b484c43da36bbe0f7e9111f6c61a951a38a7/src/app/Fake.Tools.Git/FileStatus.fs#L41

It says that this function returns all **changed** files in the current revision, but in reality it just returns git ls-files. So it is just all files in current repository. I suppose there should be an `--modified` flag or doc adjustment.

I had different ideas about this one, should i create PR with adding new function getAllChangedFiles (it will be the same command with --modified flag) and adjusting old ones comment? or should i just change the docs to "Returns all files in repository" ?

**Comment by serjebulavsky** [comment]
For some reason during fake run build.fsx i can't download RoslynTools.ReferenceAssemblies/0.1.3
![image](https://user-images.githubusercontent.com/1502886/52105852-f7d22a00-2622-11e9-8a87-1c5bd40d35ec.png)

**Comment by matthid** [comment]
You could try to download it via browser and copy/extract it to nuget cache. Or try again. From the output I'd say the package exists but something fails in the download?

Regarding the issue, yes the safe way would be to add a new function or to add a parameter (if we use regular fake parameters in this funtion, I haven't looked) and adjust documentation...

**Comment by serjebulavsky** [comment]
@matthid okay, thanks, i'll create a PR with a new function. 

Also thanks for helping with nugget. Somehow it downloads via browser but not via paket restore.
