### ISSUE TITLE
Please add clearer instructions for how to use Fake on Mac OSX

### ISSUE THREAD

**Issue by kristianmandrup** [fsharp/FAKE#2247]
### Description

Trying to use FAKE on a Mac OSX with VS Code. Total newbie with .NET and F# 

Installed `fake-cli` via `dotnet tool install fake-cli -g`

The `Readme` states that I can install `fake` using `chocolatey` (Windows only).

Wasn't sure what to do from there. Red scribbles in my project under `Fake` identifiers etc.
Not sure if I needed to install `fake` or if fake was already installed as part of cli??

Note: `$ fake --version` to check if installed and what version is installed (I had issue with fish shell from within VSC not picking up my `$PATH` or sth)

Wasn't sure how to make the Fake project download dependencies (ie. restore/build)

Luckily I had a video on `End2End WebApp with F# and Fable` where he showed next steps...

1. Set `storage:none` in `paket.dependencies` if not already set

From Terminal, in root of fake project:

```bash
$ fake build
Starting full restore process.
Downloading System.Reactive.Core 4.1 (Build)
Downloading Fake.Core.CommandLineParsing 5.5 (Build)
```

## Environment

* Mac OSX (latest)
* .NET Runtime: Core 2.2
* CoreCLR ??
* Mono Version: Latest for Mac
* Version of FAKE: 5.X

**Comment by matthid** [comment]
@kristianmandrup Thanks for your suggestion. Actually I'm not sure there is anything specific with Mac OSX here.

- That fake is not available in `$PATH` is a bug in the dotnet sdk under any unix and AFAIK they are aware of it (or decided to not fix that). Yes we could indeed add a note or link the SDK issue

- > Wasn't sure how to make the Fake project download dependencies (ie. restore/build)
  
  Yes we might need to improve the wording in https://fake.build/fake-gettingstarted.html#One-note-on-Intellisense to explicitly mention `fake build`?

- > Set storage:none in paket.dependencies if not already set

  This is not strictly required but recommended to save hard-drive space

Can you tell me if you read https://fake.build/fake-gettingstarted.html#One-note-on-Intellisense
 or https://fake.build/fake-dotnetcore.html#One-note-on-Intellisense maybe we need to delete one of the two pages and consolidate them better.

**Comment by kristianmandrup** [comment]
Upgraded to fish shell, getting unknown command `fake` after a fresh `fake-cli` install

```bash
[I] ⋊> ~ dotnet tool install fake-cli -g
Tool 'fake-cli' is already installed.
[I] ⋊> ~ fake                                         
fish: Unknown command 'fake'
```

**Comment by matthid** [comment]
@kristianmandrup maybe similar to this: https://github.com/fsharp/FAKE/issues/2091 (not using fish shell on my own)

**Comment by matthid** [comment]
To provide an alternative I'd be happy to have people distribute fake on the native package managers and automate stuff into the release process of this repository (if possible/viable/reasonable). However, we need some voluntaries willing to do the work as I'm not ready to fight every package manager out there ;)

For example we already build a `.dep` file (https://github.com/fsharp/FAKE/releases) but it is currently not pushed anywhere and installing is basically a manual download.

**Comment by kristianmandrup** [comment]
Cool :) I'll happily work on improving the docs (PRs) and making a homebrew script and/or node.js package for easy install on Mac ;)

**Comment by kristianmandrup** [comment]
I guess by default fake is installed in `$USER_HOME/.dotnet/tools/fake`? 
At least that is the case on my OSX

**Comment by matthid** [comment]
I think that is true because of dotnet sdk defaults. For a native package I'd expect it to be installed to a default path for application, somewhere in `/usr`?.
Users home directory only makes sense if the package manager supports something like single-user installations. Hope this makes sense.

**Comment by matthid** [comment]
> So to add extra docs for getting setup and started on Mac OSX, I would contribute in /next/help/markdown@release ?

Indeed, best is to update the markdown files in the help directory. We can have basic documentation to get started in the `Readme.markdown` but I'd prefer to keep it minimal and like to the corresponding `fake.build` pages in order to reduce duplicated or different docs

**Comment by kristianmandrup** [comment]
I made a PR with some install docs, feel free to edit or move around as you like.
