### ISSUE TITLE
findGitDir throws NullReferenceException if no .git directory found

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#2249]
### Description

The `Fake.Tools.Git.CommandHelper.findGitDir` function, if run outside a Git repo, will eventually climb up to the root of the filesystem, then throw a `NullReferenceException` when it tries to access `dirInfo.Parent` of the root folder.

### Repro steps

Please provide the steps required to reproduce the problem

1. Create `$HOME/projects/newFolder` and do *not* initialize a Git repo in `newFolder`.
1. Run the following FAKE build script in `newFolder`:

```fsharp
#r "paket:
nuget Fake.Tools.Git
nuget Fake.Core.Target //"

#load "./.fake/build.fsx/intellisense.fsx"

open Fake.Core

Target.create "Default" (fun _ ->
    Trace.trace "Hello world from build.fsx"
    let gitDir = Fake.Tools.Git.CommandHelper.findGitDir __SOURCE_DIRECTORY__
    Trace.tracefn "Found Git dir in %s" gitDir.FullName
)

Target.runOrDefault "Default"
```

### Expected behavior

`findGitDir` would return an option, or if a non-breaking change is desired, would return a `DirectoryInfo` corresponding to the root of the filesystem (which would be less than ideal, but would at least be better than throwing a `NullReferenceError`).

### Actual behavior

`findGitDir` throws a `NullReferenceError`, and it was hard to track down where it was coming from.

### Known workarounds

Wrap calls to `findGitDir` in a `try ... with` expression to catch `NullReferenceError`. Or run `git init` in the project folder, of course. :-)

### Related information 

* Operating system: Linux Mint 18 (based on Ubuntu 16.04)
* .NET Runtime, CoreCLR or Mono Version: dotnet 2.2, with FAKE installed by `dotnet tool install fake-cli -g`
* Version of FAKE (4.X, 5.X): 5.12.0, with Paket.Core 5.193.0

**Comment by matthid** [comment]
Nice find, can you come up with an PR + test?
