### ISSUE TITLE
Use Microsoft.SqlServer.DACFx nuget instead of sqlpackage.exe

### ISSUE THREAD

**Issue by panesofglass** [fsharp/FAKE#2251]
### Description

This is a suggestion to use the new [Microsoft.SqlServer.DACFx](https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/) NuGet package to drive Fake.Sql.DacPac rather than relying on `sqlpackage.exe`. Would this be of interest? I am not familiar with these libraries but am interested in looking into this if it can alleviate some xplat pain with DacPac.

Note also that Microsoft is now providing previews of [`sqlpackage`](https://docs.microsoft.com/en-us/sql/tools/sqlpackage-download?view=sql-server-2017) that can run on linux and macOS.

cc @isaacabraham

**Comment by matthid** [comment]
Honestly I'm not even sure what that means. Does that mean update `Fake.Sql.DacPac` to no longer require existing `sqlpackage.exe` and make it work xplat? That sounds more than reasonable. What speaks against that?

**Comment by panesofglass** [comment]
@matthid, yes, that's my understanding.

**Comment by panesofglass** [comment]
I'm probably about to investigate this more closely and may send a PR to show how this might work.
