### ISSUE TITLE
Fake GUI

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#2256]
Recently, I thought about adding a graphical user interface for using fake.

First it would be integrated into the targets package and provide an http(s) endpoint which is accessed by an fable application. The initial features would be showing the existing targets maybe as graph including dependencies and running them (either single or with dependencies).
In the future I can think about helping new users to write scripts by creating targets or suggesting "code" for commonly used stuff. In the end it would always be more a "learning" tool then a full fledged editor.

I'd like to know what others think about this idea in general?

**Comment by humhei** [comment]
I am doing similiar things in [FPublisher](https://github.com/humhei/FPublisher)
Using role based, typed common building targets  
But i think the best GUI is script itself?
![image](https://user-images.githubusercontent.com/25994449/52893336-31d02e00-31d6-11e9-808c-6a705a609cf3.png)

**Comment by matthid** [comment]
> But i think the best GUI is script itself?

Maybe, at least this didn't seem to generate a lot of interest :)
