### ISSUE TITLE
Error while setting up Environment (Invalid Parameter 'netcoreapp2.2')

### ISSUE THREAD

**Issue by TclasenITVT** [fsharp/FAKE#2269]
### Description

After adding 'Framework: netcoreapp2.2, netstandard2.0' to my paket.depencies and running 'paket update' fake build outputs this Message: 
> runOrBuild ({Script = None;
>  ScriptArguments = [];
>  FsiArgLine = [];
>  Debug = false;
>  NoCache = false;
>  RestoreOnlyGroup = false;
>  VerboseLevel = Verbose;
>  IsBuild = true;})
> FAKE 5 - F# Make (5.4.1)
> prepareAndRunScriptRedirect(Script: C:\Users\tclasen\source\repos\ITVT.SW365.PKS\ITVT.SW365.PKS\build.fsx, fsiOptions: "")
> Writing 'C:\Users\tclasen\source\repos\ITVT.SW365.PKS\ITVT.SW365.PKS\.fake\build.fsx\intellisense.fsx'
> Restoring with paket...
> The last restore is still up to date. Nothing left to do.
> Performance:
>  - Cli parsing: 608 milliseconds
>  - Packages: 212 milliseconds
>  - Runtime: 2 seconds
> There was a problem while setting up the environment, see standard error for details.
> There was a problem while setting up the environment:
> -> Error during parsing of 'C:\Users\tclasen\source\repos\ITVT.SW365.PKS\ITVT.SW365.PKS\paket.lock'.
>    StackTrace:
>         at Paket.LockFile.Parse(String lockFileName, String[] lines)
>         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>         at System.Lazy`1.CreateValue()
>         at Fake.Runtime.FakeRuntime.retrieveInfosUncached@264(String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, Lazy`1 lockFile, Lazy`1 cache, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 265
>         at Fake.Runtime.FakeRuntime.getKnownAssemblies@418(FakeConfig config, String cacheDir, Lazy`1 paketDependenciesFile, VerboseLevel logLevel, GroupName groupName, FrameworkIdentifier framework, FileInfo lockFilePath, String assemblyCacheHashFile, String assemblyCacheFile, Lazy`1 lockFile, Lazy`1 cache, Lazy`1 writeIntellisenseTask, Unit unitVar0) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 432
>         at Fake.Runtime.FakeRuntime.knownAssemblies@437.Invoke(Unit unitVar) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 437
>         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
>         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
>         at System.Lazy`1.CreateValue()
>         at Fake.Runtime.FakeRuntime.paketCachingProvider(FakeConfig config, String cacheDir, Dependencies paketApi, Lazy`1 paketDependenciesFile, FSharpOption`1 group) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 160
>         at Fake.Runtime.FakeRuntime.prepareFakeScript(FakeConfig config) in D:\a\1\s\src\app\Fake.Runtime\FakeRuntime.fs:line 568
>         at Program.runOrBuild(RunArguments args) in D:\a\1\s\src\app\Fake.netcore\Program.fs:line 155
> -> invalid parameter 'netcoreapp2.2' after >= or < in '== netcoreapp2.2) (== netstandard2.0)'
> Hint: If you just upgraded the fake-runner you can try to remove the .fake directory and try again.

I then tried to update the fake-cli like suggested. I updated to Version 5.12.4. This did not solve my problem. Paket does execute 'paket restore' without problems.

This is my paket.dependencies:
```
version 5.198.0
// [ FAKE GROUP ]
group Build
    storage none
    source https://api.nuget.org/v3/index.json
    nuget Fake.DotNet.Cli
    nuget Fake.IO.FileSystem
    nuget Fake.Core.Target
    nuget FSharp.Core ~> 4.5.0

group Main
    framework: netcoreapp2.2, netstandard2.0
    storage none
    source https://api.nuget.org/v3/index.json
    nuget Microsoft.NET.Sdk.Functions 1.0.26
    nuget FSharp.Core 4.2.3
	nuget Microsoft.AspNetCore == 2.2.0 strategy: min
    nuget Microsoft.NETCore.Platforms 2.2.0
    nuget Newtonsoft.Json 11.0.2
```
I am using Paket 5.198.0.

### Repro steps

Please provide the steps required to reproduce the problem

1. Run 'fake build'

### Expected behavior

The Environment is successfully set up and the project is successfully build.

### Actual behavior

The Error Message is shown.

### Known workarounds

Remove the 'framework: netcoreapp2.2, netstandard2.0' in the paket.dependencies and restore the old paket.lock file.

### Related information 

* Operating system Windows 10
* Nuget Package 
*CoreCLR (Runtime: 2.2.1; SDK 2.2.103)
* Severe as this completly disrupts our build via FAKE
* Version of FAKE (5.4.1)

**Comment by matthid** [comment]
Yes updating fake to 5.12.4 should solve the problem. Can you ensure that the runner is actually updated (for example by running `fake --version`) It might be that you still run an older version from chocolatey for example.

**Comment by TclasenITVT** [comment]
Running fake --version outputs:
```
FAKE 5 - F# Make (5.4.1)
FakePath: C:\Users\tclasen\.dotnet\tools\.store\fake-cli\5.4.1\fake-cli\5.4.1\tools\netcoreapp2.1\any\Fake.Runtime.dll
```

**Comment by matthid** [comment]
Yes this is 5.4.1 and not 5.12.X you need to update your dotnet tool

**Comment by TclasenITVT** [comment]
After updating and removing the .fake folder it does work 👍
While building I noticed that running it with 'fake build' outputs:

> Trying to resolve: Fake.Core.FakeVar, Version=5.12.4.0, Culture=neutral, PublicKeyToken=null
> Global resolve event: Fake.Core.FakeVar, Version=5.12.4.0, Culture=neutral, PublicKeyToken=null
> Could not find assembly in the default load-context: Fake.Core.FakeVar, Version=5.12.4.0, Culture=neutral, PublicKeyToken=null
> Redirect assembly load to known assembly: Fake.Core.FakeVar, Version=5.12.4.0, Culture=neutral, PublicKeyToken=null (Some
>   "C:\Users\tclasen\.nuget\packages\fake.core.fakevar\5.12.4\lib\netstandard2.0\Fake.Core.FakeVar.dll")
> Redirect assembly load to previously loaded assembly: netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
> Redirect assembly from 'FSharp.Core, Version=4.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' to previous loaded assembly 'FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

while building with .\fake.cmd build does not do you know why that is?

**Comment by matthid** [comment]
@TclasenITVT Usually this is output from the verbose mode `-v` usually this isn't recommended or required for users of FAKE. But sometimes, if the issue is not immediately obvious, I tell people to use it. I'd assume `fake.cmd` contains the `-v` flag. Where did you got the batchfile from? Is it from our fake template?

**Comment by TclasenITVT** [comment]
You were right I hade the -v option set when running fake inside of the commandline. The Batchfile does not contain the -v flag. I got it from the dotnet fake template.
