### ISSUE TITLE
Q: How to build an assembly to `#r` in a FAKE build script 

### ISSUE THREAD

**Issue by Danl2620** [fsharp/FAKE#2273]
### Description

I'm having trouble with something that seems like it may be fairly basic. I'd like to build an assembly and reference it into a FAKE build script (using `#r`).

I'm doing that using the `Microsoft.NET.Sdk` project sdk and targeting the `netcoreapp2.1` framework. 

### Repro steps

A FAKE build script with `#r "path/to/my/Wonderstorm.Tools.Build.dll"`

### Expected behavior

FAKE runs, references the assembly, and lets me use and open the contained namespace.

### Actual behavior

I get this error
```
Script reported an error:
-> FileLoadException: Could not load file or assembly 'Wonderstorm.Tools.Build, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. General Exception (Exception from HRESULT: 0x80131500)
-> Could not load 'Wonderstorm.Tools.Build, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   This can happen for various reasons:
 [...]
```

### Known workarounds

I tried using `#load` to grab the files from the assembly directly, but that makes it difficult/impossible to set up the correct dependencies.

### Related information 

* Operating system: macOS
* Branch: 
* .NET Runtime, CoreCLR or Mono Version: 2.1
* Indications of severity: firm blocker
* Version of FAKE (4.X, 5.X): 5.X

**Comment by matthid** [comment]
Sadly this is currently not a supported scenario, see https://github.com/fsharp/FAKE/issues/1888 for details :)
So the "fix" is to build a nuget package instead. Target `netstandard2.0` and it should work. In fact you can just build it locally stick it into a folder and use `source /my/folder` afaik.

**Comment by Danl2620** [comment]
Thanks!

**Comment by Danl2620** [comment]
@matthid Ok, I currently have the exact scenario described in this comment: https://github.com/fsharp/FAKE/issues/1888#issuecomment-385061951.

Are there any more diagnostic options to see why the package namespace isn't available?

**Comment by matthid** [comment]
@Danl2620 Why is a local nuget package not an option?

**Comment by Danl2620** [comment]
@matthid sorry, that's what I meant. I did create a local nuget package, and:

1. added the "open" line to the paket string
2. referenced the package in the string (`nuget Wonderstorm.Build.Tools`), 
3. opened the relevant namespace, 
4. removed my `build.fsx.lock` file, 
5. and reran fake 

-- it restored everything including my nuget package, but the namespace isn't available.

It's possible my nuget package is incorrect in some way but I can't see how...

**Comment by matthid** [comment]
The only real requirement is that the nuger pacjage needs to contain a netstandard2.0 dll. Can you post the relevant sections or explain the steps I need to do to reproduce this ?

**Comment by matthid** [comment]
By the way we have some limited docs for this scenario here: https://fake.build/fake-fake5-custom-modules.html
But it seems to be a little too hard to find

**Comment by Danl2620** [comment]
I posted a test repo that demonstrates the issue. Here's my nuget project `.fsproj` file: https://github.com/WSStudios/fake-nuget-test/blob/master/Wonderstorm.Tools.Build/Wonderstorm.Tools.Build.fsproj

(if you sync that repo, run `publish.sh` to generated the nuget package, then try `fake run build.fsx` to see the namespace missing)

**Comment by matthid** [comment]
Can you try to change ' <TargetFramework>netcoreapp20</TargetFramework>' to 

'<TargetFramework>netstandard2.0</TargetFramework>'

If this doesn't work I can take a look but it probably will take a while

**Comment by Danl2620** [comment]
No luck with that change...

**Comment by Danl2620** [comment]
BTW, I used `netstandard2.0` as the target framework, configured my paket dependencies using groups to support 2 scenarios: building my assembly and supporting the FAKE script. The FAKE group only refers to my built assembly. There were several details to get right, but it works like a charm now!

**Comment by davedawkins** [comment]
Just wanted to say that finding this issue solved a massive headache for me last night. Was also trying to `#r` a DLL, and using NuGet package instead solved it. Thank you!
