### ISSUE TITLE
Broken link in the "Getting started" tutorial

### ISSUE THREAD

**Issue by PeterMortensen** [fsharp/FAKE#2276]
In *[Getting started](https://fake.build/fake-gettingstarted.html)* the link *"NUnit task documentation"* (https://fake.build/apidocs/v5/fake-nunitsequential.html) in sub section *"Running the tests with NUnit"* is broken (404).

**Comment by matthid** [comment]
Fixed in https://github.com/fsharp/FAKE/pull/2267/commits/94688f340d3d3fafb53699b9a0a6a461b362d750 thanks for reporting
