### ISSUE TITLE
Document  NuGet packages for FAKE 5

### ISSUE THREAD

**Issue by agross** [fsharp/FAKE#2278]
I wrote my first production FAKE script with FAKE 5 this week. I have to admit that getting there was quite a bit frustrating at times. For example if you get all red squigglies in VS Code suddenly because of IEquatable missing and you need to look for a solution in the issue tracker. This could easily be included in the getting started.

On top of that while the docs are generally good, I often needed to look at the source code (which is linked to, which is great!).

The primary reason for this post is this: The new FAKE 5 modularization docs desperately need a to include the NuGet a module's functions are available in. I found myself hunting the right package more than once using a separate browser tab querying nuget.org for e.g. `fake nunit`.

If that information is already included it is not prominent enough to find it.

**Comment by matthid** [comment]
Hm, seems like this bit of information has gone missing. At one point it was definitely there :(

**Comment by matthid** [comment]
Indeed, the information was lost when the new layout was introduced: https://github.com/fsharp/FAKE/commit/c85e4e538d6614ec7591ad263b1b056344d3b9e3#diff-cb0959739dd1ef5ffb40a6cbfbb1d2aa

**Comment by matthid** [comment]
Will be back after the next release, currently on [staging](https://staging.fake.build) 
![image](https://user-images.githubusercontent.com/1866463/54480481-12561080-4829-11e9-940f-0ee452613510.png)

**Comment by agross** [comment]
👍🏻
