### ISSUE TITLE
Migrating Dynamics CRM Helper

### ISSUE THREAD

**Issue by DigitalFlow** [fsharp/FAKE#2280]
Hey there,

As the DynamicsCRMHelper is not yet migrated to FAKE 5, I'd like to migrate it:

https://github.com/fsharp/FAKE/blob/694f616c97fa242162cfd36db905d7df3156018f/src/legacy/FakeLib/DynamicsCRMHelper.fs#L2

Can you point me in the right direction on how to do so? It seems as if it would have to become a separate NuGet Module?

Thanks for your help.

Kind Regards,
Florian

**Comment by matthid** [comment]
Indeed, note that we have a dedicated section for this situation in our contribution guideline: https://fake.build/contributing.html#Porting-Modules-to-FAKE-5
I'd recommend reading the remaining contribution guide as well.
If you have further questions or problems understanding any of the steps let me know. 
The guide is a bit outdated as intellisense support was quite limited at the time. As of today should be able to open and edit the new project files without problems (ie editing fakelib as suggested in that guide is no longer required, just add the new project to the solution and go from there)

**Comment by matthid** [comment]
I'm closing this. Please let me know if you need further guidance
