### ISSUE TITLE
FAKE Metapackages

### ISSUE THREAD

**Issue by rtkelly13** [fsharp/FAKE#2281]
### Description

A big advantage of the move to FAKE 5 was the breaking up of FAKE.Core into several smaller packages enabling a pay for play model. The downside to this is being that it becomes hard to find the projects that are needed to create even a simple FAKE script. asp.net core solved this by introducing a metapackage https://www.fuget.org/packages/Microsoft.AspNetCore.App which bundles in all the supported and makes getting started with asp.net core much easier. 

Many people will not move away from the meta package due to a larger maintenance burden, but people who desire a smaller set of dependencies can still do so due to the nature of the platform.

### Expected behavior

Using intellisense in an appropriate IDE someone should be able to pick up FAKE and gain access to all the functionality without having to update paket to get the package they need for that task.

### Actual behavior

Positive feedback loop is broken because of simple tasks like adding a package in to gain additional behaviour takes longer and might off put new starters.

### Questions

1. Should this package be a set of all the FAKE packages or a suggested subset of them?
2. What should this package be named?
3. Would this be the new default moving forward and updating existing templates?
4. Maybe Fake.exe could assist in simplifying the dependencies as Paket does?

**Comment by matthid** [comment]
Yes. Problem is: I don't have good answers for the questions.

Regarding 4. are you thinking about exposing `paket` command line via `fake.exe`?

https://github.com/fsharp/FAKE/issues/2100 is a bit related in this context.

**Comment by rtkelly13** [comment]
In regards to the questions my initial thoughts are.

1. As long as none of the packages conflict with each other everything should be present. The point wouldn't be to limit the scope to a limited subset of things.
2. Fake.All
3. For convenience sake I would say updating existing templates would be correct, if these are intended to be for quickly spinning up a Fake project.
4. My intention would be slightly different, probably a Paket change. Simplifying the actual set of packages specified as dependencies based on if the code is used or not. I was thinking how could Fake.All be eventually moved to the pay for play model with some tooling.

**Comment by matthid** [comment]
Regarding 1. Do we include 3rd Party libs like BlackFox BuildTask?
![image](https://user-images.githubusercontent.com/1866463/54783550-f59f4b80-4c21-11e9-8494-7fbb4e002fcf.png)


Regarding 4. it might not be as hard as we think. The compiler is already removing unused references therefore the following should work quite well:

a) compile the script do `script.dll` (which we do already)
b) recursively track all dependencies (the dependency tree -> list of assemblies, we already reference Mono.Cecil, which can be used for this)
c) track every assembly to it's NuGet package (we already do this basically, as we need the list of assemblies for runtime resolution)
d) simplify the list of NuGet packages based on dependencies (not that hard)
e) write a dependencies file or fake header (basically append `nuget ` in front of every package name)

**Comment by rtkelly13** [comment]
Sorry it has taken me so long to get back to you on this one.

> Regarding 1. Do we include 3rd Party libs like BlackFox BuildTask?

If a Fake lib is dependent on another project I would expect it would be present in FAKE.All package, I'd say the definition should be all packages maintained by the Fake project and its dependencies.

>Regarding 4. it might not be as hard as we think. The compiler is already removing unused references therefore the following should work quite well:

I think that would be an amazing experience for getting started with FAKE.

I'm going to give this a go see what I come up with, maybe split the tasks into two pieces the main meta package and the simplification of the dependencies

**Comment by matthid** [comment]
> If a Fake lib is dependent on another project I would expect it would be present in FAKE.All package

Note that for BlackFox BuildTask the reverse is true. But we advertise it's usage in the menu. (Similar to Xake)
