### ISSUE TITLE
MSBuild picks oldest version by default

### ISSUE THREAD

**Issue by csmager** [fsharp/FAKE#2285]
I've noticed that when I have both VS 2017 and VS 2019 installed, VS 2017 will be picked by the `MSBuild` module by default (i.e. if not coerced by environment variables like `VisualStudioVersion`).

The relevant code is below:

https://github.com/fsharp/FAKE/blob/8081382cdb2f8bd80d81e81002828a08320ea3e8/src/app/Fake.DotNet.MSBuild/MSBuild.fs#L222-L234

`MSBuildExeFromVsWhere.get()` returns a `Map<string, string list>` of version -> list of paths. Given the way `Map` is implemented, this will be sorted. For example, I get this:

```fsharp
 map [
    (15.0, [C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin]); 
    (16.0, [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin])
]
```
`fullList` will therefore always contain the oldest version first, and this is the first place `Process.tryFindFile` will look.

Is this intended? I think I'd expect it to pick the latest first. To do this I'd simply change line 230:
```fsharp
let all = dict |> Map.toList |> List.rev |> List.collect snd
```
I'd note that the next place to search after the VSWhere paths is `vsVersionPaths`, and this uses hard coded lists defined as `knownMSBuildEntries` and `oldMSBuildLocations` which *are* defined in newest-first order. This would lead me to believe this is a bug rather than by design - given VSWhere only supports VS2017 and later, this almost certainly hasn't come up before!

**Comment by matthid** [comment]
Note that using the latest version means your build potentially breaks when installing a newer version of visual studio. I'm not sure if that's what we want...

**Comment by csmager** [comment]
I guess you have to pick one. I spotted it because my build broke when I installed an older version of Visual Studio because I needed to use an add-in that wasn't yet compatible.

**Comment by BlythMeister** [comment]
Is it possible to add a way to set the msbuild version in an environment variable.
Not exact version, but like 15 or 16.

That way, if someone has issues with 16, they can easily revert back to 15.

**Comment by matthid** [comment]
That's always and already possible

**Comment by BlythMeister** [comment]
🤦🏼‍♂️ then I don't see this as an issue. 👍
