### ISSUE TITLE
GitLab CI: No such variable CI_BUILD_ID

### ISSUE THREAD

**Issue by ytyukhnin** [fsharp/FAKE#2290]
### Description

According to the official documentation there is no such variable `CI_BUILD_ID` on the list of the GitLab CI variables: https://docs.gitlab.com/ee/ci/variables/

But Fake is providing a following function 
```
namespace Fake.Core
...
module BuildServer =
...
let gitlabCIBuildNumber = if isGitlabCI then Environment.environVar "CI_BUILD_ID" else ""
```
Which as the result is always returning an empty string while running on a GitLab CI.

### Repro steps

Call a `BuildServer.gitlabCIBuildNumber` function while running at a GitLab CI runner.

### Expected behavior

The function should be instead looking for a variable `CI_PIPELINE_ID` which defines a pipeline id.

### Known workarounds

Use `Environment.environVar "CI_PIPELINE_ID"` directly.

**Comment by matthid** [comment]
Hm, I always thought I just copied from the docs. Did this stuff change? Do we need to check the old one for backwards compat or old on-premise instances?

**Comment by ytyukhnin** [comment]
Well, we started to use GitLab only few months ago, but I did some search on the Internet, and it seems they renamed CI_BUILD_ID into CI_PIPELINE_ID about a year ago. So I think it's better to keep it backwards compatible.

**Comment by ryanjaeb** [comment]
This issue ranks pretty high in Google when searching for *GitLab CI_BUILD_ID*.  I ended up skimming the [archived docs](https://docs.gitlab.com/archives/#offline-archives) and `CI_BUILD_ID` was actually renamed to `CI_JOB_ID`.  Here's what the docs used to show:

![gitlab-ci-renamed-variables](https://user-images.githubusercontent.com/5461986/63205617-60837000-c064-11e9-9e78-1844de3179cc.png)
