### ISSUE TITLE
Invalid syntax of NuGet push after 5.13.0

### ISSUE THREAD

**Issue by aklefdal** [fsharp/FAKE#2299]
### Description

NuGet push fails, due to problem with quotes around both parameter and value, I believe.

### Repro steps

```
Target.create "NugetPackAndPublish" (fun _ ->
    NuGet.NuGet.NuGet (fun p -> 
        { p with
              Project = "My.Project"
              Version = version // Version of package being sent to repository
              Authors = ["NRK"]
              Description = "My description"
              ReleaseNotes = "my release notes"
              OutputPath = artifactsDir
              WorkingDir = publishDir
              PublishUrl = publishUrl
              Publish = not BuildServer.isLocalBuild})
        (appDir @@ "publish/My.Project.nuspec"))
```

### Expected behavior

**With 5.12.6:**

This is the push command that gets executed, and works fine:

`C:\s\my-repo\.fake\build.fsx\packages\NuGet.CommandLine\tools\NuGet.exe push "C:\s\my-repo\artifacts\My.Project.1.0.0.nupkg"  -source \\myserver\Deploypackages\MyProject`

### Actual behavior

**With 5.13.0, 5.13.1 and 5.13.2:**

This is the push command that gets executed, and fails:

`C:\s\my-repo\.fake\build.fsx\packages\NuGet.CommandLine\tools\NuGet.exe push "C:\s\my-repo\artifacts\My.Project.1.0.0.nupkg" "-Source \\myserver\Deploypackages\MyProject" "-Timeout 00:05:00"`

Gives error:
`Unknown option: '-Source \\myserver\Deploypackages\MyProject'`

Both runs NuGet.CommandLine 4.9.4.

### Known workarounds

Use version 5.12.6 of Fake.Dotnet.NuGet (and, as a result, Fake.Dotnet.Cli version 5.12.6 as well)

### Related information 

* Running Windows 10
* Also fails on our TeamCity server running on some version of Windows Server.

**Comment by matthid** [comment]
PR with unit-test and fix would be appreciated ;)
This was probably introduced in https://github.com/fsharp/FAKE/pull/2229 

/cc @atlemann 

Any problems with the workaround (ie setting `5.12.6` in your dependencies?) or are we in a hurry?

**Comment by aklefdal** [comment]
I'll look into it. We are not in a hurry since 5.12.6 works perfect for us.

**Comment by matthid** [comment]
I guess I might unlist and see how that works

**Comment by atlemann** [comment]
Ops, I guess I'm using `ToWindowsCommandLine` wrong somehow:

https://github.com/atlemann/FAKE/blob/45a26d17979257197e67708be0a5d3c40007c97f/src/app/Fake.DotNet.NuGet/NuGet.fs#L402
