### ISSUE TITLE
Create nuget package from csproj file

### ISSUE THREAD

**Issue by lianzhao** [fsharp/FAKE#230]
I want to create nuget package from my csproj file, here is my script

```
Target "NugetPack"(fun _ ->
    NuGet  (fun nugetParams -> 
        {nugetParams with
          ...
    }) "MyProject/MyProject.csproj"
)
```

It fails for that MyProject.csproj is not a valid nuspec file
BTW, it works fine if I call NuGetPack instead of NuGet

**Comment by Slesa** [comment]
I would need that feature right now, too. We have dozens of nuget packages to deploy, and it would make sense to use the projects files to resolve dependencies.

**Comment by contactsamie** [comment]
Is this possible in any way at the moment to use the projects files to resolve dependencies rather than having to supply all the nugget dependencies manually (explicitly) ?

**Comment by matthid** [comment]
@contactsamie please consider opening a new issue with more details on what exactly you expect or trying to achieve as this is quite old  :)
