### ISSUE TITLE
FAKE.exe to run script text(eval) from command line with no fsx file

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fsharp/FAKE#2302]
# Expected
```
dotnet tool install fake-cli -g
fake -eval printf "Hello FSI"
```

prints
```
Hello FSI
```

# Actual

Error.

# Why?

I want to run some scripts without creating files. F# has forward pipe operator. FAKE has abstractions more like to PowerShell, which are more sane to be used in oneliners than `corefx`. I am not going to use FAKE to build, but for automation(may be will use for deploy and build later).

# Options

List of namespaces to open:
```
-open System
```

List of `Nugets`
```
-nuget Ipfs.Engine
```

Some sane auto nugets and auto opens?  Some FAKE abstraction over processes-files-http?

# Alternative 

1. Powershell 

```
pwsh -Command Write-Host "Hello PWSH"
Hello PWSH
```
I cannot go into production code and back with PWSH. I have to translate to F#.

2. I searched how to use FSI from Command line with one line install. No way. I cannot deploy FSI into PATH on Windows. Not sure if it has `eval`

3. C# has no forward pipe operator.

# Will donate for this feature

And where is donate button?

**Comment by matthid** [comment]
In fact, at the very beginning of designing FAKE 5, I thought about this particular feature.
I think it would be really nice to have. However, we should keep in mind that while we could make it "work" it would have one huge disadvantage: It would be very slow and wouldn't benefit from caching.
The main reason for this is that FCS, as well as Paket, have huge startup times.

You would expect such a feature to be reasonably fast for it to be usable, correct? Any suggestion or feedback is welcome...

**Comment by dzmitry-lahoda** [comment]
I have fastest NVMe on the market and latest lineup of high end Intel processor. I doubt it will be slow for me. At least creating file and type-cat and then delete file would be slower for me. Or opening some IDE. I imagine FCS and paket could be  `corert`ed in some future to mitigate some startup time. May be some other optimizations in future?

When I type pwsh with no arguments, I get into it's shell. So typing fake could open fake's version of FSI. May be that will be faster. Not sure about semantics and if I need that.

**Comment by matthid** [comment]
Question is if we should implement something now or wait for https://github.com/fsharp/fslang-design/blob/master/tooling/FST-1027-fsi-references.md to be implemented. Which means we would probably get `#r "nuget:"` for free (whatever that means).

**Comment by dzmitry-lahoda** [comment]
I can wait :)

**Comment by dzmitry-lahoda** [comment]
No sure, need to find proper item, but seems some work for `fsi` to have `nuget` was done already. Meantime, I have wrote several thousands powershell lines and learned it cool argument passing and error handling.
