### ISSUE TITLE
Need for assistance regarding WiX Module

### ISSUE THREAD

**Issue by mapfel** [fsharp/FAKE#2303]
### Description

Packaging files and dirs in a WiX setup needs a more detailed explanation with examples.

Intention of 

- Wix.bulkComponentCreation(...)
- Wix.bulkComponentCreationAsSubDir(...)
- Wix.bulkComponentTreeCreation(...)

is very difficult to understand without proper documentation including examples and usage scenarios.

### Current situation

I have a folder structure (including some files) which needs to get packaged and deployed to the destination machine.

The overall picture is similar to that:

```
deployPrepDir
  file 1
  file 2
  ..
  file x
  folder A
    file A1
    file A2
    ..
    file Ay
  folder B
    file B1
    file B2
    ..
    file Bz
```

How this folder structure can be bundled into one feature and get installed in that layout?

Thanks in advance,
Marko

**Comment by matthid** [comment]
Maybe @cthangn can help?

**Comment by mapfel** [comment]
Found one solution by myself:

1. run Wix.bulkComponentTreeCreation to create the component structure
2. run Wix.getComponentRefs to create the component references
3. use the component references in Wix.generateFeatureElement
4. use the component structure in Wix.fillInWiXTemplate

the sample of this:

```
let components4AdminTools =
  Wix.bulkComponentTreeCreation
    fileFilter dirFilter (DirectoryInfo wixCollectDir4AdminTools) Wix.Architecture.X86 // <-- Step 1
let componentsRefs4AdminTools = Wix.getComponentRefs components4AdminTools // <--  Step 2
...
let completeFeature = Wix.generateFeatureElement (fun f -> 
  {f with  
    Id = "NewAdminTools"
    Title = "New Admin-Tools"
    Level = 1 
    Description = "Installs the new Configurator with its Admin-Tools Plugins"
    Components = componentsRefs4AdminTools // <-- Step 3
    Display = Wix.Expand 
    NestedFeatures = [] // no nested features yet
  })
...
Wix.fillInWiXTemplate "" (fun f ->
  {f with
    // Guid which should be generated on every build
    ProductCode = System.Guid.NewGuid()
    ProductName = "Admin-Tools"
    Description = "Setup for the improved Admin tools of Steps."
    ProductLanguage = 1031 // 7=de, 1031=de-DE, 1033=en-US
    ProductVersion = "19.0.0"
    ProductPublisher = "Marko Apfel"
    // Set fixed upgrade guid, this should never change for this project!
    UpgradeGuid = (System.Guid WixProductUpgradeGuid)
    MajorUpgrade = [MajorUpgrade]
    UIRefs = [WiXUIMondo; WiXUIError]
    ProgramFilesFolder = Wix.ProgramFiles32
    Directories = [virtualDbTemplateDir] //this is another subfolder for a 2nd feature
    Components = components4AdminTools // <-- Step 4
    BuildNumber = "Build number"
    Features = [completeFeature; dbTemplateFeature] //providing two features
    WiXVariables = WixVariables
  })
```

**Comment by matthid** [comment]
Should we update this to the docs? Can someone send a PR, can we close this issue?
:)

**Comment by mapfel** [comment]
I'm not sure whether that is the best approach.
But probably it's better than nothing.

I would try to update the docs and send the PR, but earliest mid of next week.
