### ISSUE TITLE
directExec et al should use ProcessStartInfo, not ProcStartInfo

### ISSUE THREAD

**Issue by vivainio** [fsharp/FAKE#2315]
In planning a port of fake 4 code, I noted that directExec in fake 5 had type (ProcStartInfo -> ProcStartInfo) -> bool

This is an incompatible change (because ProcStartInfo is not mutable, i.e. no setters)

It should have type ProcessStartInfo -> unit instead, i.e. implementation should be pretty much this https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/Common/ProcessHelper.fs#L226-226

```fsharp
let directExec configProcessStartInfoF =
    use proc = new Process()
    proc.StartInfo.UseShellExecute <- false
    configProcessStartInfoF proc.StartInfo
    try
        start proc
    with exn -> raise (Exception(sprintf "Start of process %s failed." proc.StartInfo.FileName, exn))
    proc.WaitForExit()
    proc.ExitCode = 0
```

There are probably other "compatibility" functions with the same problem, this is just what I hit first.

**Comment by matthid** [comment]
Yes indeed, just to check: You hit this after updating the legacy fake package (ie first step of the migration)?

**Comment by vivainio** [comment]
It was the first "processhelper" problem I hit. I didn't update fake package, rather I'm trying to update manually ("dotnet new console -lang f#", copied our build.fsx to build.fs, added FAKE PackageReference's, trying to get "dotnet run" flow running).

**Comment by matthid** [comment]
Ok, I just checked that I didn't mess up anything. 
The code is still in master here: https://github.com/fsharp/FAKE/blob/release/next/src/legacy/FakeLib/ProcessHelper.fs#L261

So to clarify: 
- Updating "fakelib.dll" is safe and doesn't break you
- Removing all "obsolete" warnings should make you FAKE 5 compatible

This doesn't imply that you can use FAKE 5 modules and keep your FAKE 4 scripts untouched.

So basically all we did is give you an option to migrate the APIs and give you a reasonable migration path and time to do so. We didn't conserve existing APIs in any way.

Does this make sense? The reason for this is that we indeed made breaking changes and we did some API redesign. So even if we kept some APIs this doesn't mean they are 100% compatible.

I'd suggest you to follow the migration path and solve the warnings. Once all warnings are solved I think you can do what you are after. Or just do everything on one step if the script is not too long.

**Comment by vivainio** [comment]
I can migrate in one go. I filed this bug to maybe smooth out porting work for posteriority :).

Still, since the function is only there only for legacy compatibility in the first place, it would make sense to have a compatible api.

**Comment by matthid** [comment]
> Still, since the function is only there only for legacy compatibility in the first place,

In this particular case, I think what happened is that we reworked the process API after 5.0.0 again in a backwards compatible manner.

Anyway thanks a lot for reporting. We definitely need people reporting such things such that we can smooth out the experience. But I feel like the ship has sailed on this one (if not a lot of other people start to report this)
