### ISSUE TITLE
DotNet.exec (dotnet installer) fails when username has a blank 

### ISSUE THREAD

**Issue by SCullman** [fsharp/FAKE#2319]
### Description

I see the following error message:
```
Starting task 'DotNet:version': running dotnet --version
C:\Users\Stefan Cullmann\Documents\Projekte\Thoth.Json.Net> "C:\Program Files\dotnet\dotnet.exe" --version (In: false, Out: true, Err: true)
2.2.107
Finished (Success) 'DotNet:version' in 00:00:00.1786084
C:\Users\Stefan Cullmann\AppData\Local\Temp\> "powershell" -ExecutionPolicy Bypass -NoProfile -NoLogo -NonInteractive -Command "C:\Users\Stefan Cullmann\AppData\Local\Temp\dotnet_install_eb0a191797624dd3a48fa681d3061212.ps1 -Verbose -Channel master -Version 2.2.101 -InstallDir "C:\Users\Stefan Cullmann\AppData\Local\Microsoft\dotnet" -NoPath; if (-not $?) { exit -1 };" (In: false, Out: false, Err: false)
C:\Users\Stefan : Die Benennung "C:\Users\Stefan" wurde nicht als Name eines Cmdlet, einer Funktion, einer Skriptdatei oder eines ausführbaren 
Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In Zeile:1 Zeichen:1
+ C:\Users\Stefan Cullmann\AppData\Local\Temp\dotnet_install_eb0a191797 ...
```

Translated:
The name "C:\Users\Stefan" was not recognized as the name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if the path is correct (if included), and repeat the process.

### Repro steps

- Add a user with a blank in the name in windows.
- Login as that user
- Clone ``https://github.com/thoth-org/Thoth.Json.Net.git`` 
- Run Fake

### Expected behavior
The script should run
### Actual behavior
The error is raised
### Known workarounds
Comment out these lines 140 -142
```
let result = DotNet.exec (dtntWorkDir testNetCoreDir) "" "Tests.dll"

    if not result.OK then failwithf "Expecto for netcore tests failed.
```

**Comment by matthid** [comment]
I'd say that is related to the space in your user profile folder.. Obviously, it still has to work but removing the space would probably be a workaround.

We probably need to do some additional escaping within the `-Command` argument
