### ISSUE TITLE
Can't use  System.Data.SQLite.Core from FAKE

### ISSUE THREAD

**Issue by csmager** [fsharp/FAKE#2320]
### Description

Using `System.Data.SQLite.Core` from FAKE 5 results in an exception.

### Repro steps

Use the following build script:
```fsharp
#r "paket:
nuget Fake.Core.Target
nuget System.Data.SQLite.Core //"
#load "./.fake/build.fsx/intellisense.fsx"

open Fake.Core
open System.Data.SQLite

let openConn (path:string) =
    let builder = SQLiteConnectionStringBuilder()
    builder.DataSource <- path
    let conn = new SQLiteConnection(builder.ToString())
    conn.OpenAndReturn()

// Default target
Target.create "Default" (fun _ ->
  Trace.trace "Hello World from FAKE"
  use conn = openConn "temp.db"    
  ()
)

// start build
Target.runOrDefault "Default"
```

### Expected behavior

I was hoping it'd just work, this does work I were to use this in a `netcoreapp2.2` console app.

### Actual behavior

```
Script reported an error:
-> BuildFailedException: Target 'Default' failed.
-> One or more errors occurred. (Unable to load DLL 'SQLite.Interop.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E))
-> DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by csmager** [comment]
And now I've tried a few extra search terms I hadn't thought of, I found #2007, which looks like a duplicate to me. If agreed, please close.

**Comment by matthid** [comment]
Yes agreed this is most likely a duplicate. Thanks for taking a look at this and posting a workaround. I'll take a look into fixing this now.

**Comment by matthid** [comment]
Also thanks for your SQLite example, this is a much better test-case then the full SQL stuff :)
