### ISSUE TITLE
Can provide an useful example how to use Fake and WiX

### ISSUE THREAD

**Issue by mapfel** [fsharp/FAKE#2322]
Hello guys,

I have an example of Fake and WiX which might be useful for others.

- [WiX.InstallerWithService](https://github.com/mapfel/WiX.InstallerWithService)

How to proceed?

- put it under the samples here & create a PR?
- link it somewhere in the docs?
- ???

Ciao, Marko

**Comment by matthid** [comment]
Hey Marko,

@mapfel Please feel free to send a PR with what you think is right.

One way is to extend this site: https://fake.build/apidocs/v5/fake-installer-wix.html
This is done by extending the xml-documentation in https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.Installer.Wix/Wix.fs (in your case, probably the top module documentation).
You can use markdown in the `///` comments

Another way would be to add a new markdown file into https://github.com/fsharp/FAKE/tree/release/next/help/markdown, possibly migrating the `todo-wix.md` file to FAKE 5 and replacing the `Modules -> Installer -> Wix` navigation to point to the new markdown files. The navigation is built here: https://github.com/fsharp/FAKE/blob/0c8eebe7da2b12064005586a797693bcae8e8c0d/help/templates/template.cshtml#L174

Thanks for considering to contribute!
