### ISSUE TITLE
Unable to install using dotnet tool install

### ISSUE THREAD

**Issue by cmeeren** [fsharp/FAKE#2324]
I am trying to install FAKE as a global tool. However, I always get the same error message (which I get regardless of the tool I try to install, e.g. also for `dotnetsay`):

```
C:\Users\Christer\Source\Repos\faketest>dotnet tool install fake-cli -g
Failed to install tool package 'fake-cli': Could not find a part of the path 'C:\Users\Christer\.dotnet\tools\.store\.stage\0qd2mqpa.m45\fake-cli'.
Tool 'fake-cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
```

I have tried for several hours to clean up my environment, PATH, reinstall VS, etc., but I can't figure out why this doesn't work.

I get the same problem when specifying a tool path.

I'm sorry for what is evidently a support request, but I haven't found anything on google, SO, etc. I'm one step short of reinstalling my whole system and have nowhere else to turn.

What could be wrong? Why doesn't this work? What could I do to troubleshoot further?

dotnet info:

```
C:\Users\Christer\Source\Repos\faketest>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.700
 Commit:    c2ef055a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.700\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by baronfel** [comment]
The tools get installed to `%USERPROFILE%\.dotnet\tools` on windows, I would make sure that path is in your PATH. This happens to me on various linux systems I tinker on as well, because there the tools get installed to `~/.dotnet/tools` and that path is _never_ in the user path by default.

**Comment by cmeeren** [comment]
It's on my path, and there's nothing in that folder anyway (just empty `.store\.stage` subfolders).

**Comment by baronfel** [comment]
What about if you specified a version to install: `dotnet tool install -g fake-cli --version 5.13.7`.  My suspicion then is that NuGet is resolving the lowest-possible version, which in the case of `fake-cli` is a prerelease.

**Comment by cmeeren** [comment]
Exact same error.

**Comment by matthid** [comment]
Before reinstalling I'd suggest opening an issue in dotnet/cli so the experts can help you diagnose this issue

**Comment by matthid** [comment]
Maybe the issue is related to some anti-malware tools deleting stuff behind the scenes?

**Comment by matthid** [comment]
Also consider upgrading to a more recent sdk version

**Comment by cmeeren** [comment]
> Before reinstalling I'd suggest opening an issue in dotnet/cli so the experts can help you diagnose this issue

Thanks, I'll do that.

> Maybe the issue is related to some anti-malware tools deleting stuff behind the scenes?

I only have Windows Defender, so that would be very strange.

> Also consider upgrading to a more recent sdk version

2.2.300 is the latest (except 3.0 preview).

**Comment by cmeeren** [comment]
Oh, I found the issue. I removed the `MSBuildSDKsPath` environment variable and now everything works fine. Thanks for the effort!

**Comment by matthid** [comment]
did you set that variable manually? can we close this?

**Comment by cmeeren** [comment]
Sorry, I thought I closed it myself.

I have no idea. Probably I have set it manually a while ago while testing some other stuff.
