### ISSUE TITLE
GitHub.uploadFile seems to hang and do nothing

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#2328]
### Description

When I try to upload a file to a Github draft the process hang and do nothing. I left it running for +5 minutes. before killing it.

If I remove `|> GitHub.uploadFile nupkg` then the Draft is being created and published.

Code used:

```fs
GitHub.createClientWithToken token
|> GitHub.draftNewRelease gitOwner repoName version (isPreRelease version) (getNotes version)
|> GitHub.uploadFile nupkg
|> GitHub.publishDraft
|> Async.RunSynchronously
```

I created a **Personal access tokens** with the following rights:
- public_repo
- repo:status
- repo_deployment

Do I need more rights? Also the repo I am releasing to is under an org where I am the admin (thoth-org).

### Expected behaviour

It should upload the file to the assets list.

### Actual behaviour

The process is hanging.

### Related information 

* Operating system: OSX
* Branch: master
* .NET Runtime, CoreCLR or Mono Version: .NetCore
* Version of FAKE (4.X, 5.X): 5.X

**Comment by matthid** [comment]
How can we reproduce this? Note that we use `uploadFiles` which just calls `uploadFile` internally:

https://github.com/fsharp/FAKE/blob/9789bb0e5b04953dbb9fd927a249fc597d1b3091/build.fsx#L1038

Our release process works.

**Comment by matthid** [comment]
> Do I need more rights? 

Maybe bot honestly I would expect a proper error if the token is not enough (like 401 or 403)

> The process is hanging.

Can you ensure that this is not somehow infrastructure related? I could imagine this being caused by a firewall or by slow upload speeds?

**Comment by MangelMaxime** [comment]
Hello @matthid ,

I saw that FAKE repo is using `uploadFiles` and tried this one too but didn't have much more success.

I created a repo so you can try it too.

**Reproduction step:**

1. Fork this repo: https://github.com/MangelMaxime/FAKE-issue-2328
2. Adapt the [gitOwner](https://github.com/MangelMaxime/FAKE-issue-2328/blob/master/build.fsx#L17) value
3. Run `./fake.sh build`

    You should see something like:

    ```
    ...
    nothing to commit, working tree clean
    On branch master
    Everything up-to-date
    Created draft release id 17906936
    ```

    And see that it's stuck after this line.

4. Go to your repo Release list on GitHub and see a new Draft with no file uploaded and not published.

<img width="1106" alt="Capture d’écran 2019-06-11 à 11 01 18" src="https://user-images.githubusercontent.com/4760796/59258432-42e6f400-8c38-11e9-93b9-88d24fe560e6.png">

I tried using my work connexion which should be enough I think :)

<img width="828" alt="Capture d’écran 2019-06-11 à 11 03 56" src="https://user-images.githubusercontent.com/4760796/59258658-abce6c00-8c38-11e9-8543-d8a738bb5515.png">

and my phone but the result is the same.

**Comment by matthid** [comment]
Hm with the given repro I run into the following error:
```
Script reported an error:
-> FileLoadException: Could not load file or assembly 'FSharp.Control.Reactive, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null'. General Exception (Exception from HRESULT: 0x80131500)
-> Could not load 'FSharp.Control.Reactive, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null'.
   This can happen for various reasons:
   - You are trying to load full-framework assemblies which is not supported
     -> You might try to load a legacy-script with the new netcore runner.
       Please take a look at the migration guide: https://fake.build/fake-migrate-to-fake-5.html
   - The nuget cache (or packages folder) might be broken.
     -> Please save your state, open an issue and then 
     - delete 'FSharp.Control.Reactive' from the '~/.nuget' cache (and the 'packages' folder)
     - delete 'paket-files/paket.restore.cached' if it exists
     - delete '<script.fsx>.lock' if it exists
     - try running fake again
     - the package should be downloaded again
   - Some package introduced a breaking change in their dependencies and .dll files are missing in the resolution
     -> Try to compare the lockfile with a previous working version
     -> Try to lower transitive dependency versions (for example by adding 'strategy: min' to the paket group)
     see https://github.com/fsharp/FAKE/issues/1966 where this happend for 'System.Reactive' version 4
   
   -> If the above doesn't apply or you need help please open an issue!
```

After deleting the lockfile and adding `nuget System.Reactive.Compatibility` (which is the official workaround) it seems to work fine: https://github.com/matthid/FAKE-issue-2328/releases

See https://github.com/matthid/FAKE-issue-2328/commit/b5f0f808cbe2ae6274e8544c75d2169e2450d4c3

One Note: I added `storage: none` which improves speed and is the recommended option but shouldn't have any other impact

**Comment by MangelMaxime** [comment]
I don't have access to my enterprise laptop. I will add to my todo to check your solution and see if this work :)

This is really strange because I didn't have the error message when running against OSX. That's too bad :man_shrugging: because the error report seems to contains everything needed to fix the problem.

**Comment by matthid** [comment]
Maybe that's the bug here, that this error scenario doesn't work on non-windows.... Or you were using a very old fake runner. I can try to check with docker maybe

**Comment by MangelMaxime** [comment]
I tried using your branch and I still have the same behaviour. 

The process is hanging with no error reported and no file pushed.

I suppose there is a problem when using it from OSX. I will try it this evening on my Linux laptop to see if that's specific to OSX or "all" Unix stations.

**Comment by MangelMaxime** [comment]
Ok so I just tested it on Linux and it's working. [Release](https://github.com/MangelMaxime/FAKE-issue-2328/releases/tag/1.0.0)

So, there is definitely something wrong on OS X. I will try to include the source code of `Fake.Api.GitHub` directly and see if I can find where the bug is coming from.

**Comment by matthid** [comment]
Yes please, if it works on Linux as well I have no way to reproduce and no way to introduce a regression test :(

**Comment by matthid** [comment]
@MangelMaxime is this still happening?

**Comment by MangelMaxime** [comment]
I suppose yes. 

I didn't have the time yet to look into the issue sorry... If want to close the issue for the backlog, you can and I can re-open it when I have time to take a look at it?

**Comment by matthid** [comment]
Yes please feel free to comment, I don't think you can re-open but I'm happy to re-open it if this is still a problem. As an alternative you can open a new issue and link back.
