### ISSUE TITLE
Consider explaining the difference between path concatenation operators @@ and </>

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/FAKE#2329]
[This source file](https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.IO.FileSystem/FileSystemOperators.fs) provides two operators for combining file paths: `@@`, and `</>`. Both have the same documentation, yet a slightly different implementation. My codebase uses both of them without a problem, and even by looking at their source code, I cannot understand what the difference between them is.

I think that documenting what makes them different would have been very helpful. Another idea is to deprecate one of them.

**Comment by matthid** [comment]
Thanks for reporting, hope https://github.com/fsharp/FAKE/commit/9789bb0e5b04953dbb9fd927a249fc597d1b3091 helps :)
