### ISSUE TITLE
Fake lock paket version

### ISSUE THREAD

**Issue by BlythMeister** [fsharp/FAKE#2333]
Add ability for FAKE to lock the version of paket so FAKE and paket match rather than show warning to user.

Maybe could be if the dependencies file has a version with a comment fake will manage it.

I.e. 'version 1.2.3 #Fake-Managed'

**Comment by matthid** [comment]
I'm not a fan of automatically editing `paket.dependencies` as that file is user-managed.
I agree that this particular instance might be worth an exception. In fact I think it would be good to have as you only need to update FAKE from this point forward.

Practically, what about users who have customized arguments like:
```
version 123.3 prerelease --source http://my.nuget.feed.corp/v2
```

Problem is the parsing is already quite complicated: https://github.com/fsharp/FAKE/blob/182fe09f8aceadfa55c605e1290fbfa11f756763/src/app/Fake.Runtime/FakeRuntimeHints.fs#L38-L64

I guess this suggestion would make that dependency even more complicated.

I would accept a PR for this :)

Also, I think if we want to "mark" the entry somehow, we need to update paket as well.


Another question arises on "when" FAKE should touch the `paket.dependencies` file.
Always, when the version doesn't match?

**Comment by BlythMeister** [comment]
Hmm true that is complex.

Maybe don't warn...error 🤣

The number of issues I've seen with paket/fake mismatch causing errors.

**Comment by BlythMeister** [comment]
How/where does fake do the restore.
I wonder as an alternative could it try and find the paket.exe (in the same way the visual studio extension does)?
Note: this is me thinking out loud a bit.

**Comment by matthid** [comment]
> Maybe don't warn...error 🤣

Yes erroring out is possible, but it might reduce the acceptance a lot.

> The number of issues I've seen with paket/fake mismatch causing errors.

Can you pinpoint them, or can we collect them somehow? I'm not aware of a lot of issues actually.

> How/where does fake do the restore.
>I wonder as an alternative could it try and find the paket.exe (in the same way the visual >studio extension does)?
>Note: this is me thinking out loud a bit.

I don't think it is as easy as that as we reference `paket.core` we are not calling `paket.exe` anywhere. And problem is I think moving to calling `paket.exe` is just too slow for our use-case. Also we do use `Paket.Core` for a lot of other things than "just" for restore. Basically it allows FAKE to get all reference assemblies for compilation, all assemblies for runtime and all native libraries to load dynamically.

**Comment by BlythMeister** [comment]
Hmm...maybe I'm barking up the wrong tree a bit here 🤣
