### ISSUE TITLE
Environment.environVarOrNone fails with empty string

### ISSUE THREAD

**Issue by MangelMaxime** [fsharp/FAKE#2338]
### Description

`Environment.environVarOrNone` returns `None` when the variable is set to `""` (empty string).

[Source](https://github.com/fsharp/FAKE/blob/c7ccb0331ccace41b201f0224a28f8a78996701f/src/app/Fake.Runtime/Environment.fs#L50-L54)

### Repro steps

Please provide the steps required to reproduce the problem

1. Create an env variable: `export MyVar=""`
2. Run:

```fs
match Environment.environVarOrNone "MyVar" with
| Some password -> password
| None -> failwith "It's failling"
```

### Expected behavior

Should return `Some ""`

### Actual behavior

It returns `None`

### Known workarounds

Use `Environment.environVar` and `isNull`.

If you are ok, I can send a PR changing the implemenation to:

```fs
/// Retrieves the environment variable or None
let environVarOrNone name = 
    let var = environVar name
    if isNull var then None
    else Some var
```

I think we should use `isNull` because `System.Environment.GetEnvironmentVariable` documentation says:

> The value of the environment variable specified by variable, or null if the environment variable is not found.

**Comment by matthid** [comment]
I think historically we always have handled `null` and `""` identically. And isn't that the most time what you expect?

**Comment by MangelMaxime** [comment]
Well, in my case I use the variable to retrieve a database password and locally I don't have a password so I need to use `""` which have a "real" meaning in my case.

Also, after testing my script on the computer of my colleague which use Windows I discovered that the Windows UI doesn't let you enter env var without value (so no empty string) this is probably why you handled it identically.

However, on Unix, I can set an env var to `""`.

**Comment by matthid** [comment]
Yes I agree, but I'm a bit hesitant about the potential impact :)

> this is probably why you handled it identically.

Actually, the code is probably older than I even know that F# exists

I guess at this point we would just properly document the behavior or add another helper function?

**Comment by MangelMaxime** [comment]
By looking at the code again and thinking about this issue we actually have a non consistent behavior:

```fs
/// Retrieves the environment variable or None
let environVarOrNone name = 
    let var = environVar name
    if String.IsNullOrEmpty var then None
    else Some var

/// Returns if the build parameter with the given name was set
let inline hasEnvironVar name = environVar name |> isNull |> not
```

`hasEnvironVar` is using `isNull` and so consider `""` as a valid value. 

I do think whatever we choose to do, we had to properly document the behavior.

> Yes I agree, but I'm a bit hesitant about the potential impact :)

I understand that :) and was thinking that we could make the function obsolete and have 2 helpers functions but I can't find a good name for them.

**Comment by matthid** [comment]
We can also just try to change it, release and see if something breaks. Or check if tests start to fail ...
