### ISSUE TITLE
Can't use netcoreapp version of referenced package

### ISSUE THREAD

**Issue by csmager** [fsharp/FAKE#2340]
This more of a question than a bug at this point. I note this has sort-of come up in #1991. 

I'm migrating some FAKE 4 scripts to FAKE 5. One of them uses an Excel library called FlexCel. The NuGet package has binaries for various frameworks, but relevant here are that is has one for `netstandard2.0` and `netcoreapp2.0`.

You can see [from this note](http://www.tmssoftware.biz/flexcel/doc/net/guides/net-core-guide.html) that they've had to pick a different approach to graphics when running on .NET Core vs the full framework. The `netstandard2.0` binary doesn't have any graphics implementation - it just throws an exception.

Ordinarily, you'll ultimately reference the library via an application that will target either `netcoreapp2.X` or `net4XX`. The library picked when that app is compiled would be one that has an implementation.

The FAKE runner is a `netcoreapp2.1`, so the `netcoreapp2.0` binary would work fine. But the runner loads all dependencies for `netstandard2.0` only, so I get the version with no implementation and I can't load any Excel file that contains an image.

I'd note here it does look like the alternative was tried:
https://github.com/fsharp/FAKE/blob/d44dd6b5040ada8e48b201cf7039489cd49e8025/src/app/Fake.Runtime/FakeRuntime.fs#L42-L45

Is there a reason it was designed like this? Are there any workarounds?

**Comment by matthid** [comment]
The main reason is compilation. At compilation time we have to add all "reference assemblies" to the command line. This is "easy" as we just use the assemblies in the `NETStandard.Library` NuGet package. I feel like this design is reasonable "safe".

To compile against the `netcoreapp` framework moniker it is unclear where we get the required reference assemblies. Calling `msbuild` or depending on installed dotnet sdk is NOT an option here.

Using `netstandard` reference assemblies but paket's `netcoreapp` resolution might be an option but I'm not sure about potential side-effects. We could add a global (experimental) command line option to enable the currently commented line and see how it works (or use the `netcoreapp` assemblies at runtime only). Given the potential side-effects it would never be the recommended default (as long as the question regarding reference assemblies is not solved)

It is a bit sad that packages are distributed this way. Maybe another solution is to wait for `netstandard2.1`

**Comment by matthid** [comment]
Thinking about it, maybe compiling against `netstandard` but using `netcoreapp` assemblies at runtime should be safe, and it would work as long as the APIs are available in the `netstandard` based assembly (if they leave them out you can't compile)

But it comes with a cost: We have to query paket twice about assemblies, which is one of the slowest operations in FAKE. So maybe it would still be opt-in. Also it will complicate some internals a bit.

**Comment by csmager** [comment]
Out of curiosity, I tried uncommenting that line & changed my paket dependencies to specifically target `netcoreapp2.0` (rather than the default `netstandard2.0` that FAKE adds when it does the `paket install`). 

It *nearly* worked, the only issue I had is the native library that this SkiaSharp graphics package requires wasn't found - I suspect that's possibly an unrelated issue, as FAKE happily shows a list of other native libraries in other packages that it could have loaded.

**Comment by matthid** [comment]
> It nearly worked, the only issue I had is the native library that this SkiaSharp graphics package requires wasn't found - I suspect that's possibly an unrelated issue, as FAKE happily shows a list of other native libraries in other packages that it could have loaded.

Yes, we should track that in a new issue, please report one. I looked at the SkiaSharp package and it looks correctly packaged.

**Comment by csmager** [comment]
Sure, will try and put1 a repro together.
