### ISSUE TITLE
Proxy settings not seems to be used only in Fake Script (407) - 200 Ok in pure FSharp

### ISSUE THREAD

**Issue by tebeco** [fsharp/FAKE#2352]
### Description
Trying to do http request to a public website behind a corporate proxy seems to only return 407.
The code works in:
* netcoreapp2.2 / C#
* netcoreapp2.2 / F#

It only fails from within the Fake Script
I've tried using multiple version :
```
> dotnet tool install fake-cli
> dotnet tool install fake-cli --version 5.1
> dotnet tool install fake-cli --version 5.10.1
```

### Repro steps
I cannot provide an actuall NTML proxy to test against ... but i can provide the code i use :

#### NetCoreApp 2.2 / C# :
```csharp
using System;
using System.Text;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace tmp
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var proxy = new WebProxy(
                    new Uri("http://SOME_CORPORATE_PROXY"), 
                    true, 
                    new string[] { "localhost, 127.0.0.1"},
                    CredentialCache.DefaultCredentials
                );

            var handler = new HttpClientHandler { Proxy = proxy, UseProxy = true };
            var client = new HttpClient(handler);

            var result = await client.GetAsync(new Uri("https://www.google.fr")).ConfigureAwait(false);
            Console.WriteLine(result);
            Console.WriteLine("Hello World!");
        }
    }
}
```

#### NetCoreApp 2.2 / FSharp

```fsharp
// Learn more about F# at http://fsharp.org

open System
open System.Net
open System.Net.Http
open System.Text
open System.Security.Authentication

module Common =
  let executeRequest() =
    let proxyUri = Uri("http://SOME_CORPORATE_PROXY")
    let proxyByPass = [|"localhost"; "127.0.0.1"|]

    let proxy = WebProxy(proxyUri, true, proxyByPass, CredentialCache.DefaultCredentials)
    let proxyHandler = new HttpClientHandler()
    proxyHandler.Proxy <- proxy
    proxyHandler.UseProxy <- true
    let client = new HttpClient(proxyHandler)

    async {
      client.GetAsync("https://www.google.fr")
      |> Async.AwaitTask
      |> Async.RunSynchronously
      |> (fun response ->
           match (int response.StatusCode) with
           | statusCode when statusCode >= 400 -> failwithf "request KO with status code %i" statusCode
           | statusCode                        -> printfn "request OK with status code %i" statusCode)
    }
    |> Async.RunSynchronously
    |> ignore

[<EntryPoint>]
let main argv =
  printfn "Hello World from F#!"
  Common.executeRequest()
  0 // return an integer exit code
```
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>
```

#### NetCoreApp 2.2 / Fake Build :

```powershell
[CmdletBinding()]
param(
    [Parameter()]
    # Delete local fake-folder and lock file, use it when you change the dependencies / want to update dependencies or in order to be sure everything is done rom scratch
    [switch]$Force = $false,

    [Parameter()]
    [string]$BuildScript = "build.fsx",

    [Parameter()]
    [switch]$FakeVerbose = $false,

    [Parameter()]
    [string]$FakeVersion = ""
)

$fakeCliNugetName = "fake-cli"
$fakeCliName = "fake"
$buildLockFileName = "$($BuildScript).lock"

$toolPath = ".$($fakeCliName)"
$fakeCli = "$($toolPath)/$($fakeCliName).exe"

function Remove-FakeItems {
    if (Test-Path $toolPath -PathType Container) {
        Write-Host "Deleting '$($toolPath)' folder"
        Remove-Item -Force -Recurse $toolPath
    }

    if (Test-Path $buildLockFileName -PathType Leaf) {
        Write-Host "Deleting fake lockfile : '$($buildLockFileName)'"
        Remove-Item -Force $buildLockFileName
    }
}

function Install-FakeCli {
    Write-Host "Installing '$($fakeCliNugetName)' dotnet tool"
    if($FakeVersion -eq "") {
        $installFakeCliArgs = "dotnet tool install $($fakeCliNugetName) --tool-path $($toolPath)"
    }
    else {
        $installFakeCliArgs = "dotnet tool install $($fakeCliNugetName) --version $($FakeVersion) --tool-path $($toolPath)"
    }

    Write-Host "Execution expression : '$($installFakeCliArgs)'"
    Invoke-Expression $installFakeCliArgs
}

function Invoke-FakeBuild([string]$TargetName) {
    $fakeBuildArgs = "./$($fakeCli)"
    $runArgs = " run --nocache $($BuildScript) --parallel 8"

    if ($FakeVerbose) {
        $fakeBuildArgs += " -v"
    }

    $fakeBuildArgs += $runArgs

    Write-Host "Execution expression : '$($fakeBuildArgs)'"
    Invoke-Expression $fakeBuildArgs
}

if ($Force) {
    Remove-FakeItems
}

$toolPathExists = Test-Path $toolPath -PathType Container
$fakeCliExists = Test-Path $fakeCli -PathType Leaf

if (-Not $toolPathExists -or -Not $fakeCliExists) {
    Install-FakeCli
}

Invoke-FakeBuild

exit $LASTEXITCODE;
```

```fsharp
#r "paket:

"

#load "./.fake/build.fsx/intellisense.fsx"

#if !FAKE
#r "Facades/netstandard"
#r "netstandard"
#endif

open System
open System.Net
open System.Net.Http
open System.Text


module Common =
  let executeRequest() =
    let proxyUri = Uri("http://SOME_CORPORATE_PROXY")
    let proxyByPass = [|"localhost"; "127.0.0.1"|]

    let proxy = WebProxy(proxyUri, true, proxyByPass, CredentialCache.DefaultCredentials)
    let proxyHandler = new HttpClientHandler()
    proxyHandler.Proxy <- proxy
    proxyHandler.UseProxy <- true
    let client = new HttpClient(proxyHandler)

    async {
      client.GetAsync("https://www.google.fr")
      |> Async.AwaitTask
      |> Async.RunSynchronously
      |> (fun response ->
           match (int response.StatusCode) with
           | statusCode when statusCode >= 400 -> failwithf "request KO with status code %i" statusCode
           | statusCode                        -> printfn "request OK with status code %i" statusCode)
    }
    |> Async.RunSynchronously

    |> ignore

Common.executeRequest()

```

**Comment by matthid** [comment]
The two issues that come to mind are:
https://github.com/fsharp/FAKE/issues/2029
https://github.com/fsharp/FAKE/issues/1660

**Comment by matthid** [comment]
Can you add the output of `dotnet --info`?
Can you tell me how you run the console application?
Can you add the project file (fsproj) of the console application? Basically you can compare it to the fake-cli version: https://github.com/fsharp/FAKE/blob/release/next/src/app/fake-cli/fake-cli.fsproj

Can you try building the fake runtime by hand (https://github.com/fsharp/FAKE/tree/release/next/src/app/Fake.netcore) and check if that works on the machine?

**Comment by tebeco** [comment]
## dotnet info
```
> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
(i also used `2.2.301` , as it was released yesterday, i though it was a regression in it but no luck)

## Can you tell me how you run the console application?
I disabled the build agent, connected with both personnal account and Build account :
`dotnet run` directly on a `cmd` shell

## Can you add the project file (fsproj) of the console application?
done

## Basically you can compare it to the fake-cli
first thing i see is `netcoreapp2.1` vs `netcoreapp2.2`
the install for `fake` also install TONS of dependency like `opensll` and so on and it reminds me of `netstandard1.x` dependency. I hope the regression does not comes from a wrong package resolution from paket

## Can you try building the fake runtime by hand
I will try ;)

**Comment by matthid** [comment]
- Just try the console app with `netcoreapp2.1` which is the same as FAKE.
- as you used `dotnet run` on your console app you can try `dotnet run --project ../somewhere/Fake.netcore.fsproj -- build`
- Make sure to add a `global.json` to your console app with the same contents as in the fake repository and try again

**Comment by tebeco** [comment]
### Just try the console app with netcoreapp2.1 which is the same as FAKE.
So i installed SDK 2.1.505 based on [this file](https://github.com/fsharp/FAKE/blob/release/next/global.json)

```
> dotnet add globaljson --sdk-version 2.1.505
> dotnet --version   # to be sure
2.1.505 
```

and i got :
> Hello World from F#!
Pushed result to xxxx with status code 200

So it seems to works in a console project using the same sdk/global.json as fake

**Comment by tebeco** [comment]
`$env:DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=false` 
did the trick.

My guess is that the runtime/sdk used by fake is affected by all the issue that were fixed in CoreFx.

Updating the Sdk to `2.2.301` for fake would probably do the trick.
Building fake on the LAN is really challenging as i have 0 access to either `nuget.org` or `github.com` on our CI
so i'll probably give it a shot on a personnal laptop and copy/paste the executable or so.

But i strongly recommand updating the runtime stack to the latest `2.2.x` (currently SDK 2.2.301 / runtime 2.2.6)

**Comment by tebeco** [comment]
Should i re-open  this issue for tracking as this is probably hurting anybody behind an NTML / Kerberos proxy attempting to make external HTTP call ?

**Comment by matthid** [comment]
It that setting helps then I think I reported the issue here: https://github.com/dotnet/corefx/issues/31098 and I think this is then related to the announcement here: https://github.com/fsharp/FAKE/issues/2029
Additionally, this is how you can workaround in code: https://github.com/fsprojects/Paket/pull/3307 (basically use the `WinHttpHandler` class)

The only question remains why it worked for a standalone application, which doesn't make a lot of sense to me as it should run into the same limitation. Can you confirm that a `netcoreapp2.1` application has this problem while a `netcoreapp2.2` doesn't have this problem?

**Comment by tebeco** [comment]
Related issue :
https://github.com/dotnet/corefx/issues/30166 <== there is an interresting thread with @karelz
https://github.com/dotnet/corefx/issues/36553
https://github.com/dotnet/corefx/issues/30354
https://github.com/dotnet/corefx/issues/30327
https://github.com/dotnet/corefx/issues/30330

i even found one of your issue that is still opened https://github.com/dotnet/corefx/issues/31098

Some were fixed here :
https://github.com/dotnet/corefx/pull/30478
https://github.com/dotnet/corefx/pull/30516

#### Can you confirm that a netcoreapp2.1 application has this problem while a netcoreapp2.2 doesn't have this problem
No i have no issue when i build the console app in `2.1` using sdk `2.1.505`
I'm going crazy because of this behavior.

**Comment by tebeco** [comment]
I think the worst part of it, is that `Fake` run perfectly on my our laptop, not on the CI (On premise Cloud computer) but works on other On premise Cloud Server ...
Seems like a side effect from either the OS / Proxy settings / netfx being installed or not

At this point i don't even want to know ...
As said i'll probably try a `2.2` build of `fake cli` or wait for `3.0` (as it will contains a tons of Proxy improuvment)
