### ISSUE TITLE
MSBuild version detection

### ISSUE THREAD

**Issue by Rajivhost** [fsharp/FAKE#2353]
Hi,
I got this error when I run fake on my Git pre-commit hook.

![image](https://user-images.githubusercontent.com/3539984/61069746-e6c4ea80-a404-11e9-9caa-6212b2a13041.png)

**Comment by Rajivhost** [comment]
This hint can maybe solve the problem.
"msbuild version '13.0.0.0' doesn't support binary logger, please set the msbuild argument 'DisableInternalBinLog' to 'true' to disable this warning."

**Comment by matthid** [comment]
Is there an easy way to reproduce this?

**Comment by Rajivhost** [comment]
Yes,
I installed [Husky](https://github.com/typicode/husky) on my project

Here, my Fake build file:
![image](https://user-images.githubusercontent.com/3539984/61147903-789c2880-a4d5-11e9-9682-883b3dbadd5c.png)

And here: my pre-commit command
![image](https://user-images.githubusercontent.com/3539984/61147950-96698d80-a4d5-11e9-9507-ed4ae2be7b0a.png)

**Comment by inosik** [comment]
Do you get this error if you run `fake build -t build` on the command line?

The error message says that you have both, a `home` and a `HOME` environment variable. This _shouldn't_ happen on Windows, but it does sometimes. See https://github.com/OmniSharp/omnisharp-vscode/issues/1754#issuecomment-330173996 and the linked issues. I fixed this by removing `home` from my environment.

**Comment by matthid** [comment]
I still need a clear way to reproduce this for this to have a chance to be resolved.
Like a standalone git repository I can clone and run a script to have this issue (as I don't yet understand the details of this report)

I'm closing this in the meantime, but please feel free to comment (and I'll re-open) or open a new issue.

**Comment by inosik** [comment]
I'm not sure about PowerShell or `cmd.exe`, but this definitely can be reproduced with Bash:

``` shell
a=1 A=1 fake -t default
```

The `default` task should execute another program.

I guess this was added to FAKE to prevent dotnet/corefx#13146.

**Comment by matthid** [comment]
Question is if this is considered as upstream issue. At least this is my partial understanding from your link?

I guess I'll revert that last fix and see if the corefx error still happens. If it does I'll make fake trigger a warning instead

**Comment by inosik** [comment]
AFAIK the linked issue was fixed in .NET Core 2. However, it might make sense to trigger a warning as you suggest, as Windows users might not be aware that they actually can have multiple environment variables with the "same" key.
