### ISSUE TITLE
No ability to supply organization in SonarQube

### ISSUE THREAD

**Issue by Lutando** [fsharp/FAKE#2356]
In order for sonar scanner to work properly, the scanner requires an organization delimited by  `/o:my-sonarqube-org` to properly work

I cant see a way to add this property to the SonarQubeParams. Imo there should be a member just like how it is in the [task](https://github.com/SonarSource/sonar-scanner-vsts/blob/1767308606c4c4632a111c533061455d67aae417/extensions/sonarcloud/tasks/prepare/new/task.json#L35), called Organization. This field gets mapped to the `/o:my-sonarqube-org` command line argument that I mentioned above.

My current workaround looks something like 
```

    let sonarQubeOptions (defaults:SonarQube.SonarQubeParams) =
        {defaults with
            ToolsPath = toolsDirectory </> "dotnet-sonarscanner"
            Key = "My_Key"
            Name = "MyProject"
            Version = buildNumber
            Settings = [
                "sonar.verbose=true /o:my-org"; 
                "sonar.host.url=https://sonarcloud.io/";
                "sonar.branch.name=dev";
                sprintf "sonar.login=%s" sonarQubeKey;
                sprintf "sonar.cs.opencover.reportsPaths=\"%s\"" testResults </> "opencover.xml";
                "sonar.visualstudio.enable=false"]}

    SonarQube.start sonarQubeOptions

```

notice on the first element of the settings array I put in the organization in there to work around the argument builder within the sonarQube module. 

I can PR this as a fix if you dare let me to :D

**Comment by matthid** [comment]
> I can PR this as a fix if you dare let me to :D

Sure, PRs are always welcome ;)

> `"sonar.verbose=true /o:my-org"; `

Interesting that this "hack" works as it really probably shouldn't ;)

**Comment by Lutando** [comment]
Ok got it. 

The [contribution guidelines](http://fake.build/contributing.html) do not specify which branch to PR into. I am assuming master since the instructions say to branch from master when contributing, correct?

**Comment by matthid** [comment]
Doesn't matter to much, by default github should suggest `release/next` but if it doesn't you can send against `master` and I'll change it anyway ;)
