### ISSUE TITLE
Cannot install specific dotnet SDK version via DotNet.install

### ISSUE THREAD

**Issue by samhanes** [fsharp/FAKE#2365]
### Description

When attempting to install a specific version of the dotnet SDK:

```
let install = lazy DotNet.install (fun opt -> { opt with Version = DotNet.Version "2.2.300" })
```
I get the following error (unless the version is already present on the machine):
```
A compatible SDK version for global.json version: [2.2.401] from [C:\foo\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

My project does not have a `global.json` file, but it appears that `DotNet.install` creates one temporarily when running the `dotnet --version` command: https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.DotNet.Cli/DotNet.fs#L839

That appears to be a problem, see: https://github.com/dotnet/sdk/issues/2334.

I see the reference to https://github.com/fsharp/FAKE/pull/1963, but I'm not sure I understand why it's necessary to create a `global.json` file in order to check the dotnet version. As it stands, I'm not able to install a specific version of the SDK via FAKE - is there a known workaround? Am I doing something silly?

### Repro steps

Please provide the steps required to reproduce the problem

1. Execute a FAKE script that attempts to install a version of the dotnet SDK not present on your machine, e.g., `let install = DotNet.install (fun opt -> { opt with Version = DotNet.Version "2.2.300" })`

### Expected behavior

Specified SDK version is installed.

### Actual behavior

Receive error response:
```
"C:\Program Files (x86)\dotnet\dotnet.EXE" --version (In: false, Out: true, Err: true)
A compatible SDK version for global.json version: [2.2.300] from [C:\foo\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

### Known workarounds

None.

### Related information 

* Windows 10
* CoreCLR 2.2.6
* FAKE 5.12.6, Fake.DotNet.Cli 5.13.5

**Comment by matthid** [comment]
Are you sure this is an error? As you can see in the linked code we redirect the output and error stream and handle that scenario.

The reason we do it this way is because the sdk selects the version for you and defaults to latest. This means without global.json it might tell you 2.2.300 is installed even when 2.1.100 is installed as well and that's the one you are looking for. So that logic is to reduce unnecessary downloads

**Comment by samhanes** [comment]
@matthid I can see how that would work if I wanted a version older than the latest one installed on the machine. In my case, I need to install a version newer than anything on the machine. Is there a way to do that right now?

**Comment by matthid** [comment]
I don't understand the problem to be honest, can you provide a small script and what exactly I need to do to reproduce? As far as I can understand your requirement it should work today. Dotnet install should search and install if it cannot find the version you ask for. It also accounts for the error you reported when searching.

**Comment by samhanes** [comment]
I must be missing something fundamental. Here are some better repro steps:

1. Ensure that the latest installled version of the dotnet SDK on the machine is < 2.2.401.
2. `dotnet new fake`
3. Use the following `build.fsx`:
```
#r "paket:
nuget Fake.Core.Target
nuget Fake.DotNet.Cli //"

#load ".fake/build.fsx/intellisense.fsx"
open Fake.Core
open Fake.DotNet
open Fake.Core.TargetOperators

Target.create "Install" (fun _ ->
    DotNet.install (fun opt -> { opt with Version = DotNet.Version "2.2.401" }) |> ignore
)

"Install"

Target.runOrDefault "Install"
```
4. `.\fake.cmd build`

Result: Version 2.2.401 is *not* installed:
```
C:\code\foo>".fake/fake.exe" build
The last restore is still up to date. Nothing left to do.
run Install
Building project with version: LocalBuild
Shortened DependencyGraph for Target Install:
<== Install

The running order is:
Group - 1
  - Install
Starting target 'Install'
Starting task 'DotNet:version': running dotnet --version
C:\code\foo> "C:\Program Files\dotnet\dotnet.EXE" --version (In: false, Out: true, Err: true)
A compatible SDK version for global.json version: [2.2.401] from [C:\code\foo\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Finished (Failed) 'DotNet:version' in 00:00:00.2111146
Retrieving version failed, assuming because it doesn't match global.json, error
was: System.Exception: dotnet --version failed with code -2147450735
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at Fake.DotNet.DotNet.getVersion(FSharpFunc`2 setParams) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 805
   at Fake.DotNet.DotNet.existingDotNet@841-1.Invoke(String dotnet) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 844
Starting task 'DotNet:version': running dotnet --version
C:\code\foo> "C:\Program Files (x86)\dotnet\dotnet.EXE" --version (In: false, Out: true, Err: true)
A compatible SDK version for global.json version: [2.2.401] from [C:\code\foo\global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
Finished (Failed) 'DotNet:version' in 00:00:00.0577232
Retrieving version failed, assuming because it doesn't match global.json, error
was: System.Exception: dotnet --version failed with code -2147450735
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at Fake.DotNet.DotNet.getVersion(FSharpFunc`2 setParams) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 805
   at Fake.DotNet.DotNet.existingDotNet@841-1.Invoke(String dotnet) in d:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 844
Starting task 'DotNet:version': running dotnet --version
C:\code\foo> "C:\Users\Samuel\AppData\Local\Microsoft\dotnet\dotnet.exe" --version (In: false, Out: true, Err: true)
2.2.401
Finished (Success) 'DotNet:version' in 00:00:00.1217873
Finished (Success) 'Install' in 00:00:00.4893959

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Install    00:00:00.4873516
Total:     00:00:00.5411705
Status:    Ok
---------------------------------------------------------------------
```

**Comment by matthid** [comment]
Yes we could hide the output better but overall the status is `Ok` and it apparently installed the version you are looking for as you can see in the last lines:

```
C:\code\foo> "C:\Users\Samuel\AppData\Local\Microsoft\dotnet\dotnet.exe" --version (In: false, Out: true, Err: true)
2.2.401
```

So you say we should make the output clearer and hide all the intermediate tries or is your build somehow affected by this?

**Comment by samhanes** [comment]
Wow, thanks - I *knew* I must have been missing something. I was attributing an error further down my build to this `--version` response, but you're right, it's working fine.

I do think the output could be hidden as you say, but that's a pretty minor issue.
