### ISSUE TITLE
Enable running on .net core 3.0

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#2371]
This tool will fail to run on .net core 3 runtimes, because the default roll-forward config only allows rolling-forward across minor versions. There are a few options here, in order from worst to best:

* let the user specify a roll-forward env variable: `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2` to allow major-version roll forward
* add a matching setting to this tool's runtimeconfig.json file, like I did in Paket: fsprojects/Paket#3635
* do the work to multitarget the tool to netcoreapp3.0

I plan on issuing a PR soon for the second option, but I wanted to add this issue explicitly in case any FAKE users try to run on 3.0.

**Comment by matthid** [comment]
But this is a duplicate of https://github.com/fsharp/FAKE/issues/2325? The current workaround is already documented. It's just that I didn't knew option 2 existed.

**Comment by baronfel** [comment]
yep, thanks! closing as duplicate, I forgot you linked to that one in the other thread and I was on auto-pilot submitting this exact text to a few of my favorite dotnet tools :)
