### ISSUE TITLE
No templates matched the input template name: fake-template::*.

### ISSUE THREAD

**Issue by homerchap** [fsharp/FAKE#2374]
### Description

I was able to install the fake-cli, but when I try installing the template I get the error 

no templates match the input template name: fake-template::*

### Repro steps

Please provide the steps required to reproduce the problem

1. Install fake-cli

2. Run this command

            dotnet new -i "fake-template::*"

### Expected behavior

Install the fake template

### Actual behavior

I get the following error.  
           
            No templates matched the input template name: fake-template::*.

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Windows 10 Enterprise
* Branch
* .NET Runtime, Visual Studio 2015, 2018
* Version of FAKE 5.X

**Comment by matthid** [comment]
Can you provide the version if the .net sdk (iirc dotnet --info) and the shell you are using?

**Comment by homerchap** [comment]
Here is the info.

.NET Core SDK (reflecting any global.json):
 Version:   2.1.604
 Commit:    c174d0ea92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.604\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.1.604 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by homerchap** [comment]
I updated the sdk and that fixed the problem. I'll close this and leave it here in case anyone else has the same issue.

**Comment by matthid** [comment]
Thanks for posting your solution!
