### ISSUE TITLE
`Error FS0078: Unable to find the file 'netstandard.dll'` when using Fake on WSL / Linux / Ubuntu

### ISSUE THREAD

**Issue by drk-mtr** [fsharp/FAKE#2375]
### Description

It appears Fake is looking in a certain path for the `netstandard.dll` and fails because the dll is not found at this location.

### Repro steps

- Install Fake using `dotnet tool install -g fake-cli`
- Add Fake to the PATH environment variable (required since I'm using ZSH) and confirm that has worked using `fake --version` (this is successful)
- Create a Safe Stack application using the latest template (v1.15.0), then do `fake build -t Run`
- Receive error as follows:
```
Script is not valid:
unknown (1,0)-(1,0): Error FS0078: Unable to find the file 'netstandard.dll' in any of
v4.5
/mnt/c/Projects/SafeStackExample
/home/{username}/.dotnet/tools/.store/fake-cli/5.15.4/fake-cli/5.15.4/tools/netcoreapp2.1/any/
```

### Expected behavior

- There is a way to override the default location that Fake uses OR
- Fake uses the `DOTNET_ROOT` environment variable

I imagine this is already possible and that I simply don't know where to specify this!

### Workarounds

Untested. I imagine copying dlls to this location would work. Alternatively, I could specify the install location for Fake to be the same as my dotnet install path. Obviously there are downsides to these approaches so I imagine there's a "cleaner" way.

### Related information 

* Operating system - Ubuntu 19.04 within WSL on Windows 10 1903
* .NET Runtime, CoreCLR or Mono Version - Mono 6.0.0.319, Dotnet core 3.0.100-preview7-012821
* Version of FAKE (4.X, 5.X) - 5.15.4

While I'm here, massive thanks for the brilliant software!

**Comment by matthid** [comment]
Can you please provide a standalone example on how to reproduce this?

**Comment by drk-mtr** [comment]
Sorry if I'm being dim here (quite new to dev generally) but what's needed for the standalone example? Reason I ask is that it seems the project itself makes little difference. A completely fresh project that simply uses the `dotnet new fake` template shows the same issue. Would you like me to upload the folder that this creates to Github?

It feels like this is more likely caused by environmental weirdnesses at my end, and that this won't show up in a standalone example (though I am just guessing here!).

In case it's relevant, my setup is as follows:

- .zshrc:
    - `DOTNET_ROOT=/usr/share/dotnet`
    - `PATH=$PATH:/usr/share/dotnet:/usr/local/bin:$HOME/.dotnet/tools/:$HOME/dotnet`
- Output of `fake --version`:
```
FAKE 5 - F# Make (5.15.4) (this line is written to standard error, see https://github.com/fsharp/FAKE/issues/2066)
FakePath: /home/badman10/.dotnet/tools/.store/fake-cli/5.15.4/fake-cli/5.15.4/tools/netcoreapp2.1/any/Fake.Runtime.dll
Paket.Core: 5.215.0
```

I hope I'm understanding what's needed here... I appreciate WSL is a rather esoteric use case so apologies for being annoying ;)

**Comment by matthid** [comment]
@drk-mtr Sorry, I think I misunderstood the issue.
The problem is that I cannot reproduce. This shouldn't happen.
I just tried on my ubuntu (WSL just like you have):

```
matthid@DESKTOP-8VDEORF:~/test$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

The following steps
```
# According to official instructions https://dotnet.microsoft.com/download/linux-package-manager/ubuntu16-04/sdk-current
wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install dotnet-sdk-2.2
mkdir test && cd test
dotnet new -i SAFE.Template
dotnet new SAFE
~/.dotnet/tools/fake build -t run
```

And the build runs without the issue. Honestly, I don't really want to test with preview versions, but other then that I'm open for suggestions on how exactly to reproduce this.

Generally fake is not really searching for `netstandard.dll` as it should download its own version of it an uses that if required.

Another thing you can do is to paste the output of the verbose version - running `fake -vv build -t Run` (maybe attach as file or use the details markdown so your post stays readable)

**Comment by drk-mtr** [comment]
Thank you so much for all the pointers. I have just tested this on another PC and I can't reproduce it either.

I'll close this for now and I'll grab my work laptop (the one where I'm seeing the issue) tomorrow and may re-open if I can come up with some consistent reproduction steps. It definitely appears it's a quirk of my environment, since on the other PC I am using the same version of Fake, same dotnet core version, same OS version etc.

Thanks again!

**Comment by matthid** [comment]
@drk-mtr If it still reproduces on your other machine maybe the NuGet cache has been corrupted somehow. You might try to delete `~/.nuget` (or wherever it lives on ubuntu) and try again.

**Comment by drk-mtr** [comment]
Just to confirm that this was 100% user error, so thanks for being patient with me :)

I've wiped dotnet, global tools, path env variables etc. and reinstalled and it's now working perfectly (I should have tried this before posting!).
