### ISSUE TITLE
Is RunSettingsArguments being used?

### ISSUE THREAD

**Issue by eiriktsarpalis** [fsharp/FAKE#2376]
### Description

It seems that the [`DotNet.TestOptions.RunSettingsArguments`](https://github.com/fsharp/FAKE/blob/6008dc27d699f3f0e66164057d04fe998709a9e0/src/app/Fake.DotNet.Cli/DotNet.fs#L1424) property is dead code?

**Comment by matthid** [comment]
Yes looks like it. Should we implement or remove it? I guess you can just use the `Common` field for this?

**Comment by eiriktsarpalis** [comment]
I tried that but it looks like common args are being placed before
everything else so it results in stuff getting ignored because of the --
prefix

**Comment by eiriktsarpalis** [comment]
Would come up with a PR but looks like it's not particularly straightforward

**Comment by matthid** [comment]
to be honest I don't know what arguments this should be used for and how it relates to the possible msbuild, dotnet cli and dotnet runtime arguments. Or where these `RunSettingsArguments` logically belong to. So a PR with examples would be appreciated. Or just some examples on what this should be used for (maybe with links to existing docs)?

**Comment by eiriktsarpalis** [comment]
Afk atm, but in essence this is what it looks like:

```
dotnet test -c Release -f netcoreapp2.2 --
RunSettingsArguments.DisableAppDomain=true
```

If I place the runsettings arguments in Common, it will render as follows

```
dotnet test -- RunSettingsArguments.DisableAppDomain=true -c Release -f
netcoreapp2.2
```
Which results in the -c and -f switches being ignored by dotnet cli (this
is because of the -- delimiter)

I tried maybe hijacking via msbuild args (which are rendered at the end of
the args strings) however arbitrary strings are currently not allowed there.

Will follow up with concrete examples once I get access to a PC.
