### ISSUE TITLE
Put dotnet.exe into PATH

### ISSUE THREAD

**Issue by forki** [fsharp/FAKE#2405]
It would be nice to have a simple way to put the dotnet path into PATH since tools like fable are calling into dotnet and  need the correct version. /cc @alfonsogarciacaro 

    let dotnetTool = (install.Value (DotNet.Options.Create())).DotNetCliPath
    let dotnetFolder = FileInfo(dotnetTool).Directory.FullName
    Environment.setEnvironVar "PATH" (dotnetFolder + ";" + Environment.environVar "PATH")

**Comment by alfonsogarciacaro** [comment]
Yes, Fable is still relying on `dotnet` being globally accessible. Also remember we had trouble before with Windows and Unix systems (Windows uses `;` as PATH separator, while Unix uses `:`).
