### ISSUE TITLE
CreateProcess.withToolType fails for ToolType.FrameworkDependentDeployment

### ISSUE THREAD

**Issue by SteveGilham** [fsharp/FAKE#2412]
### Description

CreateProcess.withToolType fails for ToolType.FrameworkDependentDeployment

The case is just a drop-through; it doesn't try to prefix with `dotnet`
```
      | ToolType.FrameworkDependentDeployment dotnetOptions -> // dotnet ToolPath (can be a dll)
        c
```
I suspect
```
      | ToolType.FrameworkDependentDeployment dotnetOptions -> // dotnet ToolPath (can be a dll)
        c
        |> DotNet.prefixProcess dotnetOptions [c.Command.Executable]
```
would work, but there may be a way that doesn't involve replacing the toolpath with itself

### Repro steps

For a suitable `path/to/netcoreapp.dll` and with sufficient `buildOptions ` that 
```
DotNet.exec buildOptions "path/to/netcoreapp.dll" args 
```
would run, try
```
    let tt = Fake.DotNet.ToolType.CreateFrameworkDependentDeployment buildOptions 
    CreateProcess.fromCommand (RawCommand("path/to/netcoreapp.dll", args))
    |> CreateProcess.withToolType (tt.WithDefaultToolCommandName "dummy")
```

### Expected behavior

Same results as for `DotNet.exec`

### Actual behavior

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```
### Known workarounds

Fall back to DotNet.exec; or there may be some hacks to fix this reflectively

### Related information 

* Fake 5.18.0, of course

**Comment by matthid** [comment]
Yes, your suggested fix is the way to do it, nice find
