### ISSUE TITLE
DotNet.restore does not support multiple framework

### ISSUE THREAD

**Issue by CumpsD** [fsharp/FAKE#2422]
### Description

Fake 5 dotnet restore does not support multiple frameworks. Fake 4 did and the dotnet restore command itself supports it o.

Looking at the code here https://github.com/fsharp/FAKE/blob/b8b7cc4f73a2a544594acfb5a0adb2d1524dc3d5/src/app/Fake.DotNet.Cli/DotNet.fs#L1132

`Runtime: string option` makes it only possible to pass in one runtime.

Looking at the docs here https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore

> -r|--runtime <RUNTIME_IDENTIFIER>
> Specifies a runtime for the package restore. This is used to restore packages for runtimes not explicitly listed in the <RuntimeIdentifiers> tag in the .csproj file. For a list of Runtime Identifiers (RIDs), see the RID catalog. **Provide multiple RIDs by specifying this option multiple times.**

In Fake 4 this could be done with something like

```
  DotNetCli.Restore(fun p ->
  {
    p with
      AdditionalArgs = ["-r win10-x64"; "-r debian.8-x64" ]
  })
``` 

It would be nice to have the option to pass in multiple runtimes with Fake 5 as well.

Executing 2 restores after each other with different runtimes will throw away the results from the first restore, which is why multiple runtimes in `dotnet restore` are supported.

**Comment by matthid** [comment]
Can you cone up with a PR?

**Comment by kmadof** [comment]
@matthid I can try to solve this.

**Comment by matthid** [comment]
@kmadof sure, very welcome :)
