### ISSUE TITLE
The Paket module doesn't know to check for paket installed as a repo tool

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#2429]
### Description

When paket is installed as a donet repo tool (via `dotnet tool install paket`), the Paket module doesn't know how to invoke it.  It attempts commands like `"paket" pack .....` when instead they should be invoked via `dotnet paket`

### Repro steps
Clone https://github.com/fslaborg/XPlot at bf5a23ec258a966e4f7b2d460d0dd09bc16884c6 and run `./build.cmd NuGet` to see the error:

```
Starting target 'NuGet'
Starting task 'PaketPack': .
.> "paket" pack --version 3.0.0 --release-notes "XPlot is now .NET Standard 2.0 only
Support for [SourceLink](https://github.com/dotnet/sourcelink)" bin (In: false, Out: false, Err: false)
Finished (Failed) 'PaketPack' in 00:00:00.0227077
Finished (Failed) 'NuGet' in 00:00:00.0365236
```
 
### Expected behavior

Paket is invoked as a dotnet repo tool if installed.

### Actual behavior

Paket is invoked as a global tool

### Known workarounds

Manually invoke the dotnet-paket version of the tool.

### Related information 

* Operating system: OSX/Windows
* Branch: Fake.DotNet.Paket (5.18.3), fake-cli 5.18.3
* .Net Core 3.0.100 SDK
* Indications of severity: Annoying
* Version of FAKE: 5.18.3

**Comment by matthid** [comment]
Just set the `ToolType` parameter according to this documentation: https://fake.build/dotnet-cli.html#SDK-tools-local-global-clireference

**Comment by baronfel** [comment]
D'oh! Thanks for the pointer, @matthid.

**Comment by matthid** [comment]
Sure thing, you are welcome :)
I mean it could be a better default to detect it somehow, but as a first start explicit is probably fine (and was easier to implement). Let's see if others fall into this as well...

**Comment by cartermp** [comment]
Updated XPlot to use this. Thanks @matthid!
