### ISSUE TITLE
Unexpected build order, what am I doing wrong?

### ISSUE THREAD

**Issue by ovatsus** [fsharp/FAKE#244]
I have the following in `build.fsx`:

    Target "GenerateDocsEn" (fun _ -> ...)

    Target "GenerateDocsJa" (fun _ -> ...)

    Target "GenerateDocs" DoNothing

    "GenerateDocsEn" ==> "GenerateDocsJa" ==> "GenerateDocs"

    Target "ReleaseDocs" (fun _ -> ...)

    "CleanDocs" ==> "GenerateDocs" ==> "ReleaseDocs"

When I call `build "ReleaseDocs"` I get this:

    The resulting target order is:
     - GenerateDocsEn
     - GenerateDocsJa
     - CleanDocs
     - GenerateDocs
     - ReleaseDocs

I was expecting this:

    The resulting target order is:
     - CleanDocs
     - GenerateDocsEn
     - GenerateDocsJa
     - GenerateDocs
     - ReleaseDocs

Is this a bug or does ==> not do what I expected?

**Comment by dsyme** [comment]
Closing old issue
