### ISSUE TITLE
[Gitlab Integration] Support nested sections in the build log

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#2453]
### Description

Gitlab supports custom nested log sections that can be independently expanded/collapsed. Documentation for the format can be found [here](https://docs.gitlab.com/ee/ci/pipelines.html#custom-collapsible-sections).  It would be very nice to support this in the gitlab tracewriter.

### Expected behavior

Fake Job steps (and maybe sections like the job graph, etc) are able to be independently expanded/collapsed)

### Actual behavior

The job logs are one large block.

**Comment by matthid** [comment]
Yes please, pr is appreciated ;)

**Comment by baronfel** [comment]
What would the test cycle for this be like? I imagine there's not a dedicated FAKE build somewhere in gitlab?

**Comment by matthid** [comment]
Yes there's already one but it only runs on the release branch/pr. I can give access to the gitlab settings if needed
