### ISSUE TITLE
Should changelog parsing detect link targets?

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#2455]
### Description

The example changelog at [Keep a Changelog](https://keepachangelog.com/en/1.1.0/) uses Markdown links to link version numbers to GitHub URLs like `https://github.com/olivierlacan/keep-a-changelog/compare/v0.0.1...v0.0.2`. The URLs are listed at the bottom of the document using Markdown [link reference definitions](https://spec.commonmark.org/0.29/#link-reference-definition). Currently, the Fake.Core.Changelog parsing logic doesn't treat the link references specially, so they end up being treated as part of the earliest entry in the changelog. This issue is to discuss whether this case should be detected and handled specially, and if so, how.

### Repro steps

Please provide the steps required to reproduce the problem

1. Copy the example changelog from https://keepachangelog.com/en/1.1.0/ into a CHANGELOG.md file.
1. Write a FAKE script that uses `Fake.Core.Changelog.load` to parse CHANGELOG.md.
1. Step through the list of changelog entries and notice that the entry for 0.0.1 includes all the links, including the links for the most recent entries (1.0.0 and Unreleased).

### Expected behavior

I'd like to see link reference targets, if the changelog includes them, being treated specially. In particular, it would be quite nice if the `Changelog.promoteUnreleased` function could add a new link to the list automatically, which might involve parsing the previous links to find the appropriate URL to link to. Then you could do `"CHANGELOG.md" |> Changelog.load |> Changelog.promoteUnreleased |> Changelog.save` in your `Release` target, and FAKE would create a new link that matches the previous link (with appropriate version number substitutions) in your CHANGELOG.md file.

### Actual behavior

The link reference targets aren't treated specially.

### Known workarounds

You can edit the CHANGELOG.md file by hand to add the appropriate links, but that makes it hard to automate your release workflow.

**Comment by matthid** [comment]
Given all your issues maybe it is reasonable to find a .NET parser for keepachangelog or create a new more sophisticated project and provide a nice API here in FAKE (in case we actually need better integration into FAKE). I'd accept changing the documentation here in FAKE to point to this new project.

This would also solve the breaking change issue from the other issue you opened.

In any case, we can just as well add a new module to `Fake.Core.ReleaseNotes` (or even a new package), but just as you discussed I feel like larger (API) changes are required to implement what you want.

In any case, PR is appreciated. I personally use the simple style release notes :)
