### ISSUE TITLE
Changelog.save should add a final newline

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#2457]
### Description

The `Changelog.save` function should write a final newline to the output file.

### Repro steps

```
    Target.create "Promote Unreleased to new version" (fun _ ->
        let newChangelog = 
            changelogFile 
            |> ChangeLog.load
            |> ChangeLog.promoteUnreleased newVersion
            |> ChangeLog.save changelogFile
```

### Expected behavior

Newly-written `CHANGELOG.md` has a newline at the end of its last line, [as text files should](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

### Actual behavior

Newly-written `CHANGELOG.md` has no final newline, resulting in a diff like this:

```diff
--- CHANGELOG.md	2020-01-27 10:19:28.413980373 +0700
+++ output_CHANGELOG.md	2020-01-27 10:19:31.366052228 +0700
@@ -49,3 +49,4 @@
 [0.0.1]: https://github.com/MyGitHubUsername/MyLib/releases/tag/v0.0.1
 [0.1.0]: https://github.com/MyGitHubUsername/MyLib/compare/v0.0.1...v0.1.0
 [0.2.0]: https://github.com/MyGitHubUsername/MyLib/compare/v0.1.0...v0.2.0
+[1.0.0]: https://github.com/MyGithubUsername/MyLib/compare/v0.2.0...v1.0.0
\ No newline at end of file
```

(Note that there had been a final newline in the input file).

### Known workarounds

You can edit the CHANGELOG.md by hand in any text editor, and saving it will insert a final newline, but if your build script also does a Git commit and push (as, for example, the build script in https://github.com/TheAngryByrd/MiniScaffold does) then that could end up as a new commit with nothing but a single newline in it.

Implementation would be simple:

```fsharp
diff --git a/src/app/Fake.Core.ReleaseNotes/Changelog.fs b/src/app/Fake.Core.ReleaseNotes/Changelog.fs
index 3ba0bd2..f54fd8f 100644
--- a/src/app/Fake.Core.ReleaseNotes/Changelog.fs
+++ b/src/app/Fake.Core.ReleaseNotes/Changelog.fs
@@ -412,7 +412,7 @@ System.IO.File.ReadLines filename
 ///  - `filename` - Changelog text file name
 ///  - `changelog` - the changelog data
 let save (filename: string) (changelog: Changelog) : unit =
-    System.IO.File.WriteAllText(filename, changelog |> string)
+    System.IO.File.WriteAllText(filename, (changelog |> string) + "\n")
 
 /// Promotes the `Unreleased` section of a changelog
 /// to a new changelog entry with the given version
```

### Related information 

* Version of FAKE: 5.19.0

**Comment by matthid** [comment]
Yes happy to accept such a change.
