### ISSUE TITLE
Changelog.Change should detect and filter out blank lines at the end of a section

### ISSUE THREAD

**Issue by rmunn** [fsharp/FAKE#2458]
### Description

Changelog.Change objects are being created with empty text when a blank line appears at the end of a section in the original CHANGELOG.md file. I believe this is unintended behavior. This doesn't affect most use cases, but I'm currently trying to write a function to automatically create a GitHub Release entry by concatenating the changes of all pre-releases. (See repro steps below for an example). Those empty Change objects are causing unwanted blank lines in the result.

### Repro steps

Run `Changelog.parse` on a file with the following contents:

```markdown
## [1.0.0-beta.1] - 2020-02-03

### Fixed
- A bug
- A second bug

### Added
- A new feature

## [1.0.0-alpha.1] - 2020-01-01
...
```

Then get the changelog entry for 1.0.0-beta.1 and do `printfn "%A" changelogEntry.Changes`.

### Expected behavior

```fsharp
[Fixed { CleanedText = "A bug"
         OriginalText = None }
 Fixed { CleanedText = "A second bug"
         OriginalText = None }
 Added { CleanedText = "A new feature"
         OriginalText = None }]
 ```

### Actual behavior

```fsharp
[Fixed { CleanedText = "A bug"
         OriginalText = None }
 Fixed { CleanedText = "A second bug"
         OriginalText = None }
 Fixed { CleanedText = ""
         OriginalText = Some "" }
 Added { CleanedText = "A new feature"
         OriginalText = None }
 Added { CleanedText = ""
         OriginalText = Some "" }]
 ```

### Known workarounds

After collecting all changes that are, say, prereleases of 1.0.0, I can run them through a filter to filter out any that have an empty ChangeText. But that's ugly, because there's no `.ChangeText` property on a Change object. Which means I have to write the filter with a DU like so:

```fsharp
let isEmptyChange = function
    | Changelog.Change.Added s
    | Changelog.Change.Changed s
    | Changelog.Change.Deprecated s
    | Changelog.Change.Fixed s
    | Changelog.Change.Removed s
    | Changelog.Change.Security s
    | Changelog.Change.Custom (_, s) ->
        String.IsNullOrWhiteSpace s.CleanedText

// thisVersion is a SemVer representation of the version I'm about to release
let versionTuple version = (version.Major, version.Minor, version.Patch)
let entriesMatchingThis = changelog.Entries |> List.filter (fun entry -> entry.SemVer.PreRelease.IsSome && versionTuple entry.SemVer = versionTuple thisVersion)
let allChanges = entriesMatchingThis |> List.collect (fun entry -> entry.Changes |> List.filter (not << isEmptyChange))
```

I'd like to not have to write the `|> List.filter (not << isEmptyChange)` step. The only reason it's needed is because the final blank line in each Changelog section (Fixed, Added, etc) is being preserved as a change object, when in fact the only purpose that blank line serves is a visual break before the next section heading.

### Related information 

* Version of FAKE (4.X, 5.X): 5.19.0

**Comment by matthid** [comment]
The question is if someone needs that data so he can reproduce the exact output (including whitespace).
I agree that for processing those empty stuff is not required but if after processing you want to write again they are (otherwise you will remove them every time).

In any case at the very least, we could provide some helpers to do what you are trying to achieve or we could change how we represent whitespace (by a new item), but this would be breaking ...

As I don't think this module is used by lots of people so I'm fine either way, but if someone complains I'd have to revert :)
