### ISSUE TITLE
Use Microsoft.NETFramework.ReferenceAssemblies instead of RoslynTools.ReferenceAssemblies.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fsharp/FAKE#2462]
There is actually a NuGet package called [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies/). It depends on smaller packages depending on the framework, that contain the actual reference assemblies separately per framework. Each of these packages weighs about 10 MB.

This would be a real fix of #2238. The smaller packages would unburden a subpar internet connection, and FAKE would stop depending on a cryptic dependency from a custom source.

**Comment by matthid** [comment]
Yep indeed I just was too lazy to change it until now. It's really a non issue for me as 100mb is not that much and it is only downloaded once...
But PR is definitely appreciated

**Comment by teo-tsirpanis** [comment]
Wait a minute, you had already fixed it in 33beb99f559d48aa24450af42d6e7a9dc3981b3a. 😂

**Comment by matthid** [comment]
Ah didn't even look and apparently forgot about it :D
