### ISSUE TITLE
Announcement: The `dotnet-fake` package and CliToolReference (Paket `clitool`) is deprecated

### ISSUE THREAD

**Issue by matthid** [fsharp/FAKE#2465]
### Description

Given that this way of distributing .NET tools is phased out by Microsoft itself (see https://github.com/dotnet/announcements/issues/107) that announcement shouldn't surprise anyone.
Additionally, we have been hit by the design flaws of this approach multiple times, see https://github.com/fsharp/FAKE/issues/2097 and https://github.com/fsharp/FAKE/issues/2447. Debugging and fixing these issues is incredibly time-consuming and frustrating.

Therefore we will no longer push updates to the `dotnet-fake` package. In the future we might additionally use this package name to publish the standalone tool (today: `fake-cli`), but as usual here in FAKE, we give people enough time to adapt.

For quite a while the documentation already stated:

```
* (No longer recommended) Use it as a dotnet tool (legacy): Add `<DotNetCliToolReference Include="dotnet-fake" Version="5.*" />` to your dependencies and run `dotnet fake ...` instead of `fake ...`, see [this example](https://github.com/FakeBuild/fake-bootstrap/blob/master/dotnet-fake.csproj)

* (No longer recommended) Bootstrap via paket `clitool` (legacy), this is basically the same as `DotNetCliToolReference` but managed via paket. See the [`paket_clitool`](https://github.com/FakeBuild/fake-bootstrap/tree/paket_clitool) branch of `fake-bootstrap` in particular the [build.proj](https://github.com/FakeBuild/fake-bootstrap/blob/paket_clitool/build.proj) file.
```

### Alternatives

We still have all the alternatives:
- Use dotnet SDK v3 and local (preferred - `dotnet tool install fake-cli`) or global (`dotnet tool install fake-cli -g`) tools
- Use global tools if you still are on v2 (`dotnet tool install -g fake-cli`) - Keep in mind that Microsoft support for .NET SDK v2 has already ended
- Download from github release page
- Install via chocolatey

See https://fake.build/fake-gettingstarted.html#Install-FAKE

## Next steps

- Beginning today the documentation for `dotnet-fake` will be removed.
  This includes the samples from https://github.com/FakeBuild/fake-bootstrap
- Beginning today the package `dotnet-fake` will no longer be updated (the broken 5.19.0 release has been unlisted). It was already marked obsolete when https://github.com/fsharp/FAKE/issues/2447 was reported.
- Starting with `5.19.1` the fake template will no longer offer to create new projects with the `dotnet-fake` package.

**Comment by isaacabraham** [comment]
@matthid just to clarify, although I know that local tools are the way forward, are you saying that installing `fake-cli` as a global tool is no longer supported by Microsoft - where's this?

**Comment by matthid** [comment]
@isaacabraham No, only `dotnet-fake` is obsolete and no longer supported. Can you show where I have to edit my post to clarify? (maybe my English failed somewhere?)

**Comment by isaacabraham** [comment]
In the alternatives bit:

> Use global tools if you still are on v2 - Keep in mind that Microsoft support has already ended (dotnet tool install -g fake-cli)

I read that as saying fake-cli as a global tool is not supported.

**Comment by matthid** [comment]
Ah ok I wanted to express that the support for v2 version of the SDK has ended, so there is no reason to stay on v2. And in v3 you can use local tools, which are recommended.
Any idea how to improve that sentence?

**Comment by matthid** [comment]
I edited it a bit.

**Comment by isaacabraham** [comment]
maybe just make it clear in the first line that you can use global tools as well although local is preferred e.g.

> Use dotnet SDK v3 and local (preferred - `dotnet tool install fake-cli`) or global (`dotnet tool install fake-cli -g`) tools
