### ISSUE TITLE
`dotnet new fake --force` overwrites config/dotnet-tools.json

### ISSUE THREAD

**Issue by ktodyruik** [fsharp/FAKE#2470]
Hi,

I was just going through the fake getting started docs. When I ran the template, it warned me that it would modify `config/dotnet-tools.json` and required --force. This doesn't seem necessary as I had already installed fake as a local tool.

Then when I ran `dotnet new fake --force`, it didn't append to dotnet-tools.json, but overwrote the dotnet-tools.json file, deleting the other local tools (like paket) I had already installed.

```
> dotnet new fake
Creating this template will make changes to existing files:
  Overwrite   .config/dotnet-tools.json

Rerun the command and pass --force to accept and create.
```

**Comment by matthid** [comment]
Isn't this just how dotnet templates work? They warn you about overwriting files and if you add `--force` they will overwrite them.
I guess you are suggesting that fake should just add itself if the file already exists, but I'm not sure if this is even possible in a "clean" way.

Are there any other templates you are aware of which do this?

**Comment by ktodyruik** [comment]
Yes. Templates work that way. I don't think it is as flexible and intuitive for the fake template to be adding itself to the local tools in this way. Others might feel differently (it's debatable) but there is no such thing as a "fake project". It's not the same thing as a console project or an ASP.NET project or other base top level projects.  Fake is something you add to existing projects.

**Comment by matthid** [comment]
But in this scenario, you would just **not** use `--force` and add it by hand via `dotnet tool install fake-cli`, right? So I'm not quite sure why this means the template isn't useful. What it adds is that it creates a very minimalistic working build script you can start with. I use it from time to time as well.

In any case I'm still not sure what the expectation or suggestion is?

**Comment by ktodyruik** [comment]
I agree. A minimalistic working build script is handy and what I was after. If I have an existing project, or didn't start from scratch with the fake template, the template will not work. Which I believe is most use cases.

My suggestion is to remove the config/dotnet-tools.json from the template.

**Comment by matthid** [comment]
Aha so the problem is it doesn't do anything without force? Thanks for clarifying

**Comment by ktodyruik** [comment]
Yeah. I wasn't sure either on hindsight after you responded and just tried it out.
