### ISSUE TITLE
[Head's Up] Next version of FCS will change the DependencyManager Api

### ISSUE THREAD

**Issue by baronfel** [fsharp/FAKE#2488]
### Description

After this MR lands (https://github.com/dotnet/fsharp/pull/8812/files) the next version of FCS will have a slightly changed API, where the ResolveDependencies member will take a 4th parameter. `runtimeIdentifier: string` will be added to the end, and we'll need to update the dummy Paket manager here.

**Comment by matthid** [comment]
@baronfel Is this already ready and released?

**Comment by matthid** [comment]
Added a TODO item to 5.20
