### ISSUE TITLE
Octokit.fsx is not DotNET Core compatible?

### ISSUE THREAD

**Issue by njlr** [fsharp/FAKE#2490]
### Description

I am trying to use Fake without Mono, only DotNET Core. 

### Repro steps

Problem encountered building `FSharp.Control.AsyncSeq`

### Expected behavior

-

### Actual behavior

```
/home/njlr/Documents/FSharp.Control.AsyncSeq/paket-files/build/fsharp/FAKE/modules/Octokit/Octokit.fsx (3,0)-(3,47): 
  Warning FS0211: 
    The search directory '/home/njlr/Documents/FSharp.Control.AsyncSeq/paket-files/build/fsharp/FAKE/modules/Octokit/../../../../../packages/Octokit/lib/net45' could not be found
```

### Known workarounds

It seems that [these lines](https://github.com/fsharp/FAKE/blob/333e137b01313820011c6b4db144d341b53e9132/modules/Octokit/Octokit.fsx#L3) should use Paket instead?

Before:

```
#I __SOURCE_DIRECTORY__
#I @"../../../../../packages/Octokit/lib/net45"
#I @"../../packages/Octokit/lib/net45"
#I @"../../../../../../packages/build/Octokit/lib/net45"
#r "System.Net.Http"
#r "Octokit.dll"
```

After:

```
#I __SOURCE_DIRECTORY__
#r "System.Net.Http"
#r "paket: nuget Octokit //"
```

However, I am fairly new to Fake so may have this wrong. 

### Related information 

* Operating system Linux
* Branch
* .NET Runtime, CoreCLR or Mono Version `dotnet 3.0.101`
* Indications of severity
* Version of FAKE (4.X, 5.X) `5.16.0`
* (if performance issue) Performance information, links to performance testing scripts

**Comment by matthid** [comment]
I'm not sure I understand the issue correctly but afaik in FAKE 5, you would use [Fake.Api.GitHGub](https://fake.build/apidocs/v5/fake-api-github.html)?
Yes this file is not really fake 5 ready.

**Comment by njlr** [comment]
I am trying to build https://github.com/fsprojects/FSharp.Control.AsyncSeq which uses that file [here](https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/8256f49806677fa82c503ccc31ba1132555e3313/build.fsx#L256). 

I suppose this build script was written before that FAKE 5 API was written?

**Comment by matthid** [comment]
@nijr Yes indeed, that whole build should be upgraded to FAKE 5 (https://fake.build/fake-migrate-to-fake-5.html). I'm a bit hesitant to still support obsolete stuff considering it was replaced 2 years ago (though I know stuff moves slowly around that area).
I'm closing this for now but let me know if you get stuck somewhere.
