### ISSUE TITLE
Fake.DotNet.Paket only works if paket is locally installed

### ISSUE THREAD

**Issue by seanamosw** [fsharp/FAKE#2491]
### Description

Paket can be installed/run in a few ways now:
  1. As a local binary, often located at .paket/paket
  2. As a local dotnet tool installed with --tool-path
  3. As a global dotnet tool
  4. As a local tool installed using the new tool manifest approach

1 and 2 work at the moment. I have not tested 3, 4 does not work.

I'm personally using paket installed in the local tool manifest.
From a shell, you would call paket using: `dotnet paket ...`

The only workaround I'm aware of is to call paket directly using `CreateProcess`.

### Expected behavior

`Fake.Dotnet.Paket.* ` works when paket is installed with dotnet tool manifest.

### Actual behavior

`Fake.Dotnet.Paket.* ` fails as it is unable to find the paket executable.

**Comment by matthid** [comment]
Afaik you can use the `ToolPath` property to tell FAKE which version you want to use (see https://fake.build/dotnet-cli.html#SDK-tools-local-global-clireference)

**Comment by seanamosw** [comment]
Thanks matthid, this worked for me.

**Comment by NicoVIII** [comment]
For everyone who has the same problem:
Passing `ToolType = ToolType.CreateCLIToolReference()` did the trick for me.

**Comment by seanamosw** [comment]
`ToolType = ToolType.CreateLocalTool ()` worked for me when the tool is installed from a tool manifest.

**Comment by matthid** [comment]
So should we close this, does somebody care to send a PR to improve the docs?

**Comment by DavidSSL** [comment]
@matthid I would like to take care of this but not sure where the best place to put this information would be.

**Comment by ImaginaryDevelopment** [comment]
The links in the discussion about this are dead. can someone point me to this? probably not related to my problem but maybe.
