### ISSUE TITLE
msbuild not generating _publishedWebsites folder in Fake 5

### ISSUE THREAD

**Issue by Aegon95** [fsharp/FAKE#2495]
### Description
Hii iam currently migrating from Fake 4 to Fake 5 
 
**This is my target In Fake 5**

Target.create "BuildApp2" (fun _ ->

    let setParams (defaults: MSBuildParams) = { defaults with Verbosity = Some(Quiet) }
    !!"src/app/**/*.csproj" 
    |> MSBuild.run setParams buildDir "Package"
           [ "Configuration", "Release"
             "OutDir", buildDir 
             "DeployIisAppPath", "Default Web Site"
             "Optimize", "true"
             "FilesToIncludeForPublish", "AllFilesInProjectFolder"
             "PackageLocation", buildDir 
             "PackageAsSingleFile", "true"
             "WebPublishMethod", "Package" ]
    |> Trace.logItems "AppBuild-Output: "
)
**In Fake 4**

Target "BuildApp" (fun _ -> 

    !!"src/app/**/*.csproj"    
    |> MSBuild buildDir "Package" [ ("Configuration", "Release")
                                      ("DeployIisAppPath", "Default Web Site") ]
    |> Log "AppBuild-Output: "
)

when i use fake 4 version i get the _publishedWebsites in my output folder. In Fake 5 i just get a copy of bin folder. I have tried adding so many properties to get this folder but nothing seems to work. Not sure if its mistake from my end or its a bug

### Repro steps

Please provide the steps required to reproduce the problem

1. MSBuild.run

### Expected behavior

Generate _publishedWebsites in outputDirectory

### Actual behavior

just has bin folder contents

### Known workarounds

Edit: found a workaround  if you give "OutDir" property it generates the package zip just like fake 4 (but careful with the path, you need to give relative or full path)

properties i used to get deploy package similar to fake 4

Configuration", "Release"
"OutDir", buildDir 
"DeployIisAppPath", "Default Web Site"
"PackageAsSingleFile", "true"
"WebPublishMethod", "Package"

Hope it helps somebody

### Related information 

* Operating system: Win 10
* .NET Runtime, CoreCLR or Mono Version: .net framework 4.7.1
* Indications of severity: no workaround
* Version of FAKE (4.X, 5.X): fake 4.62 and fake 5.19

**Comment by matthid** [comment]
I guess you compared the command lines in the FAKE output?
Do you think this a bug that should be fixed or by design?

I'd say it is reasonable that we only set and `OutDir` if it was specified by the user (and not automatically). If we set it automatically there should be a way to turn it off (which I'm not sure if that was possible in FAKE 4).
