### ISSUE TITLE
FAKE.FluentMigrator promotion

### ISSUE THREAD

**Issue by jzabroski** [fsharp/FAKE#2498]
Hi, I found https://github.com/fsharp/FAKE/blob/release/next/help/markdown/todo-fluentmigrator.md via https://github.com/fluentmigrator/fluentmigrator/issues/883

I have a section in the FluentMigrator README.md where I cross-promote the FluentMigrator ecosystem, and so far there was no plug for F#.  Please let me know if you'd like to update this blurb and make it more sexy/appealing:

https://github.com/fluentmigrator/fluentmigrator/commit/960449c7a9ced32810825bbd473f55a2b4874f5a#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by matthid** [comment]
I'm not sure who is using this module, but thanks for adding it.
Reads reasonable, but I'm not sure how up to date that module is but in any case reports will come sooner or later :)

I guess there is no action left here in FAKE, so I'm closing this?
