### ISSUE TITLE
GitHub connection doesn't work behind authenticated proxy

### ISSUE THREAD

**Issue by csmager** [fsharp/FAKE#2505]
The Octokit client created via the `Fake.Tools.GitHub` API uses the default proxy, but it doesn't pass on the credentials so you get a 407 Proxy Authentication Required error.

This proxy [can explicitly be configured](https://octokitnet.readthedocs.io/en/latest/http-client/) when creating the `HttpClient` (we'd set it [here](https://github.com/fsharp/FAKE/blob/ae35979b8430c79ba6a14d9e59ae410660d06694/src/app/Fake.Api.GitHub/GitHub.fs#L59)), but we'd need to decide how to approach this. I think we can do either of these (or both):

1. We can add additional `createClient` function(s) that accept an `IWebProxy option`. Not sure I like this as it rather ties your build script to the environment.
2. As suggested in https://github.com/dotnet/runtime/issues/25745#issuecomment-378322214, all we should have to do is make sure the `DefaultProxyCredentials` are set on the `HttpClientHandler` and the system config should 'just work'.

**Comment by csmager** [comment]
Just noticed we still target `net462` and `DefaultProxyCredentials` doesn't exist there. Might need an alternative!

**Comment by matthid** [comment]
@csmager To be honest: I have no idea what the best way forward is. Considering this might hit other modules as well we should aim for an approach which works for others as well.
Can you send a PR for approach 2?

**Comment by csmager** [comment]
Yes, will look into it. Unfortunately seems a little trickier than hoped given that property doesn’t exist in `net462`. I’m curious why we target that as well as `netstandard2.0`?

**Comment by matthid** [comment]
I don't think we really need `net462` support, we add it to make the modules more useful (all FAKE modules/libraries can be used from regular .NET projects as well)

**Comment by csmager** [comment]
Ok. It's fairly easy just to add `#ifdef NETSTANDARD2_0` and do what we need in there. Just need to find a willing colleague to do some testing to prove it solves the problem.
