### ISSUE TITLE
Dotnet pack command does not support --include-symbols

### ISSUE THREAD

**Issue by devployment** [fsharp/FAKE#2506]
### Description

`--include-symbols` seems not to be available via fake.

https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.DotNet.Cli/DotNet.fs

Documented here

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack

### Expected behavior

`PackOptions` should support existing options

### Actual behavior

No `IncludeSymbols` available for `PackOptions`

I created a local version and added `IncludeSymbols` in the PackOptions. Seems to work as I expected. It creates the symbol packages side by side. The package extension can be controlled via `SymbolPackageFormat` through `MSBuild.CliArguments`.

Right now, I'm not sure if this something that can be added in general, or if there are some rules about what parameters are added when. At least `--include-symbols` seems to be available since DNC 2.x.

As I have not too much experience in F# some advice would be  much appreciated.

**Comment by matthid** [comment]
@devployment Just send the changes you have made locally via PR. It's very likely that this is exactly what we should do :)

**Comment by devployment** [comment]
@matthid, will do so. Just one question related to the tooling. I'm on macOS and tried to open the FAKE solution in VSCode. It uses all CPU it can find for quite some time, and at the end I get errors that projects cannot be loaded.

Kind of the same goes for Rider. It shows a fatal error during startup, but is willing to continue. But after that it crashes randomly. 

So, what are you people using in terms of IDE/editors? Facing the same issues? Am I missing something?

**Comment by matthid** [comment]
Indeed, usually when ionide cache is fully build it is workable. I haven't noticed any issues in rider or full visual studio
