### ISSUE TITLE
How do I specify a version of MSBuild in Fake?

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/FAKE#2510]
I've installed dotnet 5 preview but it seems like the MSBuild there isn't compatible with what my project does (it's a sql DB project). How can I force Fake to use an older version of MSBuild? I've tried setting `ToolsVersion` but it doesn't seem to do anything.

**Comment by matthid** [comment]
In worst case you can always overwrite `ToolPath` and specify the executable you want to run manually?

**Comment by matthid** [comment]
The logic is:

https://github.com/fsharp/FAKE/blob/5e6440634c89cbc794e6caa50b2400b426f18d58/src/app/Fake.DotNet.MSBuild/MSBuild.fs#L130-L255

Apparently you can use the `MSBuild` environment variable and the `VisualStudioVersion` environment variable on windows.

**Comment by humhei** [comment]
Meet the same situation when using DonNet.Pack
My workaround is just using ```try... with... pattern``` to escape the exception.
And msbuild actually get worked in practice

**Comment by isaacabraham** [comment]
@matthid The MSBuild fake is resolving to is inside the dotnet sdk folder - I'll find the path and exact error.

**Comment by matthid** [comment]
I'm not sure what the request is, can we close this now?

**Comment by mfriese** [comment]
I would like to set the path of MSBUILD manually. How and where can I set **ToolPath**? I could not find it anywhere. Also Fake knownMSBuildEntries does not include visual studio 2019 which is the only studio i have installed.
