### ISSUE TITLE
FAKE fails when using FSharp.Data's JsonProvider

### ISSUE THREAD

**Issue by OlegZee** [fsharp/FAKE#2514]
### Description

FAKE 5.20 fails with MethodNotFound exception.

### Repro steps

1. Download and extract filed from the archive attached

2. issue `fake build` command

### Expected behavior

Script prints the package author name.

### Actual behavior

Fails with error:

> Script reported an error:
> -> BuildFailedException: Target 'Test' failed.
> -> One or more errors occurred. (Method not found: 'Microsoft.FSharp.Control.FSharpAsync`1<System.IO.TextReader> FSharp.Data.Runtime.IO.asyncReadTextAtRuntime(System.Boolean, System.String, System.String, System.String, System.String, System.String)'.)
> -> MissingMethodException: Method not found: 'Microsoft.FSharp.Control.FSharpAsync`1<System.IO.TextReader> FSharp.Data.Runtime.IO.asyncReadTextAtRuntime(System.Boolean, System.String, System.String, System.String, System.String, System.String)'.

### Known workarounds

Rollback FAKE to 5.16.1.

### Related information 

* Windows 10, Linux
* Branch
* dotnet version 3.1.202
* Severity: High
* Version of FAKE 5.20
[sample.zip](https://github.com/fsharp/FAKE/files/4632730/sample.zip)

**Comment by matthid** [comment]
Is `5.16.1` the latest that works?

**Comment by fhelje** [comment]
For us 5.19 works

**Comment by matthid** [comment]
On `5.20.3` I first got:
```
-> FileLoadException: Could not load file or assembly 'E:\Projects\FAKE\temp\sample\.fake\build.fsx\build_B4F3000F5EE70F813001EC3F714F5E1BE3D53CCD9C9B635DD4B54F897BE9D11F.dll'. Operation did not complete successfully because the file contains a virus or potentially unwanted software. (Exception from HRESULT: 0x800700E1)
```

Which apparently was blocked by defender. After allowing the "threat" it worked fine. So either this is resolved or I cannot reproduce?
