### ISSUE TITLE
I had to delete .fake after updating

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#2516]
I updated the .NET SDK from 3.1.201 to 3.1.300, fake-cli from 5.18.2 to 5.20.0 and all fake packages (see bottom).

On the next invocation I got this error:

![image](https://user-images.githubusercontent.com/4236651/82678435-e236a880-9c49-11ea-91a8-a4e84d3821fb.png)

```
-> One or more errors occurred. (Method not found: 'Void Options..ctor(System.String, Microsoft.FSharp.Core.FSharpOption`1<System.String>, System.String, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<Verbosity>, Boolean, Boolean, Boolean, Microsoft.FSharp.Collections.FSharpMap`2<System.String,System.String>)'.)
-> MissingMethodException: Method not found: 'Void Options..ctor(System.String, Microsoft.FSharp.Core.FSharpOption`1<System.String>, System.String, Microsoft.FSharp.Core.FSharpOption`1<System.String>, Microsoft.FSharp.Core.FSharpOption`1<Verbosity>, Boolean, Boolean, Boolean, Microsoft.FSharp.Collections.FSharpMap`2<System.String,System.String>)'.
Hint: The given error might indicate a problem with the fake cache. Backup the '.fake' directory, delete it and try again. If it works or you need help consider reporting a new issue.
```

I renamed the ``.fake`` directory and then it worked. I have attached the old folder.

[.fake.zip](https://github.com/fsharp/FAKE/files/4668662/default.fake.zip)

Here are the __previous__ and __new__ packages:

[packages_old.txt](https://github.com/fsharp/FAKE/files/4668691/packages_old.txt)

[packages_new.txt](https://github.com/fsharp/FAKE/files/4668693/packages_new.txt)

**Comment by matthid** [comment]
I'm not sure there is enough info to pin this one down. The first thing that comes to mind would be a binary breakage somewhere. Question is which `Option` Contructor (from which assembly?) it is missing here.

**Comment by 0x53A** [comment]
I created the issue because the error message prompted me to.

We could extend the error message with [MissingMethodException.ClassName](https://docs.microsoft.com/en-us/dotnet/api/system.missingmemberexception.classname?view=netcore-3.1)? I think that is the full name, with the namespace, not just Options.

**Comment by matthid** [comment]
Good idea
