### ISSUE TITLE
Easily run a command on Unix or Windows

### ISSUE THREAD

**Issue by theprash** [fsharp/FAKE#2524]
I would like to add a way to start a process using a command available on the path (e.g. npm) that works on any supported OS.

The SAFE template FAKE script currently contains code like this:

```fsharp
let npm args workingDir =
    let npmPath =
        let npmPath = if Environment.isUnix then "npm" else "npm.cmd"

        npmPath
        |> ProcessUtils.tryFindFileOnPath
        |> Option.defaultWith(fun () -> failwith "npm was not found in path.")

    let arguments = args |> String.split ' ' |> Arguments.OfArgs

    Command.RawCommand (npmPath, arguments)
    |> CreateProcess.fromCommand
    |> CreateProcess.withWorkingDirectory workingDir
    |> CreateProcess.ensureExitCode
    |> Proc.run
```

Ideally we could replace it with this:

```fsharp
let npm args workingDir =
    let arguments = args |> String.split ' ' |> Arguments.OfArgs
    Command.RawCommand ("npm", arguments)
    |> CreateProcess.fromCommand
    |> CreateProcess.withWorkingDirectory workingDir
    |> CreateProcess.ensureExitCode
    |> Proc.run
```

This would require the following from `CreateProcess` API automatically:

- If a file name (not path) is provided then try to find the executable file automatically
- If the environment is Windows, then automatically look for executable extensions: .cmd, .exe etc.
- If an executable was not found on the path then fail with an error message explaining that

I am happy to do this work but I'm looking for input on the best API for this. We could do it all automatically as in my example above, or add another small helper function like `Environment.findExecutableOnPath` that works on Windows or Unix. Or take some other option.

Any thoughts? Is there anything else that I should consider when adding this feature?

**Comment by theprash** [comment]
Having looked at the FAKE code I've just found that PATHEXT is actaully considered already by `ProcessUtils.tryFindFileOnPath` so we can already collapse the code down to this:

```fsharp
let npm args workingDir =
    let npmPath =
        "npm"
        |> ProcessUtils.tryFindFileOnPath
        |> Option.defaultWith(fun () -> failwith "npm was not found in path.")

    let arguments = args |> String.split ' ' |> Arguments.OfArgs

    Command.RawCommand ("npm", arguments)
    |> CreateProcess.fromCommand
    |> CreateProcess.withWorkingDirectory workingDir
    |> CreateProcess.ensureExitCode
    |> Proc.run
```

This already addresses some of the problem, which is good. However, it would still be good if it all worked in a single step, because it's not currently obvious how to use `CreateProcess` to run a command in this way.

**Comment by matthid** [comment]
I think adding a `CreateProcess.from___` helper which considers this would be acceptable, though the name and API has to be appealing. Currently there is no logic at all to resolve anything and we directly give the `RawCommand` (I mean that is the reason why it is called this way) to the system APIs. The general idea of `CreateProcess` not doing fancy things ootb needs to stay (in order to have fallback options when the fancy way breaks or in case of edge case scenarios where you need that control)
