### ISSUE TITLE
Running msbuild or dotnet test in parallel has race condition

### ISSUE THREAD

**Issue by marklam** [fsharp/FAKE#2541]
### Description

The naming of temp files for the msbuild binlog can cause a build failure when msbuild (or dotnet test) tasks are run in parallel.

### Repro steps

Run many dotnet test tasks in parallel

### Expected behavior

The tasks run to completion

### Actual behavior

If you're unlucky, two tasks try to write to the same temp file, because the files are named by asking for a temp file [and then deleting it ](https://github.com/fsharp/FAKE/blob/bdce1746a27764a630c1008c32326cc82ce90334/src/app/Fake.DotNet.MSBuild/MSBuild.fs#L711) so the next task to ask for a temp file name can get the same file name because it doesn't look like it's in use.

### Known workarounds

Disable parallel task building

### Related information 

* Windows 10
* Fake 5.20.2
* .NET Core 3.1

**Comment by matthid** [comment]
@marklam As you already found the place: Can you suggest a fix for this? If we don't delete the file it will fail as well because MSBuild will complain, correct?

**Comment by marklam** [comment]
The file that gets deleted isn't actually the filename that gets passed to MSBuild, because it gets a ".binlog" extension added. but I think this would fix the race (based on the commented-out line that's already in the code)
```
@@ -700,10 +700,7 @@ yield consoleLogParams
         None, args
     else
         let argList = Args.fromWindowsCommandLine args |> Seq.toList
-        let path = Path.GetTempFileName()
-        File.Delete(path)
-        let path = path + ".binlog"
-        //let path = Path.GetFullPath <| sprintf "fake-msbuild-%s.binlog" (System.Guid.NewGuid().ToString())
+        let path = Path.GetTempPath() </> sprintf "fake-msbuild-%s.binlog" (System.Guid.NewGuid().ToString())
         let v = getVersion exePath callMsbuildExe
         if v >= versionToUseBinLog then
             Some path, Args.toWindowsCommandLine (argList @ [ "/bl:" + path ])
```

Sorry I can't make a PR, but I can't actually get the fake project to build on my machine (I didn't have the correct version of the sdk installed, but when I worked around that I got other failures that might be related to the workaround).
