### ISSUE TITLE
Add support for net5.0

### ISSUE THREAD

**Issue by tforkmann** [fsharp/FAKE#2544]
### Description

The latest Paket alpha version 6.0.0-alpha042 supports the RC version net5.0.
There was a change in the naming so instead of netcoreapp5.0 Paket is now generating the version net5.0

### Repro steps

Restore latest Paket and Fake versions:
``
$ dotnet tool restore
Tool 'fake-cli' (version '5.20.3') was restored. Available commands: fake
Tool 'paket' (version '6.0.0-alpha042') was restored. Available commands: paket
``
Try to run your build script like this:
``
$ dotnet fake build --target run
The last restore is still up to date. Nothing left to do.
Performance:
 - Cli parsing: 272 milliseconds
 - Packages: 61 milliseconds
 - Runtime: 762 milliseconds
There was a problem while setting up the environment:
-> Error during parsing of '/Users/tforkmann/Dropbox/Programming/fsharp/DayTrader/paket.lock'.
-> invalid parameter 'net5.0' after >= or < in '== net5.0'

### Expected behavior

Should execute the build script

### Actual behavior

Runs into parsing error of the paket lock file

### Related information 

* Operating system: macOS

**Comment by baronfel** [comment]
I can echo this. I'm torn on if the proper fix is for Paket to release a 5.x version that can understand the net5.0 moniker, or if FAKE should update to one of the prereleases.

Either way, this is a blocker for my team to begin working with and evaluating .net5.0 rcs.

**Comment by baronfel** [comment]
I started https://github.com/fsprojects/Paket/pull/3913 to see if we can get a stable paket version soon to make FAKE not have to take a prerelease dependency.

**Comment by matthid** [comment]
@baronfel We could release a prerelease of FAKE based on paket6 prerelease but it makes it a bit harder for me to keep track of stuff :(

**Comment by eiriktsarpalis** [comment]
I just came across the same issue. Is there a way to work around it? I tried enabling the `PAKET_SKIP_RESTORE_TARGETS` environment variable but it didn't seem to fix the problem.

**Comment by tforkmann** [comment]
@matthid  fsprojects/Paket#3913 was merged. Could you update the Paket dependency? Or is this now working out of the box?

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/96775277-99953e00-13e7-11eb-8026-008f7db448e4.png)

**Comment by matthid** [comment]
What about https://github.com/fsprojects/Paket/issues/3896#issuecomment-714268558 ?

**Comment by forki** [comment]
I'm about to push 251 which is hoepefully backwards compatible

**Comment by forki** [comment]
so seems 5.251 seems to be working

**Comment by matthid** [comment]
Cool thanks, if someone wants to boost this they can send an PR with the update so CI can check if everything is still OK. Otherwise I'll try to update later (but realistically something usually breaks, so it can take a bit to actually release)

**Comment by matthid** [comment]
@forki I noticed a problem on GitLab which basically boils down to paket (crashing with stackoverflow) having trouble to resolve:

```
group Build
    source https://api.nuget.org/v3/index.json
    nuget Fake.DotNet.Cli
    nuget Fake.IO.FileSystem
    nuget Fake.Core.Target
```

Paket `5.251.0` runs into the following 'conflict':

```
  Conflict detected:
   - System.Security.Cryptography.Cng 5.0.0-preview.8.20407.11 requested package Microsoft.NETCore.Platforms: >= 5.0.0-preview.8.20407.11 (preview)
   - System.Text.Encoding.CodePages 4.7.1 requested package Microsoft.NETCore.Platforms: >= 3.1.1
   - System.Security.AccessControl 4.7.0 requested package Microsoft.NETCore.Platforms: >= 3.1
   - System.Security.Principal.Windows 4.7.0 requested package Microsoft.NETCore.Platforms: >= 3.1
   - System.Runtime 4.3.1 requested package Microsoft.NETCore.Platforms: >= 1.1.1
```

I assume there are still some problems with corner case packages on .net 5. Any chance we can get this fixed? While locally and on other CI systems paket finds a solution, it still dances around downgrading lots of packages until it finally finds a solution and downgrades some packages which IMHO shouldn't need to be downgraded (like `NuGet.Common` and some others). 

At the very least I need to know what I should say to users when this hits someone?

Anyway, I released `5.20.4-alpha.1642`, so maybe someone here can test if that actually works better?

**Comment by forki** [comment]
Can you please open an issue on Paket? Will take a look at it this evening

Matthias Dittrich <notifications@github.com> schrieb am Fr., 23. Okt. 2020,
16:14:

**Comment by Shmew** [comment]
Can confirm `5.20.4-alpha.1642` did the trick for me. Running FAKE at `5.20.3` and Paket at `5.251.0` was giving me the `invalid parameter 'net5.0' after >= or < in '== net5.0'` error.

**Comment by tforkmann** [comment]
I also can confirm this issue is resolved!

Thanks for your help!

**Comment by BlythMeister** [comment]
@forki @matthid any chance of this making it to the stable channel?

Hit this issue when we use net5
