### ISSUE TITLE
Support for CircleCI

### ISSUE THREAD

**Issue by brettrowberry** [fsharp/FAKE#2547]
I see that Fake has documentation for several build servers:

![image](https://user-images.githubusercontent.com/10521647/94966254-f1b4e080-04ca-11eb-8146-ef610757c70a.png)

Would you consider adding support for CircleCI?

**Comment by matthid** [comment]
Sure, I even had it running at some point here in the repository but circleci and teamcity had a tendency to break and were sent to sleep ;)
So feel free to contribute...
