### ISSUE TITLE
Warning: Paket resolved a FSharp.Core with version '5.0.0.0', but fake runs with a version of '4.7.0.0'. This is not supported.

### ISSUE THREAD

**Issue by travis-leith** [fsharp/FAKE#2551]
Not sure if this is a truly new issue but it is at least related to https://github.com/fsharp/FAKE/issues/2001, however, the advice given in the other issue does not resolve this.

My dotnet core version is 3.1.402
FAKE 5 - F# Make (5.20.3)
Paket.Core: 5.249.0

The relevant entry in paket is
nuget FSharp.Core 4.7.0.0

Is this something I can safely ignore?

**Comment by xdaDaveShaw** [comment]
Is this using the built in `Paket` module? I noticed when I tried it on Linux it didn't work as it was trying to run .NET Framework code.

So I swapped to `DotNet.exe id "paket" "restore"`, maybe that will help?
