### ISSUE TITLE
ReleaseNotes.load does not parse SemVer correctly

### ISSUE THREAD

**Issue by Freymaurer** [fsharp/FAKE#2557]
### Description

I used ReleaseNotes.load to read in my markdown release notes and tried to add the github commit to the SemVer [metadata](https://semver.org/lang/de/#spec-item-10). As "#" is not a allowed symbol in metadata the version looks like this `0.1.1+09da94a`. 

```fsharp
let release = ReleaseNotes.load "RELEASE_NOTES.md"
```

`release.SemVer.BuildMetaData` returns in this case `09`
`release.SemVer.Original` returns in this case `0.1.1+09`

if i change the SemVer to `0.1.1+test` it returns nothing for meta data.

### Repro steps

1. Create RELEASE_NOTES.md with 

```markdown
### 0.1.1+09da94a (Released 2020-11-18)
* TestDes.:
    * TestSubDesc
```

2. Parse the markdown file with `ReleaseNotes.load "RELEASE_NOTES.md"`

3. Check SemVer.BuildMetaData/SemVer.Original of the ReleaseNotes record type.

### Expected behavior

As far as i understand the [specification](https://semver.org/lang/de/#spec-item-10) it should allow both numbers and letters for 
metadata.

> Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. 

> Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, **1.0.0-beta+exp.sha.5114f85**, 1.0.0+21AF26D3—-117B344092BD.

### Actual behavior

It stops parsing the metadata at the first letter.

**Comment by Freymaurer** [comment]
Okay, so i looked a bit into this:

The problem seems to be that [SemVer is parsed from the nuget version].(https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.Core.ReleaseNotes/ReleaseNotes.fs#L62)

```fsharp
static member New(assemblyVersion,nugetVersion,date,notes) = { 
  AssemblyVersion = assemblyVersion
  NugetVersion = nugetVersion
  SemVer = SemVer.parse nugetVersion
  Date = date
  Notes = notes }
```

and nuget seems to get parsed with this Regex pattern: `([0-9]+.)+[0-9]+(-[a-zA-Z]+\d*)?(.[0-9]+)?`, which does actually not hit any metadata and is faulty as it will parse wrong patterns.

My suggestion would be to use the [offcially recommended Regex](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string) to parse SemVer. Either by parsing the full header for SemVer again or by using it to also parse the nuget version.

In the following i removed starting and ending requirement to confidently pick the complete SemVer from the start line.

```regex
(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?
```

You can check this regex against some examples:

```
### 0.1.1+7c567fd (Released 2020-11-18)

### 0.2.0+899b535 (Released 2021-1-11)

### 0.3.0+0d31c43 (Released 2021-2-11)

### 0.3.1+cbc655c (Released 2021-2-12)

1.0.0-alpha+001
1.0.0+20130313144700, 
1.0.0-beta+exp.sha.5114f85
1.0.0+21AF26D3—-117B344092BD
```

**Comment by Freymaurer** [comment]
Would it help if i did a PR for this? There are some open PRs and i don't really know if this would be useful.

**Comment by aggieben** [comment]
I think this may still be an issue and should be reopened.

**Comment by Freymaurer** [comment]
Yes sadly it is 😢 I am also having an eye on this issue
