### ISSUE TITLE
Fake does not find dotnet fsi for Fsi.exec targets.

### ISSUE THREAD

**Issue by nhirschey** [fsharp/FAKE#2561]
### Description

Fake does not find new versions of fsi on windows. FsiTool.Internal works, but FsiTool.Default and FsiTool.External "dotnet fsi" fail.

### Repro steps

1. Install a new version of fsi
    - If installed via Visual Studio 2019 16.8 Community, it will be in `[ProgramFilesX86]/Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\FSharp`
    - If installed via dotnet 5.0.100 it will be in `[ProgramFiles]dotnet\sdk\5.0.100\FSharp`.
2. Try to run `Fsi.exec id "testscript.fsx" []` or `Fsi.exec (fun p -> {p with FsiTool.External "dotnet fsi"}) "testscript.fsx" []` in a fake `build.fsx` script.
### Expected behavior

I expect fake to run `testscript.fsx`

### Actual behavior

The target fails with the error ` (Start of process 'fsi.exe' failed.)` or ` (Start of process 'dotnet fsi' failed.)`.

The problem is the fsi path searching here: https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.DotNet.Fsi/Fsi.fs#L249

To find the latest `dotnet fsi`, it will probably be necessary to update [ProcessUtils.findFilesInternal](https://github.com/fsharp/FAKE/blob/514bb278d8c0904f15a703629a03388afa5bab41/src/app/Fake.Core.Process/ProcessUtils.fs#L13) so that it searches `C:\Program Files\dotnet\sdk` for the latest sdk.

### Known workarounds

`Fsi.exec (fun p -> {p with FsiTool.Internal}) "testscript.fsx" []` works.

### Related information 

* Windows 10
* Dotnet 5.0.100
* Version of FAKE (4.X, 5.X) : 5.20.3

**Comment by nhirschey** [comment]
still an issue

**Comment by rynoV** [comment]
I'm also running into this issue. In my case FsiTool.Internal also doesn't work

**Comment by rynoV** [comment]
`Internal` doesn't seem to respect `WorkingDirectory`

I hacked `External` like this for now

```patch
diff --git a/Build/Fsi.fs b/Build/Fsi.fs
--- a/Build/Fsi.fs	(revision eb8500c3ee49ba79594a49077974bd2f9e0f935c)
+++ b/Build/Fsi.fs	(date 1711662199284)
@@ -49,6 +48,7 @@
 
     [<RequireQualifiedAccess>]
     type FsiTool =
+        /// Use an empty string to use `dotnet fsi`
         | External of string
         | Internal
         | Default
@@ -357,7 +357,7 @@
 
             let messageF msg = results.Add msg
 
-            let processResult =
+            let mutable proc =
                 CreateProcess.fromRawCommandLine fsiExe args
                 |> CreateProcess.withEnvironment (
                     defaultEnvironmentVars |> List.append (parameters.Environment |> Map.toList)
@@ -366,7 +366,11 @@
                 |> CreateProcess.withTimeout TimeSpan.MaxValue
                 |> CreateProcess.redirectOutput
                 |> CreateProcess.withOutputEventsNotNull messageF errorF
-                |> Proc.run
+
+            if String.IsNullOrWhiteSpace fsiExe then
+                proc <- proc |> DotNet.prefixProcess id [ "fsi" ]
+
+            let processResult = proc |> Proc.run
 
             if processResult.ExitCode <> 0 then
                 List.iter Trace.traceError (errors |> List.ofSeq)
```
