### ISSUE TITLE
Out of the box Bootstrapping failed 

### ISSUE THREAD

**Issue by halcwb** [fsharp/FAKE#2566]
### Description

Trying to build a contributing next/rease branch fails

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone fake
2. Checkout the next/release branch
3. Run `dotnet build`

### Expected behavior

All builds without errors

### Actual behavior

Build fails at BootstrapTestDotNetCore, see also the [CI build](https://travis-ci.org/github/fsharp/FAKE). 

### Known workarounds

??

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Indications of severity
* Version of FAKE (4.X, 5.X)
* (if performance issue) Performance information, links to performance testing scripts

**Comment by jhursey** [comment]
I can duplicate the issue on the `release/next` branch but also on the 5.20.3 release tag. Maybe it is a dependency change then?

**Comment by yazeedobaid** [comment]
Thanks for reporting it. Now the build is green so this issue no longer exists. I'll close this now, please feel free to open an issue if you have any issues.
