### ISSUE TITLE
SqlPackage.deployDb exception without timeout

### ISSUE THREAD

**Issue by jhursey** [fsharp/FAKE#2567]
### Description

When running SqlPackage.deployDb without a timeout argument an exception is thrown.

### Repro steps

Run the example found at [https://fake.build/sql-sqlpackage.html](https://fake.build/sql-sqlpackage.html).

### Expected behavior

Should either warn the user of a missing argument or provide a valid default.

### Actual behavior

Throws a NullReferenceException

### Known workarounds

Provide a timeout argument

### Related information 
```bash
fake --version
FAKE 5 - F# Make (5.10.1)

cat .config/dotnet-tools.json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "fake-cli": {
      "version": "5.20.3",
      "commands": [
        "fake"
      ]
    }
  }
}
```

I am 99% sure the error is in _src/app/Fake.Sql.SqlPackage/Sql.SqlPackage.fs_ line 121.
```FSharp
| Timeout when String.isNullOrEmpty(args.Profile) && args.Timeout.IsNone -> sprintf "/p:CommandTimeout=%d" args.Timeout.Value
```
We check that `args.Timeout.IsNone` but then call `args.Timeout.Value` anyway.

**Comment by yazeedobaid** [comment]
This should be fixed now by #2581 
please check https://github.com/fsharp/FAKE/blob/release/next/src/app/Fake.Sql.SqlPackage/Sql.SqlPackage.fs#L129
