### ISSUE TITLE
Add SqlPackage.exe /AccessToken parameter

### ISSUE THREAD

**Issue by jhursey** [fsharp/FAKE#2568]
### Description

Use the AccessToken parameter for authentication to Azure. 

### Expected behavior

Setting AccessToken on the deployment parameters gets passed to SqlPackage.exe

**Comment by yazeedobaid** [comment]
Is this the form you want:
```
SqlPackage.deployDb (fun(args:SqlPackage.DeployDbArgs) ->
        { args with
                Destination = "Data Source=https://tcp:your-server-name.database.windows.net; Initial Catalog=database-name;"
                AccessToken = "your-azure-access-token"
                Source = "path-to-sql-project.dacpac"
        })
```

I was trying with it and it didn't work, I keep receiving the following message:

> A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - No such host is known.)

Here the underlying sqlpackage.exe command that FAKE generate:
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150\sqlpackage.exe" /Action:Publish /AccessToken:your-azure-access-token /SourceFile:"path-to-sql-project.dacpac"  /TargetConnectionString:"Data Source=https://tcp:your-server-name.database.windows.net; Initial Catalog=database-name;"  /p:BlockOnPossibleDataLoss=false /p:DropObjectsNotInSource=false /p:CreateNewDatabase=false 
```

Could you please try running the above command and replace it with your server information? If it is working with you I guess then it is a problem with my connection/setup. If that is the case I can send a PR for it.
Thanks

**Comment by jhursey** [comment]
The proposed form is exactly what I am looking for.

Your attached PowerShell command works if the access token is in quotes.
