### ISSUE TITLE
#r "paket: ...." Shows an intellisense error now

### ISSUE THREAD

**Issue by seanamosw** [fsharp/FAKE#2572]
### Description

`#r "paket: ...."` shows an intellisense error now.
This started for me when Ionide updated to v5.4.0.

Example:
```fsharp
#r "paket: groupref fake //"
```
```
Package manager key 'paket' was not registered in [/home/seanamos/.vscode/extensions/ionide.ionide-fsharp-5.4.0/bin; /home/seanamos/.vscode/extensions/ionide.ionide-fsharp-5.4.0/bin/], []. Currently registered: nuget F# Compiler(3400)

'' is not a valid assembly name F# Compiler(213)
```

I suppose this was inevitable as package manager references became part of the core F# experience.

This doesn't break anything (yet) other than the build.fsx file being flagged as having errors. The fake-cli continues to work and intellisense continues to work throughout the rest file.

**Comment by kurt-mueller-osumc** [comment]
![Screen Shot 2021-04-21 at 2 53 29 PM](https://user-images.githubusercontent.com/66080261/115606240-76255000-a2b1-11eb-9124-e48c58d56d0f.png)

I get the same error.

**Comment by baronfel** [comment]
This won't be fixed until FAKE is updated to at least FCS 39, due to API breaks in that library.

Because Ionide hosts FAKE in-process, FAKE was blocking Ionide's updates to FCS, and so we made the decision to disable the FAKE support.
