### ISSUE TITLE
"Cannot find a manifest file." (Installation issue)

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/FAKE#2576]
### Description

As in the Readme described, is this how I attempt to install Fake on my Linux machine: 

[ _dotnet tool restore_](https://github.com/fsharp/FAKE#build-the-project)

This is the result: 

``` sh
Cannot find a manifest file.
For a list of locations searched, specify the "-d" option before the tool name.
No tools were restored.
```

### Repro steps

Please provide the steps required to reproduce the problem

1. dotnet tool restore

### Expected behavior

Fake can be installed with dotnet fake build

### Actual behavior

The above error message appears. 

### Related information 

* Operating system KaOS
* Branch rolling
* .NET Runtime, CoreCLR or Mono Version 5.0.201
* Indications of severity
* Version of FAKE (4.X, 5.X) 
* (if performance issue) Performance information, links to performance testing scripts

**Comment by ShalokShalom** [comment]
I got just informed, that the build instructions in the Readme are just to hack on the project, not to actually use it. 

I highly suggest, to include the following [Installation instructions](https://fake.build/fake-gettingstarted.html#Install-FAKE) also in the Readme.

**Comment by yazeedobaid** [comment]
The build instructions in the Readme are brief steps for the contribution guide/building FAKE locally.
As for usage details they can be found on FAKE website. Including them in Readme is more of a duplicate in my opinion from a maintenance point of view.

**Comment by ShalokShalom** [comment]
Better duplicate the information as put thousands  through the process finding that

**Comment by ShalokShalom** [comment]
Fixed in https://github.com/fsharp/FAKE/pull/2578
