### ISSUE TITLE
Update on Nuget.org

### ISSUE THREAD

**Issue by ShalokShalom** [fsharp/FAKE#2580]
It seems Nuget thinks FAKE is in coma and it doesnt know about the past 4 releases: 
https://www.nuget.org/packages/Fake

**Comment by matthid** [comment]
No that package shouldn't be used and probably will not be updated from this point forward:
![grafik](https://user-images.githubusercontent.com/1866463/113251357-71790780-92c2-11eb-8a40-3814f9639478.png)
It is marked as obsolete quite a while now.
