### ISSUE TITLE
#r "System.Management.Automation"

### ISSUE THREAD

**Issue by NimaRayyan** [fsharp/FAKE#2590]
### Description
#r "paket:
nuget Fake.DotNet.Cli
nuget Fake.IO.FileSystem
nuget Farmer 
nuget System.Management.Automation 
nuget Fake.Core.Target //"
#load ".fake/build.fsx/intellisense.fsx"

#r "System.Management.Automation"
open Fake.Core
open Farmer
open System.IO
open System.Diagnostics
open System.Management.Automation

////
 Target.create "Pack" (fun _ ->
        PowerShell.Create()
         .AddScript("& '' i have some command here '")
         //.AddParameter("BuildVersion", version)
         //.AddParameter("Debug", "")
         .Invoke()
        |> Seq.iter (printfn "%O")
        )
    

    Target.runOrDefaultWithArguments "Pack".

### Repro steps

Please provide the steps required to reproduce the problem

dotnet build fake

### Expected behavior

run without any problem
### Actual behavior

Error FS0078: Unable to find the file 'System.Management.Automation' in any of
         C:\Users\MSI\.nuget\packages\netstandard.library\2.0.3\build\netstandard2.0\ref
         C:\Users\MSI\Desktop\work\projects\AuditLocker\AuditLogManager
         C:\Users\MSI\.dotnet\tools\.store\fake-cli\5.20.4\fake-cli\5.20.4\tools\netcoreapp2.1\any\

**Comment by matthid** [comment]
This package simply seems to be incompatible with netstandard20 which currently is a requirement for packages to work in FAKE.

**Comment by NimaRayyan** [comment]
so what the solution!

**Comment by NimaRayyan** [comment]
closed
