### ISSUE TITLE
Building Windows Phone Sliverlight 8.1 app

### ISSUE THREAD

**Issue by igorkulman** [fsharp/FAKE#402]
I have a [F# FAKE script that works fine for Windows Phone 8 apps](https://gist.github.com/igorkulman/9842235). When I try to build a Windows Phone SIlverlight 8.1 app with it, I get

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\AppxPackage\Microsoft.AppXPackage.Targets(868,9): 
error APPX1639: File 'C:\Program Files (x86)\Windows Phone Silverlight Kits\8.1\\Include\WinRT\AppxManifestSchema.xsd' not found. 
Please install the Windows Software Development Kit. [C:\Users\Igor\Documents\Visual Studio 2012\Projects\Pocket\Pocket\Pocket.csproj]
```

I have Windows Software Development Kit for Windows 8.1 installed and I have not found any Windows Software Development Kit for Windows Phone Silverlight 8.1.

I have Visual Studio 2013 Professional Update 2 RC installed, so the SDK is there and building the same project from Visual Studio works just fine.

**Comment by dsyme** [comment]
Closing old issue
