### ISSUE TITLE
FAKE.Deploy.Web build fails with Mono

### ISSUE THREAD

**Issue by palpha** [fsharp/FAKE#413]
Project file should reference lib/fsi/FSharp.Core.dll. First build works, subsequent builds fail.

Pull req coming up.

    1) Building ./FAKE.Deploy.Web.sln failed with exitcode 1.
    2) FS1223: (0,0): FSharp.Core.sigdata not found alongside FSharp.Core
    3) FS0229: (0,0): Error opening binary file '/src/deploy.web/Fake.Deploy.Web/bin/FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core
    4) FS3160: (0,0): Problem reading assembly 'FSharp.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a': Error opening binary file '/src/deploy.web/Fake.Deploy.Web/bin/FSharp.Core.dll': FSharp.Core.sigdata not found alongside FSharp.Core

**Comment by dsyme** [comment]
Closing old issue
