### ISSUE TITLE
What is FAKE.IIS?

### ISSUE THREAD

**Issue by knocte** [fsharp/FAKE#421]
I'm completely new to FAKE, and I was interested in knowing if it had some facilities to deploy websites to IIS, so I googled "fake IIS", and the first result is https://www.nuget.org/packages/FAKE.IIS/2.10.7 . However, in that page I can only see a description of what FAKE is, not what FAKE.IIS.

I don't even find the sources for FAKE.IIS.

So I think these bits need polishing.

**Comment by dmorgan3405** [comment]
I attempted to add some basic information around FAKE.IIS. I will continue to add more to the documentation as needed. Or if their is a need for specific documentation please let me know.

**Comment by knocte** [comment]
I also wanted to highlight that, for newcomers like me, I also find it hard to know what's the difference between Fake.IIS and Fake.Deploy.Web (not enough basic info in https://github.com/fsharp/FAKE/tree/master/src/deploy.web). What should be used if one needs to deploy an ASP.NET web app to a Windows server?

**Comment by dsyme** [comment]
Closing old issue
