### ISSUE TITLE
Using AppVeyor Build Agent Api to send test results to build output page

### ISSUE THREAD

**Issue by PMudra** [fsharp/FAKE#427]
AppVeyor provides an api for sending messages and test results to the output page:
![image](https://cloud.githubusercontent.com/assets/84765/3052496/986fb6ca-e19b-11e3-87da-ac27bccce3c0.png)

The reference can be found here: http://www.appveyor.com/docs/build-agent-api

It would be nice if FAKE would use the api to provide information about tests on the build page of AppVeyor. I belief something similar exists to send test results to Teamcity.

**Comment by dsyme** [comment]
Closing an old inactive issue
