### ISSUE TITLE
NuGet Helper: unable to update NuGetParams on Mono (FS0193)

### ISSUE THREAD

**Issue by cdrnet** [fsharp/FAKE#436]
*This is likely an external bug (mono or oss-fsharp)*

Since I introduced the NuGet helper into my build scripts I can no longer build on Mono/Linux even though the same script works perfectly fine on .Net/Windows:

    error FS0193: internal error: Argument cannot be null.
    Parameter name: obj
It also affects the FAKE repository itself, i.e. I cannot currently build FAKE with FAKE on mono on my setup. But I managed to reduce the repro to the following (both via `mono FAKE.exe` or `fsharpi`):

    #I @"packages/FAKE/tools"
    #r @"packages/FAKE/tools/FakeLib.dll"
    open Fake
    let p = NuGetDefaults()
    //let q = { p with Version = "1.2.3" }
As is it works fine, but if the last line is uncommented it fails with the above error.  It's quite weird that it happens only on the NuGetParams record but not on any of the other record types I've been using so far.

There have been other FS0193-type issues in the past (#20, #113) but it seems to be unrelated.

Environment:
* Ubuntu 14.04 LTS (3.13.0-24-generic #47-Ubuntu SMP) / Vagrant
* mono-complete 3.2.8+dfsg-4ubuntu1
* fsharp 3.0.34+dfsg-3ubuntu1

**Comment by dsyme** [comment]
Closing as this is an old issue
