### ISSUE TITLE
Fake.Deploy: passing arguments to script

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#452]
My scenario is as follows:
- the package contains `deploy.fsx` script that has some logic depending on machine "role", something like this:

``` fsharp
match role with
| ProcessingNode, Cores16 -> 
    settings.ParallelProcessingTasks <- 10
| ProcessingNode, Cores16 -> 
    settings.ParallelProcessingTasks <- 6
| CrawlingNode, _ -> 
    settings.Proxy.Address <- Uri "http://my.com"
...
```

Now I'd like to deploy the package to a concrete machine, specifying a concrete "role", something like this:

```
Fake.Deploy.exe /deployRemote http://machine1:8080/fake c:\package.1.1.0.nupkg /role ProcessingNode
Fake.Deploy.exe /deployRemote http://machine1:8080/fake c:\package.1.1.0.nupkg /role CrawlingNode
```

`role` should be accessible from `deploy.fsx` as a command like argument (`fsi.CommandLineArgs`).

Maybe we could pass additional arguments via http headers? Any ideas? 

/cc @MorganPersson

**Comment by ashic** [comment]
@vasily-kirichenko Could you kindly give an example of how to use the parameter in build.fsx? Are there any helpers, or would we need to parse from fsi.CommandLineArgs? Guess opening up Fake would allow us to use getBuildParamOrDefault, but can't think of anything else...
