### ISSUE TITLE
FixMissingFiles does not retain F# project file order

### ISSUE THREAD

**Issue by bentayloruk** [fsharp/FAKE#454]
When the following is true:

* You run `FixMissingFiles` with an F# template project.
* None of the template project files are yet in the destination project.
* The set of template project files list (*in order*) is `[ "assemblyInfo.fs"; "Utils.fs"; "Types.fs"; "ArgInfo.fs"; "Parsers.fs"; "UnParsers.fs"; "UnionArgParser.fs" ]` (i.e. those in UnionArgParser).

The files will get added to the destination project out of order.  The reason is that the [result of `Set.ofSeq`](https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuild/ProjectSystem.fs#L92) is not in the same order.

This could be fixed fairly easily for the full file set case.  However, it would not then work for partially missing files, as they would all be added on the end.  Perhaps we should change `ProjectComparison` to return a collection of *all* the template files with a DU status in relation to the target project (e.g. Dupe | Missing | etc).

**Comment by dsyme** [comment]
Closing old issue

**Comment by bentayloruk** [comment]
@dsyme thanks Don!
