### ISSUE TITLE
Suggestion: target to update GitHub releases page

### ISSUE THREAD

**Issue by kurtschelfthout** [fsharp/FAKE#457]
Fake already has awesome one-click deployment capabilities - just update release notes and it does the rest.

One extra nice-to-have would be:

*  create a tag with the version number (I guess it can already do that through Git helpers?) 
*  beautify the releases page on GitHub with binaries/setup/etc and the description (plucked from the release notes).

So you end up with something like this: https://github.com/BayardRock/IfSharp/releases

**Comment by dsyme** [comment]
Closing old issue
