### ISSUE TITLE
"Illegal characters in path" error when executing build script

### ISSUE THREAD

**Issue by dbent** [fsharp/FAKE#501]
I have a [project](https://github.com/KerbalSystems/Ketchup) which uses FAKE for its build system. It currently uses FAKE 2.18.2 but there's a branch `topic/upgrade_fake` which uses FAKE 3.2.0, which is currently broken.

If I attempt to run the build I get an error like:
```
input.fsx(1,1): error FS0206: Problem with filename 'D:\Ketchuuild.fsx': Illegal characters in path.
```

The issue appears to be that FAKE is interpreting the `\b` (from `Ketchup\build.fsx`) in the path as an escaped backspace character. Hence why when the error is reproduced in the console it seems like `p\b` is missing (the backspace character is non-printable and it effectively erases the `p`).

We can test this theory by renaming `build.fsx` to `nbuild.fsx` which produces the error:
```
input.fsx(1,1): error FS0206: Problem with filename 'D:\Ketchup
build.fsx': Illegal characters in path.
```
Since the `\n` is now interpreted as a newline character.

This should be reproducible from a PowerShell console with the following commands:
```
PS> git clone https://github.com/KerbalSystems/Ketchup.git
PS> cd Ketchup
PS> git checkout topic/upgrade_fake
PS> ./build
```
(Note the build isn't expected to succeed despite FAKE because it requires non-distributable dependencies, but it will break before that due to FAKE).

It appears this bug was introduced in the 3.x series.

**Comment by dsyme** [comment]
Fixed by PR to FCS
