### ISSUE TITLE
Fake.Git.Commit doesn't work correctly

### ISSUE THREAD

**Issue by YcGeneralUser** [fsharp/FAKE#506]
I'm trying to use Fake.Git.Commit command with the next arguments: repository root, my message. And it doesn't work.

I had a look at the source code and it seems that I can specify only message but no files to be committed.

`sprintf "commit -m \"%s\"" message
    |> runSimpleGitCommand repositoryDir`

So `runSimpleGitCommand` takes only `message` as a command and nothing else.

**Comment by dsyme** [comment]
Closing as this is a question
