### ISSUE TITLE
Missing FSharp Dll in Linux Build

### ISSUE THREAD

**Issue by TonyAbell** [fsharp/FAKE#515]
Here is my build script...
```
#r @"packages/FAKE.3.2.16/tools/FakeLib.dll"
open Fake
let buildDir = "./build/"

Target "Default" (fun _ ->
    trace "Hello"
)

Target "Clean" (fun _ ->
    CleanDir buildDir
)
Target "MapKey" (fun _ ->
    !! "/MapKey/MapKey.fsproj"
      |> MSBuildRelease buildDir "Build"
      |> Log "AppBuild-Output: "
)
"Clean" 
  ==> "MapKey"    
  ==> "Default" 

RunTargetOrDefault "Default"
```
on windows my build dir has the following files

* FSharp.Core.dll  
* MapKey.XML  
* MapKey.exe.config
* FSharp.Core.xml  
* MapKey.exe  
* MapKey.pdb

where on my Linux box I get just
* MapKey.exe  
* MapKey.exe.config

Any ideas on what I am doing wrong.

**Comment by dsyme** [comment]
Not a FAKE issue
