### ISSUE TITLE
Unable to change default directory for FileIncludes

### ISSUE THREAD

**Issue by KristianSchmidt** [fsharp/FAKE#516]
In  src / app / FakeLib / Globbing / FileSystem.fs line 119
```
let private defaultBaseDir = Path.GetFullPath "."
```
sets the default directory that is used whenever you create a FileIncludes record. So if you do any of
```
Environment.CurrentDirectory <- dir
FileUtils.chdir dir
```
the !! operator ignores them, because the default dir was set upon loading FAKE. Is this the intended behavior? If not, the fix should be changing
```
/// Include files
let Include x = 
    { BaseDirectory = defaultBaseDir
      Includes = [ x ]
      Excludes = [] }
```
to
```
/// Include files
let Include x = 
    { BaseDirectory = Path.GetFullPath "."
      Includes = [ x ]
      Excludes = [] }
```

**Comment by dsyme** [comment]
Closing as this is an old discussion/feature suggestion
