### ISSUE TITLE
SemVerHelper.PreRelease.TryParse cannot parse valid nuget pre-release identifiers

### ISSUE THREAD

**Issue by HCanber** [fsharp/FAKE#522]
The current SemVerHelper.PreRelese parser isn't following the current [SemVer spec](http://semver.org/).
For example this is a valid prerelease string `Beta.7.z.92` that the PreRelease has problems with.

This is fine because nuget does not support those either. :)

The [Nuget prerelease spec]() says
>If there's a string there, it's a prerelease version.
>The prerelease versions are given precedence in alphabetical order (well technically lexicographic ASCII sort order).

Since SemVerHelper:PreRelease.TryParse expects a string followed by an int the following strings cannot be parsed, but they should as nuget will accept them:

- `dev20140819130924` (the digits are the date + time in [ISO8601](http://en.wikipedia.org/wiki/ISO_8601)) order as the number is to large for an int. This is something I really need!
- `dev-2014-08-19T130924`

I suggest you remove the int-parsing and just use the regex  [0-9A-Za-z-]+ as [SemVer spec](http://semver.org/) defines. The spec says that prerelease with only digits should be compared numerically, and identifiers with letters or hyphens should be compared in ascii order. However Nuget specifies ascii sort order so just treating it as a string will be fine.

**Comment by dsyme** [comment]
Fixed in #1325
