### ISSUE TITLE
Results.xml File access conflict in CCnet

### ISSUE THREAD

**Issue by matthewringer** [fsharp/FAKE#525]
I am getting the following stack trace on a plain vanilla CCNet project using both the exec and fake tasks. When I rolled back to version 2.18.2 with no changes in CCNet project everything builds happily. All 3.x.x packages I tried generated similar build result errors when run from CCNet.  

<buildresults>
<message level="Info"><![CDATA[Building project with version: 1] ]></message>
<message level="Info"><![CDATA[Shortened DependencyGraph for Target Default:] ]></message>
<message level="Info"><![CDATA[<== Default] ]></message>
<message level="Info"><![CDATA[<== Copy] ]></message>
<message level="Info"><![CDATA[<== Clean] ]></message>
<message level="Info"><![CDATA[] ]></message>
<message level="Info"><![CDATA[The resulting target order is:] ]></message>
<message level="Info"><![CDATA[ - Clean] ]></message>
<message level="Info"><![CDATA[ - Copy] ]></message>
<message level="Info"><![CDATA[ - Default] ]></message>
<target name="Clean">
<message level="Info"><![CDATA[Starting Target: Clean ] ]></message>
<message level="Info"><![CDATA[Deleting contents of ./build/] ]></message>
<message level="Info"><![CDATA[Deleting contents of myproject/MongoApp] ]></message>
<message level="Info"><![CDATA[Deleting contents of ./installer/] ]></message>
<message level="Info"><![CDATA[Finished Target: Clean] ]></message>
</target>
<target name="Copy">
<message level="Info"><![CDATA[Starting Target: Copy (==> Clean)] ]></message>
<message level="Info"><![CDATA[C:\CI\ccnet\repos\myproject\myproject\MongoApp already exists.] ]></message>
<message level="Info"><![CDATA[Finished Target: Copy] ]></message>
</target>
<target name="Default">
<message level="Info"><![CDATA[Starting Target: Default (==> Copy)] ]></message>
<message level="Info"><![CDATA[myproject.Setup Installer Build] ]></message>
<message level="Info"><![CDATA[Finished Target: Default] ]></message>
</target>
<message level="Info"><![CDATA[] ]></message>
<message level="Info"><![CDATA[---------------------------------------------------------------------] ]></message>
<message level="Info"><![CDATA[Build Time Report] ]></message>
<message level="Info"><![CDATA[---------------------------------------------------------------------] ]></message>
<message level="Info"><![CDATA[Target     Duration] ]></message>
<message level="Info"><![CDATA[------     --------] ]></message>
<message level="Info"><![CDATA[Clean      00:00:00.0630483] ]></message>
<message level="Info"><![CDATA[Copy       00:00:00.3930769] ]></message>
<message level="Info"><![CDATA[Default    00:00:00.0010390] ]></message>
<message level="Info"><![CDATA[Total:     00:00:00.5676653] ]></message>
<message level="Info"><![CDATA[Status:    Ok] ]></message>
<message level="Info"><![CDATA[---------------------------------------------------------------------] ]></message>
]]><![CDATA[Building project with version: 1
Shortened DependencyGraph for Target Default:
<== Default
<== Copy
<== Clean

The resulting target order is:
 - Clean
 - Copy
 - Default
Starting Target: Clean 
Deleting contents of ./build/
Deleting contents of myproject/MongoApp
Deleting contents of ./installer/
Finished Target: Clean
Starting Target: Copy (==> Clean)
C:\CI\ccnet\repos\myproject\myproject\MongoApp already exists.
Finished Target: Copy
Starting Target: Default (==> Copy)
myproject.Setup Installer Build
Finished Target: Default

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0630483
Copy       00:00:00.3930769
Default    00:00:00.0010390
Total:     00:00:00.5676653
Status:    Ok
---------------------------------------------------------------------

F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\CI\ccnet\repos\myproject\build.fsx]

namespace FSI_0001
  val srcDir : string
  val destDir : string
  val buildDir : string
  val installerDir : string
  val releaseDir : string

F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\CI\ccnet\repos\myproject\build.fsx]

namespace FSI_0001
  val srcDir : string
  val destDir : string
  val buildDir : string
  val installerDir : string
  val releaseDir : string

FsiEvaluationSession could not be created.
Build failed.
Error:
The process cannot access the file 'C:\CI\ccnet\BuildArtifacts\myproject\fake-results-c755903c-1865-49e8-89b3-b37baca8e7bd.xml' because it is being used by another process.

Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\CI\ccnet\BuildArtifacts\myproject\fake-results-c755903c-1865-49e8-89b3-b37baca8e7bd.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at Fake.TraceListener.NAntXmlTraceListener.getXmlWriter() in D:\code\fake\src\app\FakeLib\TraceListener.fs:line 70
   at Fake.TraceListener.NAntXmlTraceListener.Fake-TraceListener-ITraceListener-Write(TraceData msg) in D:\code\fake\src\app\FakeLib\TraceListener.fs:line 99
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Fake.TraceListener.postMessage(TraceData x) in D:\code\fake\src\app\FakeLib\TraceListener.fs:line 118
   at <StartupCode$FAKE>.$Program.main@() in D:\code\fake\src\app\FAKE\Program.fs:line 148
]]>

<buildresults>
<message level="Info"><![CDATA[
F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\CI\ccnet\repos\myproject\build.fsx]

namespace FSI_0001
  val srcDir : string
  val destDir : string
  val buildDir : string
  val installerDir : string
  val releaseDir : string

]]></message>
<message level="Info"><![CDATA[
F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\CI\ccnet\repos\myproject\build.fsx]

namespace FSI_0001
  val srcDir : string
  val destDir : string
  val buildDir : string
  val installerDir : string
  val releaseDir : string

]]></message>
<failure><builderror><message level="Error"><![CDATA[FsiEvaluationSession could not be created.]]></message></builderror></failure>
<failure><builderror><message level="Error"><![CDATA[Build failed.
Error:
The process cannot access the file 'C:\CI\ccnet\BuildArtifacts\myproject\fake-results-c755903c-1865-49e8-89b3-b37baca8e7bd.xml' because it is being used by another process.]]></message></builderror></failure>
</buildresults>

**Comment by dsyme** [comment]
Closing as there is no adequate repro
