### ISSUE TITLE
FAKE.exe boot conf -- faults when project path contains spaces 

### ISSUE THREAD

**Issue by matthewringer** [fsharp/FAKE#526]
I encountered this while attempting to bootstrap a project from a path with spaces. Paths with no spaces work as expected. 

I followed this example: http://t0yv0.blogspot.com/2013/04/introducing-fake-boot-workflow.html

PS C:\projects\dir with spaces\myproj> nuget install FAKE -ExcludeVersion
Installing 'FAKE 3.3.1'.
Successfully installed 'FAKE 3.3.1'.

PS C:\projects\dir with spaces\myproj> fake boot init
Generated conf.fsx and build.fsx

PS C:\projects\dir with spaces\myproj> fake boot conf
fake : 
At line:1 char:1
+ fake boot conf
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
stdin(0,1): error FS0078: Unable to find the file 'C:\projects\dir' in any of
 C:\projects\dir with spaces\myproj\FAKE\tools
 C:\projects\dir with spaces\myproj
stdin(0,1): error FS0078: Unable to find the file 'spaces\myproj\conf.fsx' in any of
 C:\projects\dir with spaces\myproj\FAKE\tools
 C:\projects\dir with spaces\myproj

PS C:\projects\dir with spaces\myproj>

**Comment by dsyme** [comment]
CLose this old issue
