### ISSUE TITLE
"--" operator doesn't seem to work as described

### ISSUE THREAD

**Issue by Bomret** [fsharp/FAKE#528]
Whenever I use the "--" operator after the "!!" operator the files excluded by "--" still get listed in the resulting files list.

## Example
```fsharp
!! (buildDir @@ "*.*")
  -- "*.xml"
  -- "*.pdb"
|> CopyFiles publishDir
```
All xml and pdb files still get copied. Even if I omit the pdb line, all xml files get copied.

Am I using it wrong or is there an issue?

**Comment by dsyme** [comment]
Closing old issue
