### ISSUE TITLE
[MageHelper] TrustLevel param may only be used on application manifests

### ISSUE THREAD

**Issue by Bomret** [fsharp/FAKE#529]
According to [MSDN](http://msdn.microsoft.com/en-us/library/acz3y3te(v=vs.110).aspx) the "TrustLevel" may only be used for Application manifests, but the MageHelper also uses it on deployment manifests. This leads to an exception and the build script fails.

**Comment by dsyme** [comment]
@Bomret Can you send a PR for this please? Otherwise we should close as it's old

**Comment by dsyme** [comment]
Closing old inactive issue
