### ISSUE TITLE
[MageHelper] IconPath parameter is never used

### ISSUE THREAD

**Issue by Bomret** [fsharp/FAKE#531]
The IconPath parameter of the MageParams record is never used, only the IconFile parameter. This can be confusing as someone (like me ;)) might think both are meant to be used like this:

```fsharp
IconPath = projectDir
IconFile = "app.ico"
```

I think removing the IconPath parameter is the best solution.

**Comment by dsyme** [comment]
CLosing - please send a PR if this is important.
