### ISSUE TITLE
Signing should be able to use time stamping and work on dev computers

### ISSUE THREAD

**Issue by Bomret** [fsharp/FAKE#533]
The current SignHelper does not provide options for time stamping signed assemblies and you have to check for the existence of the certificate file to use before you call it. I think the MageHelper handles the latter quite nicely by being able to provide a dev certificate that can safely be put into source control and allow to include the sign process into local dev builds. It would be nice to have a similar option for signing.
The only problem is: the current SignHelper already takes quite a lot of parameters and putting those new parameters there would make a call to it quite ugly. So it would be great to pass a parameters record like in the MageHelper that aggregates the available options. This would also make it easier to expand the call with new options later.

**Comment by dsyme** [comment]
Closing as this seems to have been covered by a PR
