### ISSUE TITLE
Properties don't work with quotes and spaces. 

### ISSUE THREAD

**Issue by jhsowter** [fsharp/FAKE#539]
<code>fake.exe targets.fsx Default -ev nunitHome="C:\test\some path\" </code>

running the above command, and outputting the variable "nunitHome" writes: 

<code>C:\test\some path"  </code>

Removing the quotes writes: 

<code>C:\test\some=path\ </code>

if there is not space in the path, everything seems to work as expected.

**Comment by dsyme** [comment]
Closing as this is not FAKE related
