### ISSUE TITLE
FAKE version of nuget pack foo.csproj?

### ISSUE THREAD

**Issue by AlexZeitler** [fsharp/FAKE#549]
Is there a FAKE version of `nuget pack foo.csproj` as well as `nuget pack foo.csproj -Build -Symbols`?

**Comment by bronumski** [comment]
@forki regardless of if this is right or not it still would be a good feature. I am also still not convinced as to why this is bad.

I am in the middle of creating a fake script for a small project to be built on appveyor. From my persepctive project build files should be easy to maintain and be able to run locally on any machine with minimal setup with very minimal knowladge of the build and deployment environment, In the past I would have used an msbuild script to compile, test and package. The appveyor yaml file then searches for the packages and uploads them. When I create nuget packages I want to do it as simply as possible and not have to do anything with build file.

In the past I would have achieved this by running the following nuget command from MsBuild:

    "..\tools\nuget\nuget.exe" pack "..\project.csproj" -OutputDirectory "..\bin" -Version 1.2.3.4 -Prop Configuration=Release -IncludeReferencedProjects -Verbosity detailed

This was achieved by having msbuild search out all projects that have a nuspec file and running the pack command against the csproj file using something like the following.

    <Target Name="Package" AfterTargets="Build">
      <ItemGroup>
        <Nuspec Include="..\src\**\*.nuspec" />
      </ItemGroup>
    
      <RemoveDir Directories="$(AssemblyOutputPath)" />
    
      <MakeDir Directories="$(AssemblyOutputPath)" />
    
      <Exec Command="&quot;$(ToolsFolder)\nuget\nuget.exe&quot; pack &quot;%(Nuspec.RootDir)%(Nuspec.Directory)%(Nuspec.Filename).csproj&quot; -OutputDirectory &quot;$(AssemblyOutputPath)&quot; -Version $(Version-File) -Prop Configuration=Release -IncludeReferencedProjects -Verbosity detailed"  />
    </Target>

So now when ever I add a nuspec file to a project it will automatically get packaged and if appveyor is configured correctly it will also get deployed to nuget. Any inter project package dependencies will be handled as the deployed version and all third party assemblies will be handled as the specific version or less. If I need to be specific about a dependency in a project then I can specify that in the nuspec file.

So far I have FAKE doing about 90% of my build, I really like it and would like to be able to get that to 99% with appveyor handling environment and deployment specific tasks.

**Comment by forki** [comment]
You can always use the generic task runner to execute nuget with the parameters you like. 

I still recommend to look into paket.

**Comment by forki** [comment]
Btw: are you sure the scenario is still not supported? I think @ilkerde a different others were working on nuget task a while ago and there were changes in regard to csproj files.

**Comment by contactsamie** [comment]
@bronumski were you able to come up with a solution/work-around that avoids the needs to explicitly have to supply the dependencies  ?

**Comment by contactsamie** [comment]
> Not really.
> 
> I want to target a csproj file, and have the NuGet task pick up its depedencies from the packages.config which is in the same folder as the csproj file (as NuGet would do via command line).
> 
> From what I understand from http://fsharp.github.io/FAKE/create-nuget-package.html, I have to specifiy each depedency "by hand" like this
> 
> ```
> NuGet (fun p -> 
> {p with
>     PublishUrl = @"c:\packages\"
>     AccessKey = "123456789"
> 
>     Authors = authors
>     Project = "MyProject"
>     Summary = "Summary"
>     Description = "Description"
>     ToolPath = "./tools/NuGet/nuget.exe"
>     WorkingDir = deployDir
>     OutputPath = deployDir
>     Version = assemblyVersion
>     SymbolPackage = NugetSymbolPackage.ProjectFile
>     Files = [
>              ("*.dll", Some "lib", None)
>             ]
>     // ...
>     Publish = false 
>     Dependencies = referenceDependencies
>                     [
>                         "Microsoft.AspNet.WebApi.Client"
>                         "Microsoft.AspNet.WebApi.Core"
>                         "Microsoft.Data.Edm"
>                         "Microsoft.Data.OData"
>                         "Microsoft.Data.Services.Client"
>                         "Microsoft.WindowsAzure.ConfigurationManager"
>                         "Newtonsoft.Json"
>                         "RavenDB.Client"
>                         "RavenDB.Database"
>                         "RavenDB.Embedded"
>                         "System.Spatial"
>                         "WindowsAzure.Storage"
>                     ]
>     })
>     "./template.nuspec"
> ```

@AlexZeitler any luck with not needing to specify each dependency "by hand" ?

**Comment by bronumski** [comment]
@contactsamie - It has been a while since I looked at this but yes I did get this to work. However recently I have been using .net core which allows for an even cleaner implementation.

Here are two examples of doing it with and without .net core. Also note that this project is using the older Fake framework but I have also done something similar with the Fake 5.

**Before .net core**
https://github.com/bronumski/HealthNet/blob/release/1.1.0.50/Build.fsx#L66

1. Create a nuspec file for each project you want to package with the minimum settings defined (See one of mine for details)
2. Search for and loop through all the projects with a nuspec file and find there related csproj file
3. Run the NuGetPack command on each of the projects.

**After .net core**
https://github.com/bronumski/HealthNet/blob/release/1.2.81/Build.fsx

1. Loop through all the csproj files (I package up all projects now so don't need a nuspec file as a marker anymore)
2. Call the DotNetCli.Pack command

With the new .net core project structure there are also some project xml flags you can also use to identify projects that need to packaged or not but I found this way easier for me.

Hope that helps.

**Comment by contactsamie** [comment]
> @contactsamie - It has been a while since I looked at this but yes I did get this to work. However recently I have been using .net core which allows for an even cleaner implementation.
> 
> Here are two examples of doing it with and without .net core. Also note that this project is using the older Fake framework but I have also done something similar with the Fake 5.
> 
> **Before .net core**
> https://github.com/bronumski/HealthNet/blob/release/1.1.0.50/Build.fsx#L66
> 
> 1. Create a nuspec file for each project you want to package with the minimum settings defined (See one of mine for details)
> 2. Search for and loop through all the projects with a nuspec file and find there related csproj file
> 3. Run the NuGetPack command on each of the projects.
> 
> **After .net core**
> https://github.com/bronumski/HealthNet/blob/release/1.2.81/Build.fsx#L52
> 
> 1. Loop through all the csproj files (I package up all projects now so don't need a nuspec file as a marker anymore)
> 2. Call the DotNetCli.Pack command
> 
> With the new .net core project structure there are also some project xml flags you can also use to identify projects that need to packaged or not but I found this way easier for me.
> 
> Hope that helps.

Thank you  @bronumski  That helped a lot
