### ISSUE TITLE
Broken build after upgrade to 3.5.8

### ISSUE THREAD

**Issue by provegard** [fsharp/FAKE#557]
After upgrading to Fake 3.5.8, my build fails on Nuget package greation. My nuspec contains:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        ...
    </metadata>
    <files>
        <file src="bin\*.dll" target="bin" />
        ...
    </files>
</package>
```

Previously, paths in `files` were resolved relative to the location of the nuspec file, but that doesn't seem to be the case anymore, because the error I'm getting says that the it cannot find the `bin` path.

To clarify, the path to the nuspec file is `src\Proj\deploy.Proj.nuspec`, and the `bin` directory resides at `src\Proj\bin`.

**Comment by dsyme** [comment]
Close this old issue
