### ISSUE TITLE
Fake Deploy

### ISSUE THREAD

**Issue by drusellers** [fsharp/FAKE#569]
Is there any desire to port deployment operations from chucknorris/dropkick to FAKE.Deploy? I have a ton of actions in there to do various things around the windows eco system. A compiled language was nice but I have always been hounded about the lack of a scripting capability. I'm thinking that long term there might be value in porting the dropkick tasks or some how making them available in an F# manner. Especially, given your remote runner capabilities. :+1: 

- DSN (data source name) management
- MSMQ
- IIS
- registry
- roundhouse - (database migrations)
- windows services
- File ACL
- SQL Perms
- MSMQ perms
- and more https://github.com/chucknorris/dropkick/tree/master/product/dropkick/Tasks

Any one who sees this, dropkick is an apache license, by all means feel free to copy/port/whatever if its useful. If nothing else, its pretty solid documentation on how to get something done in windows.

**Comment by dsyme** [comment]
Closing old conversation
