### ISSUE TITLE
Get current url

### ISSUE THREAD

**Issue by asherjawad** [fsharp/FAKE#573]
is there any way to get current url in f# i have written 

open IntelliFactory.WebSharper
open IntelliFactory.WebSharper.Html
open IntelliFactory.WebSharper.Html5
open IntelliFactory.WebSharper.JQuery

[<JavaScript>]
module getCurrentUrl =
    let url = Window.Self.Location.Href 

but its giving error in implmentation

**Comment by dsyme** [comment]
Close this old issue
