### ISSUE TITLE
Cannot #load fsx files in a sub-directory from main build script

### ISSUE THREAD

**Issue by mavnn** [fsharp/FAKE#583]
This may be related to #476

In [Build.Tools](http://15below.github.io/Build.Tools/) we assume that the provided build scripts will be checked out as a sub-module of your main project (let's assume it's called "tools").

If we run the default Core.fsx it ``#load``s a series of helper scripts in the same directory. This works fine.

If, however, we ``#load`` the helper scripts from a override build script in the parent folder it fails with ![error message](https://s3.amazonaws.com/uploads.hipchat.com/44491/299808/7U0swMOjGDsNuAC/upload.png)

Any ideas? Is this a bug or are we doing something wrong?

**Comment by dsyme** [comment]
Closing this old issue
