### ISSUE TITLE
FSI Shadowcopying side-effects

### ISSUE THREAD

**Issue by colinbull** [fsharp/FAKE#584]
When running a FAKE script via FSI with shadow copying turned some things break. 

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/fsharpMake">@fsharpMake</a> any ideas why my MSBuild works from cmdline but not FSI? &quot;Could not load file or assembly &#39;Microsoft.Web.XmlTransform 2.1.0.0&quot;</p>&mdash; Isaac Abraham (@isaac_abraham) <a href="https://twitter.com/isaac_abraham/status/529660926329626625">November 4, 2014</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

I'm not sure specifically why shadow copying breaks this as the relative references with in the project file should still be correct. since we aren't loading those dll's when running the MSBuildHelper. The only thing I can think of at the minute is this has the effect of changing the actual working directory of FakeLib.dll. But this is only a guess, I need to experiment. If this is true then this could have undesirable side-effects for anything that shells out processes. 

*Note:* There is a simple workaround. Simply set shadowcopy off.

* Visual Studio - Options -> F# Tool -> F# Interactive -> Shadow Copy Assemblies = false
* CmdLine - `fsi.exe --shadowcopyreferences-`

**Comment by dsyme** [comment]
Closing old issue
