### ISSUE TITLE
After clean/build assemblies with changes are stale

### ISSUE THREAD

**Issue by brodyberg** [fsharp/FAKE#585]
I am using Fake to find and build all the cs and fsproj's in my git repo. However, for some reason when I open my build directory to inspect the output built there I see assemblies that do not have updates but should. These stale assemblies should have fresh changes. Meanwhile other assemblies with no changes build fresh every time I run fbuild. 

I found that the only thing that gets a stale assembly that should build fresh to do so is to change the name of the assembly in the project properties. 

This problem made me realize that while I had thought fake was building several assemblies with new changes that was not in fact the case. 

When I examine the build log I see this: 

        Copying file from "obj\Debug\Foo.dll" to "S:\repo\project\build\Foo.dll".

That statement appears to be misleading in several respects though: 

* The Foo.dll that shows up in build/ is from 10/23, not today
* The Foo.dll in obj\debug *is* from today (right now in fact)
* There is no Foo.dll from 10/23 on my machine until I fbuild
* Not only that last fact, but the Foo.dll from 10/23 is a legitimate example of the state of the assembly on October 23rd (as verified by ILSpy.exe)

No change in this behavior was observed when I ran clean or build debug operations from Visual Studio. All through this a pre-requisite step of building in Fake is the Clean target: 

    "Clean"
      ==> "BuildSrc"
      ==> "Default"

Here is BuildSrc: 

    Target "BuildSrc" (fun _ ->
        !! csProjGlob 
          ++ fsProjGlob
          |> MSBuildDebug buildDir "Build"
          |> Log "AppBuild-Output: "
    )

As you can see, both targets are nearly direct copies from the "get started" documentation. 

What change in use do you recommend to cause Fake to produce assemblies which reflect the source code into the build folder?

Thanks, 

Brody

**Comment by dsyme** [comment]
Closing as no repro given
