### ISSUE TITLE
Deployment agent crash

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#590]
When I deploy a package with the script below (which fails because this website does not exist) the agent service process is terminated. Is that an expected behavior?

http://gyazo.com/384e413a1b1500574aad9de949143cda

#I @"tools\FAKE\tools"
#r "FakeLib.dll"
#r "Fake.IIS.dll"

open Fake
open Fake.IISHelper

Target "Stop" (fun _ ->
    AppCmd "stop site non-existence-website.com"
)

"Stop"

Run "Stop"

**Comment by dsyme** [comment]
Closing old issue
