### ISSUE TITLE
--single-target is not working

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#594]
It always execute the dependencies. I have tried all possible combinations.

**Comment by cdroulers** [comment]
Works for me in version 3.27.5 with both `-st` and `--single-target`

**Comment by Stift** [comment]
I can confirm the problem. Normally `-st` is working, but when I define an extra build parameter it is executed in the target order and `-st` is ignored.

**Comment by hiscodeness** [comment]
I confirm the problem too. Easily reproducable by calling e.g. `FAKE.exe Build -st param=1`.

**Comment by smoothdeveloper** [comment]
also hitting this issue whenever I specify a parameter it ignores -st, is there a workaround?

**Comment by cdroulers** [comment]
--single-target works great for me

**Comment by smoothdeveloper** [comment]
@cdroulers Am I doing something wrong?

```
> build -v
FakePath: C:\work\gitsvnclone\packages\FAKE\tools\FakeLib.dll
FAKE - F# Make "4.11.0"
> build generatecode buildMode=Debug --single-target
Building project with version: LocalBuild
Shortened DependencyGraph for Target generatecode:
<== generatecode
   <== buildshared
   <== buildresources
   <== warmuplocaldatabase

The resulting target order is:
 - buildshared
 - buildresources
 - warmuplocaldatabase
 - generatecode
Starting Target: buildshared
...
```

**Comment by cdroulers** [comment]
No idea. I use fake.exe and --single-target and it works. But with -st, it
doesn't work.

**Comment by mynkow** [comment]
Can you hive us working sample?

-----Original Message-----

**Comment by bentayloruk** [comment]
I think this will work for you if you change the command line to use the "modern" options.  Your current usage is a mix of the two.  This should work.

`.\bin\tools\FAKE\tools\Fake.exe test.fsx %TARGET% -st -ev applicationName MyApp`

There are some [docs here too](http://fsharp.github.io/FAKE/commandline.html).

**Comment by dsyme** [comment]
@mynkow can we close this issue?

**Comment by smoothdeveloper** [comment]
It seems #1301 will finally solve this :smile:

**Comment by mynkow** [comment]
I've just tested this. It is working now. Thank you.

**Comment by sdluxeon** [comment]
That escalated quickly :smiley:
