### ISSUE TITLE
Output of vcxproj is not copied to build directory

### ISSUE THREAD

**Issue by brodyberg** [fsharp/FAKE#596]
FAKE can build *.vcxproj and output appears as expected in the project's local Release folder (ex. foo.lib). However, foo.lib does not then appear in the FAKE build directory.

**Comment by zsims** [comment]
We looked at doing something similar, but ended up setting OutDir in a property sheet (shared codebase). You should be able to set OutDir (as it's "settable"), it actually defines $OutputPath (I suspect this is from when MS went from VSBuild to MSBuild).

From C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120
```xml
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" TreatAsLocalProperty="OutDir">

<!-- snip -->

  <!-- Ensure that IntDir and OutDir will contain proper trailing slash.  Also set the flag to warn the user.  -->
    <IntDirTrailingSlashWarning Condition="'$(IntDir)' != '' and !HasTrailingSlash('$(IntDir)')">true</IntDirTrailingSlashWarning>
    <OutDirTrailingSlashWarning Condition="'$(OutDir)' != '' and !HasTrailingSlash('$(OutDir)')">true</OutDirTrailingSlashWarning>
    <IntDir Condition="'$(IntDir)' != '' and !HasTrailingSlash('$(IntDir)')">$(IntDir)\</IntDir>
    <OutDir Condition="'$(OutDir)' != '' and !HasTrailingSlash('$(OutDir)')">$(OutDir)\</OutDir>

    <!-- Correct OutputPath as it may be out of sync with OutDir -->
    <OutputPath>$(OutDir)</OutputPath>
  </PropertyGroup>

```

You should be able to set OutDir in the FAKE MSBuild stuff (untested):

```fsharp
MSBuild "MyOutputDir" "MyTarget"  [ "OutDir", "MyOutputDir" ] [ "./MySolution.sln" ]
```
Should this also be set when OutputDir is set?

**Comment by matthid** [comment]
Please re-open or create a new issue/pr if this is still relevant.
