### ISSUE TITLE
MSB4057: The target “Build” does not exist in the project

### ISSUE THREAD

**Issue by halcwb** [fsharp/FAKE#604]
When I let appveyor build my project, I get a: MSB4057: The target “Build” does not exist in the project. I know how to fix this (http://nikosbaxevanis.com/blog/2013/10/04/how-to-configure-msbuild-to-locate-the-f-number-build-targets/). I even wrote a command line tool that will automatically fix the fsproj files. Then it builds fine on apveyor. However, the build script then fails on the local machine. Isn't there a possibility to add the path the correct build target using Fake?

**Comment by kasperhj** [comment]
The link can be found here: http://blog.nikosbaxevanis.com/2013/10/04/how-to-configure-msbuild-to-locate-the-fsharp-build-targets
