### ISSUE TITLE
Unable to deploy to Fake.Deploy.3.11.4

### ISSUE THREAD

**Issue by diskdan** [fsharp/FAKE#608]
Hi,

We have updated to the new version and it seems that http requests aren't been listened to correctly.  The command window looks OK:

![image](https://cloud.githubusercontent.com/assets/5795892/5451626/42610ec6-8512-11e4-9ae4-616b24294e7c.png)

However when a deploy is carried out we get a 404 error:

![image](https://cloud.githubusercontent.com/assets/5795892/5451673/bb4f15c6-8512-11e4-8734-ddcaf32c7f66.png)

Apologies -  my Windows is unfortunately in German.

Thanks,

Daniel

**Comment by dsyme** [comment]
@diskdan can we close this issue?

**Comment by diskdan** [comment]
Hi Don,

Yes, apologies.

Cheers,

Daniel
