### ISSUE TITLE
Replacements in ReplaceInFiles should accept regex patterns

### ISSUE THREAD

**Issue by ryanewtaylor** [fsharp/FAKE#622]
Currently, it appears the patterns used in ReplaceInFiles must match the string you want to replace exactly. However, it would be very helpful if instead of an exact match the regular expressions could be used in the pattern matching. This would enable, for instance, replacing version strings in arbitrary files with an expression akin to:

````
    !! ".\**\AssemblyInfo.cs"
        |> ReplaceInFiles [("[\d]\.[\d]\.[\d]\.[\d]", version)]

    // replace Major.minor.revision.build with the desired version
````

**Comment by forki** [comment]
This would be a breaking change, right?
How about a new function which does this?

I mark this as up-for-grabs if you are interested please send a PR.

**Comment by ryanewtaylor** [comment]
Yeah. That  might be a breaking change. Perhaps an additional argument with a default value could be added that defaulted to the current behavior but when provided would use regex to find matches? Then again, perhaps a separate ReplaceInFilesRegex would be cleaner.

**Comment by ryanewtaylor** [comment]
@forki, I am not sure of the proper protocol for closing F# - FAKE issues. I believe this issue was initially met by PR #649. May I close this issue or would you prefer to do so?

**Comment by forki** [comment]
You can just close issues when things are fixed. Thanks
