### ISSUE TITLE
ReplaceInFiles alters the encoding of the processed files to ANSI

### ISSUE THREAD

**Issue by ryanewtaylor** [fsharp/FAKE#623]
I was attempting to use ReplaceInFiles to alter a version string in arbitrary files including but not limited to AssemblyInfo.cs files (produced by Visual Studio). The code I ran was:

```
Target "StampAssemblyVersion" (fun _ ->
    !! ".\**\AssemblyInfo.cs"
    |> ReplaceInFiles [("0.0.0.0", version); ("1.0.0.0", version); ("4.0.0.0", version)]
)
```

Prior to running this the AssemblyInfo.cs files are UTF-8 encoded according to Notepad++ and KDiff3. After running this the encoding on the files is ANSI as see in Notepad++ and as System in KDiff3. I am running on Windows 7 (64 bit). This also has the side effect of "corrupting" certain characters like the copyright symbol © as it does not display correctly when interrupted via ANSI encoding in Notepad++.

**Comment by zsims** [comment]
Per EnvironmentHelper.fs, you can set the IO encoding:

```fsharp
/// Contains the IO encoding which is given via build parameter "encoding" or the default encoding if no encoding was specified.
let encoding = 
    match getBuildParamOrDefault "encoding" "default" with
    | "default" -> Text.Encoding.Default
    | enc -> Text.Encoding.GetEncoding(enc)```

There's a few places that use Encoding.Default, but this isn't one of them. I'm happy to raise a PR to make it explicit.

**Comment by matthid** [comment]
It now keeps the encoding of the existing file if possible and if we can detect that properly.
