### ISSUE TITLE
Unable to set MaxCpuCount

### ISSUE THREAD

**Issue by stonesbg** [fsharp/FAKE#624]
I could be doing something completely wrong here but when I try and set the MaxCpuCount

MSBuildDefaults <- { MSBuildDefaults with MaxCpuCount = Some 4}

apm_build.fsx(27,62): error FS0001: This expression was expected to have type
    int option
but here has type
    int

I am only at the starting line with F# and FAKE so might be an easy question.

**Comment by mexx** [comment]
The type of `MaxCpuCount` field is `int option option`.
So the correct setting would be
```
MSBuildDefaults <- { MSBuildDefaults with MaxCpuCount = Some (Some 4) }
```

The outer option indicates whether `/m` switch should be added to the argument list.
The inner one controls the value for the switch, in your example `/m:4`, if this inner option is `None`, only `/m` is added to the argument list.

The default default is `Some None` which adds `/m` to the argument list of `MsBuild`

**Comment by mausch** [comment]
My bad here. Nesting option types like this is a smell, it should be a separate type explicitly naming the options, but back when I wrote this years ago ( https://github.com/fsharp/FAKE/commit/537757392cad0582c2d7a24d3f7f4ce1b95fbe4d ) I didn't know any better.
Changing this now would break clients, but maybe we could add another field to the record and mark `MaxCpuCount` as obsolete?

**Comment by rhughesjr** [comment]
I just wrestled with this myself. I like the idea of obsoleting it and creating a more usable property

**Comment by dsyme** [comment]
Closing old issue
