### ISSUE TITLE
sbt like shell and tracking features

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#625]
One of the biggest gripes I have with Fake currently is the 5s+ boot up time. This means that even Visual Studio can build things faster than Fake, due to the latter having to load the runtime everytime. Sbt has an arguably first start time. But it takes a few steps to mitigate this. 

* sbt with arguments executes like Fake (i.e. runs a task).
* sbt without arguments launches a shell. Within the shell you ca type commands. (i.e. >build will run the build task). The only catch is if your build file changes, you need to issue >reload to pick up changes in the build file itself. 

All of this happens without having to load the runtime, as it's already been loaded. As such, after initial start, the code / build [/test] cycle is considerably faster than Fake. I believe on first start up for a project, it also caches some files, and as such, subsequent starts are faster than the initial start.

One more feature that's quite cool in sbt is the idea of file tracking. This is achieved by specifying a ~ in front of the task name. For example:
* sbt [gets you into shell]
* ~test

That effectively puts a watch on things that test depends on. And if there're any file changes, it will rerun the dependencies and rerun the task. For example, if I have a foo.sln with a foo.fsproj and foo.test.fsproj, and by "build" task builds the solution and "test" runs the tests (with test depending on build), then issuing "~test" will set up a watch so that any change in foo.fsproj that results in foo.test.fsproj tests to run again will automatically run when the file is saved. This is **immensely** helpful when doing plain text editor based development (and might even be something IDEs use for tooling). 

I believe these sbt like features will make Fake a lot smoother to use.

**Comment by leonidborisenko** [comment]
> One of the biggest gripes I have with Fake currently is the 5s+ boot up time.

Sorry for stealing your issue, but it could be partially mitigated right now by precompiling build script. It works for me with using of small shell script. I described it in #646.

**Comment by dsyme** [comment]
Closing old suggestion in spring cleaning
