### ISSUE TITLE
Allow an easy way to NGEN Fake

### ISSUE THREAD

**Issue by forki** [fsharp/FAKE#626]
@ashic reported slow startup times for FAKE. As @dsyme suggested NGEN.exe can help.

We should develop a `fake install` command which calls NGEN on itself.
Unfortunately this requires admin - otherwise we could always NGEN.

**Comment by forki** [comment]
@asic FAKE 3.14.1 has the new experimental `fake install` command. Can you please run it from administrator promt and see if subsequent fake calls are faster for you?

**Comment by ashic** [comment]
Just ran it. ngened successfully with warning about the compiler hard bind. However, running fake build.fsx still had a 5s+ startup time. Tried to fake install again, and was told it's already been ngened. Should not I've got VS2012-2015 installed on the machine. Could it be version / tool folder issues?

**Comment by forki** [comment]
I think the path is OK. I'll have to try a couple of different things. Will
probably ask you soon to retry ;-)

Thanks for your patience ;-)

**Comment by dsyme** [comment]
To make the warning go away please submit a PR to FCS to remove these lines:

https://github.com/fsharp/FSharp.Compiler.Service/blob/7790ea2709d8b8d750957b6cd6b98bc987d02d37/src/fsharp/fscopts.fs#L41
https://github.com/fsharp/FSharp.Compiler.Service/blob/a44de8f487ef2061141842e0a0be72bc3bbb7f35/src/fsharp/fsi/fsi.fs#L81
https://github.com/fsharp/FSharp.Compiler.Service/blob/a44de8f487ef2061141842e0a0be72bc3bbb7f35/src/fsharp/fsi/fsi.fs#L82
https://github.com/fsharp/FSharp.Compiler.Service/blob/7e1faeffecd47f6d40b14c262de04c1368390f86/samples/FscExe/FscMain.fs#L287
