### ISSUE TITLE
Feature Request: Provide an XmlStrip method to remove a node from an xml document via XPath

### ISSUE THREAD

**Issue by ryanewtaylor** [fsharp/FAKE#628]
I have a need to remove an XML node from a document during the deployment phase. I attempted to use XmlPoke to remove the element but this is not supported by XmlPoke as that only changes the value of a node. It would be handy to have an XmlStrip method to remove an xml node from an xml document.

Sample code is provide below though it would require additional checks and balances for production ready code.

```
let XmlStrip (fileName : string) xpath =
    let doc = new XmlDocument()
    doc.Load fileName
    let node = doc.SelectSingleNode xpath
    node.ParentNode.RemoveChild node |> ignore
    doc.Save fileName
```

**Comment by dsyme** [comment]
Closing old suggestion in spring cleaning
