### ISSUE TITLE
Latest FAKE crashes with exception

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#635]
![image](https://cloud.githubusercontent.com/assets/873919/5837167/c93986c0-a18d-11e4-9ba8-cd76243e11f4.png)

**Comment by forki** [comment]
Oh this doesn't look good.  Will investigate.

**Comment by vasily-kirichenko** [comment]
On 3.14.0 everything is ok. Switched to this version for now.

**Comment by forki** [comment]
mhm strange. Can't reproduce. Is UnionArgParser.dll in the packages/FAKE/tool fodler?

**Comment by mattsonlyattack** [comment]
UnionArgParser is now Argu and rev'd to 1.0, I've only been looking at it a few minutes now

**Comment by mattsonlyattack** [comment]
Tried to see if going the paket route for Argu would do something different for me, different error now... Hmmm.

**Comment by mattsonlyattack** [comment]
Nevermind, that was 50 levels of node_module hell. Paket seems to install Argu in a way that FAKE appreciates.
