### ISSUE TITLE
Windows vs. Unix path separators

### ISSUE THREAD

**Issue by stephensong** [fsharp/FAKE#639]
All the examples and help etc show paths with forward slashes, but I find that I need to change to (double) backslashes to get them to work on my Windows 7 machine.  Is this a known issue?  Can it be addressed?

**Comment by cdrnet** [comment]
Forward slashes work fine for me on Windows, but you can also use the `@@` operator which does it properly with `Path.Combine`.

**Comment by zsims** [comment]
There's some tools that refuse to let you mix them. We run installshield from FAKE, and it will not work with mixed separators (other tools are fine). So preferably don't mix them, what fails to work?
