### ISSUE TITLE
Introducing JSON support into FakeLib

### ISSUE THREAD

**Issue by gshackles** [fsharp/FAKE#641]
I'm working on a new helper that I'd like to contribute back to FAKE, but this helper will require parsing a JSON response from a service. I noticed that there's currently no JSON support in FakeLib, so wanted to make sure I didn't go ahead and try to add any dependencies into there that are unwelcome.  I did notice that Json.NET is used in [Fake.Deploy.Lib](https://github.com/fsharp/FAKE/blob/master/src/app/Fake.Deploy.Lib/Json.fs#L4).

Any thoughts on what to use for FakeLib? Json.NET? JSON type provider?

**Comment by forki** [comment]
I guess JSON.Net is fine

**Comment by gshackles** [comment]
![image](https://cloud.githubusercontent.com/assets/196182/5946734/18de5566-a706-11e4-8191-1ed361e00765.png)
