### ISSUE TITLE
Fake.Deploy: FsiEvaluationSession locks active deploy

### ISSUE THREAD

**Issue by xkrt** [fsharp/FAKE#642]
Our script.fsx inside deploy package uses assemblies inside package with #r "libs/SomeLib.dll".

First deploy just fine, but second with same package fails on step "Deleting contents of e:\FAKE\src\app\Fake.Deploy\bin\Debug\.\deployments/PRJ\active".
Libs inside active/libs dir cant be moved, Fake.Deploy locks them (thru FsiEvaluationSession, I guess).

Adding /shadowcopyreferences to commonOptions (FSIHelper.fs) doesnt solve that problem.

**Comment by xkrt** [comment]
Looks like this FSharp.Compiler.Service issue https://github.com/fsharp/FSharp.Compiler.Service/issues/292

**Comment by vasily-kirichenko** [comment]
fixed in https://github.com/fsharp/FAKE/pull/653
