### ISSUE TITLE
VS2015, no "enable package restore" and tutorial

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#657]
The getting started tutorial looks to use .nuget\nuget.exe to download fake. This assumes nuget.exe is there. However, starting VS2015, the option to enable package restore is gone, and the normal route is to have automatic package resolution. However, this makes it cumbersome to download fake properly. What's the recommended workaround?

The tutorial I mention is this one:
http://fsharp.github.io/FAKE/gettingstarted.html

**Comment by forki** [comment]
nuget.exe is a command line tool. this has nothing to do with VS. I'dont really understand that question.

(I'd still recommend to use paket.exe instead ;-) )

**Comment by ashic** [comment]
Previously, (and most of our projects do this), you "enabled package restore" in VS and it created the .nuget folder and dropped nuget.exe in there. The tutorial specified above relies on nuget.exe to be present there. However, since nuget.exe is no longer created, dropping nuget.exe into a .nuget folder is a manual step. I was wondering if the bat file in the demo could be updated to automatically download and put nuget.exe in there.

Paket is on the menu. But will need more buy in (and is a separate thing altogether) ;)

**Comment by forki** [comment]
Ok. so you suggest we rewrite that part and explain how to download nuget.exe? would this be enough?

**Comment by ashic** [comment]
Pretty much. Although it'd be better if the example .bat file automatically did that. It's easy in powershell, and linux. Windows cmd used to have bitadmin, but that's apparently deprecated.

**Comment by matthid** [comment]
The getting started page now suggests paket, so I don't think this is still relevant. Feel free to open a new issue or comment here.
