### ISSUE TITLE
Broken nuget package

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#663]
hello, we get the error bellow for all of our projects. Can you please take a look?

%NUGET% "install" "FAKE" "-OutputDirectory" "%TOOLS_PATH%" "-ExcludeVersion" "-Prerelease"

Uninstalling 'FAKE 3.14.0'.
Successfully uninstalled 'FAKE 3.14.0'.
WARNING: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 1, position 2927.
Unable to find version '3.17.7' of package 'FAKE'.

**Comment by forki** [comment]
mhm strange. we have 88 successful downloads and it works in our infrastructure. Could you please try to clean your tools folder and try again?

**Comment by mynkow** [comment]
Yep, I did it several times. What else I can do to find what is the actual problem

**Comment by forki** [comment]
instead of using -prerelease could you try to use -version and find the last version that works for you?

**Comment by mynkow** [comment]
It is to exclude prerelases. This is the Build.cmd from our project which fails.

````
@echo off

SETLOCAL

SET TOOLS_PATH=.\bin\tools
SET NUGET=%TOOLS_PATH%\NuGet\NuGet.exe
SET FAKE=%TOOLS_PATH%\FAKE\tools\Fake.exe

echo Downloading latest version of NuGet.exe...
IF NOT EXIST %TOOLS_PATH%\NuGet md %TOOLS_PATH%\NuGet
@powershell -NoProfile -ExecutionPolicy unrestricted -Command "$ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest 'https://www.nuget.org/nuget.exe' -OutFile '%NUGET%'"

echo Downloading latest version of Fake.exe...
%NUGET% "install" "FAKE" "-OutputDirectory" "%TOOLS_PATH%"````

I will find the latest working version now...

**Comment by mynkow** [comment]
3.17.6 works just fine. So it is only the next one which has problems.

**Comment by recumbent** [comment]
I'm seeing exactly the same problem using:

```.\src\tools\NuGet.exe install fake```

3.17.6 is fine, 3.17.7 gives:

```
WARNING: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 1, position 294
9.
Unable to find version '3.17.7' of package 'fake'.
```

**Comment by forki** [comment]
ok. thanks. 
what about  3.17.8 ?

**Comment by recumbent** [comment]
That works! (Now to remove the temporary workround!)

**Comment by mynkow** [comment]
It works now. Thank you for the quick fix!

Would you please share with us what was the issue. 10x

**Comment by forki** [comment]
no idea. I pushed exactly the same code (the diff to 3.17.6 was already almost zero).
