### ISSUE TITLE
Solution build breaking change

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#665]
With one of these two commits https://github.com/fsharp/FAKE/commit/1e0fea5f0af012370d1c7497a02cb06e415a5d54
https://github.com/fsharp/FAKE/commit/e47cca45a1276b5ad83dc366cc7062949fff3ea5

it is impossible to build our projects. It tries to find packages.config but not all projects actually use nuget.

Is there an option to suppress nuget restore? Or revert these commits?

````
Target "Build" (fun _ ->
    !! appProjectFile
        |> MSBuildRelease buildDir "Build"
        |> Log "Build-Output: "
)

**Comment by forki** [comment]
I can revert, but are you sure 1e0fea5 is a bad commit? It looks pretty harmless.

**Comment by mynkow** [comment]
I am trying to find why building a solution MSBuildRelease looks for packages.config

**Comment by mynkow** [comment]
Sorry @forki It was a false alarm.
