### ISSUE TITLE
Paket helper overriding version for project packages

### ISSUE THREAD

**Issue by mavnn** [fsharp/FAKE#666]
The point of project templates is that information like versions can be lifted from the project. The current paket helper always overrides the version parameter, breaking this completely.

This is a particular problem on solutions with many projects with many different versions.

**Comment by mavnn** [comment]
I'd suggest making the version field an option and not supply the parameter to paket if it's ``None``, but I'm up for other suggestions.

**Comment by forki** [comment]
Sounds reasonable. Probably the same with releasenotes

**Comment by mavnn** [comment]
Want me to add that, or are you in there already?

**Comment by forki** [comment]
I can do it. Just wondering if we should use null instead. Would be backwards compatible and aligns with the already existing helpers

**Comment by mavnn** [comment]
Eeeeew. I'll leave it to you :)

**Comment by forki** [comment]
actually it's not that bad here.
You just don sepcify a version in build.fsx. You'll never see that null

**Comment by mavnn** [comment]
Ha. Thanks!

**Comment by forki** [comment]
maybe it's a sign that this issue is #666

**Comment by forki** [comment]
released
