### ISSUE TITLE
Paket helper: If endpoint is reset to <emptystring> in fake script, the resulting aket push command is not valid

### ISSUE THREAD

**Issue by Vidarls** [fsharp/FAKE#667]
Paket helper: If endpoint is reset to <emptystring> in fake script, the resulting command is not valid.

There should be some way of clearing endpoint to avoid getting the default `/api/v2/package` 
Trying to do this in the build script will break the call to paket as the endpoint param is always passed.

**Comment by forki** [comment]
you could apply the same pattern as https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/PaketHelper.fs#L58 - would that help!?

**Comment by Vidarls** [comment]
It would help that the command would be valid.

Not sure what would happen in Paket though, will not giving the endpoint resolve to the default `/api/v2/package/`?

**Comment by forki** [comment]
ok. let's start from the beginning.

you don't want to specify an endpoint and you don't want it to default to /api/v2/package/? Is that correct?
Yes then we need to change something FAKE and Paket. Not sure what the best way is.

**Comment by Vidarls** [comment]
Not sure this is worth pursuing if it means making big changes due to my fringe needs.

In my case it occured cause I have the complete address to the endpoint in the URL, and I did not want the default endpoint stuff appended to it. I could just split it into URL: __http://host__, Endpoint : __/The/rest__, and as such go on happily.

But I feel there might be a violation of _the principle of least surprise_ somewhere here.

**Comment by forki** [comment]
I agree we should only append the default endpoint if we detect that there is no endpoint in the url.

I suggest the following changes:

1) In Paket we decide if we have to append the default endpoint if no endpoint was given. But how?
2) In Fake we only call paket with the endpoint if someone explicitly specified an endpoint.

I can do 2) can you help with 1)?

**Comment by Vidarls** [comment]
Sure, but how can we reliably know?

We could look at what Nuget does: https://github.com/fsprojects/Paket/pull/651#issuecomment-75917963 wich seems to be: `if Host-only then url + endpoint else url`
No sure how this would fork for MyGet as @maartenba mentions in https://github.com/fsprojects/Paket/pull/651#issuecomment-75838901 myget requires the api part, but the streams are given as this : https://www.myget.org/F/aspnetwebstacknightly/ 

Not quite sure how to proceed without giving someone somewhere a nasty surprise.

Should we start with a naive  `if Host-only then url + endpoint else url` then proceed with edge cases as they are reported?

**Comment by forki** [comment]
yes let's start simple. It seems we can't solve every quirk in one go.

**Comment by maartenba** [comment]
MyGet users typically know to append this manually, so feel free to proceed that way without MyGet specific conventions.

**Comment by forki** [comment]
(the FAKE part is done)

**Comment by Vidarls** [comment]
Ok, I will have a look at the Paket part this evening

**Comment by Vidarls** [comment]
Then I suppose we can close this?
