### ISSUE TITLE
source index not working because of %%var%%

### ISSUE THREAD

**Issue by ctaggart** [fsharp/FAKE#678]
![image](https://cloud.githubusercontent.com/assets/80104/6548649/144ed0c2-c5bd-11e4-9200-8301f2d13bce.png)

https://github.com/ctaggart/SourceLink/issues/62

The source index is ending up with a `%%var2%%` instead of `%var2%`. I haven't been able to reproduce locally yet. Any idea which version of the F# compiler is being used in these builds?

**Comment by ctaggart** [comment]
I was not able to reproduce the problem on my machine with the exact same commit.

```
git clone https://github.com/fsharp/FAKE.git
cd .\FAKE
git checkout 38986fb52c958529bb5f5eb7368807b1ae9be5e0
.\build.cmd buildsolution
```

Open `build.fsx` and remove or comment out `SourceLink` target: `=?> ("SourceLink", isLocalBuild && not isLinux)`.

```
.\build.cmd sourcelink
srctool -x C:\tmp\FAKE\build\FakeLib.dll
```

Which version of `fsc.exe` gets used during the build? Here is mine:

```
ls -r 'C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe' | % versioninfo
```

![image](https://cloud.githubusercontent.com/assets/80104/6548839/6dd02992-c5c3-11e4-9697-ce36aae8bbe3.png)

**Comment by ctaggart** [comment]
The navigate to source feature from Visual F# Power Tools works great with build.fsx scripts with FAKE `3.17.6`. /cc @dungpa 

The invalid `%%var2%%` has showed up in every build since version `3.17.9` starting on February 24th. 

```
nuget install fake -version 3.17.7
nuget install fake -version 3.17.9
nuget install fake -version 3.17.11
nuget install fake -version 3.17.12
nuget install fake -version 3.17.13
nuget install fake -version 3.17.14
nuget install fake -version 3.18.0
nuget install fake -version 3.18.1
nuget install fake -version 3.18.2
nuget install fake -version 3.19.0
nuget install fake -version 3.19.1
srctool -x .\FAKE.3.17.7\tools\FakeLib.dll
srctool -x .\FAKE.3.17.9\tools\FakeLib.dll
srctool -x .\FAKE.3.17.11\tools\FakeLib.dll
srctool -x .\FAKE.3.17.12\tools\FakeLib.dll
srctool -x .\FAKE.3.17.13\tools\FakeLib.dll
srctool -x .\FAKE.3.17.14\tools\FakeLib.dll
srctool -x .\FAKE.3.18.0\tools\FakeLib.dll
srctool -x .\FAKE.3.18.1\tools\FakeLib.dll
srctool -x .\FAKE.3.19.0\tools\FakeLib.dll
srctool -x .\FAKE.3.19.1\tools\FakeLib.dll
```

Since this the `sprintf` happens when running the build script with FAKE and since FAKE uses `fsi.exe` to execute, I think the build system has an old version. To see the version of the dll, please run this build script `.\FAKE.exe .\BugHunt.fsx` on the machine used to do builds:

``` fsharp
#r "FakeLib.dll"
open Fake
module FSIHelper =
    let fsiVersion = lazy (System.Diagnostics.FileVersionInfo.GetVersionInfo FSIHelper.fsiPath).FileVersion
Target "BugHunt" <| fun _ ->
    printfn "fsiPath: %s" FSIHelper.fsiPath
    printfn "fsiVersion: %s" FSIHelper.fsiVersion.Value
RunTargetOrDefault "BugHunt"
```

**Comment by dungpa** [comment]
From a user's point of view, I prefer an alternative (String.Format, etc.) that doesn't depend on compiler/fsi/FSharp.Core versions. There is a plenty of machines out there with old versions for which the issue can slip through the cracks.

**Comment by forki** [comment]
Only FAKE.deploy should use fsi. FAKE should still use FCS. Or did we Break that?

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/6573073/9c15960c-c717-11e4-8c41-2b94bd25d04b.png)

^^ on the machine where I do the FAKE releases.

**Comment by forki** [comment]
OK I just noticed FAKE.exe is also spawning fsi processes. That is a bug probably introduced with https://github.com/fsharp/FAKE/pull/653 

/cc @vasily-kirichenko

**Comment by ctaggart** [comment]
Can you upgrade to 3.1.2 on that machine? When you do, that script should print `4.31.30815.0`. 

3.1.1 is `4.31.30110.0`, so that looks like it may be 3.1.0 which has the bug.

**Comment by ctaggart** [comment]
FAKE 3.20.0 does not have a valid source index. :(

![image](https://cloud.githubusercontent.com/assets/80104/6584970/15e826ac-c72c-11e4-9003-c192c14c46da.png)

It is very cool to demo F12 Navigate to Source with a build.fsx when FAKE is source indexed.

**Comment by forki** [comment]
could you please retry with 3.20.1? What is the expected behaviour?

**Comment by ctaggart** [comment]
Yay!
![image](https://cloud.githubusercontent.com/assets/80104/6590069/155ca654-c768-11e4-82e8-8e8a2658c789.png)

**Comment by ctaggart** [comment]
30 second clip. I'll need to improve my QuickTime/YouTube recording skills.
http://youtu.be/5n3TUqMiysk

**Comment by dungpa** [comment]
@ctaggart Would you mind to add the video to the docs at https://github.com/fsprojects/VisualFSharpPowerTools/blob/master/docs/content/navigatetosource.fsx? I appreciate if you have something to improve the guide there.
