### ISSUE TITLE
[Suggestion] Vb6 helper

### ISSUE THREAD

**Issue by Vidarls** [fsharp/FAKE#682]
Currently working on some Vb6 and .net interop stuff,

During the process [this code came into existence](https://gist.github.com/Vidarls/5d615f2c9dd68118d231).

Need some feedback on idea, code quality and adherence to Fake idioms

**Comment by forki** [comment]
wow. that's interesting ;-)
Please remove AutoOpen, add some docs and send a PR

**Comment by Vidarls** [comment]
Thanx.

Also working on a side-by-side interop manifest helper, there are some overlap so I'll do a common PR when ready.
