### ISSUE TITLE
AssemblyInfoHelper.ReplaceAssemblyInfoVersions should not support AssemblyMetadata

### ISSUE THREAD

**Issue by inosik** [fsharp/FAKE#683]
There are two points I see here:
* If one sets the value to something like `["githash"; "abcd0123"; "build-date"; "2015-03-09"]`, then the generated code for C# would be `[assembly: AssemblyMetadata("githash", "abcd0123", "build-date", "2015-03-09")]`, which wouldn't compile.
* Since the `AssemblyMetadata` attribute is allowed to be declared multiple times for an assembly, the current function would replace each line with this attribute by the one above.

So I think the `AssemblyMetadata` attribute shouldn't be supported by this function at all, and `AssemblyInfoFile.CreateCSharpAssemblyInfo` should be used instead.

Changing the type of the `AssemblyMetadata` parameter to `string * string` would solve the first problem. The second one would need some more sophisticated parsing logic, but `CreateCSharpAssemblyInfo` can get the job done as well.

**Comment by forki** [comment]
Cc @jchannon

**Comment by jchannon** [comment]
Valid points but why not pass in a dictionary of data and it replaces where it can for `ReplaceAssemblyInfoVersions`. If there's more passed in the dictionary than there is in the assemblyinfo then it skips it. `CreateCSharpAssemblyInfo` can do its thing slightly differently if needs be

**Comment by inosik** [comment]
You're right about the dictionary, but this still would require some work in `ReplaceAssemblyInfoVersions` or `replaceAttribute`. I'm just afraid that this would turn a small, relatively easy function into something more complicated.

And since `CreateCSharpAssemblyInfo` (and it's siblings for VB and F#) already handle this, I don't see a value in keeping that functionality.
