### ISSUE TITLE
Load Teamcity Addin for NUnit when running nunit tests on teamcity

### ISSUE THREAD

**Issue by brase** [fsharp/FAKE#688]
When making nunit loading this plugin, it is reporting the progress of the test run to teamcity.

More informations can be found here:
https://confluence.jetbrains.com/display/TCD9/TeamCity+Addin+for+NUnit

**Comment by brase** [comment]
It is more complicated than I thought.

* We need to get the addin path not from an env variable. It is a teamcity system variable we need to access. As it turns out it can be read from a file which is provided by teamcity.
Infos can be fiund here:
![image](https://cloud.githubusercontent.com/assets/170088/6634177/8adf8e26-c954-11e4-9c0f-15394a3bc710.png)

* To fully automate the process we need to  find out the current nunit runners version to provide the correct version of the addin

**Comment by matthid** [comment]
Closing this out to clean the house, PR is welcome :)
