### ISSUE TITLE
Different behavior when running Fsc in FAKE vs fsc.exe 

### ISSUE THREAD

**Issue by pavelm** [fsharp/FAKE#689]
I'm seeing an error when running the Fsc build on an `fsx` file, but it successfully compiles when running fsc.exe.

`fsc -I:bin/Debug test.fsx`
vs

``` fsharp
[ "test.fsx" ] |> Fsc (fun p -> { p with OtherParams = [ "-I:bin/Debug" ] } )
```

> unknown (1,1)-(1,81) typecheck error The module/namespace 'System.Runtime.CompilerServices' from compilation unit 'mscorlib' did not contain the namespace, module or type 'ExtensionAttribute'

(I am using an extension method defined in a referenced library)

Could this be a versioning issue?

**Comment by forki** [comment]
The Fsc task uses the [FCS](https://github.com/fsharp/FSharp.Compiler.Service). What's inside test.fsx?

**Comment by forki** [comment]
(most people still use the MSBuild task and compile the whole fsproj or even the sln)

**Comment by pavelm** [comment]
I was able to reproduce with a simple project, see repo: https://github.com/pavelm/CompileFsx 

running with FAKE triggers the problem, but using fsc.exe works fine

**Comment by pavelm** [comment]
@forki I found a work around by using the `--noframework` argument along with explicitly specifying the framework libraries. 

```
    let framework = @"C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.1.0\FSharp.Core.dll"
    let mscorlib = @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll"
    let system = @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll"
    let systemCore = @"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll"

    [file]
    |> Fsc (fun p ->
        {p with OtherParams = [ "--noframework"; "-r"; framework; "-r"; mscorlib; "-r"; system; "-r"; systemCore] } )
```

Seems like FSC is using an older mscorlib and/or FSharp.Core because of the `ExtensionAttribute`. Works fine for dlls which don't expose any extension methods.

**Comment by nicolocodev** [comment]
I ran into the same issue, but it looks like a Fw 4.0 - 4.5 problem. i googled and found [some] (https://github.com/fsharp/fsharpbinding/issues/1008) [similar](https://github.com/BayardRock/IfSharp/issues/12) [issues](http://stackoverflow.com/questions/13748055/could-not-load-type-system-runtime-compilerservices-extensionattribute-from-as). Is there any way to fix it without referencing an specific `fsharp.core` and `mscorelib`? I ask this 'cause when you [use the `--noframework`](https://fsharp.github.io/FSharp.Compiler.Service/corelib.html#Which-FSharp-Core-and-NET-Framework-gets-referenced-in-compilation) you must reference other core libs like `System.Numerics` (also @pavelm shows us an example in the comment above) and, IMO, this add too much noise to build script files.

**Comment by matthid** [comment]
I guess the Fsc task should provide a "tool" property where you can override the executed tool (to execute an external `fsc.exe` instead of the bundled FCS)

**Comment by vanceism7** [comment]
I can work on this @matthid

**Comment by matthid** [comment]
@vanceism7 yes please feel free to send a pr, help is wanted on this ;)

**Comment by matthid** [comment]
As we now have the FSC module for fake 5 please report any issues the new module has
