### ISSUE TITLE
xUnitHelper is not working with xUnit 2.0.0

### ISSUE THREAD

**Issue by kowalgta** [fsharp/FAKE#699]
It seems that xUnit 2.0.0 has just been released (16.03.2015) and that it introduces breaking changes to Console runner. xUnit.Runners has been retired and replaced with xUnit.Runner.Console https://www.nuget.org/packages/xunit.runner.console/. 

FAKE xUnitHelper is using hardcoded file name to this runner (xunit.console.clr4.exe) but it has changed in a version 2.0. https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/UnitTest/XUnitHelper.fs

There might be some more breaking changes in Console runner parameters.

**Comment by Vidarls** [comment]
The hardcoded path is just the default. Does it work if you set the correct toolpath manually in your buildscript?

**Comment by kowalgta** [comment]
> The hardcoded path is just the default. Does it work if you set the correct toolpath manually in your buildscript?

Yes, and no. Yes, it will work if I use it without any extra arguments, and no because I use some and unfortunately new console runner has new format.

For example previously you could call xunit.console.clr4.exe pathToAssemblyWithTests /noshadow but with a new runner you need to do xunit.console.exe pathToAseemblyWithTests -noshadow.

**Comment by Vidarls** [comment]
you should probably be using this: http://fsharp.github.io/FAKE/apidocs/fake-xunit2helper.html
(sorry for not remembering this one before..₩

**Comment by kowalgta** [comment]
How come I've not spotted this before! 

That's solve the issue, thank you.
