### ISSUE TITLE
encoding defaults to ANSI not UTF-8

### ISSUE THREAD

**Issue by phatcher** [fsharp/FAKE#701]
It seems that the default encoding is ANSI not UTF-8, for example if I use NuGet to write a new nuspec file the copyright symbol and accented characters are corrupted.

Following reading #623 I changed my command line to ... encoding=UTF-8 and the characters are now correct.

Given that .NET's default encoding is UTF-8 it seems odd that I have to specify it.

**Comment by ErikSchierboom** [comment]
I also encountered this issue. UTF-8 seems to make more sense to me.

**Comment by matthid** [comment]
I think we default to UTF-8 now, if there are still places please report them again :)

**Comment by phatcher** [comment]
@matthid Seems to work now - the other issue, may be for documentation, is to ensure that the fake script is encoded with UTF-8 rather than ANSI, this is easy to see/change with say Notepad++
