### ISSUE TITLE
NuGet helper does not finds the tool if present in PATH

### ISSUE THREAD

**Issue by bbenoist** [fsharp/FAKE#702]
Hello there,

I am encountering a behavior that I did not expected while using NuGet for creating packages.

The [RestorePackageHelper::findNuget](https://github.com/fsharp/FAKE/blob/3.24.0/src/app/FakeLib/RestorePackageHelper.fs#L9) function does not search for the presence of the executable in the PATH environment variable.

Is it voluntary or can I propose a PR for this?

**Comment by forki** [comment]
yes this sounds like a good addition.

**Comment by forki** [comment]
btw: there is a  tryFindFileOnPath in ProcessHelper.fs - it should help you to implement this.

**Comment by bbenoist** [comment]
I saw that you worked on it while I was preparing my PR :disappointed_relieved:.
Here is my work on the FAKE source code since yesterday in case you still want to integrate some parts of it:

#### Directly related this issue:
* [feature/isvalidpath](https://github.com/bbenoist/FAKE/tree/feature/isvalidpath) [feature/split-environvar](https://github.com/bbenoist/FAKE/tree/feature/split-environvar)
    * ==> [feature/path-directories](https://github.com/bbenoist/FAKE/tree/feature/path-directories)
    * ==> [feature/nuget-in-path](https://github.com/bbenoist/FAKE/tree/feature/nuget-in-path)

#### Indirectly related this issue:
* [bugfix/typo](https://github.com/bbenoist/FAKE/tree/bufgfix/typo)
* [bugfix/system-directory](https://github.com/bbenoist/FAKE/tree/bugfix/system-directory)
* [feature/code-style](https://github.com/bbenoist/FAKE/tree/feature/code-style)
    * ==> [feature/trim-trailing-whitespace](https://github.com/bbenoist/FAKE/tree/feature/trim-trailing-whitespace)

**Comment by forki** [comment]
please send a pull request. I fixed another bug. I think the Nuget path finder is still broken.

**Comment by bbenoist** [comment]
OK, I will continue on it.

However, after remarking that the `master` branch has been reset to a previous commit, then, diverged from its original state, one question remains:

Should I rebase and recreate all my branches or will you merge them into master anyway?

As I have previously been confronted with such problems and eliminated most of them with an adapted workflow, here is some useful information about the available stategies:
* [Git team workflows: merge or rebase](https://www.atlassian.com/git/articles/git-team-workflows-merge-or-rebase/)
* [Comparing Workflows](https://www.atlassian.com/git/tutorials/comparing-workflows)
* [Merging vs Rebasing.](https://www.atlassian.com/git/tutorials/merging-vs-rebasing/)
* [Reset, Checkout, and Revert](https://www.atlassian.com/git/tutorials/resetting-checking-out-and-reverting)

**Comment by forki** [comment]
I had to remove a bad commit. I agree it would have been better to just revert that thingy.
Plese rebase your commit on current master.
