### ISSUE TITLE
#706 Cuases misbehaviour on server 2008r2

### ISSUE THREAD

**Issue by Vidarls** [fsharp/FAKE#715]
```
System.Environment.SystemDirectory: "C:\Windows\system32"
(environVar SystemRoot): "C:\Windows"
```

When trying to find .net install dir using targetplatformprefix (https://github.com/fsharp/FAKE/blob/5d1e93e903cc53edd16dee201f48fa09024a71a0/src/app/FakeLib/EnvironmentHelper.fs#L111) it fails due to starting search in system32

Can you please revert until we have a better x-platform fix @forki ?

**Comment by forki** [comment]
cc @bbenoist 
ok will revert.

**Comment by Vidarls** [comment]
Thanks.

Problem => Have lunch => Problem solved, I could get used to this..

**Comment by bbenoist** [comment]
My bad, I always use `%windir%` instead of `%SystemRoot%` and misleaded it with `System.Environment.SystemDirectory` by using my [System 1](http://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0141033576) :confused: 

I should have used `System.Environment.GetFolderPath(System.Environment.SpecialFolder.Windows)` (present since .NET 4.0) instead.

@forki Are you OK to apply the following refactoring and deprecate `SystemRoot`:
```
/// The fully qualified path of the Windows directory. Typically "C:\Windows".
let WindowsDirectory = Environment.GetFolderPath Environment.SpecialFolder.Windows

/// The fully qualified path of the system directory. Typically "C:\Windows\System32".
let SystemDirectory = Environment.SystemDirectory

/// Deprecated, please use WindowsDirectory instead.
let SystemRoot = WindowsDirectory
```

**Comment by bbenoist** [comment]
Further reading:
* [What is difference between %WinDir% and %SystemRoot%?](http://superuser.com/questions/638321/what-is-difference-between-windir-and-systemroot)
* [Difference between Environment.GetFolderPath(Environment.SpecialFolder.System) and Environment.SystemDirectory for System32 folder](http://stackoverflow.com/questions/23327711/difference-between-environment-getfolderpathenvironment-specialfolder-system-a)
* [Environment.SystemDirectory](https://msdn.microsoft.com/en-us/library/system.environment.systemdirectory(v=vs.110).aspx)
* [Environment.GetFolderPath](https://msdn.microsoft.com/en-us/library/system.environment.specialfolder(v=vs.110).aspx)
* [Environment.SpecialFolder](https://msdn.microsoft.com/en-us/library/14tx8hby(v=vs.110).aspx)
* [Environment.cs  - Mono](https://github.com/mono/mono/blob/master/mcs/class/corlib/System/Environment.cs)
* [Environment.cs - .NET Reference Source](http://referencesource.microsoft.com/#mscorlib/system/environment.cs)
