### ISSUE TITLE
Local nuget.exe should take precedence over NuGet on PATH (follow-up #702)

### ISSUE THREAD

**Issue by mthierba** [fsharp/FAKE#717]
I absolutely agree with #702 that NuGet.exe should be searched in the PATH, but the way how this has been implemented in f83255dd488b4b55148f615eeb80cd44e35e626c, it has now broken several of my CI builds (had the latest NuGet in "./packages", but an older one installed globally), and I have a feeling this might be the case for others, too. 

I think NuGet should be looked for locally *first*, and only in the PATH as a fall-back. Other tools like npm work the same way, so most users come with that expectation, and would find the new behavior counter-intuitive.

**Comment by forki** [comment]
Oh this was absolutely unintended. Can you please submit a pull request then I will release the fix as soon as possible. Sorry
