### ISSUE TITLE
What are the NugetFeeds in Fake.Deploy.Web for?

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#724]
I'm looking at Fake.Deploy.Web, and it works nicely from early tests. During the one time init, there's an option to add a list of nuget feeds for integration (or something). Looking at the code, it looks like they're saved via the data provider, but can't figure out how those are used. Are those used by a feature currently present, or sometime on the future? If the latter, what might that consist of?

Thanks,
Ashic.

**Comment by ashic** [comment]
Pinging @colinbull @forki @vasily-kirichenko @MorganPersson

**Comment by MorganPersson** [comment]
I did too many things at once and is/was part of a feature I never finished. It seems I missed to remove it when I made a pull request for something else.
The feature would make it possible to install packages from a nuget feed of your choice with a click of a button via the web UI.

**Comment by ashic** [comment]
Ah..makes sense. It'd be a useful feature, specially if you can point it to a directory. I'd leave what's in there already (possibly simply making the checkbox hidden), instead of removing it completely.

**Comment by forki** [comment]
Can you please send a  pull request which disables it? Thanks

**Comment by ashic** [comment]
Will do :)
