### ISSUE TITLE
Unable to build on OSX

### ISSUE THREAD

**Issue by bradphelan** [fsharp/FAKE#725]
When I run the build I get

    XBuild Engine Version 12.0
    Mono, Version 3.12.0.0
    Copyright (C) 2005-2013 Various Mono authors
    
    Build started 4/1/2015 9:42:09 PM.
    __________________________________________________
    /Users/bradphelan/workspace/FAKE/src/test/FsCheck.Fake/FsCheck.Fake.fsproj:  warning : Cannot import project '/usr/local/Cellar/mono/3.12.0/lib/mono/xbuild/../Microsoft SDKs/F#/3.1/Framework/v4.0/Microsoft.FSharp.Targets' again. It was already imported by '/Users/bradphelan/workspace/FAKE/src/test/FsCheck.Fake/FsCheck.Fake.fsproj'. Ignoring.
    Project "/Users/bradphelan/workspace/FAKE/FAKE.sln" (Build target(s)):
    	Target ValidateSolutionConfiguration:
    		Building solution configuration "Release|Mixed Platforms".
    	Target Build:
    		Project "/Users/bradphelan/workspace/FAKE/src/app/FakeLib/FakeLib.fsproj" (default target(s)):
    			Target PrepareForBuild:
    				Configuration: Release Platform: AnyCPU
    			Target CopyFilesMarkedCopyLocal:
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/FSharp.Compiler.Service/lib/net40/FSharp.Compiler.Service.dll' to '/Users/bradphelan/workspace/FAKE/build/FSharp.Compiler.Service.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/FSharp.Core/lib/net40/FSharp.Core.dll' to '/Users/bradphelan/workspace/FAKE/build/FSharp.Core.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Microsoft.Web.Xdt/lib/net40/Microsoft.Web.XmlTransform.dll' to '/Users/bradphelan/workspace/FAKE/build/Microsoft.Web.XmlTransform.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Mono.Cecil/lib/net40/Mono.Cecil.Mdb.dll' to '/Users/bradphelan/workspace/FAKE/build/Mono.Cecil.Mdb.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Mono.Cecil/lib/net40/Mono.Cecil.Pdb.dll' to '/Users/bradphelan/workspace/FAKE/build/Mono.Cecil.Pdb.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Mono.Cecil/lib/net40/Mono.Cecil.Rocks.dll' to '/Users/bradphelan/workspace/FAKE/build/Mono.Cecil.Rocks.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Mono.Cecil/lib/net40/Mono.Cecil.dll' to '/Users/bradphelan/workspace/FAKE/build/Mono.Cecil.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Mono.Web.Xdt/lib/Net40/Microsoft.Web.XmlTransform.dll' to '/Users/bradphelan/workspace/FAKE/build/Microsoft.Web.XmlTransform.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/packages/Nuget.Core/lib/net40-Client/NuGet.Core.dll' to '/Users/bradphelan/workspace/FAKE/build/NuGet.Core.dll'
    				Copying file from '/Users/bradphelan/workspace/FAKE/lib/ICSharpCode.SharpZipLib.dll' to '/Users/bradphelan/workspace/FAKE/build/ICSharpCode.SharpZipLib.dll'
    			Target GenerateSatelliteAssemblies:
    			No input files were specified for target GenerateSatelliteAssemblies, skipping.
    			Target CoreCompile:
    				Tool /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe execution started with arguments: -o:obj/Release/FakeLib.dll --debug:pdbonly --noframework --define:TRACE --doc:../../../build/FakeLib.XML --optimize+ -r:../../../packages/FSharp.Compiler.Service/lib/net40/FSharp.Compiler.Service.dll -r:../../../packages/FSharp.Core/lib/net40/FSharp.Core.dll -r:../../../packages/Microsoft.Web.Xdt/lib/net40/Microsoft.Web.XmlTransform.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.Mdb.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.Pdb.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.Rocks.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.dll -r:../../../packages/Nuget.Core/lib/net40-Client/NuGet.Core.dll -r:../../../lib/ICSharpCode.SharpZipLib.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/Microsoft.Build.Framework.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/mscorlib.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Configuration.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Runtime.Caching.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.ServiceProcess.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Xml.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Xml.Linq.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Core.dll --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --highentropyva- AssemblyInfo.fs CSharpHelper.fs EnvironmentHelper.fs RegistryHelper.fs FileSystemHelper.fs StringHelper.fs TemplateHelper.fs CacheHelper.fs XMLHelper.fs REST.fs BuildServerHelper.fs TraceListener.fs TeamCityHelper.fs TeamCityRESTHelper.fs TraceHelper.fs ServiceControllerHelper.fs GuardedAwaitObservable.fs ProcessHelper.fs AppVeyor.fs TaskRunnerHelper.fs Globbing/FileSystem.fs UnitTest/UnitTestCommon.fs UnitTest/UnitTestHelper.fs UnitTest/NUnit/Xml.fs UnitTest/NUnit/Common.fs UnitTest/NUnit/Sequential.fs UnitTest/NUnit/Parallel.fs UnitTest/XUnitHelper.fs UnitTest/XUnit2Helper.fs UnitTest/MSpecHelper.fs UnitTest/MSTest.fs UnitTest/ProcessTestRunner.fs AssemblyInfoFile.fs AssemblyInfoHelper.fs FXCopHelper.fs FSharpFormattingHelper.fs NCoverHelper.fs NDependHelper.fs MsBuildLogger.fs FileHelper.fs MSBuildHelper.fs ZipHelper.fs StrongNamingHelper.fs GACHelper.fs NGenHelper.fs FileUtils.fs DocuHelper.fs ILMergeHelper.fs WiXHelper.fs MSIHelper.fs RegAsmHelper.fs RestorePackageHelper.fs VSSHelper.fs DynamicsNavHelper.fs DynamicsNavFile.fs SCPHelper.fs XCopyHelper.fs XpkgHelper.fs VersionHelper.fs MSBuild/ProjectSystem.fs MSBuild/SpecsRemovement.fs Git/CommandHelper.fs Git/Sha1.fs Git/Repository.fs Git/Submodule.fs Git/Branches.fs Git/Reset.fs Git/Merge.fs Git/Stash.fs Git/SanityChecks.fs Git/Information.fs Git/FileStatus.fs Git/Rebase.fs Git/CommitMessage.fs Git/Staging.fs Git/Commit.fs FSIHelper.fs Boot.fs MessageHelper.fs HTMLHelpWorkShopHelper.fs ConfigurationHelper.fs TargetHelper.fs AdditionalSyntax.fs PermissionsHelper.fs SpecFlowHelper.fs OctoTools.fs SignHelper.fs MageHelper.fs SemVerHelper.fs ReleaseNotesHelper.fs FixieHelper.fs NuGet/NugetHelper.fs NuGet/Update.fs NuGet/Install.fs TestFlightHelper.fs DotCover.fs AzureHelper.fs FtpHelper.fs TypeScript.fs OpenCoverHelper.fs ReportGeneratorHelper.fs RoundhouseHelper.fs FscHelper.fs CscHelper.fs HipChatNotificationHelper.fs XamarinHelper.fs XDTHelper.fs AzureWebJobs.fs 
    /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/Microsoft.FSharp.Targets: error : Error executing tool '/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe': ApplicationName='/usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe', CommandLine='-o:obj/Release/FakeLib.dll --debug:pdbonly --noframework --define:TRACE --doc:../../../build/FakeLib.XML --optimize+ -r:../../../packages/FSharp.Compiler.Service/lib/net40/FSharp.Compiler.Service.dll -r:../../../packages/FSharp.Core/lib/net40/FSharp.Core.dll -r:../../../packages/Microsoft.Web.Xdt/lib/net40/Microsoft.Web.XmlTransform.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.Mdb.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.Pdb.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.Rocks.dll -r:../../../packages/Mono.Cecil/lib/net40/Mono.Cecil.dll -r:../../../packages/Nuget.Core/lib/net40-Client/NuGet.Core.dll -r:../../../lib/ICSharpCode.SharpZipLib.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/Microsoft.Build.Framework.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/mscorlib.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Configuration.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Runtime.Caching.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.ServiceProcess.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Xml.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Xml.Linq.dll -r:/usr/local/Cellar/mono/3.12.0/lib/mono/4.0/System.Core.dll --target:library --warn:3 --warnaserror:76 --fullpaths --flaterrors --highentropyva- AssemblyInfo.fs CSharpHelper.fs EnvironmentHelper.fs RegistryHelper.fs FileSystemHelper.fs StringHelper.fs TemplateHelper.fs CacheHelper.fs XMLHelper.fs REST.fs BuildServerHelper.fs TraceListener.fs TeamCityHelper.fs TeamCityRESTHelper.fs TraceHelper.fs ServiceControllerHelper.fs GuardedAwaitObservable.fs ProcessHelper.fs AppVeyor.fs TaskRunnerHelper.fs Globbing/FileSystem.fs UnitTest/UnitTestCommon.fs UnitTest/UnitTestHelper.fs UnitTest/NUnit/Xml.fs UnitTest/NUnit/Common.fs UnitTest/NUnit/Sequential.fs UnitTest/NUnit/Parallel.fs UnitTest/XUnitHelper.fs UnitTest/XUnit2Helper.fs UnitTest/MSpecHelper.fs UnitTest/MSTest.fs UnitTest/ProcessTestRunner.fs AssemblyInfoFile.fs AssemblyInfoHelper.fs FXCopHelper.fs FSharpFormattingHelper.fs NCoverHelper.fs NDependHelper.fs MsBuildLogger.fs FileHelper.fs MSBuildHelper.fs ZipHelper.fs StrongNamingHelper.fs GACHelper.fs NGenHelper.fs FileUtils.fs DocuHelper.fs ILMergeHelper.fs WiXHelper.fs MSIHelper.fs RegAsmHelper.fs RestorePackageHelper.fs VSSHelper.fs DynamicsNavHelper.fs DynamicsNavFile.fs SCPHelper.fs XCopyHelper.fs XpkgHelper.fs VersionHelper.fs MSBuild/ProjectSystem.fs MSBuild/SpecsRemovement.fs Git/CommandHelper.fs Git/Sha1.fs Git/Repository.fs Git/Submodule.fs Git/Branches.fs Git/Reset.fs Git/Merge.fs Git/Stash.fs Git/SanityChecks.fs Git/Information.fs Git/FileStatus.fs Git/Rebase.fs Git/CommitMessage.fs Git/Staging.fs Git/Commit.fs FSIHelper.fs Boot.fs MessageHelper.fs HTMLHelpWorkShopHelper.fs ConfigurationHelper.fs TargetHelper.fs AdditionalSyntax.fs PermissionsHelper.fs SpecFlowHelper.fs OctoTools.fs SignHelper.fs MageHelper.fs SemVerHelper.fs ReleaseNotesHelper.fs FixieHelper.fs NuGet/NugetHelper.fs NuGet/Update.fs NuGet/Install.fs TestFlightHelper.fs DotCover.fs AzureHelper.fs FtpHelper.fs TypeScript.fs OpenCoverHelper.fs ReportGeneratorHelper.fs RoundhouseHelper.fs FscHelper.fs CscHelper.fs HipChatNotificationHelper.fs XamarinHelper.fs XDTHelper.fs AzureWebJobs.fs ', CurrentDirectory='/Users/bradphelan/workspace/FAKE/src/app/FakeLib', Native error= Cannot find the specified file
    			Task "Fsc" execution -- FAILED
    			Done building target "CoreCompile" in project "/Users/bradphelan/workspace/FAKE/src/app/FakeLib/FakeLib.fsproj".-- FAILED
    		Done building project "/Users/bradphelan/workspace/FAKE/src/app/FakeLib/FakeLib.fsproj".-- FAILED
    	Task "MSBuild" execution -- FAILED

The FSC compiler is definately available and working.

    ➜  FAKE git:(feature/fakelikemake) ✗ ls -al /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe
    -r--r--r--  1 bradphelan  wheel  28160 Mar 22 19:40 /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe
    ➜  FAKE git:(feature/fakelikemake) ✗ mono /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe --help
    F# Compiler for F# 3.1 (Open Source Edition)
    Freely distributed under the Apache 2.0 Open Source License

It seems as if the build is trying to run it as a normal executable rather than through mono

**Comment by forki** [comment]
mhm. the mono build is working. https://travis-ci.org/fsharp/FAKE

What are you doing exactly?

**Comment by bradphelan** [comment]
Open up the terminal and type

build.sh

**Comment by forki** [comment]
I don't own a mac. @dnauck can you reproduce this?

**Comment by bradphelan** [comment]
might be something to do with the fact I installed fake under homebrew which sets up fsc as fsharpc under the following method.

    ➜  FAKE git:(feature/fakelikemake) ✗ cat /usr/local/bin/fsharpc
    #!/bin/sh
    EXEC="exec "
    
    if test x"$1" = x--debug; then
       DEBUG=--debug
       shift
    fi
    
    if test x"$1" = x--gdb; then
       shift
       EXEC="gdb --eval-command=run --args "
    fi
    
    if test x"$1" = x--valgrind; then
      shift
      EXEC="valgrind $VALGRIND_OPTIONS"   
    fi
    
    # Beware this line must match the regular expression " (\/.*)\/fsi\.exe" when fsc.exe is fsi.exe.
    # That's because the FSharp MonoDevelop addin looks inside the text of this script to determine the installation
    # location of the default FSharp install in order to find the FSharp compiler binaries (see 
    # fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerLocationUtils.fs). That's a pretty unfortunate
    # way of finding those binaries. And really should be changed.
    $EXEC mono $DEBUG $MONO_OPTIONS /usr/local/Cellar/fsharp/3.1.1.25/lib/mono/4.0/fsc.exe --exename:$(basename $0) "$@"

**Comment by bradphelan** [comment]
Ok I removed my homebrew installed versions of mono, and fsharp and installed them from 

http://www.mono-project.com/download/

and everything seems to be compiling along nicely now. Maybe you should put a warning about homebrew or contact the brew recipe maintainers.

**Comment by haf** [comment]
There are no brew recipe maintainers currently, so any help would be appreciated.

**Comment by haf** [comment]
Related https://github.com/fsharp/fsharp/issues/378

**Comment by tforkmann** [comment]
i know this is a old issue but i just can report the same issue...

> error FS0078: Unable to find the file 'packages/FAKE/tools/FakeLib.dll' in any of
 /Library/Frameworks/Mono.framework/Versions/4.2.1/lib/mono/4.5

today i updated homebrew and were running brew install mono...

In VS Code I tried to build the build.fsx file.

gonna try @bradphelan approaching now.

**Comment by dsyme** [comment]
Closing old issue, external bug has been fixed.
