### ISSUE TITLE
Fake.Deploy.Web could pass environment name to agent

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#731]
Currently, the deployment website posts an empty list of args to the remote agent:

```
match postDeploymentPackage url file [||] with
```

in Api.Package.fs.

With #452 , the Fake.Deploy supports passing parameters to the script. It seems the code required to pass features from the website to the agent is already in place. It is quite common to create one deployable for all environments (qa, dev, etc.), and to tokenization, etc. at deployment time. It would be helpful if Fake.Deploy.Web could pass the environment name while posting, which would enable this use case.

Any thoughts? I could try and put something together if there aren't any issues (or if something similar is already in place).

// @forki @colinbull @MorganPersson @vasily-kirichenko

**Comment by ashic** [comment]
@vasily-kirichenko , 
Looking into this...it appears passing multiple strings to postDeploymentPackage passes them to build.fsx as fsi.CommandLineArgs as a single semicolon separated string. Is this by design?

**Comment by matthid** [comment]
Closing old issue, not sure if anyone still uses Fake.Deploy.

**Comment by colinbull** [comment]
Yeah, I was thinking this the other month. Maybe we should just get rid of it?
