### ISSUE TITLE
Using Fake in Fake.Deploy deployment script

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#733]
Is there an easy way to reference Fake in a Fake.Deploy deployment script? Current directory is the Fake.Deploy directory, and **SOURCE_DIRECTORY** is the deploymentscript.fsx directory. It seems I can only #r from the source directory, or a hard coded path. I can get around this by copying stuff from environment dir to source dir in the fsx file, and then #r -ing the dll. It works, but is kind of icky. Though it can be argued that referencing anything outside the deployment package is icky, but would love to not have to include Fake in deployables (boxes in question don't have internet access, so can't nuget in either).

Is there a better option? @forki @vasily-kirichenko @MorganPersson @colinbull

**Comment by Vidarls** [comment]
You can use `#I` to several possible paths, and then `#r "FakeLib.dll"` with no path prefix.

You'll get warnings but no errors for locations that are unavailable.

ie:

```f#
#I @"tools/FAKE/tools/"
#I @"../../../../tools/FAKE/tools/"
#r "FakeLib.dll"
``` 

btw: Great that Fake.Deploy is getting some love. :+1:

**Comment by ashic** [comment]
For some reason, it seems you can't use #I includes for the fake binaries in env.currentdir. Perhaps it's coz it's in the currently loaded process? Copying them to SOURCE_DIR (or any other location) seems to work.

**Comment by GeorgSchneider** [comment]
I've had the same quesion and described the solution I found [on StackOverflow](http://stackoverflow.com/questions/30187619/how-can-i-reference-fakelib-dll-in-a-fake-deploy-deployment-script).

You need to a) use the default deployment directory "." (where Fake.Deploy.exe is located) and b) reference FakeLib.dll like this:

    #r @"..\..\..\FakeLib.dll"

Note that I meanwhile think it's much cleaner to actually reference and deploy FAKE with your application. The above approach breaks as soon as you choose to use a non-default deployment directory with Fake.Deploy, which I think is quite common.

**Comment by GeorgSchneider** [comment]
On that note, I would find it useful if Fake.Deploy would automatically reference FakeLib when executing the post-deployment script. I think it's quite a common use case and would avoid the need to package applications with FAKE. Not sure if this is possible though, I might take a look when I find some time.

**Comment by matthid** [comment]
Let me know if this is still relevant.
