### ISSUE TITLE
FAKE fails on OS X for Microsoft.Web.XmlTransform.dll

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#739]
Trying to compile Http.fs and it's failing on OS X due to Microsoft.Web.XmlTransform.dll.

Repro: try to build https://github.com/relentless/Http.fs on OS X.

Output:

```
Http.fs/build.fsx(2,1): error FS0078: Unable to find the file 'Microsoft.Web.XmlTransform.dll' in any of
 /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.5
 /Users/henrik.feldt/dev/haf/Http.fs/.
 /Library/Frameworks/Mono.framework/Versions/3.12.1/lib/mono/4.0/
```

Easily solved by doing `#I "packages/FAKE/tools/"`. You can decide whether this crash is 'intended and documented' or something you wish to change. I suppose NuGet.Core is an open assembly, to use from FAKE scripts? So then ILMerging to internal wouldn't work well (plus a lot of things would have to be marked internal). Can you ILMerge it to a public NS?

Perhaps this issue is related to the DLL search path issue?

**Comment by mooreniemi** [comment]
Thanks for documenting this @haf -- was able to use `#I` at least for now to get going.

**Comment by matthid** [comment]
Yes I think `#I "packages/FAKE/tools/"` is kind of the way to do things atm. FAKE 5 will provide a better solution to this.
