### ISSUE TITLE
Question: Fuchu unit tests

### ISSUE THREAD

**Issue by haf** [fsharp/FAKE#742]
Hi,

How would I configure FAKE to run Fuchu? It's just an executable; or FAKE could itself load the DLL and run all tests in it.

I suppose I could use ProcessHelper; does it automatically take care to prefix mono, like albacore does, or would I have to add that manually?

**Comment by forki** [comment]
Yes IIRC we detect mono. /cc @mausch

**Comment by mausch** [comment]
See also https://github.com/fsharp/FAKE/issues/234

**Comment by haf** [comment]
Ok, laundry list:

 - Same sort of failed/succeeded outputs as other unit tests
 - Ability to specify a computer-readable output for saving into the CI environment
 - A task that invokes the executable, since that's the 'form' that FAKE has for its tasks.

**Comment by mausch** [comment]
About "same output as other tests / computer-readable output" I was considering ( https://github.com/mausch/Fuchu/issues/1 ) generating NUnit XML output, which is probably understood by every tool out there.

About the FAKE task, do you have any pseudo-code in mind of how it would look like when calling it?

**Comment by pjean** [comment]
Hi,

Can we have an update about Fuchu integration ?
I'm newbie to F# and Fake. If there is a workaround to run Fuchu with Fake, can you provide an example, please ?

Thanks

**Comment by mausch** [comment]
@pjean  Here's an example: https://github.com/mausch/Fuchu/blob/5ef9ec303abf56f8ca5511cda3fb53bfa705007c/build.fsx#L112 i.e. you can just run the tests executable like any other executable.

**Comment by Kazark** [comment]
Is this closed by #1268 ?

**Comment by mausch** [comment]
Cool, had not seen #1268 . Yeah I think this can be closed now...
