### ISSUE TITLE
Zip working directory with back slashes no longer honoured?

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#748]
Say I have files in D:/foo/bar/baz , and I run the following:

```
files |> Zip "D:\\foo\\bar\\baz\\" "my.zip"
```

then previous (last week), it'd create the package and inside my.zip, the files will reside in the baz folder. In the version of fake I got today, it seems the files will be in a folder called foo/bar/baz (inside the zip). Running

```
files |> Zip "D:\\foo\\bar\\baz" "my.zip"
```

works fine though. 

Was this a planned change? I ask as this is breaking current behaviour.

[Note: just updated the issue. I previously thought it was an issue with unix paths, but it seems it's the trailing slash to blame]

**Comment by forki** [comment]
I assume 0df4569 by @neoeinstein was the breaking change, so I reverted that commit and the hotfix release is in progress.

**Comment by neoeinstein** [comment]
It's probably a problem with how I am trimming that trailing slash. I'll make the correction to handle this properly. It is likely not trimming off that last slash, turning the relative path it into an "absolute" path inside the zip, thus causing it to be at the root.

**Comment by forki** [comment]
I hope we can find a way to reapply 0df4569 without breaking too much.

**Comment by forki** [comment]
ah seems @neoeinstein is already looking into this. Nice

**Comment by ashic** [comment]
So I guess the trailing slash will be optional? Already worked around it my side :)

**Comment by forki** [comment]
release is out.
