### ISSUE TITLE
Nuget issue with FAKE 3.27.6

### ISSUE THREAD

**Issue by etishor** [fsharp/FAKE#752]
There seems to be an issue with the latest (3.27.6) version of the FAKE nuget package. Executing the command below results in an error:

```
>  .nuget\NuGet.exe install FAKE
Unable to find version '3.27.6' of package 'FAKE'.
```

Below the output after turning on verbosity:

```
>.nuget\NuGet.exe install FAKE -OutputDirectory Bin -ExcludeVersion -Verbosity detailed -Version 3.27.6
GET https://www.nuget.org/api/v2/Packages(Id='FAKE',Version='3.27.6')
GET https://www.nuget.org/api/v2/Packages(Id='FAKE',Version='3.27.6.0')
System.InvalidOperationException: Unable to find version '3.27.6' of package 'FAKE'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepository, IPackageRepository localReposito
ry, IPackageConstraintProvider constraintProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVer
sions)
   at NuGet.PackageManager.InstallPackage(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean
 allowPrereleaseVersions)
```

Manually accessing https://www.nuget.org/api/v2/Packages(Id='FAKE',Version='3.27.5') works but https://www.nuget.org/api/v2/Packages(Id='FAKE',Version='3.27.6') does respond with:

    Resource not found for the segment 'Packages'.

**Comment by forki** [comment]
sorry it's nuget issue. and it will solve itself with waiting a couple of minutes.

see #710

but since a couple of people reported it. I will release a zero-diff version

**Comment by etishor** [comment]
ok, thanks. Maybe you can leave one issue opened until fixed. I searched open issues before posting :)

Thanks,
Iulian

**Comment by etishor** [comment]
I get the exact same issue with 3.27.7 

Thanks for the effort. I've pinned 3.27.5 for now.

**Comment by KyleGobel** [comment]
I'm sure you know this, but I'm still getting the error on 3.28

**Comment by forki** [comment]
https://twitter.com/maartenballiauw/status/586180096974843905

**Comment by forki** [comment]
I'm unlisting latest packages in order to reduce the pain.

**Comment by forki** [comment]
Nuget index should be there again. I relisted the package.
