### ISSUE TITLE
Paket question for Fake.Deploy.Web

### ISSUE THREAD

**Issue by ashic** [fsharp/FAKE#755]
Currently Fake.Deploy.Web needs razor v2 binaries (either gac-ed or in bin). Paket brings down v3 of razor which nothing else is expecting. Is there a way to force the usage of v2? Basically, we need to ensure that http://www.nuget.org/packages/Microsoft.AspNet.Razor/2.0.30506 is used. Currently, the latest stable is put into packages: http://www.nuget.org/packages/Microsoft.AspNet.Razor/3.2.3/. The latter pretty much requires MVC5 and .NET 4.5, whereas the former doesn't. I've tried adding the following to paket.dependencies:

nuget Microsoft.AspNet.Razor 2.0.30506

but it doesn't seem to have any effect. Running .\.paket\pakete.exe install simply brings down the latest stable version. I'm not overly familiar with paket. Would appreciate it if somebody could point me in the right direction.

**Comment by forki** [comment]
like https://github.com/fsharp/FAKE/pull/756?

**Comment by ashic** [comment]
Did you update the lock file manually? I did try updating paket.dependencies and adding exactly that line, but further up the file. Kept bringing down 3.2.3.

**Comment by forki** [comment]
I added it to my paket backlog as an issue to invest. I used `paket update` and staged the lock file selectivly.

**Comment by forki** [comment]
should I merge #756?

**Comment by ashic** [comment]
Looks like it also needs microsoft.aspnet.webpages.2.0.30506 . Adding that in would make it bin-deployable (without any GAC support).

**Comment by ashic** [comment]
Also...we can remove System.Web.Razor.Unofficial from all references...it was mainly a legal issue which no longer is an issue.

**Comment by forki** [comment]
better?

2015-04-14 17:30 GMT+02:00 Ashic Mahtab <notifications@github.com>:

**Comment by ashic** [comment]
Yup...looks nice. Need to up my paket-foo :)

**Comment by ashic** [comment]
Bin deploy works :)

**Comment by forki** [comment]
regarding the paket issue: I think it's the same issue as https://github.com/fsprojects/Paket/issues/777 and fixed in 0.41.3 

any chance you could retry to confirm?

**Comment by ashic** [comment]
Will try tomorrow and let you know.
