### ISSUE TITLE
Change "xunit.console.clr4.exe" to "xunit.console.exe" in XUnitDefaults.

### ISSUE THREAD

**Issue by philderbeast** [fsharp/FAKE#757]
The xunit console runner has changed as has the package to install [split xunit.runners](https://github.com/xunit/xunit/issues/340) in v2.0 of xUnit. Please change the runner from "xunit.console.clr4.exe" to "xunit.console.exe" in XUnitDefaults.

**Comment by forki** [comment]
Could you please send a pull request? The fix should be easy to do.

**Comment by philderbeast** [comment]
I have but missed the github issue reference comment in the commit message.

https://github.com/fsharp/FAKE/pull/758

**Comment by forki** [comment]
did you see that we have http://fsharp.github.io/FAKE/apidocs/fake-xunit2helper.html?

We wil make the xUnit helper obsolete.
