### ISSUE TITLE
Latest sample project fails

### ISSUE THREAD

**Issue by nhaberl** [fsharp/FAKE#762]
I cannot run the complete build script in your samples within VS 2013.4 - latest F# version installed.
The error occurs here, the **!+** operator cannot be used:

Ans Scan is not defined.

Target "FxCop" (fun _ ->
        !+ (buildDir + @"\**\*.dll")
          ++ (buildDir + @"\**\*.exe")
            |> Scan
            |> FxCop (fun p ->
                {p with
                    ReportFileName = testDir + "FXCopResults.xml";
                    ToolPath = fxCopRoot})
    )
    
    Target "Zip" (fun _ ->
        !+ (buildDir + "\**\*.*")
            -- "*.zip"
            |> Scan
            |> Zip buildDir (deployDir + "Calculator." + version + ".zip")
    )

**Comment by forki** [comment]
Oh yes this code is obsolete. Where did you find it exactly? 

Please use !! and remove the complete line with scan.

**Comment by nhaberl** [comment]
I've downloaded this at the getting started site on the link you provided at the beginning ;)

Mit TouchDown von meinem Android-Telefon gesendet (www.nitrodesk.com)

-----Original Message-----

**Comment by forki** [comment]
In the zip file? Oups. Thanks for reporting

**Comment by nhaberl** [comment]
Yeah, right!

Mit TouchDown von meinem Android-Telefon gesendet (www.nitrodesk.com)

-----Original Message-----
