### ISSUE TITLE
Support for FluentMigrator

### ISSUE THREAD

**Issue by munumafia** [fsharp/FAKE#763]
Would anyone be interested in support for FluentMigrator for running database migrations? I'm already working on a helper for running the migrations and could send a pull request when I'm done.

**Comment by forki** [comment]
No idea what that is, but sounds interesting

**Comment by cdroulers** [comment]
I'm interested! We currently just call the exe with all parameters as string, but a module would be great!

Would it include ways to start the database from scratch?

**Comment by munumafia** [comment]
Do you mean rollback all migrations and then rerun them?

**Comment by cdroulers** [comment]
I usually DROP DATABASE whatever and run migrations from scratch before running unit tests or deploying to QA.

**Comment by munumafia** [comment]
It would be a lot of work to implement that as part of the module itself due to the large number of databases that FluentMigrator supports. Assuming you are using SQL Server, could you just have your target execute [sqlcmd](https://technet.microsoft.com/en-us/library/ms165702%28v=sql.105%29.aspx) to recreate the database before deploying to QA or running unit tests? 

Otherwise you could create a migration that runs before the rest of your migrations that will create the database if it doesn't exist. When the migration is rolled back, it would take care of dropping the database automatically. You would just have to rollback all your migrations and run them again before you run your tests or deploy to QA. This would just be slow depending on the number of migrations that need to be rolled back.

**Comment by cdroulers** [comment]
Oh yeah, that sounds good! Thanks!

**Comment by smolyakoff** [comment]
Hey guys, I'm working on the [pull request](https://github.com/fsharp/FAKE/pull/832) adding this feature. Feel free to review and discuss.

**Comment by dsyme** [comment]
Closing old issue
