### ISSUE TITLE
Azure StorageEmulator functionality does not work on latest SDK

### ISSUE THREAD

**Issue by isaacabraham** [fsharp/FAKE#765]
It looks like the StartStorageEmulator path is hard coded to a specific path i.e.

```C:\Program Files\Microsoft SDKs\Windows Azure\Emulator\csrun.exe```

on the latest SDK, on 64 bit Windows, it should be 

```C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\WAStorageEmulator.exe```

**Comment by dsyme** [comment]
Closing old inactive suggestion. Please send a PR for this if you'd like the issue addressed.
