### ISSUE TITLE
Xunit2Helper Does not allow option for formatting

### ISSUE THREAD

**Issue by jarrod268** [fsharp/FAKE#769]
With the XunitHelper you could pass in the option to format as NUnit. XUnit2Helper does not allow for that option. Is there something preventing that option from being implemented? The Nunit output XSLT is still part of the project but there is no way to specify it.

NUnitXmlOutput  
If set to true a HTML output file will be generated in NUnit format.

**Comment by matthid** [comment]
Closing old issue. A PR for this is welcome (if it hasn't been implemented since). Please re-open or create a new issue if this is still missing.
