### ISSUE TITLE
An empty message is written to stderr when the build starts

### ISSUE THREAD

**Issue by marcells** [fsharp/FAKE#777]
it seems that in the released version 3.30.0 an empty message is written to the standard error stream, when the FAKE build starts.

The exit code is still 0 and no exception is thrown. My build succeeds, too. But in the TFS summary the empty messages are displayed.

![emptyerror](https://cloud.githubusercontent.com/assets/1291607/7394495/41a341d4-ee94-11e4-83de-5232f4529d58.png)

In FAKE version 3.29.7 everything works fine.

**Comment by forki** [comment]
Ok there is still an issue with https://github.com/fsharp/FAKE/pull/773

/cc @matthid 

what do we do?

**Comment by matthid** [comment]
I probably know what this is, sending a PR soon if I'm correct...
