### ISSUE TITLE
ChangeWatcher.WatchChanges works only with absolute file patterns

### ISSUE THREAD

**Issue by inosik** [fsharp/FAKE#780]
Verified by this test case in `GlobbingSpecs.cs`:

``` csharp
It should_match_absolute_path = () =>
    IsMatch("docs/**/*.*", new [] { @"C:\dev\project\docs\help.md" });
```

Appending FAKE's `currentDirectory` to the pattern isn't a big deal, but then we should reflect this in the docs, because the [tutorial](http://fsharp.github.io/FAKE/watch.html) shows a non-working sample. The [api docs](http://fsharp.github.io/FAKE/apidocs/fake-changewatcher.html) are correct.

/cc @voiceofwisdom

**Comment by voiceofwisdom** [comment]
I didnt intend for absolute paths to be required, I'll take a look at fixing this.

**Comment by voiceofwisdom** [comment]
IsMatch is supposed to work exactly like the existing glob implementation, except not requiring directory traversal to check for a match. Any differences in behavior I would consider a bug.

**Comment by voiceofwisdom** [comment]
I made FileInclude add its base directory to the glob pattern when calling is match. Fixed in #782

**Comment by forki** [comment]
@voiceofwisdom could you please take a look at https://github.com/fsprojects/Paket/pull/811

I have very strange behaviour.

* clone project
* checkout watcher branch
* run `build.cmd KeepRunning`
* open `docs\content\faq.md` and save the file (no edit needed)

==> The watcher starts to build the docs, but it goes into endless loop since it wrongly (?) detects edits in other content files (which I didn't change or save)

**Comment by marisks** [comment]
I also have issues with relative paths. Don't know if it is same issue.

I have FAKE project in _D:\Projects\fake_test\fake_test\fake_test_ with build.fsx 
I have folder to watch in _D:\Projects\fake_test\watch_folder_ which is two levels up.
And when I configure Watch target to watch for changes to relative directory two levels up, it doesn't detect any changes to that folder.

```
let failureDir  = "../../watch_folder/"
Target "Watch" (fun _ ->
    use watcher = !! (failureDir @@ "*.*") |> WatchChanges (fun changes -> 
        tracefn "%A" changes
    )
    System.Console.ReadLine() |> ignore 
    watcher.Dispose() 
)
```

But when I use absolute path: _D:/Projects/fake_test/watch_folder/_, it works fine.

I created sample project to reproduce the issue: https://github.com/marisks/fake_test

**Comment by voiceofwisdom** [comment]
The watcher uses an alternative implementation of the globbing syntax. It does not support relative paths right now. :disappointed: 

`Fake.Globbing.isMatch` would have to be extended to accept the current directory as well, and take that into account when matching globs.

**Comment by marisks** [comment]
For now I am just using _Path_ as a workaround:

let fullDir = Path.GetFullPath relativeDir

**Comment by matthid** [comment]
The original issue seems to be fixed. Can someone open a new issue for the part which is still open (and explain what the issue is)?
