### ISSUE TITLE
RestorePackageParams to include ConfigFile path property

### ISSUE THREAD

**Issue by puddlewitt** [fsharp/FAKE#781]
It would be very useful to include a "ConfigFile" property for the RestorePackageParams type so that we could do something like...

```
Target "RestorePackages" (fun _ -> 
    solutionDir
        |> RestoreMSSolutionPackages (fun pkgs -> 
            { pkgs with
                OutputPath = "packages"
                ConfigFile = ".\.nuget\nuget.config"
            })
 )
```

https://docs.nuget.org/consume/command-line-reference
https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/RestorePackageHelper.fs#L179-179

**Comment by forki** [comment]
Sounds good. Are you interested in contributing this?

**Comment by puddlewitt** [comment]
I'll give it a try.

**Comment by matthid** [comment]
I guess the PR never made it :). It is still welcome!
