### ISSUE TITLE
Extend the Azure Cloud Service packaging helper

### ISSUE THREAD

**Issue by raymens** [fsharp/FAKE#787]
Currently the Packaging Helper kinda expects the .DLL file to always be the {workerrole}\bin\release{workerrole}.dll file. 

So there is no support for other build configurations or any specific .DLL path.

With this issue I would like to start a discussion to improve the flexibility of the helper.

I was thinking of something along the lines of:

``` fsharp
type PackageCloudServiceWorkerRoleParams =
    /// Will turn into something like /{name}/release/{name}.dll
    | Name of string
    /// Will turn into something like /{name}/{configuration}/{name}.dll
    | Extended of name : string * configuration : string
    /// Will be direct path to the compiled dll
    | DLL of name : string * path : string

/// Configuration details for packaging cloud services.
type PackageCloudServiceParams =
    { /// The name of the Cloud Service.
      CloudService : string
      /// The name of the role in the service.
      WorkerRole : PackageCloudServiceWorkerRoleParams
      /// The SDK version to use e.g. 2.2. If None, the latest available version is used.
      SdkVersion : float option
      /// The output path for the .cspkg.
      OutputPath : string option }
```

**Comment by isaacabraham** [comment]
Mmm. Certainly the initial implementation was a simple "get-up-and-running" one :-) It probably needs some refinement to make it more flexible. Will there always only be one output dll? Can't remember if that's the case or not.

**Comment by raymens** [comment]
I think it automagically adds all dependencies to the package as it does seem to work.

**Comment by matthid** [comment]
We would like to see PRs :)
