### ISSUE TITLE
Discrepancies between MSBuildHelper and TeamCity regarding "MSBuild" environment var

### ISSUE THREAD

**Issue by eggapauli** [fsharp/FAKE#788]
TeamCity understands the environment variable "MSBuild" as directory, where MSBuild.exe lives (i.e. it stupidly appends "\MSBuild.exe" to this path).  
`MSBuildHelper`, on the other hand, uses the environment variable "MSBuild" as full path to MSBuild.exe.  
What do you think of `MSBuildHelper` checking if "MSBuild" points to a directory and if so append "MSBuild.exe" to it?

**Comment by forki** [comment]
sounds good.
