### ISSUE TITLE
Unable to find .net 4.0 dir

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#790]
On windows server 2012 I get this message:

Could not find a part of the path 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0'

See this reference: https://support.microsoft.com/en-us/kb/2765375

In other words it is not possible to have 4.0 directory on WinServer2012. Any idea why this is happening?

**Comment by forki** [comment]
any ideas where this is happening?

**Comment by mynkow** [comment]
I suspect ExecProcess

**Comment by mynkow** [comment]
For now as a temporary solution I did v4.5 => copy/paste/rename => v4.0

**Comment by etishor** [comment]
I run into the same issue. You can try to install windows 7 sdk which contains the v4.0 reference assemblies, but installing win7sdk is a pain (hint: you need to uninstall any vc++ runtime first). 

Running fake on a build agent with win 2012 is not very easy at the moment. Is there anything in fake that needs the v4.0 reference assemblies? 

I've tried changing the supportedRuntime in fake.exe.config to v4.5, but the error remains. 
Even running with a non existing build script triggers the same error:

```powershell
PS> .\bin\FAKE\tools\FAKE.exe --printdetails non-existing.fsx
Build failed.
Error:
Could not find a part of the path 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0'.
-------------------
 FAKE usage
-------------------

    fake.exe [<scriptPath>] [<targetName>] [options]
```

**Comment by forki** [comment]
Could you please retry?

**Comment by forki** [comment]
More details in #794. Closing this one.
