### ISSUE TITLE
KeepAlive calls "Run" just once

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FAKE#791]
I tried using the `KeepAlive` feature following the sample from the docs: http://fsharp.github.io/FAKE/watch.html.

The sample uses `Run "some-target"` to handle the watcher events. When I did this, FAKE only executes the target once (in fact, I had `"some-target" ==> "main"` and when I started the build by running `"main"`, it would run `"some-target"` just once at the beginning and then it would not re-run it).

It does something when the watcher triggers:

```
Shortened DependencyGraph for Target reload:
<== reload

The resulting target order is:
 - reload

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
reload     00:00:07.4558560
Total:     00:00:00.0118503
Status:    Ok
---------------------------------------------------------------------
```

... but it does not actually run anything in the target. My workaround is to put an ordinary function call in the watcher handler, which works perfectly.

Am I misunderstanding something here?

**Comment by forki** [comment]
No you are correct. Use a function call for now

**Comment by evilz** [comment]
Hi, 
What do you mean by "function call"  ?
I Tried to call the watch target in loop but it doesn't work.
What is the tips ?
Thank

**Comment by tpetricek** [comment]
Something like the following should do the trick:

    let generateDocs () = 
        tracefn "Generating docs."

    Target "Watch" (fun _ ->
        use watcher = !! "docs/**/*.*" |> WatchChanges (fun changes -> 
            tracefn "%A" changes
            generateDocs()
        )
        System.Console.ReadLine() |> ignore
        watcher.Dispose() 
     )

**Comment by panesofglass** [comment]
NOTE: If you try to run `WatchChanges` against a shared folder through Parallels -- e.g. run the FAKE script in a Windows terminal against files stored on your Mac's file system -- the changes will not be detected. This may be obvious to some but may otherwise warrant a note in the docs. Would you like me to add such a note to the docs?

**Comment by forki** [comment]
Yes please

**Comment by panesofglass** [comment]
Done! Please see #806

**Comment by panesofglass** [comment]
This article appears to explain the problem I encountered: http://blogs.msdn.com/b/winsdk/archive/2015/05/19/filesystemwatcher-follies.aspx

**Comment by matthid** [comment]
We could re-open a new issue with some concrete improvement suggestions
