### ISSUE TITLE
Paket.Pack does not respect the workingDir param

### ISSUE THREAD

**Issue by theburningmonk** [fsharp/FAKE#792]
I have a repo with multiple projects, each needs to be packaged independently with its own version.
In each project repo there's a `RELEASE_NOTES.md` and `paket.template` file:
e.g.
```
src
|- ProjectA
   |- paket.template
   |- RELEASE_NOTES.md
   |- ProjectA.csproj
|- ProjectB
   |- paket.template
   |- RELEASE_NOTES.md
   |- ProjectB.fsproj
|- ProjectC
   |- paket.template
   |- RELEASE_NOTES.md
   |- ProjectC.csproj
```
My nuget target looks like this:
```fsharp
Target "NuGet" (fun _ ->
    !! "src/**/*.??proj"
    |> Seq.map (fun projPath -> projPath, getReleaseNote projPath)
    |> Seq.iter (fun (projPath, release) ->
        let dirName = System.IO.Path.GetDirectoryName projPath

        Paket.Pack(fun p -> 
            { p with
                WorkingDir = "src/" + dirName
                OutputPath = "bin"
                Version = release.NugetVersion
                ReleaseNotes = toLines release.Notes}))
)
```
where `getReleaseNote` is defined as: 
```fsharp
let getReleaseNote projectPath =
    let dirName  = System.IO.Path.GetDirectoryName projectPath
    let filename = dirName + "/" + "RELEASE_NOTES.md"
    LoadReleaseNotes filename
```

I would have expected Paket.Pack to pack only the working dir, so I'll end up with one package for each based on the latest version in their respective release notes:

- ProjectA.1.0.0.nupkg
- ProjectB.1.0.4.nupkg
- ProjectC.1.1.0.nupkg

but instead I got:

- ProjectA.1.0.0.nupkg
- ProjectA.1.0.4.nupkg
- ProjectA.1.1.0.nupkg
- ProjectB.1.0.0.nupkg
- ProjectB.1.0.4.nupkg
- ProjectB.1.1.0.nupkg
- ProjectC.1.0.0.nupkg
- ProjectC.1.0.4.nupkg
- ProjectC.1.1.0.nupkg

**Comment by theburningmonk** [comment]
Maybe just need to execute paket in the working directory on this line? https://github.com/fsharp/FAKE/blob/5603aef1351db1a6ab98a85c4e776e3661a74c34/src/app/FakeLib/PaketHelper.fs#L66

**Comment by forki** [comment]
yep. that's probably it. Could you please send PR. I'll release ASAP

2015-05-12 14:39 GMT+02:00 Yan Cui <notifications@github.com>:

**Comment by theburningmonk** [comment]
Nope, that wasn't it. 

Looks like that's the way `Paket pack` works, because we're executing paket at `root/.paket/paket.exe` it's iteratively goes through all the project folders and packs each project with the version number we have specified.

Maybe this is a change for Paket's `pack` command, so that it can take in a `workingDir` param?

**Comment by forki** [comment]
I added an optional templateFile parameter to paket pack. See
http://fsprojects.github.io/Paket/paket-pack.html
Would that help?

2015-05-12 15:43 GMT+02:00 Yan Cui <notifications@github.com>:
