### ISSUE TITLE
WatchChanges fails on Mac OSX

### ISSUE THREAD

**Issue by panesofglass** [fsharp/FAKE#805]
Not surprising, but I think we should try to resolve and fix this as `WatchChanges` would be very nice to have cross-platform.

![watchchanges-fails-on-osx](https://cloud.githubusercontent.com/assets/8803/7719273/574d8c10-fe84-11e4-8c12-95a859b6bcbb.png)

**Comment by tpetricek** [comment]
I have seen similar error once, but I have no idea what this is trying to say! 

Apparently, there is some workaround for this: https://github.com/OmniSharp/generator-aspnet/issues/138

**Comment by panesofglass** [comment]
I can confirm that adding `export MONO_MANAGED_WATCHER=false` to my `.bash_profile` fixed the problem. Thanks, @tpetricek!
