### ISSUE TITLE
TeamCity: TeamCity-Block/FAKE-Targets Integration

### ISSUE THREAD

**Issue by irgendwienet** [fsharp/FAKE#807]
TeamCity can show the build log in a tree view where one can collapse and expand messages from one group. The build script can control what messages go into one group.

For FAKE i would like to see everything between "Starting Target: abc" and "Finished Target: abc" in a group names "abc".

To achieve this FAKE should output the following line before or instead of "Starting Target: abc"
`##teamcity[blockOpened name='abc']`
And after or instead of "Finished Target: abc"
`##teamcity[blockClosed name='abc']`

This is only nessaccary when running in an TeamCity environment.

see also https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-BlocksofServiceMessages

Problem to be solved: when a FAKE taged ends with an exception (e.g. unit tests fail) there is currently no "Finished Target: abc" output, but i believe FAKE should close the TeamCity block before printing more text (e.g. the Build Time Report).

**Comment by forki** [comment]
Mhm I thought we close everything correctly. 
Your issues implies that this is not true. ;-) 
I'm open for concrete suggestions.

**Comment by irgendwienet** [comment]
I created the issue #825 (with more details and an example) for my implied bug report in this ticket.

**Comment by matthid** [comment]
I'm about to improve build server integration in FAKE 5. https://github.com/fsharp/FAKE/pull/1819
