### ISSUE TITLE
Create NuGet Package with the Version from the .nuspec

### ISSUE THREAD

**Issue by robertmuehsig** [fsharp/FAKE#830]
Hi

I'm having a trivial problem, but it seems that the NuGetHelper is "too" clever for my use case.

I just want to build a NuGet Package based on a given .nuspec file:

```
<?xml version="1.0"?>
<package >
  <metadata>
    <id>Test.Foobar</id>
    <version>2.0.0</version>
    <title>Test Foobar</title>
    <authors>Code Inside Team</authors>
    <owners>Code Inside Team</owners>
    <licenseUrl>http://blog.codeinside.eu</licenseUrl>
    <projectUrl>http://blog.codeinside.eu</projectUrl>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Hello World</description>
    <releaseNotes>
    </releaseNotes>
    <copyright>Copyright 2015</copyright>
    <tags></tags>
  </metadata>
  <files>
    <file src="CreateNuGetViaFake.dll" target="lib\net45" />
  </files>
</package>
```

The version is in this case 2.0.0. 

I invoke the NuGet Pack via the NuGetHelper:

```
Target "BuildNuGet" (fun _ ->

    NuGet (fun p -> 
    {p with
        OutputPath = artifactsDir
        WorkingDir = "./CreateNuGetViaFake/bin/Debug/"
        })  "./CreateNuGetViaFake/Test.nuspec"
)
```

The resulting .nupkg is unfortunalty called Test.Foobar.0.1.0.0.nupkg and the version number from the nuspec is ignored.

I guess the reason is this line https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/NuGet/NugetHelper.fs#L70 

Currently I have all information inside the actual nuspec file and I need to invoke the actual nuget.exe, which is not as elegant as the NuGetHelper. But the NuGetHelper will always try to invoke NuGet.exe with a - version 0.1.0.0 parameter, which will overwrite the "correct" version from the .nuspec.

My full samples is also on GitHub:
https://github.com/Code-Inside/Samples/tree/master/2015/CreateNuGetViaFake

Unfortunately my F# skills are very very low, so it would be awesome if you could give me a hint. Thanks!

**Comment by forki** [comment]
Yep that's an issue. Can't you still pass it in from the build script? It's
redundant but would work at least.

**Comment by robertmuehsig** [comment]
Well - currently the version number is managed in the .nuspec file. With the actual script I build 3 different packages with different versions.  

Would this be a appropriate workaround:

Open the .nuspec and search for the <version> tag, extract the version number and pass it to the NuGet helper? 
If yes: Is there a another FakeHelper I could reuse or should I try something like this (http://nf2p.com/dot-net/find-in-files-with-f/)

**Comment by forki** [comment]
I think @tpetricek added such a function very recently. Let me check.

**Comment by forki** [comment]
Yes. Take a look at https://github.com/fsharp/FAKE/pull/829/files you can copy this snippet and extract the version of every nuspec. Then pass it again to nuget task. Would that help?

**Comment by inosik** [comment]
Or just use this one: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/NuGet/NugetHelper.fs#L438

**Comment by robertmuehsig** [comment]
:+1: looks promising. 
 
Are you guys planning to implement this as a feature inside the NuGet helper, for example with an extra parameter like this? 

    NuGet (fun p -> 
    {p with
        OutputPath = artifactsDir
        WorkingDir = "./CreateNuGetViaFake/bin/Debug/"
        UseVersionFromNuSpec = true
        })  "./CreateNuGetViaFake/Test.nuspec"

**Comment by forki** [comment]
I personally don't want to spend time in the nuget helper since I changed
nearly everything to paket. But I would accept pull requests.

**Comment by ChrisMissal** [comment]
Does this need an `up-for-grabs` label?

**Comment by TeaDrivenDev** [comment]
I just tried this with 4.60.0, and it seems to have been fixed somewhere along the way. The package file name now always contains the version number specified in the `.nuspec` file.

![2017-04-30 23_42_07-nuget](https://cloud.githubusercontent.com/assets/2247219/25568240/b8761902-2dfe-11e7-80bc-0b21197d9e67.png)

**Comment by robertmuehsig** [comment]
Nice! I think this can be closed now.
