### ISSUE TITLE
Encoding issues when generating NuGet package

### ISSUE THREAD

**Issue by tompazourek** [fsharp/FAKE#831]
I am generating a NuGet package using FAKE and passing a string with my name to the `Authors` parameter. **The *nuspec* file inside the resulting NuGet package (nupkg) is written using some wrong encoding and messes up my name.**

I tried putting my name `"Tomáš Pažourek"` even as `"Tom\u00E1\u0161 Pa\u017Eourek"` to the *build.fsx* script to ensure that encoding of *build.fsx* file does not matter. That did not change anything, the resulting *nuspec* inside the *nupkg* has still `Tom� Pa�ourek` in it.

I also tried explicitly saving the input nuspec template file with UTF-8 encoding, but since the template file contains only ASCII characters, it does not change anything. Putting `<?xml version="1.0" encoding="UTF-8"?>` to the nuspec header also does not change anything as well.

So since the problem cannot be solved neither by changing `nuspec` template or `fsx` build script, I suspect that the problem is in FAKE.

**Comment by inosik** [comment]
You have to pass FAKE the encoding you wish, like this: `fake.exe encoding=utf-8`. Otherwise FAKE takes `System.Text.Encoding.Default`, which appears to be Windows-1252.

**Comment by tompazourek** [comment]
Thank you, that fixes the issue. :) How about documenting this somewhere?

**Comment by PiterGoCompany** [comment]
Presented solution helped me too, but I've problem with adding © symbol into copyright text. Is there any solution for it?

**Comment by dsyme** [comment]
Closing old inactive issue
