### ISSUE TITLE
Nuget Push fails on OS X

### ISSUE THREAD

**Issue by johanlasses** [fsharp/FAKE#834]
There seems to be some problem with the workingDir path when publishing nuget packages from OS X platform. The very same code works on Windows. My Nuget packaging works on OS X if I don't choose to publish the package so nothing wrong in that process.

The error message indicates (**in bold**) the workingDir path has been concatenated twice:

Creating .nuspec file at /Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/package/android/nuget.0.0.2.0.nuspec
Created nuspec file /Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/package/android/nuget.0.0.2.0.nuspec
mono  /Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/.nuget/nuget.exe pack -Version 0.0.2.0 -OutputDirectory "/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/nuget" "nuget.0.0.2.0.nuspec"  
Deleting /Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/package/android/nuget.0.0.2.0.nuspec
/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/.nuget/nuget.exe push "/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/nuget/byBrick-Xamarin.Droid.0.0.2.0.nupkg" PRIVATEKEY -s http://mynugetserver/ in WorkingDir: /Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/package/android Trials left: 5
Directory **'/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/package/android/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/nuget'** not found.

**Comment by johanlasses** [comment]
I think the error message actually is a concat between my workingDir and Nuget path.

**'/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/package/android/Users/jenkins-bybrick/jenkins/workspace/byBrick.Xamarin-DEPLOY/byBrick.Xamarin/build/nuget'**

**Comment by inosik** [comment]
Tried it without FAKE, it's an issue in NuGet.

You could try to set another working directory, or just use Paket for pushing: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/PaketHelper.fs#L75

**Comment by matthid** [comment]
Closing because the issue seems to be external.
