### ISSUE TITLE
Documentation should be clearer around passing arguments to FAKE

### ISSUE THREAD

**Issue by mastoj** [fsharp/FAKE#835]
Just started playing around with FAKE and one of the first thing I tried to figure out how arguments should be passed. Discussed it with @forki here: https://twitter.com/TomasJansson/status/613352066883448832 and the issue is that the API is somewhat inconsistent. Since it is inconsistent it is hard to change, we don't know how the users around the world execute the FAKE scripts. 

The things I tried can be found here: https://gist.github.com/mastoj/2a47953915c2698b9419

I think one way to split it in the long run is to change the documentation here, http://fsharp.github.io/FAKE/commandline.html, so it contains the recommended way to pass arguments to the FAKE.

My suggestion is to add one extra argument to fake.exe:

     fake.exe [<buildScriptPath>] [<targetName>] [options] [script options]

the difference between `options` and `script options` is that `options` are for `FAKE` while the `script options` are for the actual build script. That's how I would expect it to work at least, but it might also add one extra complexity and contribute to the inconsistency.

**Comment by dsyme** [comment]
Closing old inactive suggestion. Please send a PR for this if you'd like the issue addressed.
