### ISSUE TITLE
Configure Site Id when creating a IIS Website

### ISSUE THREAD

**Issue by petekcchen** [fsharp/FAKE#844]
There's a need that when we create a site, we need to assign its site ID. Currently i don't see any parameter in https://github.com/fsharp/FAKE/blob/master/src/app/Fake.IIS/IISHelper.fs that allows for site ID passed in, can we have this feature implemented? thanks.

**Comment by dmorgan3405** [comment]
I can put a pull request together for this feature. Is it still something you are interested in? @petekcchen

**Comment by petekcchen** [comment]
yes, it would be great if you can put a pull request for this feature, thanks.

**Comment by dmorgan3405** [comment]
Alright I have submitted a potential solution for this feature. Hopefully it will fit your needs. 
If you need any assistance, please feel free to reach out.

**Comment by dmorgan3405** [comment]
@petekcchen the feature is available in release 4.1.3 (and above), please verify it meets your needs. If so, we can close the issue.
