### ISSUE TITLE
SemVerHelper and Build

### ISSUE THREAD

**Issue by omares** [fsharp/FAKE#847]
According to the SemVer "RFC" the build should be denoted using a plus sign after the patch or pre-release version. See point 10 of http://semver.org/

The current version of the SemVerHelper adds the build number by adding a dash and a dot to the end of the patch version.

The following SemVerInfo type is translated to `1.2.3-.9` but should be `1.2.3+9`

```
{
    Major: 1;
    Minor: 2;
    Patch: 3;
    PreRelease : None;
    Build: "9" 
}
```

Also `SemVerHelper.parse` is unable to parse versions that include build information separated by a plus sign.

**Comment by omares** [comment]
Fixed `.ToString()` Method. PR will follow if issue is accepted. :)

````
    override x.ToString() =
        sprintf "%d.%d.%d" x.Major x.Minor x.Patch +
         (match x.PreRelease with
          | Some preRelease -> "-" + preRelease.Name 
          | _ -> "") +
         (if isNotNullOrEmpty x.Build then "+" + x.Build else "")
```

**Comment by baronfel** [comment]
Should we attempt to unify the SemVer parsers in Paket and Fake, so that we don't have this issue in multiple places? Paket's parser is [here](https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/SemVer.fs).

**Comment by putschoeglwe** [comment]
just encountered the same bug in FAKE 4.17.1

has anyone info on the progress on this fix?

**Comment by matthid** [comment]
> Should we attempt to unify the SemVer parsers in Paket and Fake, so that we don't have this issue in multiple places? Paket's parser is here.

FAKE will (hopefully soon) be splitted in modules. So there will be a Fake.Core.SemVer module/nuget package which we can re-use here in Paket. That should fix these kind of things (there are actually other code duplications between FAKE and Paket as well)

**Comment by matthid** [comment]
Closing in favor of https://github.com/fsharp/FAKE/pull/848
