### ISSUE TITLE
Syntax Error crashes FAKE.exe

### ISSUE THREAD

**Issue by feelingsofwhite** [fsharp/FAKE#852]
Using FAKE 3.35.5, on Windows 2012 R2 Standard, the following build file will crash FAKE.
### Problem Description

The script demonstrating the bug can be observed below (eg example.fsx)

```
#r "tools/FAKE/tools/FakeLib.dll"
open Fake

Target "testy"(fun _ ->
    ["zaro"] |> Map.map(fun s -> s.Replace("zaro", 1) |> Log "boogs"
)

Target "second" DoNothing
```

invocation is
`FAKE example.fsx testy`

notice the missing closing parenthesis after "1)".
### Actual Behavior

on Windows 2012 R2 Standard, this yeilds not a nice syntax error console dump, but a Windows GUI "F# Make Command line tool has stopped working / Checking for a solution to the problem..."
Clicking Debug yields slightly more details:
System.ExecutionEngineException was unhandled
Message: An unhandled exception of type 'System.ExecutionEngineException' occurred in FSI-ASSEMBLY.dll
### Contrast Actual Behavior With fsi

`fsi example.fsx` yields an error to the console like

```
D:\workingdir\example.fsx(9,1): error FS0010: Unexpected identifier in expression
```
### Contrast Actual Behavior With Fake's behavior on other errors

change the `1)` to `1))` in the example (ie, resolve the syntax error but introduce a type incompatibility between the number 1 and the .Replace second string parameter), and you will get console output like

```
F# Interactive for F# 3.1 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading D:\dev\copas\Scripts\example.fsx]


example.fsx(6,17): error FS0001: Type mismatch. Expecting a
    string list -> 'a
but given a
    Map<'b,'c> -> Map<'b,'d>
The type 'string list' does not match the type 'Map<'a,'b>'
```
### Expected Behavior

`FAKE` gracefully fails to the console with a syntactical message analogous to `fsi`

**Comment by matthid** [comment]
I think this has been fixed with a FCS update. Feel free to re-open or comment if not.
