### ISSUE TITLE
WatchChanges only runs target once

### ISSUE THREAD

**Issue by wastaz** [fsharp/FAKE#853]
I'm having some issues with `WatchChanges` which is quite strange

If I use it as in the documentation then everything works as expected. It runs `GenerateDocs` everytime I change something in the folder.

    Target "GenerateDocs" (fun _ ->
        tracefn "Generating docs."
    )

    Target "Watch" (fun _ ->
        use watcher = !! "docs/**/*.*" |> WatchChanges (fun changes -> 
            tracefn "%A" changes
            Run "GenerateDocs"
       )

        System.Console.ReadLine() |> ignore //Needed to keep FAKE from exiting

        watcher.Dispose() // Use to stop the watch from elsewhere, ie another task.
    )

However if I replace the target `GenerateDocs` here with a target that does something more than a trace, let's say for instance this one

    Target "BuildApp" (fun _ ->
        !! "**/*.fsproj"
        |> MSBuildRelease buildDir "Build"
        |> Log "AppBuild-Output: "
    )

Then it will only run this target once. The first time I change something it triggers this target and it runs fine. Everytime after that however I can see that the watcher is triggering, but the target is not being run.

I just get a message like this, and then nothing more:

    Shortened DependencyGraph for Target BuildApp:
    <== BuildApp
       <== Clean

    The resulting target order is:
     - Clean
     - BuildApp

If I extract the code from the target above and put it in a function instead and then call that function instead of `Run "TargetName" ` then everything works perfect. But in that case the build dependency management fails since I'm not actually running the targets that have the dependencies :( I can of course just extract these into functions as well and call them in order...but then I feel like I'm missing something.

Am I doing something stupid or is this a bug?

**Comment by voiceofwisdom** [comment]
I assumed that that would work when I wrote the docs for `WatchChanges`. Having a separate function that gets called is the current work around. I can change the docs to have it be a separate function, it seems very odd for it to not be possible to run a Target multiple times.

@forki would you like me to change the docs, or leave this as an open issue?

**Comment by dsyme** [comment]
@xavierzwirtz Please submit a PR to change the docs.  I'll close this issue until then, thanks
