### ISSUE TITLE
Documentation on how to include multiple framework versions in Paket.Pack NuGet build

### ISSUE THREAD

**Issue by varon** [fsharp/FAKE#861]
I've used XML definitions in the csproj/fsproj for different framework versions.

I've got them all building correctly and outputting them into `net35`, `net40`, `net45` directories, but these aren't being included when I call the `Paket.Pack` function - only the `net45` version is included.

I know it's possible to achieve this ([FsPickler](https://github.com/nessos/FsPickler) does it) but I've not been able to replicate the process.

This issue is requesting greater documentation for the `Paket` module, as well as how to make a NuGet package with multiple framework versions included.

Perhaps @eiriktsarpalis might have some input on this matter.

[You can view my attempt here](https://github.com/varon/aetherTemp)

**Comment by eiriktsarpalis** [comment]
@varon In FsPickler I basically just manually include all required files, see https://github.com/nessos/FsPickler/blob/master/src/FsPickler/paket.template#L29

**Comment by varon** [comment]
Thanks @eiriktsarpalis - I've got it working now. I had the template files in place, but it failed silently when it wasn't able to find files to include. It seems the critical part I missed was this: [Files must be specified relative to the template file location](https://fsprojects.github.io/Paket/template-files.html#Files).

I think there's three points we want to adress before the issue gets closed:

 1. **FAKE (or Paket?) should warn if it can't include files specified in `paket.template`.**
    
    If this is the responsibility of Paket, then we should probably open up an issue there.

 1. **We should document how to target multiple framework versions.**
    
    As @eiriktsarpalis has pointed out, this is done by: Running separate builds for each of the versions, and then manually including them by editing the `paket.template` file.  I'm not sure if this is FAKE or Paket's responsibility, but it seems like a common use of FAKE.

 1. **We should consider providing a better way to target multiple framework versions.**
    
  Editing the cs/fsproj files by hand was pretty painful, but it might be a necessary evil in this case. Perhaps someone from FAKE's side has an idea on how to do this more elegantly.

**Comment by matthid** [comment]
I read this all as improvements in paket. Please open an issue there.
