### ISSUE TITLE
iOSBuild doesn't generate IPA file

### ISSUE THREAD

**Issue by hossambarakat** [fsharp/FAKE#862]
Hi,

I am using the following target to build Xamarin iOS project. The build succeed however IPA file not generated. Am I missing anything?

```
Target "ios-adhoc" (fun () ->
    RestorePackages "solutionname.sln"

    iOSBuild (fun defaults ->
        {defaults with
            ProjectPath = "solutionname.sln"
            Configuration = "Ad-Hoc|iPhone"
            Target = "Build"
        })
)
```

**Comment by jwood803** [comment]
I'm just randomly curious...are you building this off a Mac? I have had some issues where the IPA doesn't seem to generate for me if I build a Xamarin iOS project off Windows with Visual Studio.

**Comment by thomasvdb** [comment]
Have you configured the Ad-Hoc build configuration in Xamarin Studio to generate an IPA file?

**Comment by BlueHatbRit** [comment]
This is something that we just struggled with for three days due to a lack of documentation. This is what you'll want:

```
Target "ios-adhoc" (fun () ->
    RestorePackages "solutionname.sln"

    iOSBuild (fun defaults ->
        {defaults with
            ProjectPath = "solutionname.sln"
            OutputPath = "my-folder"
            Target = "Build"
            Configuration = "Ad-Hoc"
            Platform = "iPhone"
            BuildIpa = true
        })
)
```

The configuration and platform are separate and the BuildIpa is used to tell it to produce an Ipa or not. You'll also need the OutputPath to define where to put the Ipa when it's done.

**Comment by matthid** [comment]
Probably a msbuild problem. Feel free to re-open if there is anything we can do from the FAKE side of view.
