### ISSUE TITLE
How do I just iterate over FileIncludes?

### ISSUE THREAD

**Issue by Aaronontheweb** [fsharp/FAKE#867]
I cannot figure out how to just iterate over the contents of a FileIncludes inside my own FAKE script (using a custom test runner in Akka.NET.)

If I want to iterate over the computed output of a https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/Globbing/FileSystem.fs, how would I go about doing that? I literally just want a list of assemblies that satisfy my search expression that I can iterate over.

**Comment by cdrnet** [comment]
`FileIncludes` implements `IEnumerable<string>` (`string seq`), so the usual functions in the `Seq` module like `Seq.map` and `Seq.iter` should work, e.g.

    !! "*.dll" |> Seq.iter (printfn "%s")

**Comment by Aaronontheweb** [comment]
Awesome! Thanks @cdrnet, this solved my problem.
