### ISSUE TITLE
.fake directory

### ISSUE THREAD

**Issue by mynkow** [fsharp/FAKE#871]
Today I got this directory to the root of my project.

1) What is the purpose?
2) Please remove it!

http://gyazo.com/0587baf1c80534875f15a551496d13eb

**Comment by forki** [comment]
so you are using the 4.0 alpha!? ;-)

the purpose is to cache the compiled build script and therefor speed up FAKE startup time.
You can just add it to your .gitignore file and everything should be fine.

**Comment by mynkow** [comment]
I think I am not using the alpha. Probably there is a problem with the nuget package and how it is built.

echo Downloading latest version of Fake.exe...
%NUGET% "install" "FAKE" "-OutputDirectory" "%TOOLS_PATH%" "-ExcludeVersion" "-Prerelease"

**Comment by forki** [comment]
`-Prerelease` instructs NuGet to download the latest version including alpha and beta versions.

**Comment by mynkow** [comment]
Omg, it really installs the alpha

http://gyazo.com/baae4dfc7f5bbfda9a329258298b7aec

Probably -ExcludeVersion is not working for some reason?

**Comment by forki** [comment]
no, it's the `-prerelease`. just remove that and you get latest 3.x

**Comment by mynkow** [comment]
You are right. 10x.

Can you please explain how the cache works in 4.0 and what is included?

**Comment by forki** [comment]
see https://github.com/fsharp/FAKE/pull/859

**Comment by xavierzwirtz** [comment]
It takes the dynamic assembly generated by FSI and saves it into the .fake directory. Also saves a list of all loaded dlls and there path so that they can be loaded on next run.

**Comment by xavierzwirtz** [comment]
@mynkow see [here](https://github.com/fsharp/FAKE/commit/9d76eeed9da3abdac2aae775932a703d9ea0d6fd) for a detailed explanation of the caching mechanism.
