### ISSUE TITLE
Request: "Finally" cleanup target

### ISSUE THREAD

**Issue by alexfoxgill** [fsharp/FAKE#873]
Sometimes a build will fail but you want to run some cleanup code regardless - for example, on one of my sites I need to switch two files at the beginning and end of the build. Right now if the build fails my second switch won't happen and I have to do it manually.

**Comment by forki** [comment]
We already support "final targets". See http://fsharp.github.io/FAKE/specifictargets.html

**Comment by alexfoxgill** [comment]
Apologies! I missed that in the documentation
