### ISSUE TITLE
How to publish a nuget package into the TeamCity nuget server?

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#874]
I mean:
* create a package
* publish it on the same TC server just as TC's "NuGet" build step does

**Comment by forki** [comment]
IIRC you just need to add a matching pattern to the "artifacts" in the project settings.

![image](https://cloud.githubusercontent.com/assets/57396/8824687/6a60ed58-3078-11e5-9492-d70c167f93cf.png)

**Comment by forki** [comment]
also make sure nuget is enabled at http://teamcity/admin/admin.html?item=nugetServerSettingsTab

**Comment by vasily-kirichenko** [comment]
Ah! All packages are automatically published. Cool.

**Comment by forki** [comment]
one important thing to remember: teamcity cleans artifacts automatically from time to time (this includes nuget packages). Look into your server's settings and disable that.

**Comment by vasily-kirichenko** [comment]
Yes, I know. We already create a package, but I don't know it's published all this time :)
