### ISSUE TITLE
NuGet task does not take into account `Dependencies` property

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#875]
``` fsharp
NuGet (fun p ->
        { p with 
            NoPackageAnalysis = true
            Properties = [ "configuration", config ]
            OutputPath = out
            TimeOut = TimeSpan.FromMinutes 5.
            WorkingDir = "."
            Version = version
            ToolPath = "./packages/NuGet.CommandLine/tools/nuget.exe"
            Dependencies = 
                [ "ExtCore", GetPackageVersion "./packages/" "ExtCore"
                  "mongocsharpdriver", GetPackageVersion "./packages/" "mongocsharpdriver"
                  "NLog", GetPackageVersion "./packages/" "NLog"
                  "ZetaLongPaths", GetPackageVersion "./packages/" "ZetaLongPaths"
                  "FSharp.Core", GetPackageVersion "./packages/" "FSharp.Core" 
                  "AlphaFS", GetPackageVersion "./packages/" "AlphaFS"
                  "FSharpx.Collections", GetPackageVersion "./packages/" "FSharpx.Collections"
                  "FsPickler", GetPackageVersion "./packages/" "FsPickler"
                  "Newtonsoft.Json", GetPackageVersion "./packages/" "Newtonsoft.Json" ]
        }) "_scripts/1.nuspec"
```

Result:

![image](https://cloud.githubusercontent.com/assets/873919/8825514/71d70170-3088-11e5-80f1-ced5984c1836.png)

**Comment by forki** [comment]
Sounds like your nuspec template is missing the corresponding placeholder

**Comment by vasily-kirichenko** [comment]
Ah!

**Comment by vasily-kirichenko** [comment]
Maybe NuGet task should fail in this case?

**Comment by forki** [comment]
Mhm. Maybe that would be a good PR

**Comment by vasily-kirichenko** [comment]
I totally agree :)

**Comment by forki** [comment]
don't get me wrong, but personally I don't want to invest to much time in the NuGet task ;-)

**Comment by KevM** [comment]
@forki Can we get some guidance on the preferred way to create nugets in FAKE?

**Comment by forki** [comment]
@kevm are you using paket?

**Comment by ChrisMissal** [comment]
@KevM Maybe not the perfect example, but I have a working example here: https://github.com/ChrisMissal/bootstrap-slider-nuget – FWIW, [Creating NuGet packages](http://fsharp.github.io/FAKE/create-nuget-package.html) worked well for me. Did you see issues with it?

**Comment by KevM** [comment]
@ChrisMissal I reached out on the Gitter chat about a problem I was having. It was likely my usage. 

My concern was I keep seeing references to FAKE Nuget support not being preferred to using Paket.

**Comment by forki** [comment]
It's still absolutely fine to use nuget for pack and push. Even fake does that itself. It will be maintained forever, but don't expect me to create big new features in that space.

**Comment by matthid** [comment]
"forever" ;)

**Comment by matthid** [comment]
Anyway a PR is welcome.
