### ISSUE TITLE
atom-fsharp not working with FAKE 4

### ISSUE THREAD

**Issue by forki** [fsharp/FAKE#879]
When I clone https://github.com/fsprojects/atom-fsharp/pull/102 and run it twice I get an error:

![image](https://cloud.githubusercontent.com/assets/57396/8849458/19909fae-3140-11e5-91bf-71b435ef6491.png)

@xavierzwirtz ideas?

**Comment by forki** [comment]
after adding --nocache it builds again. Still would be nice to see this working.

**Comment by dsyme** [comment]
closing old issue in spring cleaning
