### ISSUE TITLE
Cache not working with type providers

### ISSUE THREAD

**Issue by inosik** [fsharp/FAKE#881]
When I run the build-script of a project, the first run creates the cache, with this `*_references.txt` file:
```
C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll
D:\project\packages\FAKE\tools\FAKE.exe
D:\project\packages\FAKE\tools\FakeLib.dll
D:\project\packages\FAKE\tools\FSharp.Core.dll
D:\project\packages\FAKE\tools\UnionArgParser.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_de_b77a5c561934e089\mscorlib.resources.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
D:\project\packages\FAKE\tools\FSharp.Compiler.Service.dll
D:\project\packages\FAKE\tools\HashLib.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Framework\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Framework.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Tasks.v4.0\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Tasks.v4.0.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Utilities.v4.0\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Utilities.v4.0.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Tasks.v4.0.resources\v4.0_4.0.0.0_de_b03f5f7f11d50a3a\Microsoft.Build.Tasks.v4.0.resources.dll
C:\windows\Microsoft.Net\assembly\GAC_32\ISymWrapper\v4.0_4.0.0.0__b03f5f7f11d50a3a\ISymWrapper.dll
D:\project\packages\FSharp.Configuration\lib\net40\FSharp.Configuration.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Caching\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.Caching.dll
D:\project\packages\FSharp.Configuration\lib\net40\SharpYaml.dll

C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll
C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_de_b77a5c561934e089\System.resources.dll

```

*Notice the empty line after __SharpYaml.dll__*

When running the second time, I get this:
```
Build failed.
Error:
Die Zeichenfolge kann keine Länge von 0 (null) haben.
```
Which is telling me, that a string cannot be empty.

When I remove the empty line after SharpYaml.dll and run FAKE again, I get:
```
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. 
  ---> System.IO.FileNotFoundException:
  Die Datei oder Assembly "tmp217E, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
   bei <StartupCode$FSI_0001>.$FSI_0001_Build$fsx.main@()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   bei System.Type.InvokeMember(String name, BindingFlags invokeAttr, Binder binder, Object target, Object[] args)
   bei Fake.FSIHelper.runFAKEScriptWithFsiArgsAndRedirectMessages(Boolean printDetails, FsiArgs _arg1, IEnumerable`1 args, FSharpFunc`2 onErrMsg, FSharpFunc`2 onOutMsg, Boolean useCache, Boolean cleanCache) in C:\code\fake\src\app\FakeLib\FSIHelper.fs:Zeile 219.
```

A simple script without any `#r`s works just fine, also running FAKE with `-nc`.

**Comment by forki** [comment]
do you have a minimal repro sample?

/cc @xavierzwirtz

**Comment by xavierzwirtz** [comment]
Looks like theirs another dynamic assembly getting generated during the `fsi` execution. It doesnt have a `Location` on disk, so its not possible to save it for reloading later. A minimal repro would be very handy, I think I know how to fix this, need something to test with though.

**Comment by inosik** [comment]
Here you go: https://gist.github.com/inosik/66ba5df5bf2f79300470
On mono I get an other error message, similar to the one in fsprojects/FSharp.Configuration#27, except that it can't find SharpYaml.dll.

**Comment by xavierzwirtz** [comment]
You're right, its defiantly type providers. They create a dynamic assembly that does not exist on disk. Looking into the gen'ed assembly.

**Comment by xavierzwirtz** [comment]
I cannot find a way to get the AssemblyBuilder that was used to generate the dynamic assembly. Modifications would have to be made to `FSI` to have it expose all generated assemblies AssemblyBuilder. According to the [reference source](http://referencesource.microsoft.com/#mscorlib/system/reflection/emit/assemblybuilder.cs,68) we cannot get an assembly's AssemblyBuilder without it being explicitly exposed to us. I have added a check for these assemblies, the cache is not saved if they were generated.

**Comment by inosik** [comment]
Then I will rewrite the script or just run without caching.

Thanks for your efforts anyways, I really appreciate it.

**Comment by xavierzwirtz** [comment]
http://nessos.github.io/Vagabond/

I'm thinking we could fix this issue using some of the techniques that Vagabond uses. They are somehow saving dynamic assemblies and sending them over the wire.

**Comment by xavierzwirtz** [comment]
It feels like this is a complicated and general enough problem that it should be spun off into an external library. A library that provides a interactive session that can be saved to disk and reused later.

**Comment by eiriktsarpalis** [comment]
@xavierzwirtz this should be possible in principle using Vagabond.

**Comment by eiriktsarpalis** [comment]
@xavierzwirtz it also assumes that all the bindings you have created are serializable.
