### ISSUE TITLE
Can't build until .fake local hidden folder is removed

### ISSUE THREAD

**Issue by gsscoder** [fsharp/FAKE#885]
Sometimes it's impossibile to perform a build via **Fake** from _Windows 7_ *PowerShell*:
```PowerShell
No version specified. Downloading latest stable.
Paket.exe 1.21.1.0 is up to date.
2 seconds - ready.
Build failed.
Error:
Could not load file or assembly 'file:///P:\CommandLine\.fake\build.fsx_0AD6288A.dll' or one of its dependencies. Operat
ion is not supported. (Exception from HRESULT: 0x80131515)
InnerException:
An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in
previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so th
is load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources
switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
-------------------
 FAKE usage
-------------------

    fake.exe [<scriptPath>] [<targetName>] [options]

    scriptPath: Optional.  Path to your FAKE build script.  If not specified, FAKE will use the first .fsx file in the w
orking directory and fail if none exists.

    targetName: Optional.  Name of the target you wish to run.  This will override the target you specifed to run in the
 build script.
                           When targetName is equal --listTargets or -lt FAKE will list the targets with their dependenc
ies.

    Options:

        --envvar [-ev] <string> <string>: Set environment variable <name> <value>. Supports multiple.
        --envflag [-ef] <string>: Set environment variable flag <name> 'true'. Supports multiple.
        --logfile [-lf] <string>: Build output log file path.
        --printdetails [-pd]: Print details of FAKE's activity.
        --version [-v]: Print FAKE version information.
        --fsiargs [-fa] <string> ...: Pass args after this switch to FSI when running the build script.
        --boot [-b] <string> ...: Boostrapp your FAKE script.
        --break [-br]: Pauses FAKE with a Debugger.Break() near the start
        --single-target [-st]: Runs only the specified target and not the dependencies.
        --nocache [-nc]: Disables caching of compiled script
        --help [-h|/h|/help|/?]: display this list of options.

--------------------
 Classic FAKE usage
--------------------
FAKE.exe [buildScript] [Target] Variable1=Value1 Variable2=Value2 ...
PS P:\CommandLine>
```
I've to remove `.fake` local hidden folder along with its content:
```PowerShell
PS P:\CommandLine> ls .\.fake

    Directory: P:\CommandLine\.fake

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-----        25/07/2015     07:29       8192 build.fsx_0AD6288A.dll
-----        25/07/2015     07:29       3978 build.fsx_0AD6288A_config.xml
```
To make it work again I've to `rm .\.fake`, as said.

Thanks in advance! And thanks to all authors and main contributors for sharing this wonderful tool for our _amazing beloved_ **F#**!!! :+1:

**Comment by forki** [comment]
@xavierzwirtz any ideas?

**Comment by gsscoder** [comment]
@forki, if this can help, I've another information.
This thing happens with regularity:
1. A build completes with success.
2. The following fails.
3. I remove .fake.
4. GOTO (1)

**Comment by xavierzwirtz** [comment]
Cloned the repo on my machine. Builds work repeatedly on my machine.

You have it on a `P:` drive, does it work if you put it on `C:` instead?

**Comment by xavierzwirtz** [comment]
Hmm, looked at the error message more. Is `P:` a network share that you have mapped? It looks like this is .Net not liking the location you are trying to load from.

**Comment by xavierzwirtz** [comment]
I believe FAKE `4.0.2` will fail more gracefully in this situation. Instead of crashing the whole instance of FAKE it will fall back to executing the script through FSI.

**Comment by gsscoder** [comment]
@xavierzwirtz, yes `P:` is a network share between VirtualBox Windows 7 and OS X Yosemite.

**Comment by xavierzwirtz** [comment]
Can you try putting 
```xml
<configuration>
    <runtime>
        <loadFromRemoteSources enabled="true"/>
    </runtime>
</configuration>
```

Into `.\packages\FAKE\tools\FAKE.exe.config`

If that works I will put in a PR for it.

**Comment by gsscoder** [comment]
:+1: yes, @xavierzwirtz, it did the trick!

Now I can run it every time I want without problem!

Thanks for support.

**Comment by gsscoder** [comment]
I'm sorry to re-open, but the issue seems back. (Don't know what's changed).

If I've to post something to help the team resolve it, please let me know...

**Comment by xavierzwirtz** [comment]
Does `.\packages\FAKE\tools\FAKE.exe.config` still have `loadFromRemoteSources` in it?

**Comment by gsscoder** [comment]
My fault, I've I should have checked... I don't know how it could be gone.

Anyway now it works again. If issue comes back, I'll re-add `loadFromRemoteSources`.

Thanks again!

**Comment by xavierzwirtz** [comment]
That should be in the latest version of fake. Updating to it should keep 
this fixed.

**Comment by gsscoder** [comment]
@xavierzwirtz, yes, after `paket update` the setting persists. Wonderful!

**Comment by xavierzwirtz** [comment]
:smile:

**Comment by forki** [comment]
So the latest release is correct?

**Comment by gsscoder** [comment]
@forki, after running `paket update` I can run `build.cmd` script over and over again, without problems. :joy:
