### ISSUE TITLE
Is it possible to make MSBuild action to use VS 2013 having VS 2015 installed?

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsharp/FAKE#886]

**Comment by forki** [comment]
you mean the "old" MSBuild version?
there is a check for the environment var: https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs#L32

**Comment by forki** [comment]
it also looks into appsettings file

**Comment by vasily-kirichenko** [comment]
Thanks, trying 
```fsharp
Environment.SetEnvironmentVariable("MSBuild", @"c:\Program Files (x86)\MSBuild\12.0\Bin\")
```
in the build script.
