### ISSUE TITLE
xUnit2 task does not detect failed tests when running on TeamCity

### ISSUE THREAD

**Issue by mthierba** [fsharp/FAKE#888]
The xUnit2 task is using the `xunit.console.exe` exit code to determine whether a test run succeeded or not. However, when in `-teamcity` mode (explicitly set or automatic), the console runner always seems to return 0 (tested with 2.0.0 as well as with the latest 2.1.0-beta3), hence a FAKE script won't stop at this point, and will simply move on to the next target.

As a workaround, I'm now letting xUnit emit an XML report which I'm then parsing to determine any failed tests and whether or not to terminate the FAKE script run, like so:

```
    let xmlPath = testResultsDir @@ "xunit2.xml" |> FullName
    let htmlPath = testResultsDir @@ "xunit2.html" |> FullName

    !! testAssemblies
    |> xUnit2 (fun p -> 
        { p with  
            TimeOut = TimeSpan.MaxValue
            XmlOutputPath = Some xmlPath
            HtmlOutputPath = Some htmlPath
            WorkingDir = Some buildDir })
    if not isLocalBuild then
        (testResultsDir @@ "xunit*.*ml") |> PublishArtifact

    let xunitErrors = XMLRead true xmlPath "" "" "//assembly/@failed"
                      |> Seq.map (Int32.Parse)
                      |> Seq.sum
    if not isLocalBuild && xunitErrors > 0 then failwithf "%i xUnit tests failed" xunitErrors
```

Putting this here mainly for informational purposes, but also to hear opinions how to address the issue. Should this be considered a bug of the xunit runner, or should FAKE's xUnit2 task change its behavior accordingly?

**Comment by derwasp** [comment]
I am using the same runner and to stop the build I set `Execute Step: Only if build status is successful` for the build steps in the Teamcity itself. In the script I have `ErrorLevel = DontFailBuild`, so the script exits properly, but the next build step is not executed if there are tests failing.

It works for me because I have my steps set up in the teamcity. I do not use `==>`.

**Comment by SeanFarrow** [comment]
Ideally, Fake would fail the build, with the number of tests that fail and the details of said failing tests. Where in your above script are you defining the local build variable?

**Comment by mthierba** [comment]
@SeanFarrow `isLocalBuild` is provided by FAKE: https://github.com/fsharp/FAKE/blob/ab0bacd2f21ee486879a3ea2a765f15b536181fb/src/app/FakeLib/BuildServerHelper.fs#L111-111

**Comment by SeanFarrow** [comment]
@mthierba<https://github.com/mthierba>
Nice, I didn’t know about that! Are these environment variables that are used?

**Comment by mthierba** [comment]
@SeanFarrow - Yes. That is using environment vars.

**Comment by matthid** [comment]
I don;t have a good answer either. But I'd suggest to report this to the xunit guys
