### ISSUE TITLE
AWS Helper - question

### ISSUE THREAD

**Issue by tbenade** [fsharp/FAKE#889]
Hi,

We would love to have a crack at starting on an Amazon Web Services helper. Initial targets would be the management of CloudFormation stacks.

http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html

On poking around the code base I noticed little or no dependencies on vendor SDK's example AppVeyor and Azure. 

Before continuing was hoping to get some insights on general philosophies and ambitions. Is there a conscious effort not to drag in SDK's can I use the AWS one (nuget/paket) or should I avoid it and use the Http interface rather?

Thanks!

**Comment by forki** [comment]
Hi, we usually assume a command line tool is available and try to call that
