### ISSUE TITLE
The type 'string' does not support the operator '!+'

### ISSUE THREAD

**Issue by JefClaes** [fsharp/FAKE#912]
I downloaded the FAKE-calculator example, and when I execute completeBuild.bat I get an error. I tried searching master via Github for the definition of the (!+) operator but failed to find it. Is it my machine or is the example broken?

Installing 'FAKE 4.1.3'.
Successfully installed 'FAKE 4.1.3'.

F# Interactive for F# 4.0 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\Users\slotsgames\Downloads\FAKE-Calculator\FAKE-Calculator\CompleteBuild.fsx]

CompleteBuild.fsx(65,20): error FS0001: The type 'string' does not support the operator '!+'

Press any key to continue . . .

**Comment by forki** [comment]
yep. I need to update thate tutorial.
just use !! instead and remove the line with `|> Scan`

**Comment by forki** [comment]
fixed

**Comment by JefClaes** [comment]
Yep, that worked. Thanks.

**Comment by forki** [comment]
I updated the sample...
