### ISSUE TITLE
add xmldoc description to --list-targets

### ISSUE THREAD

**Issue by ctaggart** [fsharp/FAKE#922]
Only today did I discover the [--list-targets](http://fsharp.github.io/FAKE/specifictargets.html) option. Besides being able to [make it a default option](https://github.com/fsharp/FAKE/pull/921), it would be great if it included the description from the xmldoc.

![image](https://cloud.githubusercontent.com/assets/80104/9430696/40d604c8-49b4-11e5-9ddc-2353e46ddc9b.png)

It would be even better if `listTargets()` included the documentation for the target.
![image](https://cloud.githubusercontent.com/assets/80104/9430704/77a4430c-49b4-11e5-8838-ccb257436ee7.png)

Perhaps it should be the xmldoc of the target function.

``` fsharp
/// start a web server and watch for slide edits
let keepRunning() =
    use watcher = !! (slidesDir + "/**/*.*") |> WatchChanges (fun changes ->
         handleWatcherEvents changes
    )
    startWebServer ()
    traceImportant "Waiting for slide edits. Press any key to stop."
    System.Console.ReadKey() |> ignore
    watcher.Dispose()

Target "KeepRunning" keepRunning

Target "ReleaseSlides" (
    /// push the slides to GitHub gh-pages branch
    fun _ ->
    if gitOwner = "myGitUser" || gitProjectName = "MyProject" then
        failwith "You need to specify the gitOwner and gitProjectName in build.fsx"
    let tempDocsDir = __SOURCE_DIRECTORY__ @@ "temp/gh-pages"
    CleanDir tempDocsDir
    Repository.cloneSingleBranch "" (gitHome + "/" + gitProjectName + ".git") "gh-pages" tempDocsDir

    fullclean tempDocsDir
    CopyRecursive outDir tempDocsDir true |> tracefn "%A"
    StageAll tempDocsDir
    Git.Commit.Commit tempDocsDir "Update generated slides"
    Branches.push tempDocsDir
)
```

**Comment by halcwb** [comment]
Agree, the ability to provide some description for your targets would be very useful.

**Comment by matthid** [comment]
This might or might not be quite hard to do

**Comment by matthid** [comment]
You can actually set a description on a target via DSL (`Description "Some text"`)
