### ISSUE TITLE
Error running MSBuild 14.0 using /logger switch with Fake logger

### ISSUE THREAD

**Issue by alexfoxgill** [fsharp/FAKE#926]
Hi there,

I am trying to get MSBuild 14.0 up and running on my build server. I downloaded and compiled the [MSBuild source](https://github.com/Microsoft/msbuild) and copied to `C:\Program Files (x86)\MSBuild\14.0\Bin`. From the command line I can run msbuild with some parameters and the build succeeds

```
D:\TeamCity\buildAgent\work\7755c46e2aeb7907>"C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe" MyProject.sln /t:Build /m /p:RestorePackages="False" /p:Configuration="Release"
```

However, when I add the /logger parameter (which is added by FAKE when it runs MSBuild) I see an error:

```
D:\TeamCity\buildAgent\work\7755c46e2aeb7907>"C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe" MyProject.sln /t:Build /m /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"D:\TeamCity\buildAgent\work\7755c46e2aeb7907\BuildScripts\tools\FAKE\tools\FakeLib.dll"
```

> MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Switch: Fake.MsBuildLogger+TeamCityLogger,D:\TeamCity\buildAgent\work\7755c46e2aeb7907\BuildScripts\tools\FAKE\tools\FakeLib.dll

`Microsoft.Build.Framework.dll` is located in the same directory as `msbuild.exe`. I also tried adding it to the same directory as `FakeLib.dll` but the same error occurred

**Comment by forki** [comment]
that is strange. never seen this before

**Comment by alexfoxgill** [comment]
I also tried adding `C:\Program Files (x86)\MSBuild\14.0\Bin` to my `PATH` environment variable, but still no luck

**Comment by alexfoxgill** [comment]
I have a feeling this is something to do with my MsBuild compilation rather than with FAKE. I will investigate further and report back when I find something

**Comment by alexfoxgill** [comment]
I tried downloading a set of precompiled MSBuild binaries and got the same result so perhaps it is something to do with FAKE. I ran out of ideas so had to revert to MSBuild 12.0

**Comment by forki** [comment]
but AFAIK people are using MSBuild 14.

**Comment by alexfoxgill** [comment]
Is there a guide somewhere on how to set it up with FAKE? Perhaps I have it configured incorrectly?

**Comment by myuglyphotos** [comment]
I also am getting errors running with msbuild 14.0, but it works with 12.0 and 4.0. 
 1) Building C:\xx\xxx.sln failed with exitcode 1.
 2) MSB4036: C:\xx\xxx.sln.metaproj(0,0): The "Message"
task was not found.

**Comment by ImaginaryDevelopment** [comment]
I'm getting the logger issue, building locally (not on the build server) with vs2015 installed

**Comment by ImaginaryDevelopment** [comment]
if I do this it works:

```
let fixUpLoggers() = 
        let loggers = Fake.MSBuildHelper.MSBuildLoggers
        let badLogger = loggers |> Seq.tryFind(fun bl -> bl.StartsWith("Fake.MsBuildLogger+ErrorLogger,") )
        match badLogger with 
        |Some bl ->
            let name = bl |> before ","
            let path = typeof<Fake.FSIHelper.FsiArgs>.Assembly.CodeBase |> after "file:///" |> Path.GetFullPath
            Fake.MSBuildHelper.MSBuildLoggers <- 
                Fake.MSBuildHelper.MSBuildLoggers 
                |> List.except[bl]
                |> List.append [name + "," + path]
            ()
        | _ -> ()
    sprintf "MSBuildLoggers:%A" Fake.MSBuildHelper.MSBuildLoggers |> trace
    fixUpLoggers()
    sprintf "MSBuildLoggers:%A" Fake.MSBuildHelper.MSBuildLoggers |> trace
```

which tells it to use the same path as my `FakeLib.dll` that my `.fsx` is referencing.

transforms `MSBuildLoggers:["Fake.MsBuildLogger+ErrorLogger,"C:\Users\User\AppData\Local\assembly\dl3\Z0KL834B.AK5\NDJTXE77.MVE\5f464468\0002b059_45f5d001\FakeLib.dll""]`

into 
`MSBuildLoggers:["Fake.MsBuildLogger+ErrorLogger,C:\TFS\Pm-Rewrite\Source-dev-rewrite\BuildHelpers\tools\FakeLib.dll"]`

**Comment by reidev275** [comment]
having similar issue using  MsBuildHelper from an Asp.Net MVC application.  

Logger path from asp.net is
```
/logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\revans\AppData\Local\Temp\Temporary ASP.NET Files\vs\7a427554\a0b30b33\assembly\dl3\75345b43\279ce6b2_62f1d001\FakeLib.dll"
```

Same code called from a console app yields 
```
/logger:Fake.MsBuildLogger+ErrorLogger,"C:\Dev\CtaBuild\Build.Console\bin\Debug\FakeLib.dll"
```

the console app builds correctly while the web app fails with `MSB1021` that @ImaginaryDevelopment listed above

**Comment by reidev275** [comment]
Because `Fake.MSBuildHelper.MSBuildLoggers` is mutable I tried setting it to `[]` which resolves the error for me.  I assume that setting it to a specific FakeLib.dll would also work but I don't actually need the log.

```
Fake.MSBuildHelper.MSBuildLoggers <- []
Fake.MSBuildHelper.BuildWebsite buildOutput projectFilePath
```

**Comment by matthid** [comment]
Closing old issue. I guess the problem was because of self-compiled version and a workaround is given.
