### ISSUE TITLE
FAKE 4.2 or newer starts with wrong Target

### ISSUE THREAD

**Issue by utopius** [fsharp/FAKE#929]
After updating to FAKE 4.3.1 I got weird behavior regarding the build order.
The resulting build order is calculated correctly showing `Clean` and `Prepare` as first Targets to be executed. 
But then FAKE starts with the Target `Core` instead of the displayed build order, it simply skips `Clean` and `Prepare`.
Fake 4.2 shows the same behavior.
When I switch back to FAKE 4.1 it works correctly and starts with `Clean`. Am I doing something wrong regarding the dependencies or is this a bug? Could this be caused by the new soft dependencies feature?

Here the targets (exemplary):
```
Target "Core" [...]
Target "Thirdparty" [...]
Target "Updater" [...]
Target "Clean" [...]
Target "Prepare" [...]
Target "Product" DoNothing

"Product" <== ["Core"; "Thirdparty"; ]
"Setup" <== ["Clean"; "Prepare"; "Product"; "Updater"]
RunTargetOrDefault "Product"
```
The FAKE output:
```
Shortened DependencyGraph for Target Setup:
<== Setup
   <== Clean
   <== Prepare
   <== Product
      <== Core
      <== Thirdparty
   <== Updater

The resulting target order is:
 - Clean
 - Prepare
 - Core
 - Thirdparty
 - Product
 - Updater
 - Setup
```
And then it starts directly with `Core` instead of `Clean`:
```
Starting Target: Core
```

**Comment by forki** [comment]
I guess it's related to https://github.com/fsharp/FAKE/pull/920 
@jlewicki could you please take a look?

**Comment by forki** [comment]
see #931
