### ISSUE TITLE
Fake.Deploy on mono

### ISSUE THREAD

**Issue by koenmetsu** [fsharp/FAKE#938]
Does Fake.Deploy work on Mono? 

Starting Fake.Deploy.exe on windows immediately writes some output to the console, letting me know it started and on which port and so on.

Starting it on mono (`mono Fake.Deploy.exe`) just gives me "Use mono-service...", no other console output and does not seem to start the webserver. `mono Fake.Deploy.exe /help` seems to work just fine, however.

Am I doing anything wrong? (Notice: I'm *very* new to mono)

**Comment by blair55** [comment]
+1. Did you come up with a work around?

**Comment by koenmetsu** [comment]
@blair55 not yet, have given up on the matter for the time being.

**Comment by dsyme** [comment]
closing old issue in spring cleaning
