### ISSUE TITLE
Method missing since 4.3.0

### ISSUE THREAD

**Issue by drusellers** [fsharp/FAKE#948]
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Microsoft.FSharp.Quotations.FSharpExpr Microsoft.FSharp.Quotations.FSharpExpr.Deserialize40(System.Type, System.Type[], System.Type[], Microsoft.FSharp.Quotations.FSharpExpr[], Byte[])'.
   at <StartupCode$FAKE>.$Program.main@()
```

If I upgrade to anything past 4.2 I start getting this issue. I'm still new to F# so I'm really not even sure what else to check.

**Comment by forki** [comment]
How can I reproduce this?

**Comment by drusellers** [comment]
Duh. SMH. One moment. Example coming up.

**Comment by drusellers** [comment]
```
#r @"packages\FAKE\tools\FakeLib.dll"

open Fake


Target "Test" (fun _ ->
    trace "Testing stuff..."
)

Target "Deploy" (fun _ ->
    trace "Heavy deploy action"
)

"Test"            // define the dependencies
   ==> "Deploy"

Run "Deploy"
```

```
".nuget\NuGet.exe" "Install" "FAKE" "-OutputDirectory" "packages" "-ExcludeVersion" -Version 4.3.0
packages\FAKE\tools\FAKE.exe build.fsx
```

**Comment by drusellers** [comment]
Relavent? https://github.com/fsprojects/ProjectScaffold/issues/53

**Comment by forki** [comment]
![image](https://cloud.githubusercontent.com/assets/57396/9817796/525508b6-58a5-11e5-90b6-c45f52e39b36.png)

**Comment by drusellers** [comment]
Which makes me think its an environment concern on my machine but I'm not sure where to look.

I have VS2013 and VS2015 on my machine

**Comment by forki** [comment]
yes that's really strange and sounds like a FSharp.Core in GAC or something like that

**Comment by drusellers** [comment]
FSharp.Core in the GAC is 2.3.0.0

**Comment by dsyme** [comment]
Closing old issue
