### ISSUE TITLE
bootstrapper script

### ISSUE THREAD

**Issue by naveensrinivasan** [fsharp/FAKE#950]
It would be nice to have a bootstrapper script for fake with the defaults like this http://cakebuild.net/docs/tutorials/setting-up-a-new-project. 

I am trying to use FAKE first time for the build and I am looking at  FAKE scripts in other repos along with build.sh to see what are the best practices.

**Comment by sideeffffect** [comment]
this is exactly what you want:

https://github.com/fsprojects/ProjectScaffold
