### ISSUE TITLE
FAKE caching and copying files

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FAKE#951]
I just found a bit odd behavior which (I suspect) might be due to the new caching that FAKE does.

I had some slides, copied them to a new place and run the build script. I did not change my `build.fsx` (so I suspect the file had the same creation time and hash). When running FAKE, it would behave as if running the script from the old location (which has different `__SOURCE_DIRECTORY__` and so it was showing wrong slides).

As soon as I made a change in `build.fsx`, everything started working fine. Could this be a FAKE caching issue?

**Comment by forki** [comment]
Yes sounds like that. I assume we need to add location to the cache.
