### ISSUE TITLE
Fake.RestorePackageHelper.RestorePackageParams should have MSBuildVersion parameter

### ISSUE THREAD

**Issue by mstyura** [fsharp/FAKE#953]
Fake.RestorePackageHelper.RestorePackageParams should have MSBuildVersion parameter because nuget sometimes choose wrong version of MSBuild and command like RestoreMSSolutionPackages fails to run.

**Comment by mstyura** [comment]
https://github.com/NuGet/Home/issues/1392

**Comment by forki** [comment]
What is nuget doing with MSBuild?

**Comment by mstyura** [comment]
@forki I have no idea, but it somehow invokes msbuild during packages restoring and if it uses wrong version things go wrong especially for UWP projects.

**Comment by forki** [comment]
If you really need to to this, an optional parameter might work. But it's
important to keep it backwards compatible.
