### ISSUE TITLE
Can I choose to use VS 12.0 toolset instead of VS 14.0 toolset?

### ISSUE THREAD

**Issue by soloman817** [fsharp/FAKE#957]
I have a project, which built with FAKE. The project is constructed by VS 2013 (12.0). Then recently I installed VS 2015 (14.0), then the FAKE script starts to generate issues. 

So, here is what I observed.

First, I started a cmd window, and run fake, and I noticed it uses VS 14.0 toolset (such as msbuild 14, F# 4.0):

```
       CoreCompile:
         C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:T
         RACE /main:Tutorial.Cs.Program /highentropyva+ /reference:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA\lib\net40\Alea.C
         UDA.dll /reference:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA.IL\lib\net40\Alea.CUDA.IL.dll /reference:C:\Users\Xiang
```

```
      CoreCompile:
        C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0\fsc.exe -o:..\..\obj\Release\Tutorial.Fs.exe --debug:pdbonly --noframework --define:TRACE
        --doc:..\..\release\Tutorial.Fs.XML --optimize+ --platform:anycpu -r:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA\lib\n
        et40\Alea.CUDA.dll -r:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA.IL\lib\net40\Alea.CUDA.IL.dll -r:C:\Users\Xiang\Docu
        ments\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA.Unbound\lib\net40\Alea.CUDA.Unbound.dll -r:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_
```

The reason I need to stick to F# 3.1 , because in the project, I set it to target F# 3.1 runtime, and if you compile it with F# 4.0 compiler, I found there are some issues that crashes my program.

Then, I started a VS2013 developer command prompt, and I ran the script again, now the interesting thing is, the F# compiler is using F# 3.1, but the msbuild is still 14.0:

```
       CoreCompile:
         C:\Program Files (x86)\MSBuild\14.0\bin\csc.exe /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /platform:AnyCPU /errorreport:prompt /warn:4 /define:T
         RACE /main:Tutorial.Cs.Program /highentropyva+ /reference:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA\lib\net40\Alea.C
         UDA.dll /reference:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA.IL\lib\net40\Alea.CUDA.IL.dll /reference:C:\Users\Xiang
```

```
       CoreCompile:
         C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0\fsc.exe -o:..\..\obj\Release\Tutorial.Fs.exe --debug:pdbonly --noframework --define:TRACE
         --doc:..\..\release\Tutorial.Fs.XML --optimize+ --platform:anycpu -r:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA\lib\n
         et40\Alea.CUDA.dll -r:C:\Users\Xiang\Documents\Projects\AleaGPUTutorial_GitHub\packages\Alea.CUDA.IL\lib\net40\Alea.CUDA.IL.dll -r:C:\Users\Xiang\Docu
```

Although the F# now works fine, but the C# built by msbuild 14.0 csc generated some IL code which is different than msbuild 12.0 csc, and my program will do some reflection checking, that it sees some new IL code and report warning or exception.

Is there a way to switch between different toolset version in FAKE?

**Comment by theskyishard** [comment]
I hit a similar issue on a C#5 project where we have a mix of VS2015 and VS2013 installs. VS2013 builds were failing when the VS2015 guys used some C#6 functionality which can 'downpile' to C#5 because VS2013 doesn't know how to handle that newer syntax.

We fixed this temporarily by forcing FAKE to use the older tools version in msbuild using the function below:

     let SetMSBuildToolsVersion (toolsVersion:Option<string>) =
        trace "Setting MSBuild tools version..."

        match toolsVersion with
        | Some version -> MSBuildHelper.MSBuildDefaults <- { MSBuildHelper.MSBuildDefaults with ToolsVersion = toolsVersion }
        | None -> trace "No MSBuild tools version provided, using default."

**Comment by soloman817** [comment]
@theskyishard  Thanks, `Some "12.0" |> SetMSBuildToolsVersion` solves this problem
