### ISSUE TITLE
RunTargetOrDefault

### ISSUE THREAD

**Issue by wallymathieu** [fsharp/FAKE#960]
One feature I miss from other similar tools is the ability to send several targets to the script. For instance I might want to do a "Clean" and "Pack". Or is the intended philosophy for this runner that you should encode that as a separate task if you need to run it several times?

**Comment by Stift** [comment]
The tool does execute like a chain of targets that may have dependencies on each other. But the intended order of your targets, that you define in your fsx, shoudl guarantee you a certain result.

**Comment by matthid** [comment]
Yes you can have a new Task which depend on all your others.
