### ISSUE TITLE
Feature request: more RegistryHelper functions

### ISSUE THREAD

**Issue by yever** [fsharp/FAKE#966]
I've been using the RegistryHelper to get some paths and I think that it would be helpful to have functions to enumerate subkeys and to access them. Those are provided by ``Microsoft.Win32``, but it would be nice to have FAKE wrappers for them.

I would suggest to wrap the following methods from ``Microsoft.Win32.RegistryKey``:
- ``GetSubKeyNames()``
- ``DeleteSubKey()``
- ``GetValueNames()``

Would you accept a pull request for this?

**Comment by forki** [comment]
Sure.

**Comment by yever** [comment]
Wow, that was quick :)
