### ISSUE TITLE
XUnit2 task failing due to parameter change in console runnner v2.1.0

### ISSUE THREAD

**Issue by madhon** [fsharp/FAKE#977]
the command line parameter maxthreads has changed its format in the xunit.runner.console package v2.1.0 which results in the following error

    Starting Target: XUnitTest (==> All, CompileTest) 
    C:\projects\ostrich\packages\xunit.runner.console\tools\xunit.console.exe "C:\projects\ostrich\binTest\Ostrich.Tests.dll" "-parallel" "none" "-maxthreads" "0" "-appveyor" "-html" "C:\projects\ostrich\binTest\Ostrich.Tests.dll.html"  
    error: incorrect argument value for -maxthreads (must be 'default', 'unlimited', or a positive number)
    Running build failed.
    Error:
    System.Exception: xUnit2 failed for the following assemblies: C:\projects\ostrich\binTest\Ostrich.Tests.dll
       at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
       at Fake.XUnit2Helper.xUnit2(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\XUnit\XUnit2Helper.fs:line 210
       at FSI_0001.Build.clo@41-4.Invoke(Unit _arg4) in C:\projects\ostrich\build.fsx:line 42
       at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483
 
---------------------------------------------------------------------

**Comment by forki** [comment]
We have a special xunit2 task. Please try to use that one.

**Comment by madhon** [comment]
That is the task im using  as below ??

    Target "XUnitTest" (fun _ ->
        !! (testDir + @"\Ostrich.Tests.dll")
          |> xUnit2 (fun p ->
                     {p with ShadowCopy = true; HtmlOutput = true; OutputDir = testDir})
    )

**Comment by forki** [comment]
ah so this is a recent change in xunit2? Can you provide a fix?

**Comment by madhon** [comment]
It changed in August by look of it, my F# skils are low at the moment but will take a look at a fix

Sent via mobile

**Comment by inosik** [comment]
It seems like you're using the old (and deprecated) xUnit2-Task. Try using this one: http://fsharp.github.io/FAKE/apidocs/fake-testing-xunit2.html

IIRC the old xUnit2-Task worked well with the beta version of xUnit 2.

**Comment by madhon** [comment]
Aha, good call ... changing the task has fixed it, thanks
