### ISSUE TITLE
FAKE (4.7.2) breaks with 

### ISSUE THREAD

**Issue by robertpi** [fsharp/FAKE#985]
The following script breaks FAKE (4.7.2):
    #r @"..\packages\FAKE\tools\FakeLib.dll"

    open Fake
    open RegistryHelper

    let configure () =
        let dlls = seq { yield "" } 
        let tabName = sprintf "%s" ""
        for _ in dlls do
            setRegistryValue RegistryBaseKey.HKEYLocalMachine "" "" tabName

The output is:
    C:\code\rfq-hub
    >packages\FAKE\tools\FAKE.exe scripts\build.fsx

    F# Interactive for F# 4.0 (private)
    Freely distributed under the Apache 2.0 Open Source License

    For help type #help;;

    > [Loading C:\code\rfq-hub\scripts\build.fsx]

    scripts\build.fsx(12,65): error FS0971: Undefined value 'tabName : string'

Very strange little bug, if you inline the dlls identifier, it works. If you use a list instead of a sequence it works. If you call some other function than setRegistryValue, it works.

**Comment by forki** [comment]
What?

**Comment by yever** [comment]
I was worried I might have broken something in the merged pull requests #976 and #980, but I haven't changed ``setRegistryValue``. 

So, this issue has nothing to do with the Registry and is only about disappearing identifier weirdness?

**Comment by robertpi** [comment]
No, actually the repo can be reduced to:

    open Fake
    open RegistryHelper
    
    let configure () =
        let dlls = seq { yield "" } 
        let tabName = sprintf "%s" ""
        for _ in dlls do
            Console.WriteLine(tabName)

Definitely not a FAKE problem, it's an issue in FSharp.Compiler.Services.

**Comment by yever** [comment]
Phew :)

I'm wondering: I don't understand FCS very deeply, but I saw that it can't find the binding of identifiers starting with an underscore (or an underscore, for that matter): https://github.com/fsprojects/VisualFSharpPowerTools/issues/1032 and https://github.com/fsharp/FSharp.Compiler.Service/issues/422

Is your issue related to that issue?

**Comment by robertpi** [comment]
Don't think so, the bug occurs whether the for loop uses an underscore or not.

I think it's more like to relate to an optimization tries to convert strings to contants, but does take into account dynamically allocated strings. I say that, as if you change let tableTab to be a string constant, rather than the result of a sprintf, everything works ok.

**Comment by dsyme** [comment]
FCS 1.4.2.3 has been pushed with a fix for this integrated

**Comment by dsyme** [comment]
Closing old issue
