### ISSUE TITLE
Build error locally

### ISSUE THREAD

**Issue by mastoj** [fsharp/FAKE#992]
Just cloned the master repo on Windows and ran `build.cmd`. The build fails with the following exception:

```
Failures:                                                                     
                                                                              
compile csfiles to dll                                                        
» should compile to dll (FAIL)                                                
Fake.MSBuildHelper+BuildException: Exception of type 'Fake.MSBuildHelper+Build
Exception' was thrown.                                                        
   at Fake.CscHelper.Csc(FSharpFunc`2 setParams, FSharpList`1 inputFiles) in C
:\Dev\git\FAKE\src\app\FakeLib\CscHelper.fs:line 125                          
   at Test.FAKECore.compile_csfiles_to_dll.<>c.<.ctor>b__8_2() in C:\Dev\git\F
AKE\src\test\Test.FAKECore\CscSpecs.cs:line 60                                
                                                                              
Contexts: 250, Specifications: 670, Time: 23.77 seconds                       
  666 passed, 1 failed, 3 ignored                                             
Running build failed.                                                         
Error:                                                                        
System.Exception: MSpec test failed on C:\Dev\git\FAKE\test\Test.Fake.Deploy.dll, C:\Dev\git\FAKE\test\Test.Fake.Deploy.Web.dll, C:\Dev\git\FAKE\test\Test.Fake.Deploy.Web.File.dll, C:\Dev\git\FAKE\test\Test.FAKECore.dll, C:\Dev\git\FAKE\test\Test.Git.dll.                                                         
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)             
   at Fake.MSpecHelper.MSpec(FSharpFunc`2 setParams, IEnumerable`1 assemblies)
                                                                              
   at FSI_0001.Build.clo@138-8.Invoke(Unit _arg6) in C:\Dev\git\FAKE\build.fsx:line 139                                                                     
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target)              
```

It says on github that it passes, so it is a little bit weird that it doesn't when I run it locally.

**Comment by bentayloruk** [comment]
I've just had this fail for me too.  In my case, I believe it is caused by there being a space in my username.  The test in question uses `Path.GetTempPath()` and then combines this path with file names and passes to `csc.exe`.  The temp paths are not quoted in the generated command, so `csc` is not invoked correctly.  I will dig into it and PR if I have the time, but thought I'd mention it here too.

**Comment by mastoj** [comment]
@bentayloruk, you might be on something. I didn't do any further investigation, but I do have a space in my username.

**Comment by bentayloruk** [comment]
I'm hacking on a fix at the moment.  Will keep you posted.

**Comment by bentayloruk** [comment]
OK, now works for me.  If you want to try it out, [this branch](https://github.com/bentayloruk/FAKE/commits/fix-992-quote-csc-paths) is the latest from upstream, plus this fix.  This is the fix commit https://github.com/bentayloruk/FAKE/commit/7da8996f147a501768ec987d81d40b159d5c032a

I've just hacked this in and have not reviewed it.  Retiring for the evening, but will submit a PR tomorrow.  *I had to fix this, so I could submit a different PR I want for something else :-)*

**Comment by bentayloruk** [comment]
Given that `Csc` is public and could be in use from scripts that have explicitly quoted the path, I think I'll update to check the state of the provided paths first.  Don't want to break a load of existing scripts with double quoting.

**Comment by bentayloruk** [comment]
@mastoj are you able to run all the MSpec tests in Visual Studio?  `build.cmd` is building and passing tests, but if I use the R# runner or the [MSpec test adapter](https://visualstudiogallery.msdn.microsoft.com/f8d80e41-0a85-4b04-aa41-0bc59dc81a5a) all the tests involving files fail with path issues and `DirectoryNotFoundException`s.  For example:

Test Name:	should find the base dir
Test FullName:	Test.FAKECore.Globbing.TestSample1.when_using_empty_pattern::should_find_the_base_dir
Test Source:	c:\Build\FAKE\src\test\Test.FAKECore\Globbing\TestSample1\FileSetSample1Specs.cs : line 75
Test Outcome:	Failed
Test Duration:	0:00:00

```
Could not find a part of the path 'C:\Users\Bob TheBuilder\AppData\Local\Temp\e8f772a3-c964-4127-8ba3-59758cbbea7e\e8f772a3-c964-4127-8ba3-59758cbbea7e\assembly\dl3\8b1f6ef0\2279a060_3e50d101\Globbing\TestSample1\SampleApp.zip'.
Result StackTrace:	
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at Fake.ZipHelper.Unzip(String target, String fileName) in C:\Build\FAKE\src\app\FakeLib\ZipHelper.fs:line 89
   at Test.FAKECore.Globbing.TestSample1.when_extracting_zip.<.ctor>b__0() in c:\Build\FAKE\src\test\Test.FAKECore\Globbing\TestSample1\GlobbingSample1Specs.cs:line 15
```

**Comment by mastoj** [comment]
I can try to get some time today or tomorrow to test it out.

**Comment by bentayloruk** [comment]
@mastoj thanks.  Would be good to know my setup is borked, I've missed a step, or whether the MSpec test failures are also due to username space issues too.  Just want to know if you are able to run all the MSpec tests from within Visual Studio.

**Comment by forki** [comment]
FYI on my machine VS isn't compiling fake as well. Only build.cmd works.
Need to fix that one day.

**Comment by bentayloruk** [comment]
@forki good to know, thanks!  FAKE is compiling fine for me in VS, I just have 254 failed tests (with 412 passing).  Is that what you have or are you not even actually compiling?

**Comment by forki** [comment]
For me it's not even compiling in VS.

But compile + tests run fine in build. Just send your PRs and we see if
it's working on appveyor and Travis

**Comment by bentayloruk** [comment]
Thanks, will do.  I was just hoping to debug through one of them in VS :-)

**Comment by forki** [comment]
Yeah I think the project files broke on VS update. Maybe they should look
like paket's fsproj files.

**Comment by mastoj** [comment]
Now I get the same result as you @bentayloruk, it builds fine in VS but the mspec tests doesn't run.

**Comment by bentayloruk** [comment]
@mastoj I have the MSpec tests running, using the R# test runner.  I installed the MSpec runner for R# and then had to turn off **Shadow-copy assemblies being tested** in the R# Options (Tools -> Unit Testing).

**Comment by forki** [comment]
is there a way to add the R# settings to the repo?

2016-01-16 23:00 GMT+01:00 Ben Taylor <notifications@github.com>:

**Comment by bentayloruk** [comment]
This share file should fix things for a lot of people using the R# runner.  However, us idiots with spaces in our usernames, will still need PR https://github.com/fsharp/FAKE/pull/1076 to fix this issue.
