### ISSUE TITLE
opencover: add -returntargetcode option

### ISSUE THREAD

**Issue by 0x53A** [fsharp/FAKE#994]
Currently, even if a unittest fails (i.e. the testrunner returns non-zero) opencover returns success.
With the returntargetcode flag it would instead pass through the exit code of the child process.

I can try to extend the Helper and send a PR, but might not be able to do it the next few days.

**Comment by mikeyoon** [comment]
I believe you can pass that flag in via the OptionalArguments in OpenCoverParams.

**Comment by 0x53A** [comment]
Thank you @mikeyoon , I kind of missed that flag.
